### ISSUE TITLE
Solid blocks next to darkwood slabs have really dark lighting on side touching slab. 

### ISSUE THREAD

**Issue by mkaisercross** [TeamTwilight/twilightforest#1003]
Forge version: 14.23.5.2847
Twilight Forest version: 3.10.1013
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Place dark wood slab next to any block (e.g. oak plank)

What I expected to happen:
Solid blocks next to darkwood slabs have normal lighting.

What happened instead:
Solid blocks next to darkwood slabs have really dark lighting on side touching slab.

**Comment by bs2609** [comment]
This:
https://github.com/TeamTwilight/twilightforest/blob/87574e3df3b5e0ccf9e0b0d414e8a231a6bdb0e4/src/main/java/twilightforest/block/BlockTFSlab.java#L23-L29

Needs this:
https://github.com/TeamTwilight/twilightforest/blob/87574e3df3b5e0ccf9e0b0d414e8a231a6bdb0e4/src/main/java/twilightforest/block/BlockTFStairs.java#L17

`useNeighborBrightness` is one of those "gift that keeps on giving" issues - despite fixing it several times, it always manages to sneak back in.

**Comment by Killer-Demon** [comment]
This no longer happens in the 1.16.5 version.
