### ISSUE TITLE
No achievements, no progress 

### ISSUE THREAD

**Issue by EvilARN** [TeamTwilight/twilightforest#1004]
Forge version: 8.0.99.99
Twilight Forest version: 3.11.1021
Link to crash log: sorry i dont know what to paste here

What I expected to happen: I expected a normal progression on my server with a friend

What happened instead: But when I made the progress I did not receive the achievements and it prevents me from progressing

**Comment by Drullkus** [comment]
Mojang problem; fixed on newer versions of Minecraft
