### ISSUE TITLE
The portal inside twilight forest has been destroyed, how can I get back out?

### ISSUE THREAD

**Issue by SteamChpock** [TeamTwilight/twilightforest#1009]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:

**Comment by quek04** [comment]
you can find the materials to make a portal  in the twilight 
ps this isn't the place for a problem like this

**Comment by SteamChpock** [comment]
> а

Thanks for the hint, but I use the sevtech ages build and the portal creation has been changed there, and I do not know where else to turn for help

**Comment by Tamaized** [comment]
That is on the pack makers then, something they need to consider. This isn't our issue.
