### ISSUE TITLE
spooky forest doesn't generate unique graveyard structure

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#1012]
**Forge version: Forge version: 1.12.2 - 14.23.5.2838
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.11.1021**

**Steps to reproduce:**
1. make a new world and after exploring, despite finding some spooky forests, their unique structure that has its own icon on the map never generates.
That said, I did make a new world to test it out after experiencing this issue on a different world, and ironically in the new test world I spawned right next to a spooky forest with the structure. I'm not sure what's causing the problem or if it has something to do with the world I'm experiencing it on.

**What I expected to happen:** When I see spooky forests generate in my world, they would have their unique structure spawned in them, with the icon on the map and the physical structure in the world with the spawners and loot and stuff.

**What happened instead:** As I'm exploring around I can see spooky forests generate, but in every single one, the structure that actually generates in it is not the graveyard one. Instead its like a naga courtyard or a lich tower or hedge maze or some structure that's not biome specific.
The pic I have attached is of the magic maps I was exploring in my survival world. There is 24 fully explored magic maps here, and in all of them you can see that where there's a spooky forest, a structure that's not biome specific generates instead of the unique spooky forest structure. I circled every situation of this in **_yellow_** to show it, and literally every spooky forest in my world that I've ever found has this issue. I have never found the spooky forest's unique graveyard structure.

There's one exception on the magic map that my portal is in, which has terrain in it that was generated a few updates ago. In the world there is a quest grove biome in the location where the map says there's a spooky forest with the unique structure. The map was accurate before I updated to the build listed above, but when I used that build for the first time and I went in that area in my world, the map started overwriting only that biome and a couple of the ones around it.. guess it has something to do with different seeds on different updates or whatever but the point is that the structure listed on the map isn't there. I circled this in _**light blue**_ just to identify it.

![spooky forest generation problem](https://user-images.githubusercontent.com/44104096/109380744-c3360880-78a4-11eb-8f1d-ceb820601fc4.jpg)

**Comment by Tamaized** [comment]
I realized a bit late this was an issue posted for 1.12, not 1.16.

Anyway, the biome DOESNT have a unique structure, at least not yet. The graveyard is a generic feature gen, it does not appear on the map.

However it not spawning was partially fixed (it gens, just not correctly) in c0f0b8f6153810921fd551624dd536273ab33b20 for 1.16 so im closing this

**Comment by Megalodab** [comment]
> 
> 
> I realized a bit late this was an issue posted for 1.12, not 1.16.
> 
> Anyway, the biome DOESNT have a unique structure, at least not yet. The graveyard is a generic feature gen, it does not appear on the map.
> 
> However it not spawning was partially fixed (it gens, just not correctly) in [c0f0b8f](https://github.com/TeamTwilight/twilightforest/commit/c0f0b8f6153810921fd551624dd536273ab33b20) for 1.16 so im closing this

If the graveyard doesnt appear on the map, then what was the icon I circled in blue? because I didn't see that one either. The icon there is grey and black and looks like a face.

**Comment by Tamaized** [comment]
No idea it doesn't exist in our assets, an addon mod? But I'm telling you now, as the one who implemented both the biome and graveyard singlehandedly, it is NOT a structure and has no icon. It is a biome feature like druid huts.

https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/resources/assets/twilightforest/textures/gui/mapicons.png

**Comment by Megalodab** [comment]
Interesting. I am pretty sure I've seen it in other worlds too, marking a spooky forest. In the world I took that screenshot and did that exploring in, the twilight forest was the only mod I had going, besides some other QoL and performance things. but no other mods that change world gen. ima go run a new twilight world and see if i can find it again and check it out.

**Comment by Tamaized** [comment]
It's most likely a medium hill who's icon was messed up somehow

**Comment by Megalodab** [comment]
yo that might be right actually because the actual terrain over there is a quest grove like i mentioned above. looks like a small hill overlapping a quest grove icon in background

**Comment by Megalodab** [comment]
I think ur right. just loaded up another world and the first forest I found didn't have the icon, instead it had a small hill. Note that I tested this in the same 1.12 version I found this in.

i guess that was just because of the map problemos I had when i went to the new update.
