### ISSUE TITLE
Logged Error.

### ISSUE THREAD

**Issue by GhastCreepypasta** [TeamTwilight/twilightforest#1014]
Forge version: Minecraft 1.16.5 Forge 36.0.43
Twilight Forest version: 4.0.xxx
Link to error log: https://gist.github.com/GhastCreepypasta/c40679d418bad993a048c9f3ef88b9a2

**Comment by GizmoTheMoonPig** [comment]
fixed as many of these as I could, the only ones that are left are about the keepsake casket, door item models, and transwood door and trapdoor. Cant currently fix those ones due to missing textures, so I'm closing this issue now. Thanks for reporting :D
