### ISSUE TITLE
Info Error and Errors in Log

### ISSUE THREAD

**Issue by BurnutsGaming** [TeamTwilight/twilightforest#1016]
Forge version: 1.16.5 - 36.0.43
Twilight Forest version: 4.0.363
Link to crash log: N/A No crash reported.

Steps to reproduce:
1. Launch Minecraft

What I expected to happen:
It should show. VERSION: 4.0.363
What happened instead:
It showed. VERSION: NONE

Link to Error Log: https://gist.github.com/GhastCreepypasta/c40679d418bad993a048c9f3ef88b9a2
Error logged by: GhastCreepypasta

**Comment by Tamaized** [comment]
#1014
