### ISSUE TITLE
1.16.5 Crash with Optifine

### ISSUE THREAD

**Issue by nadecancode** [TeamTwilight/twilightforest#1017]
Forge version: 36.0.43
Twilight Forest version: 4.0.364
Link to crash log: 
https://paste.gg/p/anonymous/a9e8078aa0e641a187bbd594a2e42c31

Steps to reproduce:
1. Install the mod
2. Join the server

What I expected to happen:
The player can enter the world normally

What happened instead:
After few ticks of rendering, player's world crashed

**Comment by Tamaized** [comment]
This is a problem with Optifine, remove it or turn on Smart Animations before installing TF

**Comment by 1378906248** [comment]
Building spawns sometimes overlap, resulting in missing buildings
