### ISSUE TITLE
Understanding Magic Map Behavior

### ISSUE THREAD

**Issue by sibomots** [TeamTwilight/twilightforest#1018]
**Forge version:** 1.12.2-14.23.5.2838
**Twilight Forest version:** (this is the build number) 1.12.2-3.11.1021
**Link to crash log:**

No crash. Just a question about intended behavior.

Again -- **this is not a report of a defect.** Just trying to understand what the actual intended behavior is of the mod -- with respect to magic map behavior in Multiplayer (server) environment vs. Single Player. 

**Steps to reproduce:**
One of our contributors found an issue and I'm confused how to interpret it.
Here's our write up (We're trouble shooting a mod pack and maintain some Issue tracking until we're ready to spin the version).

https://github.com/sibomots/FooFarm/issues/20

**What I expected to happen:**

The expectation is that using the mod in a server environment, the map would work similiarly as it does in Single Player.

**What happened instead:**

The player marker doesn't appear in the map when made in Server mode.

If someone can pull me aside and explain what the intended behavior is, we can start looking for other things to investigate.
I'm not just not sure *if the map is supposed to work the same as it does in Single Player as Multiplayer*

Thank you.  Love the mod!

**Comment by Tamaized** [comment]
The marker is supposed to appear on servers yes

**Comment by sibomots** [comment]
Hmm.  OK.   We will take a good look at the mods we have then and see if we nerfed something with other mods interfering with that behavior.  Thanks for the feedback.  Good to know.

**Comment by Andromander** [comment]
Going to mark this as closed as the question has been answered. Feel free to reopen if this is still occurring, especially if TF is the only mod installed.
