### ISSUE TITLE
crash minecraft

### ISSUE THREAD

**Issue by RJHG56** [TeamTwilight/twilightforest#1019]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: https://gist.github.com/RJHG56/feee566dab510d831ec6f517f5286064

Steps to reproduce:
1. play minecraft

What I expected to happen:
to open minecraft
What happened instead:
crash

**Comment by Tamaized** [comment]
Caught exception from CraftTweaker2 (crafttweaker)
