### ISSUE TITLE
Suggestion [Discord said to use the issue tracker for these too]

### ISSUE THREAD

**Issue by zombies134** [TeamTwilight/twilightforest#1021]
I noticed that in the current Curseforge build, the Armored Giant uses the player's texture, I feel like that could make for a unique enemy, the Doppelganger, maybe kitted out in the optimal gear for the Final Castle?

They should probably have around 150 hp, and perhaps when they reach half health they can summon minions? Not sure what they'd summon though.

**Comment by Killer-Demon** [comment]
As it stands, we have a good outline for what we're looking to do with the Final Castle. This, unfortunately, doesn't quite align with that and it might feel too much like a copy of the currently existing Giants.
