### ISSUE TITLE
Massive Dupe Bug

### ISSUE THREAD

**Issue by JimmyRockSlayer** [TeamTwilight/twilightforest#1022]
Forge version: 14.23.5.2854
Twilight Forest version: 3.11.1021
Link to crash log: NA
Steps to reproduce:
1. Place Input item into Uncrafting Table
2. Create an item, or block, with the uncrafted recipe
3. Shift right-click the final item to keep both the final product and input item
3a) Add additional material in the crafting menu to receive twice the items. [(n-1) *2]
#
What I expected to happen:

I expected just to receive the final item without keeping the input items.

What happened instead:

As stated above and demonstrated in the video below.

[Demonstration Video](https://youtu.be/YmTh_vseO-Y)

**Comment by GizmoTheMoonPig** [comment]
should be fixed in the newest 1.16 beta. If not, please reopen
