### ISSUE TITLE
[suggestion/bug 1.16.5] compatibility improvements

### ISSUE THREAD

**Issue by Maxion78** [TeamTwilight/twilightforest#1024]
I think this mod need to be more compatible with other: it must prevent others mods spawning structures, vegetation, ... from other mods. It would also be nice if it was compatible with some shaders.
Some incompatibility issues : ext caves, abnormal environmental.

**Comment by Tamaized** [comment]
No, that is up to the offending mods to control where their own structure/features spawn.

**Comment by Quadruplay** [comment]
ppl from abnormals discord are saying it's tf's fault bc the biomes are classified incorrectly (environmental adds stuff to any biome classified as forest)

**Comment by Tamaized** [comment]
They can add blacklists, our biomes ARE forests. It's literally called Twilight Forest.
