### ISSUE TITLE
Beta build error

### ISSUE THREAD

**Issue by dhunter49** [TeamTwilight/twilightforest#1028]
Forge version: 36.1.2
Twilight Forest version: 4.0.398
Link to crash log: https://pastebin.com/1QSwxCb2

Steps to reproduce:
1. Start Minecraft
2. Generate a world

What I expected to happen:
Go to the world 

What happened instead:
After loading and seeing 1 chunk it says Saving game and Minecraft crashes

**Comment by GizmoTheMoonPig** [comment]
Yeah, my bad. Working on a fix right now. Sorry!

**Comment by GizmoTheMoonPig** [comment]
Actually, looking at the crashlog, you seem to have optifine installed. Please get rid of optifine, or refer to #1017 to fix it.
