### ISSUE TITLE
Suggestion: expanded dusts (1 per core)

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1029]
![transform_powder_plus](https://user-images.githubusercontent.com/23658767/112227915-60fbc980-8bfe-11eb-8e2d-72a89f0e4f43.png)

I made this for fun and discussion happened so this is me documenting it:

The idea was had to add a powder similar to the transformation powder for every tree core (time, sorting, mining), as the tree of transformation is associated with the transformation powder.

Time powder: acts as a buffed bonemeal, bonemealing everything in a radius (3x3, 5x5, etc) instead of the one block its used on like vanilla bonemeal. Should probably be limited to crops of the same type or just crops period so it doesn't bonemeal grass as well as a crop. Should also be able to instantly grow a sapling instead of requiring a few (as bonemeal typically requires a few to grow a sapling).

Sorting powder: sorts a chest that it is used on, the method used to sort tbd. Androsa also had the awesome idea to have it "linger" on the chest its used on as if that specific chest was in the vicinity of a sorting core, might be too close to the core's own ability but that's not for me to decide. Could also be used on the player's inventory or any backpack or other internal inventory they are carrying.

Mining powder: this one has two ideas. It could either act as a repair item for the ore magnet and/or increase its durability, OR it could convert any ore its used on into a block of said ore (gold ore transformed into gold block, etc.). If the former route is taken could also act as an instant-repair item for pickaxes and shovels to fit with the mining theme.

**Comment by Killer-Demon** [comment]
We've come to the conclusion that adding these is not within the scope of things we're wanting to do and/or are planning, so I'll be closing this one.
