### ISSUE TITLE
TW + Optifine bug (naga and hydra body parts are missing)

### ISSUE THREAD

**Issue by TiopTcz** [TeamTwilight/twilightforest#1030]
Forge version: 36.1.0 (1.16.5)
Twilight Forest version: 4.0.400 (1.16.5)
Link to crash log: Does not crash

Steps to reproduce:
1. Play TW with optifine
2. Find hydra or Naga
3. See the bug

What I expected to happen:
Seeing their full bodies

What happened instead:
Naga was missing her tail pieces while hydra was missing her heads

**Comment by Tamaized** [comment]
If this is due to optifine then there's nothing we can do

**Comment by wolfkidsounds** [comment]
I'm currently having the same issue but on 1.12.2 not running optifine.

Twilightforest: 3.11.1021
Forge: 14.23.5.2854

The Naga is missing body parts, optifine is not installed.

---

Edit:

- Fixed it by disabling "entity culling mod".
