### ISSUE TITLE
Ur-Ghast transitions into Crying Phase after being attacked by the Ghast Trap

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#1031]
Forge version: 36.1.0
Twilight Forest version: 4.0.403
No Crash Log

Steps to reproduce:
1. Fight in Survival Mode
2. Attack repeatedly when grabbed by Ghast Trap

What I expected to happen:
Ghast transitions into regular state after being trapped, shooting fireballs continuously
What happened instead:
Ur Ghast transitions into crying state immediately instead

**Comment by Tamaized** [comment]
Unable to reproduce
