### ISSUE TITLE
Enhancement: Have the inability to break blocks and damage mobs be a semi-permanent potion effect

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#1033]

**Comment by Tamaized** [comment]
what, why?

**Comment by GizmoTheMoonPig** [comment]
making it a potion effect would allow people to bypass it one way or another, which I don't find to be a good idea. 
If you're asking for this so people can make maps with it or whatnot, that's out of scope for the mod. Another mod can easily replicate this effect through forge events
