### ISSUE TITLE
Missing Textures for some items

### ISSUE THREAD

**Issue by ModernGamingWorld** [TeamTwilight/twilightforest#1035]
Forge version: 36.1.4
Twilight Forest version: (this is the build number) MC 1.16.5 - 4.0.412

Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1.  Launch game and see missing Textures for the following (Canopy, Twilight Oak, Mangrove, Darkwood, Timewood, Transwood, Minewood, and Sortingwood doors are missing Textures in JEI
2. Keepsake Casket is missing its texture in JEI
3. Transwood Trapdoor is missing its Texture in JEI

What I expected to happen:
A Fix for the broken Textures

What happened instead:

**Comment by GizmoTheMoonPig** [comment]
Doors and the trapdoor are intentional, casket will be getting its model soon

**Comment by Avem231** [comment]
So TF wood doors aren't properly implemented yet?

**Comment by GizmoTheMoonPig** [comment]
only the item models dont exist, the door blocks themselves all work fine (except transformation). The item models will come to the game eventually, theyre still being worked on

**Comment by GizmoTheMoonPig** [comment]
after all this time, this is finally no longer an issue in 1.17! We wont backport these changes, so if you want to have the textures in earlier versions, you'll need to make a resource pack for them.

**Comment by Tamaized** [comment]
> you'll need to make a resource pack for them.

Not possible in 1.12. it ***requires*** some code to tell the items to point at a specific model file.
