### ISSUE TITLE
[1.16.5] Special TF Tree Cores

### ISSUE THREAD

**Issue by HockeyZman2000** [TeamTwilight/twilightforest#1037]
Forge version: 1.16.5-36.1.0
Twilight Forest version: 1.16.5-4.0.412

I'm not sure if this is already known and being worked on or not, but all of the special "tree cores" cease to function.
Steps to reproduce:
1. Start a world and grow these trees, right click on core.

What I expected to happen:

Timewood Core to speed up crops and Tile Entities.
Heart of Transformation to slowly change the biome to Enchanted Forest
Minewood Core to pull ores from underneath it.

All as specified on the wiki.

What happened instead:

Nothing occurs besides audio and blockstate change when right-clicked.

**Comment by GizmoTheMoonPig** [comment]
all cores except the transformation should work as intended. They dont happen immediately, the effects happen over time.

**Comment by HockeyZman2000** [comment]
Okay thanks. Maybe they are just slower than I remember them being in 1.12
