### ISSUE TITLE
Missing texture on Naga

### ISSUE THREAD

**Issue by Hadies-Alchemist** [TeamTwilight/twilightforest#1038]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. find a naga boss

What I expected to happen: to see the whole naga boss

What happened instead: you can only see its head
![2021-04-04_19 36 24](https://user-images.githubusercontent.com/59758314/113535731-19275b80-9589-11eb-8e92-bd868aa0b5d1.png)

**Comment by GizmoTheMoonPig** [comment]
are you using optifine?

**Comment by Hadies-Alchemist** [comment]
yes, Is that the issue?

**Comment by GizmoTheMoonPig** [comment]
indeed. Optifine ruins some things in the mod. We cant fix these issues sadly. For the full experience I would recommend removing it.

**Comment by Hadies-Alchemist** [comment]
good to know.

**Comment by TheDarkRisen** [comment]
It will be fixed in future? Or it impossible?

**Comment by Tamaized** [comment]
We can't fix it, it's an optifine issue.

**Comment by TheDarkRisen** [comment]
Oh, it so sad .(( I will try another optifine version, maybe it will help.

**Comment by TheDarkRisen** [comment]
And another question, Naga breaking blocks of labirint and surroundings , its normal?

**Comment by Tamaized** [comment]
Yes
