### ISSUE TITLE
Druid huts sometimes generate incorrectly

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [TeamTwilight/twilightforest#1040]
Reported on the TF discord. User didnt have a github, so im putting the issue here. Screenshot below is evidence. 
![image](https://user-images.githubusercontent.com/67468252/113536009-40365b00-9592-11eb-9be4-3a0bc392f97c.png)

**Comment by GizmoTheMoonPig** [comment]
seems to be fixed now in 1.17 thanks to drull

**Comment by Drullkus** [comment]
Fixed via 02f26fa9
