### ISSUE TITLE
Massive TPS/FPS lag in the overworld I think?

### ISSUE THREAD

**Issue by Neko2n** [TeamTwilight/twilightforest#1041]
Forge version: 1.16.5-36.1.0
Twilight Forest version: 4.0.412
Link to crash log: No crash

Steps to reproduce:
1. Enter a world with twilight forest installed and Optifine to see the tickrate bar chart.
2. Look at the bar chart
3. 
![tpsgraph](https://user-images.githubusercontent.com/43053729/113546262-81ce0280-95a0-11eb-86b7-e46b3c61f307.png)

What I expected to happen: Not to hit a constant ~90ms average time between ticks

What happened instead: Tps hit bedrock

I have a spark profiler I used to be able to tell it was Twilight Forest. Issue does not happen in my modpack without Twilight Forest installed. I do have 260+ extra mods installed, so it's most likely a compatibility issue like most of my issues.
Here's the profiler's results:
![tflag](https://user-images.githubusercontent.com/43053729/113546518-00c33b00-95a1-11eb-8369-f365b407e5e9.png)

Here's my latest.log:
[latest.log](https://github.com/TeamTwilight/twilightforest/files/6256754/latest.log)

And my debug.log:
[debug.log](https://github.com/TeamTwilight/twilightforest/files/6256755/debug.log)

Edit: I may still not fully understand how the Optifine bar chart works, as I've noticed it says 20 tps despite the bar being fully red. My entire game feels like it's running in slow motion, though, and my fps is less than half of what it was before I installed this mod. Not sure if that has anything to do with this issue, so the report still stands.

Another edit: after I finally managed to get into the dimension after dealing with server lag, I've noticed the lag only happens in the overworld. My fps and tps return to normal when I'm in the Twilight Forest. Wtf? Why would spark tell me this mod's causing issues in the overworld, but the mod's dimension is less laggy than the overworld?

**Comment by Tamaized** [comment]
Spark is showing our method due to it being called from like 20 sources every tick, each entity loaded will call it multiple times each per tick as well.

I can improve it slightly but there's really no better way to go about it honestly code wise.

We've had the patch on our own test server for a few months now and it's caused no problems with upwards of 12 players online at once.

**Comment by Tamaized** [comment]
Going to safely close this as testing with this change seems to have solved it cf1f9c3fda5a0c6fa1a9a994eb0059652e77dd0b
