### ISSUE TITLE
Instant Crash when creating new world

### ISSUE THREAD

**Issue by zachsai** [TeamTwilight/twilightforest#1045]
Forge version: 
Twilight Forest version: 4.0.412
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
https://gist.github.com/celsiusqc/26aa5991eb8241c5c918a3661501ab09
Crash report and Debug.log
Steps to reproduce:
1. 
Create new world
What I expected to happen:
Not crash
What happened instead:
Crashed

**Comment by Tamaized** [comment]
duplicate #1017
