### ISSUE TITLE
Shader rendering Funky for more than 1 shader, which points towards twilight forest bad skybox textures

### ISSUE THREAD

**Issue by zachsai** [TeamTwilight/twilightforest#1046]
Forge version: 
Twilight Forest version: 4.0.412
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Crash report and Debug.log
Steps to reproduce:
1. apply shaders
What I expected to happen:
not have funky shader look
What happened instead:
funky shader look
![image](https://user-images.githubusercontent.com/63996164/113643909-6e2ea480-9651-11eb-9e3e-2b0603fcab09.png)
(happens with multiple different shaders)

**Comment by celsiusqc** [comment]
![Uploading image.png…]()

**Comment by zachsai** [comment]
![image](https://user-images.githubusercontent.com/63996164/113643985-a209ca00-9651-11eb-86ab-6472a9cf13df.png)

**Comment by Tamaized** [comment]
This has always been an issue with shaders, shaders do not support custom sky boxes. Use a shader that doesnt affect the sky.
Also: duplicate #854

**Comment by Quantumrage10** [comment]
i'm having the same issue. anyone figured out how to fix this problem client side yet?

**Comment by Azar2477** [comment]
Also this issue https://github.com/TeamTwilight/twilightforest/issues/1199 because the shaders cause this and I don't know what shaders did they use.

**Comment by Tamaized** [comment]
These are two separate issues, yes shaders are involved but it's two totally different sections of the game
