### ISSUE TITLE
Druid Skeletons are super fast and their projectiles can be blocked with shields.

### ISSUE THREAD

**Issue by SatDog92** [TeamTwilight/twilightforest#1049]
Forge version: MC 1.16.5 - 36.1.0
Twilight Forest version: 4.0.412

What I expected to happen: Druid Skeletons's walk speed should be similar to the one of vanilla skeletons. Their projectiles also shouldn't be blocked by shields (verified this with the "stable" 1.12.2 version, where these Druid Skeletons behave as intended).

What happens instead: they walk super fast (it's actually funny, though), and their projectiles can be blocked with shields, with durability not depleted at all. Not sure if this should be changed to projectiles being able to be blocked but with durability depletion, or left as it is from the 1.12.2 version.

**Comment by GizmoTheMoonPig** [comment]
Speed and projectile issues are fixed. I also just wanted to let you know that TF comes packaged with a parry mechanic. If you hold up your shield at a good time you can still deflect druid projectiles, but they will hurt you if the shield is up too long. You can disable this in the config if you wish.
