### ISSUE TITLE
Not running on a server

### ISSUE THREAD

**Issue by CoralineKoralina** [TeamTwilight/twilightforest#1051]
Forge version: 
Twilight Forest version: (this is the build number) 1.16.5-4.0.412-universal
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
just incomplete set of tags, contact operator etc
Steps to reproduce:
1. 

What I expected to happen: joining the server

What happened instead: disconnected because of incomplete set of tags

**Comment by Tamaized** [comment]
Show both client and server logs when this happens
