### ISSUE TITLE
[1.16.5] Issues with structure generation

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [TeamTwilight/twilightforest#1054]
I noticed a lot of these issues when flying around a test world that I made. 
I thought it would be easier to put all of these on one issue page, but if you want me to split them up into separate issues then I can do that.

Forge version: 36.1.4
Twilight Forest version: 4.0.412
Link to latest log: https://pastebin.com/V2zPkBwy

Steps to reproduce:
1. Open Minecraft with Twilight Forest installed and start a new world.
2. Create a portal to the Twilight Forest and go through it.
3. Locate the respective structures until the issues occur.

What I expected to happen:
The structures would spawn correctly.

What happened instead:
A few issues with structure generation that are shown below:

Naga Courtyard wall pieces sometimes generate with incorrect rotation. Other smaller structures such as trees and druid huts can also spawn inside of Naga Courtyards:
![2021-04-06_23 01 53](https://user-images.githubusercontent.com/64381954/113786342-da340a00-9730-11eb-8dac-eaa1d252733e.png)

Double chests in certain structures generate as 2 single chests instead and paintings sometimes pop off walls during generation:
![2021-04-06_23 03 10](https://user-images.githubusercontent.com/64381954/113786442-0c456c00-9731-11eb-8973-a67f1ab026d7.png)

Castle Pillars on bridges in the final castle are sometimes incorrectly rotated:
![2021-04-06_23 06 43](https://user-images.githubusercontent.com/64381954/113786549-46af0900-9731-11eb-9b61-bbc96f54d0a6.png)

This particular tower in the final castle can rarely generate like this:
![2021-04-06_23 07 58](https://user-images.githubusercontent.com/64381954/113786712-9e4d7480-9731-11eb-924e-d91c4cd2193a.png)
![2021-04-06_23 08 21](https://user-images.githubusercontent.com/64381954/113786790-c76e0500-9731-11eb-94b1-5f46ae26c850.png)

Mobs can spawn on the outside of their respective structures such as hollow hills:
![2021-04-05_21 51 02](https://user-images.githubusercontent.com/64381954/113786866-e8cef100-9731-11eb-92a0-57fd9b6f73f0.png)

The Final Castle can rarely generate cut off if it spreads into the Thornlands, like this:
![2021-04-05_21 48 43](https://user-images.githubusercontent.com/64381954/113787627-46b00880-9733-11eb-9c79-f02e4a7c0655.png)

There's also this issue with cave generation which is caused by Yung's better caves, which I thought you should know about: https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/120

**Comment by Tutegamer3101** [comment]
alguien sabe que hacer para que la hydra y la naga tengan cuerpo, por que no me deja ver sus cuerpos, no tengo optifine ni shaders.

por favor ayuudaa
![5bz361malr911](https://user-images.githubusercontent.com/82085978/113839599-37967e00-9766-11eb-8c68-55b1641777cc.png)

**Comment by The-Bernician-Lamb** [comment]
Two more issues relating to structure generation (Forgot to include these in the main post, Sorry):

The Dark forest canopy can generate inside of the dark tower:
![2021-04-08_18 44 26](https://user-images.githubusercontent.com/64381954/114074915-d4f3ce00-989c-11eb-871b-015895274c7c.png)

The furnaces in this particular dark tower room, all generate facing backwards:
![2021-04-08_18 47 52](https://user-images.githubusercontent.com/64381954/114075073-053b6c80-989d-11eb-9363-df6397defc24.png)

**Comment by GizmoTheMoonPig** [comment]
Just leaving a note here that the only ones left after my fixes are dark leaves genning in dark towers, castles cutting off, and mobs genning out of place

**Comment by PechayClub** [comment]
This issue might be relevant to this pinned issue.
TeamTwilight/twilightforest#718

**Comment by Tamaized** [comment]
It is not

**Comment by PechayClub** [comment]
Ok then. Because the generation in the stronghold is glitched.

**Comment by Tamaized** [comment]
Are any of these still an issue?

**Comment by GizmoTheMoonPig** [comment]
the only ones are the castle generation issues and apparently the hollow hill spawns being outside the hill
