### ISSUE TITLE
headless hydra

### ISSUE THREAD

**Issue by Tutegamer3101** [TeamTwilight/twilightforest#1055]
Forge version: I don´t know sorry

Steps to reproduce:
1. open Minecraft and spawn a hydra

What I expected to happen:I was hoping it would look like the videos I have seen for a long time

What happened instead: I found a hydra without all three heads

If anyone knows how to solve this bug please put it in the comments
postscript: i don't have optifine or shders installed

**Comment by Tamaized** [comment]
Show your latest.log

**Comment by MilerLite** [comment]
Same thing happens to me, my Naga also doesnt have a body, only a head. Along with my server repeating a message "twilight-forest common.toml is not correct. Correcting"

**Comment by TheOnlyMann** [comment]
remove optifine. optifine has multipart entity rendering issues. 
no, twilight devs cannot do anything about it. best is to submit a bug report on the optifine devs.
