### ISSUE TITLE
Druids track endlessly and ignore armor

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#1060]
Forge version: Forge 1.16.5 36.1.0
Twilight Forest version: 1.16.5-4.0.426

The infinite Druid speed bug was fixed, but they still track the player endlessly. Their base damage also pierces armor, which is too strong given how brutal their poison is, and how fast their attack speed is. Their damage should be changed to not ignore armor, and their poison or attack speed should be heavily nerfed.

**Comment by Tamaized** [comment]
Magic damage ignores armor
