### ISSUE TITLE
Death Tomes pierce armor

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#1063]
Forge version: Forge 1.16.5 36.1.0
Twilight Forest version: 1.16.5-4.0.426

Death Tome damage ignores armor, which makes them extremely strong for a common mob that spawns in groups inside Lich Towers. They also inflict strong slowness on top of this.

**Comment by Tamaized** [comment]
It's magic damage...

**Comment by SeaOfPixels** [comment]
Then their damage should be nerfed to 2hp (1 heart) on easy, 3hp (1.5 hearts) on normal, and 4hp (2 hearts) on hard. They are too strong atm for being a random encounter in the 2nd dungeon.
