### ISSUE TITLE
Mobs in locked progression areas should not be invincible

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#1064]
Forge version: Forge 1.16.5 36.1.0
Twilight Forest version: 1.16.5-4.0.426

Mobs in locked areas should not be invincible, because the Kobolds spawned from entering those locked areas (the ones with written books) often mean instant death given their speed and how the player will be affected by the locked area effects on top of being rapidly damaged. Mobs in these areas should always be attackable, regardless of progression. Mobs usually have green particles around them when they're invincible, this should be removed.

**Comment by Tamaized** [comment]
No
