### ISSUE TITLE
Knight Phantoms are too strong

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#1065]
Forge version: Forge 1.16.5 36.1.0
Twilight Forest version: 1.16.5-4.0.426

Knight Phantoms (specifically the ones carrying Knightly Swords), do extreme amounts of damage (8 hearts aka 16hp through diamond armor on hard mode), and can sometimes do their charge attack multiple times. Additionally, the damage upon running into one of the phantoms is too high given that they knock the player into each other dealing even more damage. The damage from these instances are way higher than the damage from the thrown axes and pickaxes, implying that this *is* a bug or perhaps a result of poor damage balancing.

The damage from Sword Knight Phantom charge attacks, and the damage from physical contact with the Knight Phantoms, should absolutely be nerfed.

**Comment by Tamaized** [comment]
Knightly does more damage too armored targets this is intentional

**Comment by GizmoTheMoonPig** [comment]
As tama said, the large amount of damage is intentional. Knightmetal weapons do more damage to armored targets, so youre gonna take more damage if you have more armor. All the damage is done through the sword
