### ISSUE TITLE
Regarding the OptiFine warning on launch

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#1066]
Forge version: Forge 1.16.5 36.1.0
Twilight Forest version: 1.16.5-4.0.426

The OptiFine incompatible message upon launching 1.16.5 OptiFine should be changed. It should still say the mod causes issues, however the message should also advise users to "enable 'Smart Animations' in your OptiFine settings to avoid crashes". Enabling smart animations in the OptiFine settings stops the game from crashing upon loading a world with both OptiFine 1.16.5 and Twilight Forest 1.16.5; this should be communicated to players.

**Comment by Tamaized** [comment]
Why, Smart Animations doesn't prevent any crash. There currently isn't any known crash but the warning is there incase one does happen...

**Comment by SeaOfPixels** [comment]
There is a crash when loading a world with both OptiFine and Twilight Forest with smart animations off. Turning them on allows the player to enter just fine. This should absolutely be included in the warning message.

**Comment by Tamaized** [comment]
There is not

**Comment by SeaOfPixels** [comment]
Bug wasn't fixed, don't know what to tell you. Just tried it in the latest release after the supposed "fix", still happens. I advise changing the launch message as I said so people stop bothering you about the incompatibility.

**Comment by fxcy1** [comment]
How do I turn on 'Smart Animations' in the Optifine settings? I don't see it.

**Comment by KondiU** [comment]
I know I'm 4 months late but it's in Video Settings>Performance

**Comment by Tamaized** [comment]
It should be noted that this is volatile, for some the setting needs to be off, for others it needs to be on, and sometimes the setting doesn't matter at all and will crash no matter what. It's highly system dependent. If it works for you then great! Otherwise, sorry to hear.

**Comment by Nazeeh114** [comment]
is this issue fixed yet
