### ISSUE TITLE
1.16.5 server crash

### ISSUE THREAD

**Issue by Daejangnamu** [TeamTwilight/twilightforest#1070]
[crash-2021-04-11_19.18.38-server.txt](https://github.com/TeamTwilight/twilightforest/files/6291534/crash-2021-04-11_19.18.38-server.txt)
Forge version: 36.1.4
Twilight Forest version: 4.0.426

**Comment by FullMetalMaster** [comment]
also getting this issue

**Comment by FullMetalMaster** [comment]
gives me this Caused by 0: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: twilightforest.entity.boss.EntityTFHydra.<init>(EntityType,World)void/newInvokeSpecial

**Comment by GizmoTheMoonPig** [comment]
thats a completely different issue from this one. Please open a new issue and include a crashlog

**Comment by GizmoTheMoonPig** [comment]
> java.lang.ClassCastException: net.minecraft.entity.item.TNTEntity cannot be cast to net.minecraft.entity.LivingEntity

I know what caused this, and it's been fixed at this point, even in 1.16. Please update TF to any version above 4.0.497 to fix the issue
