### ISSUE TITLE
[Suggestion] x on the map

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1079]
When you open the magic map and you have already killed a boss, an x ​​appears on the map above the boss to know that you have finished it :D

**Comment by Tamaized** [comment]
This was suggested once before but as I said before it's not possible without major performance impact.

**Comment by Xetaxheb** [comment]
hijack the way banners work? place one at the bottom or top of the world at boss death location?

**Comment by Tamaized** [comment]
It's not that simple, banners arent structures.

**Comment by Andromander** [comment]
Just noticed this is a duplicate of #701. It's quite similar in concept.
