### ISSUE TITLE
[Suggestion] Curios Compatibility for Charms of life and Charms of Keeping

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [TeamTwilight/twilightforest#1082]
Hello,

I remember when playing the 1.12 version of this mod, that it had compatibility with a mod called Baubles which added different inventory slots that different mods could use.

In 1.16 a similar mod has arisen called Curios and many mods have started picking it up and using it. It's functionality is extremely similar to Baubles and I think it would be great if the Charms of Life and Charms of Keeping could fit into the slots that are added by this mod, since Baubles doesn't seem to be updated past 1.12 at the moment.

An example of the Curios inventory:
![2021-04-16_22 40 47](https://user-images.githubusercontent.com/64381954/115090565-19badd00-9f0d-11eb-9e3f-bf5cef68fd5b.png)

Example of the tooltip shown on a curio (with advanced tooltips on):
![2021-04-16_23 37 37](https://user-images.githubusercontent.com/64381954/115090627-3eaf5000-9f0d-11eb-9a2a-294ac8d01e24.png)

A link to the mod's page can be found here: https://www.curseforge.com/minecraft/mc-mods/curios

This isn't essential for the 1.16 stable release, I just think it would be something convenient to have implemented at some point in the future.

Thanks a lot for all the fantastic work that you do on this mod!

**Comment by Tamaized** [comment]
We actually already had plans to do this, however we never put it on the issue tracker :)

**Comment by The-Bernician-Lamb** [comment]
Sweet! That's great to hear! I look forward to it!

**Comment by GizmoTheMoonPig** [comment]
forgot to close this one too! I recently added curios compat for our charms, trophies, and bugs. Charms even have a special render on your player! Trophies and bugs render on your head, just like if you were wearing them on your head.

**Comment by The-Bernician-Lamb** [comment]
Awesome! Can't wait to test this out! Thanks for all your hard work guys!
