### ISSUE TITLE
Strange Particles 

### ISSUE THREAD

**Issue by devilkajo** [TeamTwilight/twilightforest#1083]
When I go to the bosses there are strange particles in the Air which follow me and make me lag. I tried to turn off the prticles but it doesn´t worked.

**Comment by TheOnlyMann** [comment]
it is part of the progression, you need to defeat the bosses in specific order in order to remove those particles

**Comment by Tamaized** [comment]
They're not particles they're a weather effect, and they have no more performance impact than rain... It's the same render.

But yes it means you're in progression locked area, follow your advancements.
