### ISSUE TITLE
Incompatibility with EntityCulling

### ISSUE THREAD

**Issue by NanoHeart** [TeamTwilight/twilightforest#1084]
Forge version: 36.1.4
Twilight Forest version: 4.0.426
Link to crash log: https://gist.github.com/NanoHeart/6eb3ae40fdcfd4f53f03c7d8e6de7a9e

Steps to reproduce:
1. Install EntityCulling and Twilight Forest

What I expected to happen: Work

What happened instead: Crash on launch.

**Comment by Tamaized** [comment]
Report it to EntityCulling, it's their own bad asm.
