### ISSUE TITLE
Classic Textures incompatible with new models

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#1089]
Forge version: 36.1.0
Twilight Forest version: 4.0.433

Steps to reproduce:
1. Spawn a mob with a changed model, ie. Wild Boar, Deer, Questing Ram

What happened:

As the new textures have different UVs, whether parts have been shuffled around or a completely new texture map was created, the textures for the old models are no longer compatible. See below examples of the classic pack in effect on the new models.
![2021-04-19_13 43 42](https://user-images.githubusercontent.com/29526717/115179209-25c5bb00-a116-11eb-9714-e6ed0f7ad8cf.png)

**Comment by Drullkus** [comment]
Issue moved to 1.18 Milestone for potential 1.18 model json deserialization
