### ISSUE TITLE
error barreras con la hidra

### ISSUE THREAD

**Issue by imnotafk** [TeamTwilight/twilightforest#1090]
I use integrated launcher forge for 1.12.2 with optifine
Twilight Forest version: 1.12.2 -3.11.1021-universal

Steps to reproduce:
1. opened the portal to the dimension 2.
2. i kill the naga
3. i kill the licht
4. i kill the minoshroom
5. i went to kill the hydra but the barriers were still not removed.

What I expected to happen: the barrier was removed so I could kill it. (I have all 3 trophies in my inventory)
![2021-04-19_08 39 39](https://user-images.githubusercontent.com/82820338/115245760-e33ab900-a0ea-11eb-84ce-ead5ef593059.png)

What happened instead: I went to kill the hydra and the blockage was still there. I tried modifying the mod settings and obviously reloading the world but the problem continues.

**Comment by Tamaized** [comment]
Progression is tied to your advancements, check your advancements.

**Comment by imnotafk** [comment]
> La progresión está ligada a sus avances, verifique sus avances.

I am missing the mighty stroganoff achievement, how can I complete it?

**Comment by GizmoTheMoonPig** [comment]
Did you eat the meef stroganoff?

**Comment by Andromander** [comment]
Based on the reproduction steps, the Meef Stroganoff was not consumed. This is required to unlock the Fiery Swamp. If the Meef Stroganoff was consumed but the advancement has not been given, log out and back into the world (or restart the server if this is multiplayer).
