### ISSUE TITLE
Optifine warning appears every time you start the pack.

### ISSUE THREAD

**Issue by Seth0067** [TeamTwilight/twilightforest#1092]
Forge version: 36.1.4
Twilight Forest version: (this is the build number) 4.0.426
Link to crash log: n/a

Steps to reproduce:
1) Successfully load game with Optifine and Twlight Forest
2) See Optifine warning screen
3) click Proceed to continue
4) Restart pack
5) See Optifine warning again and again and again...

What I expected to happen:
I would expect to see this screen once, accept and proceed, and never see it again for this particular pack configuration.

What happened instead:
I see this screen every time I load the pack.

Suggestion: Allow the user to check a box that says "do not show this warning again" to bypass automatically at start.

**Comment by Tamaized** [comment]
Use the config option

**Comment by Seth0067** [comment]
OK, If there is a way to turn this off in the config, the least you could do is let the user know on the screen itself:  

"You can disable this warning in the config file."  etc.
