### ISSUE TITLE
Unexpected crash with error 0 caused by leaves

### ISSUE THREAD

**Issue by AprilDerg** [TeamTwilight/twilightforest#1095]
Forge version:  36.1.0
Twilight Forest version: 4.0.426
Link to crash log: https://gist.github.com/JARRRRATEEEEE/1da7836b09139e79d877dfcdfb318c49

Steps to reproduce:
1. start minecraft with the mod
2. go to dark forest
3. go near dark leaves
4. get crash :/

What I expected to happen: minecraft doesn't crash, or can at least relaunch without problem

What happened instead: minecraft crashes every time I start the world it crashes.

**Comment by Andromander** [comment]
Issue seems to be caused by Rapid Leaf Decay due to Dark Leaves not having a property it is expecting. May chalk this up to that mod as they should check if the block does have this property rather than assuming it does.
