### ISSUE TITLE
1.16 Skylight Forest Generation Problem

### ISSUE THREAD

**Issue by North-West-Wind** [TeamTwilight/twilightforest#1099]
Forge version: 36.1.6
Twilight Forest version: 4.0.435
Link to crash log: (It didn't crash)

Note: The mod is loaded together with Lost Cities.

Steps to reproduce:
1. Set the settings in config to `skylightForest = true`
2. Launch the game and warp to Skylight Forest
3. Sees an ugly layer of bedrock under your feet.

What I expected to happen:
Skylight Forest should not generate bedrock.

What happened instead:
Skylight Forest generates 2 bedrock layers at the bottom of the world.
Also I don't think the islands are generating quite correctly.

[Here](https://drive.google.com/file/d/1CDlVLdQau1IZTez0HQerFXthwrlLzrI_/view?usp=sharing)'s an image.

**Comment by GizmoTheMoonPig** [comment]
skylight forest is still in the works, so its expected. We'll try to finish up the dimension sometime in the future, but for now it's been disabled in modern versions and put on hold in favor of other things (porting and structure reworks). Closing for now as it is known, but not something we'll tackle atm
