### ISSUE TITLE
Weird world gen

### ISSUE THREAD

**Issue by Stalkob** [TeamTwilight/twilightforest#110]
@Benimatic 
Hello there, had a case of the maze getting into the not yet unlocked Twilight Highlands

![2017-07-05_21 40 45](https://user-images.githubusercontent.com/29694455/27884021-0b9e9e8a-61d3-11e7-9cae-7487ed16641a.png)

Seed is -2088016298777584345
Coordinates are X: -163.483 Y: 19 Z: 525.988

Now as far as I've noticed, the world gen went weird on me and the Dungeons spawned at a bit different places, as seen on the map

![2017-07-05_22 42 23](https://user-images.githubusercontent.com/29694455/27884063-391ed3c0-61d3-11e7-871f-ce9b815c47e3.png)

I hope I was of some help to you guys!

**Comment by ghost** [comment]
I had this issue as well with the naga courtyard.

**Comment by Tamaized** [comment]
Does not appear to be happening in 1.18 builds
