### ISSUE TITLE
server type check missing in code causing incomplete set of tags recieved error

### ISSUE THREAD

**Issue by Tsoccerguy3** [TeamTwilight/twilightforest#1100]
Forge version: does not matter
Twilight Forest version: (this is the build number) does not matter
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1.  Just have mod installed and log onto Vanilla , Paper , spigot , etc .. server 
![2021-04-24_13 38 58](https://user-images.githubusercontent.com/22108822/115967829-c9421180-a502-11eb-8765-dc96a8041542.png)

What I expected to happen: The soources are missing any server handling code to disable non supported forge code

What happened instead: can not log on to a non forge server , simply because the mod is installed . Server checks are missing in the sources

**Comment by Tamaized** [comment]
> does not matter

It most certintaly does matter. Now I don't know if this was 1.16+ or not. I assume so because that's the version where forge was having issues or something where the player needs to restart their client to connect to a server.

Anyway, not our problem.
