### ISSUE TITLE
Features from other mods are generating in the twilight forest 

### ISSUE THREAD

**Issue by Direbat** [TeamTwilight/twilightforest#1101]
Forge version: 36.1.0
Twilight Forest version: 4.0.435
Link to crash log: no crash

I am not sure if this is fixable on your side but here is the issue.
I am also using quite a few other mods in the screenshots but I tried the same thing with another profile that just had artifacts and twilight forest and the same issue occured.

Steps to reproduce:
1. download mods that add structures or mobs to overworld  I used greek fantasy, artifacts and wyrmroost
2. open minecraft
3. go twilight forest
4. search around for the structures(for some reason these structures don't have a /locate command sorry about that but they do generate very frequently)

What I expected to happen:
not to find overworld features in the twilight forest

What happened instead:
found structures and mobs from other mods in the twilight forest

overworld drake from wyrmroost
![2021-04-25_12 15 44](https://user-images.githubusercontent.com/74643395/115984049-a5460500-a5c2-11eb-820b-19f0622bfff1.png)
campsites from artifacts mod
![2021-04-25_12 15 58](https://user-images.githubusercontent.com/74643395/115984054-aaa34f80-a5c2-11eb-82b2-d959ff4fffdf.png)
satyr camp from greek fantasy
![2021-04-25_12 16 43](https://user-images.githubusercontent.com/74643395/115984075-c27ad380-a5c2-11eb-89c8-47c2e2e2b97d.png)

**Comment by Andromander** [comment]
Generally speaking, those mods need to be configured to not generate in our dimension, or our biomes if they do not have a blacklist for a dimension. It's out of our control.

**Comment by Direbat** [comment]
Then I suppose I will wait for the other mods to blacklist their features. 
Thank you for responding.

**Comment by MarioSMB** [comment]
I can only speak for Wyrmroost, which has been known to conflict with dimension mods (The Abyss II in my experience), and since they have no plans to update their mod any time soon, the best workaround currently is the In Control mod: https://www.curseforge.com/minecraft/mc-mods/in-control
It will allow you to disable spawning of monsters on a per-dimension basis.

**Comment by Drullkus** [comment]
Gonna tag #1120 as well since the solution for #1120 will address this as well
