### ISSUE TITLE
Assorted Decor and Twilight Forest together causing crash

### ISSUE THREAD

**Issue by judicius** [TeamTwilight/twilightforest#1106]
Forge version: 36.1.4
Twilight Forest version: 4.0.426
Link to crash log: [gist](https://gist.github.com/judicius/4b57909ff24901461792a1b29626064b)

Steps to reproduce:
1. Install Assorted Decor with Twilight Forest and JEI

What I expected to happen: JEI to be able to display items without crash

What happened instead: JEI will crash when displaying Colorizer Brush from Assorted Decor with an "unclosed" error. This only happens with Twilight Forest installed. A issue is opened with [Assorted Decor](https://github.com/grim3212/AssortedDecor/issues/5) as well .

**Comment by bs2609** [comment]
Probably a repeat of #153.

**Comment by Andromander** [comment]
This appears to have been fixed on Assorted Decor's end.
