### ISSUE TITLE
SUBMISSION REQUEST: New Shield Types [already sprited]

### ISSUE THREAD

**Issue by BrassMcCrafty** [TeamTwilight/twilightforest#1107]
I would like to request the addition of an Ironwood, Steeleaf and Fiery shield

I am only submitting additions and do not have features/special abilties written down for these shields

![steeleaf_shield](https://user-images.githubusercontent.com/72028034/116290346-385c7780-a748-11eb-92c8-49e4f244b6b4.png)
![ironwood_shield](https://user-images.githubusercontent.com/72028034/116290349-38f50e00-a748-11eb-8e4d-201f74481506.png)
![fiery_shield](https://user-images.githubusercontent.com/72028034/116290351-38f50e00-a748-11eb-99c4-8998ace0a0a3.png)

**Comment by CacoVil08** [comment]
Wow, these Additions would be so cool!

**Comment by Azar2477** [comment]
It might be added in a future version of Twilight Forest (4.0.5xx+ or 4.1)

**Comment by BrassMcCrafty** [comment]
Thank you so much for the consideration! I love shields and think MC in
general/TF could use a nice expansion. Glad to see it was seen lol

**Comment by Tamaized** [comment]
We never said this was going to be added to the base mod I'm not sure why you would say so, that's spreading false information.

As I stated on discord a while back, this is better off as an addon mod to avoid bloat.

**Comment by BrassMcCrafty** [comment]
wasn't sure who Azar was but this is the first notification I've gotten
back so I assumed it was legit

**Comment by Azar2477** [comment]
Were just helping.

**Comment by Azar2477** [comment]
I'm removing my comment now.
