### ISSUE TITLE
[1.16.5] Double Lich Caused Both To Be Immortal

### ISSUE THREAD

**Issue by cyberdragon442** [TeamTwilight/twilightforest#1112]
Pack: Valhelsia 3 3.3.1

Steps to reproduce:
Unknown, try manually spawning two liches in the same tower
NOTE: I passed by the tower at a distance and saw a lich boss bar before defeating the naga. It's possible one spawned early and the second one appeared when I went back to the tower.

What I expected to happen: 1 lich per tower which would allow attack reflection to knock down the shields 

What happened instead: 2 liches spawned in the same tower. Attempting to reflect their attacks either broke the projectiles or if they were reflected had no effect regardless of which one they hit (the sender or the other).

Possibly related to https://github.com/TeamTwilight/twilightforest/issues/829

**Comment by Azar2477** [comment]
Double Lich Caused Both To Be Immortal or #1112 is ignored.

**Comment by KingofThemyscira** [comment]
Not sure on a format here but I have the exact same issue cyberdragon442 has.  Is there any fix for this?  I'm stuck with two immortal twilight Liches.  Is there maybe a way to force restart the twilight forest in single player to fix this?
