### ISSUE TITLE
(Suggestion) Rename "Oak Savanna" to "Quercine Savanna"

### ISSUE THREAD

**Issue by KdotJPG** [TeamTwilight/twilightforest#1113]
Suggestion: Rename the "Oak Savanna" biome to "Quercine Savanna", to make the mod feel more linguistically rich.

[Quercine](https://www.thefreedictionary.com/quercine) (Quer-"sine" or Quer-"seen") - "relating to oak trees"

It might be difficult to rename the biome registry name (what shows up in the F3 dialog and in /locatebiome) without breaking existing worlds, until Forge adds a good DataFixerUpper API, but you could modify the display name. Shouldn't be too bad to have it named the two slightly different things.

Places I've found where it's defined:

- https://github.com/TeamTwilight/twilightforest/blob/7403322514eb91c61fbc960f997d3cb42fcc6ae3/src/main/resources/data/twilightforest/patchouli_books/guide/en_us/entries/world/biomes/general_biomes.json#L49 (no other language entries - can also remove the 'h' if nothing else)
- The language files here: https://github.com/TeamTwilight/twilightforest/tree/1.16.x/src/main/resources/assets/twilightforest/lang (All biome names in English, and only the set in en_us.json seems to be uncommented)

**Comment by Killer-Demon** [comment]
Unfortunately, this is not a change we're looking to make. We're happy with the current naming scheme, and oak savannas are a real life thing.

**Comment by KdotJPG** [comment]
> oak savannas are a real life thing.

Oh, cool to know. That does change my view a bit!
