### ISSUE TITLE
Life draining staff

### ISSUE THREAD

**Issue by Hexarr** [TeamTwilight/twilightforest#1117]
Forge version: forge-1.16.5-36.1.0
Twilight Forest version: twilightforest-1.16.5-4.0.435-universal
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
https://gist.github.com/Saterrr/bf1880b686c7d9f8d2185b74e3b27820
Steps to reproduce:
1. Get a life draining scepter
2. Use it on a mob
3. When the mob dies it crashes your game
What I expected to happen:
Using a life draining scepter should kill the mob and restore my health
What happened instead:
Crashes my game and gives you a exit code 0 error when the mob dies from the life draining scepter

**Comment by GizmoTheMoonPig** [comment]
looks like an issue with the hats mod, I would open an issue there too

**Comment by Killer-Demon** [comment]
Doesn't appear to be an issue with Twilight Forest.
