### ISSUE TITLE
(suggestion) New "firefly particle" spawning block

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1119]
I have heard talk of removing the firefly entity and replacing it with a particle for performance reasons. This makes sense, but also makes me a bit sad because I used to hide firefly spawners under builds in creative for atmospheric effect, and I want to still be able to do this if I can.

My pitch: a block that functions similarly (kinda maybe sorta) to the feral flare lantern from torchmaster. When placed, it generates these firefly particles periodically within a set radius. 

Texturing this would of course be up to yall (if you decide to implement something like this), but I have another idea with respect to this: make it have an adaptive texture. Give it a default texture of a stone block or something, but when shift-right-clicked (or using a keybind) with a block in hand, have it change to this block's texture. 

I have no idea if that is even possible, but I'm having flashbacks to mods that added camouflaged blocks and things like buildcrafts facades. 

Thanks for coming to my Ted Talk

**Comment by GizmoTheMoonPig** [comment]
added in 9185573235acf0c5adef18e08a0dbc45f8ab41e7, forgot to close this
