### ISSUE TITLE
Biome Category Tag Mislabeling 

### ISSUE THREAD

**Issue by waterpasta** [TeamTwilight/twilightforest#1120]
Forge version: 36.1.0
Twilight Forest version: 4.0.435
Link to crash log: No crash

Steps to reproduce:
1. Install a biome category dependant mod (subterranean wilderness).
2. Observe the various biomes (snowy forest and highlands)

What I expected to happen:
Snowy forest generates snowy caves, highlands biome generates taiga caves.
What happened instead:
Snowy forest generates temperate forest caves, highlands biome generates mesa caves.

I believe the issue is the "category" biome tag. The snowy forest biome is tagged as in the "forest" category, which is for temperate forests. The highlands biome is tagged as in the "mesa" category when it should probably be tagged as a taiga variant.

**Comment by Drullkus** [comment]
Our biome labeling is accurate. The other mod is going to want to implement a blacklist. Please leave an issue ticket on that/those mod’s issue tracker(s) asking for biome blacklisting. See team-abnormals/environmental#161

We have no control over how other mods selectively modify our biomes, they must be the ones implementing it.
