### ISSUE TITLE
Server texture issues

### ISSUE THREAD

**Issue by kaanna** [TeamTwilight/twilightforest#1121]
I have the twilight forest mod installed in my server (version 1.16.5) and it was working perfectly a while back. But I had to re-install for unrelated reasons. Now when I place blocks, they turn into stairs and water appears under them. With logs however, they just turn horizontally. Everything else in the mod works fine, it’s just blocks and such. Is there anyway to fix this?

Forgot to add this, but it only happens in multiplayer. Everything on my single player world is working fine.

**Comment by Drullkus** [comment]
What version of Minecraft, Forge, and Twilight Forest do you have?

**Comment by kaanna** [comment]
> What version of Minecraft, Forge, and Twilight Forest do you have?
 For minute craft I’m using 1.16.5 with my forge version being 36.1.0. The twilight forest’s version is 1.16.5, so I’m not sure if it’s just a bug or not with the latest version.

**Comment by Tamaized** [comment]
This is a common client server registry mismatch issue, if you restart your client it'll usually fix this, if not then the mods on your server and client are different possibly even mod versions.

This isn't a TF problem.
