### ISSUE TITLE
Structure blocks generating in the Spooky Forest biome

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1122]
Forge version: forge-36.1.13
Twilight Forest version: 4.0.435

I'm playing in my own server with Valhelsia 3.3.1 installed on it + Ice and Fire (installed by me, not a part of the modpack). I've been working my way up by defeating the bosses then I came across these structure blocks (which I believe were supposed to be spawners?) in the Spooky Forest biome. They're unbreakable and don't function at all. I'm not sure if any files are needed in this bug report but I'm ready to provide any if needed.

![2021-05-11_01 53 54](https://user-images.githubusercontent.com/83987279/117730542-8e77f300-b1fd-11eb-8898-8a43d260a606.png)

**Comment by GizmoTheMoonPig** [comment]
Has been fixed on the github, will be in the next beta
