### ISSUE TITLE
[1.16.5] Hoe stats are oddly high

### ISSUE THREAD

**Issue by Mike-U5** [TeamTwilight/twilightforest#1123]
Forge version: 36.1.16
Twilight Forest version: 1.16.5-4.0.435

The Twilight Hoes have some really bizarre stats.
The Ironwood Hoe has 4 attack damage and 10.5 attack speed, which makes it significantly stronger than the Netherite Hoe. The Steeleaf Hoe is even stronger, with and attack of 5 and a speed of 12.

**Comment by Tamaized** [comment]
This was already fixed in dev 277e549581e034e10d6ac2f012a9fd54af56cf11

**Comment by Tamaized** [comment]
Actually wait that commit is older than the build on curse. Uh oh time to look into it
