### ISSUE TITLE
Dark forest invincibility

### ISSUE THREAD

**Issue by nybble99** [TeamTwilight/twilightforest#1124]
I was following regular progression (Killed naga, lich, alpha yeti, snow queen and minoshroom) and decided to go check out the dark forest before continuing as it was now unlocked. However, all the enemies in the forest had green invincibility particles even though I had killed the lich already? I thought maybe you had to place a trophy on the pedestal first, but getting close enough to place the trophy was incredibly hard when enemies spawn regularly throughout the forest and deal heavy damage even with good gear. The invincibility went away whenever I placed the trophy, but this was so difficult I thought it must be a bug.

**Comment by Tamaized** [comment]
Yeah known issue, the structure bounding box is extending above ground, once you activate the pedestal all will be fine
