### ISSUE TITLE
Uncrafting table output items are shown outside of the GUI

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1125]
Forge version: 36.11.18
Twilight Forest version: 1.16.5-4.0.435-universal

Steps to reproduce:
1. Place uncrafting table
2. Place uncrafting table item into input slot

What I expected to happen:
The eight crafting tables and maze map focus would appear in the nine slots on the GUI.

What happened instead:
The eight crafting tables and maze map focus appear outside of the interface to the left. 

![2021-05-15_20 13 58](https://user-images.githubusercontent.com/69029346/118384469-086ff980-b5bb-11eb-8cca-fcf0ca6d4853.png)

**Comment by GizmoTheMoonPig** [comment]
fixed in dev, will be in the next beta
