### ISSUE TITLE
Cicada Jar not making sounds

### ISSUE THREAD

**Issue by FloppaWithDrip** [TeamTwilight/twilightforest#1127]
Forge version:  36.1.0
Twilight Forest version: 4.0.435

Steps to reproduce:
1. Place down Cicada Jar
2. Feel disappointed/relieved

What I expected to happen: The jar produces extremely annoying noises causing to me break it seconds after placing

What happened instead: There is no noise at all, even with all sound settings set to 100%

**Comment by GizmoTheMoonPig** [comment]
The sound is a random event, although I may have made it too rare... will have to look over it again

**Comment by FloppaWithDrip** [comment]
It still doesn't make sound for me, even in the version .467, its very strange because the regular Cicada does make sound

**Comment by Andromander** [comment]
Should be resolved in 754fcad.
