### ISSUE TITLE
A duplicate config file is created with a ".bak" file extension on top of the already existing ".toml" extension

### ISSUE THREAD

**Issue by JazDog02** [TeamTwilight/twilightforest#1131]
Forge version: 
Twilight Forest version: twilightforest-1.16.5-4.0.435-universal
Link to crash log: [gist](https://gist.github.com/JazDog02/74ade06c65c7f864beaa58a152b69ceb)

Steps to reproduce:
1. Download the .jar file as usual.
2. Start running a functioning multiplayer server 
What I expected to happen: 
The mod would be loaded for the first time and the correct config files would be created without error.

What happened instead: 
The mod created the correct config file (twilightforest-common.toml), but also created a faulty one as well (twilightforest-common.toml.bak). It seems it made a duplicate file with the extensions ".bak" on top of the config file which already has ".toml".

**Comment by GizmoTheMoonPig** [comment]
fixed in dev, will be in next beta

**Comment by Tamaized** [comment]
Also duplicate #1073 and #1129
