### ISSUE TITLE
Lighting TNT up next to a gnome crashes the game

### ISSUE THREAD

**Issue by no-sorry** [TeamTwilight/twilightforest#1132]
Hey! I'm new to Twilight Forest so I'm sorry if I didn't get the names right - it's those gnome looking fellas with boots and pickaxes, I found them under a round ant-hill kind of thing in plain fields. (I was scared so I thought I'd just..bomb it lol)

I have a whole bunch of mods, sorry to bother if this isn't an issue on your end, but I thought I'd ask since no other mobs seem to have issues with TNT! I've tried looking for similar issues, but nothing came up.

I DO have Optifine, but I removed it to see if it still happens, and it does.

Forge version: 36.1.4
Twilight Forest version: 4.0.435
Link to crash log: https://gist.github.com/no-sorry/cd56aa1c6f7985cb1b0061bb30806ae2

Steps to reproduce:
1. Go to Twilight Forest
2. Place TNT next to a gnome and light it up

What I expected to happen:
Either he mines away the TNT before I light it up, or the TNT explodes

What happened instead:
Game crashes right after right-clicking it with flint + next time I load, until I go back to my home dimension, the entirety of Twilight Forest is black, except for the sky.

Screenshot after load: 
![2021-05-18_13 25 43](https://user-images.githubusercontent.com/84387169/118651521-8f9cb780-b7dd-11eb-9f68-a929c6881c19.png)

EDIT: Alternatively, spawning one with a creative mode egg in the overworld and doing the same still crashes the game. I think maybe it has something to do with it wanting to mine the TNT away..? (Also I'm trying so hard not to look at spoilers yo, really wanna experience this mod blindly!)

**Comment by Tamaized** [comment]
That's strange, the AI is quite literally disabled I'm not sure how it's being activated.

**Comment by Tamaized** [comment]
Oh okay, it was disabled in dev 17 days ago
16596db133d8d2481b1a51c3c580a90195a7a066

**Comment by no-sorry** [comment]
> Oh okay, it was disabled in dev 17 days ago
> [16596db](https://github.com/TeamTwilight/twilightforest/commit/16596db133d8d2481b1a51c3c580a90195a7a066)

I'm VERY new to all of this, so I've no clue what disabled in dev means I'm afraid :') Is this something I should/can do anything about, or should I just leave you guys with it now?

**Comment by Tamaized** [comment]
It means we've already fixed it but we haven't pushed it to curseforge yet

**Comment by no-sorry** [comment]
> It means we've already fixed it but we haven't pushed it to curseforge yet

Oh okay, gotcha! I'll wait then, thanks!

**Comment by GizmoTheMoonPig** [comment]
since this is disabled now im gonna close this. They wont crash your game in the latest beta.
