### ISSUE TITLE
Redcap goblin's ears sometimes don't turn with its head or turn without its head

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1133]
Forge version: 36.11.18
Twilight Forest version: 1.16.5-4.0.435-universal

Steps to reproduce:
1. Spawn a redcap goblin on a pillar of blocks so that it stays still, but can look around.
2. Move around it short distances along a circle around it to get it to turn its head, **or**
3. Wait for the redcap goblin to turn its head on its own. It may take a few movements on its part for the issue to show.

What I expected to happen:
The goblin's ears would never detach from its head.

What happened instead:
The goblin's ears can sometimes not turn with its head, or turn on their own before the head moves, and clip through it in strange ways.
I've gotten this to occur with the redcap sapper as well, but far less often than the regular redcap goblin, whose ears seem to detach almost every time they turn around on their own.

![2021-05-18_14 24 58](https://user-images.githubusercontent.com/69029346/118726272-f02ff280-b7e5-11eb-8a7b-76b31a39a511.png)
![2021-05-18_14 25 07](https://user-images.githubusercontent.com/69029346/118726274-f1611f80-b7e5-11eb-986e-9a8533381f89.png)
![2021-05-18_14 30 35](https://user-images.githubusercontent.com/69029346/118726280-f2924c80-b7e5-11eb-98e9-89ac7cbfbc00.png)
![2021-05-18_14 31 59](https://user-images.githubusercontent.com/69029346/118726283-f32ae300-b7e5-11eb-8eeb-87766f979355.png)

**Comment by GizmoTheMoonPig** [comment]
fixed in dev, will be in next beta
