### ISSUE TITLE
Enchantment Description Support

### ISSUE THREAD

**Issue by WenXin20** [TeamTwilight/twilightforest#1134]
- Support for this mod would only require `enchantment.twilightforest.enchant_name.desc` to be added to the lang file.
- Mod link: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by Tamaized** [comment]
The 2 enchantments accidentally added by us mid port aren't to stay, and I believe have already been removed in dev.

**Comment by WenXin20** [comment]
Ah, I'll close this then.
