### ISSUE TITLE
Twilight Oak planks cannot be lit on fire

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1135]
Forge version: 36.1.0
Twilight Forest version: 4.0.461
Link to crash log: N/A

Steps to reproduce:
1. Use a flint and steel to light a twilight oak plank on fire

What I expected to happen: The planks to burn per normal

What happened instead: The plank does not burn. For all intents and purposes it behaves like stone being lit on fire: no fire is produced when trying to light the sides, and any fire lit on top goes out without damaging the plank.

**Comment by GizmoTheMoonPig** [comment]
all set, forgot to close this in my commit. Oops!
