### ISSUE TITLE
"Errors in currently selected datapacks" after mod getting upgraded

### ISSUE THREAD

**Issue by Duorhs** [TeamTwilight/twilightforest#1137]
Forge version: 36.1.23
Twilight Forest version: (before)1.16.5-4.0.435 --> (update)1.16.5-4.0.467
Link to crash log: https://gist.github.com/H1de0nbush/992b135cef7043758715092ba79cb1c9

Steps to reproduce:
1. upgrade mod form 4.0.435 to 4.0.467
2. Load a saved world

What I expected to happen:
Load the world like usual.

What happened instead:
 I got error : "Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually. " 
However even I pressed the "safe mode" button , it just play a "dot" sound and freeze for few seconds but nothing happened.

**Comment by ArcheCraft** [comment]
Same issue.
Console says 'Tag forge:fences/wooden used before it was bound'
The line would be this one: https://github.com/TeamTwilight/twilightforest/blob/1.16.x/src/main/java/twilightforest/TFEventListener.java#L246
Maybe that helps fixing that issue

**Comment by TheWitherlord** [comment]
Same exact error, ruins worlds that you create in a first launch of the game then when you close out of the game and re-launch the world becomes unusable.

**Comment by GizmoTheMoonPig** [comment]
I think I may have found a fix for the datapack issue, however if this doesnt work I cant really fix this. It seems like Thermal Foundation is doing something in events that causes tags to fail. If its only with forge tags this wont happen anymore, otherwise its something I cant fix

**Comment by Darkmega18** [comment]
I have this issue also. I'm told on the cofh discord that your latest version is doing something to it potentially? since it does mention your mod first before thermal below it.

I've seen this occur in similar ways to other things but at world creation when putting in custom edit datapacks for configs and loot tables etc. one was immersive engineering related and corail tombstones for example. and immersive engineering I believe had some that occurred with it and JEI integrations that they put some checks into to stop from happening I think.

**Comment by Duorhs** [comment]
So maybe it's because Thermal foundation add Twilight Forest's material to do its machine support , but now the update change some register name so Thermal foundation can't load previous items/blocks?

**Comment by ShinyPorygon** [comment]
> So maybe it's because Thermal foundation add Twilight Forest's material to do its machine support , but now the update change some register name so Thermal foundation can't load previous items/blocks?

Heya, I do all the compat for Thermal. I haven't done anything with Twilight. Anything that exists is natural example burning fences. However burning fences/fence gates works fine with any other mod (can confirm at least tinkers/biomes o plenty/biome's you'll go.) So I wouldn't believe it would be that!

**Comment by Darkmega18** [comment]
what even causes this kind of thing? like, corail tombstones which was fine one version broke with immersive engineering of all things the next time it updated for me, but it's own bug manifests when the world is being created and datapacks inserted for reconfiguring settings etc.

can be related or similar ways of fixing could be used to fix here? makes mention of burnables, and this is related to burnables also. similar "used before it was bound" kind of thing.

https://github.com/BluSunrize/ImmersiveEngineering/issues/4391

and this is the one corail is currently working out with latest tombstones and immersive engineering in latest forge.
https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/issues/22

also just realized I never dropped my log snippit in here either, so here we go:
https://pastebin.com/PnAaXjpm

I can also say that using the second latest version of twilight forest on curseforge that is available to the launcher HAS just managed to load my world on testing right now. so appears to be something in the newest for some reason or another.

**Comment by Darkmega18** [comment]
can be related or similar ways of fixing could be used to fix here? makes mention of burnables, and this is related to burnables also.

https://github.com/BluSunrize/ImmersiveEngineering/issues/4391

**Comment by Darkmega18** [comment]
WELP, alrighty then. GG?
