### ISSUE TITLE
Broken worldgen with the "more waterlogging mod"

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1144]
Forge version: release 1.16.5-forge-36.1.16
Twilight Forest version: twilightforest-1.16.5-4.0.467-universal
Link to crash log: N/A

Steps to reproduce:
1.  Install both twilight forest and more waterlogging

What I expected to happen:
Normal twilight forest worldgen

What happened instead:
The entire dimension is essentially a superflat world with only structures. (No trees, no plants, no nothing)

**Comment by Andromander** [comment]
I would believe that More Waterlogging would be at fault here, as the presence of the mod is causing this worldgen problem that doesn't exist in TF.

**Comment by Hubry** [comment]
https://github.com/TelepathicGrunt/RepurposedStructures/issues/95#issuecomment-841907063 has some explanations.

**Comment by Andromander** [comment]
Ah...that may explain it, then. This will need to be reported to that mod as it's out of our control.
(For those that needs the long short of it: the way the mod adds blockstate properties, it causes breakages in datapacks, which basically means it will break worldgen.)

**Comment by TelepathicGrunt** [comment]
@aWhisper20 More Waterlogging just got updated to 1.5 and uses the statement lib which means it now will not break worldgen json files in mods and datapacks anymore. Updating that mod should make it work with twilight forest now
