### ISSUE TITLE
Twilight Forest portals do not correctly link

### ISSUE THREAD

**Issue by Untitled-1-dev** [TeamTwilight/twilightforest#1145]
Forge version: 36.1.18
Twilight Forest version: 1.16.5-4.0.468-universal
Link to crash log: N/A

Steps to reproduce:
1. Create an Amplified world with seed -1649334887415279876
2. Create a Twilight Forest portal at the coordinates x -101 y 248 z 185
3. Jump in
4. When the Twilight Forest loads, jump back into the portal to go back to the overworld

What I expected to happen:
I'm taken back to the portal I built at those coordinates.

What happened instead:
The game generates a new portal at x -205 y 69 z 76 and takes me there instead. The portals I created are not linked properly.

**Comment by Niketats** [comment]
Not only Amplified world affected

**Comment by SummitSummit** [comment]
Got this on twilightforest-1.16.5-4.0.479-universal as well.

**Comment by GizmoTheMoonPig** [comment]
redirecting this to #1459 so we can keep track of every portal issue in 1 place
