### ISSUE TITLE
Missing textures for doors

### ISSUE THREAD

**Issue by nils142** [TeamTwilight/twilightforest#1147]
Forge version: 1.16.5-36.1.12
Twilight Forest version: (4.0.467)

Steps to reproduce:
1. Go into the creative inventory and search for doors

What I expected to happen:
The Twilight Forest doors appearing normal
What happened instead:
The textures for the doors as well as the transwood trapdoor are missing.
Instead, they are purple/black. However, when placed the textures are there.

**Comment by Drullkus** [comment]
#711
