### ISSUE TITLE
Seeker Bow deals way too much damage

### ISSUE THREAD

**Issue by FloppaWithDrip** [TeamTwilight/twilightforest#1148]
Forge version: 36.1.0
Twilight Forest version: 4.0.467

Steps to reproduce:
1. Use seeker bow (used power 5 in my tests but it also does this without power)
2. Shoot to the side of a target mob, not directly at it, the further to the side the more damage it does.

What I expected to happen: The bow deals a reasonable amount of damage, like less than half of what it currently does

What happened instead:
It did 93 damage in a single hit to the Ur-Ghast. Bow consistently deals above 80 damage.
This is probably caused by the 'aimbot' accelerating the arrow as it redirects to its target.

**Comment by bs2609** [comment]
> This is probably caused by the 'aimbot' accelerating the arrow as it redirects to its target.

I donked and used the wrong variable here:
https://github.com/TeamTwilight/twilightforest/blob/ad8d1f1dbd178d384f0c9785acfdd0e50a5f9f76/src/main/java/twilightforest/entity/projectile/EntitySeekerArrow.java#L71-L72

`targetVec.scale` should also use `courseLen / totalLen` for the velocity to be correctly preserved.
