### ISSUE TITLE
Gallons of blood and tears advancement does not require actually wearing a piece of armor

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1149]
Forge version: server version: 36.1.0 client version: 36.1.0
Twilight Forest version: 1.16.5-4.0.468
Link to crash log: N/A

Steps to reproduce:
1. Hold all four pieces of fiery armor in inventory
2. Craft/pick up a fiery pickaxe 

What I expected to happen: No advancement to be granted because I was not wearing a piece of armor per the description of the advancement (wield a fiery tool or weapon while wearing at least one piece of fiery armor)

What happened instead: The advancement was granted just by holding the armor and tool at the same time, not by putting on a piece of the armor

**Comment by FloppaWithDrip** [comment]
Isn't this the case with vanilla advancements aswell?  eg. Cover me with diamonds, Cover me in debris

**Comment by Andromander** [comment]
The requirements for the armour is "inventory_changed", meaning that if the armour is equipped or obtained from crafting, it still counts towards completing it, as all those slots are considered part of the inventory. Theoretically, you can get the advancement by wearing the armour if you use something like a dispenser to equip it to the armour slots.

**Comment by EvergreenSystems** [comment]
Submitted this report mostly because the description for it is misleading, would it make sense to tweak it?

**Comment by Tamaized** [comment]
I suggested this in dev chat as well lol

**Comment by GizmoTheMoonPig** [comment]
there we go, wording is a bit better now
