### ISSUE TITLE
1.10.2 Crash Bug On Rendering

### ISSUE THREAD

**Issue by Cynosphere** [TeamTwilight/twilightforest#115]
Forge version: 12.18.3.2316 (Latest 1.10.2 Forge)
Twilight Forest version: 2.3.8dev (commit 7363464)
Link to crash log: https://hastebin.com/eqaxigiseg

Steps to reproduce:
1. Create new world or enter existing one
2. Wait a few seconds

What I expected to happen:
Game works normally.

What happened instead:
Game works normally for a few seconds, then screen goes to being sky color and then crashes.

**Comment by Drullkus** [comment]
Use 1.11.2
