### ISSUE TITLE
No boss spawners

### ISSUE THREAD

**Issue by SummitSummit** [TeamTwilight/twilightforest#1150]
Forge version: 36.1.23
Twilight Forest version: twilightforest-1.16.5-4.0.479-universal
Link to crash log: no crash

Steps to reproduce:
1. Go to Twilight Forest, look for bosses. 

What I expected to happen:  Naga would spawn in maze, Lich would spawn in tower.

What happened instead: No sign of either of these bosses.  Not sure why the game thinks I've beaten the Naga, this is a new world, and I've never fought one yet.  But it did allow me into the Lich tower to find no boss there either.

**Comment by SummitSummit** [comment]
Update.  The first two of each I explored (near spawn) had no boss spawners.  I have started finding bosses in structures further away.

**Comment by FloppaWithDrip** [comment]
Did you previously had an older version of Twilight Forest installed? If yes, the newer version replaced the boss spawner with ones for each individual boss causing the ones generated in older versions to dissapear.

**Comment by SummitSummit** [comment]
Ahh, that must be it.  I did enter the TF before updating because  mobs were spawning regardless of light level.

**Comment by Andromander** [comment]
Correct. As stated in the changelog for 4.0.479: `"+ Unactivated boss spawners in existing worlds will vanish due to this. Newly generated structures will work fine!"`.
