### ISSUE TITLE
Ideas 

### ISSUE THREAD

**Issue by TheKingsWit2005** [TeamTwilight/twilightforest#1152]
Ok so according to the discord i should leave suggestions here. This could just be me but alot of twilight forest mobs remind me of greek mythology. If this is an intended theme, or even just as a cool thing heres a few ideas i had:
Stymphilian birds. Hercules killed these and what if there were random lakes that spawn with flocks of birds that bite and shoot their razor sharp feathers at you. These feathers could be used for maybe crafting darts or something of similar description.
This ones a bit obvious but the Nemean lion. This is where hercules got the famous lion pelt that is impervious to sharp objects. So maybe the Nemean lion could spawn in a cave and has pouncing attacks and other dextrous things. Once you kill it you get a pelt equipable in the chestplate slot. Its of similar quality to other gear in the mod but gives you a buff perhaps like resistance? Or a chance to repel arrows like a shield? Im just tossing ideas out here.
Ok last one, a cyclops. Perhaps mountains rarely spawn, not as a full biome but singularly or in threes or something. And in each group of mountains there is a cyclops. He has a club which if you hit something or the ground with it, sends out a large shockwave. This could also be a cool way to relate to the questing ram structure, as they could spawn nearby as polyphemus from the oddysey famously had a herd of sheep as pets. Again just throwing things out there. 
But yeah overall its a really cool mod and it'd be great if some of these ideas were implemented, i doubt it tho lol. Anyways have a good day to whoever had to read my wall of text.

**Comment by FloppaWithDrip** [comment]
quite pog

**Comment by MegDuck** [comment]
Cool ideas!

**Comment by Killer-Demon** [comment]
These suggestions are a little too broad to be able to work with as of right now. Thank you for taking your time to suggest them, though. Perhaps we'll see something like them in the future.
