### ISSUE TITLE
Bows Glitched

### ISSUE THREAD

**Issue by CacoVil08** [TeamTwilight/twilightforest#1153]
When you use a Twilight Forest Bow (Tri-Bow, Seeker Bow, Ice Bow and Ender Bow). In 3rd Person Vision or in Other Players Perspective, the Bow in your hand is Glitched. And this Glitch dont affects the Gameplay, but in appearance, it affect.

Forge Version: 36.1.0
Twilight Forest Version: Twilight Forest - MC 1.16.5 - 4.0.467

**Comment by GizmoTheMoonPig** [comment]
fixed in dev, will be in next beta
