### ISSUE TITLE
Able to dismount from Pinch Beetle and still taking damage

### ISSUE THREAD

**Issue by FloppaWithDrip** [TeamTwilight/twilightforest#1155]
Forge version: 36.1.0
Twilight Forest version: (4.0.482)

Steps to reproduce:
1. get grabbed by pinch beetle
2. get grabbed
3. I can press shift to dismount?
4. I still take damage after dismounting

What I expected to happen: Not being able to dismount at all, or at least not taking damage after doing so

What happened instead: I was able to dismount and still took damage afterwards

**Comment by GizmoTheMoonPig** [comment]
you dont actually dismount, its more of a visual issue. Yetis have the same problem. This does need to be looked at though

**Comment by GizmoTheMoonPig** [comment]
just wanted to make a note that I made this work a little better, but it still isnt exactly what we want. If you dismount you now should snap right back into its jaws. Im keeping this open as we most likely want to aim for not being able to dismount at all, but I thought it may be good to mark progress on it.
