### ISSUE TITLE
Crash from shaders?

### ISSUE THREAD

**Issue by Rodrigo816** [TeamTwilight/twilightforest#1157]
Forge version:  36.1.16
Twilight Forest version: 1.16.5-4.0.467-universal
Link to crash log: https://gist.github.com/Rodrigo816/545b8779ac93656d8186c134f7dfc8a1

I crash when I open Inventory, maybe its some item I have its causing the crash.

**Comment by GizmoTheMoonPig** [comment]
you sure this is the latest beta? I swear I fixed this issue

**Comment by Andromander** [comment]
Your version in the crash log does not match the version listed here.

**Comment by Rodrigo816** [comment]
Sorry, its  1.16.5-4.0.467-universal I edited.

**Comment by GizmoTheMoonPig** [comment]
just update to the newest beta and it will fix itself

**Comment by Andromander** [comment]
Fixed in version 4.0.482. Feel free to reopen if this still occurs in the latest beta.
