### ISSUE TITLE
A lot of textures are missing on MC 1.12.2

### ISSUE THREAD

**Issue by axalox** [TeamTwilight/twilightforest#1158]
Forge version: 14.23.5.2855
Twilight Forest version: 3.11.2021

A screenshot is better than words :

![image](https://user-images.githubusercontent.com/32990916/119855826-8bc21100-bf12-11eb-9a03-96fd3969a1fd.png)

**Comment by Andromander** [comment]
Resource Packs? Errored mods? Anything in the logs? All these screenshot says is that most if not everything is a missing texture, and...is it even Twilight Forest? That looks like nothing from the mod.

**Comment by axalox** [comment]
it's underground

![image](https://user-images.githubusercontent.com/32990916/119949907-a213af80-bf9a-11eb-89e8-5c29d12aea76.png)

At the top

**Comment by FloppaWithDrip** [comment]
Are you sure this is twilight forest? It looks nothing like it, not just the textures but also the trees look way too small. And is 'Plaines de Nuit' the biome? I don't speak French but it translates to 'Night Plaines'which doesn't exist in twilight forest.

**Comment by axalox** [comment]
Sorry it's midnight ... you can close

**Comment by FloppaWithDrip** [comment]
Thought it was xd
