### ISSUE TITLE
[suggestion] Trophy Pedestal Ideas

### ISSUE THREAD

**Issue by CacoVil08** [TeamTwilight/twilightforest#1159]
The Trophy Pedestal is a block that have a Cool function. With a Trophy in it, it turns On and open the Stronghold Shield! But, if it would have more functions, the Item will be more usefull! Like:

Redstone Signal: The Trophy Pedestal could send a Redstone Comparator Signal, and when it turns On, the Signal is send. This feature will make the Players creativity expand more!

Interface: (I think its Interface in english), it could have a GUI that allows the Player to configure it. Like: The Head it Needs to Turn On; If it sends Redstone Signal; The Heads Decoration in the Block.

**Comment by Tamaized** [comment]
A better idea is to have a different power output based on which head is placed, which matches the functionality of vanilla, example: jukeboxes

**Comment by CacoVil08** [comment]
It makes sense, it would be interesting too.

**Comment by GizmoTheMoonPig** [comment]
I added comparator support for the pedestal a couple weeks ago. Forgot to close this with it, sorry!
