### ISSUE TITLE
Crash Twilight forest 1.16.5

### ISSUE THREAD

**Issue by LeoCord** [TeamTwilight/twilightforest#1160]
Forge version: 
Twilight Forest version: (this is the build number) 1.16.5 4.0.482
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)  https://gist.githubusercontent.com/natanfudge/ab585f4650d88a2eb1c8ef0f5e40565f/raw/80b3d57b4737194277d670b94c857bab9785849d/crash.txt

Steps to reproduce:
1. 

What I expected to happen: I thought I would go into the world and explore it, kill bosses

What happened instead: I play with the assembly with the twilight forest, but when I enter the world of the twilight forest, the chunks are loaded a little, and later it crashes and does not come back.

**Comment by Tamaized** [comment]
Issue is on mowzies mobs end
