### ISSUE TITLE
Ur-Ghast Loot Chest Problem

### ISSUE THREAD

**Issue by BurnutsGaming** [TeamTwilight/twilightforest#1162]
Forge version: 36.1.4
Twilight Forest version: 4.0.428
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Break the middle of the floor in the Ur-Ghast battle area.

What I expected to happen: loot chest appear after i kill the Ur-Ghast.

What happened instead: The chest didn't appear, likely because the floor was broken due to... something, a fireball or creeper or so.

**Comment by BurnutsGaming** [comment]
Duplicate of #1080

**Comment by Andromander** [comment]
Correct, duplicate of #1080
