### ISSUE TITLE
Integration with TNT and Disparity Mod

### ISSUE THREAD

**Issue by PechayClub** [TeamTwilight/twilightforest#1163]
@Pechayland is working on the integration of TF for TNT and Disparity Mod.

TNT and Disparity Mod: https://github.com/Pechayland/BurnutsPlusTNTandDisparityMod

Our current build is on Curseforge: https://www.curseforge.com/minecraft/mc-mods/tnt-and-disparity

**Comment by PechayClub** [comment]
Don't forget this link for the issue: https://github.com/Pechayland/BurnutsPlusTNTandDisparityMod/issues/2

**Comment by Tamaized** [comment]
Wait why is this posted as an issue exactly?

**Comment by TheOnlyMann** [comment]
is this an elaborate ad

**Comment by PechayClub** [comment]
> Wait why is this posted as an issue exactly?

You have to click the link of the issue on your mod.

**Comment by PechayClub** [comment]
I will close this. ok?
