### ISSUE TITLE
Problem with the maven? 

### ISSUE THREAD

**Issue by PechayClub** [TeamTwilight/twilightforest#1165]
When building mods with this maven it can get gradle errors because if you will use to make a addon.

I compared each maven.

https://modmaven.dev/teamtwilight/
To
https://modmaven.dev/teamtwilight/twilightforest/4.0.482/

Old maven:

http://repository.steamnsteel.info/artifactory/twilight-forest
To
http://repository.steamnsteel.info/artifactory/twilight-forest/com/github/teamtwilight/twilightforest/twilightforest-1.15.2/4.0.99/

Its hard to use the new maven i even have trouble.

**Comment by Tamaized** [comment]
It works fine, example
https://github.com/Tamaized/FinalKobold/blob/master/build.gradle#L74

**Comment by PechayClub** [comment]
Thanks
