### ISSUE TITLE
Why there is Version: NONE instead of Version: 4.0.482?

### ISSUE THREAD

**Issue by BurnutsGaming** [TeamTwilight/twilightforest#1166]
Forge version: 36.1.24
Twilight Forest version: 4.0.482
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:
There should be Version: 4.0.482

What happened instead:
It says Version: NONE because of the mods.toml and it cant detect the jar file version because it cant be found.

mods.toml:
version="${file.jarVersion}" to version="4.0.482"

**Comment by BurnutsGaming** [comment]
Picture:
![Uploading IMG_20210530_162610.jpg…]()

**Comment by PechayClub** [comment]
You can avoid this by editing the mods.toml that's what I did in my mod.

**Comment by Tamaized** [comment]
This doesn't work because our builds are automated by devops.
The solution is to fix the variable. Editing in the version manually each time is redundant and tedious.

Work smart not harder.

**Comment by PechayClub** [comment]
Either there is no parameters to ${file.jarVersion} or it got overwritten I will check.

**Comment by PechayClub** [comment]
There is no ${file.jarVersion} config here.

**Comment by Azar2477** [comment]
Try this version="4.0"

**Comment by Azar2477** [comment]
We will just write our own code sync your mod can't be compiled with Gradle 6.9 anyways.
