### ISSUE TITLE
[suggestion] Netherite Minotaur Axe

### ISSUE THREAD

**Issue by FloppaWithDrip** [TeamTwilight/twilightforest#1171]
It would be cool to be able to upgrade the Diamond Minotaur Axe, It would make it consistent with the rest of the diamond tools and armor, and it would make TF feel more integraded into 1.16 (if that makes sense). Its stats could just be +1 damage over the Diamond Minotaur Axe

**Comment by Drullkus** [comment]
Won't add; being added to an Addon instead
