### ISSUE TITLE
Server Crash has made game unplayble

### ISSUE THREAD

**Issue by simplemath64** [TeamTwilight/twilightforest#1172]
Forge version: 1.16.5-forge-36.1.0
Twilight Forest version: twilightforest-1.16.5-4.0.426
Link to crash log: https://pastebin.com/RYbdabND

I have server where I play with friends with a couple of mods downloaded, i was in the Twilight Forest when I came across a Skeleton Druid, I used the special ability of a weapon from another mod  called Mahou Tsukai, the weapon causes a fog to surround an enemy that the can't see out of, i used that on the druid and suddenly the server crashed. Now when ever I join it crashes the entire server for everyone. 

Please tell me how to fix this

 ##

**Comment by Andromander** [comment]
Looking at the stacktrace, this is all happening in vanilla source code, indicating this issue may not be on our side. Unfortunately, I cannot verify this as the other mentioned mod is closed source.

I would send an issue ticket to their side. Alternatively, the version of that mod is outdated, so I would update first before reporting.

**Comment by stepsword** [comment]
I'm the Mahou dev - I agree its almost certainly not Twilight Forest's fault. I think it's likely a vanilla bug where calling stop() on a goal sets stuff to null that vanilla isn't prepared to have as null.. I'm pushing what I hope is a fix for it, but i couldnt get the crash to actually happen on my own so I'm not sure if it'll work :)
