### ISSUE TITLE
fiery blood and fiery tears

### ISSUE THREAD

**Issue by RYLREYFOD** [TeamTwilight/twilightforest#1175]
Forge version: 36.1.24
Twilight Forest version: 4.0.490
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. We can't make fiery ingot

What I expected to happen: i think one iron ingot + one fiery blood = fiery ingot. 

What happened instead: But their can't combine
![evidence](https://user-images.githubusercontent.com/85601931/121296356-780fa500-c92b-11eb-91f4-8dd0f055c1bd.PNG)

**Comment by TheOnlyMann** [comment]
the recipe was changed to smithing table. please use JEI for more information.
대장장이 작업대에서 만드시는 겁니다.

**Comment by RYLREYFOD** [comment]
thx i tried it. and successed very thx
![fiery ingot](https://user-images.githubusercontent.com/85601931/121458130-c7b1a780-c9e3-11eb-9265-71571756db1f.PNG)
