### ISSUE TITLE
[Suggestion] Make the Optifine Warning appear just once

### ISSUE THREAD

**Issue by tanyan-tanyan** [TeamTwilight/twilightforest#1176]
Hi! I use optifine to increase my FPS for the modpack server I play on with my friends.
Considering Minecraft is already littered with unskippable warnings about how the client is modded, we acknowledge why Twilight Forest has decided to give this warning on game start, however we would like to request that this message appears just once and not every time the game is done loading, as it's extremely infuriating to have "pop-ups" everywhere. Thanks.

![javaw_AOn6wWIvgo](https://user-images.githubusercontent.com/68793071/121616594-12223b00-ca5b-11eb-8724-c6873493305c.png)

**Comment by Tamaized** [comment]
You can disable it in the client config

**Comment by Kiwi357** [comment]
where exactly on the client config? I'm assuming you're talking about 'optionsof.txt' right?

**Comment by erickv121** [comment]
> You can disable it in the client config

How do I do that and where do I go to find it

**Comment by CaioMS2000** [comment]
> You can disable it in the client config

where exactly?
It's happening with me
![image](https://github.com/TeamTwilight/twilightforest/assets/72468013/337bc19c-af1d-4748-bbff-b260ba175195)
