### ISSUE TITLE
Knight Phantom Loot Respawning Bug

### ISSUE THREAD

**Issue by Hiagg** [TeamTwilight/twilightforest#1178]
Forge version: 14.23.5.2854
Twilight Forest version: twilightforest-1.12.2-3.11.1021-universal
not a crash

When you kill the knight phantom via falling out of the world with any method, ice and fire ice dragonsteel for example, one hit causes it to get stuck and fall as far as it can (also works on snow queen but she just sticks to the floor), a new set of loot spawns in the chest each time the main boss body falls out of the world

Steps to reproduce:
1. Stab knight phantom boss main body with ice dragonsteel sword
2. Wait for it to fall out of the world
3. Collect your multiplying loot stash as he appears back in one of the lesser bodies as intended
4. Repeat until out of phantom bodies

What I expected to happen: Get just one set of loot for killing it

What happened instead: Get a new set of loot each time it falls out of the world

**Comment by Andromander** [comment]
I would suspect any sort of weapon that (I'm guessing here because I don't know I/F) grounds a target would cause the Knight Phantoms to fall out of world due to not having collision. While we can't do a thing about that, the loot chest constantly spawning is perhaps something to investigate.
