### ISSUE TITLE
broken texture for wild deer?

### ISSUE THREAD

**Issue by Yonk316** [TeamTwilight/twilightforest#1179]
Forge version: 1.16.5-forge-36.1.31
Twilight Forest version: twilightforest-1.16.5-4.0.490-universal
![2021-06-14_14 37 09](https://user-images.githubusercontent.com/42360206/121942479-86403580-cd1e-11eb-96a2-9edbafabb7c4.png)

Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. none

What I expected to happen:na

What happened instead:na

**Comment by GizmoTheMoonPig** [comment]
do you have the classic resource pack on?

**Comment by Yonk316** [comment]
Yes it is,just turned if off and was fine.

**Comment by GizmoTheMoonPig** [comment]
yeah, the classic resource pack currently has an issue with some of the new entity textures. We'll fix it soon, its on our todo list. We already have an issue open about it, so im gonna close this one.
