### ISSUE TITLE
acid rain got disappearing over thornlands

### ISSUE THREAD

**Issue by SchmorgusBlorgus** [TeamTwilight/twilightforest#1180]
Twilight Forest version: 3.11.1021?
forge version: 14.23.5.28654

So this is a bit of a weird one. I killed all the bosses before the highlands, killed a giant for his pickaxe, went down into the troll caves and got the lamp, didn't get the achievement for it, but went ahead and burnt some of the thorns. The acid rain is still there, and the achievement for getting the lamp says it's 1/2, so i have no idea if it's a problem on my end, or a bug, but I've tried googling and watching videos on it, and I can't find a solution to my problem.

![picture 1](https://user-images.githubusercontent.com/85920570/121996450-83186a00-cd5d-11eb-9ce8-d449274f9db5.PNG)
![picture 2](https://user-images.githubusercontent.com/85920570/121996453-84499700-cd5d-11eb-8f0e-4853664b3e6c.PNG)
![picture 3](https://user-images.githubusercontent.com/85920570/121996456-84499700-cd5d-11eb-8e6d-1cd7e777c0f9.PNG)

**Comment by Tamaized** [comment]
There's a vanilla bug where advancements granted from inventory changes (getting an item) don't always trigger. If you leave and rejoin the world it will some times fix this. You could also try dropping and picking up the lamp again.
