### ISSUE TITLE
Something in the Dark Forest bricks chunk generation

### ISSUE THREAD

**Issue by scalyhat** [TeamTwilight/twilightforest#1181]
Forge version: 36.1.31
Twilight Forest version: 4.0.490
Link to crash log (for a server): gist.github.com/danlizard/f3b0f424fb3bd93ab828e52880507e5c

This is happening to a game with other mods, so we would be very thankful if you could just suggest which of the mods is interfering with the generation.

Steps to reproduce:
1. Load up all of the mods on either a MP server or in SP.
2. Go to TF
3. Kill Naga, kill Lich
4. Go to Dark Forest biome

What I expected to happen:
I get there, progress in the forest etc

What happened instead:
At some point the game freezes - calculates a single tick indefinitely (or up to 60 seconds, then crashes the server).
The server will spew out a message along the lines of "cannot find a suitable location to place 4 smaller towers" before stopping.

**Comment by scalyhat** [comment]
Just in case, the mods can be found in the log.

**Comment by Drullkus** [comment]
No idea what this was but this has been fixed in 1.17
