### ISSUE TITLE
Is this intended functionality or a bug?

### ISSUE THREAD

**Issue by Avatarded** [TeamTwilight/twilightforest#1183]
In every version of Twilight Forest since the inclusion of the uncrafting table, I noticed that this happens, but have never seen any documentation outlining it:
![Uncrafting Enchantment Transfer](https://user-images.githubusercontent.com/77522101/122325968-23eb5e80-cef1-11eb-8602-0759986c9607.png)

**Comment by GizmoTheMoonPig** [comment]
its not a bug, no. Thats a completely intended feature

**Comment by Avatarded** [comment]
> its not a bug, no. Thats a completely intended feature

Thank you for the prompt reply.

**Comment by Tamaized** [comment]
Yes it's called Recrafting
http://benimatic.com/tfwiki/index.php?title=Uncrafting_Table
