### ISSUE TITLE
Naga Courtyard Feature Crash

### ISSUE THREAD

**Issue by firemaster1294** [TeamTwilight/twilightforest#1184]
Forge version: 36.1.23
Twilight Forest version: 1.16.5-4.0.490
Link to crash log: [gist](https://gist.github.com/firemaster1294/4a763e3f86a43d50820b5eff0d4075c0)

Steps to reproduce: Unknown. Someone was just travelling through Twilight near a Maze when they received this error. No one else was in the Twilight at the time. This seems like it could be an edge case scenario or a cross-mod problem, although I don't know for certain.

What I expected to happen: The world generation to occur without error

What happened instead: The entire server crashed

**Comment by Tamaized** [comment]
`at com.stal111.valhelsia_structures.block.DungeonDoorBlock.func_196271_a(DungeonDoorBlock.java:118) ~[valhelsia_structures:1.16.5-0.1.2] {re:classloading}`

problem is on `valhelsia_structures`'s end

**Comment by firemaster1294** [comment]
RIP valhelsia. Thank you for the quick reply!
