### ISSUE TITLE
Twilight Lich is not poping

### ISSUE THREAD

**Issue by DiabolosMan** [TeamTwilight/twilightforest#1185]
Forge version: 36.1.32
Twilight Forest version: twilightforest-1.16.5-4.0.490-universal.jar
Link to crash log: No crash

Steps to reproduce:
1. Defeat Naga
2. Take one scale
3. Enter Tower lich and go to top
4. No twilight lich is there.
I did it on 2 lich towers but no boss at all.

What I expected to happen:
Have a boss in order to continue on progression system

What happened instead:
Nothing has poped. No boss. I am stuck in progression system

Is there a way to pop this boss ? (asking an admin of this server to give me an egg ?)
Is it something I am doing wrong ?
Is it possible that for any reason, the boss unpoped because of an upgrade and then it will never pop again ?

Thanks for your help,

DiabolosMan

**Comment by GizmoTheMoonPig** [comment]
if youre on a server, then someone most likely already defeated it. You'll probably have to find a new tower

**Comment by DiabolosMan** [comment]
It is on a server, we are 3 on it, I am the only one in the twiligh. So no, nobody defeated it.... Moreover, no torch, no hole, chest full of loots.... So I confirm I was the only one and the 2 other guys confirmed not in twilight

**Comment by GizmoTheMoonPig** [comment]
the other reason could be if you ever upgraded TF from 4.0.435 to a newer version. Some code was changed making it so spawners that already existed in loaded chunks would disappear. You can still find fresh spawners in unexplored areas.

**Comment by DiabolosMan** [comment]
oh yes, we upgraded from an older version. So maybe it is the reason..... Thanks for the tip. We will try to delete the entire dimension and let it regenerate

**Comment by GizmoTheMoonPig** [comment]
glad to help! Have fun with the mod!

**Comment by DiabolosMan** [comment]
Thanks. For information, it worked. The admin deleted the entire twilight forest dimention and when I went again, same generation (because same seed) and did again the lich tower. On top, the boss was there ;-)
