### ISSUE TITLE
Twilight Forest Multipart Rendering Solution | implementation to fix invisible parts

### ISSUE THREAD

**Issue by zachsai** [TeamTwilight/twilightforest#1187]
Forge version: 
Twilight Forest version: 36.1.4
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1.
Use Optifine, go to a NAGA structure / entity
![image](https://user-images.githubusercontent.com/63996164/122655237-f08e1700-d11e-11eb-8b34-d8f1f958cca5.png)

[SOLUTION]
Twilight forest uses the forge multipart system instead of the vanilla one to fix vanilla's badly implemented multipart system. 
Alex's mobs & Ice and Fire uses a custom multipart that fixes the vanilla issue but also renders with optifine.
It considers each multipart an entity.
Alex has communicated back: 
![image](https://user-images.githubusercontent.com/63996164/122655206-c5a3c300-d11e-11eb-8118-8a308433ba88.png)

The code is public for his multipart. It is worth the try instead of simply sticking to "its optfines fault and not our problem". 
Hopefully, the Twilight forest team will take this seriously to fix the problem.

What I expected to happen:
Not have multipart invisible.
What happened instead:
be visible.

**Comment by Tamaized** [comment]
Using a full blown entity per part is idiotic

I use my own system not just "forges" you people have no idea what you're saying

**Comment by Tamaized** [comment]
And people who call me mental deserve to burn in hell
