### ISSUE TITLE
[issue] Stuck in the forrest 

### ISSUE THREAD

**Issue by lavenderdotpet** [TeamTwilight/twilightforest#1188]
Mc version: 1.16.5
Forge version: 36.1.15
Twilight Forest version: (4.0.490)

Steps to reproduce:
1. hop into the twilight forest portal
2. try to leave 
2.5 try to break blocks 
2.5.5 try to type in chat

What I expected to happen:
2. be back in the overworld
2.5 blocks would break and i would get the item
2.5.5 chat msgs would be sent

What happened instead:
2. cant leave stuck in the twilight forest
2.5 blocks break but nothing dropped 
2.5.5 typed in chat but it never popped up

it seems that its 100% locking up the server and basically acting like u lost connection to the world / server and just ur client is doing stuff

**Comment by Andromander** [comment]
Are there any other mods installed? TF is capable of running just fine, and this sort of soft-lock is caused by various conditions, such as a bad worldgen mod, or just simply the game is suffering low TPS.

There's not much information to go by with this.

**Comment by lavenderdotpet** [comment]
> Are there any other mods installed? TF is capable of running just fine, and this sort of soft-lock is caused by various conditions, such as a bad worldgen mod, or just simply the game is suffering low TPS.
> 
> There's not much information to go by with this.

not fully sure what caused it but I need to close this
I my friend sent me the world file and I was able to leave the forest just fine and after that just saved and sent him the world back and then deleted the TForest dimension and when we regnened it it worked just fine
