### ISSUE TITLE
Ender Bow while you ride this bug

### ISSUE THREAD

**Issue by AntonCVM** [TeamTwilight/twilightforest#1189]
Forge version: 
Twilight Forest version: 1.16.5-4.0.490
Link to crash log: no crash.

Steps to reproduce:
1. Ride an animal, for example a horse.
2. Shoot with Ender Bow to another mob.
3. After being teleported press crouch.

What I expected to happen:
I would expect to crouch.

What happened instead:
But instead you are teleported back to the horse's side as if you just dismounted.

**Comment by GizmoTheMoonPig** [comment]
Its because you dont actually dismount when you get teleported, the game still thinks youre riding a mob. It does still need to be fixed though as that isnt exactly intended.
