### ISSUE TITLE
Ur Ghast causing server crash

### ISSUE THREAD

**Issue by 0xhayleydev** [TeamTwilight/twilightforest#1191]
Forge version: 36.1.31
Twilight Forest version: 4.0.490
Link to crash log:
https://hastebin.com/ikegufoken.rust
https://hastebin.com/uxarabodoj.rust

Steps to reproduce:
1. Kill Ur-Ghast on server (ATM6)
2. https://hastebin.com/uteleyiwuy.yaml - lines 1880-1890 (included the whole log from 2nd crash)

What I expected to happen:
The server not to crash

What happened instead:
The server crashed

Notes:
Happened twice. Not entirely what was going on as I wasn't the person using the mod. Could also be a mod pack issue - ATM6 (1.6.10).

**Comment by Andromander** [comment]
The crashes only seem to be the server watchdog assuming the server has crashed due to a single tick taking too long. 
If possible, can this be reproduced when the server watchdog is disabled (this is done through the server properties file)?

**Comment by 0xhayleydev** [comment]
If I do that, is it going to cause the server to crash entirely and hang forever?

**Comment by Andromander** [comment]
There's no real way of knowing; sometimes the server just needs more time to process, but on the off-chance it does stay locked up, the server may need a reboot to unlock itself. Best to keep a backup in case you are concerned.
I know the Ur-Ghast doesn't cause crashes in multiplayer, but there is a chance that the much larger mod list may need longer time to work or there may be something else happening, though I don't really see anything off in the full log.

**Comment by cyberdragon442** [comment]
Exact same thing happens on Valhelsia 3.4.1 servers. It does hang indefinitely.

**Comment by gelonsoft** [comment]
[crash-2021-10-02_19.37.25-server.txt](https://github.com/TeamTwilight/twilightforest/files/7271899/crash-2021-10-02_19.37.25-server.txt)
+1
