### ISSUE TITLE
Incorrect Feather Tag

### ISSUE THREAD

**Issue by WenXin20** [TeamTwilight/twilightforest#1192]
`Forge v36.1.32`
`Twilight Forest v4.0.490`

Steps to reproduce:
1. Check forge tags: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/generated/resources/data/forge/tags/items/feathers.json

What I expected to happen:
- Raven feathers should be using the official forge tag `forge:feathers`.

What happened instead:
- Raven feathers use the `forge:feather` tag instead. (It is not plural)

**Comment by WenXin20** [comment]
Mangrove Wood is also missing the `minecraft:logs` block and item tag.

**Comment by GizmoTheMoonPig** [comment]
fixed these and also went through real quick to make sure there werent any other weird ones. If you find any more please let me know. Thanks for your help!

**Comment by WenXin20** [comment]
Yeah, np! 
I think the only other thing to mention is that the ingots and metal blocks aren't using the `forge:ingots` & `forge:ingots/ingot_type` and `forge:storage_blocks` & `forge:storage_blocks/type` block and item tags.

**Comment by GizmoTheMoonPig** [comment]
alright, I updated those as well as the ores and gems tags
