### ISSUE TITLE
Structures from other mods keep generating in the dimension

### ISSUE THREAD

**Issue by Kutomi1** [TeamTwilight/twilightforest#1193]
Forge version: 36.1.4
Twilight Forest version: 1.16.5-4.0.490

The Twilight Forest dimension is full of structures from different mods, perhaps you could prevent non-vanilla/Twilight Forest structures from spawning and make a whitelist so we can enable mods to generate their structures in the dimension?

**Comment by Andromander** [comment]
It should be up to the other mods to stop their structures from spawning in our dimension, not us. That's not how worldgen works.

**Comment by Tamaized** [comment]
Yes, use the offending mod's dimension blacklist config. If they don't have one then yell at them to add one.
