### ISSUE TITLE
(Suggestion) Knight Phantoms share a boss bar, totaling their HP

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#1194]
Minecraft has scriptable boss health bars, such as Raids and the Ender Dragon

**Comment by Tamaized** [comment]
This is already planned but it's difficult to implement.

My idea is to only have the 'Main' phantom display the bar and handle updates but when that dies it may cause temporary quick derendering of the bar until the new main preforms the next render. Which is not ideal.

**Comment by Tamaized** [comment]
Implemented in 84ae5d7403f216440c0a09ddca4fdc488195e6ee
