### ISSUE TITLE
Portal Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [TeamTwilight/twilightforest#1195]
`Forge v36.1.32`
`Twilight Forest v4.0.490`

Steps to reproduce:
1. Make a portal
2. View with The One Proble

What I expected to happen:
- The name should display as "Twilight Portal" or similar.

What happened instead:
- The name is missing from the `en_us.json` file, displaying as `block.twilightforest.twilight_portal` instead when viewed with The One Probe.

![2021-07-01_20 36 11](https://user-images.githubusercontent.com/12000593/124519853-3a7a2c80-ddb0-11eb-9a0e-678491e0e939.png)

**Comment by Azar2477** [comment]
I will see if there is in the translation key so they can fix your issue by creating a pull request.

**Comment by Azar2477** [comment]
The block.twilightforest.twilight_portal is missing on en_us.json and other files in the lang folder and that's easy to fix.
