### ISSUE TITLE
Textures failing to load using the Chlorine mod

### ISSUE THREAD

**Issue by Mopaseo** [TeamTwilight/twilightforest#1198]
Forge version: 36.1.10
Twilight Forest version: 4.0.490

Steps to reproduce:
1. Download the mod Chlorine version 0.0.1.3 with Twilight Forest
https://www.curseforge.com/minecraft/mc-mods/chlorine/files/3199916

What happened : 

The textures of 9 items from the mod (twilight oak wood, canopy door, mangrove door, darkwood door, timewood door, transwood trapdoor, transwood door, minewood door and sortigwood door) won't load while using the Chlorine mod. Since Optifine isn't available with Twilight Forest and Chlorine being a very good alternative, thought it might be a good idea to find a solution to this inconvenience. I tried this with and without a modpack and also in a server and I had this bug everywhere.
_(ps: I'm new to mods and stuff so if I did something bad pls lmk!)_

![2021-07-07_22 35 47](https://user-images.githubusercontent.com/86983903/124830414-1c602800-df7a-11eb-8270-1e81da298fa1.png)
![2021-07-07_22 35 49](https://user-images.githubusercontent.com/86983903/124830427-21bd7280-df7a-11eb-882c-8c0dbed8710c.png)

**Comment by Tamaized** [comment]
This isn't a chlorine issue, those textures and models never existed in the first place.

**Comment by GizmoTheMoonPig** [comment]
the textures dont exist. This is our fault, not theirs. Theres already an issue open about the textures (#1035)
