### ISSUE TITLE
The texture of some items are wrong

### ISSUE THREAD

**Issue by Cunning-Carp** [TeamTwilight/twilightforest#1199]
Forge version: 36.1.32
Twilight Forest version: 4.0.490
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Launch game and see that the following texture is wrong (fiery boots, fiery chestplate, fiery helmet, fiery ingot, fiery leggings, fiery pickaxe, fiery sword)
![1](https://user-images.githubusercontent.com/82739716/124868070-cdee7000-dff1-11eb-80ea-5da8b5b9d46b.png)

What I expected to happen: Can display normally

What happened instead:

**Comment by Azar2477** [comment]
I will see so they can help you.

**Comment by Tamaized** [comment]
Are you using shaders, that's what causes this.

**Comment by Azar2477** [comment]
For me it's fine and the shaders cause this.

**Comment by BurnutsGaming** [comment]
What shaders did you use?

**Comment by PechayClub** [comment]
You might have used Optifine to load the shaders.

**Comment by GizmoTheMoonPig** [comment]
Hey there, was having a chat on our discord with someone who was having the same issue, and it was confirmed to be a shader issue. I wanted to learn a little more about what causes this, so could you tell me which shader pack you were using? Im curious to see if its certain shaders causing this or just them in general. Thanks!

**Comment by Azar2477** [comment]
If it's the Optifine shaders that cause this, then the issue will be labeled as Optifine.

**Comment by Tamaized** [comment]
Azar, please. You're really not helping with all these redundant comments everywhere.

**Comment by Azar2477** [comment]
Ok

**Comment by Pechayland** [comment]
Not helpful @Azar2477

**Comment by Cunning-Carp** [comment]
> 嘿，有一个关于我们的不和谐聊天的人谁是有同样的问题，它被证实是一个着色器问题。我想了解更多关于是什么原因造成的，所以你能告诉我你使用的着色器包？我很好奇，看看它的某些着色器造成这一点，或只是他们在一般情况下。谢谢！

BSL_v8.0.01

**Comment by CunningCarp0** [comment]
> 你用了什么着色器？

**Comment by Cunning-Carp** [comment]
> 你用了什么着色器？

BSL_v8.0.01

**Comment by GizmoTheMoonPig** [comment]
alright, after testing this with a couple other shaders myself, I can indeed confirm this is a universal shader issue. I tried poking around in different configs to see if there was a way I could prevent this from happening, but I believe its an internal thing that we cant really mess with. Unfortunately, this is something that we cant fix, so im gonna be closing this.
