### ISSUE TITLE
Have the lich drop an item that would alow the player to cast the shield it uses.

### ISSUE THREAD

**Issue by Darkfiremario** [TeamTwilight/twilightforest#12]
The shields that orbit around the lich are just as iconic as the scepters it drops when you defeat it. Seeing how overpowered these shields are, maybe balance them in such a way that the players cant abuse the crap out of it. Maybe have the lich drop it as a scepter capable of casting the thing, but has very limited amounts of use. The drop itself can also be rare, just to make it more special.

This idea came up on the TF Discord.

**Comment by Drullkus** [comment]
Implementation idea:

Actual Shield Item that spawns the floating shield items. Has durability based on number of shields left. Not deleted when broken. Must be crafted with a fuel item to replenish shields. Must be held in one of the hands.
