### ISSUE TITLE
Clouds are visible through Final Castle Vanishing Blocks

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#120]
Forge version: 13.20.0.2315
Twilight Forest version: 2.4.0.91

Looking through the Final Castle Vanishing Blocks can cause the clouds to be visible, despite the clouds being behind the block
![2017-07-23_16 37 30](https://user-images.githubusercontent.com/29526717/28497218-aaabe730-6fc5-11e7-87fc-baeb13c5a3f0.png)

**Comment by Tamaized** [comment]
Seems to only happen while above the clouds
