### ISSUE TITLE
1.16.5 server crash

### ISSUE THREAD

**Issue by Daejangnamu** [TeamTwilight/twilightforest#1200]
[crash-2021-07-09_21.41.59-server.txt](https://github.com/TeamTwilight/twilightforest/files/6791916/crash-2021-07-09_21.41.59-server.txt)
forge-1.16.5-36.1.32
twilightforest-1.16.5-4.0-universal

**Comment by Andromander** [comment]
This should hopefully be resolved via 88e16b7.
