### ISSUE TITLE
Prevent block placement in restricted areas.

### ISSUE THREAD

**Issue by Eggflames** [TeamTwilight/twilightforest#1203]
i was exploring around the twilight forest as someone who didnt know much about the mod yet. I went inside the dark forest not knowing i wasn't supposed to be there, and i found the structure that was listed in the book about the stronghold. but since the mobs were tough i boxed myself in for a sec to try and protect myself. Turns out, there's protection in that area when you haven't killed the hydra yet and all my stuff got stuck there including my best armor that i usually kept stored in an armor stand. could you please not make players able to place blocks in areas with protection?

Forge version: 36.1.0
Twilight Forest version: twilightforest-1.16.5-4.0.490-universal

**Comment by Andromander** [comment]
I mean...I feel like swirling yellow boxes would be an indicator that something is off and the biome granting negative effects should be a reason to turn back, but we could look into preventing block placement in protected areas.

**Comment by Eggflames** [comment]
there were no swirling yellow boxes, the only times i've seen them is when i went to kill the hydra (it's been 7 days since the og comment) after i killed the mushroom minotaur

**Comment by EvergreenSystems** [comment]
I am reasonably sure that the dark forest has these dark tentacle-like things that swirl up instead of the boxes as it’s “locked” signifier (at least it did in 1.12.2)

**Comment by Burnuts** [comment]
Forge 1.17 is here.

**Comment by Burnuts** [comment]
I deleted that comment.

**Comment by Drullkus** [comment]
Partial resolution with [8f51178](https://github.com/TeamTwilight/twilightforest/commit/8f511786ee24f37f239645043abfe3dccd8b4d28), though the item will *look* consumed on the client (but it's still there on the server, go open a chest to re-sync your inventory)

**Comment by Drullkus** [comment]
Inventory re-synced via 8acbf9f
