### ISSUE TITLE
Player skin hat layer overlaps Yeti head

### ISSUE THREAD

**Issue by WenXin20** [TeamTwilight/twilightforest#1204]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Twilight Forest v4.0.490`

Steps to reproduce:
1. Equip Yeti head
2. Observe

What I expected to happen:
- The hat layer of the player skin shouldn't overlap the yeti head.

What happened instead:
- The hat layer of the player skin overlaps the yeti head.

![2021-07-14_01 42 49](https://user-images.githubusercontent.com/12000593/126026362-66d7103d-f2ef-4ed6-8189-2b4fc8bff651.png)
![2021-07-14_01 42 54](https://user-images.githubusercontent.com/12000593/126026364-6e5457e6-403c-40f5-ba97-8766758a2948.png)

**Comment by GizmoTheMoonPig** [comment]
This has been fixed in dev, it will be in the next beta when we decide to release one

**Comment by WenXin20** [comment]
Ah, sounds good. Thanks!
