### ISSUE TITLE
Aurora slab texture on the top is see trough if a block is placed on top of the Aurora slab

### ISSUE THREAD

**Issue by SenpaiCarryMe** [TeamTwilight/twilightforest#1206]
Twilight Forest version: twilightforest-1.16.5-4.0.490-universal.jar

Steps to reproduce:
1. Place a Aurora slab on the lower half
2. Place a block on top 

What I expected to happen:
The texture loading 

What happened instead:
It is a see through so you can use it as cavefinder

![Valhelsia 3 - 1 16 5 20 07 2021 04_03_59](https://user-images.githubusercontent.com/87677072/126254093-69f75c25-2483-41fc-af36-12c0404a9bfe.png)

**Comment by Andromander** [comment]
I know it's probably easy to reproduce and thus visual evidence isn't required, but can you attach the image directly to the issue rather than a Google Drive link? It's inaccessible.
