### ISSUE TITLE
Portal is created succesfully but when jumping in doesn't teleport to Twilight forest

### ISSUE THREAD

**Issue by Huntard220** [TeamTwilight/twilightforest#1209]
Forge version: 36.1.66
Twilight Forest version: 4.0.490
Link to crash log: (there's nothing here for some reason)

Steps to reproduce:
1. Create the portal
2. Jump in

What I expected to happen:
Teleport to the Twilight forest

What happened instead:
Nothing (literally)

Note: the lightning hits the Water and actually creates the portal, but nothing happens when jumping in, the achievement does pop out.

**Comment by temp1029** [comment]
Same for me. I'm playing through Skyopolis 4 (version 11.1) and I created the portal, started it (got lit on fire by the lightening) but when I jump in it doesn't "wisk me away to the twilight forest".

**Comment by Drullkus** [comment]
Can't reproduce
