### ISSUE TITLE
Game crashed when fightwith naga

### ISSUE THREAD

**Issue by Origins-Eternity** [TeamTwilight/twilightforest#1210]
Forge version:14.23.5.2855
Twilight Forest version:3.11.1021
Link to crash log:https://pastebin.com/Hd2UdAx4

Steps to reproduce:
1. I entered twilight forest
2. I found naga
3. I began to fight with naga

What I expected to happen:I can beat naga

What happened instead:The game crashed

**Comment by bs2609** [comment]
Sounds like this might be a duplicate of #817.

**Comment by Origins-Eternity** [comment]
> Sounds like this might be a duplicate of #817.

Ok, thanks.
