### ISSUE TITLE
The 'Jack and the Beanstalk' Advancement Does Not Complete

### ISSUE THREAD

**Issue by TalisRegis20** [TeamTwilight/twilightforest#1211]
Forge version: 36.1.16
Twilight Forest version: 4.0.490
Link to crash log: No crash
Steps to reproduce:
1. Find the Magic Beans in the Troll Caves
2. Use them on the Uberous Soil and grow the beanstalk
3. Climb up to the Giant's Cloud

What I expected to happen:
The advancement to complete as normal

What happened instead:
The advancement didn't grant. The kill a Troll advancement completes, and the advancement, 'Im on Cloud Nine' also completes.

**Comment by GizmoTheMoonPig** [comment]
this was fixed in the latest beta, please update the mod.
