### ISSUE TITLE
The Hydra has no head and the Naga has no tail.

### ISSUE THREAD

**Issue by Miha573** [TeamTwilight/twilightforest#1212]
When a Naga from the spawner appears, only her head is visible, and her tail is not visible. In the Hydra, on the contrary, only the trunk and legs are visible, there are no heads.

**Comment by GizmoTheMoonPig** [comment]
remove optifine or entity culling, whichever you have

**Comment by Miha573** [comment]
> удалите оптифин или отбраковку сущностей, в зависимости от того, что у вас есть

Thank you
