### ISSUE TITLE
Death in Twilight Forest made my TF portal lead to wrong location

### ISSUE THREAD

**Issue by LuciusV** [TeamTwilight/twilightforest#1213]
Forge version: 36.1.65
Twilight Forest version: 1.16.5 - 4.0.490
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1.  I died on trapped chest in Twilight forest, and after that portal in Twilight Forest which should took me back to my overworld portal takes me to new portal in Overworld in the middle of the ocean nearby. Portal in overworld functions normally

What I expected to happen:
Portal in Twilight forest takes me to first portal in Overworld
What happened instead:
Portal in Twilight forest takes me to new portal in Overworld

**Comment by GizmoTheMoonPig** [comment]
redirecting this to #1459 so we can keep track of every portal issue in 1 place
