### ISSUE TITLE
Lich floats through floating gravel

### ISSUE THREAD

**Issue by Creepingpasta** [TeamTwilight/twilightforest#1216]
Forge version: 36.2.2
Twilight Forest version: 1.16.5-4.0.515-universal
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

https://user-images.githubusercontent.com/40845652/127423658-ed950dc0-f1b8-4378-8cbb-58f83870b340.mp4

What I expected to happen:
Lich not to float through the floating gravel
What happened instead:
Lich floated through floating gravel

**Comment by Tamaized** [comment]
This looks normal to me, the lich hitbox extends above 2 blocks so it's technically inside the third block, vanilla mechanics state you can travel upward through blocks you're already inside.

This is all normal vanilla behavior. 

Try this with a wither skeleton.
