### ISSUE TITLE
Ur-Ghast's Fireball not exploding when hitting other blocks

### ISSUE THREAD

**Issue by entrechienetloup** [TeamTwilight/twilightforest#1219]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 
![image](https://user-images.githubusercontent.com/40696228/127732645-ad0e1220-05e7-4333-a871-3e4f3d5cccdc.png)

What I expected to happen:
Fireballs to explode upon hitting instead of entering other blocks
What happened instead:
Fireballs entered other blocks

**Comment by Andromander** [comment]
There doesn't appear to be a version of Twilight Forest specified. Which version does this occur on, and if possible to answer, what other mods are installed?

**Comment by entrechienetloup** [comment]
<img width="192" alt="1629512924(1)" src="https://user-images.githubusercontent.com/40696228/130307753-dda7ba79-1b27-4191-aa13-2bb0526ba7f2.png">
