### ISSUE TITLE
crash wen

### ISSUE THREAD

**Issue by chasiopen** [TeamTwilight/twilightforest#1220]
Forge version: 36.1.63
Twilight Forest version: twilightforest-1.16.5-4.0.515
Link to crash log: https://gist.github.com/chasiopen/4a89b1453b1ad0c379c40aaca839b9cc

Steps to reproduce:
1. Fight with YetiAlpha
2. YetiAlpha through the ice block
3. Boom!crash!

What I expected to happen:

What happened instead:

**Comment by GizmoTheMoonPig** [comment]
Caves and Cliffs mod is causing it, try without it and let me know

**Comment by chasiopen** [comment]
You are right.It works regularly without CACmod. 
thx
But CAC is a  excellent mod，ilove it.
Considering about some  compatibility？

**Comment by GizmoTheMoonPig** [comment]
its not our fault its crashing, this is an issue on their end. I would talk to them about it because they obviously arent doing something right

**Comment by chasiopen** [comment]
i will report it to them too,thx
