### ISSUE TITLE
Kill the Minoshroom Achievements

### ISSUE THREAD

**Issue by Sukastros** [TeamTwilight/twilightforest#1223]
Hey !

So i have a problem with an achievement in the Twilight Forest. I went into the Twilight Forest, killed the Naga, then killed the Lich, I got the achievements for all of them. After that I killed the Minoshroom, but I didn't get the achievement for that, I already killed 5 of them and still nothing.
I got the Mighty Stroganoff advancements and killed the Hydra, so I don't know what is not working.

**Comment by GizmoTheMoonPig** [comment]
in order to get the minoshroom achievement, you have to eat the meef stroganoff he drops

**Comment by Sukastros** [comment]
I already ate the meef stroganoff, I got the advancement, but I'm talking about the achievement "Kill the Minoshroom" in the quests tab. I killed the Twilight Lich and got the reward, so the quest is unlocked but when I kill the Minoshroom it doesn't confirm the quest.

**Comment by GizmoTheMoonPig** [comment]
we dont have a quest book, this is more of an issue to talk to a pack dev about if youre playing a pack

**Comment by Sukastros** [comment]
Oh, I thought this was linked to this mod, my mistake, sorry.
Thank you for your time and your help =)

**Comment by GizmoTheMoonPig** [comment]
all good
