### ISSUE TITLE
Freezing the game after world generation

### ISSUE THREAD

**Issue by Toma400** [TeamTwilight/twilightforest#1224]
Forge version: 1.16.5
Twilight Forest version: 4.0.515
Link to crash log: -

Steps to reproduce:
1. Have Twilight Forest installed before step 2
2. Make a new world

What I expected to happen: new world to be generated

What happened instead: game freeze once world generation counter reaches random percent

**This issue is not happening if world was created without Twilight Forest and TF was loaded after generation.**

**Comment by Tamaized** [comment]
Does this occur without any other mods, as this usually happens when a structure or feature from another mod is trying to generate in TF

**Comment by Toma400** [comment]
I used absolutely minimum of mods, being them BetterEnd, Mowzie's Mobs and Infernal Expansion. I'm 50% sure that I even tried to play TF alone to see if it happens. Either way, none of these mods affect overworld generation afaik, so it's kinda weird.

**Comment by AlienXtream** [comment]
+1

heavy modded. lots of structures. too bad it deadlocks before it can log what structure is failing to generate

**Comment by Drullkus** [comment]
@AlienXtream Is this 1.16. or 1.17?

In 1.17 we identified a few causes for worldgen stalls and fixed them. Please let us know your version if in Minecraft 1.17

**Comment by AlienXtream** [comment]
ah. sorry. didn't realise you were already updated to 1.17 im in 1.16. i know managing multiple versions is a major headache so i wouldn't expect you to backport the fix (assuming its the problem in 1.16) but it would be appreciated. again, not expected. not even requesting it. just expressing gratitude beforehand :)
