### ISSUE TITLE
Traveller's Logbook [WIP]. "Filler image" in book.

### ISSUE THREAD

**Issue by Gelebor** [TeamTwilight/twilightforest#1226]
Forge version: 1.16.5-forge-36.2.2
Twilight Forest version: 4.0.546
Link to crash log: don't have a crash log. It's an issue with Traveller's Logbook [WIP] book.

Steps to reproduce:
1. Create Traveller's Logbook [WIP] book.
2. Explore some stuff.
3. Open and read the book. For example page about "Druid Huts".

What I expected to happen:
I expected to see in-game descriptions and images in the book.

What happened instead:
I see in some places blank pages in the book, sometimes without images or with an image with the text "Filler image.

![2021-08-07_12 01 18](https://user-images.githubusercontent.com/88577066/128595002-2baffe38-22b1-4a18-a3ce-c294867a112d.png)
![2021-08-07_11 46 03](https://user-images.githubusercontent.com/88577066/128595003-85c1ac7d-8b97-4374-bc68-d2bdce5a63c3.png)
![2021-08-07_12 00 46](https://user-images.githubusercontent.com/88577066/128595004-a3ec5947-d8e9-4194-bed0-cc56de1bb3ce.png)
![2021-08-07_12 01 01](https://user-images.githubusercontent.com/88577066/128595005-11123c96-9d88-4f68-83ff-4549f89f5687.png)
".

**Comment by Tamaized** [comment]
We never ported the book in 1.16 I don't think, not to mention the entire thing has always been wip

**Comment by Gelebor** [comment]
Is there any other way to learn about the world of Twilight Forest?

**Comment by Tamaized** [comment]
Exploration

**Comment by Gelebor** [comment]
It means that this book is superfluous content?
When exploring something new, the game announces about new discoveries.  So I wonder how to treat it.

**Comment by Drullkus** [comment]
The filler image is utilized when there’s an orphan page without content
