### ISSUE TITLE
intermittent crashing when exploring TF

### ISSUE THREAD

**Issue by boomsticked** [TeamTwilight/twilightforest#1227]
Forge version: 14.23.5.2855
Twilight Forest version: 3.11.1021
Link to crash log: https://pastebin.com/uz4hnqsV (vanillafix)

Steps to reproduce:
1. enter twilight forest
2. fly around in creative and load chunks
3. game will crash, seemingly more frequently around the dark forest biome

What I expected to happen: the mod would stop crashing after I blacklisted the dimension for ice and fire + tinkers construct world gen

What happened instead: still crashes. I noticed there would often be a strange visual glitch moments before the crash to launcher. sometimes there would be black lines in the sky, most of the time a bunch of textures(?) would flood the screen and tank the framerate.

**Comment by Andromander** [comment]
Stacktrace and the report are indicating the problem may be towards Baubles, however I suspect the error is elsewhere as Twilight Forest and Baubles are capable of running together. I would recommend doing a binary search of the mods to find the real culprit, however, 1.12.2 is no longer a supported version.

**Comment by boomsticked** [comment]
I've been testing a bit more now and I think the crashes might be just from generating the thorn biome and/or getting near it. the dimension runs pretty well outside of that area but as soon as I fly above it the framerate tanks and the server shuts down. Probably not much of a problem in real gameplay since you're not generating so many thorns so fast. Maybe I'm wrong though since it doesn't really explain the visual bugs I had before.

**Comment by GizmoTheMoonPig** [comment]
> sometimes there would be black lines in the sky, most of the time a bunch of textures(?) would flood the screen and tank the framerate

This sounds a lot like the dark forest locked biome effect, although I don't see why it would crash the game. Regardless, since we don't support 1.12 anymore there's no point in keeping this issue open. If something like this happens in a more modern version (if you play above 1.12, I know people like to stick to that version) please let us know.
