### ISSUE TITLE
Uberous Soil Particles when holding Magic Beans

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#1229]
When you hold the Barrier Item, Barrier Blocks use particles to show their locations - would it be possible to have green sparkling particles seen when bonemealing crops, on top of Uber Soil when holding Magic Beans item?

**Comment by Killer-Demon** [comment]
For further elaboration on the visuals of the particles:
They'd ideally be on the small side, rise up from anywhere on the top surface of the block, float up for a small distance, and then fade out of existence.
