### ISSUE TITLE
Twilight Forest loading screen glitches and game crashes

### ISSUE THREAD

**Issue by PechayClub** [TeamTwilight/twilightforest#1231]
Forge version: 37.0.33
Twilight Forest version: 4.0.566 (Minecraft 1.17.1)
Link to crash log: https://gist.github.com/Pechayland/6bd112690ff688e26c1d97bfc376861f

Steps to reproduce:
1. Go to the Twilight Forest

What I expected to happen:
It should let me go to the Twilight Forest without a glitching loading screen.

What happened instead:
The loading screen glitches like this before the game crash:
![2021-08-13_18 03 10](https://user-images.githubusercontent.com/65995040/129341711-8555cba8-69ba-49c2-8ebe-c62cb3d1d773.png)

**Comment by Tamaized** [comment]
Not sure what you're expecting. We literally JUST got the mod to compile last night....

**Comment by PechayClub** [comment]
Try going to the Twilight Forest with the this version of Twilight Forest mod to reproduce it and let me know if it shows that glitched screen in game.
Additionally I recorded the gameplay to reproduce this.

https://user-images.githubusercontent.com/65995040/129354003-6cdab13a-519f-4772-b509-ff203593c37b.mp4

**Comment by PechayClub** [comment]
Still crashes. Won't close.
https://user-images.githubusercontent.com/65995040/129354003-6cdab13a-519f-4772-b509-ff203593c37b.mp4

**Comment by Andromander** [comment]
`client-1.17.1-20210706.113038-srg.jar`

What is this?
Also, not sure why this is being treated with urgency; you are downloading development versions that were only just recently managed to load into a world.

**Comment by PechayClub** [comment]
Still the same with the latest. I bet it's a Forge issue.

**Comment by PechayClub** [comment]
That issue doesn't exist in Forge maybe, but I will make one and check if there will be a duplicate.

**Comment by PechayClub** [comment]
It's your mod not Forge. https://github.com/MinecraftForge/MinecraftForge/issues/8015

**Comment by Andromander** [comment]
Gee, really? A feature that has currently not been tested and is currently in a development environment doesn't work?

You are verging on being extremely spammy, even on Forge's end because you 1. Reported a mod problem to Forge, 2. Reported a bug on a ***DEVELOPMENT*** version to them. How many times do we need to emphasise that you are trying to desperately report a bug on a version that isn't publicly released?

**Comment by TheCurle** [comment]
When i said that there's an issue with Twilight Forest, i wasn't expecting you to come here and spam them.... 

Apologies to the maintainers.

**Comment by Tamaized** [comment]
User has been Blocked due to many of these types of issue submissions

**Comment by Andromander** [comment]
@TheCurle I was about to do the same for having someone report this issue to your end. This version shouldn't even be for public use outside of bug testing.
