### ISSUE TITLE
Optifine warning ignores config option

### ISSUE THREAD

**Issue by Clawthorn** [TeamTwilight/twilightforest#1233]
Forge version: 36.2.0
Twilight Forest version: 1.16.5-4.0.490 **(part of All The Mods 6 pack)**
Link to crash log: _(Not relevant)_

Steps to reproduce:
1. Launch Minecraft
2. See the Optifine warning screen
3. Shut down Minecraft
4. Edit `twilightforest-client.toml` and set `disableOptifineNagScreen` to `true`
5. Start up Minecraft again
6. Still get the Optifine warning screen

What I expected to happen:
That it would disable the nag screen.

What happened instead:
It is still showing the nag screen every single time the game launches.

**Comment by GizmoTheMoonPig** [comment]
just tested this in the most recent 1.16 version (its impossible to load up optifine and TF together in 1.17 at the moment) and the config option worked just fine. Make sure you actually saved the file after making the change

**Comment by Zaykana** [comment]
Can confirm the person's comment above. I also faced this problem and your post actually helped me, I had no idea what to even do before lol. I did this using the 1.18.2 version.

**Comment by iankennedy12** [comment]
it doesn't work on 1.19.4 with optine when i do the process and load a world it does saving world and crashes
is there anyway to delete twlight forest cause when i do it gives me errors and won't let me load the world in safe mode
