### ISSUE TITLE
[1.17.1] Obtaining certain TF items unlocks several Advancements

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#1236]
Forge version: 37.0.33
Twilight Forest version: 4.0.569

When obtaining seemingly any item added by TF, various advancements are unlocks. They appear to have a common criteria trigger. Not sure if it is all items or specific, first time it was Naga Chest, second it was an Adherent Spawn Egg.
The following are unlocked:
- Gallons of Blood and Tears
- I Can See Forever
- Naga Armorer
- Breaking the Maze
- By Our Powers Combined!
- And Now, to Find the Exit
- How Can That Be Worth It?
- Maniacal Dendrologist

When checking the advancements json for the player, all the `alt/` advancements are unlocked.

Criteria are also granted for the following:
- Time to Even the Scales (scales)
- Bring Out Your Dead (lifedrain_scepter, twilight_scepter, shield_scepter, trophy, zombie_scepter)
- Hydra Slayer (trophy, blood)

**Comment by GizmoTheMoonPig** [comment]
fixed when I datagenned advancements
