### ISSUE TITLE
[1.17.1] Lower Goblin Knight perma-crash

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#1237]
Forge version: 37.0.33
Twilight Forest version: 4.0.569
Link to crash log: https://gist.github.com/Andromander/3503e58a8400217a3fb6e31074f126a4

Simply spawning one in from a spawn egg (at least) causes the world to crash and remain in this crash state when trying to reload.

**Comment by Andromander** [comment]
Update: When spawning individually, it's actually the Lower Goblin Knight that causes this crash.

**Comment by GizmoTheMoonPig** [comment]
fixed this when I was fixing up models, forgot to close this
