### ISSUE TITLE
[1.17.1] Entity models to fix

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#1238]
Following mobs have a broken model due to translation problems mid-port, or some other problem.
| Mob | What's Broken |
| --- | --- |
| Alpha Yeti (Done) | "Head" is treated literally as a head, causing eyes and horns to float. Arms are missing. Right Leg box size is...very tiny. |
| Bighorn Sheep (Done) | Wool for the legs have mismatched rotation. Horns are just gone.
| Block and Chain Goblin (Done) | Block appears to jutter. A spike that should be on the edge is actually on the corner. Chain intermittently and very rapidly blinks into existence. |
| Carminite Ghastguard (Done) | Good god, I don't know what is happening. Head size is right but UVs are wrong, but the tentacles extend far backwards. |
| Carminite Ghastling (Done) | Jut a smaller Carminite Ghastguard problem. |
| Carminite Golem (Done) | Body part is shunted into the Torso, dimensions seem right. |
| Death Tome (Done) | Model parts seem all right, but it appears to be floating on an angle, about 45 degrees. |
| Wild Deer (Done) | Body part is rotated 90 degrees. |
| Goblin Knight (Upper) (Done) | Head is missing that 45 degree rotation so isn't facing forward, as well as being offset wrong. |
| Goblin Knight (Lower) (Done) | TBD, don't try. |
| Helmet Crab (Done) | Horns on the helmet are offset incorrectly, just floating above. |
| Hydra (Done) | Model parts are okay. Heads are stuck in the middle of the body and the necks are stiff. |
| Knight Phantom (Done) | Model parts are okay when visible. Missing the armour and therefore is invisible when inactive. |
| Kobold (Done) | Head is missing. Left hear has incorrect offset. |
| Minoshroom (Done) | Arms appear to be on the cow body, may also have incorrect UVs as top of the arms are invisible. |
| Naga | I'm going to guess the model parts are okay, but the whole body disappears leaving only the head. Should the tongue be flicking? |
| Penguin (Done) | Why is there two of them? |
| Questing Ram (Done) | Body is missing; could be a side effect of the body rendering. Head and neck(?) are offset incorrectly. Horns are missing. Segments render just fine. |
| Forest Raven (Done) | Wing and tail are offset much higher then the body. Everything else is clear. |
| Redcap Goblin (Done) | Left leg is offset to the left arm position. Boots are a bit too low? |
| Redcap Sapper (Done) | A green version of the Recap Goblin problem. |
| Roving Cube (Done) | Not sure if the cube is rendered too big or the particles aren't scattering wide enough. There's also a missing effect where the cube has transparent shuddering effects | 
| Skeleton Druid (Done) | UVs are all over the place, no foliage cloak. Pixels look...stretched? |
| Slime Beetle (Done) | There is no body, only tail. Tail tip is also solid, no transparency. |
| Snow Queen (Done) | Body is fine, but there's no icy shield. Unrelated, but she can't fly for some reason. |
| Stable Ice Core (Done) | TBD. Don't try. |
| Twilight Lich (Done) | Legs are offset too high. |
| Unstable Ice Core (Done) | TBD. Don't try. |
| Ur-Ghast (Done) | Wrong kind of tentacle monster...if it can be called that, to be honest. I suspect the texture UVs are smaller than the texture size itself. |
| Twilight Wraith (Done) | Model parts are fine, but transparency is missing. |

**Comment by GizmoTheMoonPig** [comment]
alright only the ghasts are left, im leaving those up to drull since he made the 1.17 logic for them

**Comment by Drullkus** [comment]
Fixed Ghasts in 9e7b8e84e24c9da710c936ee9616b33b4e792f63

Naga and Hydra confirmed fixed too
