### ISSUE TITLE
Twilight forest portal not spawning

### ISSUE THREAD

**Issue by Thr3e8** [TeamTwilight/twilightforest#1239]
I submitted this issue last night but it was closed without anyone saying anything. But that being said I try to build the portal for the twilight forest and when I throw the diamond in it does nothing. No lightning, no portal, nothing. I'm playing this through the better Minecraft modpack 1.16.5

**Comment by Tamaized** [comment]
Because it's a duplicate, it WAS stated. Even with the issue linked.

**Comment by Tamaized** [comment]
However now that you've given more information, it sounds like the portal activation item was changed for the pack you're playing... In other words this isn't even an issue at all.
Consult the pack devs if it's confusing what item is required.

**Comment by Thr3e8** [comment]
Ok can you send me the link to the one that is already open I couldnt find it
