### ISSUE TITLE
Magic map, posibil bug

### ISSUE THREAD

**Issue by VeganAcuracy0** [TeamTwilight/twilightforest#1243]
Forge version: 36.1.2
Twilight Forest version: 4.0.546

Created Magic map in Overworld and it gave me a odd map with grass and sand
when re'creating in Twilight forest gives me the same map even after re loading the world

**Comment by GizmoTheMoonPig** [comment]
magic maps cant be made in other dimensions anymore in 1.17, so that will fix this issue
