### ISSUE TITLE
Crash During Roguelike Adventures and Dungeons 1.42 Server with Hamachi

### ISSUE THREAD

**Issue by AWDangel** [TeamTwilight/twilightforest#1245]
So im starting to have this problem, i just play with 2 friends, for fun, and we get the server crashed everytime we are exploring.
![image](https://user-images.githubusercontent.com/33313409/130364887-9d415860-0f29-4277-a469-d151fff00dde.png)

if some can help me would be awesome, we jsut wanna keep playing this awesome modpack, thnks.
Ask for any archive or whatever, ill repond asap. thnks :D

**Comment by GizmoTheMoonPig** [comment]
I dont see a crash here, can you send the crash log so I can take a look?

**Comment by AWDangel** [comment]
where i can find it??, The probelm 

> I dont see a crash here, can you send the crash log so I can take a look?

where i can find it??, The probelm i have is the last  line "Causing cascading worldgen lag"
This is the issue, when im exploring with my friend, hte server just froze and brokes. i do have 12gb of ram for the server but still having this issue :C

**Comment by AWDangel** [comment]
[hs_err_pid17924.log](https://github.com/TeamTwilight/twilightforest/files/7039056/hs_err_pid17924.log)
[hs_err_pid27940.log](https://github.com/TeamTwilight/twilightforest/files/7039057/hs_err_pid27940.log)
[hs_err_pid9844.log](https://github.com/TeamTwilight/twilightforest/files/7039058/hs_err_pid9844.log)
 This is the only "error" files i can find, they said insuficient RAM? but i have 12gb D: i cant put more i only have 16gb on my pc, hope someone can help me
![image](https://user-images.githubusercontent.com/33313409/130616179-9375f44c-09f4-4dc1-9d7a-f082d79b233e.png)

**Comment by Andromander** [comment]
Best I can say here is lowering the amount of RAM allocated as one of the possible solutions suggests. Likely, too much RAM has been allocated.

**Comment by Drullkus** [comment]
Closing because older versions are not supported and this appears to be a RAM problem
