### ISSUE TITLE
Load Up Error

### ISSUE THREAD

**Issue by IceyGunter** [TeamTwilight/twilightforest#1249]
Forge version: 
Twilight Forest version: Twilight Forest - MC 1.16.5 - 4.0.546
Link to crash log: ![Screenshot (2)](https://user-images.githubusercontent.com/89666881/131193321-7e147c9b-06a8-4e8f-8640-5a1bdf32249c.png)
Steps to reproduce:
1. Open Modpack threw curseforge
What I expected to happen:
Game Load as usuall
What happened instead:
Game failed to load

**Comment by Tamaized** [comment]
you need to post the log

**Comment by Killer-Demon** [comment]
I'm closing this issue as no other way of helping was provided. Feel free to re-open the issue if you happen to find the log file.
