### ISSUE TITLE
Alpha Yeti Cave bugged

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1251]
Forge version: 1.17.1(whatever version the modpack on)
Twilight Forest version: 4.0.655
Link to crash log: n/a

Steps to reproduce:
1. go to the alpha yeti cave, which will be bugged, then spawn in the alpha yeti.

What I expected to happen: it to be an open cave, with the alpha yeti having free roam to attack the player

What happened instead: the alpha yeti being trapped in icicles mixed with stone hanging from the ceiling all the way to the bottom of the cave
![2021-08-29_05 48 49](https://user-images.githubusercontent.com/68449401/131247972-368110e1-6659-4ce7-bf1f-188cd35b22e0.png)

**Comment by Drullkus** [comment]
Fixed via b098ddce8b99d39a08cc16710eb5a77d3f42bcfb
