### ISSUE TITLE
hollow hill glitch

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1253]
Forge version: whatever version the modpack is on.
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce: go to the coordinates provided on the seed provided. and find the hollow hill
1. 

What I expected to happen: for the hollow hill to have generated normal

What happened instead: for the stalactites to be above the ground level
![2021-08-29_06 06 28](https://user-images.githubusercontent.com/68449401/131248559-fb2a354e-8e2e-44a4-b05c-12b0fcf295ef.png)
![2021-08-29_06 09 07](https://user-images.githubusercontent.com/68449401/131248564-a6b06321-9297-4c21-b690-ff4b20b43704.png)
![2021-08-29_06 09 14](https://user-images.githubusercontent.com/68449401/131248567-56a4bfef-f7aa-4b44-932d-002deb0ad528.png)

the robust tree glitch is also at this location

**Comment by Drullkus** [comment]
Fixed via b098ddc
