### ISSUE TITLE
Phantom Knight Stronghold Exposed/Misleveled

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1257]
Forge version: 1.17.1 modpack version
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

the phantom stronghold was exposed/misleved a little bit. like, it wasnt just a slight thing, it was literally poking out of the ground like a sore thumb. again, im not sure if these glitches are natural or whatever, i will be posting more as i get to them, but i was just reporting it
![2021-08-29_07 42 24](https://user-images.githubusercontent.com/68449401/131253728-ee121132-0dcb-414c-8e75-1f71b3105d8a.png)
![2021-08-29_07 34 13](https://user-images.githubusercontent.com/68449401/131253732-fcfc60f9-3a5c-482c-aaae-d480da7a61b6.png)

**Comment by Drullkus** [comment]
The overexpansion I can fix, but the entrance is meant to stick out of the ground like that

**Comment by Drullkus** [comment]
This is looking *pretty* fixed now. They'll still bleed out into rivers and stuff which I can't really promise to be fixed but I've fixed it *enough* to hold us, until we redesign this structure
