### ISSUE TITLE
Missing Giant Lily Pad Textures

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#126]
Forge version: 13.20.0.2315
Twilight Forest version: 2.4.0.102

Textures for the Giant Lily Pad are not rendering. They only appear as checker squares with text.
![2017-07-30_13 47 30](https://user-images.githubusercontent.com/29526717/28750437-25c82f06-752e-11e7-8987-41e5fb2066eb.png)

**Comment by Drullkus** [comment]
Yes, I accidentally removed a model. Will fix

**Comment by Drullkus** [comment]
Fixed via 8dbfaac
