### ISSUE TITLE
ghast tower misleveled 

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1260]
Forge version: 1.17.1 modpack version
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

the ghast tower is buried a little bit, making it to where the entry is almost impossible.
![2021-08-29_07 39 31](https://user-images.githubusercontent.com/68449401/131254095-8413f6de-147c-494d-a7a9-6ac833936264.png)

**Comment by Drullkus** [comment]
Fixed via 25801c667bb83af56dd8fdbffc43e845a9fd4a7f
