### ISSUE TITLE
final plateau misleved

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1261]
Forge version: 1.17.1 modpack version
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

i found out that its not just the final castle that is misleveled/bugged, its almost the entirety of the final plateau, as in the thornlands/mountains were at a different level than the twilight forest. with the exceptions of the giants cottage and troll caves, it was pretty much misleveled. and the troll caves were sometimes deeper than usual. i dont have a screenshot, but if you just look into it, you could probably see what i mean

**Comment by GizmoTheMoonPig** [comment]
the highlands and plateau are supposed to be higher than the rest of the TF, thats completely intended. When looking around that area nothing really seemed out of place to me. If you can send screenshots that prove otherwise I can take a look

**Comment by CobaltGlacier** [comment]
i might be able to reload into a world with the same seed and search

**Comment by CobaltGlacier** [comment]
![2021-08-29_14 28 17](https://user-images.githubusercontent.com/68449401/131263023-83065afa-84f8-483d-8db7-4695fa8ee1e5.png)
![2021-08-29_14 28 27](https://user-images.githubusercontent.com/68449401/131263024-eac1cdb4-dc9c-4169-84c7-a0189f7f7ff7.png)

this is what i was talking about. im not sure if the troll caves being deeper than usual was a glitch or not

**Comment by Drullkus** [comment]
It’s above sea level, it’s intended
