### ISSUE TITLE
1.17 World generation stall

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1262]
Forge version: 1.17.1 modpack version
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. go to the twilight forest. then search around, opening up more chunks than you can possibly keep track of. then try to save the world or log out.

What I expected to happen: i expected to log out and it save like normal.

What happened instead: it was stuck on the saving world screen, delaying the crash, and i had to close out of the launcher. i couldnt take a screenshot because of this.

**Comment by CobaltGlacier** [comment]
![2021-08-30_17 08 30](https://user-images.githubusercontent.com/68449401/131412443-fc7721f2-b42e-4749-97e0-9675f76026f1.png)
![2021-08-30_17 08 34](https://user-images.githubusercontent.com/68449401/131412446-3d5624ff-93bc-4c39-9b65-dfb98a4f3cf4.png)
![crash stall](https://user-images.githubusercontent.com/68449401/131412482-8d44421f-3719-4344-9569-d9e4bd13a8ce.PNG)
![crash stall 2](https://user-images.githubusercontent.com/68449401/131412484-57cfe1a3-5214-4a61-83b0-c621b84a84ca.PNG)

**Comment by CobaltGlacier** [comment]
![2021-08-30_17 17 51](https://user-images.githubusercontent.com/68449401/131413103-d580d02d-0697-4384-92de-85526a98d446.png)
![2021-08-30_17 17 47](https://user-images.githubusercontent.com/68449401/131413108-b74f443b-2393-4b0f-ba88-6057c5c5cef7.png)

**Comment by CobaltGlacier** [comment]
this is around the area i reloaded my world into. its usually around the 20,000 x or z coordinets, and possibly -20,000 as well

**Comment by Drullkus** [comment]
x`-524` z`19961` Thanks!

**Comment by CobaltGlacier** [comment]
at least, thats what im gathering with what has been reaccuring. and the screenshots.

also, your welcome

**Comment by Drullkus** [comment]
Closed as duplicate, see #1272 for future resolution
