### ISSUE TITLE
mobs spawning outside of the hollow hill

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1266]
Forge version:  modpack version
Twilight Forest version: 4.0.655
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

the mobs are spawning outside of the hollow hill. when they should be spawning inside it. and there isnt any way they could just walk out. im not sure if this is intentional or not, but im just reporting it
![2021-08-30_10 08 37](https://user-images.githubusercontent.com/68449401/131361533-99b4aee6-107b-4548-962a-2a928c1486b2.png)

**Comment by GizmoTheMoonPig** [comment]
doesnt seem to be an issue anymore from my testing, reopen if it is

**Comment by Swedz** [comment]
Confirmed still an issue. Case that I had it happen in was a medium hollow hill.

Twilight Forest version: 4.1.1027

Seed: 8538490036238121031
Coords: -255, -1007

![2022-05-26_16 26 15](https://user-images.githubusercontent.com/6707125/170574511-c79a7da6-8951-4ed9-a377-4b2f2979b3ee.png)

**Comment by GizmoTheMoonPig** [comment]
ok its fixed for real this time I promise

**Comment by EvergreenSystems** [comment]
Sorry... Seed 6134731083552941833, coords are in the screenshot 

Mod version 4.1.1041
![2022-05-29_14 24 44](https://user-images.githubusercontent.com/23658767/170888285-c6b350ee-62e3-4f94-a327-bc098034be06.png)

**Comment by Darkally33** [comment]
Still seems to be a thing.
Ran into it while playing with 1.18.2-4.1.1423-universal

Did a couple tests on the server pack (1.19-4.2.1421-universal) and confirmed it's still a thing for medium and large hollow hills. It does not seem to happen with small hollow hills.
![2022-10-22_12 51 29](https://user-images.githubusercontent.com/78669103/197362673-1fefa4c2-32e5-42f0-928a-b7f2ad16e91a.png)
![2022-10-22_12 51 46](https://user-images.githubusercontent.com/78669103/197362678-a87e0506-b7ca-4bb0-b171-0cd0f2582fd6.png)
Screenshot was naturally generated,other tests were by blotting out the sun(moon?) with canopy trees and later, giant beanstalks.

**Comment by Tamaized** [comment]
We should turn the hill's single bounding box into 3 or more bounding boxes stacked on top each other like a pyramid. 
That way the smaller boxes the higher you go wont be sticking out of the hill.

Although this means making more components, and it may break stalactites.. maybe it's not worth it. 

Another solution is just having 2 components, 1 which already exists and the 2nd one only covering a small section of Y level that will handle mob spawns, keep the diameter the same as the 1st. just do (floor y level -> floor y level + 10)
