### ISSUE TITLE
error loading mod 1.16.5

### ISSUE THREAD

**Issue by Salmiakkiii** [TeamTwilight/twilightforest#1267]
Forge version: 
Twilight Forest version: (1.16.5-4.0.546)
Link to crash log: https://gist.github.com/Salmiakkiii/e990560c52045910dbf2dfa1d6e4f32a there is both crash and latest log just in case

Steps to reproduce:
1. download the mod
2. open the game
3. crash

What I expected to happen: the mod to load correctly

What happened instead: i get a crash error during sided_setup event phase

**Comment by Andromander** [comment]
Why are you running a 1.17.1 version of Optifine on 1.16.5?
