### ISSUE TITLE
server crashing while exploring  

### ISSUE THREAD

**Issue by GK64** [TeamTwilight/twilightforest#1274]
Forge version: 1.16.5  - 36.2.4 (It's server not singleplay)
Twilight Forest version: Twilight Forest 4.0.546-universal
Link to crash log: https://gist.github.com/GK64/068e25c65a28ca7dc013bcfc0161c592

Steps to reproduce:
1. install TWF and generate world 
2. Kill hydra 
3. exploring other biomes

What I expected to happen: no crash
What happened instead: server crashed, but console doesn't warn anything before crash

I'm playing TWF mod with my friends, but server crashing after kill hydra I checked several times, but I can't find any issue

even I removed the dimension and regenerate it, but still crashing the server after kill hydra and enter other biomes

crash report showing tick and chunk issue, but I don't know why report saying chunk problem and tick, there is no any problem with chunks and tick always on 19 ~ 20 tps 

my modpack are stable in singleplay

(Sorry I'm actually not good at speaking English)

**Comment by Gezeck** [comment]
Hello,
Could you solve it? I have the same problem

**Comment by Andromander** [comment]
As far as I can see with this crash report, it's just the Server Watchdog crashing the server under the assumption that a chunk taking too long to generate is a sign it has crashed. The workaround for this is to change a setting in `server.properties` to a higher number or -1 to give a chunk more time to generate or prevent the Server Watchdog from crashing the server.
It might be that there is a chunk hanging, but it could also just be a chunk needing more time to generate. As far as I know, the official TF server, this kind of crash hasn't been seen.

**Comment by GK64** [comment]
@Andromander Yeah I fixed it few days before just config the watchdog
