### ISSUE TITLE
Post-Lich Boss Sets: Not working right on the dark forest labyrinth area.

### ISSUE THREAD

**Issue by RosaVTuber** [TeamTwilight/twilightforest#1275]
Forge version: 1.16.5
Twilight Forest version: Says NONE on it when I run the Forge Modloader
Link to crash log: [Game didn't crash: Mobs just can't be hit]

Steps to reproduce:
1. Kill the Lich
2. Kill the Minotaur
3. Kill the Hydra
4. Proceed to dark forest area for progression. Find out that none of the mobs can be hit

What I expected to happen: Smooth progression

What happened instead: Mobs are invincible

**Comment by Drullkus** [comment]
> Says NONE on it when I run the Forge Modloader

Where did you download this Twilight Forest build

**Comment by Tamaized** [comment]
All 1.16 builds are marked as NONE, our mod toml file was never populated. I fixed this in 1.17 in this commit
eeb798e7c08a67694878eaec86ed40f309b73f9c

**Comment by Drullkus** [comment]
I determined this was caused by the Goblin Stronghold's bounding box to be above ground, will need to see if this is still happening in 1.17

**Comment by GizmoTheMoonPig** [comment]
did a bit of testing in 1.17 to see if this was still an issue and I never had the bounding box generate too high. Please reopen this if you find this to still be an issue
