### ISSUE TITLE
Are Giants supposed to respawn?

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#1276]
Might want to check out the 1.7.10 code to verify if they're supposed to respawn

**Comment by Andromander** [comment]
I'm not experienced with 1.7.10 code so I can't tell where the logic for spawning Giants are, but based on an old revision of the wiki page, it states:

> The cloud cottage is made of Giant Cobblestone with a Giant Logs as a roof. If left intact, more giants may spawn inside the cottage following normal monster spawning rules.

**Comment by GizmoTheMoonPig** [comment]
pretty sure it worked the same as it does now: 
https://github.com/TeamTwilight/twilightforest/blob/98b88bde74d6db0aa463dba304f5c13acb6140fb/src/main/java/twilightforest/TFFeature.java#L174-L175
Since they're added to the structure spawns, they're free to respawn whenever the mob cap lets them
