### ISSUE TITLE
Missing boss/dungeon generation while using Hexlands II chunk generator [1.16.5]

### ISSUE THREAD

**Issue by Royal-Jelly** [TeamTwilight/twilightforest#1277]
Hexlands II requires overriding the chunk generator to function, however no dungeons/bosses can spawn with the chunk generator being overridden. I was hoping it is not too much to ask for comparability with custom chunk generators.

Cross posted issue for Hexlands II can be found on it's github [here](https://github.com/alcatrazEscapee/hexlands/issues/2#issue-989786863)

**Comment by Drullkus** [comment]
The bad news is that the terrain deformation, structure-locating, and the such is dependent on the chunk generator, this would require a hard dependency and a fully custom ChunkGenerator that implements our stuff

**Comment by Drullkus** [comment]
Just had a brainwave that I can turn our ChunkGenerator into a wrapper

**Comment by Drullkus** [comment]
@Royal-Jelly If you're working on 1.17, please try this out!
