### ISSUE TITLE
ur-ghast tower is still burning  when reaching the middle levels

### ISSUE THREAD

**Issue by th3akmin3412** [TeamTwilight/twilightforest#1282]
Forge version: 1.12.2

When i finaly defeat the phantom knight and can pass trough the vanishing doors and etc etc,, i expected to complete the beautifull and very hard dark tower in survival and fight the Ur-Gast.

But  at middle level of the dark tower (at blaze spawners), the "fireproof planks" are burning instead of being innflamable, is this a bug or theres something that i need to do to fix this?????

**Comment by GizmoTheMoonPig** [comment]
towerwood isnt fireproof, it just burns a lot slower than normal wood. We do still have to check if it was that way in 1.7, as that may not be intended. However, 1.12 wont be seeing the fix if its made as we dont support that version anymore.

**Comment by th3akmin3412** [comment]
thanks for the answer
