### ISSUE TITLE
Error happened when reenter the server

### ISSUE THREAD

**Issue by PotatoGan** [TeamTwilight/twilightforest#1286]
Forge version: 36.2.0(server)
Twilight Forest version: 1.16.5-4.0.546-universal
Link to crash log: no

Steps to reproduce:
1. In a server with Twilight Forest
2. Enter the Twilight Forest
3. Quit server
4. Reenter the server

What I expected to happen: Standing right at where I was in Twilight Forest

What happened instead: Stuck in the rock of main world

**Comment by GizmoTheMoonPig** [comment]
we really need more info to help you with this, no idea what would be causing this

**Comment by Killer-Demon** [comment]
Please re-open the issue if the issue persists and you have more information to provide about it. Until then, I'm closing this for lack of anything tangible to work with.
