### ISSUE TITLE
Hydra lair generation bug

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1288]
Forge version: 37.0.45
Twilight Forest version: 1.17.1-4.0.676
Link to crash log: N/A

Steps to reproduce:
1. Visit a hydra lair

What I expected to happen: The cave to generate like normal, partially covering the hydra overhead

What happened instead: The cave is generating to be about 10 blocks tall, the rest is presumably buried 
![2021-09-18_14 52 22](https://user-images.githubusercontent.com/23658767/133907163-71b933a5-5660-41f0-98d5-8d380c743c11.png)

**Comment by Drullkus** [comment]
Fixed via 3cfc50ab531349fe7e76ce1171786fdecb6e0338
