### ISSUE TITLE
Minoshroom may never respawn after changing from Peaceful Mode

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#129]
Forge version: 13.20.0.2315
Twilight Forest version: 2.4.0.107

This may be an age-old bug, but may be worth mentioning
Steps to reproduce:
1. Enter the Labyrinth/ Minoshroom Boss's spawn radius in Peaceful Mode
2. Change game mode either away from or inside the Labyrinth
3. Find Minoshroom Boss's Lair

What I expected to happen:
Like most bosses, the Minoshroom would not spawn until the player was Easy Mode or above. If the player was nearby in Peaceful Mode, a Boss Spawner would remain idle and not activate

What happened instead:
The Minoshroom of that Labyrinth will never respawn again

**Comment by williewillus** [comment]
when you got there was the spawner still there or was it gone?

**Comment by Tamaized** [comment]
I believe this one doesn't have a spawner. Like the Yeti and such.

Yea, it spawns during `ComponentTFMazeRoomBoss#addComponentParts`
