### ISSUE TITLE
Candelabras cannot be placed on the top of a block if there is a valid wall of a block next to it

### ISSUE THREAD

**Issue by jodlodi** [TeamTwilight/twilightforest#1291]
Forge version: 37.0.69
Twilight Forest version: 867
Link to crash log: no crash

Steps to reproduce:
1. Attempt to place a candelabra on the floor while there is a block such as cobblestone in the next space

What I expected to happen: The candelabra will be placed on top of the block

What happened instead: If im facing the wall, the candelabra gets placed onto the wall, if im facing away from it, nothing happens at all

**Comment by GizmoTheMoonPig** [comment]
drull used the wrong direction on his floor checker, will push a fix once I wrap up my other stuff. Thanks for reporting!
