### ISSUE TITLE
Rare hollow oak tree cutoff issue

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [TeamTwilight/twilightforest#1292]
Seed: -2246345335780047347
Coords: 12982, 58, 1648
Seems to only happen to the long leaf blobs. All the other parts of the tree are fine now.
![2021-09-23_13 34 16](https://user-images.githubusercontent.com/67468252/134573315-5c740548-10ad-4d02-8ef7-42fbd3320b90.png)

**Comment by Drullkus** [comment]
It seems feature gen is not deterministic with `Random`. I regenerated the tree at this spot around 10 times, got all different trees, then scanned like 20 more. It might be a weird fluke of worldgen that I'd say is safe to ignore
