### ISSUE TITLE
Dwarf Rabbits don't use rabbit sounds and aren't breedable with Dandelions/Carrots

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#1293]
Forge version: 
Twilight Forest version: 1.17.1-4.0.721
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Spawn Dwarf Rabbit
2. hit Dwarf Rabbit/attempt to breed it

What I expected to happen:
Dwarf Rabbit makes rabbit sounds + is breedable. It should follow the same behavior as Rabbits, being hunted by wolves, cats, and foxes
What happened instead:
Dwarf rabbit uses blank sounds and cannot be bred.

**Comment by GizmoTheMoonPig** [comment]
gonna make a note that the hunting bit is addressed in a separate issue, as other mobs should get this treatment as well: #1303
