### ISSUE TITLE
charm of keeping bug

### ISSUE THREAD

**Issue by TwigDemonTF** [TeamTwilight/twilightforest#1295]
Forge version: 1.17.1
Twilight Forest version: 4.0.676.

Steps to reproduce:
1. die with a charm of keeping (any level) in your inventory

What I expected to happen: the charm of keeping gets consumed after being respawned

What happened instead: your player keeps the charm of keeping and can be re-used as long as its in the players inventory

**Comment by GizmoTheMoonPig** [comment]
fixed in 1f06ac17c24435a8cb7aad3d081f96f66c2a5146

**Comment by Drullkus** [comment]
As noted above, it’s already been fixed and you’ll need to update the mod

**Comment by TwigDemonTF** [comment]
Alright I'll update to a newer version, I apologize for addressing an issue
that has been solved in future versions

Op zo 26 sep. 2021 23:33 schreef Drullkus ***@***.***>:
