### ISSUE TITLE
Crashing with Et Futurum Requiem

### ISSUE THREAD

**Issue by gmnovakrc** [TeamTwilight/twilightforest#1296]
Forge version: forge-1.7.10-10.13.4.1614

Twilight Forest version: Twilight Forest 1.7.10-2.3.8

Link to crash log: [crash-2021-09-26_18.15.11-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/7232382/crash-2021-09-26_18.15.11-server.txt)

Making a custom modpack, a lot of mods, but only crashes with this specific mod.
Et Futurum Requiem 1.7.10-2.2.1

Game crashes after arriving in dimension right after some chunks start to load in.

Not sure which mod is causing it though, seems to be a specific block/item though.
Will be posting this in Et Futurum Requiem issues as well just in case.

Thanks

**Comment by Tamaized** [comment]
1.7.10 isn't supported
