### ISSUE TITLE
`twilightforest:hardened_dark_leaves` have weird behavioural differences compared to regular darkwood leaves

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1298]
Fabric version: 0.11.6
Twilight Forest version: 4.0.51 (downloaded from the Discord server)
Fabric API version: 0.40.1
Cloth Config version: 5.0.38
This was encountered in the Fabric 1.17 in-development versions, but, seeing as how I highly doubt you made these two separate blocks after leaves gained a `persistent` blockstate, I'd presume this occurs on Forge as well.

What I expected to happen:
The leaves on the darkwood trees in dark forest biomes would be the regular darkwood leaves block, and, as such:
- would be shown as "Darkwood Leaves" with a picture of the block in HWYLA/WTHIT
- would be able to be pick blocked to yield the darkwood leaves item
- wouldn't conduct redstone
- wouldn't let the player use a flint and steel on them directly

What happened instead:
The leaves on the darkwood trees in dark forest biomes are a separate block, `twilightforest:hardened_dark_leaves`, that has numerous different behaviours from the regular darkwood leaves:
- HWYLA/WTHIT shows them as "Twilight Forest Canopy Leaves" with no picture
- They cannot be pick blocked
- They act as solid blocks for purposes of redstone
- They can be set on fire, although they don't burn
I understand why such a block was added back in 1.7.10 before the days of `persistent` leaves, but, in the modern era, the only beneficial difference between `twilightforest:hardened_dark_leaves` and darkwood leaves is that the former blocks light. Even this behaviour is strange in its inconsistence, seeing as how the two blocks are visually the same.

Describe the solution you would like:
Make regular darkwood leaves block light so all darkwood leaves are consistent, then make the dark forest biomes generate them with `persistent: true` instead of a technical block with weird quirks. Optionally remove `twilightforest:hardened_dark_leaves` from the mod.

**Comment by GizmoTheMoonPig** [comment]
Actually, these were added recently. I had a couple reasons for doing so. I wanted the dark forest canopy to have leaves that weren't decayable or that didn't have an effective tool or obtainable block version. The idea is to have a version of darkwood leaves that could act as a barrier in the dark forest, while still having a version that acted as normal leaves on trees. Adding persistence to them wasn't gonna cut it, as they would still have been mined faster with hoes and would be classified as leaves to other mods, which may cause issues.  Decayable darkwood leaves have been something I've wanted for a long time, and making a special fake leaf block for the dark forest was the solution the team agreed on. Hopefully this is easy to understand and if you have any questions please let me know.

**Comment by saltyseadoggo** [comment]
Yeah, totes. I was wondering if there are any reasons I missed for adding a separate block. This makes sense.
In that case, can we get the inconsistencies I listed fixed, like the solidity, pick blocking and translation for HWYLA/WTHIT?

**Comment by GizmoTheMoonPig** [comment]
Also yeah, it's weird that normal darkwood leaves don't block light, I think that may have been a side effect of turning it into an actual leaf block. I will be fixing that bit

**Comment by GizmoTheMoonPig** [comment]
>In that case, can we get the inconsistencies I listed fixed, like the solidity, pick blocking and translation for HWYLA/WTHIT?

The hardened leaves don't have a blockitem as I don't want them to be obtainable. Block picking should give normal darkwood leaves.. The translations should be there, but I will have to confirm that

**Comment by saltyseadoggo** [comment]
> The translations should be there

The translations are there, but they're nonsensibly called "Twilight Forest Canopy Leaves." I think "Thick Darkwood Leaves" or something would make more sense

> The hardened leaves don't have a blockitem

Maybe one that's only obtainable via commands? Either way is fine, though, it's a minor detail

**Comment by GizmoTheMoonPig** [comment]
Hahaha I copied the wrong line, nice. I'll fix that
