### ISSUE TITLE
Make the inside of robust twilight oaks stripped logs

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1299]
Not a bug, but a suggestion. I think robust twilight oaks could be adjusted to use stripped logs in all of the blocks composing their trunk except for the outermost layer, so that, when the player is climbing the vines in the center, there isn't bark on the inside of the tree.~
![2021-09-26_18 38 51](https://user-images.githubusercontent.com/69029346/134833502-e81c1130-24a1-4f40-9cd5-2f8984c54ab4.png)

**Comment by jodlodi** [comment]
We've decided that we prefer the look of the non-stripped logs more
