### ISSUE TITLE
Mossy blocks can't be crafted with moss blocks

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1301]
Fabric version: 0.11.6
Twilight Forest version: 4.0.51 (downloaded from the Discord server)
Fabric API version: 0.40.1
Cloth Config version: 5.0.38
This was encountered in the Fabric 1.17 in-development versions, but, due to its nature as a recipe issue (thus a resources issue), I would presume that it exists on Forge as well.

What I expected to happen:
I would be able to craft mossy etched nagastone, nagastone pillar, , underbrick, castle brick, towerwood and mazestone with 1.17 moss blocks, matching vanilla mossy block recipes.

What happened instead:
I can't craft Twilight Forest's mossy blocks using the new moss block. The existing vines recipes still exist, as they should.
*(Watto voice) Moss blocks don't work on me, only vines!*

**Comment by GizmoTheMoonPig** [comment]
ah I forgot this was a thing now, will fix that asap
