### ISSUE TITLE
Stairs and trapdoors have recipes resembling Vanilla Tweaks and not vanilla

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1302]
Fabric version: 0.11.6
Twilight Forest version: 4.0.51 (downloaded from the Discord server)
Fabric API version: 0.40.1
Cloth Config version: 5.0.38
This was encountered in the Fabric 1.17 in-development versions, but, due to its nature as a loot table/placement issue, I would presume that it exists on Forge as well.

What I expected to happen, versus what happened:
- Twilight Forest staircase recipes would output four stairs instead of eight.
- Twilight Forest trapdoor recipes would output two trapdoors instead of six.
- Twilight Forest stairs would not have recipes to craft them back into blocks.

Describe the solution you would like:
These recipes would output vanilla numbers of blocks and not significantly more, or would at least be configurable. Modpack makers looking to unify staircase yield with Vanilla Tweaks can make a KubeJS script that changes the output of every staircase recipe fairly easily. The number of trapdoors yielded by these recipes doesn't even match Vanilla Tweaks; I have no idea where six came from.

**Comment by GizmoTheMoonPig** [comment]
we'll be keeping the 8 stairs recipes since those actually make sense and vanilla is dumb, but I'll fix the other 2

**Comment by saltyseadoggo** [comment]
To be honest, if you're not afraid of straying from vanilla, I like the stairs to blocks recipes. Since a lot of TF's building blocks are not renewable, you have to take apart the structures to get them, so being able to convert stairs into blocks is helpful to get more blocks. I'd like to see this feature expanded to include the wood types (taking the time/trans/mine/sortingwood roofs off of druid huts, notably) and slabs.
