### ISSUE TITLE
"Hatchet Honchos" secret advancement

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1304]
A silly secret advancement idea I had based on #1303's request for "mob interactions." If the player somehow gets a minotaur and a piglin brute in the same place, they exchange their respective golden axes and grant the advancement. This would entail getting the minotaur into the overworld, into the Nether, and then in the same place as a Brute, about as much trouble as such vanilla secret advancements as How Did We Get Here?

It also cannot be cheesed by using transformation powder on a zombified Piglin in the nether because the resulting minotaur wouldn't be carrying an axe. Sending another piglin brute to the overworld to zombify, using the powder on it and sending it back through as a minotaur would work, however.

**Comment by GizmoTheMoonPig** [comment]
Thank you for the suggestion! While a fun idea, unfortunately this is not something we will be adding as we are not fans of modifying how vanilla mechanics work. Having a mechanic like this doesn't seem worth it to add just for an advancement regardless tbh
