### ISSUE TITLE
Ideas to update transformation powder

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1305]
I had some ideas for additional mobs the transformation powder can effect. Take or leave them at your leisure:

- Carminite Ghastguard <=> Ghast
- Towerwood Borer <=> Silverfish
- Carminine Golem <=> Iron Golem
- -  Being able to turn the golems into power allies so easily may make parts of the dark tower too easy.
- Maze Slime <=> Slime
- Twilight Wraith <=> Vex
- - Wraith behaves similarly to the vex, and both are ghosts. More fitting than the blaze.
Stable / Unstable Ice Core <=> Blaze
- - Blaze is more similar to these than the wraith.
- Upper Goblin Knight <=> Pillager
- Lower Goblin Knight <=> Vindicator
- Block and Chain Goblin <=> Evoker
- - Since the redcap goblin turns into a villager, I figure the more militaristic goblins can turn into illagers.

**Comment by Drullkus** [comment]
I like the Ghast, Borer, Maze Slime, and Wraith ones, but I don’t agree with the rest

The philosophy is that not every mob has to have an analogue to a Vanilla mob
