### ISSUE TITLE
Charm activation visuals should appear like vanilla totem of undying visuals

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1306]
The current effect used by the charms of life and keeping, where the charm circles around the player's head, is a bit hard to decipher due to all of the particles and it being on the top edge of the player's field of vision in first person. I suggest replacing them with ones that resemble the Totem of Undying's visual, where the charm sprite appears on screen, waggles around for a bit and then spins away.
The one detriment I can see is the obstruction to the player's field of vision, which could be problematic in the sorts of scenarios the charms of life are used in, not so much for the charm of keeping. A smaller version of the Totem of Undying visual centered over the hotbar could be less intrusive.

**Comment by Killer-Demon** [comment]
We're not looking to change our visuals on these for at least the time being.

**Comment by GizmoTheMoonPig** [comment]
Even though we don't want to replace the default effect for the charms, I did add a config option to switch to using the vanilla totem animation in my latest commit. It'll be available from 1.20.4 onwards!
