### ISSUE TITLE
Decentivize walking over the dark forest canopy to the tower

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1307]
You've probably already thought of this, but I couldn't find anything in a quick search of past issues, nor on the Discord.
Right now, there's nothing stopping the player from climbing on top of the dark forest canopy and taking a little stroll over to the dark tower. I always found having to navigate through the underbrush to be more interesting, as this is where you find mobs, have to invest torches into lighting a path, etc. As such, I suggest making naturally generated darkwood leaves [`twilightforest:hardened_dark_leaves`] damage things on top of them, akin to hedges, so the player has to travel under the canopy and not over it. The regular, player grown leaves could or could not have this function at your discretion.

Alternatively, some kind of dangerous mobs could decentivize travel atop the canopy. Perhaps standing on the canopy leaves could cause swarm spiders, mist wolves, whatever to spawn nearby.

**Comment by Tamaized** [comment]
> Right now, there's nothing stopping the player from climbing on top of the dark forest canopy and taking a little stroll over to the dark tower.

The progression system...?
You have to get through the knights stronghold first.

**Comment by saltyseadoggo** [comment]
Oops, sorry for the confusion! That's not what I meant. What I meant is, once the knight phantoms are killed, you can simply walk over the canopy to the tower and avoid investing light sources, hacking through leaves, fighting mist wolves etc. I thought some kind of danger on the canopy would make this a less no-brainer choice

**Comment by Tamaized** [comment]
I don't think this is a problem honestly, people like that will just fly over it anyway. Let the player do what they want.
