### ISSUE TITLE
Make Magic Maps not work in Non-Twilight worlds

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#1308]
Ideally, the map should check `TFGenerationSettings.usesTwilightChunkGenerator(ServerLevel)`. If the condition fails then display title text over the hotbar "The map seems unresponsive..."

**Comment by Tamaized** [comment]
I've got a better idea:
Maps can only be 'activated' in TF, maintain the display render from the TF so people can use it as decoration in other dims on item frames

**Comment by Drullkus** [comment]
Ah, I never specified “working” to “activating” but yes that’d be ideal
