### ISSUE TITLE
Map Crash

### ISSUE THREAD

**Issue by Flyer173** [TeamTwilight/twilightforest#131]
Forge version: Doesn't matter (i think)
Twilight Forest version: 13.20.1.2429
Link to crash log: 
[crash-2017-08-06_14.29.37-client.txt](https://github.com/TeamTwilight/twilightforest/files/1203320/crash-2017-08-06_14.29.37-client.txt) (sorry u might not want this but idk how to make things a link. let me know if i did a good)
This was also by ZombieEnderman5, not me. he is a kewl person on discord.

> Tried to open my inventory with a Maze Map.

They also said these wonderful things =)
> Something to do with ItemTFMagicMap and ItemMap and GuiScreen
> It is the same version. Same world in fact.
> No idea if it helps but it crashed right after I collected a piece of Raw Meef
> Huh... like I thought, the unknown map bug only occurs in chests @Hammer Bro (Me in nickname form)

**Comment by Tamaized** [comment]
Happens with Vanilla maps as well, I can't exactly reproduce it consistently. Seems kinda random.

**Comment by williewillus** [comment]
It's because we're doing a dirty hack piggybacking off of vanilla's mapdata ID
Needs this to be fixed https://github.com/MinecraftForge/MinecraftForge/pull/4068

**Comment by williewillus** [comment]
rolling into #29
