### ISSUE TITLE
Structure generation Bug

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1319]
### Forge Version

37.0.73

### Twilight Forest Version

4.0.742

### Steps to Reproduce

idk bro just search for the structures man

### What You Expected

generation of structure

### What Happened Instead

no generation

[
![image](https://user-images.githubusercontent.com/82680956/135701126-78666996-adec-4d33-959e-8808fb0808ff.png)
](url)

[
![image](https://user-images.githubusercontent.com/82680956/135701137-4d013fa3-6897-4719-8492-79ae7b811dd1.png)
](url)

### Additional Details

theese 2 structures didint generate, althogh nearby structures did

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by VilligerKing** [comment]
*forgot to mention is on the official tf server

**Comment by GizmoTheMoonPig** [comment]
this is the same issue as #1313, structures arent supposed to try to spawn in the dense mushroom forest either.
