### ISSUE TITLE
Hydra den stalagmites generating on top of hydra den

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1320]
### Forge Version

37.0.73

### Twilight Forest Version

4.0.742

### Steps to Reproduce

idk bro just look for hydra caves

### What You Expected

ore stalagmites to generate properley

### What Happened Instead

the unfunny

[
![image](https://user-images.githubusercontent.com/82680956/135709213-23cd51db-2f8e-458d-8e82-f6ff332d4ba7.png)
](url)

### Additional Details

this is on the official tf server, also I remember a very similar glitch happening on a previous ver of tf on hollow hills, but was fixed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment]
Fixed via 2fd526a7
