### ISSUE TITLE
Moonstone and Sunstone Geodes

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest#1321]
### The Suggestion

I had an idea for a couple of geode ideas, similar to the amethyst geodes in 1.17, exclusive to the twilight forest.

Sunstone Geodes:
contains Budding Sunstone, Sunstone Blocks, and Sunstone Clusters.

fully grown Sunstone Clusters drop Sunstone Shards, which can be crafted into Sunstone Blocks, Twilight Torches(a new kind of torch that provides a light source akin to Glowstone, and has a pink glow to it), Sunstone Armor(which has fire resistance), and Mega Twilight Maps.

the Twilight Torches can be crafted by combining either a soul torch or normal torch with sunstone shards surrounding it completely, which gives 8 Twilight Torches.

Sunstone blocks, items, and armor/weapons would be in a light-golden orange color

Moonstone Geodes:
contains Budding Moonstone, Moonstone Blocks, and Moonstone Clusters.
fully grown Moonstone Clusters drop Moonstone Shards, which can be crafted into Moonstone Blocks, Moon Dials(which can change the phase of the moon), Moonstone Armor(which gives regeneration), and Mega Twilight Maps.

Moonstone blocks, items, and armor/weapons would be in light blue color.

Moon Dials would be crafted using a Bottle O' Enchanting in the middle. Glass vertically and horizontally, and Moonstone Shards diagonally.

Mega Twilight Maps are Maps that Cover 9x the map distance that a normal map would be able to cover.

Mega Ore/Maze map: covers all the ores in a 3 map x 3 map distance. and it covers all the mazes in that distance, and all of the floors added to it, both Minoshroom and Knight Phantom.

Mega Maze Map: Covers all the floors to either a Knight Phantom or Minoshroom maze, with the ability to auto switch between floors..

Mega Magic Map: Covers all the locations of a 3 map x 3 map distance, with the ability to zoom in and out.

each mega map needs to have 4 sunstone shards in each corner, 4 moon stone shards vertically and horizontally to the map itself, and a respective condensed map in the center, which can be crafted with 9 empty twilight maps of the same kind. i.e. 9 empty ore/maze maps, 9 empty maze maps, or 9 empty magic maps.

### Why Should It Be in the Mod?

it would be cool if the developers added new types of ores or geodes into the game that are exclusive to the twilight forest, and would provide a really cool experience for players moving forward.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
These make no sense to me, there's no concept of celestial beings in the dimension.

**Comment by CobaltGlacier** [comment]
who said these represent celestial beings. my intention is that these represent the sun and moon, mostly because that time known as "twilight" is in between day and night. I'm not referring to celestial beings, unless you refer the sun and moon as "celestial beings", in that case I'm sorry for suggesting this for that reason. but I still think that these would be a good addition because it adds a twilight exclusive variant of the amethyst clusters

**Comment by Tamaized** [comment]
The sun and moon are celestial beings... They do not exist in this dimension at all.

**Comment by Andromander** [comment]
Think the more accurate term here is "celestial object", as "being" implies there is some sort of living thing.

**Comment by Tamaized** [comment]
Google says 'body' I guess
Meh

**Comment by CobaltGlacier** [comment]
Ok, let me revise the reason why i think it would be cool. I believe it would be cool If there were ores or geodes that are exclusive to the twilight forest, similar to how netherite and nether quartz are signature to the nether.

**Comment by CobaltGlacier** [comment]
i just revised it in case anyone wants to look at the new reason

**Comment by Killer-Demon** [comment]
Unfortunately, this isn't something we're looking to add. The sun and moonstone suggestions aren't quite fit for the theme of the mod as it stands.
