### ISSUE TITLE
Naga advancement can be cleared without killing naga thanks to naga scales in hollow hills

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1322]
### Forge Version

N/A, loot table/advancement .json issue

### Twilight Forest Version

4.0.61

### Steps to Reproduce

1. Complete "Twilight Hunter" advancement
2. Search medium and/or large hollow hills until a naga scale is found, and place it in your inventory
3. Watch as the naga killing advancement is granted

### What You Expected

It would be impossible to gain this advancement and enter the lich tower without killing a Naga. Either scales wouldn't be able to be found in hollow hills, or the advancement would mandate killing a Naga in some other way, perhaps with nbt data on naga-obtained scales?

### What Happened Instead

It is possible to break progression through the steps described above and not need to kill a Naga.

### Additional Details

The bug is still present as of commit 1ebe112c6e6f778881c046d8135d6637e2a60afa , which I can see by checking the medium and large hollow hill chest loot tables and naga advancement.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
forgot to mention, I replaced the naga scales in the medium and large hollow hills with magic maps instead here: 197fae3435c4fac4097aa84b1c7a1ba619a0bfe3 . I didn't realize I included the loot table changes here so they weren't mentioned, my bad
