### ISSUE TITLE
[Suggestion] Smith alpha yeti fur onto armour to actually "line" it

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1324]
### The Suggestion

The advancement for killing an alpha yeti tells you to line your armour with its fur to take on the glacier's cold, but, in actuality, this isn't possible. The closest thing you can get is creating alpha yeti armour, which isn't required to take on the glacier at all.

My suggestion is as follows: using the smithing table, applying alpha yeti fur to any armour piece will apply two enchantments:
**Warm**: This enchantment is required to face the glacier's cold, as the advancement says. If the player doesn't wear a full set of armour with this enchantment, they recieve the chilled effect upon entering the biome.
**Chill Aura**: The existing enchantment implemented properly, to give any piece of armour the functionality of alpha yeti armour.

In addition, alpha yeti armour would be retooled to be created by smithing arctic armour with alpha yeti fur. Each alpha yeti would drop only four furs so the player has just enough to line their armour, and the fur itself would have a tooltip explaining what to do with it to progress if you feel people would have troubles like the meef stroganoff.

### Why Should It Be in the Mod?

Making these changes would serve to further immerse the player in the Twilight Forest by actually making them do what the advancement says and line their armour with the fur, much like eating the meef stroganoff to become acclimated to the fire swamp. Also, being able to get Chill Aura in this way I feel is more interesting than an enchanted book, drawing the player to engage with the yeti lairs if they want the effect.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
We currently have a little something drafted up for the Alpha Yeti Fur and the armor crafted from it, so I'm closing this suggestion in favor of that for when we implement it.
