### ISSUE TITLE
Make helmet crabs drop cooked cod upon death while on fire

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1327]
### The Suggestion

Make helmet crabs drop cooked cod upon death while on fire, pretty simple

### Why Should It Be in the Mod?

happens to cows n pigs, why not crabs?

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
I actually need to make all of the mobs that drop cookable foods do this, thank you for the reminder
