### ISSUE TITLE
Issues when using shaders

### ISSUE THREAD

**Issue by EjJon** [TeamTwilight/twilightforest#133]
Forge version: 1.11.2-forge1.11.2-13.20.1.2429
Twilight Forest version: 2.4.0.125

When using SEUS Shaders the sky does not display properly. In addition to this the Castle Rune Bricks display as coloured blocks without the pattern. The Day/Night cycle also has no effect on the lighting. Not sure if this happens with other shader packs. 

The issues can be viewed below:

![2017-08-07_12 27 31](https://user-images.githubusercontent.com/30797926/29024829-d10f63c8-7b6b-11e7-841f-4bc6614bf858.png)

![2017-08-07_12 27 36](https://user-images.githubusercontent.com/30797926/29024831-d38ade5c-7b6b-11e7-879a-9f8609e8d9cb.png)

**Comment by Drullkus** [comment]
Fulbright cannot work properly with Optifine
