### ISSUE TITLE
towerwood borer being a wussy (instantley going inside another towerwood block the second its broken)

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1331]
### Forge Version

37.0.73

### Twilight Forest Version

4.0.742

### Steps to Reproduce

step 1: break infested towerwood
step 2: get a 50/50 percent chance of the borer being a wussy

### What You Expected

borer to attack me

### What Happened Instead

sometimes it just dont feel like wakin up

### Additional Details

i know this is more of a mojang thing instead of a tf thing, but I think it would be nice to add a cool down to the borer before it can go inside another block, considering sometimes players don't interact with them at all when exploring an urghast tower

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
yeah, this is indeed a mojang thing, as we literally use silverfish logic, but I can look into putting a longer timer in
