### ISSUE TITLE
Tree o transformation addition

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1334]
### The Suggestion

By name, i thing the tree o trans should maybe transform animals around it, along with the biome. Although I don't think it should make trans powder useless, I do feel like it would be a nice addition to be able to use the tree o trans for something other than decor, perhaps it could transform a single mod every couple of minutes, or just have a random chance, I also feel like it would be cool if an oak dree/dark oak tree were in the area of effect of the tree o transformation, it would turn it into twilight oak or rainbow oak/dark wood. This would make it so that planting a tree in a forest would turn the biome into an enchanted forest, trees n all

### Why Should It Be in the Mod?

bc the name "tree of transformation" rlly does feel like it would transform stuff around it, including mobs n blocks

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
fun fact: the transformation tree code does have a todo attached to it for this, so I think it may happen eventually :)

**Comment by jodlodi** [comment]
After further thought, we have decided against this, due to the fact that it would remove the need for transformation powder, which would make it less valuable.
