### ISSUE TITLE
Ghastling ai ignores player in certain conditions

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1335]
### Forge Version

37.0.73

### Twilight Forest Version

4.0.743

### Steps to Reproduce

step 1: get ghastling
step 2: get ignored

### What You Expected

ghasting to try to kill me

### What Happened Instead

got ignored

### Additional Details

ghastlings seem to ignore players that arnt 2 blocks away from there face or are below them, they also seem to just freeze in the air sometimes

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Tamaized** [comment]
That's intended. When you're far enough away they ignore you unless looked at, similar to endermen

**Comment by VilligerKing** [comment]
op, my bad then
