### ISSUE TITLE
The Twilight Forest Crash in Forge 36.2.0

### ISSUE THREAD

**Issue by RoWithJason** [TeamTwilight/twilightforest#1336]
### Forge Version

36.2.0

### Twilight Forest Version

4.0.546

### Client Log

https://gist.github.com/RoWithJason/e830f611fc8b56f8c98f96fcc942e0a6.js

### Crash Report (if applicable)

https://gist.github.com/RoWithJason/a1552f24dafffaecab330f6a1d0031c6

### Steps to Reproduce

1. Download Twilight Mod on Forge
2. Open Forge 1.16.5

### What You Expected

Successfully open and play mod server with my friends.

### What Happened Instead

It shows "The Twilight Forest (twilightforest) encountered an error during the sided_setup event phase"

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
> java.lang.NoClassDefFoundError: net/minecraft/network/chat/Component

that, uh, shouldn't be happening. I know I'm over 6 months late to answering this, but if you're still having this issue, you may want to try reinstalling minecraft and/or forge. If you figured it out, feel free to close this
