### ISSUE TITLE
Some decoration blocks like cave roots and torch berries not generating

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1337]
### Forge Version

37.0.73

### Twilight Forest Version

4.0.742

### Steps to Reproduce

i dont think i need to explain this one

### What You Expected

generation

### What Happened Instead

world gen said "haha fuck you"

### Additional Details

was on the server when was trying to get the "collect all things plants" achievement when I noticed cave roots, torch berry plants, large lily pads and trollibers don't spawn, there may be more stuff not generating but I'm not sure.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
fixed in aa16d95e5fa6e8b2b668194124c29b3f787df59d
