### ISSUE TITLE
Mangrove Tree is split apart when grown

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#1338]
### Forge Version

37.0.82

### Twilight Forest Version

4.0.766

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

1. Grow a Mangrove using Bone Meal
2. 
![image](https://user-images.githubusercontent.com/36087299/136455410-4c18c5c2-9506-48cf-b3ac-6a7b27fc0184.png)

### What You Expected

The tree isn't splitting apart

### What Happened Instead

the tree split apart

### Additional Details

N/A

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment]
Fixed via a3f7e156b621dab66605167aabd4d04413eb3065
