### ISSUE TITLE
make carminite golems drop carminite

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1339]
### The Suggestion

i mean its in the name, why not? in the wiki it is stated its animated with carminite

### Why Should It Be in the Mod?

bc it would b cool

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This wouldn't work due to lore implications. There are also Carminite Broodlings, Ghastlings, and Ghastguards who also don't drop it for the same reason,
