### ISSUE TITLE
Improper rotations still existing

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#134]
![2017-08-06_20 04 29](https://user-images.githubusercontent.com/5010174/29048814-6996e2e0-7b87-11e7-9478-f47c02187550.png)

Mostly limited to the Caves. Affects all the shrooms.

**Comment by Andromander** [comment]
Seems to also occur in the Labyrinth
![2017-08-08_16 17 05](https://user-images.githubusercontent.com/29526717/29058720-3051d0b6-7c55-11e7-802c-17bd875ad378.png)
