### ISSUE TITLE
Small hollow hills becomes microscopic hollow hills

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1341]
### Forge Version

37.0.82

### Twilight Forest Version

4.0.766

### Steps to Reproduce

join the coolest server (official tf server)

head twards -1305 -762

become antman

### What You Expected

hollow hill

### What Happened Instead

hill

### Additional Details

screenes

[
![image](https://user-images.githubusercontent.com/82680956/136683757-8359f576-1cb2-44b3-a624-a8c809ebc317.png)
](url)

[
![image](https://user-images.githubusercontent.com/82680956/136683766-8c6caf8f-f1c5-4e52-a115-e437f9b854aa.png)
](url)

[
![image](https://user-images.githubusercontent.com/82680956/136683782-165e8bd0-b536-4a29-86c3-2d6f03fb6204.png)
](url)

[
![image](https://user-images.githubusercontent.com/82680956/136683789-c3890a2a-d9aa-4574-9d77-e6157addd655.png)
](url)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Tamaized** [comment]
Not a problem in the current 1.18 dev builds
