### ISSUE TITLE
Naga not spawning in cortyards

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1342]
### Forge Version

37.0.82

### Twilight Forest Version

4.0.766

### Steps to Reproduce

look for a cortyard

### What You Expected

naga

### What Happened Instead

no naga

### Additional Details

I remember a similar bug to this one happening a long time ago but it was fixed, also its on the official server

and yes, i traveled very far, every cortyard i find is intact and w/o a naga

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment]
Fixed via d98f4aca8132bda7aeaae3833b632dda53463ebe
