### ISSUE TITLE
Keepsake Caskets do not lock for other players

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1343]
### Forge Version

1.17.1-37.0.82

### Twilight Forest Version

1.17.1-4.0.766

### Steps to Reproduce

1. Die with a keepsake casket in your inventory (does not matter if there are items to go in the casket also in your inventory or not)

2. Die, and have another player open and break the casket

### What You Expected

The casket to be locked to all players but the one that died, and for other players to also be unable to break the casket

### What Happened Instead

Other players can both open and break the casket.

### Additional Details

Discovered on the official testing server
![2021-10-12_19 26 56](https://user-images.githubusercontent.com/23658767/137047798-936cdb8c-baae-4680-a968-3ba33b4a68f0.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
Intentional: the locking thing is a config option, which I forgot to toggle back on on the server.
