### ISSUE TITLE
[Suggestion] Allow configuration of item stats and mob's attack speed

### ISSUE THREAD

**Issue by megagnarxd** [TeamTwilight/twilightforest#1345]
### The Suggestion

As titled, increase the configuration of item stats such as attack speed and damage for fiery sword, toughness and armor stats for armors. Allow configuration of bosses too (no idea how this will work with naga and minoshroom), but allowing hydra and ur-ghast to be allowed to fire more fire is always nice.

### Why Should It Be in the Mod?

The reason why these should be included is due to twilight forest feeling overall weird in terms of pacing. Items such as naga scales are similar to iron, and fiery items are better than netherite. This makes vanilla ores pretty much uselesss. To be able to configure those would allow players to defer the twilight forest to a mid-game progression system rather than an early one. Mob hp and damage is configurable through other means, so i guess it's fine to not include it.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
You can change the attributes on items by changing the NBT on the Recipe output.

[Incontrol](https://www.curseforge.com/minecraft/mc-mods/in-control) lets you alter properties of mobs upon their spawning
