### ISSUE TITLE
Giants cant reach you in what could be considered within there reach

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1347]
### Forge Version

37.0.82

### Twilight Forest Version

4.0.776

### Steps to Reproduce

build up to there faces

no hit

### What You Expected

getting whacked

### What Happened Instead

no whack

### Additional Details

video showcasing bug on server

[https://youtu.be/7EBLGya87pI](url)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment]
Unless this is an AI problem, this might be doable by increasing its reach distance in the Mob attributes
