### ISSUE TITLE
[Suggestion] Replace fires in druid huts with campfires

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1348]
### The Suggestion

Replace the two fire blocks in the chimneys in druid huts with campfires.

### Why Should It Be in the Mod?

The campfire fits really well here in my opinion due to having visible firewood, and they would also emit smoke and allow the chimney to actually function, adding life and atmosphere to the huts.

Current:
![2021-10-14_21 12 25](https://user-images.githubusercontent.com/69029346/137431312-626b9f44-4040-476c-95fd-00d1bc3fb2ae.png)
With this change:
![2021-10-14_21 12 33](https://user-images.githubusercontent.com/69029346/137431319-1f1f159e-cc91-4ab8-adc4-041c4d5dfc42.png)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
This might've been more ideal for the older Druid Huts with one-block fireplaces, but the size of fire on the campfires don't really compare at all
