### ISSUE TITLE
Goblin Knights do not spawn with lower Goblin

### ISSUE THREAD

**Issue by LapisWhovian** [TeamTwilight/twilightforest#135]
Forge version: 
Twilight Forest version: 128
(did not crash)

Steps to reproduce:
1. Complete the mod up to the phantom tombs.
2. Wander through the maze
3. Look for a double-decker goblin

What I expected to happen:
I wanted to find a cool mob which was actually 2 different mobs.
What happened instead:
I found the upper knight, but not the lower.

**Comment by LapisWhovian** [comment]
Oops! Called it the wrong thing XD

**Comment by Tamaized** [comment]
Looks to be related to https://bugs.mojang.com/browse/MC-103516

the spawn egg and /summon command all work just fine. Spawning naturally is the issue as it fails the `isNotColliding` check in `WorldEntitySpawner`

**Comment by williewillus** [comment]
there's a forge patch in for this, not much we can do here on our own, the bug affects all naturally spawning stacked entities

**Comment by Tamaized** [comment]
Linking this here and also gonna take the milestone off, don't think this issue needs to be in it tbh
https://github.com/MinecraftForge/MinecraftForge/pull/4429

**Comment by Drullkus** [comment]
Since there is no problem on our end, this issue will effectively be patched when the version of Forge with the Patch will be released. Closing issue
