### ISSUE TITLE
Fiery Metal Block Usage suggestion

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1350]
### The Suggestion

Scince there so hard to get, and scince it is also a cool looking blocc, i fell like it should have a use besides armour, therefore, i propose it work like knightmetal, as a stronger alternative to magma, (exept way stronger, like perhaps killing an unarmed player in about 4 dmg ticks) i also think it whould be cool if it hurt you if you stoon dent to it like kightmetal and cacti (but also not destroy blocks). I also think it whould be cool if fire res lowered the dmg, but not nullify it entierly.

### Why Should It Be in the Mod?

bc fiery metal block cool block and id love to see it get some more love, also already does fire dmg but not alot, wich is weird considering it can make ppl spontaniusly combust at a touch (fiery aura)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
Some of the things mentioned in this suggestion exist in the mod and we're happy with how that currently exists.
