### ISSUE TITLE
Mosquito Swarms should be hurt by 1.19 frogs

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#1355]
Not entirely consuming since it's a swarm, not a single specimen per swarm entity

**Comment by Smokedeuch** [comment]
"Mosquito Swarm Half Slab"

**Comment by GizmoTheMoonPig** [comment]
we found theres no easy way to pull this off, due to the way frogs work. Closing this as its not something we're gonna bother with
