### ISSUE TITLE
Mining core does not replace granite, andesite or diorite

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1356]
### Forge Version

1.17.1-37.0.82

### Twilight Forest Version

1.17.1-4.0.766

### Steps to Reproduce

1. Activate a mining core
2. Remove the ore it pulls up and observe what blocks the core has replaced with ore

### What You Expected

All stone varients to be replaced with ore

### What Happened Instead

The mining core does not seem to replace granite, diorite or andesite with ore. I don't know if this is intended or not, but it does seem to be inconsistent with the cores purpose and rather odd behavior.

### Additional Details

Discovered on the tf testing server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by EvergreenSystems** [comment]
![2021-10-16_19 03 56](https://user-images.githubusercontent.com/23658767/137605079-b258d43c-9a1c-45b9-b88c-c7b8a5def992.png)

**Comment by EvergreenSystems** [comment]
![2021-10-16_19 24 30](https://user-images.githubusercontent.com/23658767/137605399-943cf720-9e12-4b20-afbc-3e76c5e679be.png)

**Comment by GizmoTheMoonPig** [comment]
good catch, will fix
