### ISSUE TITLE
Gold Minotaur Axes can drop with 0 dura

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1357]
### Forge Version

37.0.38

### Twilight Forest Version

4.0.766

### Steps to Reproduce

kill som fokin minotaurs

get funny axe

### What You Expected

no dura

### What Happened Instead

dura

### Additional Details

the funny

[
![image](https://user-images.githubusercontent.com/82680956/137610037-a2749e86-9935-42ce-8d90-c5c95fcf0858.png)
](url)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
this is a vanilla thing, cant do anything about it
