### ISSUE TITLE
Mazestone Pillars

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1358]
### The Suggestion

Mazestone Pillars?

### Why Should It Be in the Mod?

Mazestone Pillars.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
Closing for now, will reopen if you have any specifics you'd like to suggest about the block. Otherwise we'll only add new blocks as we naturally see fit when designing a new structure
