### ISSUE TITLE
[Suggestion] Make transformation powder use 'recipe' jsons

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1360]
### The Suggestion

Make transformation powder read from a number of .json files resembling recipe files to determine its interactions. While this is certainly an unusual use case for a recipe file, I don't see why it  couldn't be done.

Example format:
{
  "type": "twilightforest:transformation",
  "usedon": "twilightforest:wild_boar",
  "result": "minecraft:pig"
}

### Why Should It Be in the Mod?

For configurability, especially for modpack developers who may wish to let other mods' mobs transform into mobs of their choosing, disable existing transformations, make transformations one-way, etc.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
crumble horn and transformation powder now use jsons to determine transformations. 
Crumble horn example: 
{
  "type": "twilightforest:crumble_horn",
  "from": "twilightforest:castle_brick",
  "to": "twilightforest:cracked_castle_brick"
}

Transformation powder example: 
{
  "type": "twilightforest:transformation_powder",
  "from": "minecraft:bat",
  "to": "twilightforest:raven"
}
I even wrote datagenerators for both, so other mods are more than welcome to use that to make recipes. Enjoy!
