### ISSUE TITLE
[Suggestion] Final Boss Idea

### ISSUE THREAD

**Issue by AceOfSpadesYT** [TeamTwilight/twilightforest#1361]
### The Suggestion

Alright, this is a really, really big part of the mod and deserves much discussion. I just thought I would share my idea on what it should be.
This mod features tons of Greek and other mythological creatures. For this reason, I believe the ultimate enemy resting on top of the final tower should be the **TYPHON**. The Typhon is considered to be the most fearsome monster in Greek mythology. Even the Gods were scared of it. Therefore, it should have the honor of being the monster above all monsters in Twilight Forest as it is in mythology. Also, when it shows up, the area it spawns is surrounded by the purple forcefield - preventing either it or the player from escaping.

I love this mod very much. I have made it all the way to the end and even wrote a short chapter book about the mod. I would love to see my suggestion taken into consideration. Thanks! Keep up the good work.

### Why Should It Be in the Mod?

I feel it should be in the mod because it is said to be the most dangerous monster in all of Greek mythology and the mod features a lot of that already. We would finally get a final boss, and be able to feel accomplished at the end.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
The plateau boss is already fully planned out in our dev docs, but we appreciate the suggestion!
