### ISSUE TITLE
Life charms Spawned in loot chests dont stack w Life charms in inventory

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1363]
### Forge Version

37.0.82

### Twilight Forest Version

4.0.766

### Steps to Reproduce

Charm o life in inv

log out/leave the tf/

join bacc

Side note: i dont know what exactly causes the bug, but the ones listed here is what i assume what causes it

### What You Expected

stacc

### What Happened Instead

no stacc and annoying

### Additional Details

video showcasing the bug in the server

[https://youtu.be/dmjGcFSBBo4](url)

enjoy the music playing in the background :p

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment]
Can you enable advanced tooltips by holding `F3` while pressing `H`, then tell us if it has any NBT

**Comment by VilligerKing** [comment]
i have advance tooltips enabled in the video, in witch i hover over both my life charms and the one in the chest

**Comment by Drullkus** [comment]
Your URL is broken smh

**Comment by GizmoTheMoonPig** [comment]
cant reproduce this in 1.18, grabbed a bunch of life charms from trees and they stacked just fine with other ones. If this still happens for you in 1.18 please reopen this
