### ISSUE TITLE
ores and silktouch giant pickaxe have some weird stuff goin on

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1364]
### Forge Version

37.0.82

### Twilight Forest Version

4.0.766

### Steps to Reproduce

enchant the big boy with Silk touch

start mining them ores

(results showcased in video)

### What You Expected

Giant pickaxe to work as normal pickaxe w silktouch, and drop ores

### What Happened Instead

Each ore has a diff result

diamond ore turns to stone

gold ore dissapears

iron ore works fine for some reason

and restone ore dissapears, but can only be mine one at a time (im pretty sure the big of mining one at a time was foxed in a later ver, update the server gizmo!)

### Additional Details

video lol
[text](https://youtu.be/4E89aFSuNIg)

enjoy me getting trolled

(was on server)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
giant pickaxes are a stone tier tool, so you cant mine ores like gold, redstone, or diamond with it. I'll investigate the diamonds turning to stone though, that sounds really weird

**Comment by GizmoTheMoonPig** [comment]
actually if a giant pick cant mine a block it shouldnt be mining the whole vein. I'll need to investigate that too as it creates a huge loss if youre clueless about the harvest level

**Comment by VilligerKing** [comment]
> giant pickaxes are a stone tier tool, so you cant mine ores like gold, redstone, or diamond with it. I'll investigate the diamonds turning to stone though, that sounds really weird

there needs to be some way of telling the player its a stone level, scince you use it to mine the giant obsidian, most ppl (including me) assume its diamond

**Comment by GizmoTheMoonPig** [comment]
...its a stone pickaxe, thats telling enough. If it was diamond tier we would use a diamond pickaxe
