### ISSUE TITLE
Give the player a way to know the Giant pickaxe is stone level, not diamond

### ISSUE THREAD

**Issue by VilligerKing** [TeamTwilight/twilightforest#1365]
### The Suggestion

I have no idea how, it needs to be clarified that the pockaxe is stone, not diamond. Perhaps it could be fixed by turning the obsidian in the troll caves into stone, making it make sense being able to mine it with a stone pickaxe, or a description saying its a stone level, just something

### Why Should It Be in the Mod?

many players (including me) assume the pickaxe is diamond level due to the fact that you mine the giant obsidian with it, and this can lead to many problems down the line.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
there is really no need for this. The pickaxe is a stone pickaxe, indicating that its stone tier. It has a tooltip that says its able to break giant blocks. The pickaxe is special in this way, and when it comes to giant blocks, rules dont need to be followed in the same way they do with normal blocks. How are you able to break leaves, or wood with it? Its just supposed to be a tool that allows you to break giant blocks
