### ISSUE TITLE
Twilight scepter projectiles can't damage Hydra, don't deflect its fireballs, break on contact instead of being deflected

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1366]
### Forge Version

Fabric 0.11.6

### Twilight Forest Version

4.0.118

### Steps to Reproduce

1. Spawn hydra
2. Equip twilight scepter
3. Enter survival mode to make hydra aggro
4. Wait for a head to use fireball attack
5. Spam twilight scepter projectiles at where the fireballs are coming from
6. Get closer to the Hydra
7. Fire twilight scepter at one of hydra's mouths while open
8. Fire twilight scepter at hydra's body

### What You Expected

Like arrows, twilight scepter projectiles
- would damage the hydra if shot at its open mouths when the player is close enough
- would be able to parry the hydra's fireballs when they touch one
- would deflect off of the hydra like arrows when shot at it from afar

### What Happened Instead

Twilight scepter projectiles can't damage the hydra at all, don't parry its fireballs on contact, and simply break into a few particles on contact with it, instead of deflecting off of it like arrows.

### Additional Details

I wasn't able to test if this occurs on Forge, but, upon checking in with the Discord server, Gizmo made it sound like the scepter has numerous issues on both modloaders. If this doesn't occur on Forge, I can report this to the fabric repo.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
Twilight scepter bolts are now classified as projectiles, so this works properly now. Did some testing myself and it seems to work as intended now
