### ISSUE TITLE
No Trophy Pedestal at Stronghold Entrance

### ISSUE THREAD

**Issue by ChiefBalthazar** [TeamTwilight/twilightforest#1368]
### Forge Version

0.185.2.1

### Twilight Forest Version

1.47a

### Steps to Reproduce

After finding the entrance to the Stronghold, another structure (roots and such) had invaded the opening area, and caused there to be no Trophy Pedestal. I had to go into creative and place one in order to continue playing.
![Screenshot 2021-10-27 203548](https://user-images.githubusercontent.com/93300834/139176494-058537ef-51ab-4751-9fa7-e2793d4e60ff.png)

### What You Expected

According to some youtube walkthroughs I watched, the pedestal is usually right next to the square opening in the floor that leads to the Stronghold.

### What Happened Instead

Instead, I found some roots and pumpkins in a half-destroyed room that had a hole in the floor, and there was no way to remove the shield from the stronghold.

### Additional Details

I am using RAD, which has additional mods on top of TF. Some ores appeared in the TF dimension, but there were no other apparent examples of world generation being effected by the other mods.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Drullkus** [comment]
> 1.47a

Where the heck did you download this version

**Comment by GizmoTheMoonPig** [comment]
What is that version of TF and forge????
anyway, this has been fixed in later versions. Things wont be able to replace pedestals anymore.

**Comment by DaemonUmbra** [comment]
...That's the modpack version...
https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons/files/3464722
