### ISSUE TITLE
[Suggestion] Please do not discontinue 1.16.5 updates!

### ISSUE THREAD

**Issue by LuciusV** [TeamTwilight/twilightforest#1369]
### The Suggestion

Hi,
It certainly seems that 1.16.5 would be main version for most modpacks for at least 1-2 years, as only a handful core mods are updated to 1.17 now. It would be a pity do not have final boss and other latest updates in 1.16.5 modpacks including TF.
Please, keep at least adding most important updates...

### Why Should It Be in the Mod?

Described above

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
We've become too dependent on 1.17 to backport, no dice sadly
