### ISSUE TITLE
Castle Rune Brick Colour

### ISSUE THREAD

**Issue by EjJon** [TeamTwilight/twilightforest#137]
Forge version: 1.11.2-13.20.1.2429
Twilight Forest version: 2.4.0.129
(No Crash)

The castle rune bricks are displaying like this for some reason (This is without Optifine): 

![2017-08-09_22 06 49](https://user-images.githubusercontent.com/30797926/29144049-51c88abe-7d4f-11e7-8277-eb071b8333c2.png)

When using Optifine they display as solid colour blocks:

![2017-08-09_22 11 52](https://user-images.githubusercontent.com/30797926/29144175-dd805eb0-7d4f-11e7-942d-af97f8233507.png)

Edit: Using CTM does fix the issue both with and without Optifine.

**Comment by Andromander** [comment]
Optifine has some compatability issues with Twilight Forest, if I recall. Try using CTM to enhance the castle brick runes

**Comment by Drullkus** [comment]
Partial duplicate of #133 and also don't use Optifine

**Comment by williewillus** [comment]
Is it possible to have an alternate model/check if optifine is loaded? It's fine if fulbright doesn't work but a solid color looks a bit ugly :P

**Comment by Drullkus** [comment]
@williewillus, added CUTOUT render layer
