### ISSUE TITLE
Lost Connection after going through portal

### ISSUE THREAD

**Issue by TheSwitzVirgin** [TeamTwilight/twilightforest#1370]
### Forge Version

36.1.23

### Twilight Forest Version

4.0.546

### Client Log

https://gist.github.com/TheSwitzVirgin/6d8edb054be4d25a7b05d4e28d8a4443

### Steps to Reproduce

My girlfriend crashes everytime she tries to enter or leave the Twilight Forest Dimension. I have Optifine installed, but I already tried to remove Optifine and trying it again and it still crashes. 

Step 1 - My Girlfriend enters my server.

Step 2 - She enters/leaves the Twilight Portal

### What You Expected

Entering or Leaving the Dimension without any problems.

### What Happened Instead

She loses connection from the server.

### Additional Details

Message that appears on her screen after losing connection:

_Internal Exception: io.netty.handler.codec.EncoderExcpetion: java.lang.IndexOutOffBoundsException: index: 256, lenght: -203 (expected: range(0, 256))_

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by Tamaized** [comment]
If this is LAN then there's not much we can do about it. LAN has issues.

Otherwise I cant reproduce this, and 1.16 is no longer supported.
