### ISSUE TITLE
Mob Textures not loading correctly

### ISSUE THREAD

**Issue by phDoenix** [TeamTwilight/twilightforest#1375]
### Forge Version

36.2.0

### Twilight Forest Version

4.0.546

### Client Log

https://gist.github.com/phDoenix/eee1aaf7e6b4a7336efa6d51d808a187

### Steps to Reproduce

1. Install The Twilight Forest on Curseforge
2. Load into the game and go into Twilight Forest
3. Notice some mobs with flickering textures while deer torso's float a meter above their bod
![2021-11-06_19 34 03](https://user-images.githubusercontent.com/93850160/140631622-d243b822-13d3-4c21-ad04-9611a9872343.png)
![2021-11-06_19 34 04](https://user-images.githubusercontent.com/93850160/140631626-e30daa81-103b-43f7-8d8f-4c3c59196371.png)
y
![2021-11-06_20 28 54](https://user-images.githubusercontent.com/93850160/140631632-673b7b8a-9739-4c7c-b36d-1365ae294455.png)
![2021-11-06_20 28 23](https://user-images.githubusercontent.com/93850160/140631636-14801ef3-8d50-4365-8dce-6d949f9ad70a.png)

,

### What You Expected

Mob textures to be properly set on their models

### What Happened Instead

Bighorn sheep use their horns to see now (aka model wasn't displaying correctly)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by GizmoTheMoonPig** [comment]
youre using the legacy resource pack. Unfortunately we couldnt get a legacy model loader done for 1.16, so this is how its supposed to be. To fix it just dont use the legacy pack. We'll have this fixed eventually in 1.17 or 1.18
