### ISSUE TITLE
[Suggestion] Goblins Mining/Building Micro colony

### ISSUE THREAD

**Issue by LevGrandSorcerer** [TeamTwilight/twilightforest#1376]
### The Suggestion

Goblin Colony Miner/Building Minion
It would be cool to see the Twilight Forest Goblins be able to Mine blocks and long tunnels or large chunks of blocks like 5X5 to 9X9 underground, even temporarily set of TNT once in a while (Not a lot so it isn't griefable and distracting) to quickly dig a goblin cave as their HQ Base of operations for their evil nefarious plans to take place! >:))) I also suggest they can build (A little bit) like small huts for them to live in, campfires, roast spits, small blacksmith furnace with anvil, etc to show industry expanding, like a micro colony, if you don't hurt them and watch from a distance where they cant see you or invisible they will mine and build these things. Like the Goblin Town caves from the hobbit and LOTR Orc industry and caves building

### Why Should It Be in the Mod?

It will make the Goblins more menacing and more calculating, to have them build micro colonies and mining around themselves, if makes it feel like they are plotting against the player and surviving together while they cackle their laughs, it will make the goblins more immersive

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
While it would make them much more lively, this is far outside the scope of the mod. It would be an almost entirely new mod on its own akin to [Millénaire](https://www.curseforge.com/minecraft/mc-mods/millenaire).
