### ISSUE TITLE
Naga and hydra spawn with only head/body

### ISSUE THREAD

**Issue by natalie-j-w** [TeamTwilight/twilightforest#1377]
Forge version: 36.2.8
Twilight Forest version: 4.0.546

The Naga spawns without a body, only the head. The Hydra spawns only with a body but without heads (or invisible heads) shooting fire balls, but the heads can't be hit and therefor the Hydra is unkillable. I've tried cheating in a new Hydra with an egg, but the same problem occurs.

What I expected to happen: Extremities

What happened instead: No extremities

**Comment by GizmoTheMoonPig** [comment]
youre using either optifine or entity culling, please remove whichever you have. This isnt something we can fix.

**Comment by Tamaized** [comment]
**Please follow issue templates, they exist for a reason!**
![image](https://user-images.githubusercontent.com/9671313/141002446-2b4369df-25f4-40ef-93b8-abae836f45c9.png)
