### ISSUE TITLE
1.16.5 Unable to break or place blocks

### ISSUE THREAD

**Issue by SilencedSoppu** [TeamTwilight/twilightforest#1378]
### Forge Version

36.2.0

### Twilight Forest Version

4.0.546

### Steps to Reproduce

create portal
jump in
unable to place blocks
unable to break blocks

### What You Expected

able to break blocks and place them to get to places normally out of reach

### What Happened Instead

unable to do anything with breaking blocks or placing anything which in turn stops progression for being able to place trophies in the dark forest.

### Additional Details

The only thing i can think of is this mod was added after the world was generated and along side it IE was added as well.
We got to talk to the server owner and while OP'd and in creative they themselves were unable to break or place blocks.
Not sure if we did something wrong or what the heck is going on.
Any and all help would be appreciated to try and assess what is going on.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Are you able to reproduce this in Single Player

**Comment by SilencedSoppu** [comment]
did not try that
...
Just tested and things are able to be broken and placed in single player.

**Comment by DaemonUmbra** [comment]
Are you able to provide the save?

**Comment by SilencedSoppu** [comment]
i am running through MultiMC to keep things organized and for some reason no save exists.

**Comment by DaemonUmbra** [comment]
Well if you're playing on a server the save would be on the server

**Comment by SilencedSoppu** [comment]
i can ask for it when they wake up and provide it then.

**Comment by Drullkus** [comment]
What extra mods/plugins does the server have? Chances likely are it's not our problem

**Comment by SilencedSoppu** [comment]
![explorer-11-09-2021-23-03-56](https://user-images.githubusercontent.com/50304989/141047795-ed332290-b211-4b1d-9dee-85bf31f905ad.png)

**Comment by Drullkus** [comment]
Those are your client mods, I'm asking about the server (Which you'll need to ask your Server's operator)

**Comment by SilencedSoppu** [comment]
server mods?
that is the servers mods, everyone has everything the server has

**Comment by Drullkus** [comment]
Then... why are you able to place/break blocks in Single Player and not on the Server? You'll need to poke your Server's operator and have them let us know of any extra mods/plugins they have so we can properly diagnose this issue.
