### ISSUE TITLE
Portals generate in locked/dangerous biomes

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1379]
### Forge Version

37.0.104

### Twilight Forest Version

1.17.1-4.0.816

### Client Log

https://gist.github.com/Shedao-Shai/afbc7f25513019319f15a809d51f7771

### Steps to Reproduce

1. Create a tf portal in the overworld\
2. If luck is not shining on you, the portal will come out in a dangerous/locked biome (in this case the swamp)
3. Suffer due to a hostile environment

### What You Expected

The portal to redirect to a safe location close to the original coordinates

### What Happened Instead

The portal came out in the correct coordinates, but in the process came out in the incorrect biome

### Additional Details

![2021-11-10_17 22 17](https://user-images.githubusercontent.com/23658767/141210140-8882bd40-cba8-4e66-bb20-72da054adbb3.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
redirecting this to #1459 so we can keep track of every portal issue in 1 place
