### ISSUE TITLE
Magic Tree Cores work backwards

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#138]
Forge version: 13.20.0.2315
Twilight Forest version: 2.4.0.133

Steps to reproduce:
1.  Plant two of the same Magic tree saplings, preferably having a large distance between them
2.  Have one core active and one inactive

What I expected to happen:
The greyed out core would be idle, not affecting the environment/doing it's purpose, while the active one would do it's special trait

What happened instead:
It seems that the cores work in the opposite way they should. Greys out trees are active, whereas 'Active' trees remain idle

**Comment by Tamaized** [comment]
state textures might be inverted, haven't checked yet however looking at the 1.7.10 version the tree spawns with the active texture meanwhile the current 1.11.2 versions it spawns with the grayed out texture.
