### ISSUE TITLE
[Suggestion] Three ideas for renewable carminite

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1380]
### The Suggestion

Look over the following ideas for making carminite farmable and pick one:
- Replace borer essence with *carminite residue*, which would look like a slimy paste with carminite's colours. Remove it from towerwood borer loot table and add it to the loot tables of carminite ghastlings, guards, and possibly golems and/or broodlings.
OR
- Make carminite ghastlings, ghastguards, and possibly golems and/or broodlings have a chance to drop carminite to make carminite renewable. Remove carminite crafting recipe. Remove borer essence item.
OR
- Make carminite ghastlings/guards drop carminite when killed by a ghast trap. Remove carminite crafting recipe. Remove borer essence item.

### Why Should It Be in the Mod?

- To make carminite in large quantities, you need to grind for borer essence, which is a dull, monotonous and frustrating experience. Redstone dust can be farmed from witches or mined en masse in the TF's hollow hills, or just from regular mining, and ghast tears can be farmed from ghasts in nether ceiling soul sand valley farms, but there is no way to make obtaining bulk borer essence easier because it isn't renewable, forcing players who need the stuff to grind.
- There is no unique reason to farm dark tower mobs at the moment because they all drop vanilla items that can be obtained elsewhere. Knight stronghold farms yield armour shards for players wanting knightmetal blocks for farms; labyrinth farms are the only renewable source of charms of keeping; giant cottages yield giant pickaxes for large scale excavation; even medium hollow hill farms make for a nice upgrade to regular mob farms. If carminite ghasts/golems/broodlings dropped carminite or some component of it, there'd be a reason to make a mob farm in the tower.

Specific pros and cons of my three ideas:
**Having ghastlings, guards, golems and/or broodlings drop *carminite residue* as a replacement for borer essence**
Pros:
- Makes carminite renewable, because redstone dust and *carminite residue* are both renewable, solving the borer essence grind issue.
- Gives players a unique reward for facing off against the tower's mobs instead of regular loot available elsewhere, much like how labyrinth, knight stronghold and snowy forest mobs have unique loot.

Cons:
- Introduces a micro craft item that may not be necessary. After all, ghast tears can also be farmed in the tower without much extra effort, and redstone dust is already needed to turn the carminite into the machines.

**Having ghastlings, guards, golems and/or broodlings drop carminite directly with a low chance**
Pros:
- Makes carminite renewable, solving the grind issue.
- Gives players a unique reward for facing off against the tower's mobs instead of regular loot available elsewhere, much like how labyrinth, knight stronghold and snowy forest mobs have unique loot.
- No micro craft items, and actually removes one microcraft item due to the removal of borer essence.

Cons:
- Removes the requirement of diverse or outside ingredients to make carminite. However, farming just carminite versus farming both carminite and ghast tears isn't much of a difference because both can be farmed in the tower, and, as mentioned above, all of the carminite machines use redstone dust in their recipes, so requiring more isn't too significant either.

**Make ghastlings/guards drop carminite when killed by a ghast trap**
Pros:
- Makes carminite renewable, solving the borer essence grind issue.
- Gives an additional use to ghast traps. A fully automatic farm could be made by, for example, clearing the logs from one of the large log rooms with carminite ghastling spawners inside, using snow golems to push the ghasts into a knightmetal block to die near a trap, and activating the trap with a redstone clock every so often to kill additional ghasts for carminite.
- Makes a rather unique sort of farm needed to farm carminite.
- No micro craft items, and actually removes one micro craft item due to the removal of borer essence.

Cons:
- Not immediately obvious to players. Even with an advancement to explain how this works, expect players to pop into your discord every so often asking how to get carminite.

I would love to discuss this with the devs if you'd like to.~

Similar to #1339, but acknowledges other possibilities and the issue with borer essence being too grindy.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by saltyseadoggo** [comment]
Regarding how removing or replacing the essence makes borers useless:
I'm aware, and, honestly, I don't want borers to be use*ful* if it means tediously grinding for their essence. My suggestions all make carminite able to be obtained en masse without tedium. My suggestions also make obtaining carminite less about whacking weird termites that many players don't ever encounter, and more about whacking the actual carminite mobs.

**Comment by VilligerKing** [comment]
Imo carminte shouldn't drop for a few reasons, but regarding renuability, there's enough carminte in the towers as is, considering you can uncraft all the carminite devices, aswell as the borders, that's atleast 2-4 stacks of carminite from one tower

**Comment by saltyseadoggo** [comment]
> Imo carminte shouldn't drop for a few reasons, but regarding renuability, there's enough carminte in the towers as is, considering you can uncraft all the carminite devices, aswell as the borders, that's atleast 2-4 stacks of carminite from one tower

I would like to hear your "few reasons" to contribute to this discussion and consider.

One thing renewability really helps with is servers. Dark towers are not the most common structures (only one of them is supposed to generate per magic map area), so, on a server, the first players who want carminite for something will go tear out all of the reappearing blocks/builders/reactors from the nearest towers, leaving none close to spawn for other players. It's an issue vanilla End Cities experience, notably. Carm is less universally appreciated than elytras, but reappearing blocks are pretty good in mob farms, for example.

I don't know what you mean by uncrafting the "borders." If you mean the encased towerwood, unless I missed something, it doesn't uncraft at all due to its recipe becoming a stonecutting recipe.

**Comment by GizmoTheMoonPig** [comment]
I do like the idea with the ghast traps, ill see what other people on the team think about it. 
One issue I have with this suggestion is the idea of removing an item that's been part of the mod since basically forever. I don't like the idea of a. Removing an item and b. Making a mob that had a use become useless. Instead, what about a way to farm borers? It could be something as simple as having multiple come out of 1 block, to something like having them spread through towerwood over time. I'm always open to hearing ideas, but I don't think removing a mechanic from the mod is the best way to go about this.

**Comment by EvergreenSystems** [comment]
I would support the idea of borers spreading throughout the tower, the question would be how long does it take for a given area to become fully infested. The loot table could also be boosted so each borer also drops more essence.

**Comment by saltyseadoggo** [comment]
If borer essence was made renewable to make the current, and imo horribly tedious borer essence grind optional, that would be great imo. I also like the idea of making them drop more essence so, for players who don't want to make a farm, the grind is shorter.
I also like the idea of some other use for the ghast trap, even if it's not related to carminite farming.

Honestly, borers need some help to feel more integrated into the tower conquering experience, but I'm gonna comment on the issue specifically talking about that.

**Comment by Killer-Demon** [comment]
Unfortunately, none of these suggestions mesh all that well with how the mod currently is designed or how we would want to go about things. As @GizmoTheMoonPig said, we're not looking to remove any existing items as they are part of the narrative in said dungeon. We will be having discussions about renewability of items/blocks in the future once we have less on our plate, though, so this topic will be further discussed internally at that time.
