### ISSUE TITLE
Minoshroom AoE makes its allies destroy it before player can fight it

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1381]
### Forge Version

Fabric loader 0.12.5, Discord convo implied this happens on Forge too

### Twilight Forest Version

4.0.133

### Steps to Reproduce

1. Go to labyrinth in spectator mode to prevent activating minoshroom spawner
2. Use /summon to spawn in a number of labyrinth mobs in the cage
3. Position yourself outside of the cage on one side, illuminating and walling off area to ensure no outside mobs sneak up on you
4. Enter survival mode
5. Break a fence
6. Get minoshroom to target you
7. Wait for minoshroom to perform AoE attack

### What You Expected

Minoshroom's AoE wouldn't cause other labyrinth mobs to turn on it

### What Happened Instead

Minoshroom's AoE causes other labyrinth mobs hit by it to attack the minoshroom. If enough mobs spawn in there, which is made more likely if the player takes the time to explore and light up much of the labyrinth, there will be enough mobs attacking the minoshroom to kill it before the player even has to fight it.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
I thought mobs spawning in the cage was fixed recently, has it not?

**Comment by EvergreenSystems** [comment]
I cannot replicate mobs spawning in the cage in the forge version of the mod (tf 4.0.823, forge 37.0.104), if this is still an issue it is specific to fabric. (30 cages were searched to come up with this result, I think that is a safe number to confirm that mobs spawning in the cage on forge no longer occurs)

**Comment by saltyseadoggo** [comment]
I determined this to be an issue with the cage room spawning mobs on Fabric, and reported it there. Closing this issue.

**Comment by EvergreenSystems** [comment]
I am going to walk back what I said, I have replicated mobs spawning inside the cage on forge (tf version 4.0.823) with cave spiders spawning in the cage.

**Comment by EvergreenSystems** [comment]
![2021-11-16_19 32 14](https://user-images.githubusercontent.com/23658767/142092828-3098bd41-b64b-4e7f-b485-e2772afd22ce.png)
These guys

**Comment by Tamaized** [comment]
This doesn't happen on the current 1.18 dev builds
