### ISSUE TITLE
[Suggestion] Make druid hut/well wood types configurable

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1382]
### The Suggestion

Make the wood types used for druid hut roofs/floors/furniture and wells configurable, so the player can look at some type of file, see all of the wood types used by the mod to make these structures and the rarity tiers you mentioned in a previous issue, and put any wood type of any mod into any rarity tier.

### Why Should It Be in the Mod?

- Mod compatibility. Modpack dev wants BYG or BoP woods to generate in huts/wells? Now it would be possible.
- If someone wants to make the treasure woods as frequent in huts/wells as they used to be, they could.
- If some mad person wants huts and wells to use crimson and warped wood like you didn't like, they could do that too. :p

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
~~They already are via nbt structure files~~ nvm im dumb

**Comment by Tamaized** [comment]
@Drullkus I blame you for hardcoding this :P could prob do some tag or set of tags https://github.com/TeamTwilight/twilightforest/blob/1.17.x/src/main/java/twilightforest/enums/StructureWoodVariant.java

**Comment by Drullkus** [comment]
That's a mapped data structure, you cannot tag it

**Comment by Tamaized** [comment]
Eugh, lame

**Comment by Drullkus** [comment]
It's not lame, there's no other solution. LMK if you have one

**Comment by Tamaized** [comment]
It's lame that there's no other solution is what i mean

**Comment by Tamaized** [comment]
One word: Codecs

**Comment by Drullkus** [comment]
Discussed it over Discord, there's an approach we have now. Won't be hard just will need time

**Comment by Drullkus** [comment]
implemented with f23a3b5b11208c25ad6f88d85a1ce21f0708a238
