### ISSUE TITLE
Make mob spawning more flexible

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#1383]
Reading through some mobs' `canSpawn` static methods, we can definitely make a few of these more flexible for datapackers who wish to add these mobs to their own biomes. Some of them need a complete logic overhaul while others like the Penguin would best be expanded into a block tag

**Comment by GizmoTheMoonPig** [comment]
changed the giant and penguin to use a block tag in ab1350184eafbe546e09cd9c8b8cd37f4d982231, will look over spawning logic for other mobs that have strange criteria in the nearby future
