### ISSUE TITLE
Block and Chain cannot hit multiparts

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1385]
### Forge Version

1.17.1-37.0.109

### Twilight Forest Version

4.0.826

### Steps to Reproduce

1. Aquire a block and chain, and locate a naga/hydra/ice queen
2. Attempt to damage the multipart portion of the boss

### What You Expected

The boss to take damage per normal, or in the case of the ice queen for the multipart to shield her from damage

### What Happened Instead

In the case of the naga and hydra the multipart completely ignores the B&C, and in the case of the ice queen it either ignores it and nothing happens, or the ice queen takes damage if aimed properly.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Fixed by 0e44e0473d6723e6829e821119ef547eaaba1804
