### ISSUE TITLE
Fix stronghold shield blocks

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#1388]
1.6 - Knight Stronghold's underground pieces used to be fully encased in Structure Shield blocks with the green side facing inside. The 1.7 transition to the progression system

**Comment by Drullkus** [comment]
Yeah I should've put a description. I saw a problem during a convo and left this here as a reminder. I don't remember anymore :^)

**Comment by GizmoTheMoonPig** [comment]
He forgor 💀

**Comment by GizmoTheMoonPig** [comment]
this was intentionally removed, we dont need to bring them back
