### ISSUE TITLE
Ur-Ghast bug 

### ISSUE THREAD

**Issue by hardusinho** [TeamTwilight/twilightforest#1392]
### Forge Version

36.2.9

### Twilight Forest Version

4.0.546

### Steps to Reproduce

1. host the world to lan
2. go to urghast tower
3. spawn urghast
4. it disappears

### What You Expected

I expected it to not be invisible, and i should be able to hit him

### What Happened Instead

i am able to hit him but i cannot see him which makes it really hard in survival mode

### Additional Details

i dont use sponge, i have it in the modpack better minecraft but i dont know what to do to stop it from happening

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Can you share us your full mod list please

**Comment by hardusinho** [comment]
https://www.curseforge.com/minecraft/modpacks/better-minecraft-plus/relations/dependencies

here is the site with all mods included in that modpack

**Comment by Drullkus** [comment]
Yikes 15 pages of mods. Can you please try isolating the problem by binary searching for it?

The way binary searching works is that you remove half of the mods, add back in all dependencies and Twilight Forest. Find out if that causes the problem.

If that doesn't cause the problem, then try the opposite half and see if those cause a problem with the Twilight Forest.

Keep searching for the half that does cause the problem until you arrive at a fully reduced set of mods that still causes the issue to occur.

**Comment by Tamaized** [comment]
Closing as there hasn't been an update.
