### ISSUE TITLE
Right-nagastone stairs and its variants are uncraftable

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1394]
### Forge Version

37.0.104

### Twilight Forest Version

4.0.823

### Steps to Reproduce

1. Attempt to craft both left and right nagastone stairs (and/or the mossy and weathered varients)

### What You Expected

To be able to craft both "sides" of stairs

### What Happened Instead

Only left nagastone stairs are craftable: entering the flipped recipe for right stairs results in a crafting output of left regardless. The right stairs _can_ be stonecut with the stonecutter, but not in any crafting table.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
closed as a recipe already exists, its just an upside down stair recipe
