### ISSUE TITLE
The server crashes and freezes 

### ISSUE THREAD

**Issue by xxlio109** [TeamTwilight/twilightforest#1396]
### Forge Version

forge-1.16.5-36.2.8

### Twilight Forest Version

twilightforest-1.16.5-4.0.546-universal

### Client Log

https://gist.github.com/xxlio109/87b8420e170f181c513471bd43296327

### Crash Report (if applicable)

https://gist.github.com/xxlio109/09e52ff36091091bbf3dd7f6a8497766

### Steps to Reproduce

Player crashes after being killed by Minotaur 

### What You Expected

It may be caused by an item in the player’s inventory 

### What Happened Instead

The server crashes and freezes 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
seems like the grave pet from Inventory Pets caused the crash. I don't think this is our issue, but if it does somehow get traced back to something we do, please reopen this.
