### ISSUE TITLE
fly glitch ( with wings mod

### ISSUE THREAD

**Issue by oyasumi-sama** [TeamTwilight/twilightforest#1397]
### Forge Version

1.16.5

### Twilight Forest Version

1.16.5

### Steps to Reproduce

first of all i have the wings mod https://www.curseforge.com/minecraft/mc-mods/wings downloaded

1st step: equip the wings from the wing mod and build the twilight portal

2nd step: fly using the wing mod into the portal

3rd step: double press the spacebar and you will be able to fly like in creative 

if you are with this glitch you can just jump into the portal again (without flying using the wing) and you will not be able to fly like in crative anymore or if you are in a server ( im using aternos) just rejoin.

### What You Expected

that i would not be able to fly like in creative

### What Happened Instead

 i began to fly like in creative if i double jumped

### Additional Details

wings mod [https://www.curseforge.com/minecraft/mc-mods/wings](url)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
I don't understand the issue, you downloaded a flight mod and expected not to be able to fly? What? And how is this our problem exactly?

**Comment by Drullkus** [comment]
I'm not convinced this is our issue, go report to https://github.com/pau101/Wings/issues please
