### ISSUE TITLE
Naga Trophy doesn't grant the advancement

### ISSUE THREAD

**Issue by Tamaized** [TeamTwilight/twilightforest#1398]
This was lost during 1.12 porting efforts, see
https://github.com/TeamTwilight/twilightforest/commit/3d84c2ad19f0e08e760c4038bad24c081d81662e#diff-fc2c0e4c75a249b4e4c4c257ef83a0311071a22916fbffa600dacac5d5846aa6
the grant code in the TFEventListener was never actually replaced in any advancement file.

Blame willie for this 4 year old bug

**Comment by williewillus** [comment]
pausechamp

**Comment by GizmoTheMoonPig** [comment]
fixed in 675e0bc32df369a770d59eafc5e1c2553c07a0e1
