### ISSUE TITLE
Game not launching after downloading Twilight Forest

### ISSUE THREAD

**Issue by mezzodepresso** [TeamTwilight/twilightforest#1399]
### Forge Version

37.0.25

### Twilight Forest Version

4.0.849

### Client Log

https://gist.github.com/mezzodepresso/2529f27c44e174543abc32ba3e19552b

### Crash Report (if applicable)

Cannot find crash report

### Steps to Reproduce

1. Download mod
2. Launch game

### What You Expected

I expected the game to launch properly.

### What Happened Instead

Once I tried to launch the game, the server crashed giving me an "error code:0" message

### Additional Details

I noticed in the debug log that it says that there is a mandatory mod missing. Once I removed the Twilight Forest mod this message went away and my game launched as normal.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Update forge, you're insanely outdated

**Comment by mezzodepresso** [comment]
Thank you so much! I downloaded the latest Forge version and it worked.
