### ISSUE TITLE
Game crash when click on the SortingWood

### ISSUE THREAD

**Issue by JunkGD** [TeamTwilight/twilightforest#140]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1

What I expected to happen:
the eyes on the log open and something happen 

What happened instead:
when i right click on this log the game crash

sorry i'm french so my  english is not very very good :/

**Comment by williewillus** [comment]
we need the crash log (lots of text that the launcher shows when the game is running).
put it on something like pastebin.com

**Comment by Drullkus** [comment]
Probably related to #138

**Comment by Drullkus** [comment]
When I use the Sorting Wood engine, it works just fine in both states. I will need the crashlog to properly diagnose the problem.

**Comment by Drullkus** [comment]
Closing. I don't think anyone's having this issue then.
