### ISSUE TITLE
Hedge maze generation bug

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1400]
### Forge Version

37.0.126

### Twilight Forest Version

4.0.842

### Steps to Reproduce

1. Enter the Twilight Forest and locate a hedge maze

### What You Expected

Typical smooth generation under the maze

### What Happened Instead

The maze generated on a sort of shelf, and in the midst of a chunk boundary-related generation bug. I suspect this is related to biome shuffling and all of the fun can of worms that that opens.

### Additional Details

![2021-11-29_14 41 27](https://user-images.githubusercontent.com/23658767/143977158-8204d46f-bc16-48b2-ac33-200bb3df6cd4.png)
![2021-11-29_14 42 21](https://user-images.githubusercontent.com/23658767/143977162-fa5700b7-63af-464a-b01f-144f5d0b6e44.png)

Map showing the maze and the surrounding generation issues
![2021-11-29_14 41 34](https://user-images.githubusercontent.com/23658767/143977204-95897579-3e08-4b4a-8a74-943592492f71.png)

Zoomed-out map showing wider generation bugs, notice the biome boundaries along chunk borders.
![2021-11-29_15 56 15](https://user-images.githubusercontent.com/23658767/143977242-fcc7bacd-5fc0-4d7f-85dc-c093a0dd7d77.png)

This was identified on the tf testing server earlier today, coords are listed in each picture if you desire to see this specific issue for yourself.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
(Potentially) fixed in 9e8d5fe56545955f14bb76f1eb18cec014273c64
