### ISSUE TITLE
Non [a-z0-9/._-] character in path of location: twilightforest:textures/block/Untitled.png

### ISSUE THREAD

**Issue by Zarepheth** [TeamTwilight/twilightforest#1402]
### Forge Version

37.0.126

### Twilight Forest Version

4.0.849

### Crash Report (if applicable)

https://gist.github.com/Zarepheth/2061a5213e327e416c51eb2e0cdbea58

### Steps to Reproduce

I have a CurseForge on OverWolf profile for the Valhesia 4 modpack on which I have added numerous mods (and turned off a few).

Pre-condition: add all the mods on the crash report's list of mods.

1. Start the game from OverWolf client.
2. When the native launcher is ready, hit the "Play" button.
3. Wait a minute or so for the game to crash.

### What You Expected

I expected the game to finish loading and bring me to the main menu.

### What Happened Instead

I suffered a crash which accuses Twilight Forest of having an illegal character in the path of a resource.

### Additional Details

I would not be surprised if the crash occurred due to another mod.

I updated three mods this evening, and turned on three other mods (which were previously turned off).

Mods recently turned on:
- engineersdecor-1.17.1-1.1.17.jar
- JustEnoughResources-1.17.1-0.13.0.131.jar
- BetterAdvancements-1.17.1-0.1.2.116.jar

Mods recently updated:
- JAOPCA-1.17.1-4.a.0.4.jar
- Cyclic-1.17.1-1.6.5.jar
- curios-forge-1.17.1-5.0.2.0.jar

I'll do some more trouble-shooting to see if one of the above might be related to the crash. Last night, those changes were not present and I made it to the main menu.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
fixed. we'll be pushing a new CF build out pretty soon anyway since we're moving to 1.18, just give us a little :)

**Comment by Zarepheth** [comment]
That was incredibly fast!

**Comment by Zarepheth** [comment]
Has anyone explained why resource paths cannot use more than that small set of characters?
And why am I now getting fatal errors for such when last night I did not (I think I'm using the same Minecraft and Forge versions)?

**Comment by Tamaized** [comment]
its a Vanilla Minecraft restriction that had existed for a long time but only began being enforced around 1.10. It only fails when actually loaded into the game, which we did not do here with these textures but there are mods out there that are a bit aggressive and will load all assets for all mods on the install, you most likely have such a mod

**Comment by Zarepheth** [comment]
Looks like it was "curios-forge-1.17.1-5.0.2.0.jar" was the problem. However, authors have already fixed it.
https://github.com/TheIllusiveC4/Curios/issues/183
