### ISSUE TITLE
putting banner into loom w/ naga scale pattern caused client crash on official server

### ISSUE THREAD

**Issue by skythegguy** [TeamTwilight/twilightforest#1404]
### Forge Version

37.1.0

### Twilight Forest Version

1.17.1-4.0.860-universal

### Client Log

https://gist.github.com/skythegguy/8f26e6224b9f23d6ca0222e0f22b2ce4

### Crash Report (if applicable)

https://gist.github.com/skythegguy/403834d82c79939584fa78df2acc4bd2

### Steps to Reproduce

place naga pattern, banner, and black dye into loom (works in any order)

### What You Expected

I expected to see what the naga scale banner pattern

### What Happened Instead

game crashed upon shift clicking banner into loom, server did not crash.
Second test putting naga pattern into loom last instead of banner, game still crashed.

### Additional Details

I was on the official twilight forest server.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
forgot to close this, but its fixed now
