### ISSUE TITLE
Yeti Horned Helmet enchantment layer overlapping other large items

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1405]
### Forge Version

36.2.9

### Twilight Forest Version

1.16.5-4.0.546

### Steps to Reproduce

1.place a knight metal helmet in your inv
2. place yeti helmet next to it(right side)
3. Knight metal helmet right side get enchanted

### What You Expected

Enchantment layer to be smaller

### What Happened Instead

Helmet side getting enchanted
![unknown - 2021-12-08T042719 983](https://user-images.githubusercontent.com/29407027/145143198-6c0d44a9-0478-405c-b9fb-a57464348e86.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
unfortunately this is an issue with all of our 32x32 textures. The enchantment bleeds over into other slots that have 32x32 items. I attempted to make this less of an issue in 1.17, but it didnt fix it completely. The best way we can fix this is to make the textures 16x16 instead

**Comment by ghost** [comment]
What about 18x18?

**Comment by GizmoTheMoonPig** [comment]
it'll be an issue with any texture larger than 16x16

**Comment by Drullkus** [comment]
I'll take a stab at it at a later time, no guarantees
