### ISSUE TITLE
Item using overlapping GUI model aren"t hold correctly

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1406]
### Forge Version

36.2.9

### Twilight Forest Version

1.16.5-4.0.546

### Steps to Reproduce

1.Hold any items who use overlapping models(knightmetal helmet,maze ore map,yeti helmet,moonworm queen)

### What You Expected

Item to be held correctly like the generated model

### What Happened Instead

Item using handheld model

### Additional Details

![unknown - 2021-12-08T043248 753](https://user-images.githubusercontent.com/29407027/145143698-a3ae00d0-8bd7-42f5-8719-44f790a76b7e.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
fixed in 1.17. Since we dont support 1.16 anymore it wont be fixed there, but you could do it yourself with a resource pack instead
