### ISSUE TITLE
[Suggestion] Unique spawn eggs texture

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1407]
### The Suggestion

Since 1.17,you are able to make custom spawn eggs textures,its not using hardcoded colours anymore

### Why Should It Be in the Mod?

A bit more uniqueness to twilight

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This is not something we're looking or wanting to do at the current time.
