### ISSUE TITLE
[Suggestion] Animated sprites

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1408]
### The Suggestion

Animated sprites for transformation powder,borer essence,lamp of cinders,ice bomb

### Why Should It Be in the Mod?

Cool Visual addiiton to these sprites

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
While it would be cool, such changes would be more appropriate for a fan-made resource pack. At the very least, it's not a change we're looking to make currently.
