### ISSUE TITLE
Is Magic Map's icon changed ?

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#141]
Forge version: forge-1.11.2-13.20.1.2454-universal.jar
Twilight Forest version: (this is the build number): twilightforest-1.11.2-2.4.0-universal.jar

Is Magic Map's icon changed ?
ver 2.3.7's magic map
https://img.atwikiimg.com/www26.atwiki.jp/minecraft/attach/644/27009/twilight_map_20151012.gif

ver 2.4.0's magic map
![magic_map](https://user-images.githubusercontent.com/2891031/29578147-3106f874-87a9-11e7-8d39-3c3c7ba7880f.png)

**Comment by williewillus** [comment]
temporary workaround until i can get stuff into forge

**Comment by ghost** [comment]
what do you mean ?
please teach me more details.

**Comment by Tamaized** [comment]
We're waiting for some code to get into MinecraftForge before we can do anything about this.

**Comment by ghost** [comment]
OK thanks.
by the way 1.11.2 forge is too old.
is it new release this version forge ?

**Comment by williewillus** [comment]
the code that I need to get in is going to 1.12 so the mod will need to be ported.
