### ISSUE TITLE
[Suggestion] Renaming mobs spawn egg to fit with lang file name

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1410]
### The Suggestion

Renaming lich_spawn_egg to twilight_lich_spawn_egg
quest_ram_spawn_egg to questing_ram_spawn_egg
wraith_spawn_egg to twilight_wraith_spawn_egg
squirrel_spawn_egg to forest_squirrel_spawn_egg
bunny_spawn_egg to forest_rabbit_spawn_egg
deer_spawn_egg to wild_deer_spawn_egg
yeti_alpha_spawn_egg to alpha_yeti_spawn_egg
redcap_spawn_egg to redcap_goblin_spawn_egg
raven_spawn_egg to forest_raven_spawn_egg
tower_termite_spawn_egg to towerwood_borer_spawn_egg
wraith_spawn_egg to twilight_wraith_spawn_egg

### Why Should It Be in the Mod?

consistent spawn eggs name

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
discussed in discord. Some of these have already been done as the old names didnt make much sense, (tower_termite, mini_ghast, etc.) The others match the raw IDs of the mobs, not the translated names, and we would like to keep it that way :)
