### ISSUE TITLE
[Suggestion] Update zh_tw.json

### ISSUE THREAD

**Issue by xz123456xz** [TeamTwilight/twilightforest#1411]
### The Suggestion

Hi. I translated a file for Twilight Forest mods, I hope the author can add this file. thanks~

Version 1.17.1 [URL](https://gist.github.com/xz123456xz/504eafdc5ed1a607f84e13010653faba)

Version 1.17.1 file :[zh_tw.zip](https://github.com/TeamTwilight/twilightforest/files/7682262/zh_tw.zip)
 

### Why Should It Be in the Mod?

Outdated translation

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Hey there, a couple things:
1. Language translations should be submitted through pull requests. This allows us to check over the files and make sure everything is translated and there. You can look up how to make pull requests if you dont know how to. 
2. 1.17 will not be seeing any more updates. Please aim for the 1.18 branch instead. 
Appreciate the help though!
