### ISSUE TITLE
Chunk generator deforms land for structures even if they can't spawn there

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [TeamTwilight/twilightforest#1413]
The lake is an excellent example of a place where this happens. It'll deform the land for a courtyard or hollow hill but since a structure can't actually spawn there you either get a slab of land or an empty hill. 
![image](https://user-images.githubusercontent.com/67468252/145496259-4917c8da-1e8c-4100-a308-7b557fb263e3.png)

**Comment by Tamaized** [comment]
Is this still a problem, can it be closed?

**Comment by GizmoTheMoonPig** [comment]
pretty sure you fixed this in cc0ffd2512b1c73b12df637ac300316960540258, closing this
