### ISSUE TITLE
Redstone dust and etc placeable inside of hollow logs

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1415]
### The Suggestion

Allow for the placement of redstone dust, repeaters, comparators, etc inside of hollow logs to allow for parallel circuits that don't interfere with each other

### Why Should It Be in the Mod?

Adds more functionality to the already awesome hollow log + potential compat with tech mods such as IE (wires, conveyors, etc)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
This falls pretty far out of scope from the mod's intention with logs, I recommend this feature being put into an addon

**Comment by Killer-Demon** [comment]
As @Drullkus said, this is quite far outside the scope of the log. Unfortunately, I don't think we'll be adding this.
