### ISSUE TITLE
[Suggestion] Lootr support: removing deterministic loot table seeds

### ISSUE THREAD

**Issue by noobanidus** [TeamTwilight/twilightforest#1417]
### The Suggestion

Currently, [Twilight Forest uses a set seed and member method `setLootTable`](https://github.com/TeamTwilight/twilightforest/blob/1.17.x/src/main/java/twilightforest/loot/TFTreasure.java#L129) of RandomizableContainerBlockEntity.

This prevents my mod, [Lootr](https://www.curseforge.com/minecraft/mc-mods/lootr), from replacing these chests with custom loot chests, as my hook relies on the *static* `setLootTable` method instead.

Adjusting/fixing this would be a simple matter of replacing the member `setLootTable` with the static method and providing the world generation context, random, etc. I would make a PR for this, ***but currently loot table seeds are manually calculated***, and it is not possible to do this with the static method.

How desirable is this deterministic loot for the mod?

I've had a number of people request support for it in the past, but basically come up against the fact that this would "regress" the current behaviour into a non-deterministic randomized seed.

On the other hand, all Vanilla loot chests use this static method, for the most part, and thus have random rather than deterministic seeds.

### Why Should It Be in the Mod?

Confer suggestion.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
TF chests seem to be converted to lootr chests nowadays. Do we need to do anything or is this resolved?

**Comment by noobanidus** [comment]
I don't believe there's anything that needs to be done at this point.
