### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [TeamTwilight/twilightforest#1419]
Forge version: 14.23.5.2859 
Twilight Forest version:  3.11.1021 

Link to crash log: 

 [crash-2021-12-17_16.21.37-client.txt](https://github.com/TeamTwilight/twilightforest/files/7736208/crash-2021-12-17_16.21.37-client.txt)

Steps to reproduce:
1. Run Minecraft

What I expected to happen: Minecraft is loaded without crash

What happened instead: Crash

I don't know how to use Gist.

**Comment by Drullkus** [comment]
> `net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: twilightforest/item/ItemTFTransformPowder`

Somehow something is *very* broken. This absolutely should not happen under normal circumstances. Does it only happen if Twilight Forest and Forge is installed?

**Comment by Kasia1403** [comment]
I have very slow computer ( only AMD FX 6300 ) and if mods are loading it takes all day. Should I run only Twilight Forest with this addon mod to test what will happen ? How disabled person can buy better computer if this person has no money ? Hope that this what I'm writing will not make You angry.

**Comment by Kasia1403** [comment]
OK, when I ran Minecraft with only Twilight Forest and Twilight Tweaks everything is OK.
