### ISSUE TITLE
Crash when attacking giant with glass sword under survival mode, possibly due to unchecked cast

### ISSUE THREAD

**Issue by 3TUSK** [TeamTwilight/twilightforest#142]
Forge version: 
Twilight Forest version:

| State     | ID             | Version      | Source                                     | Signature                                |
|:--------- |:-------------- |:------------ |:------------------------------------------ |:---------------------------------------- |
| UCHIJAAAA | minecraft      | 1.12.1       | minecraft.jar                              | None                                     |
| UCHIJAAAA | mcp            | 9.19         | minecraft.jar                              | None                                     |
| UCHIJAAAA | FML            | 8.0.99.99    | forge-1.12.1-14.22.0.2462-universal.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge          | 14.22.0.2462 | forge-1.12.1-14.22.0.2462-universal.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | foamfixcore    | 7.7.4        | minecraft.jar                              | None                                     |
| UCHIJAAAA | foamfix        | @VERSION@    | foamfix-0.7.4-1.12-anarchy.jar             | None                                     |
| UCHIJAAAA | twilightforest | 2.3.8dev     | twilightforest-1.12-2.4.0.11-universal.jar | None                                     |

Link to crash log: https://paste.ee/p/BGj9n

Steps to reproduce:
1. Get to the giant island in the sky via any means;
2. Grab a glass sword;
3. Ensure the gamemode is survival;
4. Find a giant and attack giant with glass sword.

What I expected to happen:
Nothing special except damage is being dealt (and hopefully the glass sword is broken). Side note: only tested with glass sword. Based on my observation on actual code, my speculation is that any damage source will [trigger this](https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/world/TFWorld.java#L13).

What happened instead:
Game crash immediately.

**Comment by Tamaized** [comment]
I assume this was on a dedicated server? I just fixed this type of crash

**Comment by 3TUSK** [comment]
Singleplayer.

**Comment by Tamaized** [comment]
Try it again with build 12 anyway, should still have fixed it.

**Comment by 3TUSK** [comment]
It is fixed indeed.

> Isn't singleplayer just an `IntegratedServer` since Minecraft 1.3 release?

**Comment by Tamaized** [comment]
Yup but I had only experienced it while on a dedicated server so I had thought there was some thread trickery going on but guess not.
