### ISSUE TITLE
Bosses do not render properly when using optifine

### ISSUE THREAD

**Issue by yeetgrenadewastaken** [TeamTwilight/twilightforest#1423]
Forge version: 1.16.5-36.2.20
Twilight Forest version: 1.16.5-4.0.870

Steps to reproduce:
1. load a boss while optifine is installed(any version of optifine seems to cause the issue)

What I expected to happen: I am able to see and interact with bosses fully

What happened instead: only the bosses primary portion(the main head of the naga, body of hydra, etc) renders. the rest of the parts can still be hit by projectiles, however I can not see or interact with them

**Comment by Tamaized** [comment]
duplicate #1023
