### ISSUE TITLE
Duplicated portal in forge multi-server

### ISSUE THREAD

**Issue by Evenstarneko** [TeamTwilight/twilightforest#1424]
### Forge Version

36.2.19

### Twilight Forest Version

4.0.546

### Steps to Reproduce

1. Use a forge multi player server and join more than 2 players
2. I am not sure if this only happens when delay time is long. In my case some players have 400ms+ delay.
3. One of the player open the portal and join, everything is fine.
4. Another player join the same portal some time later, there is a chance (My experience is roughly 10%) that A new portal will be created, and the location is in some forbidden area (like Fire Swamp) and he receives debuff.
5. When that player try to go back using the new portal, it will create another portal in the main world, which is always deep inside some caves.
6. Two portals in main and two portals in twilight forest have the same relative distance.

### What You Expected

Different player join the same portal should be ported to the same place in twilight forest, and it should not be in some forbidden areas.

### What Happened Instead

In my case there is a chance that a second user of the portal will be proted to a new location and likely in a forbidden area. When they come back another new portal in main world will be created. A total of 6 new portals are now exist in my server in two days of playing.

### Additional Details

I am not using Optifine or other bug-related things. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
redirecting this to #1459 so we can keep track of every portal issue in 1 place
