### ISSUE TITLE
Balans improvments

### ISSUE THREAD

**Issue by User-green** [TeamTwilight/twilightforest#1425]
### The Suggestion

- Dors, anti-builders and builders in Ur-gust tower should NOT be brakable with "Brack block" CAD trick.
- Haydra (and all other bosses) sould NOT be killable by lightnighs, explousions and wither effect ("smite", "Effect: wither", "Explode" tricks) unless protections charm is removed.
- Fire (flameing air) in the fire swamps should ignor fire resistnce effect as well as deal damage when player is under/in water
- Walls of the minotaur maze should be much more resistant to explousions (to protect maze from been cleard by TNT or "Explode" trick)

### Why Should It Be in the Mod?

Resons of balans and immersion

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
We don't balance around other mods, if you're having a personal problem with balance then just don't use it.

**Comment by User-green** [comment]
> We don't balance around other mods, if you're having a personal problem with balance then just don't use it.

Okay. Can you please add this to the templet requirements?

BTW. Some of this things can be qualified as minor bugs.

**Comment by Tamaized** [comment]
Using TNT is not a bug, it's intended. Same with creeper explosions
