### ISSUE TITLE
Hydra crush

### ISSUE THREAD

**Issue by Reavez5** [TeamTwilight/twilightforest#1426]
### Forge Version

36.2.22

### Twilight Forest Version

4.0.870

### Client Log

https://gist.github.com/Reavez5/a178d674898a31d42310dc1e6e7735bc#file-latest-log

### Crash Report (if applicable)

https://gist.github.com/Reavez5/c1f359795647d456a58cc39e5351f5d1#file-gistfile1-txt

### Steps to Reproduce

enter the world
spawn hydra
fight it
get the crush

### What You Expected

Im just was fighting hydra

### What Happened Instead

my game has crushed

### Additional Details

I saw something about mortar head in logs

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Problem lies here
`com.talhanation.recruits.RecruitEvents.onProjectileImpact(RecruitEvents.java:41) ~[?:1.2.0] {re:classloading}`

Whatever mod Recruits is

**Comment by Reavez5** [comment]
> Problem lies here `com.talhanation.recruits.RecruitEvents.onProjectileImpact(RecruitEvents.java:41) ~[?:1.2.0] {re:classloading}`
> 
> Whatever mod Recruits is

Thank you so much!
