### ISSUE TITLE
Map Bug

### ISSUE THREAD

**Issue by mikezhl** [TeamTwilight/twilightforest#1427]
### Forge Version

1.17.1-37.1.1

### Twilight Forest Version

1.17.1-4.0.860

### Steps to Reproduce

create a map

### What You Expected

I will apear in the middle

### What Happened Instead

I am outside the map
![image](https://user-images.githubusercontent.com/24950039/147612582-8292623c-3b46-4c0a-bccb-8813d4a138d7.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This was fixed in dc2e55ca534fb4302390161bc22d202256d8c2b7
