### ISSUE TITLE
1.18 crash

### ISSUE THREAD

**Issue by Suncradle** [TeamTwilight/twilightforest#1428]
### Forge Version

38.0.4

### Twilight Forest Version

4.0.873

### Steps to Reproduce

open a world

### What You Expected

mod work's

### What Happened Instead

my game crash

### Additional Details

download from here https://artprodcus3.artifacts.visualstudio.com/Abaabfa6c-deea-4587-ba05-c308c2597b7a/1ef09d39-06cf-41fa-ad98-7258b70c2a72/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3RlYW10d2lsaWdodC9wcm9qZWN0SWQvMWVmMDlkMzktMDZjZi00MWZhLWFkOTgtNzI1OGI3MGMyYTcyL2J1aWxkSWQvMTEzOC9hcnRpZmFjdE5hbWUvUmVsZWFzZQ==0/content?format=file&subPath=%2Ftwilightforest-1.18-4.0.873-universal.jar

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Suncradle** [comment]
why

**Comment by Suncradle** [comment]
your mod is broken

**Comment by Suncradle** [comment]
i uninstall

**Comment by GizmoTheMoonPig** [comment]
because 1.18 isnt even close to being ready. What do you expect from dev builds

**Comment by Suncradle** [comment]
fix or i ununstall

**Comment by GizmoTheMoonPig** [comment]
uninstall then. see if I care

**Comment by Suncradle** [comment]
no
