### ISSUE TITLE
Twilight Forest Data Pack has no 1.18.1 Compatibility and doesn't Load and stops World Generation if not on Safe Mode

### ISSUE THREAD

**Issue by aaronschneider7797** [TeamTwilight/twilightforest#1429]
### Forge Version

39.0.9

### Twilight Forest Version

4.0.873

### Steps to Reproduce

1. Launch Minecraft with the mod. (I used only Forge 1.18.1 and Minecraft 1.18.1 to test the mod)
2. Make a new world with the mod and ignore Data packs error.

### What You Expected

It should load the Data pack normally with 1.18.1 even if 1.18 mods are compatible to Forge 1.18.1.

### What Happened Instead

It doesn't load the Data pack because the game said that it is not compatible with Minecraft 1.18.1.

### Additional Details

![2022-01-02](https://user-images.githubusercontent.com/96625032/147871733-d99208ee-11da-4d9d-8640-ad494c56afe6.png)
![2022-01-02 (1)](https://user-images.githubusercontent.com/96625032/147871752-86c52d46-94cc-464d-8b43-50ec2efc3f80.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
We ask that you do not run any of the 1.18 builds until we say it is ready. They are highly unstable and not viable for testing.

**Comment by aaronschneider7797** [comment]
Thanks.
