### ISSUE TITLE
[1.12.2] Simple error with huge lilypad texture

### ISSUE THREAD

**Issue by Dasawkem** [TeamTwilight/twilightforest#1430]
### Forge Version

14.23.5.2860

### Twilight Forest Version

3.11.1021

### Steps to Reproduce

Simply opening the latest 1.12.2 version and finding and/or placing a huge lilypad will show the issue.

### What You Expected

Lilypad texture should display properly. (example screenshot shown here with my fix via resourcepack blockstate tweaks)
![2022-01-02_19 28 55](https://user-images.githubusercontent.com/65155806/147893592-48a75c56-23cd-44e9-8743-c4b9ef1cc684.png)

### What Happened Instead

Broken texture, with west side of sprite appearing on the east side, and vice versa.
![2022-01-02_19 46 00](https://user-images.githubusercontent.com/65155806/147893594-c93ead98-856d-4489-898d-f30494ec512b.png)

### Additional Details

This is incredibly easy and minor of a fix, so this is probably a low priority issue, but definitely is a thing that exists regardless of having or lacking optifine. Thankfully this is easily fixed via resource pack and a simple blockstate json for huge_lilypad.

Here is the original blockstate json for the huge lilypad

[huge_lilypad - original json.txt](https://github.com/TeamTwilight/twilightforest/files/7800029/huge_lilypad.-.broken.txt)

Here is my personal fix

[huge_lilypad - fixed json.txt](https://github.com/TeamTwilight/twilightforest/files/7800030/huge_lilypad.-.fixed.txt)

To fix, the json (both of these are txt to upload here, just change the filetype manually to json) is placed within TF's "blockstates" folder, titled "huge_lilypad", for anyone who wants to fix this themselves in the meantime.

Again, this is a very minor issue, so probably low priority for fixing. Just wanted to provide my own personal fix and also bring light to the minor issue.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this seems to have been fixed in later versions of the game. Since we don't support older versions of the mod anymore, I'm gonna close this. You're always free to share your fix with others that may be having the issue though!
