### ISSUE TITLE
1.17.1 won't launch

### ISSUE THREAD

**Issue by robinsoni12** [TeamTwilight/twilightforest#1433]
### Forge Version

37.1.1

### Twilight Forest Version

4.0.875

### Client Log

https://gist.github.com/robinsoni12/1db3fed087c78a819992d81d6afc3122

### Crash Report (if applicable)

https://gist.github.com/robinsoni12/91918bcdae3dbec9f48a56cfb2d6da86

### Steps to Reproduce

1.Launch game

### What You Expected

The game launching

### What Happened Instead

The game crashed

### Additional Details

I don't have optifine installed. I made a modpack and it worked yesterday but today it just crashes

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
> java.lang.UnsupportedClassVersionError: net/darkhax/enchdesc/EnchDescForge has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

61.0 is for Java 17, which only runs with 1.18. Did you grab the right version of enchantment descriptions?

**Comment by robinsoni12** [comment]
I deleted enchantment descriptions and downgraded create and it works now
