### ISSUE TITLE
Making the mod more customizable for modpack devs

### ISSUE THREAD

**Issue by megagnarxd** [TeamTwilight/twilightforest#1434]
### The Suggestion

Allow a config option for monster type to spawn in twilight forest(dont allow it to be hard coded).

### Why Should It Be in the Mod?

Good for modpack devs

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
This is already the case via datapacks. There are other mods to help with spawning rules as well if that becomes an issue.

The only thing hardcoded are structures, which will change in the future
