### ISSUE TITLE
Twilight Forest Encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Acar25** [TeamTwilight/twilightforest#1436]
### Forge Version

36.2.22

### Twilight Forest Version

4.0.546

### Client Log

https://gist.github.com/Acar25/4fda917b51411a4f8c1ca9e1c216eded

### Steps to Reproduce

Step 1. Launch FTB Ultimate Anniversary through Overwolf
Step 2. Crash

### What You Expected

To play Minecraft

### What Happened Instead

Crash of Twilight Forest Mod

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Update TF, this is an error caused by a recent update to Immersive Engineering.
