### ISSUE TITLE
Game Crashed whilst Initializing

### ISSUE THREAD

**Issue by LaMelancholie** [TeamTwilight/twilightforest#1437]
### Forge Version

fabric

### Twilight Forest Version

twilightforest-fabric-1.18.1-4.0.154

### Crash Report (if applicable)

<script src="https://gist.github.com/LaMelancholie/7d563158c06266e8d39080374d3f8ad9.js"></script>

### Steps to Reproduce

1. Put mod into mod folder
2. See if it runs with my other mods
3. Nope it won't even open or try. No incompatible mod notice.

### What You Expected

pls worky

### What Happened Instead

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'twilightforest'!
Exit Code: -1

### Additional Details

Does you mod not work with OptiFine/Fabric ? If not could it do so in the future? Thanks!

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
1. This is the wrong repository. This is for the Forge version.
2. Do not report bugs for the 1.18.1 versions as they are not ready for use.
