### ISSUE TITLE
Peacock Fan increases speed while using Elytra

### ISSUE THREAD

**Issue by Cryomancer765** [TeamTwilight/twilightforest#1439]
### Forge Version

36.2.20

### Twilight Forest Version

4.0.870

### Steps to Reproduce

1. Equip Elytra
2. Use fan to jump
3. Begin gliding
4. Wait for cooldown and activate fan to accelerate, repeat until going ridiculously fast

### What You Expected

Expected to reach a maximum speed. Assumed the fan would only accelerate if below a certain threshold.

### What Happened Instead

Reached insane speeds, started at about X:1000 Z:1000, within 30 seconds I reached X:-10000 Z:5000

![2022-01-19_17 36 39](https://user-images.githubusercontent.com/12061270/150235827-8580747b-fae7-453c-bdeb-11f792a1f9e3.png)
0
Image from reproduction of the bug.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This was patched in 1.17. Since 1.16 won't be getting any more updates I'll consider this fixed and close it.
