### ISSUE TITLE
Twilight Portal incompatible with Dark Utilities Portal Charm

### ISSUE THREAD

**Issue by Darkhax** [TeamTwilight/twilightforest#1441]
### Forge Version

36.2.23

### Twilight Forest Version

4.0.870

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

1. Equip the portal charm from Dark Utilities. The item can go in the curio slot, offhand, or the inventory.
2. Build a standard Twilight Forest portal.
3. Jump in the portal
4. Nothing happens.

### What You Expected

The player should be able to travel through the portal like normal. 

### What Happened Instead

The player was completely prevented from traveling through the portal.

### Additional Details

The Portal Charm is an item from Dark Utilities that allows players to instantly travel through portals like the Nether Portal, as if they were in creative mode. When trying to enter the Twilight Forest portal they will be prevented from entering. This is because the [portal charm sets the portal timer to 100](https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/1.16.5/src/main/java/net/darkhax/darkutils/features/charms/CharmEffects.java#L47-L54) which is the amount of ticks for a vanilla portal. The twilight forest portal [also uses this timer](https://github.com/TeamTwilight/twilightforest/blob/33b5529d64cdb017c51aa10c6932d6a646eced94/src/main/java/twilightforest/block/TFPortalBlock.java#L265-L267) but gives it an inverted meaning. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
the code shown had no bad side effects when removing it, so I assume its useless. I left it there, commented out, just in case it does actually break something

**Comment by Darkhax** [comment]
Thanks for looking into this issue.
