### ISSUE TITLE
Mod has missing version data.

### ISSUE THREAD

**Issue by Darkhax** [TeamTwilight/twilightforest#1442]
### Forge Version

36.2.23

### Twilight Forest Version

4.0.870

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

1. Open the compiled jar and look at the mods.toml file

alternative steps
1. Launch the game
2. Go to the modlist
3. Version is reported as NONE

### What You Expected

The version should probably be 4.0.870

### What Happened Instead

The version is reported as NONE

### Additional Details

The mods.toml file in the JAR is using Forge's magic version string `"${file.jarVersion}"` which redirects the version query to the JAR manifest. The manifest file in this JAR has no properties.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This was fixed in later versions. Not likely that 1.16 will get another upload with the fix.
