### ISSUE TITLE
armor crashing on other players or when i press f5  

### ISSUE THREAD

**Issue by mimecraftxdee** [TeamTwilight/twilightforest#1446]
### Forge Version

1.17.1

### Twilight Forest Version

4.0.849

### Steps to Reproduce

1. wear knight metal helmet
2. press f5
3. crash

### What You Expected

would put me in third person

### What Happened Instead

crashed

### Additional Details

also crashes other players on aternos

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
you need to send the crash report, otherwise we can't help. Why didn't you read the template?
