### ISSUE TITLE
Darkwood Sapling Crash when Grown?

### ISSUE THREAD

**Issue by Ashley123477** [TeamTwilight/twilightforest#1447]
### Forge Version

36.2.28

### Twilight Forest Version

twilightforest-1.16.5-4.0.870-universal

### Crash Report (if applicable)

https://gist.github.com/Ashley123477/a0cfb6ac5ca07d0f009963c70cb7becf

### Steps to Reproduce

Plant darkwood sapling
grow darkwood sapling using bonemeal
crash

### What You Expected

Tree to grow as usual

### What Happened Instead

Crashed

### Additional Details

As far as my crash log knowledge goes i believe this could be caused by magnesium?

Edit: Confirmed this is a magnesium issue with twilight as removing magnesium renders it fine. also put a issue on the magnesium issue page https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/181

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Closing as this is a fault of another mod.
