### ISSUE TITLE
Can't craft raw ironwood material

### ISSUE THREAD

**Issue by Plumbog** [TeamTwilight/twilightforest#1448]
### Forge Version

1.17.1

### Twilight Forest Version

4.0.875

### Steps to Reproduce

![Bug](https://user-images.githubusercontent.com/100095555/154864341-0f51f4c0-99cf-4486-b9f2-937a78ef9afa.PNG)

### What You Expected

In previous versions, I have been able to craft Ironwood material as usual.

### What Happened Instead

When the ingredients are put together on the crating table it doesn't do anything.

### Additional Details

I have tried downloading and redownloading the mod and all versions made on Minecraft 1.17.1 and none of them work.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
The 1.17 recipe was switched to use raw iron instead of normal iron, try that instead.

**Comment by Plumbog** [comment]
> The 1.17 recipe was switched to use raw iron instead of normal iron, try that instead.

Yup this is the answer, I have no idea how I was supposed to know that but thank you very much.

**Comment by GizmoTheMoonPig** [comment]
I thought I stated it in the changelog but if I didn't I apologize. Enjoy the mod :)
