### ISSUE TITLE
Fungal Aranea Boss And Dungeon(Not In Love With The Name)

### ISSUE THREAD

**Issue by ShadySheep228** [TeamTwilight/twilightforest#1449]
### The Suggestion

Boss and dungeon idea: So Twilight Forest is an amazing mod, and I'm so happy to know that it will continue to recieve updates after the final boss is added! But one thing about the mod that isn't perfect is how every boss is needed for progression. I think there is room for some optional bosses that you can fight. Now, I used to always wonder the purpose of the Mushroom Tower structure, something that seemed like a giant mushroom village. I recently found out that the structure was removed. I think it had potential. My idea is to bring back the structure and add many more bridges between mushrooms. Then, add an underground dungeon similar to that of the Minoshroom Labrynth. To enter this dungeon, there is a trophy pedestal similar to the Goblin Dungeon one, to keep new players from wandering in. It looks like the dungeon has been overgrown and filled with mushrooms. There are many unique mobs in the dungeon, including variations of existing mobs that have been overgrown and filled with fungi like the dungeon itself. I imagine a Carminite Golem that is broken down and overgrown as a possible mob. Exploring the dungeon will grant new loot and eventually you will find a main room. The main room contains an egg on a large pedestal. Picking up the egg plays a loud sound and text appears reading "You Hear A Loud Rumble From The Surface."
Upon returning to the surface, you can go back up to the Mushroom Tower structure and find that at the top is a Boss Spawner. Upon approaching the spawner a massive mushroom spider will spawn. The Fungal Aranea has a few attacks, including a massive leap towards the player or onto a nearby bridge and an attack that shoots a web at the player, placing cobwebs on them if it hits. The boss will climb around bridges faster than the player, and it can break most basic blocks, meaning the player has to try to jump between bridges to avoid it. To attack the boss, hit its large abdomen with ranged or melee attacks. The boss will also shoot out many small mushroom spiders as an attack. This boss is meant to be fought at any time after the lich. The boss drops a chest of cobwebs, steel leaves, a few diamonds, and a new item called the Web Slinger. This item allows players to shoot out a stream of webs like the boss is able to do to slow the player in cobwebs. It doesn't have durabilty but requires cobwebs for ammo.

### Why Should It Be in the Mod?

Twilight Forest needs some optional bosses and I think this one is a good idea. Maybe if it seems like too much remove the dungeon part of the boss and just have it spawn on top of the Mushroom Tower. This idea leaves many possibilites and even if it is not added I would love to see some optional bosses other than the Questing Ram.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
The Structure removal isn't permanent.

We aren't going to do our own thing with it either unless Benimatic didn't have any plan for it to begin with. We plan to consult him about it when the time comes.

**Comment by dudedudeDUPPPER** [comment]
I think fungal resembles fungus, but it would be nice if the boss were a poisonous mushroom, inside a mossy cave, the boss will release balls of poisonous moss, in addition to releasing mini mushroom that when the player approaches it explodes like a crepper

**Comment by Killer-Demon** [comment]
Basically what @Tamaized already said. While it is really cool you thought all of this up, the structure removal isn't permanent and we as a team will be looking into creating something that fits the mod and its themes when the time comes.
