### ISSUE TITLE
Scepter of Twilight losing enchantment on recharging (MC 1.12.2)

### ISSUE THREAD

**Issue by Gideon9212** [TeamTwilight/twilightforest#1451]
### Forge Version

14.23.6.2860

### Twilight Forest Version

3.11.1021

### Client Log

None

### Crash Report (if applicable)

None

### Steps to Reproduce

1. Put an enchantment on the scepter of twilight. Enchant example unbreaking 3.
2. Use the scepter until you can recharge it. Even at 98 or 97.
3. Charge scepter. Now the enchantment is missing and would need to be enchanted again.

### What You Expected

For the scepter to keep the enchantment

### What Happened Instead

It didn't keep the enchantment

### Additional Details

Nothing on config or anything else confirms that this is intended or not.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
They were never intended to have enchantments.
