### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by SnowMan5050** [TeamTwilight/twilightforest#1452]
### The Suggestion

My idea is that the final boss would be a mirror that will send you all the boss you have fight with, but the bosses are more difficulty. and and how is a mirror if you, hit the mirror the mirror reflect the damage and if you hava a effect potion the effect that effect will give it to the boss. and the mirror can shoot to you when you are fight in and when you defeat all the bosses the mirror its gona to change he aspect with your skin and this can make copies of he.

### Why Should It Be in the Mod?

I think it could be added because it is a somewhat original idea and it would add a very fun fight and difficulty for the player. bye, love you : D

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
Final Plateau content is already planned out

**Comment by dudedudeDUPPPER** [comment]
The mod have a Hydra, miniotaurs, a Naga and a Yety. Why not a White dragon for final boss, shots two fireballs, a dragon breath, like a flying hydra, but he summon mini versions of the bosses you fought previously, very weak and has no strategies to take damage. And fix the amount of Yetis in the Yeti Alpha Cave, Please.
