### ISSUE TITLE
Naga's body is invisible (only head)

### ISSUE THREAD

**Issue by I3estOFF** [TeamTwilight/twilightforest#1454]
### Forge Version

36.2.21

### Twilight Forest Version

1.16.5-4.0.870-universal.

### Client Log

https://gist.github.com/I3estOFF/21911422736c21dd8dcdd7d6e3908582.js

### Steps to Reproduce

1. Enter Twilight Forest
2. Go to Naga

### What You Expected

Naga should be a long snake

### What Happened Instead

There is only a walking Naga's head not a snake

### Additional Details

![image](https://user-images.githubusercontent.com/63112899/158595161-3bee24d0-2288-4b40-ace1-5f87755db41e.png)

Only this part of Naga is visible

### Please Read and Confirm The Following

- [ ] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Your log file indicates you have Optifine installed.
Please read the issue template more carefully when you make a report next time. We will not support any issues if Optifine is installed due to bugs it introduces.
