### ISSUE TITLE
Final Boss Not Done

### ISSUE THREAD

**Issue by zaxlofful** [TeamTwilight/twilightforest#1457]
### Forge Version

latest

### Twilight Forest Version

latest

### Client Log

latest

### Crash Report (if applicable)

latest

### Steps to Reproduce

Finish the final boss

### What You Expected

latest

### What Happened Instead

latest

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Correct
