### ISSUE TITLE
Not working with optifine

### ISSUE THREAD

**Issue by AwesomeAddy09** [TeamTwilight/twilightforest#1458]
### Forge Version

37.0.103

### Twilight Forest Version

4.0.875

### Client Log

[22Mar2022 19:36:20.765] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Awesome_Adam2, --version, 1.17.1-forge-37.0.103, --gameDir, C:\Users\miadi\AppData\Roaming\.minecraft, --assetsDir, C:\Users\miadi\AppData\Roaming\.minecraft\assets, --assetIndex, 1.17, --uuid, 52036a57493148fd8fe50caf865e3b9f, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 37.0.103, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]

### Steps to Reproduce

1. I downloaded Forge version 37.0.103, OptiFine version HD U H1, and Twilight Forest Version 4.0.875
2. I loaded forge into minecraft
3. I loaded minecraft and it worked fine
4. I went into the mods folder through the mods button and dragged OptiFine into it
5. I loaded minecraft again with no crashes
6. I went into the mods folder again and dragged twilight forest into it
7. I restarted minecraft again and this time it kept crashing.

### What You Expected

Minecraft to launch fine and OptiFine to work with the mod.

### What Happened Instead

When I launched minecraft with the launcher it crashed and I got a message saying "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. This Issue may have been caused by an invalid java runtime configuration. Check any custom configuration settings. Exit code: 1"

### Additional Details

I am using java addition. I am using java version 16.0.1. I tried all versions of 1.17.1 Twilight Forest but none of them worked. The Error happened when I was using an older version of java, but still happened when I updated it to the latest version. I checked off "I have confirmed this bug can be replicated without the use of OptiFine." even though it doesn't so I could post this, but please don't delete this I need help and this form took a long time to fill in.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
we dont support optifine issues

**Comment by AwesomeAddy09** [comment]
> we dont support optifine issues

thanks for the help

**Comment by Drullkus** [comment]
Points for honesty lol

**Comment by AwesomeAddy09** [comment]
@GizmoTheMoonPig  It's fine if I don't get personal help, but can you please try to get the bug fixed?
