### ISSUE TITLE
Game Crashes on Startup "No model for layer twilightforest:hydra_head#main"

### ISSUE THREAD

**Issue by TheTanzer22** [TeamTwilight/twilightforest#1461]
### Forge Version

37.1.1

### Twilight Forest Version

1.17.1-4.0.875

### Client Log

<script src="https://gist.github.com/TheTanzer22/31a01a82f7ec0d56d27704185df4bec1.js"></script>

### Crash Report (if applicable)

<script src="https://gist.github.com/TheTanzer22/5c171776327867887b66f0c42d1b447c.js"></script>

### Steps to Reproduce

I opened the game, and before the game fully loaded it crashed

### What You Expected

The game was supposed to load properly

### What Happened Instead

The game crashed

### Additional Details

The game gives me an error: game crashed of
The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: No model for layer twilightforest:hydra_head#main
Exit Code: -1

I do not have Optifine installed (nor do I know how to)

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TheTanzer22** [comment]
I found that several different mods being added seem to cause the crash. Enchantment Descriptions caused it, but it happened with a different mod earlier. The mods that add the issue back are completely unrelated to each other, but the result is always the same: The game crashes and blames Twilight Forest and the head of a Hydra (for whatever reason)

**Comment by ijwrighty1** [comment]
I am just starting out with modding and get the exact same issue. Running 1.1.82-forge-40.0.36 and  twilightforest-1.17.1-4.0.875-universal.jar.

**Comment by ijwrighty1** [comment]
Is there a workaround to get this working at all?

**Comment by Andromander** [comment]
Please provide a crash log (and the latest.log) so we can get a better look. Based on the information provided in this issue, it seems like a mod error earlier in the loading caused a cascade of errors, resulting what seems like our mod crashing, likely isn't.

**Comment by ijwrighty1** [comment]
Thanks @Andromander . Im new to Minecraft modding. Can you advise how I get the logs please? I am technical so not a complete noob!

**Comment by Andromander** [comment]
From the Minecraft help article for getting to the game files on the default launcher:
1. Open the Minecraft launcher and log in. 
2. Select Launch options, and then select the launcher configuration you are running (the default is set to Latest release).  
3. Locate the Game directory selection and select the little green arrow to the right of it. A new window will open containing your Minecraft folder.

Alternatively, if you use Windows, you can search or put into Run `%appdata%` and find a folder called `.minecraft`
If you use a different launcher such as Curseforge or MultiMC, the instructions might be different.

There, you should find a folder called `logs` for the full log file, or `crash-reports` for crash reports. When getting the crash report, the date and time of the crash is the name of the file. When getting the log file, the `latest.log` file will have the details of the last session you played on. If that session is when you crashed, it'll have all the info we need.
To paste the contents, open those files in a text document like Wordpad and paste them into [a Gist](https://gist.github.com/). You can also just drag the files into here, just saves on downloading them.

**Comment by ijwrighty1** [comment]
[latest.log](https://github.com/TeamTwilight/twilightforest/files/8495601/latest.log)
[crash-2022-04-15_12.12.18-client.txt](https://github.com/TeamTwilight/twilightforest/files/8495602/crash-2022-04-15_12.12.18-client.txt)

**Comment by Andromander** [comment]
Ah, your problem is that you're trying to run a version of Twilight Forest that can only run on 1.17.1, but you're on 1.18.2. The version supported by the mod has to match the version of the game.

**Comment by ijwrighty1** [comment]
Fantasic. That worked a treat. Thank you for your help.

**Comment by Tamaized** [comment]
Original issue is caused by another mod:
`Caused by: java.lang.UnsupportedClassVersionError: net/darkhax/enchdesc/EnchDescForge has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0`
