### ISSUE TITLE
[Suggestion] Make the"Carminite Reactor" be able to create more nether blocks than netherack 

### ISSUE THREAD

**Issue by Smokedeuch** [TeamTwilight/twilightforest#1467]
### The Suggestion

Maybe this will make more sense when Carminite becomes renewable but a reason to use the reactor core after the initial gotcha moment  may be for a possible way to get Ancient Debris,Quartz and Nylium in the Twilight forest since its not currently possible in a Pure play through.

Could also possibly be inbeded in the tower itself since that seems to be the DeepLore tm 

### Why Should It Be in the Mod?

A way to get Ancient Debris,Quartz,and Nylium in a pure Twilight Forest play through. 

Ancient debris=Netherite stuff

Quartz=Various Redstone components

Nylium=The nether wood 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
ancient debris will never happen, but I already added quartz and nether gold ore in 1.17. I dont feel nylium would make a lot of sense tbh

**Comment by Tamaized** [comment]
I'm not a fan of nylium either

**Comment by Killer-Demon** [comment]
I'm against making everything from the Nether available in the forest. If people really want that the can change the loot tables, but at the end of the day the dimension isn't supposed to be the end-all be-all stop for everything vanilla. It takes away from the base game and turns the mod into metagaming.

Therefore, I am again adding Ancient Debris and Nylium in any capacity at this time.

**Comment by Drullkus** [comment]
We use a tag list `twilightforest:carminite_reactor_ores` to determine the ore blocks placed when a Nether Reactor explodes. You can use a datapack to modify or set the blocks in this tag list
