### ISSUE TITLE
The twilight forest structures spawned in other dimension.

### ISSUE THREAD

**Issue by Parallel011** [TeamTwilight/twilightforest#1468]
### Forge Version

40.1.0

### Twilight Forest Version

4.1.916

### Steps to Reproduce

1.create a new world

### What You Expected

The twilight forest structures shouldn't spawned in overworld, not mention in the Nether or the End.

### What Happened Instead

The twilight forest structures spawned in other dimension.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
please dont make reports for dev builds. They arent ready to be tested yet. Ive already fixed this anyway
