### ISSUE TITLE
Knightly Armor doesn't show the right way on armor stands 1.12.1

### ISSUE THREAD

**Issue by ItzMojang** [TeamTwilight/twilightforest#147]
Forge version: 14.22.0.2462 (1.12.1)
Twilight Forest version: (this is the build number) twilightforest-1.12.1-2.4.0.26-universal
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Keep taking it on and off it will still happen

What I expected to happen: To show how it looks like on a  player
[![Screenshot from Gyazo](https://gyazo.com/e48258725516240a975f959c2c5a3a4d/raw)](https://gyazo.com/e48258725516240a975f959c2c5a3a4d)
What happened instead: The armor wants to become magic armor 
[![Screenshot from Gyazo](https://gyazo.com/4decb00f53b1d46543dd7fc97a447967/raw)](https://gyazo.com/4decb00f53b1d46543dd7fc97a447967)

**Comment by williewillus** [comment]
ah, the classical "armor stands are dumb" helmet-facing-south and armor-breathing bugs
fix coming
