### ISSUE TITLE
Crash Pls Help

### ISSUE THREAD

**Issue by Kokos321** [TeamTwilight/twilightforest#1470]
### Forge Version

37.1.1

### Twilight Forest Version

4.0.875

### Client Log

https://gist.github.com/Kokos321/1aa8c92167d1066ae5b8be2ffd559bf5

### Crash Report (if applicable)

https://gist.github.com/Kokos321/88adf71c7cb2a137c6c8189b95027af8

### Steps to Reproduce

1. I make mod pack
2. I run game with my mod pack
3. I get crush and open console 

### What You Expected

It should fire up and work

### What Happened Instead

Doesnt work

### Additional Details

![image](https://user-images.githubusercontent.com/78508698/165586248-6fe4974c-29e7-4bb2-8494-5ce087bea7d2.png)
![image](https://user-images.githubusercontent.com/78508698/165586290-1881ebaf-90dc-4e49-9c90-204064c141bd.png)
![image](https://user-images.githubusercontent.com/78508698/165586931-384517a5-702e-4ee2-a5c7-6c1a92f90b8a.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] I have confirmed this is not from a development build and is from a build uploaded to Curseforge.

**Comment by Tamaized** [comment]
We don't offer support for TLauncher.
