### ISSUE TITLE
[Suggestion] Config option to choose between structures before and after being spruced-up

### ISSUE THREAD

**Issue by DoctorCJack** [TeamTwilight/twilightforest#1474]
### The Suggestion

For future spruced-up structures and the already spruced-up Naga courtyard, I propose a config option for each boss structure (currently only the Naga Courtyard) to be able to toggle between the 2 versions of the structure when generating a world.

### Why Should It Be in the Mod?

I personally really enjoy the current boss structures (and both Naga Courtyards), so I will likely miss them in future updates; I expect other players would feel the same. This would be a nice feature to have for long-time players who would like to feel nostalgia without needing to return to older versions of the mod and of Minecraft.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
As nice as this would be it defeats the purpose of maintainability.

The entire reason for the reworks is to move away from in-code structures that break every Minecraft version.

**Comment by DoctorCJack** [comment]
Ah, that makes sense. Thanks for explaining.
