### ISSUE TITLE
Knight Phantom  doesn't spawn the right way 1.12.1

### ISSUE THREAD

**Issue by ItzMojang** [TeamTwilight/twilightforest#148]
Forge version: 14.22.0.2462 (1.12.1)
Twilight Forest version: (this is the build number) twilightforest-1.12.1-2.4.0.26-universal
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Keep trying to spawn the mob in.

What I expected to happen: When you try spawning the mob in with the egg it shoudl stay their
What happened instead: When i spawned the mob it went into the ground as a ghost and went very very fast away from you and then goes away

**Comment by Tamaized** [comment]
~tbh this one shouldnt even have a spawn egg due to how the AI works~

Actually, the entire AI for this one is really outdated. I'll just modernize it and fix this with it.
