### ISSUE TITLE
[1.12.2]Can't load any boss

### ISSUE THREAD

**Issue by nanhuajiaren** [TeamTwilight/twilightforest#1485]
### Forge Version

14.23.5

### Twilight Forest Version

3.11.1021

### Client Log

https://gist.github.com/nanhuajiaren/6aca8a68b9e53d76b4dbc5599026f6f7

### Steps to Reproduce

Load it and try to defeat any boss, Naga for instance

### What You Expected

The boss spawn normally

### What Happened Instead

The game didn't crash, but isn't normal either. No boss spawned in supposed positions. No other mods loaded. I tested this for multiple times but the results are the same.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
~~Possibly some kind of mod conflict?~~ Didn't realize you stated there aren't any mods.
1.12 is quite old and we've never seen this issue before.

I've no idea what could be causing this.

**Comment by nanhuajiaren** [comment]
I tried again today and it's ok :D
Maybe I should have accidentally created my test level in wrong difficulty level without realizing it
