### ISSUE TITLE
[1.18.2] Naga stun lasts for far too long

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1488]
### Forge Version

40.1.19

### Twilight Forest Version

1.18.2-4.1.1010

### Steps to Reproduce

1. Stun a naga with a shield

### What You Expected

Stun to last for long enough to get two, maybe three hits before it wakes up (consistent with previous versions of the mod)

### What Happened Instead

Stun lasted for longer than ten seconds, allowing me to drain a third of the naga's health in one stun with a diamond sword. This is a much longer stun than I have ever observed in previous versions of TF

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
can you test what the time used to be in 1.12 and let me know? I'll fix it to be that again

**Comment by EvergreenSystems** [comment]
Let me brush the dust off of my 1.12.2 directory, one moment

**Comment by EvergreenSystems** [comment]
In 1.12.2 it is long enough for about two sword swings, so I would estimate about four seconds or so

**Comment by GizmoTheMoonPig** [comment]
according to the code, the naga stun timer should last anywhere from 3 to 5 seconds. This bit hasn't changed at all since it was first introduced, so I have no idea what's going on here. From testing it myself, it seems the same as I remember it being in older versions

**Comment by Tamaized** [comment]
Potentially low tps in that moment?

**Comment by EvergreenSystems** [comment]
/forge tps returned a 20, singleplayer world at ~40 fps. I wasn't experiencing any noticeable lag, it's possible it's just my perception being odd but the fact that I drained a third of its health with an unenchanted sword in one stun is... odd, at least to me

**Comment by Maxie333** [comment]
i encountered it at 1.18.2 4.1.1052 and after multiple tests the stun time was always either around 7 seconds or around 9 seconds

**Comment by GizmoTheMoonPig** [comment]
I still can't reproduce this myself, and even if the timer is longer for some people, the higher player knockback in 1.19 should accommodate for it a bit. I don't really see this as an issue anyway tbh, the boss isnt supposed to be hard to kill
