### ISSUE TITLE
Pinch beetle can hold a player helplessly inside a block

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest#1493]
### The Suggestion

Pinch beetles can grab a player hold them inside a block (without taking suffocation damage though) if the beetle is in a 1-block tall space. This seems kind of broken as the player can not attack the beetle and breaking the block takes too long without good gear.

Ideally the beetle should drop the player if it puts the player inside a block, or if the beetle is in a 1-block tall space
Or perhaps the beetle and player are both forced out if the player ends up inside a block

### Why Should It Be in the Mod?

Being held inside a block unable to attack the beetle feels unfair.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
turns out a fix for this already existed, it just broke during one of the ports (probably 1.12 -> 1.16). Ive reapplied he fix, so suffocation shouldnt happen anymore. :)
