### ISSUE TITLE
Shaders UV map is broken

### ISSUE THREAD

**Issue by wontactcivilized** [TeamTwilight/twilightforest#1494]
### Forge Version

Forge 40.1.19

### Twilight Forest Version

twilightforest-1.18.2-4.1.995

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/106423970/170825432-95caaf04-3293-4df6-bf7f-704047b727c3.png)

### What You Expected

idk what to put here

### What Happened Instead

broken 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
I'm...going to assume by "shader" you mean "Shader Bag" for Immersive Engineering compat and not "shaders" as in the term often associated with Optifine?

**Comment by wontactcivilized** [comment]
Shaders bags yeah
