### ISSUE TITLE
Incompatibility issue with Sophisticated Storage

### ISSUE THREAD

**Issue by Swedz** [TeamTwilight/twilightforest#1498]
### Forge Version

40.1.20

### Twilight Forest Version

4.1.1051

### Client Log

https://gist.github.com/Swedz/f2185d2ac80349dd4fe63f687973f713

### Crash Report (if applicable)

https://gist.github.com/Swedz/46ec46d880a1b0e3e4455d6df4ab3f36

### Steps to Reproduce

1. Install Sophisticated Storage
2. Place a dyed barrel
3. Break the barrel

### What You Expected

The barrel to break

### What Happened Instead

The game crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
We have checks to prevent this sort of crash, though they may be new checks only in newer versions but it does mean this shouldn't happen anymore which means this can be closed.
