### ISSUE TITLE
[1.18.2] Server and Client crash for Twilight and Immersive Engineering

### ISSUE THREAD

**Issue by Mitchell5200** [TeamTwilight/twilightforest#1499]
### Forge Version

40.1.25

### Twilight Forest Version

1.18.2-4.1.1052-universal

### Client Log

https://gist.github.com/Mitchell5200/3441795004b88b1fc85ff30fc9f829ee

### Crash Report (if applicable)

https://gist.github.com/Mitchell5200/f0096bfd7a8c340101b265bf37120aa1

### Steps to Reproduce

1. Take working 1.18.2 modpack (atm7 0.4.5 in this case)
2. Slam twilight forest in hoping it works
3. startup client or server
4. ???
5. no profit, just crash

### What You Expected

I sorta expected twilight forest to not cause a startup crash for immersive engineering, i did expect bugs though

### What Happened Instead

Startup crash

### Additional Details

tested with both Immersive Engineering -1.18.2-8.0.0-146 and -1.18.2-8.0.1-147 on forge 40.1.25

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
IE has this fixed already just not released yet, it'll be in their next update.

**Comment by Mitchell5200** [comment]
understood, thanks for the reply, i'll pass it on to the pack team
