### ISSUE TITLE
Yeti's spawning at the top of the Yeti Cave

### ISSUE THREAD

**Issue by Maxie333** [TeamTwilight/twilightforest#1500]
### Forge Version

1.18.2 - 40.1.30

### Twilight Forest Version

1.18.2 - 4.1.1052

### Steps to Reproduce

Find a Yeti Cave

### What You Expected

Little yeti's spawning inside of the Yeti Cave

### What Happened Instead

Little yeti's spawning on the top of the Yeti Cave

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TimTheHedge** [comment]
![2022-06-01_16 12 06](https://user-images.githubusercontent.com/101013126/171416817-9ebf867c-2b15-4c9d-a7fc-e7420d4337d9.png)
)
