### ISSUE TITLE
Skyblock visual bug with any shaders

### ISSUE THREAD

**Issue by BeardedHamster** [TeamTwilight/twilightforest#1501]
### Forge Version

40.1.0

### Twilight Forest Version

4.1.1052

### Crash Report (if applicable)

Dividing the sky into 2 fragments

### Steps to Reproduce

1. Install TF and Oculus mod for shaders
2. Turn on shaders 
3. Look

### What You Expected

Normal sky as in the overworld

### What Happened Instead

Dividing the sky into 2 fragments

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This is not something we can fix. If need be, a datapack can remove our skybox and replace it with the overworlds.

**Comment by BeardedHamster** [comment]
Where can I find this datapack?
