### ISSUE TITLE
[1.18.2]Magic map does not display correctly in the player's hand

### ISSUE THREAD

**Issue by BradClc** [TeamTwilight/twilightforest#1505]
### Forge Version

40.1.19

### Twilight Forest Version

twilightforest-1.18.2-4.1.1052-universal

### Steps to Reproduce

Right click to open magic map but it doesn't show anything

### What You Expected

The magic map should display correctly in the player's hand

### What Happened Instead

Magic maps can only be correctly displayed in item frame

### Additional Details

![2022-06-03_00 35 39](https://user-images.githubusercontent.com/88281511/171684701-cc54695c-e96c-46cc-b336-89c715c7e5da.png)
![2022-06-03_00 50 16](https://user-images.githubusercontent.com/88281511/171684807-bad22702-4c24-4a6e-9af4-16d795ef9937.png)
![2022-06-03_00 50 29](https://user-images.githubusercontent.com/88281511/171684850-dfe7b630-5739-4e24-8cc2-3150acb04532.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This is usually caused by a mod conflict. Does it work fine with TF alone?

**Comment by BradClc** [comment]
There should be a conflict, the map display is fine when I install TF alone.
I'll probably take my time trying to figure out which mod is causing the conflict, and I'll let you know if I do find it. Anyway, thanks for such a quick reply.

**Comment by BradClc** [comment]
Although I still can't figure out which mod is causing the conflict. Fortunately, this problem was automatically resolved after I upgraded the other mods to the latest version.
