### ISSUE TITLE
Crash entering Portal Latest Beta, Tested with Modpack

### ISSUE THREAD

**Issue by TheWitherlord** [TeamTwilight/twilightforest#1506]
### Forge Version

1.18.2 Forge-40.1.31

### Twilight Forest Version

Twilight Forest - MC 1.18.2 - 4.1.1052

### Client Log

https://gist.github.com/TheWitherlord/57d4fb753d489579433157e83844e0da

### Crash Report (if applicable)

https://gist.github.com/TheWitherlord/ad1dd7aa80f6f94adb6999c38d4349d0

### Steps to Reproduce

1. Downloaded Beta
2. Ran the mod with my set mod pack for testing.
3. Went through the Twilight Portal
4. It gives a server crash on singleplayer

### What You Expected

The game to load the dimension.

### What Happened Instead

It crashes and never loads it sends me back to the server list.

### Additional Details

This is tested with an unreleased mod pack update to see if the mod works with it yet.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Most likely another mod adding features to our biomes wrongly.

**Comment by GizmoTheMoonPig** [comment]
if this is still an issue, can you download cyanide (https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) and post a crash report with it installed? This mod helps feature order cycles become more readable, so we can help with this more. If its no longer happening, please close the issue, thank you!
