### ISSUE TITLE
[fabric] mod conflict (Create + Twilight Forest)

### ISSUE THREAD

**Issue by AmonRay** [TeamTwilight/twilightforest#1511]
### Forge Version

fabric 0.14.6

### Twilight Forest Version

4.1.232

### Client Log

https://gist.github.com/AmonRay/bde55f52c585f2af908e24e4a9504a0f

### Crash Report (if applicable)

https://gist.github.com/AmonRay/f4382edefd7c9bad329299077e538900

### Steps to Reproduce

1. install create mod
2. install twillight forest
3. run mc

### What You Expected

no crashes

### What Happened Instead

crash

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Wrong repo plus duplicate

**Comment by GizmoTheMoonPig** [comment]
guys fabric has their own repo. Please stop reporting this stuff here, its for forge

**Comment by AmonRay** [comment]
got it, sorry, CurseForge link brings me here
