### ISSUE TITLE
Skin Customization Setting not working

### ISSUE THREAD

**Issue by TheGamingFireman** [TeamTwilight/twilightforest#1515]
### Forge Version

40.1.20

### Twilight Forest Version

4.1.1056

### Steps to Reproduce

1. Updated all mods in mod pack
2. Removed the newest mods one by one once the problem occurred
3. stepped pack back to working version then added twilight back in

### What You Expected

Went to remove "hat" layer from skin

### What Happened Instead

cant change layers of my skin from game settings since adding this mod to my pack. 

### Additional Details

Mod pack is Mek & Cheese, version 2.0 added this mod (and others but tests confirm this mod is the cause)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
my bad, i'll push a fix momentarily
