### ISSUE TITLE
[Suggestion] Wearable Trophies

### ISSUE THREAD

**Issue by sylenthuntress** [TeamTwilight/twilightforest#1516]
### The Suggestion

Boss trophies should be wearable, like mob skulls, and boss masks in Terraria.

### Why Should It Be in the Mod?

Purely cosmetic reasons, it's very low-priority but it would be a fun addition for messing around with or without friends.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
you can already do this :)
