### ISSUE TITLE
Crash with Terrablender (for Biomes O' Plenty)

### ISSUE THREAD

**Issue by Sovaster** [TeamTwilight/twilightforest#1517]
### Forge Version

40.1.35 (not important. crash on any version)

### Twilight Forest Version

4.1.1052

### Client Log

https://gist.github.com/Sovaster/f4ca11022f13cd9dd2022f947b0b5d28

### Steps to Reproduce

1) Download minecraft 1.18.2
2) Install Forge 40.1.35
3) Install Biomes O' Plenty 16.0.0.114
4) Install Terrablender 1.1.0.102 for Biomes O' Plenty 
5) Install Twilight Forest 4.1.1052
6) Launch the game

![изображение_2022-06-07_174251076](https://user-images.githubusercontent.com/96499377/172409293-58c16f3b-96b1-413d-8586-7c095c8719a6.png)

![изображение_2022-06-07_174311931](https://user-images.githubusercontent.com/96499377/172409371-29049d96-7441-4dfe-9b48-659353ae613a.png)

![изображение_2022-06-07_174334142](https://user-images.githubusercontent.com/96499377/172409448-729480f3-eef6-4982-9abc-ab28209b421d.png)

![изображение_2022-06-07_174348992](https://user-images.githubusercontent.com/96499377/172409499-773bf0ca-f00c-494e-9819-4c293a5f8c1e.png)

![image](https://user-images.githubusercontent.com/96499377/172409656-78422345-593b-4174-9117-52d5c04a3bf1.png)

FILE WITH CRASH:
[Crash.txt](https://github.com/TeamTwilight/twilightforest/files/8854273/Crash.txt)

### What You Expected

Twilight forest conflicts with Terrablender.
Fix it please
I really love your mod

### What Happened Instead

minecraft crashed :(((

### Additional Details

Any version of Forge or Terrablender  or Biomes O' Plenty leads to error

I have OptiFine HD_U_H7  (without optifine, minecraft crash)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
TLauncher is not supported.
