### ISSUE TITLE
[1.18.2]Cave Troll causing server crashes

### ISSUE THREAD

**Issue by Nothingness-Void** [TeamTwilight/twilightforest#1519]
### Forge Version

40.1.31

### Twilight Forest Version

4.1.1052

### Client Log

Server crash

### Crash Report (if applicable)

https://paste.fastmirror.net/?a2855b5ee214f485#4cwaKSqvisu6E8saMmfAQvujekkTbPjRgw8WZRJGhtGJ

### Steps to Reproduce

Step1.Players hanging out in the cave
Step2.Cave Troll has been spawn
Step3.Players Fight with troll
Step4.Server crash

### What You Expected

Everything goes on normally,server don't crash =.=

### What Happened Instead

Server cras

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Might I suggest trying to reproduce this without mods such as Tough As Nails? Some mods that modify entity behaviour could cause crashes like this.

**Comment by Nothingness-Void** [comment]
Thank you for your reply
I followed your method to remove Tough As Nails
But the server crashed again when the player who caused the crash joined the server
Here's the latest crash report:https://paste.fastmirror.net/?d593eca18002d1df#Hhe4brbdV12cT3M52CJsJwbXnfLrA6i82MZhiRnLBL1Z

**Comment by Tamaized** [comment]
We're ending 1.18.2 support so i'm closing this however the logs expired so I cant actually see what happened. (Yes i'm only just now seeing this :stuck_out_tongue:)
