### ISSUE TITLE
1.18.2 Crash with optifine

### ISSUE THREAD

**Issue by Blugori** [TeamTwilight/twilightforest#1520]
### Forge Version

40.1.47

### Twilight Forest Version

4.1.1056

### Client Log

<script src="https://gist.github.com/Blugori/50430a61f422ab55ed1492dfb62e3d83.js"></script>

### Steps to Reproduce

1. Launch minecraft
2. Crash

### What You Expected

I expect the game to start

### What Happened Instead

Game doesnt start

### Additional Details

Maybe there is a config to change, so optifine would work with TF (I didnt see any other issue in 1.18 with optifine is that a known bug ?)

### Please Read and Confirm The Following

- [ ] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
"Crash with Optifine" and yet you ticked the box that says you can replicate this bug *without* Optifine.
No, there is no config or switch that magically fixes Optifine. It crashed because it is a buggy, broken mod that removes code we need to make our mod run.

**Comment by RSSYLY** [comment]
I have confirmed that removing Optifine can fix this bug，Optifine HD U H7，with the lastest TF mod and forge 40.1.68🙏🙏.
