### ISSUE TITLE
Can't disable Lich Shields orbiting player

### ISSUE THREAD

**Issue by minecraft9w** [TeamTwilight/twilightforest#1521]
### Forge Version

40.1.48

### Twilight Forest Version

4.1.1056

### Steps to Reproduce

1. Create a world in Creative mode with cheats.
2. Type /advancement grant [username] everything (I Don't know if this matters, but I always do this first when in creative mode)
3. Press F5

### What You Expected

I expected to see just my character.

### What Happened Instead

Instead I have 3 Twilight Lich shields orbiting me, and I searched for a way to get rid of them, because I find them annoying, but it seems they can't be turned off, at least not that I know of.

![2022-06-09_16 49 15](https://user-images.githubusercontent.com/107201751/172882277-25d8321d-f0d9-4cd1-acda-232282beb236.png)

### Additional Details

I Have to add that I've played only Twilight Forest before in 1.7.10, so I don't know if this is a bug or a feature (albeit a very annoying one if that's true). I tried switching to Survival, but it didn't help. I am not sure if advancements have anything to do with it. Also gamerule /tfEnforcedProgression was False.

I have 190 mods installed, but I think this doesn't look much like a cross-mod issue.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
The shields can be removed from your player either by taking damage or using the /tffeature shield set 0 false command.

**Comment by minecraft9w** [comment]
Using the command worked, thanks!
