### ISSUE TITLE
OptiFine HD U H7 crashes while ran with 1.18.2

### ISSUE THREAD

**Issue by Omegapepega553** [TeamTwilight/twilightforest#1522]
### Forge Version

40.1.51

### Twilight Forest Version

1.18.2-4.1.1096

### Steps to Reproduce

drop optifine h7 for 1.18.2 and twilight forest in ur mods folder

### What You Expected

for it to run

### What Happened Instead

it crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
> I have confirmed this bug can be replicated without the use of Optifine.

Read the issue template next time.

**Comment by Drullkus** [comment]
Optifine is closed source and their overhauls to the Minecraft code are not visible for mod developers. Optifine cannot be supported
