### ISSUE TITLE
My modpack crash

### ISSUE THREAD

**Issue by ChillirCR** [TeamTwilight/twilightforest#1523]
### Forge Version

40.1.25

### Twilight Forest Version

4.1.1096

### Client Log

https://gist.github.com/ChillirCR/8945a832cd012e7dab33dcc2158624cb https://gist.github.com/ChillirCR/1fb87eb6dd61fb9cbf12c244041e47a9

### Crash Report (if applicable)

https://gist.github.com/ChillirCR/68daa4421c2dfe7035d52e1b9850ab5f

### Steps to Reproduce

No way to open the game（optifine）

Or the datapack cannot be loaded

### What You Expected

Don't know how to be compatible

### What Happened Instead

Unable to load datapack

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
> I have confirmed this bug can be replicated without the use of Optifine.

Please read the issue template next time.
