### ISSUE TITLE
[1.12.1] [twilightforest-1.12.1-2.4.0.26-universal] Game crash in regards to rendering of a TwilightForest block in JEI

### ISSUE THREAD

**Issue by MrBurd** [TeamTwilight/twilightforest#153]
Forge: 1.12.1-14.22.0.2463
Crash log: https://gist.github.com/MrBurd/129cb7a83d5d9a3516709c51556d781d

Description: Looked up a recipe in JEI, had some TForest blocks on that page.
Upon opening inventories, the game crashes with the above error.

Am able to reproduce, although I am not sure how exactly. 
Originally I queried for "transf" to look up the IE transformer. This also shows the tree of transformation as a result. Having TF blocks on a JEI result page results in a crash after a while.

Spoke about this error with asiekierka on IRC, received this response:

[00:14] MrBurd: this one is most likely a bug in Twilight Forest
[00:15] i assume one of their blocks is disabled in config, so they end up registering an IItemColorHandler for air

I've posted this to both JEI and TwilightForest githubs, JEI commented that this is likely a TF issue.

**Comment by Kris1432** [comment]
https://github.com/mezz/JustEnoughItems/issues/985
