### ISSUE TITLE
Mounts (Carminite Mount) 

### ISSUE THREAD

**Issue by PepperPaws** [TeamTwilight/twilightforest#1530]
### The Suggestion

I believe that this mod should add a mount or mounts to the game. There are many different creatures you could use as inspiration for mounts such as Unicorns, mythical birds, or an entirely new creature that the mod team develops unique to the Twilight Forest. It would obviously be used for travel and could even be progress locked behind some of the early game bosses. 

Similar to the Questing Ram, this creature could have its own special structure and unique way of taming the animal requiring a special food or item. Accessing the creature itself could also require a specific special item as I stated previously, or a fun puzzle. Perhaps Carminite could even be used since it doesn't have much of a purpose out of the several blocks that you can craft. A robot/golem-like mount that feeds off Carminite or Redstone sounds quite interesting to me at least, and would even add a balanced way for people to not abuse the feature since they have to go and find more Carminite and/or Redstone.

Heck! Finding an ancient structure made out of the special Carminite Builder/Reactor/etc blocks would be cool too, maybe a lab of sorts. In the middle could be a mini Iron Golem like structure that one would have to finish building out of Carminite materials in order to summon the creature/mount. The mini golem structure could be partially finished and would hint to players that fixing the build would offer them something nice... being the mount of course 

### Why Should It Be in the Mod?

Adding a mount or mounts to the game would immensely improve travel and exploration throughout the mod. Finding specific structures and bosses in the mod is relatively easy due to the magic maps, but having to find multiple of each structure can prove to be difficult and tedious on foot. It would be helpful to have a rideable companion to help speed up the process. Usually when fighting a boss that drops armor crafting materials such as the Naga or Hydra, you only have to fight the boss 2 or 3 times, but when playing with friends you have to find 2 or 3 more structures per person to be able to craft your desired armor or tools. Of course exploration is a key part to the Twilight Forest, but it can get quite boring if you've already encountered all the biomes and structures provided within the mod and you just need that last 3 Fiery Blood to complete and armor set. 

The idea of a magical rideable creatures fits the "Magical Forest" theme very well and would not seem out of place for the mod. Overall adding more creatures and animals to the game would help the mod feel more alive then it already is. Mounts and Pets in minecraft mods is something that a lot of people enjoy and the fact that the Twilight Forest has none of those things is really shocking to me. It could add more uses for Carminite besides the special blocks too!! The addition of Mounts would definitely appeal to explorers and people who like pets, and would even add a fun new puzzle or achievement for collectors and just those that play the game. 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
We currently are not looking to add any mounts. While helpful to the player, better movement options are preferable in the form of features that don't take away from the quiet, lonely atmosphere outside of dungeons.
