### ISSUE TITLE
Knight Phantom Trophy is Missing its Helmet

### ISSUE THREAD

**Issue by mateidragony** [TeamTwilight/twilightforest#1531]
### Forge Version

40.1.20

### Twilight Forest Version

4.1.1102

### Steps to Reproduce

When the phantom knight trophy is placed or when it is dropped the helmet is missing and you only see the skull beneath the helmet.

### What You Expected

Expected to see the white skull with the green helmet over it

### What Happened Instead

Only saw white skull

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
im pretty sure this is a bug with rubidium, it renders fine in the base mod

**Comment by mateidragony** [comment]
That must be it because I just recently started using rubidium

**Comment by PraseodymiumSpike** [comment]
Shouldn't this be closed?

**Comment by GizmoTheMoonPig** [comment]
closing as this isnt our issue (not sure why I didnt do this a while ago)
