### ISSUE TITLE
Crashing Upon Start Even After Mod Uninstall

### ISSUE THREAD

**Issue by Gurkk80** [TeamTwilight/twilightforest#1532]
### Forge Version

36.2.35

### Twilight Forest Version

4.0.870

### Client Log

https://gist.github.com/Gurkk80/ab2df30d648286510ea33308d21d2554

### Crash Report (if applicable)

https://gist.github.com/Gurkk80/ab2df30d648286510ea33308d21d2554

### Steps to Reproduce

The game shows the Error loading mods screen upon start-up

### What You Expected

It was supposed to go to the start menu

### What Happened Instead

It went to an error load mods screen saying "The Twilight Forest (twilightforest) encountered an error during the common_setup event phase"

### Additional Details

I have 173 other mods 3 of which are compatibility mods, so any other mod could be causing this, also it keeps giving this pop-up event after I remove twilight forest.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Your report states you're using Twilight Forest version `4.0.546`
The log shows you didn't remove it either.
https://gist.github.com/Gurkk80/ab2df30d648286510ea33308d21d2554#file-crash-2022-06-18_13-24-19-fml-txt-L118

You should update to .870.
