### ISSUE TITLE
1.18.2 Items removed on respawn instead of kept with Enigmatic Legacy item testament of contempt

### ISSUE THREAD

**Issue by RavenWolfTiger** [TeamTwilight/twilightforest#1533]
### Forge Version

40.1.31

### Twilight Forest Version

4.1.1052

### Client Log

https://gist.github.com/RavenWolfTiger/d088dc67086f61be246df9c78b50d51c

### Steps to Reproduce

1. Put on the ring of seven curses
2. Wait to reach 99.5% of time spent with ring on
3. Equip the testament of contempt
4. Die in survival (issue does not happen in creative)

### What You Expected

All items are returned to your inventory by the testament of contempt after death.

### What Happened Instead

All items (except curios slot items) are removed from your inventory, and completely deleted. 

### Additional Details

I've tested this with only twilight forest and these mods installed to make sure

Enigmatic Legacy 2.23.1
Patchouli 1.18.2-69 (70 crashes sometimes for some reason) (required for enigmatic)
caelus forge 1.18.1-3.0.0.2 (required for enigmatic)
curios forge 5.0.7.0 (required for enigmatic)

And have also tested with only twilight forest removed to make sure it was not an issue in the mod itself.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Please update Twilight Forest, I already fixed this happening
