### ISSUE TITLE
uncrafting table crash on modded server. 

### ISSUE THREAD

**Issue by GeminiMarshdevil** [TeamTwilight/twilightforest#1534]
### Forge Version

40.1.51

### Twilight Forest Version

4.1.1102

### Client Log

https://gist.github.com/GeminiMarshdevil/e14dbfa657d841761b7cabb1e20f4180

### Crash Report (if applicable)

https://gist.github.com/jinkhya/9b317032619d5897f5e7edaf614256db

### Steps to Reproduce

install twilight forest into a modded minecraft (could take my modpack or just make the modpack yourself)
install said modpack onto a server. 
launch minecraft and log into the newly created modded server.
once inside, follow these steps:

step 1. 
acquire an uncrafting table.

step 2. 
place it anywhere, preferably a stable flat surface.

step 3. 
right click the uncrafting table

step 4. 
place any item in the uncrafting slot.

server will immediately crash. 

### What You Expected

the server not to crash upon placing an item such as tinkers shurikan, supplementary's flax seed, or oak wood planks, into the uncrafting table.  

### What Happened Instead

it crashed big time styles.  instantly and hard.

### Additional Details

playing on this modpack: https://www.curseforge.com/minecraft/modpacks/shaped-aion-cubes/files
the latest release 0.1.0

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this one isnt our fault. The mod in question, AE2 wireless terminal, is marking a method we need to read as client only. Issue spot is here: https://github.com/Mari023/AE2WirelessTerminalLibrary/blob/master/common/src/main/java/de/mari_023/ae2wtlib/wut/recipe/Common.java#L38
Please open an issue about it on their repo instead.
