### ISSUE TITLE
[1.19] Luring the naga outside the courtyard causes a desync

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1537]
### Forge Version

41.0.35

### Twilight Forest Version

1.19-4.2.1135

### Client Log

https://gist.github.com/Shedao-Shai/a2c64a3f9dcb4af8c88c9a1417f8d710

### Steps to Reproduce

1. Find a naga courtyard and spawn the naga
2. Lure the naga outside the courtyard
3. Get it as far out as it will go from the courtyard, easy to do when it charges

### What You Expected

The naga to still function normally (I should be able to hit it, and I belive it should stay within a certain distance from the courtyard)

### What Happened Instead

After getting some distance away (30-40 blocks or so) from the courtyard I am no longer able to damage the naga (though I am able to stun it with a shield still). If it should happen to fall into a cave, tunneling chaos ensues. It does not seem to return to the courtyard on its own 

### Additional Details

Debug log: https://gist.github.com/Shedao-Shai/7bca00fe8fda434d1e42dfe89a601d15

Bug discovered on the tf testing server, replicated by toasterstrudel95 and cupcakeko

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by EvergreenSystems** [comment]
Relogging fixes the issue (at least on a server) and the naga returns to its home, though its possible to repeat the desync with the same naga

**Comment by GizmoTheMoonPig** [comment]
it is worth noting that the naga not being able to take damage outside of its home point is completely intentional, the thing I fixed here is that it will now actively attempt to find its way back into the courtyard if it leaves it.
