### ISSUE TITLE
[1.19] Feather Fan does not protect from fall damage

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1538]
### Forge Version

41.0.35

### Twilight Forest Version

1.19-4.2.1135

### Steps to Reproduce

1. Use a feather fan to jump

### What You Expected

The feather fan should prevent all fall damage resulting from an assisted jump, no matter the height fallen from

### What Happened Instead

The feather fan is not protecting from any fall damage, resulting in it being very risky to use the fan to navigate

### Additional Details

Discovered on the TF testing server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Fixed in 9f7af1025c4f0c487bd688998181ba195009cf8d
