### ISSUE TITLE
[1.19] Canopy bookshelf recipe conflicts with vanilla bookshelves 

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1540]
### Forge Version

41.0.35

### Twilight Forest Version

4.2.1135

### Steps to Reproduce

1. Attempt to craft canopy bookshelves

### What You Expected

The resulting item crafted should be canopy bookshelves

### What Happened Instead

The recipe conflicts with the vanilla bookshelf recipe, and the vanilla recipe overrides. Therefore, it is impossible to craft canopy bookshelves without a mod such as polymorph (which is not yet updated to 1.19)

### Additional Details

Discovered on the TF testing server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Closing as this was already fixed, it's just not on the testing server yet
