### ISSUE TITLE
[1.19] Tree of transformation will not transform biomes on servers

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1541]
### Forge Version

41.0.35

### Twilight Forest Version

4.2.1135

### Steps to Reproduce

1. Grow a transformation tree on a server and activate the core

### What You Expected

The core should transform the surrounding biome into the enchanted forest

### What Happened Instead

The core is ineffective: still lights up and hums, but no biome shift

### Additional Details

Discovered and replicated on the TF testing server, 6/29/2022

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Fixed in d366684b087599a5b79ab4a4f9122d0e6f80d02c
