### ISSUE TITLE
[Suggestion] Update the foliage surrounding generated twilight portals

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1542]
### The Suggestion

Allow twilight portals generated by the game to use a wider range of flowers and other foliage. These could include:
- Flowers added in Minecraft 1.7 and 1.14: Blue Orchid, Allium, Azure Bluet, all four tulips, Oxeye Daisy, Cornflower and Lily of the Valley
- Ferns
- Twilight Forest's Mayapples and Mushglooms

### Why Should It Be in the Mod?

Twilight portals seem to only ever generate with dandelions, poppies, grass, and red and brown mushrooms, which would imply that the list of foliage they can use hasn't been updated since before Minecraft 1.7. Letting the portals generate with the newer flowers and such would make them feel more well integrated into modern Minecraft.~
It would also make the portals more varied, and including Twilight Forest foliage like the ones mentioned would make them feel more related to the mod itself.~

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
yeah, it turns out that list hasnt been updated once since we picked up the project. 
I added a bunch of new flowers, as well as a couple TF plants in e47fc078bbd1b80fcc417570019141ae0d447b5f. This has been on my todo list for a while, I just keep forgetting to do it. Thank you for the suggestion!
