### ISSUE TITLE
[1.18.2]server crashed while i put a torch on the tower of the Snow Queen

### ISSUE THREAD

**Issue by MoXuanSun** [TeamTwilight/twilightforest#1543]
### Forge Version

40.1.53

### Twilight Forest Version

4.1.1102

### Client Log

https://gist.github.com/MoXuanSun/65025a1d734297ccb5e50c1ad732d45d

### Crash Report (if applicable)

https://gist.github.com/MoXuanSun/7bb4bf43da560a31d4ae483d3f4a1dba

### Steps to Reproduce

i was going to beat the snow queen, but when i put a torch on the tower,the server crashed,i tried three times

### What You Expected

i supposed that should light around

### What Happened Instead

the server crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Most likely another mod at play here. I'm not sure what's going on. Though we're ending 1.18.2 support so i'm closing this.
