### ISSUE TITLE
Twilight trilobite 

### ISSUE THREAD

**Issue by Icekaiser** [TeamTwilight/twilightforest#1546]
### The Suggestion

I just been thinking since the twlight forest is its own place and there isn't much at all for the mod sawnping in the twlight streams it would be neat to see a twlight trilobite crawling around and maybe there can be biome variations that spawn based on what biomes the stream is dividing. Maybe they can be added just throwing this out there well they of course all you to get food from them too.

### Why Should It Be in the Mod?

It would be well a new food source something to make the streams more alive then just water dividing the biomes. it would be neat to be able to brew a resistance potions with there shells because of how long the species survived irl for but so its balanced you can brew a uncracked shell which drops from when the trilobites hatch from there eggs similar to sea turtles but have it so it's only resistance 1. It would be cool to craft a sheild with the shells the uncracked ones idk what it can do uniquely I am stumped on that part. But oh you can breed them with sea grass or trilobite meat 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
Trilobites are fascinatingly weird but they're better suited for saltwater environments
