### ISSUE TITLE
[1.19] Rubidium crash when putting magic map in item frame

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1548]
### Forge Version

41.0.35

### Twilight Forest Version

4.2.1135

### Client Log

https://gist.github.com/Shedao-Shai/61c0510490ead9d42e1e439c30eb14d6

### Crash Report (if applicable)

https://gist.github.com/Shedao-Shai/e2d1a8eb6e67f8e9992fc76e973541e1

### Steps to Reproduce

1. Install Rubidium and TF
2. Open a magic map, then attempt to place said map in an item frame

### What You Expected

The map should have displayed on the item frame per normal

### What Happened Instead

Game crashed prior to rendering the map

### Additional Details

Discovered on the TF Testing Server

As this is a crash resulting (I think) from a conflict, I am also reporting this on Rubidium's github. I am unsure which mod is at fault, though I suspect Iris as performance mods can do strange things

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Fixed by eefe5585b03e220f5d537d6275d38021c26182e3
