### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by StaticSapphic** [TeamTwilight/twilightforest#1550]
### The Suggestion

Add an option to the client config file for changing the texture, model and sounds of all 4 (?) spider-based entities added in this mod to something less spiderlike like a blob or a beetle. It would be a purely cosmetic change and wouldn't affect hitboxes or gameplay.

### Why Should It Be in the Mod?

Some people with arachnophobia are unable to play the base game due to the spider models. [While there are resource packs that fix this for the base game](https://www.curseforge.com/minecraft/texture-packs/spiders-be-gone), they require optifine (Which is incompatible with a lot of forge mods) and are specific to the vanilla spiders.

I'm personally requesting this because one of my friends has severe arachnophobia, however I am sure that this feature would make the mod more accessible to many players

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
Everything but changing the model is do-able by Resource Pack already.

Models are complicated and can't be done until Mojang makes them data-driven (json files)

**Comment by StaticSapphic** [comment]
Yeah the model part was the main bit that I was stuck with, I figured there wasn't really any point changing the texture if the model is still spider shaped

Its weird that they're not changeable already to be honest since they already added that feature to bedrock

That's a shame, thanks for letting me know so quickly tho
