### ISSUE TITLE
Can't make any progress after kill Naga

### ISSUE THREAD

**Issue by Amysita** [TeamTwilight/twilightforest#1551]
### Forge Version

1.16.4

### Twilight Forest Version

1.16.5-4.0.870-universal

### Steps to Reproduce

We decided to do the twilight forest quests, when we finish killing Naga, it doesn't show any progress, therefore we can't enter the twilight lich castle, it only shows the dropped items but no notification or achievement in the chat.

### What You Expected

nothing

### What Happened Instead

nothing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
progression relies completely on advancements, not quests. If you don't have "Time to Even the Scales", you won't be able to move on. Here's a few things you can try to get the advancement:
- in 1.16 and below, getting the Naga advancement requires you to get "The Silence of the Forest". To get this, simply kill any TF mob.
- make sure you have either killed the Naga, held the trophy, or held a Naga scale. Any of these 3 will grant you the advancement. 
- If that doesn't do the trick, try relogging.  Vanilla sometimes has issues with advancements that we can't really fix, and relogging often helps.
