### ISSUE TITLE
Currently no boats for any Twilight Forest planks

### ISSUE THREAD

**Issue by RepeatGitHub** [TeamTwilight/twilightforest#1552]
Forge version: 
Twilight Forest version: 4.0.943

Steps to reproduce:
1. Try crafting a boat using any set of Twilight Forest planks.

What I expected to happen:
It would craft a boat out of any given set of planks.

What happened instead:
Boats cannot be made out of Twilight Forest planks.

**Comment by GizmoTheMoonPig** [comment]
We haven't gotten around to making them yet. It's on my todo list though

**Comment by GizmoTheMoonPig** [comment]
added in c88868a9af923ecd44501b73ea4488f1baf4656c
