### ISSUE TITLE
[Suggestion] Renewable Underbrick

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1553]
### The Suggestion

Two Armor Shards and two clay balls in a checkerboard shape can be crafted into Undergrout, which is visually similar to the clay ball, but its colored more like the grout lines between the bricks on the Underbrick block texture. Crafting two Undergrout and two bricks in the same checkerboard shape would yield Underbrick blocks.

### Why Should It Be in the Mod?

- Making building blocks like Underbrick renewable helps players get large quantities of the blocks for large builds.
- This means of obtaining the bricks renewably would give Armor Shards another use, since the player currently has no reason to go back to the goblin knight stronghold to farm them once they have better armor and tools/weapons than Knightmetal.
- Because the player has to deliberately make Undergrout, they wouldn't end up with them clogging up their inventory, which would happen if they were a mob drop, for example. This is a non intrusive and simple way of making Underbricks renewable.
- Undergrout could be added to the stronghold's loot chests as a flavorful, if not very useful, loot item.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by PraseodymiumSpike** [comment]
Good idea

**Comment by Killer-Demon** [comment]
If we're going to make Underbrick renewable we'll revisit this suggestion when it comes time for the dungeon's rework. It won't be with knightmetal, though.
