### ISSUE TITLE
Crash while rendering item with Immersive Weathering

### ISSUE THREAD

**Issue by moon-st0ne** [TeamTwilight/twilightforest#1556]
### Forge Version

40.1.54

### Twilight Forest Version

4.1.1102

### Client Log

https://paste.ee/p/nLJOD

### Crash Report (if applicable)

https://paste.ee/p/9PeMF

### Steps to Reproduce

1. Load into the world
2. Scroll through JEI until you reach Immersive Weathering, or browse the creative menu
3. Enounter the glitched item(s)
4. Crash

### What You Expected

Items should display as normal and not crash the game

### What Happened Instead

The game crashed whilst trying to render the item(s)

### Additional Details

Immersive Weathering 1.2.11
JEI 9.7.0.209

No optifine, spark, rubidium, etc. performance mods
I'm not sure if this is a TF bug, JEI bug, or IW bug. Since Twilight Forest was listed first in the crashlog, I submitted it here.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
looks like the paste.ee links are expired. If youre still having an issue with this, can you send some new ones so I can take a look?

**Comment by CrownJoker** [comment]
Hello there, I believe I may be experiencing the same/a similar issue. Pastebin of the full crash report below.
Minecraft Version 1.18.2
Forge Version 40.1.86
Twilight Forest Version 4.1.1423
Immersive Weathering 1.2.11

https://pastebin.com/BBVCEuvT

**Comment by GizmoTheMoonPig** [comment]
This really shouldn't have been on our end to fix, as it looks like IW is loading in the item colors before items are fully registered, but I added an extra check to prevent this crash in 1.19
