### ISSUE TITLE
[1.19] Change to the naga courtyard floor

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1557]
### Forge Version

41.0.35

### Twilight Forest Version

4.2.1163

### Steps to Reproduce

1. Locate a naga courtyard

### What You Expected

The tiles in the past have consisted of etched nagastone, ruined etched nagastone and mossy etched nagastone. About equal quantities of each (I assume a 1/3rd chance between the three for each block)

### What Happened Instead

In 1.19 it only consists of etched nagastone, no ruined or mossy. The walls remain the same, this is just the floor. I do not know if this was an intentional change or not, which is why I am pointing it out

### Additional Details

Discovered on the TF testing server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by EvergreenSystems** [comment]
Hmm, this seems to be on a case by case basis. I've found another that generated normally, and yet another that has the same issue

**Comment by Drullkus** [comment]
Sounds like the structure processor isn't getting applied

**Comment by jodlodi** [comment]
Seems to not happen anymore? Re-open if the issue reoccurs.

**Comment by EvergreenSystems** [comment]
Re-opening this because I've found this happening in 1.19.3. In this case, all the floor bricks are the base nagastone, no mossy or ruined

System details: forge 44.1.17, TF 4.2.1604

I am not sure if this would be replicable with a new world with the same seed, but here are those details anyway.
Seed: -5014295792392571317    Coords: 16089 ~ -16410 (in TF)

**Comment by EvergreenSystems** [comment]
![2023-02-22_14 42 10](https://user-images.githubusercontent.com/23658767/220754070-0a80a05f-33a7-4b87-bd6d-eb3722a2aa38.png)

**Comment by Tamaized** [comment]
Possibly related to #1757 ?
