### ISSUE TITLE
[1.19] Wither can break keepsake caskets

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1559]
### Forge Version

41.0.35

### Twilight Forest Version

4.2.1163

### Steps to Reproduce

1. Place a keepsake casket by a wither, either manually or by dying

### What You Expected

The casket to be there when I returned to recover my items (and finish fighting the wither)

### What Happened Instead

The wither can break caskets when it does its block-breaking movement, spilling stuff all over the floor and leaving it open to being blown up

### Additional Details

Discovered on the tf testing server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
I was going to say, this shouldnt be possible as the casket is in the wither immune tag, but I just learned that the tag has no bearing on the block breaking thing after being hurt. Thanks, mojang. I'll fix this soon

**Comment by EvergreenSystems** [comment]
My blown up netherite pickaxe thanks you
