### ISSUE TITLE
Lich's Tower Uncraftable Potion

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#156]
Forge version: 14.22.0.2462
Twilight Forest version: (this is the build number) 2.4.0.26
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline) N/A

Steps to reproduce:
1. Open chest in a Lich's Tower library.
2. Get lucky.
3. Uncraftable Potion.

What I expected to happen:
A normal potion.

What happened instead:
A not normal potion, not much to it.

http://imgur.com/a/OHfSz

**Comment by williewillus** [comment]
there isn't a good way to go about this because I use `CustomPotionEffects` tag, which automatically makes the name look like that (MC ignores the PotionType after it sees CustomPotionEffects). 
Setting a name manually in the loot table would be bad because then it wouldn't be localized.

**Comment by williewillus** [comment]
though, there are only two uses of CustomPotionEffects and they're both for potions very similar to default ones so I might just make it use a default potion
