### ISSUE TITLE
[Suggestion]  TF paintings, for the lich tower and elsewhere

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1564]
### The Suggestion

The current lich tower has a multitude of paintings, and while I don't know this for certain I assume the reworked structure will as well. Paintings are all well and cool, but most don't really fit the TF aesthetic. I have gone and made multiple painting textures that more suit the TF, and will be creating more as time allows. 

### Why Should It Be in the Mod?

As stated above, vanilla paintings don't really suit the Twilight Forest. Along with (if I can say so) looking cool, this would improve the aesthetic of the lich tower and anywhere else these paintings should appear. Pasted below are both actual size pictures, and blown up screen shots for non-squinting use.

Screenshots: 
<img width="349" alt="Hydra" src="https://user-images.githubusercontent.com/23658767/178166634-dac27006-bea8-4aa1-b0cf-88ff5d5ea23c.png">
<img width="344" alt="Ice_Queen" src="https://user-images.githubusercontent.com/23658767/178166636-a1029bb4-c992-46cb-ae5d-b08903d9a69a.png">
<img width="344" alt="Lich" src="https://user-images.githubusercontent.com/23658767/178166637-6b323ad8-0705-45c2-bc57-5503c57b0e74.png">
<img width="343" alt="Minoshroom" src="https://user-images.githubusercontent.com/23658767/178166638-76138d40-e1cf-41ca-90aa-6f494d4c3a4e.png">
<img width="173" alt="Naga" src="https://user-images.githubusercontent.com/23658767/178166639-abb2e65c-40af-4ab8-a1c4-dbec8d9bc985.png">
<img width="376" alt="Phantom 2" src="https://user-images.githubusercontent.com/23658767/178166640-c0b88405-6b59-443d-8860-fe3a7c4708b1.png">
<img width="377" alt="Phantom" src="https://user-images.githubusercontent.com/23658767/178166641-0e7a3dd7-562b-438f-b99c-5f8d79b46477.png">
<img width="341" alt="Snowflake" src="https://user-images.githubusercontent.com/23658767/178166642-345c4821-3276-48c8-af5d-9cb7b71a5e04.png">
<img width="352" alt="Ur_Ghast_16x16" src="https://user-images.githubusercontent.com/23658767/178166643-e4b04fef-05bf-4a3d-a2a5-b2bc1bcae405.png">
<img width="351" alt="Ur_Ghast_32x32" src="https://user-images.githubusercontent.com/23658767/178166644-18ccdb07-272c-473e-bb49-d2193cbbc335.png">
<img width="341" alt="Yeti" src="https://user-images.githubusercontent.com/23658767/178166645-d231e1e0-5ac3-4192-9efa-34883c54f658.png">
<img width="171" alt="Yeti_2" src="https://user-images.githubusercontent.com/23658767/178166646-bf52a8bc-8c2e-4753-92b2-bb955ac5000e.png">

Actual Size: 
![Hydra_64x64](https://user-images.githubusercontent.com/23658767/178166655-08a0ce5d-0b9f-4524-9899-615c8d321ba7.jpg)
![Ice_Queen_32x32](https://user-images.githubusercontent.com/23658767/178166656-defbf511-76bc-49e3-87c2-daa0ed0ab11e.jpg)
![Knight_Phantom_2_64x64](https://user-images.githubusercontent.com/23658767/178166658-ef808bbb-e821-4acc-98d7-3b397aaadee5.jpg)
![Knight_Phantom_32x32](https://user-images.githubusercontent.com/23658767/178166659-079cd325-2d86-4172-8a8a-08d0969a40ac.jpg)
![Lich_64x64](https://user-images.githubusercontent.com/23658767/178166660-2950d2a9-9f13-4b8a-b28b-b7d7147be97f.jpg)
![Minoshroom_32x32](https://user-images.githubusercontent.com/23658767/178166661-e3d1087b-5095-4ec0-84ab-8849591c796c.jpg)
![Naga_16x32](https://user-images.githubusercontent.com/23658767/178166662-634f8bab-b2ef-4c37-b568-c889e2110819.jpg)
![Snowflake_32x32](https://user-images.githubusercontent.com/23658767/178166663-d1d6ed03-b377-4de7-8a7a-1072afb56200.jpg)
![Ur_Ghast_16x16](https://user-images.githubusercontent.com/23658767/178166664-a8d72b41-f171-439c-8118-087fcfbc9196.jpg)
![Ur_Ghast_32x32](https://user-images.githubusercontent.com/23658767/178166665-8fa87ff8-884d-4933-bf62-be04a52dca6d.jpg)
![Yeti_32x32](https://user-images.githubusercontent.com/23658767/178166666-e7ed4ba0-f259-4e5d-bd14-e966553206ee.jpg)
![Yeti_32x64](https://user-images.githubusercontent.com/23658767/178166667-de9c01be-3ed3-49df-96e2-064625b777ed.jpg)

I will be creating more of these as I find them quite fun, and will add them as I go

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by EvergreenSystems** [comment]
Skull Candle
![Skull_Candle_32x32](https://user-images.githubusercontent.com/23658767/178166883-982c4af7-84f3-4473-bb24-b25ac557a2bb.jpg)
<img width="353" alt="Skull_Candle" src="https://user-images.githubusercontent.com/23658767/178166889-15fd2843-8b22-4371-97d6-ced038ec8aa9.png">

**Comment by EvergreenSystems** [comment]
Uncrafting Table
![Uncrafting_Table_32x32](https://user-images.githubusercontent.com/23658767/178167380-3af323d7-ba41-401c-af22-c203ac51edf6.jpg)
<img width="347" alt="Uncrafting_Table" src="https://user-images.githubusercontent.com/23658767/178167387-5c706456-ab49-4c10-b65e-789df82b7cf4.png">

**Comment by EvergreenSystems** [comment]
Kobold, wide and tall
![Kobold_16x16](https://user-images.githubusercontent.com/23658767/178168677-5f5a575f-df99-430f-ac8e-c25f8b7e6b83.jpg)
![Kobold_16x32](https://user-images.githubusercontent.com/23658767/178168678-a0b69646-9ff1-4888-9690-993db994bfa0.jpg)
<img width="347" alt="Kobold_16x16" src="https://user-images.githubusercontent.com/23658767/178168681-7c9de1c3-be24-49d9-976c-2a9e2b04c42c.png">
<img width="170" alt="Kobold_16x32" src="https://user-images.githubusercontent.com/23658767/178168682-d9878b69-bd2c-45a9-833d-560b66ada21b.png">

**Comment by EvergreenSystems** [comment]
Towers
![Aurora_64x64](https://user-images.githubusercontent.com/23658767/178169304-44813e34-e331-4d3c-8efd-f83789daed19.jpg)
![Dark_Tower_64x64](https://user-images.githubusercontent.com/23658767/178169307-37e94ae8-5737-44ff-9b78-039039bdcd14.png)
<img width="344" alt="Aurora_64x64" src="https://user-images.githubusercontent.com/23658767/178169315-3918ebee-2ce0-4b78-9890-5f3142be4c62.png">
<img width="344" alt="Dark_Tower_64x64" src="https://user-images.githubusercontent.com/23658767/178169316-8a9a1cd6-7d76-4186-8489-fdd60367754b.png">

**Comment by EvergreenSystems** [comment]
Ur-Ghast
![Ur_Ghast_32x16](https://user-images.githubusercontent.com/23658767/178170337-bd49ca61-9a2d-4b3b-a093-aa9ab2b2dabe.jpg)
![Ur_Ghast_64x64](https://user-images.githubusercontent.com/23658767/178170338-0f119e08-e500-4c8d-b49c-437d9ca4778c.jpg)
<img width="514" alt="Ur_Ghast_32x16" src="https://user-images.githubusercontent.com/23658767/178170344-9a124d2a-b1c3-455b-8260-bf20148503fc.png">
<img width="347" alt="Ur_Ghast_64x64" src="https://user-images.githubusercontent.com/23658767/178170346-4bf2b86d-7446-40c4-8d3f-8464bf0f3058.png">

**Comment by EvergreenSystems** [comment]
Crab

![Crab_32x32](https://user-images.githubusercontent.com/23658767/178170955-d1158b4e-c8d2-430c-809b-1a7cda6e624c.jpg)
<img width="347" alt="Crab_32x32" src="https://user-images.githubusercontent.com/23658767/178170959-8b1423be-4693-4059-b66d-f099dabab34d.png">

**Comment by PraseodymiumSpike** [comment]
I'd say that they shouldn't just be screenshots or drawings of in-game things. The Vanilla game only has a couple of those, There should be some mostly-unrelated ones, too. Screenshots are especially bad.

**Comment by EvergreenSystems** [comment]
> I'd say that they shouldn't just be screenshots or drawings of in-game things. The Vanilla game only has a couple of those, There should be some mostly-unrelated ones, too. Screenshots are especially bad.

These are meant to specifically be related to the TF, that's the entire point. An unrelated painting wouldn't make any sense for inclusion in the mod (or in an addon, which I have created for 1.18.2)

**Comment by PraseodymiumSpike** [comment]
> > I'd say that they shouldn't just be screenshots or drawings of in-game things. The Vanilla game only has a couple of those, There should be some mostly-unrelated ones, too. Screenshots are especially bad.
> 
> These are meant to specifically be related to the TF, that's the entire point. An unrelated painting wouldn't make any sense for inclusion in the mod (or in an addon, which I have created for 1.18.2)

Still, I'd say that pixelated screenshots shouldn't be added. With all due respect, merely pixelating a screenshot isn't super creative. May I suggest something else instead? Find a real painting of a non-Minecraft version of the object such as [this](https://en.wikipedia.org/wiki/Minotaur#/media/File:Edward_Burne-Jones_-_Tile_Design_-_Theseus_and_the_Minotaur_in_the_Labyrinth_-_Google_Art_Project.jpg), pixelate it, and replace the non-Minecraft version of the object or objects (for example the Minotaur, Theseus, and Theseus's string) with the Minecraft version (for example the Minoshroom, a Minecraft Player, and some Red Thread). This follows the style of [Pigscene](https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/be/Pigscene_%28texture%29_JE1_BE1.png/revision/latest/scale-to-width-down/120?cb=20201027074218), which is a "Minecraftization" of [The Artist's Studio](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Jacob_van_Oost_%28I%29_-_The_Artist%27s_Studio_-_WGA16654.jpg/800px-Jacob_van_Oost_%28I%29_-_The_Artist%27s_Studio_-_WGA16654.jpg?20110722054117). The resulting Paintings would still be related to the Twilight Forest, and they would match the vanilla Paintings better.

Here is a short list of paintings that could be "Minecraftized":
[Kobold](https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Kobold_and_flowers.jpeg/220px-Kobold_and_flowers.jpeg)
[Helmet Crab](https://www.nationalgallery.org.uk/media/35032/l-0995-00-000007-hd.jpg?center=0.43613707165109034,0.48571428571428571&mode=crop&width=1280&height=960&rnd=132385930482730000)

**Comment by Killer-Demon** [comment]
This is not something we're looking to add. We're currently doing something with paintings in our own way, however.
