### ISSUE TITLE
[1.19] Malformed client-bound packets are sent when entering the dark forest biome on a server, causing repeating disconnections

### ISSUE THREAD

**Issue by ibarnstormer** [TeamTwilight/twilightforest#1566]
### Forge Version

41.0.98

### Twilight Forest Version

4.2.1212

### Client Log

https://gist.github.com/ibarnstormer/2dfa13a244d704c889ed5993ba467c51

### Crash Report (if applicable)

N/A

### Steps to Reproduce

1. Setup an instance of a Minecraft Forge server running the Twilight Forest mod (doesn't have to be a 3rd party provider, can be localhost but not LAN)
2. Enter the Twilight Forest and locate a dark forest biome
3. Enter the biome and walk (or fly around) near the ground level for a few minutes (1-3 should be enough)
4. The client would sometimes disconnect from the server (but not crash to desktop) most likely caused by malformed client-bound packets, sometimes causing a continuous softlock of disconnects

### What You Expected

The player should traverse the dark forest without any random disconnects.

### What Happened Instead

The player randomly disconnects from the server while traversing the dark forest.

### Additional Details

Multiple different network related exceptions were recorded:

![tf_dark_forest](https://user-images.githubusercontent.com/48729319/179575755-9c50abf5-c08c-4445-9a2d-13025f79fc4b.png)
![tf_dark_forest_2](https://user-images.githubusercontent.com/48729319/179575813-3f14808e-499f-4ce9-84f5-8d95423fe3a1.png)
![tf_dark_forest_3](https://user-images.githubusercontent.com/48729319/179575826-ecfa3f10-65d2-43ca-a5d4-5a436894cdff.png)
![tf_dark_forest_4](https://user-images.githubusercontent.com/48729319/179575849-19afa6aa-6d7c-4830-8e51-a3da3647174e.png)

Other notes:
The issue did not seem to be present on mod version 4.2.1163 running forge 41.0.63
Tested on multiple worlds with different seeds

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Can we get a server log as well

**Comment by ibarnstormer** [comment]
https://gist.github.com/ibarnstormer/b7bf857a2c9a2feb28663a889d5227b0

**Comment by GizmoTheMoonPig** [comment]
ive tracked this down to be an issue with the block and chain goblins, we'll do our best to fix this as soon as we can

**Comment by GizmoTheMoonPig** [comment]
disconnection issues are fixed for now, you will notice that hydra heads and block and chain chain pieces don't render correctly. Tama will be fixing this later this week when he has time.
