### ISSUE TITLE
Мод не работает на сервере

### ISSUE THREAD

**Issue by MrTvist** [TeamTwilight/twilightforest#1568]
### Forge Version

36.2.35

### Twilight Forest Version

4.0.870

### Steps to Reproduce

Мод через jei показывает что мод присутствует на сервере, но создавая портал и кинув туда алмаз, нечего не происходит, всё испробовал  но нечего не помогает.

### What You Expected

Думал появиться молния и портал но нет

### What Happened Instead

Всё описанно до этого

### Additional Details

Это всё на сервере, где играют мои друзья, но у них мод не запрашивает.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Just getting a rough translation: Twilight Forest blocks and items are showing up in JEI but the portal doesn't activate.

This indicates that the server does not have Twilight Forest installed. There are a few reasons why:
1. The server is a Vanilla server (the wrong server jar was run). To test, run `/forge`, and if it says the command is unknown, the server is not modded.
2. The server does not have Twilight Forest installed. While players can enter with the mod installed on their side, the server does not have the mod and will not create the portal. To test, run `/tffeature`, and if it says the command is unknown, the server does not have the mod installed.

**Comment by MrTvist** [comment]
А можете дать сыллки на скачивание этих 2 модов?
