### ISSUE TITLE
Hydra Fire Should Smelt Raw Ore Blocks.

### ISSUE THREAD

**Issue by PraseodymiumSpike** [TeamTwilight/twilightforest#1570]
### The Suggestion

If a raw ore Block such as a Raw Iron Block, Raw Gold Block, Raw Copper Block, or Raw Ironwood Block is in the path of the Hydra's fire breath attack, it would turn into a Block of Iron, Block of Gold, Block of Copper, or Block of Ironwood, respectively.

### Why Should It Be in the Mod?

It would increase the speed of smelting, but only if the Player is willing to brave the danger of being close to the Hydra. Also, Hydra fire seems like it would be hot enough to do this.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by PraseodymiumSpike** [comment]
You could also make this a form of recipe able to be changed using Datapacks. Just Enough Items integration may need to be done as well.

**Comment by Drullkus** [comment]
This is way out of scope for a boss battle
