### ISSUE TITLE
Hydra Fire Smelting for Netherite

### ISSUE THREAD

**Issue by PraseodymiumSpike** [TeamTwilight/twilightforest#1571]
### The Suggestion

A 4x4x4 cube of Ancient Debris and Blocks of Gold arranged in a 3-dimensional checkerboard pattern (like sodium and chlorine atoms in salt) in the path of the Hydra's fire breath attack would be converted into a single Block of Netherite. Which block of the 64 is replaced with the Block of Netherite would depend on from which direction the fire breath was coming.

### Why Should It Be in the Mod?

I am not completely sure this is a good idea, but I figured I would put it out there for completeness. Note that this method would require less Netherite but more Gold than doing it the normal way.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by PraseodymiumSpike** [comment]
You could also make this a form of recipe able to be changed using Datapacks. Just Enough Items integration may need to be done as well.

**Comment by Drullkus** [comment]
This is way out of scope for a boss battle
