### ISSUE TITLE
[1.19] Magic maps in item frames are still broken on servers

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1572]
### Forge Version

41.0.100

### Twilight Forest Version

4.2.1213

### Steps to Reproduce

1. Fill out a magic map and place the map in an item frame
2. Restart the server

### What You Expected

The magic maps in the item frames should remain unchanged and intact across server restarts

### What Happened Instead

The maps looked fine when they were first put in the item frames and were fine across relogs, however once the server restarted and I rejoined the next day they had broken: they rendered as an item in the frame instead of a map, and when taken out the biomes in the background had disappeared. This persisted when placed back in the item frame, sadly the maps are permanently broken. 
![2022-07-22_12 07 54](https://user-images.githubusercontent.com/23658767/180490494-4a841820-edf6-4841-af78-c952c83bf61a.png)

### Additional Details

Discovered on the TF testing server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Does the same thing happen to Maze and Ore maps?

**Comment by EvergreenSystems** [comment]
I have not tested, I'll make one of each but I don't have a good way to test it without having the testing server restart

**Comment by AerosAtar** [comment]
Can confirm the same issue in 1.18.2 with Twilight Forest 4.1.1397. The fact it is on server restart makes it especially bad for Single Player worlds.

Additional information: When in your hand, the biomes show but the icons do not. However, any blank areas on the map do not fill as you explore (either biomes or icons).

EDIT: Have checked Maze and Ore maps and they appear fine, so the issue only appears to affect the Magic Map.
