### ISSUE TITLE
[Suggestion] Giant's Furnace

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1573]
### The Suggestion

Surrounding a lamp of cinders with eight giant cobblestone in a crafting grid creates a *giant furnace*, a furnace of the same scale as the other giant blocks. Since it takes up the space that 64 regular furnaces would occupy, it smelts up to 64 items at once in the same amount of time it would take a regular furnace to smelt one. It also consumes fuel 64 times as fast as a regular furnace. It would thus act as a way of interacting with 64 furnaces at once in the form of one block, which is more convenient than a vanilla super smelter contraption.

Visually, it would either use the furnace texture scaled up, like how the giant blocks looked in 1.7.10, or 64x64 versions of the furnace textures to keep the same pixel scale as other blocks.

The lamp of cinders is in the recipe to make it harder to make tons of giant furnaces, given that the giant pickaxe makes giant cobblestone renewable, and also provides a use for lamps of cinders the player acquires after their first one; see below.

### Why Should It Be in the Mod?

- The giants and their giant-size hut and trees make for a fairly silly structure, and the giant furnace would be a suitably silly reward for clearing these structures. *How do the giants smelt?* In a giant furnace, of course!
- Compared to other structures, which offers different sets of equipment, unique weapons like the Lich's scepters or the block and chain, utilities like the uncrafting table and regenerating experiment 115s... the troll caves/giant clouds offer very little functional loot. You get a new sword, a pickaxe good for mass mining, magic beans for climbing, the lamp of cinders needed to progress, and that's it. Adding the giant furnace would give these structures another reason for the player to loot them.
- There is currently very little motivation to clear more than one troll cave, given that lamps of cinders after the first one are unneeded, and the unique magic beans and giant obsidian are farmable; only uberous soil is a unique loot item if a player for some reason wants tons of it. This is silly to me when each highlands contains four troll caves, considering that similar structures have reasons to raid more than one (looting vaults in multiple mazes to try for a Mazebreaker, getting enough alpha yeti fur for a complete armor set & stocking up on the ice bombs). Adding the giant furnace and making each one require a lamp of cinders would incentivize players to raid multiple troll caves if they want multiple giant furnaces.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
an 4x4x4 block entity sounds like a nightmare
