### ISSUE TITLE
[Suggestion] Silent Gear compatability

### ISSUE THREAD

**Issue by farinc** [TeamTwilight/twilightforest#1574]
### The Suggestion

Basically include similar materials and traits for silent's gears tools like what is already available for tinker's construct.

### Why Should It Be in the Mod?

While such materials can be added without such a compat (although certain traits would still have to done java side), it would make sense that gameplay with similar mods to tinker's construct see identical traits and materials. 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
This would be better suited for an addon mod.

We plan to move tcon support into its own addon mod as well.

**Comment by Killer-Demon** [comment]
Basically what Tama said. I'm closing this issue in light of that.
