### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by callmebigpasta** [TeamTwilight/twilightforest#1577]
### Forge Version

40.1.60

### Twilight Forest Version

twilightforest-1.18.2-4.1.1184-universal.jar

### Client Log

https://gist.github.com/callmebigpasta/d9791c5e0f1978ffdd3e6d485e997b00

### Crash Report (if applicable)

https://gist.github.com/callmebigpasta/443629c9f4392126e7b71ebe0b0c029b

### Steps to Reproduce

1. Right click on Stalwart Dungeons Broken Spawner
2. Crash

### What You Expected

Tried to right click on Stalwart Dungeons broken spawner in JEI to see recipes (I had a few in my inventory)

### What Happened Instead

Screen went black with a gray pixelated image in the center then crashed. Can't load past the title MC screen (when choosing singleplayer, multi, etc.)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
> 	Mod File: stalwart-dungeons-1.18.2-1.2.2.jar
	Failure message: Stalwart Dungeons (stalwart_dungeons) has failed to load correctly
	
This isn't a Twilight Forest issue.

**Comment by callmebigpasta** [comment]
> 

The crash message I got was:

The game crashed whilst rendering overlay Error: net.minecraftforge.fml.ModLoadingException: The Twilight Forest (twilightforest) encountered an error during the enqueue_imc event phase Exit Code: -1

Not sure if that changes anything, my bad for forgetting to mention that.

**Comment by GizmoTheMoonPig** [comment]
as tama said, this is an issue with stalwart dungeons. Please report it to them instead.
