### ISSUE TITLE
[Suggestion] Craft Red Thread into red wool

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1580]
### The Suggestion

Placing four red thread in a 2x2 formation in a crafting grid yields one red wool.

### Why Should It Be in the Mod?

Vanilla has white string that can be crafted into white wool. It stands to reason that TF's red string should be able to be crafted into red wool. This is a small feature- one singular recipe- that would improve the feel of the mod by giving red thread a use consistent with string. It's also silly and fun.~

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
Red Thread is a mystical item, even from mythology tales, crafting it into wool is an insult to the item :smile:
