### ISSUE TITLE
[1.19.1] Dimension does not load on first world startup

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1582]
### Forge Version

42.0.0

### Twilight Forest Version

4.2.1236

### Client Log

https://gist.github.com/Shedao-Shai/9ee4ae83cfb9503ad62e5c26e3e24c6b

### Steps to Reproduce

1. Create a new world, and light a TF portal.
2. Enter the portal, this must be done before the world is closed for the first time (the bug fixes itself after first reload)

### What You Expected

The portal should function per normal 

### What Happened Instead

When the world is first created, the twilight forest dimension does not exist. Therefore, the portal will not allow you to enter (though you can still light it), and /execute commands cannot detect the twilight forest dimension.

### Additional Details

Debug log: https://gist.github.com/Shedao-Shai/8fae419b8902d831c6979c5b1d3be78d

Ye olde portal bath
![2022-07-31_13 47 48](https://user-images.githubusercontent.com/23658767/182041213-820af33f-84b5-492d-87a9-27cf5422d11e.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Sounds like a vanilla bug to me.

**Comment by GizmoTheMoonPig** [comment]
this is due to a vanilla bug: https://github.com/MinecraftForge/MinecraftForge/issues/8964. Not really our issue, closing
