### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by nicXcole** [TeamTwilight/twilightforest#1583]
### Forge Version

40.0.32

### Twilight Forest Version

4.1.1220

### Client Log

https://gist.github.com/nicXcole/8712f49a95abbb448efe4e9886a30260

### Crash Report (if applicable)

https://gist.github.com/nicXcole/5b07e0a8112b2f9eb736f0f90abda71a

### Steps to Reproduce

1. add mod to folder 
2. launch game 
3. error in common_setup event phase 

### What You Expected

I expected that when I launched Minecraft the the mod would load properly and open up to the starter menu.

### What Happened Instead

When I launched Minecraft the game never actually loaded it went straight to the crash window saying there was an error loading the mod. It said the error was in the  common_setup event phase. 

### Additional Details

I have multiple other mods installed (not including optifine). I tried uninstalling my other mods and tried to run twilight forest by itself but it still said there was an issue loading the mod. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by isaaclepes** [comment]
Have you tried with a newer version of Forge?  I know the mods.toml just requires 40.0.2 or higher, but forge has changed a lot since March.  Current recommended release of Forge for 1.18.2 is 40.1.0.

**Comment by nicXcole** [comment]
Installing a new version of forge worked, thank you.
