### ISSUE TITLE
[Suggestion] Make portal texture differ from Nether Portals.

### ISSUE THREAD

**Issue by isaaclepes** [TeamTwilight/twilightforest#1585]
### The Suggestion

I think it would be better if the TF portal didn't look like nether portals.  Maybe something as simple as recoloring the original using the TF logo colors (blues/greens).

### Why Should It Be in the Mod?

I believe it would make the mod feel more polished while also differentiating it from the nether portals.

I checked through closed topics and did not see a similar suggestion.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by isaaclepes** [comment]
I was digging around in the jar file and discovered you are using a custom texture, but in my world it looks just like the nether portal.

idk.. closing suggestion.

**Comment by isaaclepes** [comment]
I changed the nether portal texture hue just to see what it might look like, but the TF portal would have to reference it's own texture for this to be separate.

![image](https://user-images.githubusercontent.com/54421422/182727208-c2095325-b56d-4eb8-8199-85164cd9eae6.png)

**Comment by GizmoTheMoonPig** [comment]
We decided it would be best to leave the portal as-is. The portal is extremely iconic to the mod, so changing it would not be the wisest idea. Since the portal is its own block, one can easily change its model and texture with a resource pack.

**Comment by isaaclepes** [comment]
Fair enough. Because it references the nether portal texture, it's not possible to retexture it with a normal resource pack without also changing the nether portal.

**Comment by GizmoTheMoonPig** [comment]
you can change the texture reference in the block model and that should do the trick
