### ISSUE TITLE
Server crashed 1.16.5

### ISSUE THREAD

**Issue by Legofano** [TeamTwilight/twilightforest#1589]
### Forge Version

36.2.34

### Twilight Forest Version

4.0.870

### Client Log

https://mclo.gs/gHrJaiz

### Steps to Reproduce

1. Get in to the portal
2. You appear in the TF world
3. You cant change the mode of the game, eat or open things like backpacks
4. The server kicks you out with the excuse of "timeout".
5. If you try to log in, the timeout message appears.

### What You Expected

Appear in the first biome and no kick us

### What Happened Instead

When we enter we appear in the middle of the water next to a snow biome, just after the server freezes and throws us out although in the server page appears that we are connected, and yet every time we try to get in the timeout message appears. 
In one of the many tests we tried to enter and exit quickly and as a consequence we appeared in a different place in the overworld, we restarted the server and tried to enter again from the first portal in the overworld but this time we appeared further on in the TF.

### Additional Details

We play in a server of exaroton with 6RAM, 46 (all work properly except for this error) and we are two players

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Legofano** [comment]
https://mclo.gs/5duV7ZZ 
The register when I start the server

**Comment by Legofano** [comment]
https://mclo.gs/S45M6r6
And the register when I enter I the portal and kick me because the time of wait is out.
I have to restart the server.

**Comment by Tamaized** [comment]
Those logs dont show that anything is wrong, maybe a client log has some helpful information, regardless 1.16 is no longer supported.
