### ISSUE TITLE
[1.19.1] Blocks cannot be placed on fiddleheads or mayapples

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1592]
### Forge Version

42.0.1

### Twilight Forest Version

4.2.1239

### Steps to Reproduce

1. Attempt to place a block on a fiddlehead or mayapple, same as you would on vanilla grass (the plant, not the block)

### What You Expected

In vanilla when you attempt to place a block on a piece of grass, it destroys the plant and replaces it with the block, and I expected this to also be the case here. 

### What Happened Instead

This does not occur; the block is placed on top or to the side without destroying the plant. As they are harvested in the same way as grass and otherwise behave the same, I believe this is an inconsistency. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
I think fiddleheads or mayapples are actually supposed to be more akin to flowers, which cannot be replaced by placing a block on them, so this is indented behavior?

**Comment by EvergreenSystems** [comment]
I guess that's possible, though a bit unintuitive as they otherwise behave as grass (you need shears to pick them up and they share a similar color palate)

**Comment by GizmoTheMoonPig** [comment]
I decided that mayapples should act more like flowers in terms of not being replaceable, but fiddleheads can now be replaced like grass. Even though both still need silk, I don't feel like mayapples should act like grass completely. Hope this works
