### ISSUE TITLE
Dispensers can't light up Nether Portals.

### ISSUE THREAD

**Issue by StanTheMachinegun** [TeamTwilight/twilightforest#1593]
Forge version:  40.1.69
Twilight Forest version: 1.18.2-4.1.1220

Steps to reproduce:
1. Place an unlit nether portal (obsidian frame)
2. Place dispenser with flint & steel placed inside facing the opening of the portal frame (but not mid-air)
3. Activate through redstone (button, lever & pressure plate tested)
4. Watch particles appear, but portal not lighting up. No durability is used up on flint&steel
What I expected to happen:

Dispensers do not ignite nether portals with flint & s
![2022-08-08_21 45 13](https://user-images.githubusercontent.com/4107735/183501612-d2d137c5-9b1d-4704-a8c5-e9ef59adf9e5.png)
teel, hence "toggle-type" nether portals are not possible.

What happened instead:

The nether portal is not lit up. Curiously, bucket and AFAIK anything else is being dispensed.
Clean install with only Forge and TF. Tried different orientations (north-south-etc), different sizes

**Comment by GizmoTheMoonPig** [comment]
I do unfortunately know about this, and ive fixed it in 1.19. I wont be backporting the fix since support for 1.18 has been dropped and I dont see this as a super serious issue.
