### ISSUE TITLE
Uncrafting table doesn't leave items behind in the grid

### ISSUE THREAD

**Issue by Toastr125** [TeamTwilight/twilightforest#1594]
### Forge Version

43.0.0

### Twilight Forest Version

4.2.1376

### Steps to Reproduce

Use the uncrafting table to craft an item that would leave things behind in the crafting grid (for example, a cake leaving behind empty buckets)

### What You Expected

Certain items would be left in the crafting grid

### What Happened Instead

Nothing was left in the crafting grid, the items were just deleted

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Fixed in 7f50e67fb6da7091258ad7d902d5195cbf57bb7d
