### ISSUE TITLE
Infinite oak wood glitch (self contained within Twilight Forest

### ISSUE THREAD

**Issue by NCL68** [TeamTwilight/twilightforest#1595]
### Forge Version

40.1.51

### Twilight Forest Version

4.1.1172

### Steps to Reproduce

When you put a Giant Log in the crafting table you get 4 stacks of Oak Planks, which is normal.
However, if you put a single stack of Oak Planks into the uncrafting table you can take a Giant Log out, thereby generating 3 stacks of Oak Planks for a grand total of 1 level.

### What You Expected

I probably shouldn't be able to take a Giant Log out for only 1/4 of its material

### What Happened Instead

Infinite Oak

### Additional Details

I think the only ways to fix this would be to remove the giant log as a result when uncrafting, or allowing the input slot to overflow past 64 items

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
while this isnt that big of an issue in my eyes, I did fix this in 1.19 at one point. I thought it was in 1.18 too but oh well
