### ISSUE TITLE
1.19.0 compatibility? [Suggestion] 

### ISSUE THREAD

**Issue by mimi-min** [TeamTwilight/twilightforest#1596]
### The Suggestion

Hello,

I'm really excited to see that you released this for 1.19.1-2! 

However, I'm running 1.19, so Forge says it's an incompatible version... I'm wondering if this is an easy fix, or is it more complicated than it seems?

Either way, thank you for your hard work!

### Why Should It Be in the Mod?

(I want to add it to my server!)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
We can't run the mod on 1.19. Vanilla made a change to music discs that we need to account for so it's not backwards compatible, and keeping a 1.19 version as well as the .1/.2 one is the same as supporting 2 versions basically, which won't happen. Hope you understand.

**Comment by mimi-min** [comment]
Aww, that's a bit sad but i understand. Thank you for your response!
