### ISSUE TITLE
close me

### ISSUE THREAD

**Issue by Fitonissossas** [TeamTwilight/twilightforest#1597]

**Comment by Tamaized** [comment]
This is a forge bug, you cant not use old worlds, you must use a new world.
See https://github.com/MinecraftForge/MinecraftForge/issues/8915

**Comment by Fitonissossas** [comment]
> This is a forge bug, you cant not use old worlds, you must use a new world. See [MinecraftForge/MinecraftForge#8915](https://github.com/MinecraftForge/MinecraftForge/issues/8915)

you mean create a new world from zero?
there isn't any way to save my world?

**Comment by Tamaized** [comment]
Correct.

**Comment by Fitonissossas** [comment]
> Correct.

c'mon the is a way to solve it

**Comment by Fitonissossas** [comment]
> Correct.

actualy i tought to put the immersive portal mod to solve it.
only a problem... IT IS TOO OLD and a 1.18.2 version don't exist

**Comment by TelepathicGrunt** [comment]
If you have NBTExplorer, a way to try and fix the issue is to make a new world, open its level.dat file, go to the WorldGenSettings, copy the nether and end, and paste them into your broken world’s level.dat file

**Comment by Fitonissossas** [comment]
> If you have NBTExplorer, a way to try and fix the issue is to make a new world, open its level.dat file, go to the WorldGenSettings, copy the nether and end, and paste them into your broken world’s level.dat file

where can i download nbt explorer

**Comment by Fitonissossas** [comment]
ok, i have it

> If you have NBTExplorer, a way to try and fix the issue is to make a new world, open its level.dat file, go to the WorldGenSettings, copy the nether and end, and paste them into your broken world’s level.dat file

**Comment by Fitonissossas** [comment]
> If you have NBTExplorer, a way to try and fix the issue is to make a new world, open its level.dat file, go to the WorldGenSettings, copy the nether and end, and paste them into your broken world’s level.dat file
how can i copy that dimension thing?

**Comment by TelepathicGrunt** [comment]
You can click on them, ctrl+C to copy, and then ctrl+v to paste in the other world‘s level.dat opened in another NBTExplorer window

**Comment by Fitonissossas** [comment]
> You can click on them, ctrl+C to copy, and then ctrl+v to paste in the other world‘s level.dat opened in another NBTExplorer window

actualy i discovered that the end and the nether files don't exist!!!

**Comment by Fitonissossas** [comment]
> You can click on them, ctrl+C to copy, and then ctrl+v to paste in the other world‘s level.dat opened in another NBTExplorer window

how can i add the end and the nether files?

**Comment by TelepathicGrunt** [comment]
Thats what I am describing. Take the nether and end entries from the fresh world’s level.dat file and put them into the level.dat file that is missing them.

**Comment by Fitonissossas** [comment]
ok i did it now i will check iif it work

**Comment by Fitonissossas** [comment]
> Thats what I am describing. Take the nether and end entries from the fresh world’s level.dat file and put them into the level.dat file that is missing them.

ok i did it now i will check iif it work

**Comment by Fitonissossas** [comment]
> Thats what I am describing. Take the nether and end entries from the fresh world’s level.dat file and put them into the level.dat file that is missing them.

it worked, thanks man.
