### ISSUE TITLE
[Suggestion] Uncrafting Table Config Addition (Disable experience requirement)

### ISSUE THREAD

**Issue by KuwuroUsagi** [TeamTwilight/twilightforest#1601]
### The Suggestion

The ability to disable the use of experience with the table while maintaining it's recipes would be a nice toggleable option for server administrators

### Why Should It Be in the Mod?

It promotes adventuring in the twilight forest to find the feathers to be used in the map core to create the table, but without the pain of needing to set up an exp farm/mob farm. More twilight gameplay in modpacks used by smaller more casual groups who don't want to delve too deeply into the various mechanics of spawners and exp storage and any other options out there that the uncrafting table would require.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
added in 0a52ba8472d205d16ff413f3dcf936c21f7845d6. There are 2 separate config options for disabling the uncrafting cost and the repairing/recrafting cost. Thank you for the suggestion!

**Comment by SparkyTD** [comment]
Would it be possible to backport this one feature to the 1.19.x branch? I could try to set up a PR replicating 0a52ba8 if you're okay with meging it.

**Comment by Tamaized** [comment]
Aug 2022 is 1.19...
https://github.com/TeamTwilight/twilightforest/commits/1.19.x?after=fd45f78a7979c99ec757cd5012d6b63517da820b+384&branch=1.19.x&qualified_name=refs%2Fheads%2F1.19.x
