### ISSUE TITLE
Twilight forest 1.19.2 doesn't work with Biomes o' plenty mod

### ISSUE THREAD

**Issue by kralrindo** [TeamTwilight/twilightforest#1602]
### Forge Version

43.0.19

### Twilight Forest Version

4.2.1381

### Client Log

https://gist.github.com/kralrindo/4dc56d8a451cedd20b9e847c84b1cacf

### Crash Report (if applicable)

https://gist.github.com/kralrindo/6c58a47a1d1319824b7d187a90a47a87

### Steps to Reproduce

BiomesOPlenty-1.19-17.0.0.143
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.7
TerraBlender-forge-1.19.2-2.0.1.125
twilightforest-1.19-4.2.1381-universal

Twilight forest crashes when I add biomes o plenty, they work fine if I load them alone, game doesn't even launch and I get:

The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: The Twilight Forest (twilightforest) encountered an error during the common_setup event phase
Exit Code: -1

### What You Expected

I expect them to work together, both of them are amazing mods and I hope this issue is fixable

### What Happened Instead

Launch crash

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
You grabbed the wrong BoP version. Use this one instead: https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/files/3927361

Since BoP adds music discs, the normal 1.19 version won't work on 1.19.2 since Mojang made a change to them. We had to deal with this same issue, and that's why the mod won't run on 1.19

**Comment by kralrindo** [comment]
ah thank you so much, no idea how I didn't see there is a 1.19.2 version for BoP, and didn't notice issue was BoP because it works alone fine

have a great day
