### ISSUE TITLE
Head is visible in First Person whilst Twilight Forest (Forge) is installed with Better Combat by Daedelus

### ISSUE THREAD

**Issue by chronosacaria** [TeamTwilight/twilightforest#1608]
### Forge Version

40.1.73

### Twilight Forest Version

4.1.1220

### Client Log

https://gist.github.com/chronosacaria/30008b67dd6ee5f3929ddbcd78ff1045

### Steps to Reproduce

1. Install Better Combat by Daedelus
2. Install Twilight Forest
3. Load game and swing weapon
4. See back of head

### What You Expected

That the head should not come into view whilst attacking in first person

### What Happened Instead

The head is shown when attacking in first person

### Additional Details

> This issue needs to be fixed by Twilight forest, their Trophy renderer causes it.
> There is nothing I can do to fix it.
> An example of the bugfix already exists in the Fabric port of their project.
This is from https://github.com/ZsoltMolnarrr/BetterCombat/issues/60

This issue was opened up by the request of another user who does not have GitHub

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
I fixed this already, it's in 1.19 173c04088ea8c0085b7eecea6a02b1ec94168f03

1.18 isn't receiving updates anymore.

**Comment by chronosacaria** [comment]
Oh, fantastic! I didn't realise it had been fixed with 1.19. Thanks for the update! I'll pass that along to the person who mentioned the issue :)
