### ISSUE TITLE
Deny BlockEvent.BreakEvent on maze blocks and made bedrock?

### ISSUE THREAD

**Issue by ProsperCraft** [TeamTwilight/twilightforest#161]
Currently mods can bypass maze blocks and break them, in the past 1.7.10 versions Blood magic bound picks were used to abuse the maze blocks with right click.  

Right now I am working with a mod called Prefab that has premade structures you can place in the world, it has a built in block to the user if the BlockEvent.BreakEvent is not allowed and I wondered if you could block it in mazes?

Steps to reproduce:
1. click with a house, and it obliterates the maze blocks.

What I expected to happen:
the event is denied and the house is not allowed to be placed.

What happened instead:
https://github.com/Brian-Wuest/MC-Prefab/issues/61#issuecomment-326252586

**Comment by liach** [comment]
I don't think that maze blocks are unbreakable.

**Comment by Andromander** [comment]
Maze Blocks can be broken, but the time taken by a normal pickaxe takes a long time. This is because of how one can obtain a Mazebreaker pickaxe in the maze, and also because said pickaxe is used to create shortcuts. It's less Maze Blocks are unbreakable more it takes a long time to break.
