### ISSUE TITLE
[1.18] [Unplayable] [Server] Low TPS while players enter Knight Phantom dungeon

### ISSUE THREAD

**Issue by Cixon** [TeamTwilight/twilightforest#1610]
### Forge Version

1.18.2 Server - 40.1.73

### Twilight Forest Version

latest - 4.1.1397

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

There is no steps.

### What You Expected

A comprehensive lag-free experience when exploring/defeating dungeons for online entertainment.

### What Happened Instead

![tps](https://user-images.githubusercontent.com/69068153/187014456-8c9055cc-7d4c-4c39-b49b-90a73fc54ede.png)

Alone on the server. 7GB of free memory.

### Additional Details

**DISCLAIMER(s):**
-The results above are from 1 player (me). There was no one else on the server.
-The server is hosted via ReviveNode which is a server hosting platform on 7GB. No special server parameters.
-I do not utilize any other mods aside from InControl that would change entity behavior and some minor performance enhancers like spark for example.

**Context:**
I'm not entirely sure what could cause this but if you ask me I think it could just be the way the knight phantom was coded and his goons. It's possible there's a memory leak some where that wasn't patched for multiplayer play and if this is the case, it could very well be infecting other dungeon bosses as well.

**Possibly a dupe of** #1607 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
since you have spark on your server, could you make and send us a profile report? We never had issues like this on our testing server so I assume there's some sort of other mod doing something here.

**Comment by Cixon** [comment]
sure thing, one moment

**Comment by Cixon** [comment]
> since you have spark on your server, could you make and send us a profile report? We never had issues like this on our testing server so I assume there's some sort of other mod doing something here.

https://spark.lucko.me/EKkhcMahyR

**Comment by GizmoTheMoonPig** [comment]
oh do you only have spark running on the client? im gonna need a server report to help out. TPS lag is gonna be on the server, so a client report wont help very much

**Comment by Cixon** [comment]
> oh do you only have spark running on the client? im gonna need a server report to help out. TPS lag is gonna be on the server, so a client report wont help very much

my apologies.
https://spark.lucko.me/ZGrunEsT1Z

**Comment by GizmoTheMoonPig** [comment]
alrighty, it looks like some datapack or even a mod is using the /execute command quite excessively, and the testing for entities bit is taking up 89% of the resources your server is using. Any ideas what may be doing this? We certainly dont use this anywhere in the mod so im 99% sure we arent at fault here.

**Comment by Cixon** [comment]
> alrighty, it looks like some datapack or even a mod is using the /execute command quite excessively, and the testing for entities bit is taking up 89% of the resources your server is using. Any ideas what may be doing this? We certainly dont use this anywhere in the mod so im 99% sure we arent at fault here.

can u provide me with this line? maybe i can identify it

**Comment by Drullkus** [comment]
Your problem is a Datapack that's being run every single tick. Your performance issue is coming from a command that's polling every single entity in the world and changing their SaveData

![image](https://user-images.githubusercontent.com/5010174/187017231-2f8567ef-5aa6-43c8-b2b9-1424ea7989d2.png)

What datapacks do you have installed? It would be a good idea to disable those that have commands running every single tick

**Comment by Cixon** [comment]
> Your problem is a Datapack that's being run every single tick. Your performance issue is coming from a command that's polling every single entity in the world and changing their SaveData
> 
> ![image](https://user-images.githubusercontent.com/5010174/187017231-2f8567ef-5aa6-43c8-b2b9-1424ea7989d2.png)
> 
> What datapacks do you have installed? It would be a good idea to disable those that have commands running every single tick

maybe? it messes with skeletons
https://www.planetminecraft.com/data-pack/vanilla-expansion-datapack/

**Comment by Cixon** [comment]
i’ll do some troubleshoot but ima close this issue for now. i’ll re-open in the event i cannot find the problem. thank you for your time!

**Comment by Drullkus** [comment]
That explains why the Druid Skeletons are showing up in the callstack. Make a copy of your world without the datapack and see if the lag persists
