### ISSUE TITLE
Dark Forest Doesnt Renders and Crashes game

### ISSUE THREAD

**Issue by RetepBoi** [TeamTwilight/twilightforest#1611]
### Forge Version

36.2.9

### Twilight Forest Version

4.0.546

### Client Log

https://gist.github.com/RetepBoi/455bf9a509495ed795b41d6d7cd05c11

### Crash Report (if applicable)

https://gist.github.com/RetepBoi/d0aa08f6b16b03904b369f52bc347eb1

### Steps to Reproduce

1. Load into Twilight Forest
2. Find Dark Forest Biome
3. Walk into Biome
4. Crash

### What You Expected

For the biome to render correctly like everything else and function as intented.

### What Happened Instead

When game renders dimension everything else will render correctly but Dark Forest Biomes appear similar to un-rendered chunks where you can see below ground but all above ground is invis.

See images.

![image](https://user-images.githubusercontent.com/112253265/187028400-ac73e3db-bc88-4827-8db8-b51cd214e7bc.png)
![image](https://user-images.githubusercontent.com/112253265/187028525-ff277044-3885-4292-8630-d737bf8425ad.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
If I recall correctly, this is an issue caused by unofficial Forge ports of Sodium (these go under various names of elements on the periodic table).

**Comment by RetepBoi** [comment]
I don’t understand half of what you just said but how do I fix it because I cant progress the quest line until I resolve it.

**Comment by Drullkus** [comment]
Try removing rubidium and see if that fixes the crash

**Comment by RetepBoi** [comment]
> Try removing rubidium and see if that fixes the crash

Apologies for my incompetence but how do I go ahead removing it, I cannot find it under the mods list ingame, or is it under something else?

**Comment by GizmoTheMoonPig** [comment]
remove magnesium, not rubidium. Rubidium is the 1.18 port of sodium, magnesium is the 1.16 port

**Comment by RetepBoi** [comment]
> remove magnesium, not rubidium. Rubidium is the 1.18 port of sodium, magnesium is the 1.16 port

That worked, thank you! Should I re-add it after rendering the biome or is it okay to keep it out the pack? Unsire what will break if its not re-enabled?

**Comment by GizmoTheMoonPig** [comment]
I would recommend keeping it out of the pack. Its just a performance mod, but it seems like it was ported rather poorly
