### ISSUE TITLE
[1.18.2][Portal Issue] Underground portals cannot correctly link and randomly redirect to wrong positions

### ISSUE THREAD

**Issue by SodiumZH** [TeamTwilight/twilightforest#1613]
### Forge Version

40.1.68

### Twilight Forest Version

4.1.1184

### Steps to Reproduce

Two manually-created portals with identical XYZ location cannot link correctly.

I tried to link two portals from overworld to TF. The overworld one was underground in an ocean biome. The TF one was in the labyrinth. The two portals' XYZ position was _exactly identical_ and both was manually created. 
This led to unstable locating when I tried going through the portals. 

To reproduce:
1) Find a labyrinth and create a portal inside. Set down its XYZ position. (In my case Y=-14.)
2) Find the position of the portal above in the overworld (usually underground), and create a portal at the identical position.
3) Go through the above 2 portals.

### What You Expected

The two portals should be linked. When I get into one, I should be sent to the other one, just like the Nether portals do.

### What Happened Instead

Several random issues have ever happened:

1) Portal in the Twilight Forest ("TF portal" below) created a new portal on the surface of the ocean.
2) Portal in the overworld ("overworld portal" below) created a new portal outside the labyrinth in the twilight swamp.
3) When I manually broke the generated portals, they may still send me to the broken portal without generating a new one.
4) The TF portal sent me to the sea level above the position of the overworld portal, without any new blocks generated.
5) Rarely the overworld portal sent me directly above the TF portal, and I was sent back immediately to the overworld that the TF wasn't shown at all. (This case happened only once for me, so I'm not sure if it can be reproduced.)
6) Several tests through the same portal could lead to different positions, sometimes correctly to the other one, and sometimes with the above issues happening.
7) Different portal blocks in a single portal could lead to different results.
8) After breaking one of the portals and then remaking it, the results may change.
9) Block changes near the portal may change the results.

### Additional Details

#1459

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SodiumZH** [comment]
An additional case:
After filling the target positions with solid blocks, the portal may still teleport me to the former position into solid blocks.

**Comment by SodiumZH** [comment]
After some additional tests, I found that a portal on the ground may also lead to issues above, but the probability is much lower.

**Comment by SodiumZH** [comment]
A save data with the issue 7 is available. If anyone needs the sample, please contact me to take it. (Difficult to upload as it's 3GB large)

**Comment by GizmoTheMoonPig** [comment]
linking this back to #1459 just to keep the issue tracker clean. We're very aware of all of the portal issues, and I hope we can completely rewrite the logic someday.
