### ISSUE TITLE
1.18.2 Magical Map bug with item frames.

### ISSUE THREAD

**Issue by KodYazanDruid** [TeamTwilight/twilightforest#1615]
### Forge Version

40.1.74

### Twilight Forest Version

4.1.1397

### Crash Report (if applicable)

No need for log

### Steps to Reproduce

Step 1: Craft and use magic map.
Step 2: Place it on item frame.
Step 3: Take it from the item frame and it is full blank doesn't show anything but still rendering in the item frame.

### What You Expected

Working as intedted instead of full blank page.

### What Happened Instead

It renders full blank map instead of the regular magic map.

### Additional Details

I have rubidium, rubidium extras as performance mods.
![2022-08-31_00 18 46](https://user-images.githubusercontent.com/45048634/187545200-444498c3-fc9e-4569-9428-7e16f79e6154.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Duplicate #1505 #1545
