### ISSUE TITLE
[1.18.2] Mod Interaction Crash. Twilight Forest Swarm Spider mob vs. Apoth Spawner

### ISSUE THREAD

**Issue by enigmaquip** [TeamTwilight/twilightforest#1619]
### Forge Version

40.1.74

### Twilight Forest Version

4.1.1397

### Crash Report (if applicable)

https://mclo.gs/ZXJ8RkD

### Steps to Reproduce

Use a mob spawn egg of a swarm spider on an apotheosis spawner

### What You Expected

mobs to spawn

### What Happened Instead

server crashed on attempted spawn of mob

### Additional Details

Apotheosis Dev had a suggested fix here
<https://github.com/Shadows-of-Fire/Apotheosis/issues/648>

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
fixed in 1.19. We're done with backports so this wont make it to 1.18

**Comment by Shadows-of-Fire** [comment]
Linking https://github.com/Shadows-of-Fire/Apotheosis/issues/669 for reference
