### ISSUE TITLE
Branch ready with Bugfixes for plants and huge canopy trees from MC 1.2.5 Version

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#162]
Forge version: 13.20.0.2309
Twilight Forest version: Forked from branch 1.11.2 - d3bbb9c

Hello TeamTwilight,

I created a bugfix for Version 1.11.2 where plants like moss patch or torchberry plants can't be replanted.  A few improvements for vine generation for the enchanted forest was done too, to make them hang down. 

Also I ported 2x2 canopy trees from an old twilight forest version for MC 1.2.5 . Seems like they were removed while the hollow trees were refactorized to be a structure. For this I used a trick to allow recursive calls to the biome decorators. This is needed, because such trees are too wide and thus may invoke chunk generations during the decoration process.
![2017-09-05_12 03 12](https://user-images.githubusercontent.com/21110130/30056329-8a72076c-9232-11e7-986e-bbbefdbe82f3.png)

Do you wish my branch to be uploaded?

Regards,
Avatair

**Comment by Andromander** [comment]
Any feature that is a modification of a file can be submitted as a Pull Request. I believe that vines and moss patches may have been dealt with, but the current version hasn't fixed Torchberries. If you can submit the modifications as a Pull Request, it can be taken into consideration, and conflicts can be detected if any exist.
Also, can this apply to 1.12.x? At this current stage, I think 1.11.2 is no longer being worked on.

**Comment by ghost** [comment]
I have no rights to upload a branch to be able to make a pull request.

**Comment by ghost** [comment]
A migration of the code to 1.12 should be possible with minimal efforts.

**Comment by Tamaized** [comment]
Why 1.11.2, we're going straight to 1.12.1, also you don't need to upload to our repo to make a pull request, you can use your own fork.

**Comment by ghost** [comment]
Thanks. I'm new to github, but good to know there is such feature.

I'm playing on 1.11.2  and develop mods on it. But my changes should be migrateable easily.

**Comment by williewillus** [comment]
seeing as this issue isn't really an issue, I'm closing it now

the changes will be accepted if they target the `1.12.x` branch and are submitted via a PR

I look forward to your PR :D 

we can discuss the technical aspects once the code is shown
