### ISSUE TITLE
Foxes can't be bred with torchberries

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest#1628]
### Forge Version

43.1.3

### Twilight Forest Version

4.2.1392

### Steps to Reproduce

1. Look in TF's generated data files for a `data/minecraft/tags/items/fox_food.json`, the vanilla tag that is supposed to contain all berries so that they can be used to breed foxes.
2. Observe that the tag is not there, lol.

### What You Expected

TF would add torchberries to the `fox_food` item tag so that they can be used to breed foxes, like other berries.

### What Happened Instead

TF does not add torchberries to the tag needed for them to be usable to breed foxes.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Just because it's a berry doesn't mean a fox eats it or that it's particularly healthy for a fox.

There are no foxes in twilight forest so this feature makes no sense.
