### ISSUE TITLE
Peacock Feather Fan does not set off Sculk Sensors

### ISSUE THREAD

**Issue by Toastr125** [TeamTwilight/twilightforest#1631]
### Forge Version

43.1.2

### Twilight Forest Version

4.2.1392

### Steps to Reproduce

1. Find or place a sculk sensor
2. Use a peacock feather fan (to blow away entities or to boost your jump, neither will trigger it)

### What You Expected

The sculk sensor would take notice of the vibration

### What Happened Instead

The sculk sensor didn't get set off, even when I blew a gust directly towards it

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Toastr125** [comment]
Just realized I didn't test it when standing. It triggers when you stand, but if you use the fan while crouching it doesn't trigger

**Comment by GizmoTheMoonPig** [comment]
intended, using items in the base game works the same way. Try crouching and using a shield, the same thing will happen
