### ISSUE TITLE
[1.18.2] Magic Map copying issues (stacking and display)

### ISSUE THREAD

**Issue by SodiumZH** [TeamTwilight/twilightforest#1633]
### Forge Version

40.1.68

### Twilight Forest Version

4.1.1184

### Steps to Reproduce

1. Create a magic map and open it in the TF
2. Create another empty magic map and copy the former one on the crafting table. Divide the stacked two map and then try stacking them again
3. Place an item frame and put one of the maps above on it.
4. Try several times ending and starting the game. Check the both maps. 

### What You Expected

On step 2, the map copies should be able to stack again.
On step 4, the map on the item frame should display its content as the overworld maps do.
At any time, the map on hand should display the biomes (colors) and the structure icons.

### What Happened Instead

On step 2: 
The two copies can be taken out of the crafting table as the stacked form, but after they're divided, they cannot stack again.
The stacked maps cannot be placed onto the anvil. Only one of the maps is placed on the anvil, so the maps cannot be renamed as a stack.

On step 4, display errors below may randomly occur:
1. Sometimes the map on the item frame may display as the map icon instead of the map content. At this time, the copy of that map on the hand displays only biomes without structure icons.
2. Sometimes the map on the hand doesn't display anything but only a piece of empty paper.
After restarting (save and load the save data, no need to reboot the game), the display issues may disappear and occur randomly.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this has been fixed in 1.19. 1.18 is no longer supported, so there wont be any backports
