### ISSUE TITLE
Friend gets kicked from game when playing twilight forest together

### ISSUE THREAD

**Issue by Isabelke2** [TeamTwilight/twilightforest#1634]
### Forge Version

1.19.2

### Twilight Forest Version

1.19.2

### Steps to Reproduce

Use the mod in LAN with another person.

### What You Expected

To play the mod with my friend.

### What Happened Instead

Hi! me and my friend was playing twilight forest through LAN and everything went alright for a while until we encountered the NAGA snake. My friend got kick from the game repeatedly until I killed the snake and we left the area. Now we are exploring the dark forest, trying to find the stronghold and the same thing happened. It seems to only happen in specific areas of the forest. We both have the same forge version and version on the mod.

### Additional Details

![unknown](https://user-images.githubusercontent.com/106089602/190503830-99d3c53c-0cdc-4bef-aab1-978d48c7bc21.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
This issue has been fixed as of Forge 43.1.53.
