### ISSUE TITLE
Crash on mod spawn from command

### ISSUE THREAD

**Issue by VallenFrostweaver** [TeamTwilight/twilightforest#1635]
### Forge Version

40.1.68

### Twilight Forest Version

1.18.2-4.1.1184-universal

### Crash Report (if applicable)

https://gist.github.com/VallenFrostweaver/d9567c124bc855d7f3e3bf0703df7900

### Steps to Reproduce

1. On a server, I am running CCI (Content Creator Integration) mod to produce a mount for myself and another player to be spawned under us (forcing us to mount the entity) using the SwapThings mod using this command:
2. Be in the nether when this command is used or triggered.
3. The other player and eventually myself are both put into a state of inactivity on the server and can't effect anything. Re-logging will result in either another crash or the sudden arrival of the "mount" as described above and possibly more crashes.

### What You Expected

The players described as above to be put on a mount with no crashing or issues.

### What Happened Instead

The other player and eventually myself are both put into a state of inactivity on the server and can't effect anything. Re-logging will result in either another crash or the sudden arrival of the "mount" as described above and possibly more crashes.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Closing this one as it is superseded by #1636.
