### ISSUE TITLE
Minecraft 1.18.2 crashes instantly when trying to open twilightforest chest

### ISSUE THREAD

**Issue by timm-u** [TeamTwilight/twilightforest#1637]
Forge version:  40.1.76
Twilight Forest version: twilightforest-1.18.2-4.1.1397-universal
Link to crash log: https://mclo.gs/1Wu760S

Steps to reproduce:
1.get  atm 7 sky modpack v1.0.6 (you can try with rubidium/rubidium extras or without, crashes both ways)
2. go to twilight forest(duh)
3.  go to the lich castle.. kill the mob and try to open the loot chest
4. Game instantly crashes with the following log

What I expected to happen:
Game not to crash, chest to open normally and me getting the loot from that chest.

What happened instead:
Game crashed instantly when i right clicked the chest.

**Comment by timm-u** [comment]
https://mclo.gs/11vDm91 maybe this log also helps

**Comment by timm-u** [comment]
This crash also happened now when scrolling JEI(looking up recipes).
Meanwhile modpack got updated to atm1.0.7, i am running it on macbook pro m1 if that also matters somehow

**Comment by timm-u** [comment]
https://mclo.gs/9Yt6J4s new log

**Comment by timm-u** [comment]
Talking in atm7-sky discord and diagnosing it we came into conclusion that this issue is probably related to twilightforest shader being incompatiable with new lwjgl. Basically M1 (apple chips, also m1 pro/max, m2 etc) all require the new lwjgl to work. 
My setup is: Apple macbook pro m1 8gb 512gb with java 17.0.4.1. (this is for apple aarch64) - silicon. And also i am using manymc which gets the right assets so game runs just fine. Just this mod seems to have incompatibility. Maybe it is possible to bypass it or make neccessary changes so this would work :)

**Comment by Tamaized** [comment]
Does looking at any shader bag from Immersive Engineering also crash or is it strictly the Twilight Forest ones.

**Comment by Tamaized** [comment]
Try this dev build, I have no way of testing to see if this worked or not.
https://artprodcus3.artifacts.visualstudio.com/Abaabfa6c-deea-4587-ba05-c308c2597b7a/1ef09d39-06cf-41fa-ad98-7258b70c2a72/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3RlYW10d2lsaWdodC9wcm9qZWN0SWQvMWVmMDlkMzktMDZjZi00MWZhLWFkOTgtNzI1OGI3MGMyYTcyL2J1aWxkSWQvMTk1OC9hcnRpZmFjdE5hbWUvUmVsZWFzZQ==0/content?format=file&subPath=%2Ftwilightforest-1.18.2-4.1.1422-universal.jar

**Comment by mwindsor-beoped** [comment]
@Tamaized  - that worked for me!  Same setup as previous reporters Macbook Pro M1 (Max), also using ManyMC so with the new lwijgl.

Thanks a bunch :)

BTW, Shader bags hadn't caused a crash for me (before or now).

**Comment by Tamaized** [comment]
I pushed the build to CurseForge. It'll be live shortly.

**Comment by timm-u** [comment]
I can also confirm that this issue is solved. Big thanks!
