### ISSUE TITLE
[Suggestion] Make Hydra Trophies Open and Close their Mouths like Dragon Heads

### ISSUE THREAD

**Issue by PraseodymiumSpike** [TeamTwilight/twilightforest#1638]
### The Suggestion

When a Hydra Trophy is under the effect of Redstone Power, its mouth should open and close like Dragon Heads' mouths do. Similarly, when a Hydra Trophy is on an Entity's Head, and it is walking, its mouth should open and close.

[relevant animation](https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/Dragon_Head.gif/revision/latest?cb=20200125194556)

relevant section of Minecraft Wiki: "The dragon head opens and closes its mouth repeatedly like the [ender dragon](https://minecraft.fandom.com/wiki/Ender_dragon) when placed and powered by redstone. The same animation occurs when worn by a (horizontally) moving player, zombie, skeleton, or [armor stand](https://minecraft.fandom.com/wiki/Armor_stand) (note: the animation does not play if the NoGravity tag is set to 1)"

### Why Should It Be in the Mod?

The Hydra Trophy looks very much like the Dragon Head. Therefore, it makes sense that it would have a similar effect.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
I've already said I'm not doing this countless times, I don't want to copy the dragon head. Please stop asking.
