### ISSUE TITLE
Ur-Ghast Trophy Tentacles not Rendering when "Body" is Off-Screen

### ISSUE THREAD

**Issue by PraseodymiumSpike** [TeamTwilight/twilightforest#1639]
### Forge Version

43.1.2

### Twilight Forest Version

twilightforest-1.19-4.2.1392-universal.jar

### Steps to Reproduce

1. Place the Ur-Ghast Trophy on a wall.
2. Look at it at an angle such that its tentacles should be visible, but the main cube "body" shouldn't be.

### What You Expected

The tentacles are visible.

### What Happened Instead

The tentacles are not rendered.

### Additional Details

I am not sure if this occurs with the actual Ur-Ghast Entity or just the trophy. I am also not sure whether it occurs with the Ur-Ghast Trophy on another Entity's Head.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
That's how culling works
