### ISSUE TITLE
Goat ram attack triggers fiery armor

### ISSUE THREAD

**Issue by Toastr125** [TeamTwilight/twilightforest#1640]
### Forge Version

43.1.2

### Twilight Forest Version

4.2.1392

### Steps to Reproduce

Get a goat to use its ram attack on you while you're wearing fiery armor

### What You Expected

Nothing to happen to the goat

### What Happened Instead

The goat was set on fire

### Additional Details

Thorns doesn't trigger on goat ram attacks, so I figured the same would be true of fiery armor

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Fire react and chill aura should work EXACTLY the same as thorns so I'll have to see what's going on here

**Comment by Toastr125** [comment]
I didn't test it with fire react, only with fiery armor. IDK if that makes a difference.

**Comment by GizmoTheMoonPig** [comment]
Oh that would make sense then, the builtin armor effects work a bit differently. I'll get to this when I have a chance

**Comment by GizmoTheMoonPig** [comment]
looked into this further, and thorns not working on goats is a confirmed vanilla bug. https://bugs.mojang.com/browse/MC-223301 . Conflicted on whether I should change anything or not

**Comment by PraseodymiumSpike** [comment]
I think you should not change it as it is technically an attack, so the fire effect should be applied.

**Comment by Tamaized** [comment]
Closing as this is a vanilla bug.
