### ISSUE TITLE
[1.19.2] Transformation core biomes reset on world reload if not updated

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1645]
### Forge Version

43.1.25

### Twilight Forest Version

4.2.1421

### Steps to Reproduce

1. Use a transformation core to change the surrounding biome
2. If a chunk changed does not have any changes made post-generation (no placed blocks, etc) the biome will reset upon world close-reload

### What You Expected

Biomes should stay set once changed

### What Happened Instead

As above, if a chunk has not had any post-generation changes made it will lose its re-assigned biome upon world reload and revert to its original biome

### Additional Details

Discovered on the server build version at the time, on the orders of Tama

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Fixed in ccb52c551a734d337ef545e3a31eeed166c7e4d6
