### ISSUE TITLE
Walking on Powder Snow with Arctic Boots doesn't give the advancement

### ISSUE THREAD

**Issue by Toastr125** [TeamTwilight/twilightforest#1648]
### Forge Version

43.1.25

### Twilight Forest Version

4.2.1421

### Steps to Reproduce

1. Put on arctic boots
2. Walk on powder snow

### What You Expected

I would get the vanilla advancement "Light as a Rabbit" (description: "Walk on Powder Snow...without sinking in it")

### What Happened Instead

I did not get the advancement

### Additional Details

I didn't sink in the powder snow, so that part is still working as intended

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
the advancement is hardcoded to check for leather boots. Cant fix this.

In general, any time something of ours doesnt work with a vanilla advancement its because the criteria is hardcoded and we cant add to these advancements without overwriting them.
