### ISSUE TITLE
Slime Beetles don't drop anything

### ISSUE THREAD

**Issue by Toastr125** [TeamTwilight/twilightforest#1649]
### Forge Version

43.1.25

### Twilight Forest Version

4.2.1421

### Steps to Reproduce

Kill a slime beetle

### What You Expected

It would drop slime balls

### What Happened Instead

It did not drop anything

### Additional Details

Tested with looting 255 sword to ensure it wasn't just bad luck

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Have they ever dropped anything? If not I don't think I should change it

**Comment by EvergreenSystems** [comment]
To my knowledge they have dropped slime balls in the past

**Comment by Toastr125** [comment]
Yeah, they used to drop slimeballs. IDK how long this has been broken for, but I know they did in 1.12 and it says as much on the wiki

**Comment by GizmoTheMoonPig** [comment]
Weird. According to the loot table, they're reusing the slime loot table. I'm not currently able to look at what the slime loot table actually is but I assume slime sizes play a role here making the drop impossible. Loot table is here: https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/generated/resources/data/twilightforest/loot_tables/entities/slime_beetle.json
