### ISSUE TITLE
Lich tower "barrier" effect still active even after all players have earned "Naga Hunter" advancement

### ISSUE THREAD

**Issue by LordMonoxide** [TeamTwilight/twilightforest#165]
Forge version: 2443
Twilight Forest version: 5c9fca78f0bb2a2857247d293bb98d0ad334babf

Steps to reproduce:
1. Kill two nagas to gain the advancement
2. Try to enter a lich tower

What I expected to happen:
No "barrier" effect

What happened instead:
"Barrier" effect is still rendered

~~Note that there doesn't seem to be any ill effect from the barrier (eg. hunger from the swamp), though I'm not sure if there's supposed to be any effect in the first place.~~
It's not possible to break any block of the lich tower.

**Comment by Drullkus** [comment]
Show us a pic of your advancements screen

**Comment by LordMonoxide** [comment]
![image](https://user-images.githubusercontent.com/437657/30139117-76fb7e6e-9342-11e7-95c0-dc0880d72f40.png)

**Comment by Drullkus** [comment]
Fixed via f366628
