### ISSUE TITLE
Stuck On Optifine Detected Warning Screen

### ISSUE THREAD

**Issue by RegulusMasamune** [TeamTwilight/twilightforest#1651]
### Forge Version

Forge 43.1.32

### Twilight Forest Version

Twilight Forest-1.19-4.2.1414, +.1421

### Steps to Reproduce

Have Optifine and Twilight Forest, Try to Launch Minecraft, Get Stuck on Optifine Detected Warning Screen

### What You Expected

The warning has a 'proceed' button. I expected to be able to click on that and go to Minecrafts main menu. So I could play the game.  I can't launch the game.

### What Happened Instead

The 'proceed' button doesn't function at all.  Clicking on it does not work.  When its in small windowed form the button is light grey, and you can click on it. But nothing happens. If you maximize the size of Minecraft's window, the button turns grey and can't be clicked on.  Either way, I can't get to the main menu. Which means I can't play the game.

### Additional Details

I've seen a couple other people have this issue in the comments on Curseforge. I cant just get rid of Optifine because I have resource packs that depend on it to function. Problem is present on the two newest versions of Twilight Forest 1.19.2, as of Oct. 7, 2022
I am aware that deleting Optifine fixes this issue. I am also aware that the 1.16.5 version has the same screen, and the 'proceed' button works.  

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [ ] I have confirmed this bug can be replicated without the use of Optifine.

**Comment by Andromander** [comment]
Fixed in b13ac86. In the meantime, use the Esc key when the Proceed button activates.

**Comment by RegulusMasamune** [comment]
Thank you
