### ISSUE TITLE
[Suggestion] How to remove a portal activator?

### ISSUE THREAD

**Issue by Tw1L1ght12** [TeamTwilight/twilightforest#1653]
### The Suggestion

It's not a suggestion, but I don't know where to write

I wanted to change portal activator from diamond to soul heart (from alexs mobs)
I created a new datapack using open loader (config\openloader\data\Datapack\data\twilightforest\tags\items\portal\activator.json) with this code:
{
  "values": [
    "alexsmobs:soul_heart"
  ]
}

It worked, but didn't remove diamond as activator.

### Why Should It Be in the Mod?

Pls help

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
add `"replace": true` to the file to override the tag.

The github is not a place to ask questions like this. We use this to keep track of bugs and suggestions. If you want to ask a question like this in the future, feel free to join our discord!
