### ISSUE TITLE
[1.19.2] Mod twilightforest requires forge 43.1.23 or above

### ISSUE THREAD

**Issue by Kasardas** [TeamTwilight/twilightforest#1654]
### Forge Version

43.1.3

### Twilight Forest Version

4.2.1421

### Client Log

https://gist.github.com/Kasardas/e968fc57ae44737b3622d6c4877a6c50

### Crash Report (if applicable)

https://gist.github.com/Kasardas/504f08f498d430d3a1b4cd83aa992903

### Steps to Reproduce

1. Installed all the mods
2. Turned on the server
3. server almost immidately crashed on error listed
4. on client it works (on forge 43.1.3)

### What You Expected

to work as it should

### What Happened Instead

server crash

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
I feel like you skipped right over what the error message is asking you for.

You're attempting to play TF on Forge 43.1.3. 
The error message says it needs Forge 43.1.23. 
43.1.3 is a smaller number than 43.1.23.
You need to get the version with the bigger number in order to play. This is not a bug.

**Comment by secretmeister** [comment]
um, 43.1.3 is BIGGER than 43.1.23, unless the version numbers are weird

**Comment by jodlodi** [comment]
After the last dot, we have a 23, and a 3.
23 is a larger number than 3

**Comment by Toastr125** [comment]
I mean, the version numbers seem weird numerically but they're fine in terms of how they're interpreted here. Like, Minecraft version 1.13 comes after version 1.2, y'know?

**Comment by secretmeister** [comment]
yeah, my brain autocorrected to decimal because you know, the dot, but yeah it isnt decimal
