### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by seb17051998** [TeamTwilight/twilightforest#1657]
### The Suggestion

Hello, would it be possible to make it compatible in version 1.15.2 because I would like to make a suggestion for the Craft to exile dissonance modpack.

### Why Should It Be in the Mod?

To be compatible in 1.15.2

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
We dont do backports, especially to a version that came out almost 3 years ago. Its an insane amount of extra work for our limited manpower
