### ISSUE TITLE
[Suggestion] Not allowing Block and Chain to break blocks when having Mining Fatigue effect

### ISSUE THREAD

**Issue by SodiumZH** [TeamTwilight/twilightforest#1658]
### The Suggestion

Players with the Mining Fatigue effect will not be able to break any blocks with Block and Chain despite its Destruction enchantment.

### Why Should It Be in the Mod?

Block and Chain breaks blocks instantly, ignoring the mining speed and hardness, even when the player has a high level Mining Fatigue effect which should disable mining. In cases that breaking blocks is disabled by the Mining Fatigue effect (e.g. in the Ocean Monument), Block and Chain will be breaking the rule.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
Implemented
