### ISSUE TITLE
Tinkers' Twilight

### ISSUE THREAD

**Issue by ICantPlayThis** [TeamTwilight/twilightforest#166]
Idea posting here for reminder and brainstorm.
Twilight addon with components from Twilight resources

List as follows:
Ironwood - Reinforced
Steeleaf - Reinforced II
Timewood - Mending
Firey ingot - 10% chance to deal AoE fire damage when damaging an entity
Knightmetal - Spikey

Weapon upgrades:
Experiment 115 - 5% chance to kill you when damaging an entity (can be stacked)

Scepters can be added as a upgrade to weapons to give them abilities:
Scepter of Twilight has a charge that shoots projectiles at enemies
Zombie Scepter has a charge that spawns friendly zombies that attack only players
Scepter of Life Draining has a passive life-steal and charge that drains the health of entities to heal you for 50% of the health drained.

**Comment by ThePromisedLAN** [comment]
Correct me if I'm wrong, but ExtraTiC should work for extra tool parts (Only works in 1.7.10 and below).

**Comment by ICantPlayThis** [comment]
This isn't 1.7.10 and below.

**Comment by Zarafa04** [comment]
No the life drain would add a form of nectrotic
