### ISSUE TITLE
Crash with Curios

### ISSUE THREAD

**Issue by Nevrai** [TeamTwilight/twilightforest#1663]
My game (client) crashed seemingly randomly when I opened my inventory. It seems to be related to The Twilight Forest’s compatability implementation with [Curios](https://www.curseforge.com/minecraft/mc-mods/curios). I didn’t open my Curios inventory. I’m not sure how to reproduce this issue.

OptiFine is not installed.

This was in single-player.

**Crash report:** https://pastebin.com/raw/zZHEs4x4

### Versions

* **Minecraft:** 1.18.2
* **Forge:** 40.1.80
* **The Twilight Forest:** 4.1.1423 (latest)
* **Curios API:** 5.0.7.1 (latest)

**Comment by gglobensky** [comment]
I had a very similar crash in a single player world, no optifine but a big custom modpack.
I did not open my inventory on crash.

https://pastebin.com/bpqZuPva

**Comment by GizmoTheMoonPig** [comment]
fixed in 1.19, but I am beyond done backporting stuff to 1.18. It takes an insanely long time to open a workspace, and I dont want to keep supporting an old version of the mod

**Comment by Nevrai** [comment]
Well, that’s a shame 😕 But it’s understandable.
