### ISSUE TITLE
Hydra doesn´t takes melee damage

### ISSUE THREAD

**Issue by FruynGames** [TeamTwilight/twilightforest#1664]
### Forge Version

36.2.34

### Twilight Forest Version

4.0.870

### Steps to Reproduce

1. Spawn a Hydra
2. Try to hit him with melee weapons

### What You Expected

I supposed that i had to be able to hit him. I already know that i have to hit him on the heads

### What Happened Instead

Its immune to melee damage

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
cant replicate, even in 1.16. Hydra takes damage just fine when hit

**Comment by FruynGames** [comment]
I solved it, it was a problem with forge, i had to reinstall it.
