### ISSUE TITLE
cant go to the forrsest

### ISSUE THREAD

**Issue by ricovandenelshout** [TeamTwilight/twilightforest#1665]
### Forge Version

43.1.43

### Twilight Forest Version

4.2.1421

### Steps to Reproduce

1 i opened the portal 
2the portal was working
3 cant get in

### What You Expected

i was expected to go to the forrest

### What Happened Instead

diddnt go to the forrest

### Additional Details

i have more mods installed 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please post a log.

**Comment by Tamaized** [comment]
Log isn't really necessary here.

When touching the portal, did you actually get teleported or is no teleporting happening at all?

If not, is this on a server?

**Comment by ricovandenelshout** [comment]
> Log isn't really necessary here.
> 
> When touching the portal, did you actually get teleported or is no teleporting happening at all?
> 
> If not, is this on a server?

It's not on a server and it just doesn't do anything I  go in the portal and it does nothing

**Comment by Tamaized** [comment]
Not sure if this will work on singler player.. but you could try running the /reload command twice then leaving and rejoining the world, see if that works. If not you'll need to create a new world, this is a known vanilla bug with datapack dimensions.

**Comment by ricovandenelshout** [comment]
> Not sure if this will work on singler player.. but you could try running the /reload command twice then leaving and rejoining the world, see if that works. If not you'll need to create a new world, this is a known vanilla bug with datapack dimensions.

Okay ill try that thanks!
