### ISSUE TITLE
Bosses are not spawning in my modpack

### ISSUE THREAD

**Issue by PraiaOO** [TeamTwilight/twilightforest#1667]
### Forge Version

1.12.2 14.23.5.2859

### Twilight Forest Version

1.12.2-3.11.1021

### Client Log

<script src="https://gist.github.com/PraiaOO/431e3d602f873ef8152ab289fb699f92.js"></script>

### Steps to Reproduce

1. Enter twilight
2. Look for a boss area
3. Go to where any boss spawns
4. Find a "Naga Spawner" instead of the boss spawning

### What You Expected

I expected to find the boss to slaughter it because im playtesting my modpack but that didnt happend.

### What Happened Instead

I was stuck with a "Naga Spawner" infront of me and it wouldnt spawn the boss itself, on any difficulty and even whilst on gamemode 1.

### Additional Details

Might be a mod error but i dont know which mod that is.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Try running without Twilight Tweaks? I can't replicate the issue, but it's worth a shot

**Comment by PraiaOO** [comment]
tried and it didnt worked, i uploaded the mods to curseforge and check if it's a mod problem or if it's just my PC doing some weird things to minecraft (https://www.curseforge.com/minecraft/modpacks/decland-figgles/files/4044139).

**Comment by PraiaOO** [comment]
tried and it didnt worked, i uploaded the mods to curseforge and check if it's a mod problem or if it's just my PC doing some weird things to minecraft (https://www.curseforge.com/minecraft/modpacks/decland-figgles/files/4044139).

> Try running without Twilight Tweaks? I can't replicate the issue, but it's worth a shot

**Comment by PraiaOO** [comment]
Found the error. It was caused by a mod named "Tiquality-FAT".
