### ISSUE TITLE
A Suggestion for the Final Castle's Basement

### ISSUE THREAD

**Issue by BararDragoni** [TeamTwilight/twilightforest#1669]
### The Suggestion

So In the basement of the final castle. there are a lot of empty sealed cages. so my idea is that in those cages you could have small terrariums, each containing 1-3 of most of the monsters/entities from around the over-world and twilight forest. each cage could be specialized to the creature inside of it, so like the one holding cave trolls could look like the inside of the caves, or for skeletons could look like a tomb, the yeti cage could looks like a frozen tundra on the inside and the Carminite ghastling cage could look like the inside of the Ur-Ghast's tower. basically my idea is to make the castle basement be like a zoo or a menagerie and perhaps one or two could of the cages could have piles of gold or other valuables. 

### Why Should It Be in the Mod?

This idea provides a way to fill the empty space in the basement/room underneath the Final castle.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
We have plans for the castle already.
