### ISSUE TITLE
Crash Trying to Enter Twilight Dim

### ISSUE THREAD

**Issue by Tyrius1** [TeamTwilight/twilightforest#1673]
### Forge Version

43.1.47

### Twilight Forest Version

1.19-4.2.1421

### Client Log

https://pastebin.com/Tj5gfbSt

### Crash Report (if applicable)

https://pastebin.com/TvRsaWCs

### Steps to Reproduce

Install shown mods in modlist and attempt to enter twilight forest.

### What You Expected

Given all the performance mods and new world generation with Tectonic I sort of expected the crash to be honest. I hoped it might let me enter the dimension though.

### What Happened Instead

It crashed

### Additional Details

Utilizing many "performance" enhancing mods as well as 2 new world gen mods called Tectonic and Continents

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
please install the mod cyanide (https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) to give us a more readable crash report. Once you install the mod and get the game to crash again, please let me know and I can track down the issue.

**Comment by Tamaized** [comment]
Most likely another mod(s) injecting features into our biomes.
