### ISSUE TITLE
Initializing game

### ISSUE THREAD

**Issue by Rafcioff15** [TeamTwilight/twilightforest#1674]
### Forge Version

43.1.47

### Twilight Forest Version

1.19-4.2.1392/1421-universal

### Client Log

https://gist.github.com/Rafcioff15/12bd904cb6ce9093748e40c8615dda12

### Crash Report (if applicable)

https://gist.github.com/Rafcioff15/830c4af54854f5d3cb8a3d1c4d2147d4

### Steps to Reproduce

I made list of mods, and got crash with "render threat" so i started adding mods one by one and when twilight is added client getting crashed, every time. I tried start with forge version from 43.1.30 till 32.1.47 always same crashes. 

### What You Expected

I uninstalled mods like "bartering station" or "farmer's delight " but it still doesnt work 

### What Happened Instead

Client crash in loading.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
looks like a crash with Every Compat. Something is going wrong when loading the TF module, which is why the game crashes when you add TF. I would report this to their issue tracker if its not already reported.

**Comment by Rafcioff15** [comment]
Thanks for fast reaction. Thanks to you, I noticed that I have an old version "everycomp" now all works pretty good!!! :D
