### ISSUE TITLE
JAde Error Loading Twilight Forest.Compat plugin

### ISSUE THREAD

**Issue by Zelioth** [TeamTwilight/twilightforest#1676]
### Forge Version

43.1.47

### Twilight Forest Version

4.2.1421

### Client Log

https://gist.github.com/Zelioth/90e5efd6aae30786e72b2a43407cafd1

### Steps to Reproduce

Umm install both jade and TLF

### What You Expected

to work

### What Happened Instead

error

### Additional Details

https://github.com/Snownee/Jade/issues/169

reported to jade and they directed me to TLF

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
THIS was the issue I was trying to close yesterday. I'll have another beta (maybe even the 1.19 release? Not sure yet) out soon, it'll be fixed then. 

(fixed in f34d092cb026dd2505ac450081e5c0a0ffe4bc35)
