### ISSUE TITLE
Dark forest canopy generates low

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest#1679]
### Forge Version

43.1.47

### Twilight Forest Version

4.2.1421

### Steps to Reproduce

Find a dark forest

### What You Expected

For there to be at least 2-3 blocks of space on average between the canopy and the ground

### What Happened Instead

The canopy generates low, so that large portions are 0-1 blocks above ground, and strongholds often have to be found by digging

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Fixed in 8ff7c4fa20ef378088c1d8c918cba014bc8633ed
(Mod version 4.2.1447)
