### ISSUE TITLE
Hostile vanilla mobs spawning on the surface of dark forests

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest#1680]
### Forge Version

43.1.47

### Twilight Forest Version

4.2.1421

### Steps to Reproduce

Find a dark forest
Explore the surface under the canopy

### What You Expected

Only certain hostile twilight forest mobs to spawn

### What Happened Instead

All hostile vanilla mobs will spawn, as well as various hostile twilight forest mobs

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Intended. All monsters that spawn in the dark forest are listed here: https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/generated/resources/data/twilightforest/worldgen/biome/dark_forest.json#L71
Its a mix of vanilla and TF mobs
