### ISSUE TITLE
[1.19.2] Ice bow effect does not work on squid

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1681]
### Forge Version

43.1.32

### Twilight Forest Version

4.2.1463

### Steps to Reproduce

1. Shoot a squid/glowsquid in the water with an ice bow

### What You Expected

I expected the frost effect to negate the squids response to damage (when damaged, a squid will jet away far faster than its normal movement)

### What Happened Instead

While the squid displayed the ice effect, it still moved quickly as if it did not have any ill effects from the bow

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
looking at the code, it seems squids dont take movement speed into account when moving or fleeing, so frosted will be useless when used against them. They get the effect, but it does absolutely nothing thanks to this. 

Stupid Mojang.
