### ISSUE TITLE
[1.19.2] Naga only accepts frosted effect when hit on head

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1683]
### Forge Version

43.1.32

### Twilight Forest Version

4.2.1463

### Steps to Reproduce

1. Shoot naga in the body (on a multipart segment) with a frosted bow, and then on the head

### What You Expected

I would expect that hitting the naga anywhere would grant the frosted effect, as hitting it on the head does grant the effect.

### What Happened Instead

The multipart segments do not grant the effect, only striking it on the head.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by EvergreenSystems** [comment]
Notably, the naga does not get the ice spike visual that other mobs does, just the vanilla effect bubbles and the slowdown that the effect grants

**Comment by GizmoTheMoonPig** [comment]
Not really able to fix this, as mob effects can only be applied to LivingEntities. Multiparts are just normal entities, so they dont have a way to accept mob effects. Switching multiparts to livingentities isnt a valid option unfortunately.
