### ISSUE TITLE
Transformation Powder's mob transformation bug

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [TeamTwilight/twilightforest#1684]
### Forge Version

40.1.84

### Twilight Forest Version

4.1.1423

### Steps to Reproduce

Use Transformation Powder to transform Pig, Zombie, Villager, Cod respectively.

### What You Expected

Pig->Boar
Zombie->Nothing happened
Villager->Nothing happened
Cod->Nothing happened

### What Happened Instead

Pig->Zombie
Zombie, Villager or Cod->Pig

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
unable to reproduce. Tested on all the mobs listed and all of them worked as intended. Can you reproduce this with only TF? If not, it would seem like either theres a mod conflict or a modpack is changing the transformation recipes if youre playing one.

If possible, can you also post your debug.log? Another possible culprit could be that the recipes arent being properly loaded and thats an issue. Want to hopefully rule out that possibility
