### ISSUE TITLE
Fiery items invisible when held in hand with shaders enabled

### ISSUE THREAD

**Issue by LolJohn11** [TeamTwilight/twilightforest#1685]
### Forge Version

43.1.43

### Twilight Forest Version

4.2.1468

### Client Log

https://gist.github.com/LolJohn11/c66e2e1683df4e229961aec82f44a2ff

### Steps to Reproduce

1. Have Twilight Forest, Rubidium and Oculus installed
2. Enable any shaders
3. Hold any "fiery" item in your hand

### What You Expected

All items should be visible when held in hand, both in first-person and in third-person view.

### What Happened Instead

With any shaders enabled, all of the "fiery" items - ingot, armor, tools and weapons - are invisible when holding them in hand, both in first-person view and in third-person view. Fiery armor is only visible when equipped.
This issue exists only when using shaders and is not specific to any specific shaderpack. 
As hinted in the "steps to reproduce" section, I am not using Optifine - I am using Rubidium and Oculus instead (forge ports of Sodium and Iris).

### Additional Details

Shaders Disabled:
![2022-11-15_14 03 53](https://user-images.githubusercontent.com/49366383/201916577-db86238b-b38d-4f98-af79-fdca8beed675.png)
![2022-11-15_14 04 35](https://user-images.githubusercontent.com/49366383/201916568-4d9fd12a-8c04-4f07-910b-e31b8d4925b6.png)

Shaders Enabled:
![2022-11-15_14 04 08](https://user-images.githubusercontent.com/49366383/201916686-884ae85e-6f59-4789-bf4f-c9c2ff3caf50.png)
![2022-11-15_14 04 21](https://user-images.githubusercontent.com/49366383/201916700-058bf3ee-93e7-4d6c-9a82-f96483e254b8.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by EvergreenSystems** [comment]
I reported this issue to Oculus last week, as far as I'm aware the bug is on their end as this happens with any fullbright items

**Comment by Tamaized** [comment]
We use a system provided by Minecraft Forge. We can't fix this.
