### ISSUE TITLE
[Suggestion] Giant Nether Portal

### ISSUE THREAD

**Issue by Rusthicc** [TeamTwilight/twilightforest#1687]
### The Suggestion

Creation of nether portals using giant obsidian blocks

### Why Should It Be in the Mod?

Fun. Hilarious. Adds variety.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by anonymous2007** [comment]
Isn't this theoretically already in? I'm uncertain, but I think the obsidian in giant obsidian could be used as a nether portal. if not, it's presumably just an NBT tag away and would be relatively easy to implement (although not high on the priorities list)

**Comment by Rusthicc** [comment]
> Isn't this theoretically already in? I'm uncertain, but I think the obsidian in giant obsidian could be used as a nether portal. if not, it's presumably just an NBT tag away and would be relatively easy to implement (although not high on the priorities list)

You can't actually place giant obsidian in the overworld, and you also can't travel to the nether either from the twilight forest unfortunately even with a normal obsidian portal as far as I'm aware.

**Comment by anonymous2007** [comment]
I didn't know you couldn't place giant obsidian in the overworld!
If they do, it'd be neat if the portal itself was larger

**Comment by GizmoTheMoonPig** [comment]
you can place giant obsidian in the overworld, its just a bit tricky to do so because of how giant blocks work.
As for the giant obsidian being a portal frame, while its a fun idea, and certainly not the first time we've heard it, we're not sure if it should actually be in the mod since you cant light nether portals in TF anyway thanks to vanilla constraints

**Comment by PraseodymiumSpike** [comment]
I suggest it should use a different portal block, the Giant Nether Portal, which would be 4 times thicker than the normal Nether Portal and have bigger pixels.
