### ISSUE TITLE
Thorns Rose able to be placed below blocks and on the side of non-thorn blocks

### ISSUE THREAD

**Issue by TelepathicGrunt** [TeamTwilight/twilightforest#1688]
### Forge Version

43.1.52

### Twilight Forest Version

4.2.1468

### Steps to Reproduce

Get Thorn Rose from creative menu. Place it on the bottom side of any block. Notice it is now floating due to the textures. Also placing it on the side of any block will work regardless if it is a thorn block or not.

![image](https://user-images.githubusercontent.com/40846040/202875064-7356ada1-8645-478b-b2c5-938bc78c309d.png)

### What You Expected

An idea is to make their canSurvive method in the block class return true only if the spot given is next to a thorn block or below is a dirt-tagged block/thorn block

![image](https://user-images.githubusercontent.com/40846040/202874995-ca56dc9e-2121-4f9c-a1bd-705d1081594b.png)

Also, small suggestion, could the rose be tagged as `minecraft:small_flowers` so that bees can be pollinated in the rose just like vanilla's Rose Bushes?

### What Happened Instead

Currently Thorn Rose can be place on the side of any block regardless of how it'll look or if it'll be floating

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
This is just the initial fix, will think about on what kind of blocks in can be placed on now.
