### ISSUE TITLE
 Colliding entity with block Server crash

### ISSUE THREAD

**Issue by enjoyable1** [TeamTwilight/twilightforest#1689]
### Forge Version

36.2.39

### Twilight Forest Version

4.0.870

### Client Log

-

### Crash Report (if applicable)

https://gist.github.com/enjoyable1/4b5267bfbbf1407f91625fe7a8a3cd5e#file-gistfile1-txt

### Steps to Reproduce

When a monster or entity enters the portal, it causes the server to crash.  Log description: Colliding entity with block. .  
I don't know how to solve this problem.

### What You Expected

Should creatures be teleported to the world.Don't crash the server

### What Happened Instead

--

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
im unable to reproduce this issue. Entities are able to go through the portal just fine, both entering and leaving TF. If I had to guess, theres some mod conflict at play here. Are you able to make this happen with just TF installed?
