### ISSUE TITLE
TF's defines a structure override list in the chunk generator, making non-TF structure spawns impossible

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [TeamTwilight/twilightforest#1690]
Pretty much speaks for itself. Since we actually populate the structure overrides HolderSet, no other structures that tell the game they can show up there will actually show up. (see: ChunkGenerator.possibleStructureSets()) I dont see why we need to have this set up, but maybe something will come up when trying to fix this.

**Comment by GizmoTheMoonPig** [comment]
1.19.3 removes the override list, so this should no longer be an issue. Will need to do some further testing to make sure

**Comment by Tamaized** [comment]
Can this be closed?

**Comment by GizmoTheMoonPig** [comment]
confirmed to be working correctly in 1.19.3, closing
