### ISSUE TITLE
graphic bug in fire swamp

### ISSUE THREAD

**Issue by RubyMarc2969** [TeamTwilight/twilightforest#1692]
Minecraft vers 1.19.2 
I'm playing all the mods 8 and killing all the bosses when I go to the fire swamp this happens 
![2022-11-26_01 45 11](https://user-images.githubusercontent.com/107775189/204078329-059e886d-5201-47c4-b4b9-f35082bfcf7e.png)

**Comment by RubyMarc2969** [comment]
I'm playing on a private server and I've tried logging out and back in

**Comment by Andromander** [comment]
Can we get a mod list? We've been trying to pin down if this is a conflict but have never found a root cause.

**Comment by RubyMarc2969** [comment]
i found this for the version I'm playing on 
https://www.curseforge.com/minecraft/modpacks/all-the-mods-8/files/4083520

**Comment by RubyMarc2969** [comment]
The graphic bug happens right when I hit the fire swamp biome
![2022-11-26_02 05 00](https://user-images.githubusercontent.com/107775189/204078864-01133670-41d3-4dbc-81b6-56def6e9006f.png)

**Comment by GizmoTheMoonPig** [comment]
Do you have Nature's Aura installed by any chance? Ive seen this happen only when that mod is installed. I have absolutely no idea why they interact like this tbh
