### ISSUE TITLE
Centering worldborder far from 0,0 makes portals spawn outside of world border and kill players

### ISSUE THREAD

**Issue by E-daw** [TeamTwilight/twilightforest#1693]
Forge version: 43.1.52
Twilight Forest version: 1.19.2-4.2.1468

Steps to reproduce:
1. Center world border out from 0,0
2. Enable world border to smaller value
3. Create portals in over world

What I expected to happen:
Players spawn in the forest normally
What happened instead:
Players immediately die from suffocation because they're placed outside the border

Is there a way to set the scale to 1:1 rather than the 8:1 to fix this or some way to allow for portals to spawn within the border?

**Comment by Andromander** [comment]
This is an issue present in vanilla as well, nothing we can do. Only fix for this is to keep the world border at 0,0.

**Comment by GizmoTheMoonPig** [comment]
You can set the scale with a datapack if you want to. Simply copy this file and change the coordinate scale: https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/generated/resources/data/twilightforest/dimension_type/twilight_forest_type.json#L4. Otherwise, the worldborder not scaling correctly in other dimensions when the center is changed is a vanilla bug that we cant really do much about.

**Comment by E-daw** [comment]
> You can set the scale with a datapack if you want to. Simply copy this file and change the coordinate scale: https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/generated/resources/data/twilightforest/dimension_type/twilight_forest_type.json#L4. Otherwise, the worldborder not scaling correctly in other dimensions when the center is changed is a vanilla bug that we cant really do much about.

How would I go about adding that file to a datapack?

**Comment by GizmoTheMoonPig** [comment]
the file goes under the same directory as the file I just linked. (data/twilightforest/dimension_type/twilight_forest.json). If you've never made a datapack before, you can read the wiki page to understand how to set a basic one up. https://minecraft.fandom.com/wiki/Data_pack
