### ISSUE TITLE
BiomesOPlenty clashed with Twilightforest and collapsed

### ISSUE THREAD

**Issue by yuankun1** [TeamTwilight/twilightforest#1696]
### Forge Version

36.2.39

### Twilight Forest Version

4.0.870

### Crash Report (if applicable)

---- Minecraft Crash Report ---- // I let you down. Sorry :(  Time: 22-11-28 下午12:07 Description: Exception in server tick loop  java.lang.OutOfMemoryError: Java heap space 	at it.unimi.dsi.fastutil.longs.Long2IntLinkedOpenHashMap.rehash(Long2IntLinkedOpenHashMap.java:1823) ~[fastutil-8.2.1.jar:?] {re:classloading} 	at it.unimi.dsi.fastutil.longs.Long2IntLinkedOpenHashMap.insert(Long2IntLinkedOpenHashMap.java:336) ~[fastutil-8.2.1.jar:?] {re:classloading} 	at it.unimi.dsi.fastutil.longs.Long2IntLinkedOpenHashMap.put(Long2IntLinkedOpenHashMap.java:344) ~[fastutil-8.2.1.jar:?] {re:classloading} 	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:27) ~[?:?] {re:classloading} 	at net.minecraft.world.gen.layer.Layer.func_242936_a(SourceFile:23) ~[?:?] {re:classloading,pl:accesstransformer:B} 	at biomesoplenty.common.world.BOPBiomeProvider.func_225526_b_(BOPBiomeProvider.java:70) ~[biomesoplenty:?] {re:classloading} 	at net.minecraft.world.server.ServerWorld.func_225604_a_(ServerWorld.java:217) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:library_of_exile-mixins.json:ServerWorldMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:A} 	at net.minecraft.world.IWorldReader.func_225526_b_(IWorldReader.java:54) ~[?:?] {re:mixin,re:classloading} 	at twilightforest.command.MapBiomesCommand.execute(MapBiomesCommand.java:83) ~[twilightforest:?] {re:classloading} 	at twilightforest.command.MapBiomesCommand$$Lambda$18102/1494499244.run(Unknown Source) ~[?:?] {} 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[brigadier-1.0.17.jar:?] {re:classloading} 	at net.minecraft.command.Commands.func_197059_a(Commands.java:217) ~[?:?] {re:classloading} 	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1119) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,pl:mixin:A} 	at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1102) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,pl:mixin:A} 	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1081) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,pl:mixin:A} 	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading} 	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading} 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading} 	at net.minecraft.network.PacketThreadUtil$$Lambda$20829/1089744732.run(Unknown Source) ~[?:?] {} 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:computing_frames,re:mixin,re:classloading} 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer$$Lambda$19349/216171549.run(Unknown Source) ~[?:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.16.5 	Minecraft Version ID: 1.16.5 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_291, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 561872408 bytes (535 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB) 	CPUs: 8 	JVM Flags: 7 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions -Xmn256m -Xmx2048m 	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec 	ModLauncher launch target: fmlclient 	ModLauncher naming: srg 	ModLauncher services:  		/mixin-0.8.4.jar mixin PLUGINSERVICE  		/eventbus-4.0.0.jar eventbus PLUGINSERVICE  		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE  		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE  		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE  		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE  		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE  	FML: 36.2 	Forge: net.minecraftforge:36.2.39 	FML Language Providers:  		javafml@36.2 		minecraft@1 	Mod List:  		潘马斯树pamhc2trees-1.16.3-1.0.1.jar                  |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |DONE      |Manifest: NOSIGNATURE 		[皮肤补丁]CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-|CustomSkinLoader              |customskinloader              |14.14-SNAPSHOT-346  |DONE      |Manifest: 4a:31:8b:cf:34:eb:d0:13:f3:19:39:d5:d2:b9:12:78:b5:f2:8d:91:3e:6f:8f:ed:97:48:00:69:e1:30:3a:54 		枪械crafting-dead-core-1.16.5-1.7.5-alpha.jar       |Crafting Dead                 |craftingdead                  |1.7.5-alpha         |DONE      |Manifest: NOSIGNATURE 		星占魔法astrologicalsorcery-1.16.4-1.3.2.jar          |Astrological Sorcery          |astrosorc                     |1.16.4-1.3.2        |DONE      |Manifest: 8d:20:3c:56:44:0d:d9:3c:79:c2:c7:a2:4f:cc:c8:00:97:c4:a2:e2:41:e5:38:1e:ba:6b:c9:f2:eb:64:8d:84 		星辉魔法astralsorcery-1.16.5-1.14.1.jar               |Astral Sorcery                |astralsorcery                 |1.16.4-1.14.1       |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7 		挖矿与砍杀Mine_and_Slash_BETA-1.16.5-4.0.18.jar.jar    |Mine and Slash                |mmorpg                        |NONE                |DONE      |Manifest: NOSIGNATURE 		[物品管理]jei-1.16.5-7.7.1.152.jar                    |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE 		拔刀剑SlashBlade-1.16-0.0.12.1.jar                   |Slash Blade                   |slashblade                    |0.0.12              |DONE      |Manifest: NOSIGNATURE 		[铷]rubidium-0.2.10.jar                            |Rubidium                      |rubidium                      |0.2.10              |DONE      |Manifest: NOSIGNATURE 		[经验机制改革]Clumps-6.0.0.28.jar                       |Clumps                        |clumps                        |6.0.0.28            |DONE      |Manifest: NOSIGNATURE 		[旅行地图]journeymap-1.16.5-5.8.5p6.jar               |Journeymap                    |journeymap                    |5.8.5p6             |DONE      |Manifest: NOSIGNATURE 		前置citadel-1.8.1-1.16.5.jar                        |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE 		Alex 的生物alexsmobs-1.12.1.jar                      |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE 		[汉化]i18nupdatemod-1.16.5-2.0.4.jar                |I18n update Mod               |i18nupdatemod                 |2.0.4               |DONE      |Manifest: NOSIGNATURE 		[优化前置]Placebo-1.16.5-4.7.0.jar                    |Placebo                       |placebo                       |4.7.0               |DONE      |Manifest: NOSIGNATURE 		旅行者背包TravelersBackpack-1.16.5-5.4.16.jar          |Traveler's Backpack           |travelersbackpack             |5.4.16              |DONE      |Manifest: NOSIGNATURE 		静谧四季SereneSeasons-1.16.5-4.0.1.126-universal.jar  |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.126    |DONE      |Manifest: NOSIGNATURE 		更多动物betteranimalsplus-1.16.5-11.0.5-forge.jar     |Better Animals Plus           |betteranimalsplus             |1.16.5-11.0.5       |DONE      |Manifest: NOSIGNATURE 		阶段前置Bookshelf-Forge-1.16.5-10.4.32.jar            |Bookshelf                     |bookshelf                     |10.4.32             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		[DFU载入优化]lazydfu-0.1.3.jar                        |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE 		冰与火之歌iceandfire-2.1.11-1.16.5.jar                 |Ice and Fire                  |iceandfire                    |2.1.11-1.16.5       |DONE      |Manifest: NOSIGNATURE 		日系附属包拔刀剑-1.16-1.2.jar                             |SlashBlade Addon              |ex_blades                     |1.1                 |DONE      |Manifest: NOSIGNATURE 		[镁铷：附属]magnesium_extras-mc1.16.5_v1.4.0.jar       |Magnesium Extras              |magnesium_extras              |mc1.16.5_v1.4.0     |DONE      |Manifest: NOSIGNATURE 		[减速器FPS]FpsReducer-forge-1.24-mc1.16.5.jar        |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |DONE      |Manifest: NOSIGNATURE 		魔改CraftTweaker-1.16.5-7.1.2.515.jar               |CraftTweaker                  |crafttweaker                  |7.1.2.515           |DONE      |Manifest: NOSIGNATURE 		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90 		阶段配方RecipeStages-2.0.0.21.jar                     |Recipe Stages                 |recipestages                  |2.0.0.21            |DONE      |Manifest: NOSIGNATURE 		暮色森林twilightforest-1.16.5-4.0.870-universal.jar   |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE 		更多箱子ironchest-1.16.5-11.2.21.jar                  |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE 		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE 		工业先锋industrial-foregoing-1.16.5-3.2.14.6-14.jar   |Industrial Foregoing          |industrialforegoing           |3.2.14.6            |DONE      |Manifest: NOSIGNATURE 		匠魂TConstruct-1.16.5-3.3.4.335.jar                 |Tinkers' Construct            |tconstruct                    |3.3.4.335           |DONE      |Manifest: NOSIGNATURE 		[氡]radon-0.8.0a.jar                               |Radon                         |radon                         |0.8.0a              |DONE      |Manifest: NOSIGNATURE 		工业先锋前置titanium-1.16.5-3.2.8.4-10.jar              |Titanium                      |titanium                      |3.2.8.4             |DONE      |Manifest: NOSIGNATURE 		沉浸工程ImmersiveEngineering-1.16.5-5.1.0-148.jar     |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |DONE      |Manifest: NOSIGNATURE 		更多生物群系BiomesOPlenty-1.16.5-13.1.0.488-universal.ja|Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.488   |DONE      |Manifest: NOSIGNATURE 		无尽贪婪Endless-1.16.5-1.4.0.jar                      |Endless                       |endless                       |1.16.5-1.4.0        |DONE      |Manifest: NOSIGNATURE 		潘马斯作物pamhc2crops-1.16.3-1.0.2.jar                 |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |Manifest: NOSIGNATURE 		[区块加载]ChunkAnimator-1.16.5-1.2.3.jar              |Chunk Animator                |chunkanimator                 |1.16.5-1.2.3        |DONE      |Manifest: NOSIGNATURE 		植物魔法Botania-1.16.5-420.2.jar                      |Botania                       |botania                       |1.16.5-420.2        |DONE      |Manifest: NOSIGNATURE 		[流畅加载]smoothboot-forge-1.16.4-1.2.2.jar           |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE 		挖矿与砍杀圣神任务Divine_Missions-1.16.5-1.0.1.jar         |Divine Missions               |divine_missions               |NONE                |DONE      |Manifest: NOSIGNATURE 		潘马斯拓展pamhc2foodextended-1.16.3-1.0.4.jar          |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |Manifest: NOSIGNATURE 		[TexTrue的铷视频界面]textrues_rubidium_options-1.0.3-mc1|TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.3-mc1.16.5      |DONE      |Manifest: NOSIGNATURE 		车万女仆touhoulittlemaid-1.16.5-1.0.2.jar             |Touhou Little Maid            |touhou_little_maid            |NONE                |DONE      |Manifest: NOSIGNATURE 		前置curios-forge-1.16.5-4.0.8.2.jar                 |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE 		帕秋莉手册Patchouli-1.16.4-53.2.jar                    |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE 		匠魂前置Mantle-1.16.5-1.6.157.jar                     |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE 		阶段GameStages-Forge-1.16.5-7.3.13.jar              |GameStages                    |gamestages                    |7.3.13              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		阶段物品ItemStages-Forge-1.16.5-3.0.9.jar             |ItemStages                    |itemstages                    |3.0.9               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		潘马斯食物pamhc2foodcore-1.16.3-1.0.2.jar              |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |Manifest: NOSIGNATURE 		敌对生物hmag-mc1.16.5-4.5.11.jar                      |Hostile Mobs and Girls        |hmag                          |4.5.11              |DONE      |Manifest: NOSIGNATURE 		[铷 · 扩展]RubidiumExtra-1.16.5-0.4.10.37.jar        |Rubidium Extra                |sodiumextra                   |1.16.5-0.4.10.37    |DONE      |Manifest: NOSIGNATURE 		[快速工作台]FastWorkbench-1.16.5-4.6.1.jar             |Fast Workbench                |fastbench                     |4.6.1               |DONE      |Manifest: NOSIGNATURE 		夸克前置AutoRegLib-1.6-49.jar                         |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE 		夸克Quark-r2.4-322.jar                              |Quark                         |quark                         |r2.4-322            |DONE      |Manifest: NOSIGNATURE 		[氪Forge版]ryptonreforged-mc1.16.5_v1.0.0.jar       |Krypton Reforged              |kryptonreforged               |mc1.16.5_v1.0.0     |DONE      |Manifest: NOSIGNATURE 		[多态合成]polymorph-forge-1.16.5-0.41.jar             |Polymorph                     |polymorph                     |1.16.5-0.41         |DONE      |Manifest: NOSIGNATURE 		坚定意志ToughAsNails-1.16.5-4.1.0.9-universal.jar     |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.8      |DONE      |Manifest: NOSIGNATURE 		[实体渲染机制优化]entityculling-forge-mc1.16.5-1.5.2.jar  |EntityCulling                 |entityculling                 |1.5.2               |DONE      |Manifest: NOSIGNATURE 		时装工坊armourersworkshop-forge-1.16.5-2.0.0-beta.3.ja|Armourer's Workshop           |armourers_workshop            |2.0.0-beta.3        |DONE      |Manifest: 58:d0:3b:4b:a0:4b:43:fb:59:0f:27:f5:39:d5:65:de:9a:24:ee:2e:15:48:b1:4f:78:1a:e1:ef:cd:a4:d9:0a 		挖矿砍杀前置World_of_Exile-1.16.5-1.4.3.jar             |Dungeons of Exile             |world_of_exile                |NONE                |DONE      |Manifest: NOSIGNATURE 		自定义NPCCustomNPCs-1.16.5.20220515.jar              |Custom NPCs                   |customnpcs                    |1.16.5.20220515     |DONE      |Manifest: NOSIGNATURE 		挖矿与砍杀前置Library_of_Exile-1.16.5-1.2.3.jar          |Library Of Exile              |library_of_exile              |NONE                |DONE      |Manifest: NOSIGNATURE 		[熔炉优化]FastFurnace-1.16.5-4.5.0.jar                |FastFurnace                   |fastfurnace                   |4.5.0               |DONE      |Manifest: NOSIGNATURE 		凡家物语前置architectury-1.32.66.jar                    |Architectury                  |architectury                  |1.32.66             |DONE      |Manifest: NOSIGNATURE 		凡家物语重制minecraft-comes-alive-7.3.21+1.16.5-universa|Minecraft Comes Alive         |mca                           |7.3.21+1.16.5       |DONE      |Manifest: NOSIGNATURE 		MrCrayfish 的家具cfm-7.0.0pre22-1.16.3.jar           |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE 		[苹果皮]appleskin-forge-mc1.16.x-2.4.0.jar           |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |DONE      |Manifest: NOSIGNATURE 		额外植物学ExtraBotany-r1.2-69.jar                      |ExtraBotany                   |extrabotany                   |1.0                 |DONE      |Manifest: NOSIGNATURE 		[铁氧体磁芯]ferritecore-2.0.7-forge.jar                |Ferrite Core                  |ferritecore                   |2.0.7               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a 		星辉前置observerlib-1.16.5-1.5.3.jar                  |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE 		前置CodeChickenLib-1.16.5-4.0.7.445-universal.jar   |CodeChicken Lib               |codechickenlib                |4.0.7.445           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71 		龙之研究前置BrandonsCore-1.16.5-3.0.15.248-universal.jar|Brandon's Core                |brandonscore                  |3.0.15.248          |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe 		龙之研究Draconic-Evolution-1.16.5-3.0.27.462-universal|Draconic Evolution            |draconicevolution             |3.0.27.462          |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe 		龙之研究拓展Draconic-Additions-1.16.5-2.2.3.6-universal.|Draconic Additions            |draconicadditions             |2.2.3.6             |DONE      |Manifest: NOSIGNATURE 		前置geckolib-forge-1.16.5-3.0.92.jar                |GeckoLib                      |geckolib3                     |3.0.92              |DONE      |Manifest: NOSIGNATURE 	Crash Report UUID: a3149a39-1afe-4769-9e46-a737dddcde35 	Patchouli open book context: n/a 	Player Count: 1 / 8; [ServerPlayerEntity['123321'/412, l='ServerLevel[新的世界]', x=518.89, y=72.91, z=-610.76]] 	Data Packs: vanilla, mod:pamhc2trees (incompatible), mod:customskinloader (incompatible), mod:craftingdead (incompatible), mod:astrosorc (incompatible), mod:astralsorcery, mod:mmorpg, mod:jei, mod:slashblade (incompatible), mod:rubidium (incompatible), mod:clumps, mod:journeymap (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:i18nupdatemod, mod:placebo (incompatible), mod:travelersbackpack (incompatible), mod:sereneseasons, mod:betteranimalsplus, mod:bookshelf, mod:lazydfu, mod:iceandfire, mod:ex_blades (incompatible), mod:magnesium_extras, mod:fpsreducer, mod:crafttweaker, mod:forge, mod:recipestages, mod:twilightforest, mod:ironchest, mod:industrialforegoing (incompatible), mod:tconstruct, mod:radon (incompatible), mod:titanium (incompatible), mod:immersiveengineering, mod:biomesoplenty, mod:endless, mod:pamhc2crops (incompatible), mod:chunkanimator, mod:botania, mod:smoothboot, mod:divine_missions (incompatible), mod:pamhc2foodextended (incompatible), mod:reeses_sodium_options (incompatible), mod:touhou_little_maid, mod:curios, mod:patchouli (incompatible), mod:mantle (incompatible), mod:gamestages, mod:itemstages (incompatible), mod:pamhc2foodcore (incompatible), mod:hmag, mod:sodiumextra (incompatible), mod:fastbench (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:kryptonreforged (incompatible), mod:polymorph, mod:toughasnails, mod:entityculling, mod:armourers_workshop, mod:world_of_exile (incompatible), mod:customnpcs, mod:library_of_exile (incompatible), mod:fastfurnace (incompatible), mod:architectury, mod:mca, mod:cfm (incompatible), mod:appleskin, mod:extrabotany (incompatible), mod:ferritecore (incompatible), mod:observerlib, mod:codechickenlib (incompatible), mod:brandonscore (incompatible), mod:draconicevolution (incompatible), mod:draconicadditions (incompatible), mod:geckolib3 (incompatible) 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'forge'

### Steps to Reproduce

The biome search function is used
/locatebiome 

### What You Expected

not

### What Happened Instead

not

### Additional Details

not

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Looks like this was caused by the map biomes command. Any reason you were using this? Its meant as a debug command for us devs to use really.
Since this is an Out of Memory Error, you can just allocate some more RAM to prevent this from happening again. 
1.16 is also no longer supported
