### ISSUE TITLE
LAN online players are offline

### ISSUE THREAD

**Issue by hqxxx** [TeamTwilight/twilightforest#1697]
### Forge Version

forge 43.1.47

### Twilight Forest Version

twilightforest-1.19.2-4.2.1468-universal

### Steps to Reproduce

1.19.2 Players who play LAN online hosts with friends will be disconnected once they are close to Naga and the Dark Forest

### What You Expected

不会出现掉线的情况

### What Happened Instead

 
Connected player offline display          internal excrptionjava.lang.indexoutofboundsexception:readerIndex(177）=length（4） exceedswriterIndex(180):pooledUnsafeDirectExteBuf(redx:177.widx:180,cap:180)

However, it can be repeatedly connected until the host leaves a specific location, and it will not be disconnected

### Additional Details

[2022-11-27-3.log.gz](https://github.com/TeamTwilight/twilightforest/files/10100978/2022-11-27-3.log.gz)
[debug-3.log.gz](https://github.com/TeamTwilight/twilightforest/files/10100981/debug-3.log.gz)
[debug-4.log.gz](https://github.com/TeamTwilight/twilightforest/files/10100982/debug-4.log.gz)
[debug-5.log.gz](https://github.com/TeamTwilight/twilightforest/files/10100983/debug-5.log.gz)
[debug-1.log.gz](https://github.com/TeamTwilight/twilightforest/files/10100984/debug-1.log.gz)
[debug-2.log.gz](https://github.com/TeamTwilight/twilightforest/files/10100985/debug-2.log.gz)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Update forge to 43.1.53
