### ISSUE TITLE
Naga Boss Is Very Fast

### ISSUE THREAD

**Issue by Darkosto** [TeamTwilight/twilightforest#170]
Hello,

While working through and testing out the 1.12.1 build of TF, I walked into the Naga fight and discovered it's generally very fast. I understand he does a charge move which makes him move at the player quickly but his other actions are all much faster than in previous versions. Can this be reduced or at least have a config option to change the speed for maximum customization?

This speed increase affects my project in particular since players will be unable to bring other weapons/armor/items into the Twilight Forest so they will be facing the Naga and other bosses with TF items only. 

MC: 1.12.1
TF: 2.4.0.61
Forge: 2479

Thank you for your time,
Darkosto

**Comment by Benimatic** [comment]
I think we're on the same page here. It is still the intention that the naga is difficult but possible to fight in unenchanted iron armor, and less difficult in diamond or enchanted armor

**Comment by Darkosto** [comment]
I completely agree with the difficulty level and armor level the player should have when fighting the Naga. During my testing over the last couple of days a few things happen that would help in terms of making the fight a bit more fair but not too easy.

Sidenote: I am limiting the player to only having iron level armor once they begin the twilight, I'm working on a heavily gated pack that limits the ability to bring flight or weapons far too high of a level into the twilight. This approach should let the player experience the TF in a much more intended way, rather than skating through and completing achievements just to check them off a list.

I noticed the Naga does a couple of things that are a bit "unfair" during the fight: 
1. When doing his charge attack, using a shield works a portion of the time and he will damage the player and throw them up into the air causing 3-4 hearts of damage in a span of 3 seconds (this is with iron armor on)
2. His charge attack, on occasion, will allow him to hit the player from 10-16 blocks away
3. When the player is running at full speed, it's still difficult to catch up with the Naga
4. He seems to do his charge attack very often, and this makes it difficult for the player to duck out of the fight for a few seconds to eat some food and take advantage of the new health regen system
5. This may or may not be intended; direct comparison to 1.7.10 the Naga does 1 more heart of damage in 1.12.1. With iron armor on he will do 1 1/2 hearts of damage on a normal strike and in 1.12.1 he does 2 1/2
6. His reach seems very far, the player is just barely in meelee range before getting hit when running up the side of the Naga

I feel like some of these points may help to balance the fight out a bit but still keep it fairly challenging. Even when testing with diamond armor it's a tough fight (which can be a great thing). Ultimately, this fight in its current state is really only achievable via ranged combat and even then it's a pretty close fight.

I hope this helps out a bit and thank you for your work! Take care o/
Darkosto

**Comment by Divineaspect** [comment]
I'm going to expand on this

1. The Broken and Dropped items and blocks from the Naga thrashing can add up and reduce fps. Maybe have the Naga pick up (swallow) those items untill killed?
2. The Body doesn't seem to take melee damage, only the head. This heavily biases fighting it at range, already a superior option.
3. The Shield is so sporadic due to the incredibly rapid speed of it's charge.  

Requests / Suggestions
Shooting it at range slows it down for a while, but does reduced damage. 
Blocking it with a shield should stun it for a second or two to facilitate melee attacks on it.

The Fight would feel more rewarding if it dropped more scales, say 0-2 every time a segment is destroyed.
Naga return to spawner form if a player runs away instead of despawning.

**Comment by Tamaized** [comment]
I've adjusted the Naga a bit so it's a bit more fair. 6a69c69300cba80b782dab02197ae625de199002
Slowed him down, reduced his damage slightly, so on.

Gonna close this issue as most of the problems here have been addressed, the shield working half the time would be the last one.  I'll open up another issue for the Shield stuff.
