### ISSUE TITLE
Hydra fight causes entity tick crash

### ISSUE THREAD

**Issue by Tyre4770** [TeamTwilight/twilightforest#1700]
### Forge Version

43.1.57

### Twilight Forest Version

4.2.1468

### Client Log

https://gist.github.com/Tyre4770/d0438994bdaf0e87a2f3a5120ca57a24

### Crash Report (if applicable)

https://gist.github.com/Tyre4770/78ce541f0aa33c9a830a383110bd6628

### Steps to Reproduce

1. aggro hydra
2. wait for the fireball attack
3. crash

### What You Expected

was supposed to fight hydra

### What Happened Instead

crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this looks like an issue with Open Parties and Claims. This is the 2nd time today ive seen this issue pop up with a mod using the mob griefing Forge hook, so I can only assume theyre doing something wrong on their end. I would report this to their repo.

**Comment by Tyre4770** [comment]
I'm sorry, is that a mod or could it have something to do with the server settings? I don't know very much about this stuff so being directed on where to go to make a bug report would be great. Thank you!

Edit: Sorry I'm dumb, please ignore this LOL. I'm very tired and very stupid, and can't read

**Comment by GizmoTheMoonPig** [comment]
looks like OPaC fixed the issue here: https://github.com/thexaero/open-parties-and-claims/commit/d2cf74fc7e2dc9363635b11a9db20d78c0905d83. Be on the lookout for a new beta from them whenever that comes out
