### ISSUE TITLE
Ticking Entity "Nature Bolt" Causes Player Disconnection on Load

### ISSUE THREAD

**Issue by ItsKingAlex** [TeamTwilight/twilightforest#1702]
### Forge Version

43.1.65

### Twilight Forest Version

4.2.1468

### Client Log

https://gist.github.com/ItsKingAlex/b8f53b7148fb40f6b6030adae9069138

### Crash Report (if applicable)

https://gist.github.com/ItsKingAlex/83d5a049d755070174094de504dd047e

### Steps to Reproduce

1. Enter Twilight Forest
2. Command: /summon twilightforest:nature_bolt

### What You Expected

Stable entity spawn.

### What Happened Instead

Game immediately crashes.

### Additional Details

The first initial crash resulting from this ticking entity was from a naturally occurring "Nature Bolt". Subsequent tests spawning in more have yielded the same results.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
same issue as #1700
