### ISSUE TITLE
[1.16.5] Unable to interact with the forest in multiplayer

### ISSUE THREAD

**Issue by InstaSax** [TeamTwilight/twilightforest#1703]
### Forge Version

36.2.39

### Twilight Forest Version

4.0.870

### Client Log

https://gist.github.com/InstaSax/e0d1a535c53a6294d47b8e52116e6a0c

### Steps to Reproduce

1. Create portal
2. Walk through portal, load into the Twilight Forest
3. Try to break/place blocks

### What You Expected

I expected to be able to interact with the forest's blocks

### What Happened Instead

I couldn't break, place, or interact with blocks.
![image](https://user-images.githubusercontent.com/119818823/205518173-86788928-41e6-4ce0-a3c4-65d67c0ec0d3.png)

### Additional Details

Running Minecraft 1.16.5. I'm the server owner, we have several mods. Here's the list.
![image](https://user-images.githubusercontent.com/119818823/205518400-d037f906-ac2f-420b-8fc6-c0aca2942285.png)
Mekanism's Mekasuit took heavy damage but I wasn't being harmed at all. When I removed any piece of my armor, the damage to the armor stopped.
I couldn't interact with blocks. Pictured is a lever I placed with setblock. I couldn't pull it. 
![image](https://user-images.githubusercontent.com/119818823/205518252-95970ab6-fadb-4ada-bc74-23063b0c235b.png)
There was no black outline over blocks I'm looking at. It feels like adventure mode or something.
Thermal Expansion's grenades still destroy blocks. 
I can interact with everything just fine in singleplayer. This is a multiplayer exclusive bug.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
have you messed with the worldborder at all? Changing the center of the worldborder screws up the worldborder in other dimensions and is unfortunately a vanilla bug
