### ISSUE TITLE
[1.18.2] GL Error 1282

### ISSUE THREAD

**Issue by 12345-mcpython** [TeamTwilight/twilightforest#1704]
### Forge Version

40.1.86

### Twilight Forest Version

4.1.1423

### Client Log

https://gist.github.com/12345-mcpython/4294bb7cda8f2cfe9e599fb361cbc86c

### Steps to Reproduce

1. Go to Twilight Forest
2. View logs/latest.log
3. See lots of error

### What You Expected

There were not so many mistakes

### What Happened Instead

Have lots of error

### Additional Details

GPU: Intel Graphics UHD 770
System: Windows 11

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
no longer an issue on 1.19 as it had to do with the builtin IE compat. This is being moved to its own addon mod and ive fixed the issue there
