### ISSUE TITLE
1.19.2  Flash back into the game

### ISSUE THREAD

**Issue by hqxxx** [TeamTwilight/twilightforest#1706]
### Forge Version

forge 43.1.47

### Twilight Forest Version

twilightforest-1.19.2-4.2.1468-universal

### Steps to Reproduce

Flash back when error is reported in the game

### What You Expected

Can enter the game without deleting mod

### What Happened Instead

I was able to play normally before. I couldn't get into the back
Error report

### Additional Details

[错误报告-2022-12-9_22.00.19.zip](https://github.com/TeamTwilight/twilightforest/files/10199186/-2022-12-9_22.00.19.zip)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Don't use Optifine.
