### ISSUE TITLE
[1.18.2] Sided_Setup Event Phase Error

### ISSUE THREAD

**Issue by JCGemX** [TeamTwilight/twilightforest#1708]
### Forge Version

41.1.86

### Twilight Forest Version

twilightforest-1.18.2-4.1.1423-universal

### Client Log

https://gist.github.com/JCGemX/5755faa688505300fc43c51c62f8683d

### Crash Report (if applicable)

https://gist.github.com/JCGemX/3b953f2d35fc92a7e4ab735aae1840e1

### Steps to Reproduce

1. Launch the game.
2. Get error.

### What You Expected

I expected it to continue to the title screen.

### What Happened Instead

It brought me to the error screen and said "The Twilight Forest (twilightforest) encountered an error during the sided_setup event phase".

### Additional Details

I don't use Optifine.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Should be fixed in 49bd59d, released as version 4.1.1494.
