### ISSUE TITLE
[Suggestion] Vertically extending banisters

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1709]
### The Suggestion

Banisters as they are right now have the ability to extend a half-block downwards. This is an awesome aesthetic ability (and quite useful). However, it would be equally useful to have the same effect going upwards, to prevent situations such as this (pictured below) where having a half-block above such as a slab or stair prevents a clean railing.
![2022-12-15_20 04 40](https://user-images.githubusercontent.com/23658767/208005567-6ba96e2b-78c8-4573-b66e-a0ce48b27415.png)

### Why Should It Be in the Mod?

This ability would greatly increase the versatility of possibly the best wooden block in the mod, without infringing on its core design. I cannot speak for others, but such a feature would be an amazing asset in my builds

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This is currently not something we're thinking would be within the design of the block, but it might be changed at some point still.
