### ISSUE TITLE
Circumventing expected teleportation logic

### ISSUE THREAD

**Issue by Darkhax** [TeamTwilight/twilightforest#171]
Hello,

Sorry for not using your template. This issue doesn't really fit into the format you guys had set out. I have a mod called [Dimension Stages](https://minecraft.curseforge.com/projects/dimension-stages). This mod allows access to dimensions to be completely restricted, until a custom condition set by the modpack has been met. My mod makes use of the [EntityTravelToDimensionEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/event/entity/EntityTravelToDimensionEvent.java) to accomplish this. This event is normally fired by `EntityPlayerMP#changeDimension(int dimension)` however your teleporter block [circumvents this method](https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/block/BlockTFPortal.java#L223) and does not call the event. Could you please use the correct method, or incorporate this event into your custom teleportation logic?

**Comment by bs2609** [comment]
You can't really use `changeDimension` for any custom dimensions, it has hardcoded cases for vanilla dimensions and doesn't let you supply your own teleporter.

It'd be nicer if the event was fired from a better place, but I don't know if that's feasible.

**Comment by AtomicBlom** [comment]
Still, we can add the event in easily enough for our teleport. I'll take a look at it tonight, time permitting.

**Comment by AtomicBlom** [comment]
Naw, sadly changeDimensions is SUPER vanilla specific, but I've added the event in the couple of places it was missed. Willie did add it under other circumstances, but not the main cases.

**Comment by Darkhax** [comment]
Thanks for looking into the issue for me :)
