### ISSUE TITLE
Scepter of Life Draining Death issue

### ISSUE THREAD

**Issue by Jaudr3yy** [TeamTwilight/twilightforest#1714]
Forge version: 36.2.31
Twilight Forest version: twilightforest-1.16.5-4.0.870-universal

Steps to reproduce:
1.  Get the scepter of life draining
2. Kill your friend ;)

What I expected to happen:
The friend dies

What happened instead:
The friend dies, then comes back to life on their side, they can hit players, but nobody can see them. When you die in this state. it completely breaks the game and you cant respawn lol

**Comment by Tamaized** [comment]
1.16.5 is no longer supported. A majority of the bugs from that version got fixed in the 1.17 versions, so is this still a problem on the latest 1.19 versions?

**Comment by GizmoTheMoonPig** [comment]
I fixed this in 19398a461eacc99e2ad03ffc9286c45683600814, which is for 1.19. I was only made aware of the issue a few days before I fixed it so thats why it took me so long to actually fix it
