### ISSUE TITLE
I cannot kill Hydra

### ISSUE THREAD

**Issue by repopon** [TeamTwilight/twilightforest#1715]
### Forge Version

36.2.34

### Twilight Forest Version

4.0.870

### Steps to Reproduce

Just to kill Hydra so you can kill more boss.

### What You Expected

I expected I can use sword and kill Hydra also see his fire breath.

### What Happened Instead

I can’t kill hydra. The hydra has a fire breath but I can’t see it. It opens it mouth and somehow I’m on fire. I used a strong fire resistant potion but still I’m dead. Also I can only attack but hitting his attacks back unlike people I’ve seen who use a sword and hit the mouth. He regenerates very fast even if he didn’t lose a head. It’s hard to explain, but he kills me unusually fast.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
1.16 is no longer supported, however I believe another mod is at play here.
