### ISSUE TITLE
update the download file

### ISSUE THREAD

**Issue by TheDofToca** [TeamTwilight/twilightforest#1717]
### Forge Version

44.0.48

### Twilight Forest Version

4.2.1468

### Steps to Reproduce

1. start to download, but forge minecraft is 1.19.3
2. so it don't work

### What You Expected

it will work

### What Happened Instead

didn't work

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
what?
