### ISSUE TITLE
my client starts to lag when i see a hydra

### ISSUE THREAD

**Issue by JayWJJ** [TeamTwilight/twilightforest#1718]
### Forge Version

36.2.35

### Twilight Forest Version

4.0.870

### Client Log

https://upload.in.ua/ru/7PyBx

### Steps to Reproduce

I approach the hydra to defeat it. As soon as she started releasing fireballs, the game started to lag. When I moved away from her at blocks 70-80, she lost sight of me, and the game stopped lagging. Also, when you turn your head 180 degrees (you stand with your back to it) - the lags disappear

### What You Expected

expected that this would not happen

### What Happened Instead

the game crashes when you get close to the hydra

### Additional Details

the game crashes when you get close to the hydra

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
I can't access the crash report, and version 4.0.870 is not on Curseforge (unless you mean 4.0.860), let alone the latest version of TF on 1.17.1. In the future, please use GitHub Gist as it shows the raw text of the file without an expiration date and only requires a GitHub login.

If the issues continue after updating to 4.0.943 and it can be verified this issue does persist on 1.19.2+, feel free to reopen this issue. However, as of now, the error is on an outdated version of the mod, and an unsupported version of the game.
