### ISSUE TITLE
[Inter-Mod] Geolosys integration for hollow hills

### ISSUE THREAD

**Issue by oitsjustjose** [TeamTwilight/twilightforest#172]
Hey all! 

@Darkosto and I have been talking about ways to get Geolosys working seamlessly in Twilight Forest, and I've already taken the steps to make sure that my ores adjust for the Twilight Forest's lowered sea-level, but there was one last thing we both wanted to see to finalize the integration.

I don't know how difficult it'd be with the current code-base, and I know you guys have much higher priorities than mod-integration, but it would be super cool to see (either via config option or just on by default) hollow hills generate with Geolosys ores rather than vanilla ones, if Geolosys is available. This'd include the both the vanilla-based and mod-based resources (iron being vanilla, copper being modded, if you get the gist) which, in Geolosys, are two different blocks.

[Geolosys is completely open-source](https://github.com/oitsjustjose/Geolosys), so feel free to take a look at whatever you need and tell me how I can help. I just figured that given my options, having you guys integrate would be a less game-breaking and more seamless approach.

Darkosto might have more input on what kinds of patterns he'd be seeking with the Geolosys generation in hollow hills (i.e. maybe only the huge ones would generate certain types of ore), but you'd have to check in with him to see if that's what he feels would be right. I - on the other hand - feel like any sort of generation of my ores would work out just nicely, so I don't necessarily have any preference.

Alright - once again, just let me know *how* I can help and I'm there. Thanks for all of your hard work everyone!

**Comment by AtomicBlom** [comment]
I seem to remember us having a discussion about supporting mod ores in general. It's certainly on our radar, we just need to prioritise it.

**Comment by Darkosto** [comment]
Hey @AtomicBlom I'd like to throw my hat in and offer any testing or help that's needed. Just let me know and I'll give you a hand :)

**Comment by bs2609** [comment]
Should be resolved by #729.
