### ISSUE TITLE
Darkwood sapling grows into canopy tree

### ISSUE THREAD

**Issue by Aliensearcher** [TeamTwilight/twilightforest#1721]
### Forge Version

1.19.2

### Twilight Forest Version

1.19.2

### Steps to Reproduce

Planted single darkwood saplings in overworld
Waited until they grew and harvested them
Got only canopy logs and canopy saplings from them 
Double checked that I definitely had only darkwood saplings 
Planted them again but this time bonemealed them until grown
Got darkwood logs and darkwood saplings 
Tested again planing more and letting them grow on their own
Got only canopy logs and saplings.

### What You Expected

Planted darkwood saplings would grow into darkwood trees 

### What Happened Instead

If I didn't bonemeal them darkwood saplings grow into canopy trees

### Additional Details

I don't have footage but I can record it if required. 
Additional mods include: Biomes O plenty, Create, waystones, travelers backpack, friends and foes, better mineshafts.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Cannot reproduce, both methods of trees grow the same Darkwood Tree.
This is highly likely a result of another mod, or a Canopy Tree Sapling was placed instead and, as a result of confirmation bias, it was believed a Darkwood Tree Sapling was placed.

**Comment by Tamaized** [comment]
I tried to reproduce in the overworld with randomTickSpeed set to 100, but it produced darkwood.

So I believe there's another mod at fault here.
