### ISSUE TITLE
Mushrooms generated around the portal break upon first entering the dimension

### ISSUE THREAD

**Issue by MarioSMB** [TeamTwilight/twilightforest#1722]
### Forge Version

40.2.0

### Twilight Forest Version

4.1.1423

### Steps to Reproduce

1. Open a portal to the Twilight Forest
2. Enter the dimension

### What You Expected

Upon entering the dimension, I expect to see a ring of various plants around the portal.

### What Happened Instead

Mushrooms generated around the portal break and are thrown on the ground or picked up by the player due to the light level of the portal itself being too bright for mushrooms.

### Additional Details

The mushrooms being thrown into the player's inventory makes for a funny first impression in showcases such as this: https://youtu.be/6cH4QPXPwbU?t=240  
I received a "Nah" when mentioning this in previous issues but am deciding to report it properly here as it is a slightly annoying bug that every player who has ever played the mod will see and should probably be addressed, perhaps by making portal generation exclude mushrooms.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
https://github.com/TeamTwilight/twilightforest/issues/1603#issuecomment-1221219948

I'm also not a fan of removing something that's been there for ages. Plus I like it because it's an easy source of mushrooms :stuck_out_tongue:

**Comment by Tamaized** [comment]
Besides if you really don't like it then you can change the tag here.

https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/generated/resources/data/twilightforest/tags/blocks/portal/decoration.json

**Comment by GizmoTheMoonPig** [comment]
generated portals dont actually use the tag, they use a separate hardcoded list of blocks: https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/main/java/twilightforest/world/TFTeleporter.java#L465-L482
I made a comment about turning it into a tag, which I may do in the future, but im keeping mushrooms included by default. I swear ive had this conversation with you before...

**Comment by MarioSMB** [comment]
This was mentioned in a separate report but this bug apparently hasn't been reported before.  

This isn't a personal preference (not using the mod ATM due to #1607), I saw a video showcasing the mod and noticed the bug yet again, realising every single player has encountered it and *noone* has reported it made me decide to formally make an issue on the topic.  
Whether or not it gets solved is up to the developers, it just seems strange to leave a bug in the mod out of some sense of nostalgia - I can assure you nobody wants mushrooms dropped into their inventory when they enter the dimension.
