### ISSUE TITLE
[Suggestion] Multi-block makeup for hollow hill stalactites

### ISSUE THREAD

**Issue by Swedz** [TeamTwilight/twilightforest#1725]
### The Suggestion

Stalactites in Hollow Hills should allow for multiple blocks to form in the same stalactite with varying weights for each block. Here's an idea for how the datapack stalactite json format could change:
```
{
  "max_length": 7,
  "blocks": [
    {
      "block": "twilightforest:liveroot_block",
      "weight": 1
    },
    {
      "block": "twilightforest:root",
      "weight": 9
    }
  ],
  "size_variation": 0.75,
  "weight": 10
}
```
Not necessary to change the "ore" key to "blocks", but might be more clear if the value becomes more generalized.

### Why Should It Be in the Mod?

It allows for more customization with stalactites both by default by TF, but also for pack creators who wish to add extra blocks found in hollow hills.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
added in 9b508acd581ca9ad00231e186add16dc34e527e1. Thank you for the suggestion!
