### ISSUE TITLE
[1.18.2] Optifine Message unable to be interacted with/"proceed" button inert (a bad submission on a technicality, game's not rendering anything yet)

### ISSUE THREAD

**Issue by anonymous2007** [TeamTwilight/twilightforest#1727]
### Forge Version

40.2.0

### Twilight Forest Version

4.1.1494

### Client Log

https://gist.github.com/anonymous2007/74cae55c1f6903e675672288bdea5cec

### Crash Report (if applicable)

Doesn't crash, just "softlocks" the game before the title can open

### Steps to Reproduce

I open the game and wait for it to load. It loads (that's a step!) and The Optifine warning shows up. Can't close it.

### What You Expected

Pressing "Proceed" closes the tab and sends me to the title screen.

### What Happened Instead

Pressing "Proceed" does nothing and the only acknowledgement I get is the button being highlighted when I put my cursor over it; cannot go to title screen.

### Additional Details

This is mostly just a "this is here" report instead of a "pLeAsE FiX ThIs" report, as I'll probably just switch to Oculus+Rubidium, but any recommendations for .toml file openers would be appreciated, as I know there's a config option to remove the screen entirely but cannot utilize it without one (or I'm just a stupid b****, which isn't out of the question)
This bug cannot be replicated without optifine excepting with possible dev tools, so I'm going to mark it as it's still a TF-based problem. Terribly sorry in advance if I shouldn't have put it here.

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by anonymous2007** [comment]
Again, you don't have to act on this, this is just a thing that shouldn't happen. I've already worked around it, however.

**Comment by GizmoTheMoonPig** [comment]
the button was fixed in 1.19. In 1.18, you can either hit the esc key after a few seconds or disable it in the config and itll go away

**Comment by anonymous2007** [comment]
My dumb self never thought of esc lmao, thanks for tolerating my
incompetence :P
