### ISSUE TITLE
"Null" error opon startup 

### ISSUE THREAD

**Issue by MrBlackhole618** [TeamTwilight/twilightforest#1728]
### Forge Version

44.1.0

### Twilight Forest Version

4.2.1468

### Steps to Reproduce

Open up the launcher, The forge error screen tells me that the mod has a "null" error 

### What You Expected

I expected it to open normally. 

### What Happened Instead

I got a crash report from forge. 

### Additional Details

There are other mods installed. But they don't interact with twilight forest at all.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
youre using a 1.19.3 version of forge with a 1.19.2 version of the mod. If you want to play on 1.19.3, youre gonna have to wait until the port is released. We have relatively stable builds on our discord, so if you want to grab one of those for the time being feel free
