### ISSUE TITLE
Excessive mob spawn

### ISSUE THREAD

**Issue by Osorex24** [TeamTwilight/twilightforest#1729]
### Forge Version

36.2.39

### Twilight Forest Version

4.0.870

### Steps to Reproduce

1.Upon entering the dimension
2.-Many pigs appear even though I kill them with commands

### What You Expected

That the mod will work correctly

### What Happened Instead

Many pigs causing lag

### Additional Details

Playing on a server with the abbys II mod

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Unless you mean the Wild Boar mob added by Twilight Forest, Pigs are not set to spawn in any of the biomes. This will be a result of another mod adding in their own spawns, which we do not have any control over.
