### ISSUE TITLE
Crash Caused by Bosses/entities with segments

### ISSUE THREAD

**Issue by ShadeKage** [TeamTwilight/twilightforest#1731]
### Forge Version

43.2.3 (Newest for 1.19.2)

### Twilight Forest Version

4.2.1493 (Though also happens on 4.2.1468, as I swapped to a newer version tryin to fix this)

### Client Log

Listed Below

### Crash Report (if applicable)

Listed Below

### Steps to Reproduce

1: Load into any world
2: Have either the "Naga" boss or "Hydra" boss within your loaded chunks, though this could happen with other entities with several "segments"
3: Instant freeze and crash

### What You Expected

The game should countinue as normal

### What Happened Instead

Crash and frezze

### Additional Details

Below this you'll find the latest.log and the crash report, which will also say which mods are within the mod pack, I have at least checked that no, create mod and its extra add on mods are not the issue causer

There was a post prior I found mentioning this for an older version of forge, but it claimed it was fixed, it clearly was not 
Post in question: https://github.com/TeamTwilight/twilightforest/issues/1634#ref-issue-1428634345

This issue is very confusing, cause as the post above says, its only happening to me in our friend group, the boss being loaded on my screen causes a crash to me, but no one else, and I'm unable to rejoin either till the boss in question is removed
And yes, we all have the exact same version of the game, I'm truly stumped, please help

[latest.log](https://github.com/TeamTwilight/twilightforest/files/10427217/latest.log)

[crash-2023-01-16_10.20.19-client.txt](https://github.com/TeamTwilight/twilightforest/files/10427219/crash-2023-01-16_10.20.19-client.txt)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ShadeKage** [comment]
P.S. i can try to write out a full list of every mod in the pack, and even try to cross off the confirmed non-issue causers, as of me writing Im going to test just the Twilight mod alone to see if the crash also happens

**Comment by ShadeKage** [comment]
Update, it is 100% one of the mods causing the issue, loading just the TF mod and forge doesn't cause the crash, ill be trying to figure out which mod is causing it now on my own end

**Comment by ShadeKage** [comment]
New update, found the mod causing it, Vivecraft, i was thinkin of tryin VR when we made the pack, I tried it once in a test world
Thats also why only I was crashing, i had previously loaded the game in VR before, while my friends have not, I'll be removing the mod so I can continue playing

I'll leave the bug report open as to let the dev see this and maybe implement a fix? or at least add a warning as to not use vivecraft with this mod

Crash report from my testing (I was adding mods back in based from me reading the crash reports from before)
[crash-2023-01-16_10.56.33-client.txt](https://github.com/TeamTwilight/twilightforest/files/10427469/crash-2023-01-16_10.56.33-client.txt)

**Comment by GizmoTheMoonPig** [comment]
yeah vivecraft is a known incompatibility, they make unsafe assumptions about multipart entities that we have no control over. Closing as this isnt our issue. 
You can follow the report over on their github if you want to get updates about it: https://github.com/ferriarnus/VivecraftMod/issues/100
