### ISSUE TITLE
Moss Patch texture is added to all atlases in the game

### ISSUE THREAD

**Issue by TelepathicGrunt** [TeamTwilight/twilightforest#1734]
### Forge Version

43.2.3

### Twilight Forest Version

4.2.1493

### Steps to Reproduce

Download Atlas Viewer mod. 

Run game with Twilight Forest

Press V to open Atleas Viewer screen (rebind any key to v that is conflicting)

View every atlas and notice that the Moss Patch block texture from Twilight Forest is in all atlases. Even modde dones

![image](https://user-images.githubusercontent.com/40846040/213818179-31b3b1af-4240-4809-9e23-75f9dbf40760.png)

![image](https://user-images.githubusercontent.com/40846040/213818312-18a71c7e-a777-4f20-b346-54ae2cce842f.png)

![image](https://user-images.githubusercontent.com/40846040/213818323-54e2d1aa-8767-4af3-b0bc-fee682c2eae7.png)

### What You Expected

Moss Patch block texture only exist in Block Atlas

### What Happened Instead

Moss Patch texture is added to all atlases

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
forge, fabric, or both?

**Comment by Tamaized** [comment]
Both

**Comment by GizmoTheMoonPig** [comment]
fixed in 23226810e5a7b5c00072368b5ccadfca6938c7dd. This isnt an issue in 1.19.3 thanks to a change in how atlases work. I'll push a build for this at some point
