### ISSUE TITLE
Twilight forest portal bug 1.16.5 

### ISSUE THREAD

**Issue by Thunderrock424242** [TeamTwilight/twilightforest#1735]
### Forge Version

36.2.34

### Twilight Forest Version

4.0.870

### Steps to Reproduce

1. make the portal
2. go through walk around a bit
3. go back through and it will create a 3rd portal 500 blocks away from original 

### What You Expected

I expected to come out of the portal i went through the one that i built at my base and just have 2 portals.

### What Happened Instead

it created a portal 500 blocks away i destroyed that one went through and it recreated it.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
known issue, see #1459
