### ISSUE TITLE
Game Crashed going into Swamp Biome now save is borked (Valhesia 5 ModPack)

### ISSUE THREAD

**Issue by Deathefrog** [TeamTwilight/twilightforest#1736]
### Forge Version

43.1.43

### Twilight Forest Version

4.2.1421

### Crash Report (if applicable)

https://gist.github.com/Deathefrog/12704c86fc3fa8e05b321fddf050b807

### Steps to Reproduce

1. Was walking at the edges of the forest between the snowy/cold biome and the swamp biome (both currently locked).  
2. Attacked suddenly by swarm of mosquitos.
3. Killed said mosquitos.
4. Turned and took three steps away from swamp and game imploded.
5. Crashy saved it and went to title screen - I loaded the game again.  World generated, got one brief flash of tree and BAM  - crash and save.  Happened 3 more times so now this save is toast.

### What You Expected

I expected to turn around from getting molested by a bunch of mosquitos I didn't mean to aggro and continue to try to figure out WTF I was supposed to be doing besides trying to curb stomp the squirrels.  Frigging crusty little rodents.

### What Happened Instead

Brown Screen of Death and I am afraid now I can't save this world and I am Not Happy About This.

### Additional Details

If you need more info I can definitely try to dig up the log but I work 14 hour days at a crap job with 'college educated' middle aged toddlers making it feel like I'm herding cats.  Please help me save my one ray of vague happiness.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
As far as I can tell, something corrupted the Vertex Buffer pipeline. Could be anything.
It just so happened that the corruption happened while rendering a firefly.

Is this reproducible without any other mods?

**Comment by Deathefrog** [comment]
I managed to fix it.  I rebooted the game after running a repair on it,
sacrificed a goat, screamed into the Void and fired up my game.
Immediately dumped all fireflies and cicadas I had on me - fixed save.

Hasn't happened again but I haven't even stood near a firefly so....

**Comment by Tamaized** [comment]
I'll go ahead and close this as assuming its another mod's fault.

**Comment by Deathefrog** [comment]
I haven't been able to reproduce it again but if it does happen, I'll let
team Valhesia know.  Thanks!
