### ISSUE TITLE
Peaceful Mode Monster Despawn

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#174]
Forge version: 14.22.0.2467
Twilight Forest version: 2.4.0.63
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Have your world on any difficulty aside from Peaceful.
2. Spawn in/generate a Hydra, Phantom Knight, Twilight Wraith, or Naga.
3. The Hydra, Phantom Knight, and Twilight Wraith wont despawn.
4. The Naga will despawn but leave its model behind.

What I expected to happen:
The listed mobs to despawn upon setting the difficulty to Peaceful.

What happened instead:
They were still in the world set to Peaceful mode.

**Comment by Andromander** [comment]
My assumption for the Hydra not despawning is because the Enderdragon does not despawn in Peaceful mode, and the Hydra has similar coding to the Enderdragon. Only a theory though
