### ISSUE TITLE
Twilight Forest failed to load correctly when opening

### ISSUE THREAD

**Issue by ZalazarAxath** [TeamTwilight/twilightforest#1740]
### Forge Version

1.19.3-forge-44.1.0

### Twilight Forest Version

twilightforest-1.19.2-4.2.1493-universal

### Crash Report (if applicable)

https://gist.github.com/ZalazarAxath/b983f9ac9ec987b416810ad2b5c86590

### Steps to Reproduce

1. Download stated version of forge.
2. Install Twilight Forest and all other mods found in the crash report.
3. Open Minecraft, if correctly reproduced, Twilight Forest will not load correctly when Minecraft is opened. I was able to reproduce this offline.

### What You Expected

I expected Twilight Forest to load correctly.

### What Happened Instead

Twilight Forest did not load correctly.

### Additional Details

[2023-02-04 12-48-12.zip](https://github.com/TeamTwilight/twilightforest/files/10609309/2023-02-04.12-48-12.zip)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
You can't run twilight forest 1.19.2 on forge 1.19.3. Grab the 1.19.3 build off curseforge instead
