### ISSUE TITLE
Crash with oculus $$13 is null (twilightforest:render)

### ISSUE THREAD

**Issue by thekoot** [TeamTwilight/twilightforest#1741]
### Forge Version

4.2.0

### Twilight Forest Version

4.4.1494

### Crash Report (if applicable)

https://gist.github.com/thekoot/8064daa7eb98b920bd3f8fdbd139acd9

### Steps to Reproduce

MC 18.2

Portal into the twilight forest and after a few minutes the game will crash. Also if you walk into an oh the biomes you'll go biome, near a witchhazel tree or interact with one (ie. cut one down) the game will freeze and crash. I suspected this could also be a  BYG issue but reading the logs twilightforest is mentioned in the error log every time. 

### What You Expected

The game not to crash.

### What Happened Instead

The game crashed. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
I would say whatever mod `net.coderbot.batchedentityrendering` is, is at fault.

**Comment by thekoot** [comment]
> net.coderbot.batchedentityrendering

Thanks! Gives me somewhere to start!

**Comment by TropheusJ** [comment]
that's iris/oculus

**Comment by thekoot** [comment]
> that's iris/oculus

Thanks!
