### ISSUE TITLE
[1.18.2] Escessive tick lag in Twilight Forest

### ISSUE THREAD

**Issue by Reshy** [TeamTwilight/twilightforest#1743]
### Forge Version

40.2.1

### Twilight Forest Version

 twilightforest-1.18.2-4.1.1494-universal.jar

### Client Log

https://gist.github.com/Reshy/3c360fd9aaf2bcfd017a947ac3218302

### Steps to Reproduce

Unsure.

### What You Expected

The tick lag shouldn't be so extreme specifically in twilight forest, and there is no clear culprits.

### What Happened Instead

Extreme tick lag, no matter what steps taken it was a struggle to get it above 10 ticks/sec.

### Additional Details

![image](https://user-images.githubusercontent.com/2096384/218081809-20fa9bd0-092d-4c37-821e-96e06fa285d0.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This issue has been fixed in a newer version of TF. We dont backport changes as we're all extremely limited on time, so I would recommend either updating to 1.19 or removing TF. Sorry I cant give you an answer im sure you want to hear

**Comment by Reshy** [comment]
Unfortunately, the mod I wish to use is unlikely to be updated to 1.19 in the near future so I'll remove it instead.
