### ISSUE TITLE
houses underground

### ISSUE THREAD

**Issue by Thunderrock424242** [TeamTwilight/twilightforest#1747]
### Forge Version

40.2.0

### Twilight Forest Version

1.18.2

### Steps to Reproduce

1. go to the forest 
2. 2. you might find some houses generate underground

### What You Expected

to see a normal house above ground

### What Happened Instead

the house was underground.

### Additional Details

i am making a modpack so idk if its a world gen issue even tho this mod is its own dimmension

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
can you send a screenshot of this happening? I've never seen this happen before

**Comment by Thunderrock424242** [comment]
sure i will send it in a couple hours
