### ISSUE TITLE
/kill command for Hydra does not work

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#175]
Forge version: 14.22.0.2479
Twilight Forest version: 2.4.0.63

Steps to reproduce:
1. Spawn a Hydra
2. Input `/kill @e[type=twilightforest:Hydra]`

What I expected to happen:
The Hydra (and any other existing Hydra) will be instantly killed
What happened instead:
Nothing happens. The game executes the command, but the Hydra remains. However, if `kill @e[type=!Player]` is input, the command successfully executes, but the game says it killed the Hydra and all of the heads, even those that do not exist yet, individually.

**Comment by Drullkus** [comment]
Doesn't work for some others including the Lich too

**Comment by Andromander** [comment]
The Lich seems to be immune to /kill commands unless he is shieldless

**Comment by Sonicwave** [comment]
Interestingly, "/kill @e[type=twilightforest:hydra_head,c=1]" will kill off the entire Hydra even when only one head is selected.
