### ISSUE TITLE
[1.19.2] Game crashes when entering the twilight forest

### ISSUE THREAD

**Issue by tvoklov** [TeamTwilight/twilightforest#1755]
### Forge Version

43.2.4

### Twilight Forest Version

4.2.1518

### Crash Report (if applicable)

https://gist.github.com/tvoklov/136599c742e9915963b05d08f9c69444

### Steps to Reproduce

1. Join the server
2. Enter the twilight forest portal
3. Run around a bit (the player specifically said something about approaching a dark forest)

### What You Expected

The game doesn't crash

### What Happened Instead

The game crashed

### Additional Details

This happened on a server (if it matters at all), but the server doesn't have any logs about it (the crash does happen on the render thread, so this makes sense).

Here's a tl;dr of the crash report:
  class twilightforest.entity.SpikeBlock cannot be cast to class twilightforest.entity.monster.BlockChainGoblin

The player's client will keep crashing if they log back on the server, until they are transferred from the twilight forest (by editing the playerdata files). Seems to me that there's some mob that, when rendered, makes a broken cast to another class.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this is unfortunately a vivecraft issue, nothing we can do about it. Theyre doing some unsafe casts where they shouldnt be
