### ISSUE TITLE
[1.19.3] Hedge Mazes are sometimes missing canopy trees on entrances 

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1756]
### Forge Version

44.1.17

### Twilight Forest Version

4.2.1604

### Steps to Reproduce

1. Locate the entrances to a hedge maze

### What You Expected

Typically (to my knowledge) hedge mazes always have two canopy trees on their entrances, one per side.

### What Happened Instead

Occasionally one of the two trees will be replaced by hedge, and the entrance can occasionally be a bit narrower than it should (my assumption is a dead end is overwriting the tree)
Attached are screenshots of this occurrence
![2023-02-21_18 16 04](https://user-images.githubusercontent.com/23658767/220494179-bbb6f771-f6c6-4982-b2b6-6e0569125377.png)
![2023-02-21_18 16 09](https://user-images.githubusercontent.com/23658767/220494215-23b07866-f452-4c61-ade3-dd46decdf254.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Duplicate #1746
