### ISSUE TITLE
game crash?

### ISSUE THREAD

**Issue by Ethan1903c** [TeamTwilight/twilightforest#1761]
### Forge Version

43.2.0

### Twilight Forest Version

4.2.1518

### Client Log

https://gist.github.com/Ethan1903c/3d3d8dae787f5465caf6e9fea313a2a4

### Steps to Reproduce

change language english > chinese

### What You Expected

chinese language games work fine

### What Happened Instead

English language games work fine

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- 
![MOD](https://user-images.githubusercontent.com/126200697/221041799-56bd2188-9403-4651-b244-7a61900327a2.png)

**Comment by Andromander** [comment]
You have run out of memory, this is caused by not allocating enough RAM to the game.

**Comment by Ethan1903c** [comment]
> 您的內存不足，這是由於沒有為遊戲分配足夠的 RAM 造成的。

thank you
