### ISSUE TITLE
Naga boss not dropping loot.

### ISSUE THREAD

**Issue by ItzMaCade** [TeamTwilight/twilightforest#1763]
Basicly im in 1.19.2 better minecraft mod pack and i killed 2 nagas and they dropped nothing both times. Ive killed most mobs and they all dropped somthing but when i kill the naga nothing drops. I dont know if it will happen with other bosses but any ideas?

**Comment by Toastr125** [comment]
It spawns the drops in a chest, which will be either where you killed the boss or where it spawned (in the center of the courtyard)
