### ISSUE TITLE
Alpha Yeti spawners generating off center

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest#1764]
### Forge Version

44.1.8

### Twilight Forest Version

4.2.1604

### Steps to Reproduce

Find a yeti cave

### What You Expected

To find an alpha yeti spawner in the center

### What Happened Instead

Alpha yeti spawner generates off to one corner

### Additional Details

Image is a bit dark but the spawner is visible
![2023-02-25_17 34 45](https://user-images.githubusercontent.com/105689931/221384518-4c827791-322e-4f6c-bf07-ed6fe46e41e1.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Most likely related to #1757
