### ISSUE TITLE
Magic/Maze map doesn't draw correctly and shows completely blank (caused by Optifine)

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#177]
Forge version: 14.22.1.2478
Twilight Forest version: 2.4.0.73 (MC 1.12.1)

When I take an Empty Magic or Maze Map from the Creative inventory (or craft one in Survival) and right-click it, it will often give me a completely blank map. This map doesn't fill up even when I move around. If I use a vanilla map and then a Magic Map, the Magic Map sometimes draws, but appears exactly the same as the vanilla map. This happened on several different worlds that I created in 1.12.1.

**Comment by Sonicwave** [comment]
Forgot to search for already closed issues; seems like this is a duplicate of https://github.com/TeamTwilight/twilightforest/issues/29

**Comment by williewillus** [comment]
does it work on the newest builds?

**Comment by Tamaized** [comment]
~~No this was introduced when the forge PR hit~~

**Comment by williewillus** [comment]
? do you mean this is a valid bug? If so I can't reproduce.

**Comment by Andromander** [comment]
I think a vanilla map needs to be opened first, then a tf map needs to be opened

**Comment by Tamaized** [comment]
~~Odd, I've seen this issue in both old worlds and new worlds, I actually haven't seen the map working correctly once since.~~

Turns out my forge version was wrong (oops)
Maps are working perfectly fine for me

**Comment by williewillus** [comment]
The fix breaks all old maps, and I can't reproduce the issue with new ones (making vanilla then TF)

**Comment by Sonicwave** [comment]
It also works on Forge 14.22.1.2485 (latest). Using a vanilla map first occasionally causes the Magic map to simply duplicate the vanilla map, but it won't be updated (including the location marker). I might try to make a video of this issue.

**Comment by Sonicwave** [comment]
I made a [Youtube video](https://youtu.be/rPrasFt1VCI) of the issue; it's laggy and not the best, but hopefully you get the general idea. This was in a newly generated world in Minecraft Forge 14.22.1.2478 and TF 1.12.1-2.4.0.73-universal; the other mods I'm using are CTM-MC1.12-0.2.2.7 and OptiFine_1.12.1_HD_U_C5.

You can see that the first maps I created did draw, but they looked exactly the same as the vanilla map and had no structure icon (despite me being inside a Naga courtyard).

**Comment by Sonicwave** [comment]
Actually this issue seems to no longer occur, at least with TF 3.2.192, Optifine HD_U_C6 and a newly generated world. I'll test more over the next few days; if this is indeed fixed we wouldn't have to tell people that Optifine is incompatible anymore :P
