### ISSUE TITLE
Moonworms disappear when looking straight down

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest#1770]
### Forge Version

44.1.8

### Twilight Forest Version

4.2.1616

### Steps to Reproduce

Place a moonworm

### What You Expected

To see the moonworm

### What Happened Instead

Moonworm disappears when looking straight down

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
I cant get this to happen with just TF. Do you have any performance mods installed by any chance?

**Comment by ToasterStrudel95** [comment]
> I cant get this to happen with just TF. Do you have any performance mods installed by any chance?

I do not. Every time I have a bug, I test it with a pure TF instance before reporting.

**Comment by ToasterStrudel95** [comment]
It's a 1.19.3 thing.
