### ISSUE TITLE
[Suggestion] Gauntlet of Creation, Giant Castle, and Giant Crafting Bench.

### ISSUE THREAD

**Issue by Puckuchu** [TeamTwilight/twilightforest#1774]
### The Suggestion

The Gauntlet of Creation is an item that would allow the player to place Giant variance of many more blocks (however many variance within reason) including Cobble, Oak logs, Oak Planks, Leaves, and Obsidian. and can be found in a Giant Castle. A Giant crafting bench can be found within the Castle as well that allows the creation of Giant Stairs, etc.

> The Giant Castle.

- The Castle would be floating somewhere remote, the best way to find it, and only way to access it, is with a map found on one of the 4 Giant Islands surrounding the final Castle.
- the player finds the Gauntlet of Creation, and Giant Crafting Bench as the prize inside the Castle.
- the structure can only be accessed with the map acting as a sort of right of entry or key. Where this new structure introduces new Giant block variance within itself.
- Perhaps this structure is found in the middle of the Twilight Lake biome floating above it.
- The other Giant block variance I would make it out of are Stone Bricks, Bricks, Oak Planks, and Glass. where the 4 original Giant blocks could be found within the structure as well.

> The Giant Crafting Bench.
- The Crafting Bench would let you do just that. (with limits obviously.)
- it would let you create Giant Planks from Giant logs, Create Giant Cobble Stairs from Giant Cobble, etc. maybe even let you convert stacks of blocks directly into Giant variance.
- it would also be the new way of crafting Giant Pickaxes, Swords, and maybe be the only way to obtain a Giant Axe and Shovel.

> The Gauntlet of Creation
- The Gauntlet would be held in the players hand in order to use it. while holding the Gauntlet, you'll have 4 times more placement range, and see a grid for where it's possible to place the blocks. 
- since the blocks themselves are 4 times the size of a normal blocks, it is only reasonable for the Gauntlet to give the player more range to place them. 
- there is no other benefits to holding the gauntlet other than the creation of Giant block variance.

> The Gauntlets functionality.
- The Functionality of the Gauntlet is simple and straight forward. Left click to bring up a GUI. right click to place blocks.
- left clicking with the gauntlet would bring up a radial or a GUI that allows the selection of an assortment of Giant blocks. or just the default 4 that are already in the mod.
- Right clicking would place the selected block. the ghost of where the block would be placed would highlight red when it's not a valid placement, and would look transparent and normal when it's a valid placement.
- The block will highlight red if you don't have the required 64 stack of blocks in your inventory, or don't have Giant blocks in your Inventory.

> Other ideas.
- When holding the Gauntlet, you can sneak and click a chest to have the gauntlet absorb (only 64 stacks) of legal blocks into itself and be able to place them.
- the player may also be able to sneak and punch a chest to deposit (only 64 stacks) of blocks back into the container, this would make the gauntlet double as a type of storage. but the limit should be somewhere around 64 of each type of Giant block, in the Gauntlet at one time.
- holding the Gauntlet in your off-hand and using a Giant Pickaxe should also let the mined blocks, if possible, go directly into the Gauntlet.
- within the Giants Castle. the player might encounter a Cake or Cookie called 'Eat_Me' that makes them increase to the size of a Giant for a short time. and maybe even a vial of purple liquid called 'Drink_Me' that shrinks the player down 4 times their normal height (a half slab tall).
- Have the ability to crush the Giant Blocks into Diced versions (Diced Obsidian, Diced Cobblestone.) which is the Giant block textures on normal blocks. so maybe instead of having to craft Giant stairs, you could build them using the Diced variance of blocks.

### Why Should It Be in the Mod?

There's so much potential within the Giant Blocks, and other Giant mechanics. and as a fantasy Dimension I think it's really fitting. I know for builders, they'd love this a lot, I'd love it a lot that's for sure. It's a lot to add, but I would be grateful for it.

### Please Read and Confirm the Following

- [x] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
Thank you for your suggestion, but this would be more suited for an addon mod and it feels out of the scope of the main mod.
