### ISSUE TITLE
Naga not receiving damage

### ISSUE THREAD

**Issue by floppacoolestflop** [TeamTwilight/twilightforest#1776]
### Forge Version

45.0.20

### Twilight Forest Version

twilightforest-1.19.4-4.2.1641-universal

### Steps to Reproduce

1: go to naga labyrinth or creative mode
2: let naga spawn or spawn it with an spawn egg
3: attack it 

### What You Expected

I fighting naga normally, with it receiving damage from my attacks 

### What Happened Instead

naga does not take damage 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by floppacoolestflop** [comment]
quick reminder that i will go to school from 1 pm to 4pm (brazil time) so i wont be able to close the issue at this time

**Comment by EvergreenSystems** [comment]
Confirmed that the naga does not take damage from any source, it is impossible for the player to deal any form of damage to the naga (1.19.4-4.2.1643)
