### ISSUE TITLE
Exception loading model

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1778]
### Forge Version

14.23.5.2860

### Twilight Forest Version

twilightforest-1.12.2-3.11.1021-universal

### Client Log

https://gist.github.com/SegoItCh/3e04c59002f272becd21683e1456d5da

### Steps to Reproduce

Run game

### What You Expected

No exceptions at least

### What Happened Instead

Exceptions :c

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Not a bug, see #711. We have the textures made in newer versions. 1.12 hasn't been supported for years

**Comment by ghost** [comment]
So you can't backport textures?

**Comment by GizmoTheMoonPig** [comment]
That's not exactly all it is. We also need to do some code bits to properly get them working, but as I said before, we don't support 1.12 anymore and haven't for years

**Comment by ghost** [comment]
But I can do this If will have enough skill?
