### ISSUE TITLE
Sorting Tree Not Working

### ISSUE THREAD

**Issue by JosiahGertz** [TeamTwilight/twilightforest#1779]
### Forge Version

44.1.12

### Twilight Forest Version

4.2.1620

### Steps to Reproduce

1. Plant a sorting tree sapling on a block of dirt.
2. Use bone meal to grow the sorting tree.
3. Right-click the sortingwood engine so the eye is open.
4. Place two double chests within seven blocks of the tree.
5. Place a variety of items in the chests.

### What You Expected

That the items would be sorted.

### What Happened Instead

The items wouldn't change position. Items that should have been combined into one stack stayed separate. Nothing happened.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Not a bug, the sorting core was entirely reworked. The core now takes items from chests in its vicinity (5x5x5 area around the core) as input and transfers it into any inventory it finds in a 33x33x33 radius around itself that contains the same item. If you were looking at the wiki page, its very outdated and none of us have had time to update it

**Comment by JosiahGertz** [comment]
Ah, thank you so much. I was really confused.
