### ISSUE TITLE
Remove mod make my world cant enter

### ISSUE THREAD

**Issue by BatafuraiS** [TeamTwilight/twilightforest#1780]
### Forge Version

44.1.23

### Twilight Forest Version

4.2.1620

### Client Log

https://gist.github.com/BatafuraiS/f81d512936c29a4eb12f35321441368d

### Steps to Reproduce

1 Enter the wolrd play normally 
2 I just remove mods form mod folder
and now i cant play if twl mods not in mods forlder 
i just want to deleted mods

### What You Expected

i just want to deleted mods and play vanila minecraft

### What Happened Instead

Cant enter the world

### Additional Details

![bukcd](https://user-images.githubusercontent.com/129674761/229360556-c425255f-f69e-49a6-b1f1-3c31f98d80ef.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this is unfortunately something we cant fix (vanilla bug). There is a workaround, however. 
Download NBTExplorer, open the level.dat file in your world's folder, navigate to `Data -> WorldGenSettings -> dimensions` and delete the `twilightforest:twilight_forest` and save the file. Please note that reopening a world after removing mods (especially all of them!) will cause many other issues, as modded worlds dont convert to vanilla worlds very well.
