### ISSUE TITLE
failed to load correctly

### ISSUE THREAD

**Issue by BookMantheGamer** [TeamTwilight/twilightforest#1781]
### Forge Version

forge-1.19.4-45.0.41-universal

### Twilight Forest Version

twilightforest-1.19.3-4.2.1620

### Client Log

https://gist.github.com/BookMantheGamer/666a80eb1c6364ea05c1f9213d3d0699#file-latest-log

### Crash Report (if applicable)

https://gist.github.com/BookMantheGamer/666a80eb1c6364ea05c1f9213d3d0699#file-crash-2023-04-05_02-05-41-fml-txt

### Steps to Reproduce

open mincraft luancher 
press play 
fail to load

### What You Expected

i expected to be able to load into the main menu

### What Happened Instead

it showd a screen sayin that twilight forest could not load

### Additional Details

![Capture](https://user-images.githubusercontent.com/129936501/230014017-3a4f1e48-588f-4788-82aa-a72478732cc4.PNG)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
You cannot use a 1.19.3 mod on 1.19.4.

**Comment by BookMantheGamer** [comment]
ah thank you
