### ISSUE TITLE
Visual: Tier 0 harvest level description become tconstruct.harvest_tier.twilightforest.ice

### ISSUE THREAD

**Issue by Deadmanovi4** [TeamTwilight/twilightforest#1783]
### Forge Version

40.2.1

### Twilight Forest Version

4.1.1494

### Steps to Reproduce

1. Download both Twilight Forest and Tinkers Construct. 
2. Download WTHIT Harvestability (with dependencies: WTHIT and badpackets) or any tool to show block harvest level.
3. Start a new game or launch a existed one.
4. Look at any block with tier 0 harvest level (stone, grass, leaves etc.)
Issue starts here.

### What You Expected

See harvest level correctly

### What Happened Instead

See stat.tconstruct.harvest_tier.twilightforest.ice

### Additional Details

Issue screenshot - https://prnt.sc/LPOnKz4HZwwh
debug.log - https://pastebin.com/ajG9mzd4
latest.log - https://pastebin.com/p7yyk0f6

Followed from here:
https://github.com/SlimeKnights/TinkersConstruct/issues/5125

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Carphent** [comment]
Is there any known patches to apply to any config files or the JAR itself?

**Comment by GizmoTheMoonPig** [comment]
its worth noting this is purely a visual issue. Having our tiers like this doesnt affect gameplay at all, this was purely an issue with WTHIT. Regardless, wont be a problem anymore in 1.19.4+
