### ISSUE TITLE
Can't break blocks

### ISSUE THREAD

**Issue by DizzeeThugg** [TeamTwilight/twilightforest#1787]
### Forge Version

1.19.2

### Twilight Forest Version

4.2.1518

### Steps to Reproduce

1. Patched myself in a 1x2 hole and am unable to break blocks to get out.
2. When breaking blocks, green sparkles pop up and the block replaces.

### What You Expected

I expected to be able to dig out of the hole made out of blocks that I placed.

### What Happened Instead

I am locked in and can't break the blocks to get out.

### Additional Details

![2023-04-21_15 26 20](https://user-images.githubusercontent.com/131488071/233718863-f9885d7e-8386-4905-85d5-24016fa5e481.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
judging from your minimap, it looks like you might be right above a troll cave. im pretty sure the bounding box for the troll cave extends all the way to the sky because of the giant cloud, but i'll need to double check. I'll look into this regardless.

**Comment by Tamaized** [comment]
@GizmoTheMoonPig poke

**Comment by DizzeeThugg** [comment]
Was not able to break any blocks to get out, but i had a friend come to my location and bring ender pearls to glitch myself out. I guess just be careful where you box yourself in!
