### ISSUE TITLE
Crash in 1.11

### ISSUE THREAD

**Issue by forestbat** [TeamTwilight/twilightforest#179]
Forge version: 13.20.1.2476
Twilight Forest version: twilightforest-1.11.2-2.4.0.144-universal
Link to crash log: http://paste.ubuntu.com/25620574/

Steps to reproduce:
1. Press shift on items，such as seeing tooltip of TE‘s ’capacitor or Psi's CAD，even get a whole stack of items will lead to crash of MC。
2.Or picking up many items can also incur the crash。
What I expected to happen:
I hope the mod won't crash when I want to see tooltips or pick up items。
What happened instead:

**Comment by Tamaized** [comment]
This was already fixed in the 1.12 branch.

**Comment by forestbat** [comment]
@Tamaized I can't change MC version temporarily，some mods I like haven't updated yet。
