### ISSUE TITLE
Lich Shield Rendering

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#1790]
### Forge Version

45.0.46

### Twilight Forest Version

4.2.1660

### Steps to Reproduce

Look at the Lich.

### What You Expected

No fashion lines on the shields.

### What Happened Instead

Several dresscode violations.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Fix via [94bf744](https://github.com/TeamTwilight/twilightforest/commit/94bf744ff708f700c14f6295aec4c24f9ece7de4)
