### ISSUE TITLE
[Suggestion] Configure What SkeleDruid Projectile (Nature Bolt) can turn into birch leaves

### ISSUE THREAD

**Issue by MCJEModder2026** [TeamTwilight/twilightforest#1792]
### The Suggestion

the name says it all
maybe a whitelist or blacklist of blocks or configureable hardness

### Why Should It Be in the Mod?

i dont want skeledruids destroying my hard work esspecially hard to get blocks or chisels and bits blocks

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
decided to make it a whitelist, you can add blocks to the new tag `twilightforest:druid_projectile_replaceable` in 1.19.4+ as needed

**Comment by MCJEModder2026** [comment]
will this be in 1.18.2 for people making reasonable modpacks?

**Comment by GizmoTheMoonPig** [comment]
No, nothing below 1.19.4 is supported anymore. We don't have the time or resources to backport anything
