### ISSUE TITLE
[1.19.2] Fireflies Don't Work in Curio Slot

### ISSUE THREAD

**Issue by Flexico** [TeamTwilight/twilightforest#1796]
### Forge Version

43.1.52

### Twilight Forest Version

4.2.1468

### Steps to Reproduce

Enter Twilight Forest, collect a firefly, put it in your helmet slot, and it lights up the world around you, but if you choose the Curio "Head" slot, it can be put in, but doesn't spread any light.

### What You Expected

Firefly glow!

### What Happened Instead

Firefly no glow :(

### Additional Details

Optifine is required for the dynamic lights to work! If I remove it, neither slot works.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
We don't support Optifine related issues. Please read the checkboxes before actually selecting them

**Comment by Flexico** [comment]
Great, the Curio people sent me here, now to Optifine. ><

**Comment by Flexico** [comment]
Curious, if the fireflies in the head slot don't actually glow with only TF installed, what is their purpose?

**Comment by GizmoTheMoonPig** [comment]
because its funny

**Comment by Flexico** [comment]
Oh, ok! So Optifine were the people who decided to make it a dynamic light source! That is helpful, thanks~
