### ISSUE TITLE
License unclear regarding redistribution of .jar file

### ISSUE THREAD

**Issue by copygirl** [TeamTwilight/twilightforest#1798]
I just checked the page for a modpack of mine on Modrinth. After having been accepted 8 months ago, it has now been rejected again due to licensing issues regarding The Twilight Forest mod. I'll just paste the message in full:

> It has come to our attention that Twilight Forest cannot be redistributed in our modpacks due to containing assets that are licensed All Rights Reserved. It passed initial approval because the mod was mistakenly labeled solely as LGPL on CurseForge and in the mod's metadata. This means that for now Twilight Forest won't be able to be used in modpacks.

While it doesn't currently affect me – I've stopped updating the pack and I don't mind its page being down – this mod is clearly one of the most popular and long-lived mods out there, and there will be a lot of other modpack creators who would like to include your mod in one of their packs not hosted on CurseForge.

It would be greatly appreciated if you could clearly state the redistribution permissions for the .jar file somewhere, contact the Modrinth moderators for manual approval, and/or upload the mod to Modrinth.

Many thanks for hearing me out, and for your continued work on this gem of a mod. :green_heart:

**Comment by Andromander** [comment]
Full terms of the License can be found can be found [here](https://github.com/TeamTwilight/twilightforest/blob/1.19.x/README.md#licensing). The license on Curseforge will be updated in due time as none of us had the permission on the site to update it.

We are currently not considering uploading Twilight Forest to Modrinth at present.

**Comment by copygirl** [comment]
From the sound of it you are saying redistribution (and therefore inclusion in non-CurseForge packs) is not allowed?

The terms are likely why the Modrinth team decided to pull the "redistribution permissible flag" from their system for the Twilight Forest mod, essentially taking down any pack that used the mod; with the only options for their creators being removing the mod (affecting players) or getting explicit permission.

Would you consider giving permission case-by-case, or perhaps as a whole for all Modrinth packs?

**Comment by GizmoTheMoonPig** [comment]
For now we aren't giving explicit permission to include the mod in modrinth packs. This may change in the future, but for now it's easier to just say no. I'm sorry if this is inconvenient. 
We have updated the Curseforge license to hopefully prevent any further confusion regarding this. Thanks for taking the time to bring this up, we appreciate it!
