### ISSUE TITLE
Uncrafting table's "targeted block" outline is transparent

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest#1799]
### Forge Version

45.0.49

### Twilight Forest Version

4.2.1681

### Steps to Reproduce

Place an uncrafting table
Target it

### What You Expected

A black outline to appear to indicate you're targeting the block

### What Happened Instead

A transparent outline appears instead

### Additional Details

![Uploading 2023-05-07_11.06.26.png…]()

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this is something I cant fix as vanilla draws the collision box like this on transparent blocks. Youll notice it happens with glass if you look close enough. We rely on using the translucent rendertype to properly render the glow of the uncrafting table so this is unavoidable unfortunately
