### ISSUE TITLE
Amethyst clusters do not recognize twilight forest pickaxes as pickaxes

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest#1801]
### Forge Version

45.0.50

### Twilight Forest Version

4.2.1681

### Steps to Reproduce

Find an amethyst cluster
Mine said cluster with any twilight forest pickaxe without silk touch

### What You Expected

For four or more amethyst shards to drop

### What Happened Instead

Only two shards drop

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
seems to be tied to 
![image](https://user-images.githubusercontent.com/67203206/236732674-77761e9b-792e-4386-be3f-a70b14731215.png)
