### ISSUE TITLE
[Suggestion] 1.18 Config option for void Twilight Forest generation

### ISSUE THREAD

**Issue by pantsguyapp** [TeamTwilight/twilightforest#1803]
### The Suggestion

I've wanting to generate a void TF and build a skyblock world there, unfortunately there are no methods that allow me to do so.

### Why Should It Be in the Mod?

Because I have a potato laptop and normal TF is too laggy for me to enjoy with my modpack (the modpack is very heavy ans cannot be dismantled either.)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
In the current day and age of modding this can be accomplished with a datapack. Because of that, we're currently not too keen on bundling it into the main mod again.
