### ISSUE TITLE
[Enhancement] Config to allow any item to be dropped into pool to use activate gate

### ISSUE THREAD

**Issue by Vyraal1** [TeamTwilight/twilightforest#181]
If this feature is no longer relevant or mechanic is no longer used, please feel free to delete. But older versions of TF I recall that it needed to be a diamond to unlock TF, which could be too early or too late depending on the modpack. Can there be a config or a TF only item (that can be CraftTweakered) that is dropped into the pool instead to open the gate? This would grant other modpack makers a lot more flexibility when adding Twilight Forest to their pack.

**Comment by Shadows-of-Fire** [comment]
This configuration has already been implemented

**Comment by Drullkus** [comment]
Already a thing, enhanced by #167

Look at your config file lol
