### ISSUE TITLE
Uncrafting table does not show breaking texture

### ISSUE THREAD

**Issue by kodadacod** [TeamTwilight/twilightforest#1810]
### Forge Version

45.0.57

### Twilight Forest Version

4.2.1681

### Steps to Reproduce

Place an Uncrafting Table
Start breaking it in survival mode

### What You Expected

The breaking texture would display

### What Happened Instead

The breaking texture did not display at any angle during the animation

### Additional Details

https://streamable.com/si4kt7

![2023-05-10_19 45 54](https://github.com/TeamTwilight/twilightforest/assets/75467920/86fe8e99-3bc9-413f-9dc8-0ed2f4c48dc0)
This and #1799 seem to be fixed by setting the rendertype in the model json to solid, although this breaks the glow textures on the top and sides (image is of the rendertype set as solid)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this is unfortunately a vanilla bug regarding transparent layers on blocks, nothing I can do to fix this
