### ISSUE TITLE
Hydra does not take damage from reflected mortars

### ISSUE THREAD

**Issue by sm644me** [TeamTwilight/twilightforest#1812]
### Forge Version

45.0.63

### Twilight Forest Version

4.2.1681

### Steps to Reproduce

- Encounter a Hydra.
- Wait for it to use its mortar attack.
- Reflect its mortars back at an open mouth.
- Observe.

### What You Expected

I expected the Hydra to take damage.

### What Happened Instead

The Hydra took no damage. There was no damage sound or red color, and the health bar remained the same.

### Additional Details

Despite the Hydra taking no damage, its heads still eventually died after enough hits, so they're clearly receiving some sort of damage interaction. I have also confirmed that this happens even with no mods other than Twilight Forest installed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This has already been fixed, it'll be in the 1.19.4 release when I'm able to get it out. Should be uploaded tomorrow if all goes well

**Comment by sm644me** [comment]
> This has already been fixed, it'll be in the 1.19.4 release when I'm able to get it out. Should be uploaded tomorrow if all goes well

Oh, awesome! Glad this was already noticed; hope all goes well with the release!
