### ISSUE TITLE
Twilight forest crash when crafting item

### ISSUE THREAD

**Issue by splatchoot** [TeamTwilight/twilightforest#1816]
Forge version: 4.2.2
Twilight Forest version: 4.1.1494
Link to crash log: []https://mclo.gs/6oIweTY

Steps to reproduce:
1. load minecraft
2. craft an item
3. try to pick the item from the crafting table

What I expected to happen:
the game not to crash and recieve the item afterward
What happened instead:
the game crash

**Comment by Andromander** [comment]
This crash log just says Ice and Fire is missing a mod called Citadel.

**Comment by splatchoot** [comment]
> This crash log just says Ice and Fire is missing a mod called Citadel.

all my apologies, this a an old log, this is the one i wanted to put :
https://mclo.gs/i2StN9D

**Comment by GizmoTheMoonPig** [comment]
this is an issue with sophisticated backpacks, please report this to their issue tracker instead.

**Comment by splatchoot** [comment]
> this is an issue with sophisticated backpacks, please report this to their issue tracker instead.

yeah but it only does that with Twilight forest craftings... not all the other mods

**Comment by Tamaized** [comment]
net.p3pp3rf1y.sophisticatedcore.crafting.StorageDyeRecipeBase.matches(StorageDyeRecipeBase.java:33) ~[sophisticatedcore-1.18.2-0.5.56.273.jar#106!/:1.18.2-0.5.56.273] {re:classloading}
