### ISSUE TITLE
Rail Entity Being Ticked

### ISSUE THREAD

**Issue by FlamingCatz** [TeamTwilight/twilightforest#1817]
### Forge Version

36.2.34

### Twilight Forest Version

4.0.870

### Client Log

https://gist.github.com/FlamingCatz/c2146a313bd98e5726822993abffd80c/revisions#diff-6eb5aa2af122281945d8d42cc285a04af319c927fec0b2e03ce47987c39985a2

### Crash Report (if applicable)

https://gist.github.com/FlamingCatz/c3e590314aed250f8f35e23d148e8748/revisions#diff-6eb5aa2af122281945d8d42cc285a04af319c927fec0b2e03ce47987c39985a2

### Steps to Reproduce

1. I downloaded many around 29 mods, including Twilight Forest, onto an Aternos server.
2. I then started the server.
3. The server crashed almost as soon as it started.

### What You Expected

I expected the server to continue working, especially after I used a new seed.

### What Happened Instead

The server crashed and it said that it was because of a rail entity.

### Additional Details

I wasn't sure what happened, so I asked for help and someone said that they thought it had something to do with the Twilight Forest mod and how it affected world generation.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
I'm looking at the crash reports and there's nothing pointing to any specific mod, nor even Twilight Forest.

The crash is `java.lang.BootstrapMethodError: java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "org/apache/logging/log4j/util/MessageSupplier"`, however, I wouldn't have a clue what results in this. Perhaps a bad mod.

**Comment by FlamingCatz** [comment]
Ok ty.

**Comment by FlamingCatz** [comment]
However, it says, https://gist.github.com/FlamingCatz/b73e75e9a6f183cd37d922c1de35fd0f/revisions#diff-6eb5aa2af122281945d8d42cc285a04af319c927fec0b2e03ce47987c39985a2 in the crash report under the entity being ticked version.

**Comment by Tamaized** [comment]
That's just from our asm, it doesn't actually mean we're the problem.
