### ISSUE TITLE
Crash after install

### ISSUE THREAD

**Issue by StarscapeNW17** [TeamTwilight/twilightforest#1822]
### Forge Version

45.0.66

### Twilight Forest Version

 4.2.1696

### Client Log

https://gist.github.com/StarscapeNW17/1c8989da95e928fc7d87c3507618656e

### Crash Report (if applicable)

https://gist.github.com/StarscapeNW17/d42666e9b4462fa3ce6b4019c746f534

### Steps to Reproduce

First, I open the Twilight Forest profile in Curseforge, and it opens in the custom launcher, and after installing it crashes every time. 

### What You Expected

I expected Minecraft to open as usual with the modpack. 

### What Happened Instead

Crashed over and over, even after trying to troubleshoot on my own.

### Additional Details

I am using a gaming laptop and this worked on my PC, so that might be the cause of the issue but I'm not sure.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Java itself here crashed, not sure exactly why. Could try a different version of java or try updating your drivers.

Also be very wary of posting these types of logs, they contain sensitive information like your minecraft access token.
That means anyone can take that token and login to online mode servers as if they were you.

To make this current key no longer valid, login to your account 3 times in the launcher.

**Comment by StarscapeNW17** [comment]
Oh, that's interesting. And I didn't know that, thank you for the warning.
