### ISSUE TITLE
Hostile mobs not spawning naturally

### ISSUE THREAD

**Issue by pablormsn** [TeamTwilight/twilightforest#1823]
### Forge Version

14.23.5.2860

### Twilight Forest Version

3.11.1021

### Steps to Reproduce

1. Entered to any structure, for example Goblin Stronghold
2.Goblins not spawning, only mobs which come from spawners
3.Same happen in the rest of structures where mobs are supposed to spawn naturally, like Aurora Palace

### What You Expected

Hostile mobs spawning naturally in structures

### What Happened Instead

Hostile mobs only spawned from spawners

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
1.12.2 is no longer supported
