### ISSUE TITLE
[1.19.4] Sorting Core can insert items into slots they normally shouldn't enter

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1824]
### Forge Version

45.0.59

### Twilight Forest Version

4.2.1644

### Steps to Reproduce

1. Set up a sorting core near a furnace
2. Put a fuel in the furnace, and the same fuel in a chest by the sorting core

### What You Expected

I would expect the sorting core to insert the fuel into the fuel slot of the furnace as it depletes, but not stuff it into the smelting slot as well once the fuel slot is full

### What Happened Instead

The sorting core treats the smelting slot of the furnace the same as the fuel slot, resulting in a clogged furnace 
![2023-06-03_10 09 36](https://github.com/TeamTwilight/twilightforest/assets/23658767/e26a962d-da7e-4732-b3cb-5616edaf2597)

### Additional Details

Would it be possible to force the sorting core to respect a tag or similar on certain slots, for example a theoretical forge:furnace_smeltable and forge:furnace_fuel? 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by EvergreenSystems** [comment]
Adding this comment from the discord to add context so it doesn't get lost: you technically can insert anything you want into the top slot of a furnace, but the sorting core will shove fuel in because it matches the contents of the container and it sees an empty slot, thus making the furnace unusable practically as it clogs whenever it's empty

**Comment by Tamaized** [comment]
@jodlodi
