### ISSUE TITLE
spawning ur-ghast

### ISSUE THREAD

**Issue by Sigurd23** [TeamTwilight/twilightforest#1826]
Forge version: 
Twilight Forest version: 
Link to crash log: https://pastebin.com/srrqDLk7
Steps to reproduce:
1. spawn ur-ghast

What I expected to happen:

What happened instead:

**Comment by GizmoTheMoonPig** [comment]
1. next time, please use a proper issue template. We have them for a reason. 
2. This is an issue with Sponge. It doesn't like our large entities, luckily this is easily fixable. Open `config/sponge/global.conf` and set the max-bounding-box-size to `6000` or higher, or `0`
