### ISSUE TITLE
[Suggestion] Armor trim colors for Twilight Forest materials (and the possible colors for them)

### ISSUE THREAD

**Issue by bleh1245** [TeamTwilight/twilightforest#1827]
### The Suggestion

With the recent release of 1.20, armor trims are now a thing. This is a very simple suggestion for adding armor trims colors that coincide with the materials found in the Twilight Forest used for crafting tools and armor.

Here are some examples of what the trim colors for the materials could be:

Ironwood
![image](https://github.com/TeamTwilight/twilightforest/assets/69449343/d3fb2ba4-1b49-41bd-812d-65dc20d06577)

Steeleaf
![image](https://github.com/TeamTwilight/twilightforest/assets/69449343/16cea4e9-a881-4335-bfad-ff84a8fa4c58)

Knightmetal
![image](https://github.com/TeamTwilight/twilightforest/assets/69449343/728b7248-af4e-4865-a6d2-b448c31dec45)

Fiery ingots in particular could be special, and instead of being a solid color for the trim, could have it to where it pulsates a bright orange, with an emission texture (ala glow squids), similarly to the magma block's cracks
![Magma_Block_JE2_BE2](https://github.com/TeamTwilight/twilightforest/assets/69449343/ab79537b-d573-4b84-8240-4c66e821fb7c)

### Why Should It Be in the Mod?

Giving the player more aesthetic customization options is almost always a boon for any mod. Plus having 3 more green color options for trims would be very fitting for a forest themed mod.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
closing as trim materials are already added in the upcoming 1.20 port. Appreciate the suggestion though, even if I beat you to it :P
