### ISSUE TITLE
Block and Chain will crash a server if you go through the portal

### ISSUE THREAD

**Issue by BelowAvaragezZ** [TeamTwilight/twilightforest#1832]
### Forge Version

45.1.2

### Twilight Forest Version

twilightforest-1.19.4-4.2.1696-universal.jar

### Client Log

https://mclo.gs/Eqt4rbI#L5

### Crash Report (if applicable)

https://mclo.gs/Eqt4rbI#L5

### Steps to Reproduce

1. Play on Aternos
2. Go to the Nether
3. Before it teleports you you must use the 'Block and Chain' item
4. If you come back the server will crash
5. CG

### What You Expected

Maybe the entity should be deteled as soon as you teleport away with the **Nether Portal**

### What Happened Instead

When I went back through the portal it was bugging through the blocks and than the server crashed.

### Additional Details

I know that the link maybe _sketchy_ but trust me, it's for the **crash report** from the server.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
fixed in 6a285b9
