### ISSUE TITLE
No support for custom models

### ISSUE THREAD

**Issue by Refried-Beans** [TeamTwilight/twilightforest#1834]
### Forge Version

43.2.9

### Twilight Forest Version

4.2.1518-universal

### Steps to Reproduce

1. Create block model, (in this case bushy leaves) along with blockstates and textures in appropriate folders. 
**Minecraft Leaves Model (The Parent Model)**
{
	"credit": "Made with Blockbench",
	"textures": {
		"particle": "#all"
	},
	"elements": [
		{
			"from": [0, 0, 0],
			"to": [16, 16, 16],
			"faces": {
				"north": {"uv": [0, 0, 16, 16], "texture": "#all", "cullface": "north"},
				"east": {"uv": [0, 0, 16, 16], "texture": "#all", "cullface": "east"},
				"south": {"uv": [0, 0, 16, 16], "texture": "#all", "cullface": "south"},
				"west": {"uv": [0, 0, 16, 16], "texture": "#all", "cullface": "west"},
				"up": {"uv": [0, 0, 16, 16], "texture": "#all", "cullface": "up"},
				"down": {"uv": [0, 0, 16, 16], "texture": "#all", "cullface": "down"}
			}
		},
		{
			"from": [8, -8, -8],
			"to": [8, 24, 24],
			"shade": false,
			"rotation": {"angle": -22.5, "axis": "y", "origin": [8, 8, 8]},
			"faces": {
				"east": {"uv": [0, 0, 16, 16], "texture": "#bush"},
				"west": {"uv": [0, 0, 16, 16], "texture": "#bush"}
			}
		},
		{
			"from": [-8, -8, 8],
			"to": [24, 24, 8],
			"shade": false,
			"rotation": {"angle": -22.5, "axis": "y", "origin": [8, 8, 8]},
			"faces": {
				"north": {"uv": [0, 0, 16, 16], "texture": "#bush"},
				"south": {"uv": [0, 0, 16, 16], "texture": "#bush"}
			}
		}
	],
	"display": {
		"thirdperson_righthand": {
			"rotation": [75, 45, 0],
			"translation": [0, 2.5, 0],
			"scale": [0.375, 0.375, 0.375]
		},
		"thirdperson_lefthand": {
			"rotation": [75, 45, 0],
			"translation": [0, 2.5, 0],
			"scale": [0.375, 0.375, 0.375]
		},
		"firstperson_righthand": {
			"rotation": [0, 45, 0],
			"scale": [0.4, 0.4, 0.4]
		},
		"firstperson_lefthand": {
			"rotation": [0, 225, 0],
			"scale": [0.4, 0.4, 0.4]
		},
		"ground": {
			"translation": [0, 3, 0],
			"scale": [0.25, 0.25, 0.25]
		},
		"gui": {
			"rotation": [30, 225, 0],
			"scale": [0.625, 0.625, 0.625]
		},
		"fixed": {
			"scale": [0.5, 0.5, 0.5]
		}
	}
}
**Twilight Oak Block Model:**
{
  "parent": "minecraft:block/leaves",
  "textures": {
    "all": "minecraft:block/oak_leaves",
    "bush": "minecraft:block/oak_bush"
  }
}
4. Load resourcepack into minecraft
5. Begin weeping

### What You Expected

I wanted the leaves of Twilight Forest to be bushy. Basically the ordinary Twilight Forest leaves, but with cross added displaying the bushy textures I added.

### What Happened Instead

The best I could produce was a block with the original texture on the block, but invalid textures on the cross (the cross is what I added to the original leaves block model)

### Additional Details

Here's an example of Twilight Forest Leaves along with Vanilla and Biomes O' Plenty Leaves

![2023-07-03_13 47 08](https://github.com/TeamTwilight/twilightforest/assets/138521820/9103e0e2-ed08-49c0-b9bb-1e07d7594c28)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
It's literally impossible for this mod to cause this error alone. Post the full log.
