### ISSUE TITLE
Portal spawned in aurora tower

### ISSUE THREAD

**Issue by cottonyfluff** [TeamTwilight/twilightforest#1835]
### Forge Version

43.2.13

### Twilight Forest Version

4.2.1518

### Steps to Reproduce

I honestly have no idea how to replicate this, but i'll do my best to explain what happened.

1. I placed a new portal a couple thousand blocks away from my old portal and at a y of 127.}

I think due to world generation and already explored TF chunks on this server it just put me here instead of a twilight plains

### What You Expected

I had expected for the portal to spawn in the twilight plains area with the naga den.

### What Happened Instead

My portal spawned inside an aurora tower

![image](https://github.com/TeamTwilight/twilightforest/assets/138530318/718d6116-a70c-4020-a336-66b25b9669a7)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
1.19.2 isn't supported, this was resolved in later versions.
