### ISSUE TITLE
When opening the chest that spawns after defeating a boss it doesn't load the loot table for it

### ISSUE THREAD

**Issue by TheLordMagus** [TeamTwilight/twilightforest#1840]
### Forge Version

47.1.0

### Twilight Forest Version

4.3.1735

### Client Log

https://gist.github.com/TheLordMagus/1dcd1ba461b943bae952388d6e2ccfcf

### Steps to Reproduce

1. Kill the boss, ex: Naga
2. Find and open the chest that spawned

### What You Expected

Chest to contain the loot for killing the boss

### What Happened Instead

The chest was empty

### Additional Details

![Minecraft 1 20 1 _ FPS_ 33 _ Mem_ 54% 3512_6432MB _ Ping_ 0 7_10_2023 3_55_45 PM](https://github.com/TeamTwilight/twilightforest/assets/139176273/fdca43e0-b5eb-4366-b5f8-53561cc16d9b)
When killing the bosses the advancement is still given

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
fixed in a57d0bb, will have a new build up shortly

**Comment by GizmoTheMoonPig** [comment]
you can grab the build that has the fix here: https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/4635921
