### ISSUE TITLE
no loot in chests 

### ISSUE THREAD

**Issue by DEXTER15O** [TeamTwilight/twilightforest#1841]
### Forge Version

47.1.0

### Twilight Forest Version

4.3.1734

### Steps to Reproduce

1- entered the dimension 
2 searched for a boss (naga/lich)
3- prior to finishing the boss fight the chests turn out to be empty and have to loot after many tries

### What You Expected

getting loot for killing the bosses 

### What Happened Instead

didnt get any loot from killing the bosses and iam running a server

### Additional Details

i have a server  on 1.20.1 and iam having the issue motioned before i  hope that you can help me solve it or understand waht happening 
iam new to get hub so sorry if i gave the information in wrong order or anything   

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
update to 4.3.1740
