### ISSUE TITLE
Seeker Bow goose for XP orbs

### ISSUE THREAD

**Issue by HeavyDeception** [TeamTwilight/twilightforest#1842]
### Forge Version

43.2.14

### Twilight Forest Version

4.2.1518

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

1. Have a Seeker bow
2. Has XP orb on the ground
3. Shoot past it.

### What You Expected

For the arrow to hit the mob behind the XP orb.

### What Happened Instead

The arrow is eager to strike the XP orb. (must have said something about its mom.)

### Additional Details

The is in all ATM8 I have tried it with just the TTF and the same thing happened.

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Unable to reproduce in 1.20.1. Arrows just shoot as normal near Experience Orbs.
