### ISSUE TITLE
Breaking a Bed in the Twilight Forest sets your respawn point to the Overworld, even when the player is configured to always respawn in the Twilight Forest

### ISSUE THREAD

**Issue by puncrafter** [TeamTwilight/twilightforest#1843]
### Forge Version

36.2.33

### Twilight Forest Version

4.0.870

### Steps to Reproduce

1. Set `newPlayersSpawnInTF = true` in the `twilightforest-common.toml` config file.
2. Place a bed in the Twilight Forest and sleep in it to set your spawn.
3. Die, just to make sure the bed worked properly just in case.
4. Break the bed.
5. Die again.
6. You should respawn in the Overworld.

### What You Expected

I expected to respawn in the Twilight Forest, since the game is configured so that you spawn in the Twilight Forest. 

### What Happened Instead

I spawned in the Overworld.

### Additional Details

I also have `disablePortalCreation` set to true in the same config file, but I don't think that should be interacting with this.

I am aware that I am reporting this bug in 1.16.5, a version that is no longer being developed for, but I figured it would be important to point out, just in case.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this has been fixed in newer versions. I think we did it in 1.18? Regardless, youll always respawn in TF if you dont have a spawnpoint and you set the config option to true in more recent versions. Since we dont maintain 1.16 anymore im gonna close this. Thank you for reporting though!
