### ISSUE TITLE
[Suggestion] Certain Blocks be able to be turned into bricks/woods

### ISSUE THREAD

**Issue by Nightfigure** [TeamTwilight/twilightforest#1844]
### The Suggestion

I might be going over my head with this but What if certain blocks could be put made into other blocks for example,if you put deadrock into a stone cutter it could be turned into castle brick,etc etc. So i put a list of possible convertable blocks
-Deadrock to Castle brick variations in stone cutter aswell as nagastone
-Darkwood With Carminite in a crafting table to make tower wood
-ice With Transformation powder to make Aurora Blocks

Im pretty sure this wont be added but its a cool idea

### Why Should It Be in the Mod?

It would Add variety and lore to the structures and blocks.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Toastr125** [comment]
You can already make Towerwood by putting Darkwood Logs in a Stonecutter.

**Comment by Killer-Demon** [comment]
Thank you for your suggestion. However, these aren't changes we're looking to make for various reasons.
