### ISSUE TITLE
Crash near dark forest biome

### ISSUE THREAD

**Issue by YourMotherr** [TeamTwilight/twilightforest#1845]
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1740

### Crash Report (if applicable)

https://pastebin.com/rEEYkjAE

### Steps to Reproduce

just crashes when near the dark forest biome

### What You Expected

to not crash

### What Happened Instead

crashed

### Additional Details

impossible to approach the forest if it crashes everytime

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by CaracalPilot** [comment]
I got this too, ticking entity thing. how do you fix it?

**Comment by tommyboy3424** [comment]
the mob that crashes it is the skeleton druid for some reason his attack (nature bolt) makes the game crash
