### ISSUE TITLE
Crash Loading Game

### ISSUE THREAD

**Issue by Mezimaru** [TeamTwilight/twilightforest#1846]
### Forge Version

47.1.39

### Twilight Forest Version

1.20.1-4.3.1750

### Client Log

https://gist.github.com/Mezimaru/fdd1ce7d192cf4bd59dd6b96d3b768c6

### Crash Report (if applicable)

https://gist.github.com/Mezimaru/e8043fe56a00c17561cc337695303d70

### Steps to Reproduce

Using Rubidium+Oculus with the new 4.3.1750 Twilight Forest update crashes game upon main menu load.

### What You Expected

No crash?

### What Happened Instead

Crash?

### Additional Details

Sorry if this is a Iris/Oculus fix and not you guys, just wanted to make sure people were aware.
Appreciate all that you guys do!

Also sorry if this falls under Optifine problems since its regarding shader usage, if so please just close and ignore me.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Downgrade Forge to 47.1.3

**Comment by Mezimaru** [comment]
Dang, that's unfortunate. There's been quite a bit of issues with multi part entities and crashing from various sources before update Forge 47.1.24.
Did confirm that 47.1.3 works fine as suggested for the new twilight forest update.
Thank you Tamaized!
