### ISSUE TITLE
forge not support 47.1.30

### ISSUE THREAD

**Issue by Hisamikatsuki** [TeamTwilight/twilightforest#1848]
### Forge Version

47.1.30

### Twilight Forest Version

4.3.1750

### Steps to Reproduce

![0E~H% M@TQ8W UG@`IOLOHQ](https://github.com/TeamTwilight/twilightforest/assets/140148912/2ca9632d-8463-476f-af63-b0da2afc5825)

### What You Expected

fix 47.1.30≠47.1.3

### What Happened Instead

no more

### Additional Details

no more

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Well...of course 47.1.30 won't work. That's how numbers work.

30 is a bigger number than 3 and we need a number equal to or lower than that. You can see that when you look at a number chart.

**Comment by Hisamikatsuki** [comment]
![6M9V98H2PME}65FC8J$VOEY](https://github.com/TeamTwilight/twilightforest/assets/140148912/d668b55e-e856-4693-be91-16fbc1c31cdd)


> Well...of course 47.1.30 won't work. That's how numbers work.
> 
> 30 is a bigger number than 3 and we need a number equal to or lower than that. You can see that when you look at a number chart.

**Comment by Andromander** [comment]
No...a number smaller than the number *3*.
30 is not 3. 30 - 3 = 27. That's how big of a difference it is.
29 is still a bigger number than 3, anyway.

**Comment by Hisamikatsuki** [comment]
> No...a number smaller than the number _3_. 30 is not 3. 30 - 3 = 27. That's how big of a difference it is. 29 is still a bigger number than 3, anyway.

Is that means 47.0.45-47.1.03？

**Comment by Hisamikatsuki** [comment]
> No...a number smaller than the number _3_. 30 is not 3. 30 - 3 = 27. That's how big of a difference it is. 29 is still a bigger number than 3, anyway.

OK thanks，my miss

**Comment by AlphaMode** [comment]
What is this issue non sense

**Comment by CodexAdrian** [comment]
alphamode its 3 am go to sleep
