### ISSUE TITLE
[Suggestion] Corner Banisters

### ISSUE THREAD

**Issue by SuperStefan97** [TeamTwilight/twilightforest#1849]
### The Suggestion

Banisters are some awesome decorative block that can be used to lot of decoration. For stairs, ships, animal pens... but they are difficult to place correctly at the edges as they need a whole block to cover one side, using more space than needed.

### Why Should It Be in the Mod?

I think it would add a vanilla-like behaiviour like fences that connected on corners. Only one model would be neded that would rotate (upper-right, upper-left, downward-right, downward-left). Also, it would be really practical.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This is not something we're currently looking into adding. You can create your own solid corners with alternating the banisters, too.
