### ISSUE TITLE
Ticking Entity Crash When Approaching Hydya

### ISSUE THREAD

**Issue by lemorage** [TeamTwilight/twilightforest#1850]
### Forge Version

47.1.14

### Twilight Forest Version

4.3.1740

### Client Log

https://gist.github.com/lemorage/fad163ed7de0f13eb4e1afcd95603fa4

### Crash Report (if applicable)

https://gist.github.com/lemorage/6c68751b762ebd96e89d4bf00655e2f0

### Steps to Reproduce

I tried multiple times to determine when and how the crash occurred. I thought the point was that the crash happened immediately when I approached the Hydra's nest. In other words, I can only get into the outer ring of the fire swamp, but cannot get deeper furthermore.

### What You Expected

I would like to defeat Hydra, so I can get into the next stage and go to defeat the boss after Hydra.

### What Happened Instead

Every time I approached Hydra, the game just crashed without any reason.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Downgrade Forge to 47.1.3
