### ISSUE TITLE
[Suggestion] Chest Tag Group

### ISSUE THREAD

**Issue by Duxtorm** [TeamTwilight/twilightforest#1851]
### The Suggestion

May you please add a tag group for the Twilight Forest chests?

### Why Should It Be in the Mod?

It would make it easier to make them play nice with other mods through config or datapacks ♥

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
There already is a blocktag for them, keep in mind that you can easily create custom tags with a datapack
