### ISSUE TITLE
The return of Twilight Forest Problem

### ISSUE THREAD

**Issue by giovy14** [TeamTwilight/twilightforest#1855]
### The Suggestion

**So, there is to improve the fact that the mod has this problem I don't know if anyone remembers it, that that problem would be that the Twilight Forest Mod doesn't work in the version (47.1.42).

### Why Should It Be in the Mod?

Because I want you to add that version to be able to battle mobs or make a survival out of it.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
we locked TF to 47.1.3 because of all the breaking changes forge keeps making. Its not stable past that version, I dont recommend using it.
Also, please dont use the suggestion tickets for this stuff.
