### ISSUE TITLE
Rename to "Twilight Mangrove"

### ISSUE THREAD

**Issue by Aceplante** [TeamTwilight/twilightforest#1858]
### The Suggestion

For the sake of better integration with mods that potentially add a mangrove wood type (such as BOP), and especially now that mangrove exists in vanilla, I propose renaming the mangrove wood type to twilight mangrove, just like twilight oak.

### Why Should It Be in the Mod?

The aforementioned reasons of compatibility

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
No

**Comment by GizmoTheMoonPig** [comment]
We've already stated many times (mainly on our discord) that there's no reason for us to do this. So we won't.

**Comment by Aceplante** [comment]
Even if you do not wish to change 1.18 and before, mangrove now exists in vanilla 1.19+

Still no? up to you i guess

**Comment by Andromander** [comment]
Still a no. We're not changing it just because vanilla decided to add their own tree.
