### ISSUE TITLE
Server Crashing in 1.19.2 when a Specific mob spawn (Druid Skeleton)

### ISSUE THREAD

**Issue by Sumerato** [TeamTwilight/twilightforest#1859]
### Forge Version

43.2.8

### Twilight Forest Version

Twilight Forest - MC 1.19.2 - 4.2.1518

### Client Log

https://gist.github.com/Sumerato/477047c5aacb1e80abb279c6df9abf7a

### Crash Report (if applicable)

https://gist.github.com/Sumerato/a1b658c00341ac48de9983d942ee28a1

### Steps to Reproduce

1° - The server crash instantly when one or more players walk through twilight
2° - The server keeping crashing even when change the mod version or deleting and creating a new twilight world
3° - In all crash report from the server folder they describe in beginning:
"java.lang.AssertionError: Unknown entity class twilightforest.entity.monster.SkeletonDruid"

### What You Expected

based on all server's crash-reports i suppose that the crash could be when Skeleton Druid spawn.

### What Happened Instead

The server crashing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by task58** [comment]
I got the same problem with 1.18.2-4.1.1494-universal.
I have tried several times and each time I get "java.lang.AssertionError: Unknown entity class twilightforest.entity.monster.SkeletonDruid".

**Comment by task58** [comment]
I was using Mohist when I got this problem, but when I used the regular forge server instead of Mohist, I did not got this problem.

**Comment by Mgazul** [comment]
I have fixed it in mohist latest version
