### ISSUE TITLE
Chill aura Enchantment still in Aurora loot tables

### ISSUE THREAD

**Issue by LizzieSpace** [TeamTwilight/twilightforest#1861]
### Forge Version

N.A (dev issue. will happen regardless of loader version)

### Twilight Forest Version

4.2.357

### Client Log

N.A

### Crash Report (if applicable)

N.A

### Steps to Reproduce

1. play game as normally
2. get to the aurora castle
3. have a chance to find `chill Aura` enchantment book
4. realize it does not work

### What You Expected

Either the enchantment should go back to work as intended, or it should be removed entirely.
[The wiki](http://benimatic.com/tfwiki/index.php?title=Chill_Aura) affirms that this enchantment shouldn't exist:
> This enchantment is no longer in the game as of version 2.3.3

### What Happened Instead

Not only is the Enchantment in question still accessible to the player through loot tables, it does not work at all.

### Additional Details

The `Chill Aura` enchantment persists through two loot tables:
* [`twilightforest:structures/aurora_cache`](https://github.com/TeamTwilight/twilightforest/blob/1debd5c78075a5382986ac7027dd71ee17585891/src/generated/resources/data/twilightforest/loot_tables/chests/aurora_cache.json#L292C12-L292C12)
* [`twilightforest:structures/aurora_room`](https://github.com/TeamTwilight/twilightforest/blob/1debd5c78075a5382986ac7027dd71ee17585891/src/generated/resources/data/twilightforest/loot_tables/chests/aurora_room.json#L175C33-L175C38)

permalinks as of august 11 2023. 

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
1.7 has been unsupported for many years, so this won't be changing. We only support the newest MC version.
In later versions (1.17+ I think?), the enchantment was actually reimplemented and given functionality. Dont think the wiki actually says that though

**Comment by LizzieSpace** [comment]
I wonder what you mean by 1.7, since that's not mentioned anywhere in the issue... 

Indeed the wiki doesn't say anything about it, although it's briefly mentioned on the change logs. 

The version of the mod I played on 1.19.2 fabric didn't seem to get the enchantment working, thought it was due to it being removed.

I'll review if the issue actually persists on the forge version and if not I'll make an issue on the right place. I apologize for the trouble.

**Comment by Andromander** [comment]
I can confirm the wiki is a bit outdated on the Enchantment side of things. Can't say for sure about it working or not, since I don't work on the Fabric version.

**Comment by GizmoTheMoonPig** [comment]
My bad on the 1.7 bit, I saw the low version number and automatically assumed it was an older version. (this is why you should also give the MC and forge versions). Regardless, this issue tracker isnt for fabric issues, those should be reported [here](https://github.com/TeamTwilight/twilightforest-fabric/issues). Chill aura works just fine on forge, I just tested it
