### ISSUE TITLE
Not spawning in Twilight Forest

### ISSUE THREAD

**Issue by MuteTiefling** [TeamTwilight/twilightforest#1863]
### Forge Version

43.2.14

### Twilight Forest Version

twilightforest-1.19.2-4.2.1518

### Client Log

https://gist.github.com/MuteTiefling/e753baeb3a4496c12b75aa5d101b8453

### Steps to Reproduce

1. Set configs to start in Twilight Forest
2. Create a new world
3. Change world properties while making the new world (specifically changing the World Type),
4. Generate the world and join

Not only will the player not start in Twilight, but they'll also be unable to teleport there by any means. `/execute in` won't show `twilightforest:twilight_forest`, for example. 

### What You Expected

Player should still start in Twilight, regardless of the Overworld generation settings. 

### What Happened Instead

Started in Overworld and could no longer visit the Twilight Forest. 

### Additional Details

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/598

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This is unfortunately an issue with forge (see https://github.com/MinecraftForge/MinecraftForge/issues/8964). Datapacks arent reloaded for any world type except the default for some reason I havent looked into yet. I dont know if forge is still doing updates for 1.19.2 or not though, as our focus has shifted over to neo so I havent been keeping up with what theyre doing over there

**Comment by MuteTiefling** [comment]
Awesome. Thanks for the info!
