### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by nulleqn** [TeamTwilight/twilightforest#1866]
### The Suggestion

1.20 fo NeoForge

### Why Should It Be in the Mod?

NeoForge > Forge

### Please Read and Confirm the Following

- [ ] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
Although it's not yet published, the mod has already been moved to NeoForge.

**Comment by nulleqn** [comment]
> 虽然尚未发布，但该模组已经转移到 NeoForge 上。

When will that be published?

**Comment by jodlodi** [comment]
We still have some things to fix first, we will publish after it's all okay.

**Comment by nulleqn** [comment]
yes sir✌
