### ISSUE TITLE
World crashing when placing Red Thread. Unable to enter world afterwards

### ISSUE THREAD

**Issue by LashtarkSuros** [TeamTwilight/twilightforest#1870]
### Forge Version

47.1.0

### Twilight Forest Version

4.3.1750

### Client Log

https://gist.github.com/LashtarkSuros/d419f6c4a1aa4338e70757b21e29ff71

### Crash Report (if applicable)

https://gist.github.com/LashtarkSuros/475eaaefdc9193663199780c5c5b4abe

### Steps to Reproduce

1. Open a Minecraft world
2. Place Red Thread on world

### What You Expected

Red Thread to be placed and function normally

### What Happened Instead

Block with invisible texture was placed and game freezed, crashing after a few seconds

When joining a world, it crashes at loading screen after a few seconds of being completely loaded

### Additional Details

Running a heavy-modded Forge client with Rubidium, Canary and Resource Packs

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
does removing rubidium fix this? I feel like ive seen this crash before in other mods and rubidium was the problem

**Comment by LashtarkSuros** [comment]
Yes. I disabled Rubidium, entered my world, broke the thread, exited, enabled it, entered again and now I'm able to play normaly. Sorry for not testing before and thank you.

**Comment by Voltem0** [comment]
Yeah, currently placing down 'red thread' while you have twilight forest and rubidium installed crashes the server and makes the world inaccessible
However rubidium is just about the most important performance mod i have installed, game is very laggy etc without it and twilight-forest HATES optifine which would be my alternative.
Unfortunately I just don't know what alternative mods to use or what else to do.
Rubidium is critical for the dynamic lighting mod i use and for general FPS increases.

**Comment by GizmoTheMoonPig** [comment]
For reference if anyone else comes across this: use embeddium instead. It's another fork of sodium that's actually maintained well and focuses more on mod compatibility
