### ISSUE TITLE
Final Boss Suggestion - Twilight King

### ISSUE THREAD

**Issue by StickminReve3YT** [TeamTwilight/twilightforest#1873]
### The Suggestion

A powerful boss mob, partially inspired from the Sun Spirit of the Aether Mod, that is the cause of the eternal night. Will send powerful attacks at the player, partially from every boss mob in the mod. When defeated, hostile mobs like kobolds, etc. are made passive and permanent night is removed from the dimension for the world. Drops the Moonlight Altar when killed, which allows you to control the day and night cycle in the dimension.

### Why Should It Be in the Mod?

Adding it into the mod would add some interesting lore to the game, make the final castle more meaningful to find, and make it more interesting. I mean, no mod is complete without a final boss.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
The boss is already fully planned out, sorry.
