### ISSUE TITLE
[Portal Issue] Players sent right inside the portal

### ISSUE THREAD

**Issue by SodiumZH** [TeamTwilight/twilightforest#1874]
### Forge Version

43.2.0

### Twilight Forest Version

4.2.1421

### Steps to Reproduce

1) Make a portal in the Overworld and put a layer of blocks around it, as the image shows.
2) Get inside the portal and then try getting back from TF.
![2023-08-31_20 37 03](https://github.com/TeamTwilight/twilightforest/assets/46860829/41fb6bbb-65ca-4d26-872c-c344a09dc34a)

### What You Expected

The player should be placed on the ground around the portal in the Overworld.

### What Happened Instead

The player was placed right inside the Overworld portal, which immediately sent the player back to TF.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SodiumZH** [comment]
#1459

**Comment by Tamaized** [comment]
1.19.2 is no longer supported.
