### ISSUE TITLE
[1.19.2]some textures are broken by ConnectedTexturesMod

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#1876]
### Forge Version

1.19.2-Forge_43.2.21

### Twilight Forest Version

twilightforest-1.19.2-4.2.1518-universal

### Steps to Reproduce

1.Install [CTM](https://www.curseforge.com/minecraft/mc-mods/ctm)-1.19.2-1.1.6+8 and Twilight forest-1.19.2-4.2.1518-universal
2.Start the game

### What You Expected

![image](https://github.com/TeamTwilight/twilightforest/assets/129179911/948ea05c-1f3e-4152-8edf-f7d176fa91e8)

### What Happened Instead

![image](https://github.com/TeamTwilight/twilightforest/assets/129179911/e7a38ca5-f16c-4eda-8799-ca2b42196f2e)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ghost** [comment]
The texture of experiment 115 is also broken.I guess there are more broken textures I have not found 
![ZW18ALGV{J@MPL`OXWZYU04](https://github.com/TeamTwilight/twilightforest/assets/129179911/1ef81dac-9eae-49a8-bfe5-4032467b8400)

**Comment by GizmoTheMoonPig** [comment]
all mcmeta files for CTM have been removed in later versions since the mod isnt necessary anymore, so im gonna close this. 
1.19.2 wont be getting a fix since we dont backport things but you can fix it yourself with a resource pack
