### ISSUE TITLE
Game crashing when ice core dies.

### ISSUE THREAD

**Issue by redlive36** [TeamTwilight/twilightforest#1877]
### Forge Version

43.2.0

### Twilight Forest Version

4.2.1518

### Crash Report (if applicable)

https://gist.github.com/redlive36/bc35398828253f152f11e0fca500ac24

### Steps to Reproduce

1. Find an unstable ice core.
2. Kill it.
3. Game crash when it does its exploding animation.

### What You Expected

I expected my game to not crash.

### What Happened Instead

My game closed.

### Additional Details

I understand this might be an issue caused by another mod, and if it is, I understand you can't do anything about it. Still, thank you for reading my issue, and have a great day.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
not even sure how this happened. What blocks were around the ice core? Was it just in an aurora palace or did you spawn one in?

**Comment by redlive36** [comment]
> not even sure how this happened. What blocks were around the ice core? Was it just in an aurora palace or did you spawn one in?

It was a naturally spawning one, and the blocks around it were the blocks that make up the aurora palace, the ones that change color. I will be providing a video later trying to re-create the problem. Thank you for your interest.

**Comment by redlive36** [comment]
https://youtu.be/4_td-p05IpQ
https://youtu.be/7uwXf3wPyOA
As promised, here are two videos showcasing the bug. The first one is the crash actually ocurring, and the second one is what happens after re-starting the world. It was a naturally spawned one in an aurora castle, and it happens in all of my worlds. Thank you for your help.
