### ISSUE TITLE
Penguin Shadow Size

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#188]
Forge version: 14.23.0.2491
Twilight Forest version: 2.4.0.82

Steps to reproduce:
1. Look at the Penguin.

What I expected to happen:
A proportionate sized shadow.

What happened instead:
Fat.
https://i.imgur.com/OOsMaLq.png

**Comment by Drullkus** [comment]
乇乂ㄒ尺卂 ㄒ卄丨匚匚

![Extra Thicc](http://i1.kym-cdn.com/photos/images/newsfeed/001/232/046/190.gif)
