### ISSUE TITLE
Got this crash shortly after loading world.

### ISSUE THREAD

**Issue by gitguette** [TeamTwilight/twilightforest#1883]
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1846

### Crash Report (if applicable)

https://gist.github.com/gitguette/786b31744f733ec0fddcdf69a928da36

### Steps to Reproduce

Have twilight forest mod.
Load a world.

### What You Expected

Game works normally.

### What Happened Instead

Game freezes, tries to save and exit, and crashes soon after.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
alexsmobs is what crashed

**Comment by gitguette** [comment]
is this mod incompatible with alex's mobs? it only crashes like this if twilight forest is loaded.

**Comment by lcy0x1** [comment]
It seems like a 3-way (at least) compatibility issue with Iron’s Spell, Alex Mobs, and TF. 

Iron Spell is trying to render a spell casting mob with Alex’s flying fish boot. I’m not sure how TF comes into this

**Comment by gitguette** [comment]
the game crashes without it sometimes, is it possible that the incompatibility is between alex's mobs and iron's spells, and TF just makes it worse?

**Comment by GizmoTheMoonPig** [comment]
this isnt an issue with TF, see https://github.com/AlexModGuy/AlexsMobs/issues/1882
