### ISSUE TITLE
Banner patterns not working

### ISSUE THREAD

**Issue by LazarBajkic** [TeamTwilight/twilightforest#1886]
### Forge Version

1.20.1

### Twilight Forest Version

4.3.1846

### Steps to Reproduce

1.add everything to the loom
2.craft it, nothing shows on the banner

### What You Expected

I expected the naga pattern or the yeti pattern (tried with both)

### What Happened Instead

 neither worked and left the banner blank

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
unable to reproduce. All banner patterns we add (minus quest ram as that one doesnt have a texture) work just fine on banners. Tested on 4.3.1850

**Comment by jodlodi** [comment]
If you're talking about the quest ram one, it has now been added to the NYI item tag, and it will be implemented properly in the future, if you're having trouble with the other banner patterns, re-open this issue and add more info
