### ISSUE TITLE
Giant Pickaxe doesn't work

### ISSUE THREAD

**Issue by 0Isospin0** [TeamTwilight/twilightforest#1888]
### Forge Version

1.20.1

### Twilight Forest Version

4.3.1850

### Steps to Reproduce

1. I Can't
2. Break Blocks
3. With Giant Pickaxe

### What You Expected

4x4x4 blocks should be broken when using Giant Pickaxe

### What Happened Instead

I can't break blocks

### Additional Details

![2023-09-23_23 03 01](https://github.com/TeamTwilight/twilightforest/assets/145584434/646e6660-509c-4172-b5f1-2473b452ac1d)
![2023-09-23_23 02 58](https://github.com/TeamTwilight/twilightforest/assets/145584434/e4a5bdd0-ee9a-4c0b-a9d5-6b73bbf05f04)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Goriragi** [comment]
I`m having the same issue, when breaking a block it make the animation of breaking but instantly restore all blocks, tried with and without enchant, in overworld and nether.
Tried in other worlds in creative but has the same issue.

![2023-09-24_16 15 45_2](https://github.com/TeamTwilight/twilightforest/assets/137117129/4b283a95-24b9-4a5e-be3d-f9a7fed31f04)
![2023-09-24_16 15 45_3](https://github.com/TeamTwilight/twilightforest/assets/137117129/d8c7617d-1c1b-4efa-8140-eba0ee629d81)
![2023-09-24_16 15 43_2](https://github.com/TeamTwilight/twilightforest/assets/137117129/7aa6b65b-c343-403e-ab54-e849af248175)
![2023-09-24_16 15 44](https://github.com/TeamTwilight/twilightforest/assets/137117129/292ea936-cbb5-4440-994d-0f98ab3fbbe3)
![2023-09-24_16 15 44_2](https://github.com/TeamTwilight/twilightforest/assets/137117129/fb606e60-ca30-49bc-82a9-ba54527eec80)
![2023-09-24_16 15 45](https://github.com/TeamTwilight/twilightforest/assets/137117129/5a533734-8c25-4d6f-9ad4-710efe104d02)

**Comment by aqua-air** [comment]
Same problem here, exactly same issues stated above.  Sanctum Network curseforge modpack 1.20.1

**Comment by jodlodi** [comment]
I am unable to replicate this with TF alone, so I ask for your help in finding what mod conflict is causing this to happen, so that I can see what can be done about this

**Comment by aqua-air** [comment]
For the rest of you, the problem is the tree chop mod. Replace the tree chop mod you use with tree harvester and it should fix this problem

**Comment by muon-rw** [comment]
If you'd prefer to keep HT's TreeChop, set `multimine = False` in treechop-common.toml. 

It currently breaks all other AoE abilities including every Vein mining mod and Ars, so this is not a twilight forest issue.
