### ISSUE TITLE
boss opening bug

### ISSUE THREAD

**Issue by Xardiii** [TeamTwilight/twilightforest#1889]
### Forge Version

1.12.2

### Twilight Forest Version

3.11.1021

### Steps to Reproduce

after killing the Naga boss, loot drops, but the achievement for killing the boss is not given, because of this I cannot kill subsequent bosses, Lich, and so on

### What You Expected

I hope to find a way to fix this bug with the achievement about killing Naga

### What Happened Instead

The achievement was not obtained after killing the boss, because of this it is not possible to kill subsequent bosses

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Toastr125** [comment]
Try leaving and rejoining. That's just a general bug with advancements in 1.12, they don't always register immediately

**Comment by Xardiii** [comment]
> Попробуйте выйти и снова зайти. Это просто общий баг с улучшениями в 1.12, они не всегда сразу прописываются

yes it worked, THANK YOU very much!!!)
