### ISSUE TITLE
Trophy Pedestal Texture

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#189]
Forge version: 14.23.0.2491
Twilight Forest version: 2.4.0.82

Steps to reproduce:
1. Find a Trophy Pedestal

What I expected to happen:
For it to show four different bosses on the sides like in previous versions.

What happened instead:
The Naga appears on all four sides; both active and inactive.

**Comment by williewillus** [comment]
did we decide to expand/change it?
I checked in 1.7 a while ago and it seems like the pedestal should just have a FACING property, and shows the four original bosses on it (+ the LATENT property)
But in the codebase it has an extra BOSS property that seems to be unused.

**Comment by Drullkus** [comment]
Fixed in e0a2e31
