### ISSUE TITLE
Crashing issues with magic map

### ISSUE THREAD

**Issue by geterhun** [TeamTwilight/twilightforest#1890]
### Forge Version

47.1.46

### Twilight Forest Version

4.3.1850

### Client Log

https://gist.github.com/geterhun/5c1170f7856ad9df23d7ff4a197dafc3

### Crash Report (if applicable)

https://gist.github.com/geterhun/5c1170f7856ad9df23d7ff4a197dafc3

### Steps to Reproduce

1.) use modpack from curseforge Name-- MysticCraft: An Epic Journey through the Multiverse

2.) get magic map use it in the twilight world

### What You Expected

well since its a map it should have opened

### What Happened Instead

Crashed saying yjava.lang.NullPointerException: Cannot read field "f_256718_" because "data" is null

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
looks to be an issue with moonlight lib's injection into the map packet. Make sure you update moonlight as this looks like it shouldn't be possible in the newest version

**Comment by MehVahdJukaar** [comment]
you can close this btw, i already moved injection point and all works fine now
