### ISSUE TITLE
Entity renderer setup re-opens resource packs countless times, leading to absurd game load times when combined with conditional dynamic resource generation

### ISSUE THREAD

**Issue by lukebemish** [TeamTwilight/twilightforest#1893]
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1850

### Client Log

https://gist.github.com/lukebemish/ee4cd5d4730c7452d6e51a429f4f5d55

### Steps to Reproduce

1. Install Exavated Variants, Dynamic Asset Generator, and Twilight Forest. Adding more mods that provide resources, or that Excavated Variants will generate variants for, will increase the effect.
2. Launch the game

### What You Expected

This bug was encountered while investigating lukebemish/ExcavatedVariants#174. What occurs is that https://github.com/TeamTwilight/twilightforest/blob/e170d59945b1eb15451d186c213b933b54c9c866/src/main/java/twilightforest/client/JappaPackReloadListener.java#L41 is used countless times during load - each load invokes `Pack#open` and `PackResources#getResource` for each `Pack` in the pack repository. This operation is made expensive when a mod - in this case, the combination of Excavated Variants and Dynamic Asset Generator - makes this operation expensive for some packs. The resources that DynAssetGen generates depend on the contents of certain other resources in other packs - meaning that DynAssetGen has to re-load, read, and process those resources each time this method in Twilight Forest is invoked. This leads to an *extremely* long load time - in the case of the issue I was investigating, it appeared to cause the game to crash in some way. There is not really any way around this in DynAssetGen - I have to recalculate that stuff each time it's opened because there's no guarantee that the resources it depends on haven't changed between resource reloads - say, if a resource pack is changed by the user.

### What Happened Instead

Load time took around 5 minutes to set up twilight forest entity renderers with a larger pack, where Excavated Variants has a larger number of things to check on during resource reload: https://gist.github.com/lukebemish/c21c899b10fab7c48f8b0e5d4081605a

### Additional Details

In my opinion, the optimal solution here would be for Twilight Forest to query the `PackResources` of the currently open `ResourceManager` directly - with `Minecraft.getResourceManager().listPacks()`. Is there a reason this would not work? It uses the already open pack instances, instead of re-opening every single pack every time the listener or that supplier is used - which is what the current solution does.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Heyo! Very sorry about that. I wasnt aware listPacks was a thing: switched to it and everything still seems to still be working as intended. Can you give [this build](https://artprodcus3.artifacts.visualstudio.com/Abaabfa6c-deea-4587-ba05-c308c2597b7a/1ef09d39-06cf-41fa-ad98-7258b70c2a72/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3RlYW10d2lsaWdodC9wcm9qZWN0SWQvMWVmMDlkMzktMDZjZi00MWZhLWFkOTgtNzI1OGI3MGMyYTcyL2J1aWxkSWQvMzM4NS9hcnRpZmFjdE5hbWUvUmVsZWFzZQ==0/content?format=file&subPath=%2Ftwilightforest-1.20.1-4.3.1855-universal.jar) a test and see if it fixes the issue?

**Comment by lukebemish** [comment]
Seems to fix the load time issue! I don't know enough about how Twilight Forest works to know if anything else broke

**Comment by GizmoTheMoonPig** [comment]
I tested before pushing, models are still changed as needed. Thanks for letting me know about this! I'll have a fix pushed onto curseforge after I fix another issue I need to tackle
