### ISSUE TITLE
Improper rendering of the giant's sword and pickaxe

### ISSUE THREAD

**Issue by gitguette** [TeamTwilight/twilightforest#1894]
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1850

### Client Log

https://gist.github.com/gitguette/15ff0c7e8e073a08c80c1a493923f223

### Steps to Reproduce

- Launch game
- Use creative menu to grab a giant's sword or giant's pickaxe

### What You Expected

The player holding a very large stone sword and pickaxe.

### What Happened Instead

The player holds the same sprite as the inventory icon.

### Additional Details

![2023-10-09_10 17 19](https://github.com/TeamTwilight/twilightforest/assets/109386903/e512dd54-610f-413e-927d-6de1ff11f19e)
![2023-10-09_10 15 29](https://github.com/TeamTwilight/twilightforest/assets/109386903/125514bf-6a15-442b-a454-4d2076cbca7f)
![2023-10-09_10 17 13](https://github.com/TeamTwilight/twilightforest/assets/109386903/9b27e0d4-0a47-45b9-b513-4d871234e8df)
![2023-10-09_10 15 33](https://github.com/TeamTwilight/twilightforest/assets/109386903/5a8991a1-0d8f-4141-b00f-ee3bf6bf5ff2)
![2023-10-09_10 15 18](https://github.com/TeamTwilight/twilightforest/assets/109386903/42042c34-d1e9-4d84-870d-54e41931f219)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Unable to reproduce, currently playing in a pack with over 250 mods and it renders just fine. Also works as intended with just the Twilight Forest installed.
![2023-10-09_11 53 45](https://github.com/TeamTwilight/twilightforest/assets/67468252/2774141a-641e-4756-aae6-1a9c4bf3ac1c)
Do you have any sort of resource pack that would be changing the item jsons?

**Comment by gitguette** [comment]
was using the jappa pack, but it was disabled when i took those screenshots, and it doesn't seem to have any textures for the giant's sword

**Comment by gitguette** [comment]
tested it with no other mods and it works, finding the bad mod now

**Comment by gitguette** [comment]
found the bad mod! continuity(running on sinytra connector)

**Comment by GizmoTheMoonPig** [comment]
Probably an issue with them not taking forges separate model transforms into account. Gonna say this isn't our fault as that's not a system we made, it's something built into forge. I don't really expect this to be fixed as it's a fabric mod however.
