### ISSUE TITLE
[Suggestion] damaging player when on top of Dark forest biome

### ISSUE THREAD

**Issue by Nightfigure** [TeamTwilight/twilightforest#1895]
### The Suggestion

Damaging the player when on the top of the dark forest biome/on top of thick darkwood leaves similar to the forest maze

### Why Should It Be in the Mod?

it would prevent people from just towering up and going to the tower

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
But players need to go to the stronghold before the dark tower first....

**Comment by Nightfigure** [comment]
yes i know that,but a lot of people i've seen play the mod just tower up and walk across the top of the biome to go the dark tower.

**Comment by Tamaized** [comment]
If they've already gone through the dark forest to do the stronghold then that seems fine to me.

**Comment by Happy1speed** [comment]
It would be so funny if this was actually added to the mod since pretty much every time I playthrough the mod I seem to find a dark forest stronghold right on the edge, beat it, and proceed to skip most of the dark forest hostiles by running along the treetops.

**Comment by Happy1speed** [comment]
Although, It would make finding the dark tower extra hard

**Comment by jodlodi** [comment]
we decided that its best if players do what they want
