### ISSUE TITLE
Incompatibility with Moonlight 1.20.1

### ISSUE THREAD

**Issue by litjohn50** [TeamTwilight/twilightforest#1897]
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1850-universal

### Client Log

https://gist.github.com/litjohn50/7a5fcfe7f61ba86618bf52a1c1aee6af

### Steps to Reproduce

https://github.com/MehVahdJukaar/Moonlight/issues/161

### What You Expected

Not to disconnect and magic maps work correctly.

### What Happened Instead

Disconnect with inability to rejoin

### Additional Details

Other mods used in the testing

labels-1.20-1.16.jar
supplementaries-1.20-2.6.12.jar
dummmmmmy-1.20-1.8.3.jar
suppsquared-1.20-1.1.10.jar

Debug log at the previously mentioned issue

It is similar to another ticket, but instead of crashing it just disconnects.

https://github.com/TeamTwilight/twilightforest/issues/1890

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by muon-rw** [comment]
Update moonlight lib to 2.8.50

This is not a twilight forest issue.

**Comment by litjohn50** [comment]
Fixed thanks
