### ISSUE TITLE
SnowBiome Crash

### ISSUE THREAD

**Issue by ChokoNutss** [TeamTwilight/twilightforest#1899]
### Forge Version

40.2.10

### Twilight Forest Version

4.1.1494

### Client Log

<script src="https://gist.github.com/ChokoNutss/9053cc4a85ff1fea5b7eb1fbd2d952a7.js"></script>

### Crash Report (if applicable)

<script src="https://gist.github.com/ChokoNutss/9d8e074d9d2daa037be40c816723b431.js"></script>

### Steps to Reproduce

1. I enter the dimension
2.  I kill some bosses
3. nothing happens
4. i found the snow biome
5. i walk in to it
6. the chunks barely charge 
7. and the game crash in a minute

### What You Expected

I don't think it should have crashed

### What Happened Instead

When i try to open my world again, it crashes too. i can't even play enymore

### Additional Details

i have some other mods.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [ ] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
You're using an old version, update the mod.

**Comment by ChokoNutss** [comment]
really? i'm using the latest one for 1.18.2, there is somewhere else i can find the updated version?

**Comment by Tamaized** [comment]
Oh I totally misread this crash, i thought this was the recent 1.20 crash because its very similar, oops!!

The crash is from the batchedentityrendering mod

**Comment by ChokoNutss** [comment]
This isn't exactly a mod, apparently it's a bug in the oculus mod, let me try remove it

**Comment by ChokoNutss** [comment]
It worked, I had to take off the Oculus, but it worked, thank you 😭😭
