### ISSUE TITLE
Moonworm Queen Wiggling

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#190]
Forge version: 14.23.0.2491
Twilight Forest version: 2.4.0.82

Steps to reproduce:
1. Use a right-clickable item like the Peacock Feather Fan or the Crumble Horn while the Moonworm Queen is on your hot bar.
2. Watch the Moonworm Queen drop some sick uncalled for dance moves.

What I expected to happen:
The Moonworm Queen to be still.

What happened instead:
I got schooled in dancing.

**Comment by williewillus** [comment]
this should be fixed already in 72+ 0.o

**Comment by williewillus** [comment]
EDIT guess not, I'm really confused
