### ISSUE TITLE
Game crashing when Naga spawner

### ISSUE THREAD

**Issue by MiracleBelief** [TeamTwilight/twilightforest#1900]
### Forge Version

47.2.1

### Twilight Forest Version

4.3.1860

### Crash Report (if applicable)

https://gist.github.com/MiracleBelief/6681d491d7d3e5e9465fae10b88a6227

### Steps to Reproduce

1 enter the Naga Courtyard

### What You Expected

I expected my game to not crash.

### What Happened Instead

Crash.

### Additional Details

Thank you.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
The problem mod is Alex's Caves.

https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/java/com/github/alexmodguy/alexscaves/mixin/EntityMixin.java#L208

**Comment by boredboardboared** [comment]
Having the same issue, don't have alex's caves installed.

**Comment by GizmoTheMoonPig** [comment]
then you arent having the same issue. Please open a new ticket and attach a crash report
