### ISSUE TITLE
Game crashes when placed shulker box next to the force field

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [TeamTwilight/twilightforest#1902]
### Forge Version

14.23.5.2855

### Twilight Forest Version

3.11.1021

### Client Log

https://gist.github.com/WOSHIZHAZHA120/0d835746ac006c2f7905a1b9d126a213#file-debug-log

### Crash Report (if applicable)

https://gist.github.com/WOSHIZHAZHA120/0d835746ac006c2f7905a1b9d126a213#file-gistfile1-txt

### Steps to Reproduce

1. Place force field
2. Place the shulker box next to the force field
3. Game crashed

### What You Expected

Game normal running

### What Happened Instead

Game crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
1.12 is no longer supported and this isn't an issue in newer versions
