### ISSUE TITLE
Naga/Hydra Not Rendering

### ISSUE THREAD

**Issue by cuoconnell** [TeamTwilight/twilightforest#1903]
### Forge Version

47.2.0

### Twilight Forest Version

4.3.1860

### Client Log

https://gist.github.com/cuoconnell/82626ff1fb34f0f87aa21cce89db6f57

### Steps to Reproduce

1. install performant mod
2. spawn in naga
3. spawn in hydra
4. find tailless/headless
![Sample](https://github.com/TeamTwilight/twilightforest/assets/6139440/2e187a0a-7051-4408-b2d4-2a0661a1eeaf)

### What You Expected

Cool mobs to spawn and my frame rates to improve.

### What Happened Instead

My frame rates improved but mobs were nerfed.

### Additional Details

I truly did not install optifine, I'm not using a resource pack, and I don't have a mod specifically called Entity Culler though the entity culling behavior may be called by Performant. One of its features is "Dynamic Entity Rendering" but it has a config which can be used to exclude entities from its feature. Right now I have it set to the following:  https://gist.github.com/cuoconnell/4a47ece7f0c272689dae71510475d9ee

and was able to get the naga to come back. But per the config I just disabled the feature globally. I was hoping to get the entity ids to exclude those mobs from being subjected to the "culling".

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
I generally don't look into performant issues as that mod is really invasive but I'll see if I can figure anything out when I get a chance. Don't get your hopes up for a fix though

**Comment by GizmoTheMoonPig** [comment]
considering performant is currently locked behind a patreon subscription I cant look into this
