### ISSUE TITLE
Missing registry: ResourceKey[minecraft:root / twilight:restrictions]

### ISSUE THREAD

**Issue by Zendrex** [TeamTwilight/twilightforest#1904]
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1809+

### Client Log

https://gist.github.com/Zendrex/f01a1cb49ec34da3ea6019f306febf25

### Crash Report (if applicable)

https://gist.github.com/Zendrex/749afce24a6f70246c9a0d1a855c89bc

### Steps to Reproduce

Install Twilight Forest version 4.3.1809+
Connect to a vanilla/spigot/mohist/etc server on 1.20.1

### What You Expected

Not to crash

### What Happened Instead

Crashed

### Additional Details

I've discovered that this occurs on any version starting at 4.3.1809 and beyond.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
You need the mod on both the client and the server.
