### ISSUE TITLE
[Suggestion] Replace vanilla wood with Twilight Forest wood in Twilight Forest chest loot tables

### ISSUE THREAD

**Issue by aarontapper** [TeamTwilight/twilightforest#1905]
### The Suggestion

One of the items I found in a Hedge Maze chest was vanilla oak planks. As far as I know, these are not obtainable or at least uncommon in the Twilight Forest dimension now that each TF wood has its own planks. I'd suggest replacing vanilla woods with those obtainable in the mod

### Why Should It Be in the Mod?

This change would add consistency to the items crafted in the world and found in chests. Additionally, it would simplify inventory management while in the Twilight Forest dimension

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
for the record vanilla oak and birch trees can still be found all over the dimension, but I'll definitely bring this up for discussion behind the scenes at some point

**Comment by Killer-Demon** [comment]
We've pretty much come to the conclusion that we like the Hedge Mazes carrying forth their ancient legacy. Thus, oak-only loot remains for the Hedge Mazes.
