### ISSUE TITLE
Generating a chunk in The Twilight Forest dimension, ends in a fatal crash, and is repeated on every attempt to generate said chunk.

### ISSUE THREAD

**Issue by d3voted4ngeI** [TeamTwilight/twilightforest#1906]
### Forge Version

1.20.1-47.2.0

### Twilight Forest Version

1.20.1-4.3.1860-universal

### Client Log

[log](https://gist.github.com/d3voted4ngeI/34cbc8f3b1804520619b05726e133838) (the error is on line 415)

### Crash Report (if applicable)

[report](https://gist.github.com/d3voted4ngeI/b5b0dc89b00b23409e9cd0e3099ec5b1)

### Steps to Reproduce

1. Have the same set of mods on a Minecraft server hosting platform as me.
2. Start generating chunks in The Twilight Forest dimension, either manually or using a chunk pre-generator.
3. At some point run into the exception and crash.
4. After you hit the chunk in world generation that causes this exception, every time you try to generate said chunk, the same crash will occur.

### What You Expected

The chunk generation of The Twilight Forest to go smoothly as it did on all other dimensions.

### What Happened Instead

An unexpected exception occurred that caused the server to crash.

### Additional Details

List of mods on the server with their precise versions: [mods](https://gist.github.com/d3voted4ngeI/2779bf6c7f488f17c33ff5e609024134)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Gonna have to look into this - not quite sure what's going wrong here but this might be another case of another mod revealing an issue in our structure code

**Comment by GizmoTheMoonPig** [comment]
I looked into this and theres no possible way this should happen when generating a maze, but I put a null check in just in case. Your game will no longer crash but a warning will be printed to your log of where the problem block is.
