### ISSUE TITLE
{Incompatibility} Nether Dungeons w/ Twilight Forest crash.

### ISSUE THREAD

**Issue by togera13** [TeamTwilight/twilightforest#1907]
### Forge Version

43.3.2

### Twilight Forest Version

1.19.2-4.2.1518

### Crash Report (if applicable)

https://gist.github.com/togera13/eb9b5762dce4857c38b2701d49c20557

### Steps to Reproduce

It happened when I went near a goblin thing, unless my friend triggered the crash idk.

### What You Expected

To fight a goblin.

### What Happened Instead

The server crashed.

### Additional Details

I don't really know if it was nether dungeons that did it, but the crash report mentioned it & I haven't had any crashes really up until adding this mod & a few others so I suspect it is incompatible.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Issue with nether dungeons: they're making an unsafe cast when applying some sort of vampirism effect or whatever. Can't check what the code does as the mod isn't open source and I'm currently away, but this is 100% on them

**Comment by Nikonell** [comment]
I am one of the authors of the Nether Dungeons mod. The bug has been fixed in the latest update.
