### ISSUE TITLE
Uncrafting table: infinite diamond duplication glitch

### ISSUE THREAD

**Issue by Voltem0** [TeamTwilight/twilightforest#1909]
### Forge Version

47.1.3

### Twilight Forest Version

4.3.1860

### Client Log

-

### Crash Report (if applicable)

-

### Steps to Reproduce

Setup: 
Have at least 2 levels of xp
Have 9 diamonds

1) craft a pair of diamond leggins
2) put those in the 'input slot' of the uncrafting table but do not yet take them out.
3) fill the remaining slots in the middle 3x3 grid with your 2 leftover diamonds and you can grab the resulting diamond block (you cannot do this step if you do not have 2 levels but it does not actually cost xp)
4) you can then still grab the diamond leggins after taking out the block. You get both the leggins and the block. (you just made a 7 diamond profit)
6) turn the block into diamonds, repeat turning the leggins into blocks over and over again

infinite diamond duplication!

This works with other recipes too, diamonds is simply the most outrageous. i actually discovered this with droppers and dispensers. Put a dropper in, put a bow in the middle slot, grab a dispenser out, but then you can actually grab the same dropper from the output slot, effectively allowing you to turn bows into dispensers.
It should work with any other recipes that follow the general formula as well, including iron (infinite iron) and gold (infinite gold) infinite steelleaf, ironwood etc
This is on the most recent version of twilightforest.

### What You Expected

-

### What Happened Instead

-

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
The leggings are supposed to be getting consumed but for some reason they're not

**Comment by EvergreenSystems** [comment]
![2023-10-31_15 50 28](https://github.com/TeamTwilight/twilightforest/assets/23658767/37986af7-1fc6-4aa4-96ce-e81469087e8a)
Yep

**Comment by GizmoTheMoonPig** [comment]
looks like I broke this fixing a different bug, awesome. I'll have a fix out shortly

**Comment by GizmoTheMoonPig** [comment]
mfw missed a single exclamation point

**Comment by Voltem0** [comment]
it do be like that sometimes
