### ISSUE TITLE
O  mod não salva minha progressão de bosses 

### ISSUE THREAD

**Issue by TheWolf737** [TeamTwilight/twilightforest#1911]
### Forge Version

1.12.2 - 14.23.5.2860

### Twilight Forest Version

twilightforest-1.12.2-3.8.654-universal

### Steps to Reproduce

jogue a versão twilightforest-1.12.2-3.8.654-universal do mod
com o forge na versão 1.12.2 - 14.23.5.2860

### What You Expected

Que salva-se minha progressão nos bosses 

### What Happened Instead

Não salvou 

### Additional Details

Simplesmente não salva minha progressão dos bosses, de maneira aleatória simplesmente "reseta", não posso acessar o labirinto do Minoshroom mesmo tendo matado o lich, ai tenho que matar a naga e assim por diante, para poder prosseguir.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
progression is tied to your advancements. If killing a boss or holding its drops doesn't grant you the advancement, try exiting and re-entering the world. Advancements are a bit buggy in 1.12
