### ISSUE TITLE
Error java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.

### ISSUE THREAD

**Issue by mikerazer610** [TeamTwilight/twilightforest#1912]
### Forge Version

14.23.5.2860

### Twilight Forest Version

1.12.2-3.11.1021

### Client Log

<script src="https://gist.github.com/mikerazer610/4a3c5dc02136fb9d252fe18214ac222a.js"></script>

### Crash Report (if applicable)

<script src="https://gist.github.com/mikerazer610/6f28f75722b429dd8c24970d6b12ab42.js"></script>

### Steps to Reproduce

ran a personal mod pack with twilight forest mod in it

### What You Expected

to work

### What Happened Instead

crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
You have too many mods that add biomes, remove some.
