### ISSUE TITLE
[1.20.1] Java Runtime Environment Crash

### ISSUE THREAD

**Issue by PlayfulPiano** [TeamTwilight/twilightforest#1913]
### Forge Version

47.2.4

### Twilight Forest Version

4.3.1860

### Client Log

https://gist.github.com/PlayfulPiano/5a82a205fc90ee8f06a65f5625fa75e1

### Crash Report (if applicable)

https://gist.github.com/PlayfulPiano/994f7f29455038121d4a33c1933e63ec

### Steps to Reproduce

1. Enter the Twilight Forest.
2. Run outside of where you spawned for an extended period of time.
3. Crash occurs.

### What You Expected

No Crash occurs.

### What Happened Instead

Crash occurs.

### Additional Details

My Nvidia Driver (1650 ti) is updated to the latest version (546.01) dated for 2023/10/31. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this was solved on our discord: advancedcompass is doing some strange rendering code
