### ISSUE TITLE
game crashes as soon and I press play

### ISSUE THREAD

**Issue by laurenkhan** [TeamTwilight/twilightforest#1916]
Forge version: 48.0.37
Twilight Forest version: 4.3.1860
Link to crash log: <im sorry I don't know how to link it

What I expected to happen: to open Minecraft and use the mod.

What happened instead: my game crashed before I loaded and said "The game crashed whilst rendering overlay"

**Comment by GizmoTheMoonPig** [comment]
forge 48 is for minecraft 1.20.2. The mod doesn't currently work in that version. We list compatible versions for a reason on curseforge, please follow them.
