### ISSUE TITLE
1.20.1 Dupe using a uncrafting workbench

### ISSUE THREAD

**Issue by Lucky3228** [TeamTwilight/twilightforest#1917]
### Forge Version

47.2.1

### Twilight Forest Version

4.3.1850

### Steps to Reproduce

Dupe using a uncrafting workbench, everything is visible in the video
'twilightforest:uncrafting_table'

https://youtu.be/64l5n_T_WoQ

### What You Expected

There shouldn't be a dupе

### What Happened Instead

Refer to "steps to reproduce".

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Update the mod, this has already been fixed
