### ISSUE TITLE
Fiddlehead Harvesting Without Shears

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#192]
Forge version: 14.23.0.2491
Twilight Forest version: 2.4.0.82

Steps to reproduce:
1. Hit a Fiddlehead without Shears.
2. You get the Fiddlehead.

What I expected to happen:
Needing Shears to obtain the Fiddlehead like any other grass like in the forest.

What happened instead:
Fiddleheads drop themselves when hit with anything.

**Comment by Tamaized** [comment]
This was actually how they behaved in 1.7.10 as well (Just tested it)
Shears weren't needed. 

Unless this was a bug back then too?
