### ISSUE TITLE
Minotaur Labrynth missing blocks?

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1922]
### Forge Version

20.2.37-beta

### Twilight Forest Version

4.4.1909 

### Steps to Reproduce

Not sure how to replicate. Minoshroom Labrynth has a line of holes? The corners connected wall -> roof/floor just dont exist on the lower flower. Screenshot is from the SE corner. 

### What You Expected

No holes?

### What Happened Instead

Holes 😔✊

### Additional Details

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/9a724ba7-faee-4145-a315-cc06ea1db87b)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Sleepy-Horse** [comment]
Thanks for the report! I fixed this bug in 1.20.2. Could you close this issue? 
@AriaElidove

**Comment by AriaElidove** [comment]
Yes I can, thank you for reminding me (Thought Tama closed it when merged)
