### ISSUE TITLE
Magic Map Out of Range for Conquering

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1923]
### Forge Version

20.2.37-beta

### Twilight Forest Version

4.4.1909 

### Steps to Reproduce

If the player is off of the Magic Map range, but there is still an icon representing a structure, it will not be marked unless the player is within the map's range. Tested with both Naga and with Phantom Knights.

### What You Expected

Funny edge of map was supposed to be my friend, not my enemy :(

### What Happened Instead

if your icon turns into the circle but you're in the boss room still, you're fucked if you stand on the wrong part of the room lol.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Working as intended, Vanilla maps work in this same way
