### ISSUE TITLE
Magic Map Conquering (WAI, extra notes) | Outside of Biome and Multi Boss Spawner Spawns

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1924]
### Forge Version

20.2.37-beta

### Twilight Forest Version

4.4.1909 

### Client Log

https://gist.github.com/AriaElidove/46771e1234bc24a8c27da72d5ed16961

### Steps to Reproduce

Bosses don't really care where they are so long as they are within range for their structure on the map, the Magic Map can mark it as complete despite being 1,000+ blocks away. Bosses spawned by non-generic/default boss spawner blocks that are slain in their respective quarters counts. Which ever boss is killed first takes the priority in conquering on the map (A respawning system COULD actually benefit from this). Important to note that the spawn eggs do NOT mimic this behavior whatsoever. 

Tested with the Minoshroom at -1,452/-2,673 and the nearest labrynth marked was at -1,557/-2,550, and again within the Fiery Swamp (To test biome).

### What You Expected

Bosses to have a smaller conquorering range (at least within the structure bounding box).

### What Happened Instead

Your Minoshroom is now going to jail for multiple counts of tomfoolery after defying the laws of logic by standing in the Fiery Swamp.

### Additional Details

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/1ee17733-74d0-428d-98b1-0214f1aaf007)
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/7bad8081-77a8-41be-a0c4-ae4cbd66a0cf)

before and after i ated him for not giving me milk >:(

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Working as intended, upon spawning bosses will save their "home" location. Used for their loot chest and also marking a structure as conquered. If a boss has been taken out of its home structure, it'll be reasonable to mark the structure as completed since boss rewards are no longer obtainable there
