### ISSUE TITLE
Lamp of Cinders / Mazebreaker Container >>> TwF Chest

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1926]
### The Suggestion

Turn the chests that the Lamp of Cinders and Mazebreaker spawns in into TwF chests opposed to vanilla chests

### Why Should It Be in the Mod?

Prevents per-user rare loot via Lootr and marks structure as conquered better

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Gonna close this as we will eventually switch the chests to use TF chests (probably during each structure's rework), but I will be keeping lootr support for all structure chests as I don't think people should be forced to find a new structure if someone else has already conquered it
