### ISSUE TITLE
magic map causes internal crash when joining server but not on single player

### ISSUE THREAD

**Issue by GreenForzeGaming** [TeamTwilight/twilightforest#1928]
### Forge Version

47.2.0

### Twilight Forest Version

1.20.1-4.3.1893

### Client Log

https://gist.github.com/GreenForzeGaming/7b611fddd7da947f28d35e9e2caf72ae

### Crash Report (if applicable)

https://gist.github.com/GreenForzeGaming/b010c202391b9c57cf0c265024a8ed7c

### Steps to Reproduce

be on a server
use a magic map.
causes internal crash
can no longer join due to becomming a ticking player which reapets step 3

### What You Expected

the map too work

### What Happened Instead

map sent me too the error world

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Busyfox123** [comment]
I also encountered this issue where the server archive was directly damaged

**Comment by ianwilliamson5** [comment]
just encountered it

**Comment by yath178** [comment]
I also encoutered almost same situation on 1.20.2(neoforge)
server: linux(ubuntu)
client: windows10 and MacOS
when it happend, the client could't login the server with "internal server error".
but deleted MagicMap on inventory using NBT exploer, once that it solved .

**Comment by Sm0keWag0n** [comment]
Replicated the same issue many times with several users on NeoForge 20.2.88 (MC 1.20.2) using `twilightforest-1.20.2-4.4.1977`. User can create a blank magic map, but as soon as the map is used, the server logs the same type of internal error linked in OP's comment, and the user is disconnected. Attempting to rejoin immediately repeats the error-and-disconnect.

Oddly, I have another server running the same versions as OP (Forge 47.2.0 / `twilightforest-1.20.1-4.3.1893`) and that server has no issue at all with magic maps.

**Comment by GizmoTheMoonPig** [comment]
pretty sure this is an issue with map atlases (see https://github.com/MehVahdJukaar/mapatlases-neoforge/issues/93). Our decoration rendering stuff should NEVER be called on the server and somebody is. Since map atlases does stuff with our maps im gonna assume its on them. Will reopen if this isnt the case and someone lets me know
