### ISSUE TITLE
Torchberry Plant and and Root Strands Placement

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#193]
Forge version: 14.23.0.2491
Twilight Forest version: 2.4.0.82

Steps to reproduce:
1. Try to place them on the underside of a block.
2. Only able to place them on top of dirt.
3. Despawns after a couple of seconds.

What I expected to happen:
To be able to hang Torchberry Plants and Root Strands from the underside of blocks.

What happened instead:
They can only be placed on top of blocks, which makes them disappear after a couple of seconds.

**Comment by Tamaized** [comment]
Duplicate of #79?

**Comment by Killer-Demon** [comment]
It seems so.
Searched for Torchberry and got nothing, that one is only about Root Strands.
