### ISSUE TITLE
Fix Forcefield Blockstates in Castle Generation 

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1938]
### The Suggestion

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/4a87bfba-b331-486b-88f7-5ce5f55a3519)

### Why Should It Be in the Mod?

I'm so fucking sorry Jodi xd

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
Anything related to castle generation won't get touched until we're actively working on it. The entire place is broken.

**Comment by AriaElidove** [comment]
I know. Just putting it up so you guys dont end up forgetting about it. 

Also found that the bottoms dont touch here, similar to how the basement has the top connection issue.

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/70bcfa08-fb2f-45a8-baf1-7b1f4ee8e50b)

**Comment by Tamaized** [comment]
The structure is currently code based. All of it is going to get thrown out and replaced with jigsaws.
