### ISSUE TITLE
Fix map icons

### ISSUE THREAD

**Issue by williewillus** [TeamTwilight/twilightforest#194]
now that forge PR is in, restore real icons.

**Comment by Drullkus** [comment]
🎉 🎉 🎉 🎉 🎉

**Comment by williewillus** [comment]
As of latest commit, all that remains is the logic here: https://github.com/TeamTwilight/twilightforest/blob/7558f4deb8e3a11fff900a2980e92e635c18fd14/src/main/java/twilightforest/TFMagicMapData.java#L118

which should just be a modified version of the vanilla code in `MapItemRenderer`.

However, I'm too lazy to do it right at this moment, and I also don't know what icon corresponds to what feature ID.

So if anyone wants to do it before I do go right ahead.
