### ISSUE TITLE
Crash Report on Local Server.

### ISSUE THREAD

**Issue by BreezyShad** [TeamTwilight/twilightforest#1942]
### Forge Version

47.2.17

### Twilight Forest Version

4.3.1893

### Crash Report (if applicable)

https://gist.github.com/BreezyShad/81216a9a26ff88de6491ec72604fd419

### Steps to Reproduce

Joining the server crashes the player.

### What You Expected

Well, simply joining the server.

### What Happened Instead

My game crashed, though the server is still running.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Are the server and your client on the exact same version of the mod? Please double check

**Comment by Sleepy-Horse** [comment]
I can't reproduce the bug with only twilightforest.

**Comment by BreezyShad** [comment]
I managed to fix it, do not worry.
