### ISSUE TITLE
Is it possible to use this mod on a private server? (Asking for advice) [Suggestion] 

### ISSUE THREAD

**Issue by SebboSL** [TeamTwilight/twilightforest#1944]
### The Suggestion

I've been working on a modpack to use on a private server with 5-10 people where everyone would be having their own individual journeys and I've been wondering is it any way possible to balance this mod for multiple independent players? I know there's a progression system that locks people out unless you do things with a party, is there any way to avoid that? Are there other bosses of the same to locate after they've been defeated or maybe you can respawn them? I would really like to have this mod on a server just wondering if it's possible to make it work for everyone, would really appreciate any tips!

### Why Should It Be in the Mod?

hlep

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
There's a boss every 1024 blocks, basically infinite assuming there's no world border

**Comment by SebboSL** [comment]
Thank you
