### ISSUE TITLE
Hedge Unsynced Damage?

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1946]
### Forge Version

47.2.0

### Twilight Forest Version

4.3.1893

### Steps to Reproduce

Mine at a hedge
Take some damage
Completely normal
Mine at hedge for a little while
Take no damage
Weird but okay makes sense
Mine at hedge again for a little while
Suddenly damaged twice
What the fuck just happened

### What You Expected

Hedge Damage is wacky. It's sometimes delayed too?

### What Happened Instead

https://github.com/TeamTwilight/twilightforest/assets/144502047/d9ccda63-7841-4fd6-b786-88ebc9d8f281

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
sort of intended? The block schedules a tick 10 ticks after the hedge recognizes its been damaged (1/2 a second). I do think theres a better way of handling this but its not a bug
