### ISSUE TITLE
Banister Lighting go brrr

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1947]
### Forge Version

20.4.0-beta

### Twilight Forest Version

4.4.1989 

### Steps to Reproduce

Place banisters facing outwards at X, place a solid block at point O (slabs and stairs dont affect it)
Something like XOX, where theres a small gap between X and O.
Lighting bug :)

### What You Expected

Proper rendering with the blocks in between
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/da804af7-c94e-4af6-88a3-b165392be1c1)

### What Happened Instead

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/b9113ffe-915f-4987-8c22-3c5909182178)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this isn't something I can fix in TF, its just a quirk with vanilla's lighting engine. Setting `experimentalForgeLightPipelineEnabled` to true in (neo)forge's client config will fix the issue
