### ISSUE TITLE
Root Strands Offset By One Pixel

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#195]
Forge version: 14.23.0.2491
Twilight Forest version: 2.4.0.89

Steps to reproduce:
1. Place or find a Root Strands block in the world.
2. See it float under the block or clip down into one under it.

What I expected to happen:
Proper alignment.

What happened instead:
https://i.imgur.com/8zh6J4C.png

**Comment by Drullkus** [comment]
🤦‍♂️ how'd this revert....

**Comment by Drullkus** [comment]
self: investigate Plant Crop model, see if it's shifted down by 1 voxel
