### ISSUE TITLE
Cartography Table & TF Maps 

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1950]
### The Suggestion

Vanilla has a mechanic where if you put a map (even purchased maps) into a cartography table with a blank map, it will make a duplicate copy of said map. I would imagine doing similar with TF maps would be a nice addition,

### Why Should It Be in the Mod?

Filled maps can't be uncrafted (Vanilla & TF Maps), so there wouldn't be any real gain from it if you were to use a blank map. I guess if that is ever an issue, you could always make it so that (example) a filled ore map needs a blank ore map in order to make the 2 copies. 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
You can already duplicate our maps in a normal crafting table (the way vanilla does) but I can look into adding the functionality to the table assuming they don't hardcode it

**Comment by GizmoTheMoonPig** [comment]
forgot I looked into this a while ago, the behavior is hardcoded to hell and back and would require quite a bit of ASM to get working. Honestly I dont see it as worth it for such a small feature

**Comment by AriaElidove** [comment]
If this cartography changes to become data driven, I'll reopen this o7
