### ISSUE TITLE
Trapped Chests

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1951]
### The Suggestion

Add the new Trapped Chest variants to the requirements for Arborist.

### Why Should It Be in the Mod?

They're an additional version of the normal chest, and seeing as chest boats variants were added into the advancement when introduced, this wouldn't be too out of nowhere.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Oops
