### ISSUE TITLE
Magic Map doesn't render/disconnects players

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#1953]
### Forge Version

20.4.45-beta

### Twilight Forest Version

i dont fecking know, 2008

### Steps to Reproduce

Create a Filled Magic Map

### What You Expected

map

### What Happened Instead

On single player worlds, the Filled Magic Map won't render as a map, only the item.
Multiplayer worlds, the player will be disconnected and unable to rejoin.

### Additional Details

Taken from the error logs, the cause is in the `update` method of MagicMapItem: 
`Caused by: java.lang.ExceptionInInitializerError
    at twilightforest.item.MagicMapItem.update(MagicMapItem.java:181) ~[twilightforest-1.20.4-4.4.2005-universal.jar%23128!/:4.4.2005] {re:classloading}`

Further into the error, the cause is a sided issue:
`Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER`

I can't find when this started, can only assume it happened during the 1.20.4 port but I can't find any sort of culprit. Packet rewrite issue?

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by LeoBeliik** [comment]
~~This still happens in 1.20.1 - 4.3.2145, was this only fixed in 1.20.2 - 4.4.1977?~~

Never mind wrong Issue, my problem is #1928 sorry
