### ISSUE TITLE
grass will not spawn

### ISSUE THREAD

**Issue by BrendenPeery** [TeamTwilight/twilightforest#1959]
### Forge Version

20.2.86

### Twilight Forest Version

MC 1.20.2 - 4.4.1977

### Client Log

<script src="https://gist.github.com/BrendenPeery/2c360534649e6ca6771eb2c5942eb755.js"></script>

### Steps to Reproduce

Download the version of the game on curforge in a new profile, and create a new world and log on to that new world, I made the world in creative, but my sister on a different computer using the same process created a survival world, and it did the same thing

### What You Expected

I expected grass/flowers/ any foliage to be on the ground

![2023-12-24_20 16 46](https://github.com/TeamTwilight/twilightforest/assets/101530907/413cfd81-a9d4-4808-a081-89ccc1c61a54)

### What Happened Instead

I got grassless, and flowerless ground everywere. I think there was no deadbush or any foliage of the sort on the ground.

![2023-12-24_20 14 26](https://github.com/TeamTwilight/twilightforest/assets/101530907/b6c24f23-1de7-49fd-b1d5-2ad2ce56ea6a)

### Additional Details

 When i tried to bonemeal the ground, it showed the particles, but no grass or flowers spawned. I fixed the issue by going into the options folder in the game folder that curseforge made for the modpack, and creating a option called "grass_disable:false". that made the grass spawn in a new world, but the old world stayed the same as before the option.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
This is a bug with NeoForge, that was later fixed: https://github.com/neoforged/NeoForge/pull/372
