### ISSUE TITLE
Several Trophy Pedestal Bugs

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#196]
Forge version: 14.23.0.2491
Twilight Forest version: 2.4.0.89

Steps to reproduce:
1. When a chunk with a activated Trophy Pedestal unloads, when coming back to it said pedestal will have reverted into its unactivated state.
2.When mined it gives off Soul Sand breaking particles. 
3. The Trophy Pedestal can be moved by pistons, potentially breaking the forcefield deactivation of the stronghold below.

What I expected to happen:
1. The Trophy Pedestal to be unmovable with pistons.
2. For it to have retained its previous state.
3. Something more similar to smooth stone breaking particles.

**Comment by Drullkus** [comment]
Fixed in e0a2e31

**Comment by Drullkus** [comment]
If the Trophy Pedestal isn't Latent, then it can be broken and moved with pistons.
