### ISSUE TITLE
Can't break block in twilightforest

### ISSUE THREAD

**Issue by sheng-ri** [TeamTwilight/twilightforest#1960]
### Forge Version

20.4.58-beta/20.4.60-beta

### Twilight Forest Version

4.4.2021

**these version are development builds**

### Client Log

https://gist.github.com/sheng-ri/0d3dc27511e6db18c39ed056460c1073

### Steps to Reproduce

don't know what needs to be done
I just Play 1.20.4-4.4.2015 for a while
Then update it to  1.20.4-4.4.2021

### What You Expected

I can break block

### What Happened Instead

I can't break any block

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Busybody64** [comment]
I'm having this problem. I thought it was a modpack problem, until I saw this issue.

Even after the naga dies, I STILL can't break anything.

**Comment by Andromander** [comment]
This bug report is for a version not even publicly released yet. You might be experiencing a different issue.

**Comment by Busybody64** [comment]
Oh lol.

**Comment by jodlodi** [comment]
Due to changes to hollow hills, on the newer version, your world is broken.
Sorry :(
