### ISSUE TITLE
Spike block causing ticking entity crash

### ISSUE THREAD

**Issue by GothCartel** [TeamTwilight/twilightforest#1961]
### Forge Version

47.2.0

### Twilight Forest Version

4.3.1893

### Crash Report (if applicable)

https://gist.github.com/GothCartel/7e3b7cff49cf5a7f67c8de262d534df2

### Steps to Reproduce

Progressing through the knight dungeon, the mobs with the spiked ball either cause crash on death when using their weapon or possibly when interacting with another mob as its difficult to ascertain what the precise action causing it is. Either way the spike ball itself becomes a ticking entity and closes server.

### What You Expected

I expected it not to crash repeatedly. Bit obvious really but there you have it

### What Happened Instead

Server went into tick longer than 60 seconds and closes

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this is caused by cotw (curse of the warden) doing unsafe casts on entities instead of properly checking the entity. Please report this to them

**Comment by GothCartel** [comment]
Intriguing. I will pass it on, just wondered how it was just this one entity that its occurring with, server has been running for weeks fine with many other mob mods not having this conflict. May I ask precisely what the issue is with this one entity case so I can pass on the relevant information.

Regards
Goth_Cartel

**Comment by Drullkus** [comment]
Just reference Gizmo's message earlier. It's a really straightforward crash
