### ISSUE TITLE
Block and Chain bricks world

### ISSUE THREAD

**Issue by GearsawStudios** [TeamTwilight/twilightforest#1963]
### Forge Version

45.2.0

### Twilight Forest Version

4.2.1696

### Client Log

Sadly, none could be found. 

### Crash Report (if applicable)

https://gist.github.com/GearsawStudios/7233387fcd990525be38ac063994f2a1

### Steps to Reproduce

1. Start digging with Block and Chain with Destruction 1
2. Notice the Block and Chain is off center
3. Digging horizontally at bedrock level bricks game

### What You Expected

I can dig and my block and chain aims correctly

### What Happened Instead

My game crashes 1-7 frames into the game

### Additional Details

I am currently using the Explorer's Eve mod pack, which contains several performance enhancing mods. 
Crash log is from a random retry since the first crash report wasn't saved due to me thinking it was a one time thing.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this issue is unique and has not been reported already.

**Comment by GearsawStudios** [comment]
Solved by setting kill @e[type=twilightforest:chain_block] to run every tick.

**Comment by GizmoTheMoonPig** [comment]
this was fixed in 1.20.1, so it shouldnt be an issue in newer versions
