### ISSUE TITLE
Anti-Builder Maybe Bug?

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1964]
### Forge Version

47.2.16

### Twilight Forest Version

4.3.1893

### Steps to Reproduce

Find Dark Tower with an Anti-Builder Maze
Break a fence
Block gets replaced (as intended)
Break that block and quickly place a new fence (Or skip step 2 and 3)
Anti-Builder doesn't care

Note: It has to be in the spot the fence was originally

### What You Expected

Expected the new placed fence to be replaced.

### What Happened Instead

New fence is not replaced

### Additional Details

This also happens with other blocks when you replace them with their original block. 

I'm pretty sure this is WAI, but I do find it a bit odd tho...

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
I would argue this is intended, the anti builder has a snapshot of what the original world looked like and if you break and replace with whats already in that snapshot, it will leave it alone
