### ISSUE TITLE
Blocks refuse to break.

### ISSUE THREAD

**Issue by Busybody64** [TeamTwilight/twilightforest#1965]
### Forge Version

47.2.19

### Twilight Forest Version

4.3.1893

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

Just try to break a block in the titular forest of twilight.

### What You Expected

The block.... uh, breaks.

### What Happened Instead

Doesn't even get past the first part of the breaking animation, even with the right tools or after the naga's death. (Then again, I cheesed the fight with a bow and arrow from a distance.)

### Additional Details

Twilight forest is part of a GIANT (500 Mod) modpack. (I'd need to make a zip file at this point.)
Umbral skies, Twilight's Delight, and Twilight Forest; The Lost Blocks are also installed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
I assume you meant the Twilight Forest and NOT Titular Forest, lol. 

We will need a bit more information though: What blocks are you attempting to break, and where exactly were you when attempting? From what you described, it seems that you are at the post Naga point of progression, and but testing it on your version of MC and TF doesn't seem to break anything that was intended. 

If possible, may you send a modlist so I can better experiment and test your issue?

**Comment by Busybody64** [comment]
Basically, NONE of the blocks are breaking. Not even ONE.

**Comment by Busybody64** [comment]
It'd have to be the entire multiMC instance. Would that be fine?

**Comment by Busybody64** [comment]
Actually, Never mind, the glitch fixed itself after a restart. Perhaps I could still post the MultiMC instance too, to check for other incompatibilities? After all, I know Mo' Zombies wave is spawning their zombie variants in the titular twilight forest.
