### ISSUE TITLE
portal generation and usage on low coordinates

### ISSUE THREAD

**Issue by protoplanetary-disco** [TeamTwilight/twilightforest#1968]
### Forge Version

47.2.6

### Twilight Forest Version

4.3.1893

### Steps to Reproduce

(((I already structured all information in a post on the discord and got asked to open a github-ticket for this. I don't want to rewrite everything for this formula. [Here](https://discord.com/channels/313006291012288521/373298308178771978/1196118118255316992) and pasted as the text below is the report.)))

"Hi, i think i found a bug.
It's about making/using portals in and out of the twilight forest on low coordinates.

Here's what happened:
I created a twilight forest portal in our base in the overworld near spawn (77 -53 -57). I jumped into it and came out at roughly (500 7 -400). I jumped back in the portal that was generated in the twilight forest. I spawned in the overworld at the same coordinates, but without any portal and suffocating in rocks.
I did this again a few times and it's pretty consistent. I also travelled to the coordinates of our base in the twilight forest and made a portal there. It didn't connect to the initial portal in the overworld and also didn't generate a portal but just spawned me in our base-cave.
I also tried breaking and rebuilding the portal. It didn't change anything.

So i did some testing.

What i found out:
1. Creating portals at normal y levels in the overworld works just fine. They connect properly.
2. If you create portals at low y levels near bedrock the portal coordinates in the twilight forest will multiply somehow.
3. If you use this generated portal in the twilight forest to go back to the overworld it doesn't connect to the initial portal. Instead it gives 0 fucks and just kicks you out at the same (miltiplied) coordinates in the overworld. It doesn't generate a new portal and it doesn't cares about you spawning in solid blocks or in mid air.
If your funny you can then dig down again and build your next portal to multiply your coordinates again.
Like this:
[create portal] overworld: (-300 -60 300) (jump in)
[generated portal] twilight forest: (-2510 27 2589) (jump in)
[spawn without portal] overworld: (-2510 27 2589)
[create new portal] overworld: (-2510 -60 2589) (jump in)
[generated portal] twilight forest: (-20043 6 20731) (jump in)
[spawn without portal] overworld: (-20043 6 20731)
[create new portal] overworld: (-20043 -60 20731) (jump in)
[generated portal] twilight forest: (-160436 6 165847) (wtf)
... ... ... 3 created portals later ... ...
[generated portal] twilight forest: (-29999959 7 29999882) (worldborder)

Yes, you can actually travel to the worldborder with this within a few minutes and only 6 portals.

Additional info:
We played in a curseforge modpack named CreateABurger. It's for 1.20.1. Later we additionally installed Twilight Forest along with some other mods like Aether. So it's possible that it's a mod-incompatibility. But i think it's more then that as quite a few people complain about similar things in this channel.
I hopes this helps somehow."

### What You Expected

...

### What Happened Instead

...

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
Replicated in 4.3.2145, with extra bonus of getting exact same coords in the Twilight Forest after warping in from the Overworld (y=50) and falling into the Void!

**Comment by AriaElidove** [comment]
Confirmed again in lastest release (4.4.2235). See: https://www.youtube.com/watch?v=Zlh49KvPcuI
