### ISSUE TITLE
Glass Sword Advancement (One Hit Wonder)

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#1969]
### The Suggestion

Update the advancement so the requirement is for the Glass Sword to be USED, not for it to become broken. 

### Why Should It Be in the Mod?

I think for a vanilla playthrough of Twilight Forest, those who get a Glass Sword will likely put Unbreaking III onto the sword, and having it need to break seems like a hastle if you're attempt to get both the advancement and showcase the sword. When other mods get involved, Forbidden and Arcanus for example, the sword can become near indestructible easily using the Eternal Stella or higher levels of Unbreaking. 

It wouldn't hurt too much to change here since normally it is only a 1 and done, and those who put more effort into maxing this sword out should have some benifit to gain out of it (The advancement IS called "One Hit Wonder", not "Oops, I broke it!").

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Toastr125** [comment]
You can just get another glass sword to break though, it's not like you only ever get one. Besides, if you make it able to withstand multiple hits then it's not exactly a *one hit* wonder anymore, so in that sense the name makes more sense for breaking it.
