### ISSUE TITLE
Explosive Entrance to the Lich Tower

### ISSUE THREAD

**Issue by Divineaspect** [TeamTwilight/twilightforest#197]
Forge version: 8.0.99.99
Twilight Forest version: 2.4.0.91
Link to crash log: Not a crash.

Steps to reproduce:
1. Put tnt next to a lich tower and apply redstone signal.

What I expected to happen: That the protection would prevent me from exploding my way in.

What happened instead: I blew a big hole in the side.

**Comment by Sonicwave** [comment]
This also applies to the Dark Tower (for towerwood, not the mechanism blocks), perhaps the blast resistance of Towerwood could be boosted in general. The progression system also doesn't stop you from placing blocks, but disallows you from breaking the blocks that you placed.

**Comment by Benimatic** [comment]
It's not really fixable with the current system. Progression is per-player, not per-structure, and changing that would, IMO, make the whole system less intuitive.

And, I never considered this too serious. Even if you can gain access to the structure (which for many structures you can anyways) you can't do anything important in them (kill mobs, open chests) while the protection is up.
