### ISSUE TITLE
jp lang file issue

### ISSUE THREAD

**Issue by UANote** [TeamTwilight/twilightforest#1972]
Japanese language file is not applied.
I checked where the problem is in the file, but I couldn't find it.

**Comment by Andromander** [comment]
All language files are applied no different to vanilla, just change them in the Language. If they are not applying, it may mean there are entries that are not translated yet and won't apply, or an external issue - there might be an error in the log indicating why.

If the issue persists, try with Twilight Forest alone and change the language.

**Comment by Tamaized** [comment]
There was a missing comma in the file, it's been fixed in the current source code
