### ISSUE TITLE
Flying books paper attack goes through mekasuit

### ISSUE THREAD

**Issue by Acat1234** [TeamTwilight/twilightforest#1973]
### Forge Version

47.2.19

### Twilight Forest Version

4.3.1893

### Steps to Reproduce

1. Beat the naga
2. go to the lich tower
3. use full mekasuit
4. get hit by paper
5. take damage

### What You Expected

To lose energy not health

### What Happened Instead

no energy loss but I lose health

### Additional Details

Using full mekasuit fully blocks most damage types and cant block things like void /kill and stuff like that

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
I don't know specifically how that mod works, but Death Tome projectiles deal magic damage, which generally bypasses armour. It would have to depend on if they specifically code against magic damage or not, which I can't verify.

**Comment by Acat1234** [comment]
I have the module that blocks magic damage

**Comment by jodlodi** [comment]
should be resolved in #[d7ac353](https://github.com/TeamTwilight/twilightforest/commit/d7ac35312b439d6df5f69057907055b46b388e85)

if it still does not work, the creator of the mod you're talking about is not utilizing the correct damage type tags
