### ISSUE TITLE
ForgeHooks issue on Creative ModeTab Build Contents

### ISSUE THREAD

**Issue by XGI223** [TeamTwilight/twilightforest#1974]
### Forge Version

47.1.47

### Twilight Forest Version

4.3.189

### Client Log

https://gist.github.com/XGI223/b5e59e857c03bbfbc49a02ae6f5530b0

### Crash Report (if applicable)

https://gist.github.com/XGI223/fac54a7812a0376d5b1efde52f036b78

### Steps to Reproduce

1. go intocreative mode.
2. try to go to invintory
3. crash

### What You Expected

open the creative invintory.

### What Happened Instead

crash

### Additional Details

I think it has something to do with stack count of one or many of the item id in the mod but not too sure.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
somebody is either adding stacked contents to our creative tab or modifying stack sizes of our stuff. This doesnt happen with just TF, so its not really our issue
