### ISSUE TITLE
Portal Not Working :/

### ISSUE THREAD

**Issue by cherriekae** [TeamTwilight/twilightforest#1975]
### Forge Version

47.2.0

### Twilight Forest Version

4.3.1860

### Steps to Reproduce

1. making portal
2. following all steps
3. finished making portal
4. nothing happened

### What You Expected

I expected the portal model to transform into the Twilight Forest portal.

### What Happened Instead

Nothing changed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by cherriekae** [comment]
I also installed the mod through the CurseForge app, maybe that's why it's not working? There's other mods on there yet all of the items in the Twilight Forest mod are in the inventory library.

**Comment by cherriekae** [comment]
hello?

**Comment by AriaElidove** [comment]
Need more information. Mod list, if possible, would be preferred here.

**Comment by GizmoTheMoonPig** [comment]
closing due to lack of information and the fact theres been no response for a long time
