### ISSUE TITLE
[Suggestion] Do not loop over entire structure registry every mob spawn attempt

### ISSUE THREAD

**Issue by TelepathicGrunt** [TeamTwilight/twilightforest#1976]
### The Suggestion

This seems inefficient and will perform increasingly worse the larger the pack is as more and more structures are added to the registry.
https://github.com/TeamTwilight/twilightforest/blob/98e0f858ec72ca2adc64dc85518c80afebdc2d8f/src/main/java/twilightforest/world/components/chunkgenerators/ChunkGeneratorTwilight.java#L841

### Why Should It Be in the Mod?

The solution would be to either cache the structures that you're interested in from the registry or use a structure tag to collect your structure together and then grab the entries of the tag when needed instead of looping the whole registry. Example:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/8b65df28e4ef45a0a2918b0cf93485921218299b/common/src/main/java/com/telepathicgrunt/repurposedstructures/mixins/features/NoVinesInStructuresMixin.java#L41

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
There's a cache

**Comment by TelepathicGrunt** [comment]
Hmm I miss read the code. Does the cache bust on world exit and re-entering?

**Comment by Tamaized** [comment]
It's a WeakHashMap
