### ISSUE TITLE
[Suggestion] Fix vanilla-like mob models

### ISSUE THREAD

**Issue by cccarrrottt** [TeamTwilight/twilightforest#1978]
### The Suggestion

As far as I understood, TF reuses some vanilla models. It causes conflict when, for example, Fresh Animations that change default sheep's wool model, also changes the one fom the mod, resulting in some definetly incorrect results. How about duplicating them into the mod itself, so models can be changed independently from vanilla?

### Why Should It Be in the Mod?

Just to make mod a little more customizable with CEM resourcepacks.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
I'd rather not duplicate existing vanilla code

**Comment by cccarrrottt** [comment]
I'm completely incompetent in modding, so there may be more reasonable methods, i guess 😅😅

**Comment by Killer-Demon** [comment]
This is not something we're wanting to do as it'll make porting the mod more work in the long run.
