### ISSUE TITLE
Yeti Cave Generation bug

### ISSUE THREAD

**Issue by foonley21268** [TeamTwilight/twilightforest#1980]
### Forge Version

20.4.146

### Twilight Forest Version

4.4.2147

### Steps to Reproduce

Find a yeti cave

### What You Expected

Yeti Cave structure to generate with snow blocks only

### What Happened Instead

Yeti Cave structure generated with snow blocks and dirt blocks

### Additional Details

![2024-02-01_22 27 28](https://github.com/TeamTwilight/twilightforest/assets/158525340/7ec52021-2761-422e-9f2c-142e57523790)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
Adding to this, there is also a bug regarding other caves carving into parts of the cave. Not sure if these two issues are related or not, so if needed I can open a separate issue.

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/c94eb4ea-9932-4f4c-9adb-3ee3bf693203)

**Comment by AriaElidove** [comment]
Bump (v4.5.2348)

Also, they can generate too close to a twilight stream:
Seed: 3219846238290517736
Cords: -8929 40 -9627
 
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/c902b641-277c-4bf2-9c69-033e5576ef7c)

**Comment by jodlodi** [comment]
While it was different for quite some time on release builds, this is actually the way its intended to be
