### ISSUE TITLE
Giant House Floor Height

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#1982]
### Forge Version

20.4147-beta

### Twilight Forest Version

4.4.2147

### Steps to Reproduce

Walk up to the Giant house.

### What You Expected

The floor to be flush.

### What Happened Instead

The floor inside the house can have the height variance of the rest of the cloud, making it so the giants sometimes can't leave the house.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Killer-Demon** [comment]
Forgot the coordinates.
x:1240 z:3333
Seed: -7535851884589983802

**Comment by Drullkus** [comment]
Fixed via 8456549f39f72d064d7e16e4a7acd385eafd5480
