### ISSUE TITLE
Giant Leaves are Solid Blocks

### ISSUE THREAD

**Issue by Bumper3241** [TeamTwilight/twilightforest#1988]
### NeoForge Version

47.2.20

### Twilight Forest Version

4.3.2145

### Steps to Reproduce

Place down a Giant Leaf Block

### What You Expected

Not to Suffocate

### What Happened Instead

Suffocated. Oh also, it blocks out sunlight.

### Additional Details

I was told in the Discord server that this didn't sound intentional and to report it here

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by PraseodymiumSpike** [comment]
I wonder if they should be Waterloggable with a Giant Water Bucket.
