### ISSUE TITLE
No loot in the boss Chest

### ISSUE THREAD

**Issue by Yannatash** [TeamTwilight/twilightforest#1989]
### NeoForge Version

47.2.0

### Twilight Forest Version

4.3.1735

### Steps to Reproduce

1. I fought and won against the Naga 2 times) and the litch (once)
2. The chest spawned
3. the chest were empty

### What You Expected

I thought that the loots would either spawn at the corpse of the boss or in the chest

### What Happened Instead

The chest was empty

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
You're using a very old version, can you try with [4.3.1893](https://legacy.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/4865711)?

**Comment by GizmoTheMoonPig** [comment]
This was fixed in 4.3.1740, update the mod
