### ISSUE TITLE
Crash while exploring, may be crossmod with OTG, may be map needing an error check for unknown biomes

### ISSUE THREAD

**Issue by Divineaspect** [TeamTwilight/twilightforest#199]
Forge version: 8.0.99.99
Twilight Forest version: 2.4.0.91
Link to crash log: https://gist.github.com/Divineaspect/e49df9a606dab131e244746b95b81b2d

Steps to reproduce:
1. Explore Twilight Forest with OTG installed

What I expected to happen: I would eventually find a naga courtyard looking at all the icons on the map.

What happened instead: this crash whenever I look at the map.

**Comment by Tamaized** [comment]
Hmm, wouldn't this actually be on their end? Shouldn't they be extending the class instance they replace?
We can still do an instanceof check and just not call the `BiomeForest#addDoublePlants` if it fails but it still seems pretty silly.

**Comment by 0uti** [comment]
https://github.com/PG85/OpenTerrainGenerator/issues/76

**Comment by Alaberti** [comment]
Question: Is this being worked on here or there?

**Comment by williewillus** [comment]
We can add a workaround

**Comment by Alaberti** [comment]
Thank you!
