### ISSUE TITLE
Twilight forest magic maps crash player on render when Map atlases is installed 

### ISSUE THREAD

**Issue by LeoBeliik** [TeamTwilight/twilightforest#1990]
### NeoForge Version

Forge 47.2.0

### Twilight Forest Version

Twilight Forest 1.20.1 - 4.3.2145

### Crash Report (if applicable)

Crashlog https://mclo.gs/Sblwed2

### Steps to Reproduce

craft a magic map
hold it

### What You Expected

not being kick out of the server

### What Happened Instead

get kick out of the server

### Additional Details

Map Atlases 1.20 - 2.7.18

Crafting a magic map and holding it in hand will perma kick the player out of the server, **this only happens** when map atlases is installed.

also reported to map atlases: https://github.com/MehVahdJukaar/mapatlases-neoforge/issues/93

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
see #1928
