### ISSUE TITLE
[Suggestion] Naga Scale Crossbow

### ISSUE THREAD

**Issue by PraseodymiumSpike** [TeamTwilight/twilightforest#1991]
### The Suggestion

The Naga Scale Crossbow would be similar to a vanilla Crossbow, but when you shoot with a Naga Scale Crossbow, if there is a loaded Naga Scale Crossbow anywhere in your Inventory (not in a Bundle or Shulker Box) except for in your Hotbar, the loaded one will go into your hand, replacing the one you just shot with, and the one you just shot with will go into your Inventory. So you can fill your inventory with loaded Naga Scale Crossbows, and you can have just 1 in your Hotbar, and when you shoot with it, a loaded one from your inventory will pop into your hand, and then you can shoot that one, and another loaded one will pop into your hand, and so on until your inventory is filled with unloaded Naga Scale Crossbows.

This wouldn't be that overpowered because you'd need to load all of them again after. Also, you'd need to kill a lot of Nagas for this. The Naga Scale would take the place of the Tripwire Hook in the Crossbow Recipe. If this is too easy, perhaps, the String in the Crossbow Recipe would need to be replaced with Red Thread, too, or the Iron Ingot with a Fiery Ingot. Requiring a Fiery Ingot might make it too hard to get, though, so maybe, that could be a stronger version that shoots flaming Arrows like a Flame Bow. There are many directions you can go with this.

### Why Should It Be in the Mod?

It's pretty easy to kill Nagas, and they're fairly common, so you can end up with a lot of Naga Scales. And they're not that useful after you have better armor. So this is something to do with them that would be useful. The same goes for Red Thread if you decide to go with that. Also, the Naga Scale Crossbow is a lateral upgrade. It's not objectively better than a Bow Enchanted with Power V for example; it's good in a different way. I think that's cool.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This is currently not something we're looking to add. We're always open to expand on loot from bosses (and structures!) so maybe something like it will appear in some form at some point.
