### ISSUE TITLE
Chain goblin crash

### ISSUE THREAD

**Issue by mxnmnm** [TeamTwilight/twilightforest#1992]
### NeoForge Version

47.1.100

### Twilight Forest Version

4.3.2145

### Client Log

https://gist.github.com/mxnmnm/66951d2c00ca24232695471315db201b

### Crash Report (if applicable)

https://gist.github.com/mxnmnm/a5553c7469a3c72d631b70e5ae45b9ce

### Steps to Reproduce

1. Spawn chain goblin using commands or spawn egg
2. Crash

### What You Expected

No crash

### What Happened Instead

Crash

### Additional Details

This is caused by another mod but I'm not sure which one. If you need me to find the specific one (aka the crash/log wasn't enough info) then let me know.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by mxnmnm** [comment]
I have found the culprit mod so here's a cleaner crash report: https://gist.github.com/mxnmnm/38289b55da4c0cffd81b4f61e49dd020

**Comment by mxnmnm** [comment]
This is unlikely to be this mod's fault as reverting the other mod's version fixed the issue

**Comment by Sazuzaki** [comment]
Can you tell what mod was the culprit? I'm experiencing this myself.

**Comment by GizmoTheMoonPig** [comment]
if you have `Bad Optimizations` installed thatll be your issue, if not send a crash report and I can take a look

**Comment by Sazuzaki** [comment]
Gotcha, reverting BO to ver 1.6.3 (or 5.14.0 if you're using cursed forge) fixes the issue. Thank you very much!

**Comment by mxnmnm** [comment]
there is a config option you can change with the newer versions that crash that should fix it
