### ISSUE TITLE
[Suggestion] Boats with Twilight Forest wood

### ISSUE THREAD

**Issue by Jatie1** [TeamTwilight/twilightforest#1995]
### The Suggestion

I noticed in E9E (uses latest Twilight Forest 4.2.1518 for MC 1.19.2) I can't make a boat from Twilight Oak Planks:
![image](https://github.com/TeamTwilight/twilightforest/assets/70575943/9f175ca5-6e69-4400-9387-46e5036436fb)

Suggestion is to add this type of boat and any other Twilight woods that don't have a related boat. If you don't want extra boats, just make the recipe create a regular oak boat.

### Why Should It Be in the Mod?

Consistency with any other type of wood.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Andromander** [comment]
As a matter of fact, Boats and Chest Boats have been implemented, but only for 1.19.3 and above.
