### ISSUE TITLE
Ability to adjust sea level

### ISSUE THREAD

**Issue by UndeadZeratul** [TeamTwilight/twilightforest#2]
The current world generation is set up so that the "sea level" of the dimension is set to 32, which was done so that the world would have more space for its massive trees.  This was back when the world was limited to 128 blocks and so the world was split 25:75 rather than the 50:50 split of vanilla.

Now that the world can hold up to 256 blocks of height, it'd be nice to see more space given to the features generated underground.  With double the head room, doubling the sea level back to 64 should allow for more underground features while still keeping the 25:75 split.

Obviously not everyone will want this to change, and so I would propose a config setting to adjust the height at which the world generates.  That way it's left up to the server owner or pack developer to configure their environment the way they want it.

**Comment by Drullkus** [comment]
Naturally shipped with 1.17 now
