### ISSUE TITLE
Lich killed by tamed animals doesnt give advancement or unlock swamp

### ISSUE THREAD

**Issue by Divineaspect** [TeamTwilight/twilightforest#200]
Forge version: 8.0.99.99
Twilight Forest version: 2.4.0.91
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Tame Wolves
2. Fight lich, letting wolves get the final hit

What I expected to happen: Having the scepter would be enough

What happened instead: continue to be hungered from the swamp.

**Comment by williewillus** [comment]
it's a vanilla bug, wolves don't count as a player kill in the loot tables, which drops the item that gives the advancement

**Comment by Divineaspect** [comment]
Well is there a reason to make this seperate from the sceptre, considering that automatic machines can't get past stage 1 of the fight anyway?

**Comment by Drullkus** [comment]
Issue indirectly fixed by 07ccac5 which fixes #164
