### ISSUE TITLE
Boss Trophy on Noteblock

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2002]
### The Suggestion

Similar to mob heads on noteblocks making the respective mobs' sound, adding the boss trophies to that to produce those bosses sounds (similar to right clicking them). It could also produce the boss's respective particles, such as the snowflakes from the snow queen. This would allow for player created particles if paired well with redstone set ups :)

### Why Should It Be in the Mod?

It'd be neat c:

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
vanilla's noteblock instrument system isn't extensible, so adding custom sounds like that isn't really doable. You can also already make the trophies play sounds by powering them, so I don't see a reason to bother with it
