### ISSUE TITLE
Red thread doesn't render with Embeddium

### ISSUE THREAD

**Issue by Blugori** [TeamTwilight/twilightforest#2004]
### NeoForge Version

Forge 47.2.20

### Twilight Forest Version

4.3.2145

### Steps to Reproduce

Install Embeddium (0.3.4+), and the Complementary Unbound 5.1.1shader.
Run the game, place a red thread behind a wall.

### What You Expected

I expected the red thread behind the wall to render while holding one in my hand.

### What Happened Instead

The red thread didn't render.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
This is a shader mod problem, unfortunately not fixable due to how old yet widespread OF's Shader system is.

Embeddium, in isolation, was just tested by me and is confirmed working
