### ISSUE TITLE
Uncrafting Table cant craft shrouded gear

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2009]
### NeoForge Version

20.4.200

### Twilight Forest Version

4.4.2235

### Steps to Reproduce

Try crafting an armour piece with an emporer's cloth in the uncrafting table. You cant! D:

### What You Expected

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/7a9671b6-cb69-42c6-b438-7fb05a8f8f22)
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/605e14f7-a2c2-4969-ba87-5f62460fde12)

### What Happened Instead

damn this table cant craft shit rn

### Additional Details

screams in el salvadorian spanish

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
currently the uncrafting table doesnt support any special recipes when crafting. You cant use it to craft banners onto a shield for example. i'll have to look into this one a bit further
