### ISSUE TITLE
Crashing in 1.20.1 

### ISSUE THREAD

**Issue by vnsmnn** [TeamTwilight/twilightforest#2012]
### NeoForge Version

47.2.20

### Twilight Forest Version

4.3.2145

### Crash Report (if applicable)

https://gist.github.com/vnsmnn/4476f3863e088546eecb50e589aa2e31

### Steps to Reproduce

1. Go to Twilight Forest or Spawn Naga
2. Immediately Crash after encountering Naga

### What You Expected

Not Crash

### What Happened Instead

Game Crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This is a problem with the `bad optimizations` mod

**Comment by vnsmnn** [comment]
Hi appreciate the fast response. I removed the Bad optimization mod and it doesnt crash anymore. Thank you so much!

**Comment by imthosea** [comment]
Rather than removing it you should be able to simply disable the config option here: https://github.com/ItsThosea/BadOptimizations/issues/42

...I should really make it force-disable if you have twilight forest. I'll do that next update.
