### ISSUE TITLE
Not checking for safe blocks around portal

### ISSUE THREAD

**Issue by Intresting09** [TeamTwilight/twilightforest#2014]
### NeoForge Version

47.2.20

### Twilight Forest Version

4.3.2145

### Steps to Reproduce

build a portal. then build a 2 tall, 2 thick wall along the north edge of the portal replacing the flowers. go throught he portal, then return. 

### What You Expected

to be blaced on a side of the portal that is not currently occupied by a wall; remaining in the overworld

### What Happened Instead

you spawn inside the north wall and get pushed back into the portal.

### Additional Details

i tested this on a multiplayer ATM9 server. i would test on singleplayer but my computer cannot handle a singleplayer atm9 world and im lazy :)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
amended in commit 130b8eb8235bed4772f061af095e4b4a6d49f374

while it does not prevent you from being pushed back into the portal, it does prevent you from being teleported once that happens
