### ISSUE TITLE
Twilight forest wont let Minecraft launch, freezes during loading screen

### ISSUE THREAD

**Issue by WillAlmond** [TeamTwilight/twilightforest#2015]
### NeoForge Version

42.2.0

### Twilight Forest Version

4.3.2145

### Client Log

https://gist.github.com/WillAlmond/ee3f664849e83958f028eb771b72b8bb#file-gistfile1-txt

### Steps to Reproduce

1.Download Twilight forest for Minecraft 1.20.1
2. Add mod File to Minecraft mod folder
3. Run Forge mod lauder client to run Minecraft
4. Loading screen freezes, unable to launch game

### What You Expected

Minecraft to launch and run properly.

### What Happened Instead

Minecraft freezes at the loading screen, unable to make it to main menu.

### Additional Details

Problem occurs whether Twilight forest is the only mod in the Minecraft mod folder or is included with X number of mods. Problem has been tested with 5-6 versions of twilight forest for Minecraft 1.20.1 and persists. Problem resolves itself when twilight forest is not in the folder, X number of other mods still work properly and cause no issues.

When testing it in the Forge folder to launch a server, it launches with no errors and shows the server is online.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
`[01Apr2024 17:10:51.819] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Out of memory`

You ran out of ram
