### ISSUE TITLE
Conflicts with Ars Nouveau mod

### ISSUE THREAD

**Issue by rjdxxxxxccc** [TeamTwilight/twilightforest#2018]
### NeoForge Version

47.2.21

### Twilight Forest Version

4.3.2145

### Steps to Reproduce

Waiting for one minute to use the magic book will exit the game

### What You Expected

The game continues

### What Happened Instead

Game continues to exit

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
No crash report, no client log, the reproduction steps indicate that the game does exit, but no log was provided to indicate why. Please provide a client log and/or a crash report for better troubleshooting.
