### ISSUE TITLE
Description: Unexpected error

### ISSUE THREAD

**Issue by OniVision** [TeamTwilight/twilightforest#2021]
### NeoForge Version

47.2

### Twilight Forest Version

1.20.1-4.3.2145-universal

### Crash Report (if applicable)

https://gist.github.com/OniVision/1ff57a62e5ebbee240b23a77ace7392f#file-gistfile1-txt

### Steps to Reproduce

Started the server and tried to connect.

### What You Expected

A possible conflict with biome ID's?

### What Happened Instead

Total system crash.

### Please Read and Confirm The Following

- [ ] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Make sure the TF version is the exact same on both the client, and the sever

**Comment by GizmoTheMoonPig** [comment]
closing due to lack of response. Do what jodi said and check that the versions on the client and server match each other, this error only happens when they dont match
