### ISSUE TITLE
rare random Crafting Issue

### ISSUE THREAD

**Issue by MSandro** [TeamTwilight/twilightforest#2022]
### NeoForge Version

20.4.225

### Twilight Forest Version

4.4.2235

### Steps to Reproduce

It's hard to reproduce. When I enter a world it happens about 1 in 30 times that the crafting outputs are messed up. So recipes without input are loaded.

I don't necessarily just want to blame Twilight Forest for this, sometimes an item from another mod comes out, e.g. Modern Industrialization or Blue Skies.
I've been running different mod combinations dozens of times for hours. Load worlds at least 5-10 times each time only to notice that the error occurs again.
I hope someone can help me find out what the problem is. I will also report this bug to the other affected mods.

### What You Expected

The recipes shouldn't get so mixed up.

### What Happened Instead

It doesn't matter what I put into the crafting grid, something from Twilight Forest always comes out.

### Additional Details

![image](https://github.com/TeamTwilight/twilightforest/assets/10937159/22eb0d7b-6e1d-40b3-a88e-0f6f46b7660b)
![image](https://github.com/TeamTwilight/twilightforest/assets/10937159/969131f6-3f50-4c8c-848b-04764e30749f)
![image](https://github.com/TeamTwilight/twilightforest/assets/10937159/dc91b4b3-f5ae-4ce3-8a1f-f17bfcf87a2f)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
What in the world

**Comment by MSandro** [comment]
![image](https://github.com/TeamTwilight/twilightforest/assets/10937159/d2f7ba5f-7539-4f2d-b441-6eaaae465142)

After re-joining or reloading (without any changes, no DataPack, etc.):
![image](https://github.com/TeamTwilight/twilightforest/assets/10937159/e6e9bb7b-5331-4090-b878-c050995ccd5f)


It is the same ID, but something gets messed up randomly.

**Comment by MSandro** [comment]
https://github.com/AztechMC/Modern-Industrialization/issues/694

**Comment by GizmoTheMoonPig** [comment]
gonna say this isnt our fault since neo apparently fixed it already
