### ISSUE TITLE
You Are Unworthy

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2029]
### NeoForge Version

20.4.200

### Twilight Forest Version

4.4.2271

### Steps to Reproduce

Be in creative mode
Place Trophy Pedestal + Trophy
"You are unworthy"
Cry

### What You Expected

Expected the Trophy Pedestal to activate due to there being no restrictions on anything else while in creative (ie, breaking blocks in structures that are beyond a certain point in progression).

### What Happened Instead

I was simply not worthy. 

### Additional Details

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/ab095c21-e757-4f6e-a509-b8cf127e90c9)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Creative doesn't bypass criterions

**Comment by AriaElidove** [comment]
Creative bypasses being able to harm mobs and break blocks in restricted structures, so this seemed like an odd, one off thing. I figure to mention it.
