### ISSUE TITLE
Missing textures with ressouce pack with custom models

### ISSUE THREAD

**Issue by LiderKonmils** [TeamTwilight/twilightforest#2031]
### NeoForge Version

47.1.104

### Twilight Forest Version

4.3.2145

### Steps to Reproduce

1.Install Twilight forest and every required dependencies
2.install a ressource pack that change the "model" of the leaves (exemple: DokuCraft)
3.Watch the leaves

### What You Expected

Normal leaves

### What Happened Instead

Missing textures

### Additional Details

/!\FIRST THING, I FOUND A TEMPORARY FIX AND SAW THAT THE PROBLEM REMAINS IN THE LAST VERSION EVEN IF I DON'T USE THE LAST ONE/!\

I found that in the files of the mod, leaves of Twilight oak, canopy tree, mangrove and rainbow oak are using vanilla texture from assets/minecraft/textures/block. I'v tried to add the textures in minecraft/textures/block in another resource pack, but nothing was repaired. The only fix that i found (that i think that should be basic in the pack) is going to assets/twilightforest/models/block and changing the "textures: all: minecraft:block/[wood]_leaves" by "textures: all: twilightforest:/block/[wood]_leaves" for all four leaves files and manually adding the [wood]_leaves files to assets/twilightforest/textures/blocks.

BEFORE FIX
![2024-04-23_12 34 56](https://github.com/TeamTwilight/twilightforest/assets/1256145/6dbf04df-2584-4a9d-8b32-f167c89ef1fe)
AFTER FIX
![2024-04-23_12 45 19](https://github.com/TeamTwilight/twilightforest/assets/1256145/6c4e5274-ebd8-43c7-b67c-ce9652724968)

BEFORE FIX
![Twilightforest 2](https://github.com/TeamTwilight/twilightforest/assets/1256145/338d6ff0-7764-4cdc-af2c-050a6685fa88)
AFTER FIX
![Twilightforest 1](https://github.com/TeamTwilight/twilightforest/assets/1256145/0368baf4-d73c-4b23-a984-cf0a3de78777)
![Twilightforest 3](https://github.com/TeamTwilight/twilightforest/assets/1256145/58291231-d3c8-44ed-9513-33c75e75cfd6)

What i'm asking for, is stoping to use the vanilla files for any blocks and adding them directly in the twilightforest folder. Like that, any ressource pack that use custom models should'nt (in theory) break textures anymore.

Also, if you agree to use this temporary fix as a final fix, it could also be great to fix the 1.20.1 version, since i' pretty sure a lot of people like me will downgrade to it since it's the last version where Forge and NeoForge are still compatible 
(that's the only reason i'm not in 1.20.4... anymore).

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Redistributing vanilla textures in our jar file is a huge no no. There's legal issues with that.

**Comment by LiderKonmils** [comment]
In that case can you create new texture for thoses leaves instead of using vanilla one?

**Comment by LiderKonmils** [comment]
Or modify the vanilla one enough to avoid thoses legal issues?

**Comment by Tamaized** [comment]
No that's not how copyright works.

**Comment by Tamaized** [comment]
If we want to use vanilla textures we should be allowed to. If it breaks with another mod/resourcepack then that's the entire point of additional resource packs to begin with, to fix these types of issues.

**Comment by AriaElidove** [comment]
I cannot reproduce this bug, so I don't know how you broke it. Either way, it's not TF at fault. 

Using "Clarity 1.20" Resource Pack, Forge 47.2.0, and TF 4.3.2145 : 
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/7a914bf5-6769-45af-9af8-99251374b550)

**Comment by LiderKonmils** [comment]
Try with DokuCraft High
