### ISSUE TITLE
Update Player Block & Chain Animation

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2032]
### The Suggestion

Change the player's animation for the Block & Chain to mimic that of the Goblin. It'd make it more interesting then it just being thrown out like a Fishing Rod. As an additional feature, it could "charge" the distance it can travel as you swing it around your head longer and longer, being more similar to how the Bow works.

### Why Should It Be in the Mod?

Just something neat to add. No real reason otherwise besides animation consistency

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
Adding poses to player models is very difficult

**Comment by Tamaized** [comment]
I've been corrected, apparently Forge added an api for this at some point around 1.19

**Comment by lwh2333** [comment]
> 我已经得到了纠正，显然 Forge 在 1.19 左右的某个时候为此添加了一个 api

which api?

**Comment by lwh2333** [comment]
> I've been corrected, apparently Forge added an api for this at some point around 1.19

which api?
