### ISSUE TITLE
Additional/New Trapped Chest Recipes

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2034]
### The Suggestion

TF Chest + Tripwire Hook = TF Trapped Chest

### Why Should It Be in the Mod?

Adds a recipe that reflects the Vanilla recipe.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
this isnt gonna work as it causes conflicts with the vanilla chest recipe. The recipes used to be like this but I had to change them because of that exact reason

**Comment by AriaElidove** [comment]
Unlucky
