### ISSUE TITLE
Fiery/Yeti Armor Refuse Books

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2040]
### NeoForge Version

20.4.233

### Twilight Forest Version

4.4.2235

### Steps to Reproduce

Get book with both some form of Protection and Thorns on it
Try to combine with armor to get the Protection off of the book.
Fail and cry

### What You Expected

Expected the armor to recieve the Protection enchantment and ignore the Thorns enchantment

### What Happened Instead

Anvil refuses.

### Additional Details

I found this originally in 1.19.4, so I guess it's been a bug for a hot minute :<

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Sleepy-Horse** [comment]
Did I try to reproduce the bug correctly?
![2024-05-02_19 15 48](https://github.com/TeamTwilight/twilightforest/assets/97367938/85101a00-8f83-4efc-b87b-7ea2d0b0e6c9)

**Comment by AriaElidove** [comment]
That looks correct, yup.

**Comment by Sleepy-Horse** [comment]
I believe it was fixed in the 1.20.x branch. I think you can close the issue

**Comment by AriaElidove** [comment]
Opened up a new bug.

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/54a2e4d1-3aa2-4570-bf08-10354f61175d)

**Comment by AriaElidove** [comment]
v1.20.6-4.5.2325

**Comment by AriaElidove** [comment]
v1.20.5-4.5.2321
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/a1c6d9fe-0db3-4c3b-a0eb-c4b66ebb3a8f)

**Comment by jodlodi** [comment]
whats the difference

**Comment by AriaElidove** [comment]
Fire React shouldn't be on Yeti Armor. The restrictions are currently broken.

**Comment by Tamaized** [comment]
Try in survival, creative mode lets you put any enchant on anything in an anvil.

**Comment by jodlodi** [comment]
no, I mean between the screenshots

**Comment by AriaElidove** [comment]
Versions. Wanted to check whether or not a recent update broke something to direct to it.

**Comment by GizmoTheMoonPig** [comment]
.5 and .6 are identical, you dont need to check between those 2

**Comment by Tamaized** [comment]
https://bugs.mojang.com/browse/MC-95555

**Comment by AriaElidove** [comment]
Chill Aura and Fiery React works in survival btw, but Thorns seems to still be restricted.

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/fd8b6f4d-1d1f-4ed3-8d1a-252a94eaf19c)

**Comment by AriaElidove** [comment]
Initial bug is fixed with Thorns. Yippee!

**Comment by AriaElidove** [comment]
Seems like it's been broken since the 1.20.5 port. Either that, or 1.20.4, which I'd hafta go into dev builds later to figure out when exactly it broke.... Guh

**Comment by AriaElidove** [comment]
Latest 1.20.4 build (2277) is perfectly regarding above. Guess it was a porting issue.
