### ISSUE TITLE
Aurora Shader: Skybox Colour

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2048]
### The Suggestion

If set via the client config to a new biome, the shader should share the same skybox as the Glacier.

### Why Should It Be in the Mod?

This should be added because it'll show the shader much nicer in the respectively added biomes (ie, Snowy Forest looks bad when the shader is applied into it, and should have it's skybox overrided).

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
Biome sky colors is controlled by the biome json. Use a datapack.
