### ISSUE TITLE
Dark Tower: Unreachable Balcony

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2049]
### NeoForge Version

20.6.18

### Twilight Forest Version

4.5.2348

### Steps to Reproduce

On rare occassions, the first floor of a Dark Tower can generate with a "disattached" balcony. 

### What You Expected

This balcony simply should never exist on the first floor.

### What Happened Instead

Balcony exists.

### Additional Details

Seed: 3219846238290517736
Cords: -9703, 5, -10009

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/c13c7f5e-9463-4d2b-b922-f5a1710b1693)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
I dont personally see this as an issue but i'll leave it open in case anyone wants to change it
