### ISSUE TITLE
Uncrafting Table: Recipe Book UI

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2050]
### NeoForge Version

20.6.18

### Twilight Forest Version

4.5.2348

### Steps to Reproduce

Select something in the Recipe Book to craft (Don't have the items in inventory)
Shift-Click the Item you want to uncraft

### What You Expected

If an item is in the Uncrafting Slot of the Uncrafting Table, there should not be a Crafting Output unless there are items actively in the Crafting Grid.

### What Happened Instead

The Uncrafting Recipe will show correctly, but the Recipe Book's pushed recipe does not get removed.

### Additional Details

This does NOT happen if you drag and drop the desired Uncrafted Item into the Uncrafting Slot, only if you Shift-Click...

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/68c0effe-d258-42a3-b423-a7151e660591)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
vanilla has this same issue in the crafting table so im gonna say this isnt our fault (mostly because I dont want to copy a bunch of vanilla code to fix it)
