### ISSUE TITLE
Uberous Soil: Select Blocks Do Not Transform

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2051]
### NeoForge Version

20.6.18

### Twilight Forest Version

4.5.2348

### Steps to Reproduce

Put Uberous Soil on top of any block that should be changed into a different block when one is above it (Nylium, Mycelium, Grass), and the lower block will not turn into the type it should be (Dirt or Netherrack, in this case)

### What You Expected

Uberous Soil to "decompose" the block below it

### What Happened Instead

The block below did not change.

### Additional Details

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/74f7423e-ffa5-4c9b-ba85-4d402e02994f)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
topsoil blocks dont decay immediately when a block is placed above them, theyll decay on random ticks. If they dont decay at all regardless, do they do it when farmland is placed above them? If not theres nothing we can do about it

**Comment by AriaElidove** [comment]
They decay both Farmland and Grass Paths, but not the ones mentioned above.

Also, oddly Podzol just never decays? Wonder if that's intended or a vanilla bug.

**Comment by GizmoTheMoonPig** [comment]
yeah I kinda figured those would decay, but I was asking what happens if you place grass or mycelium below vanilla farmland instead of uberous soil. Both blocks have the same exact shape so I would expect the behavior to be the same between them

**Comment by AriaElidove** [comment]
These all decay under Farmland.
