### ISSUE TITLE
Slider: Movement Logic

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2052]
### NeoForge Version

20.6.18

### Twilight Forest Version

4.5.2348

### Steps to Reproduce

Place down a Slider
It spins and travels
On it's way back, it just goes NYOOM

### What You Expected

Slider should have a certain bound on it's travel distance, center to it's initial placement and mimicing it's initial movement

### What Happened Instead

The Slider just said "Aight I'm out of here"

### Additional Details

The Slider can also go into the void???

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This is a heavily WIP block/entity

**Comment by AriaElidove** [comment]
This video applies for both #2052 & #2053 

https://github.com/TeamTwilight/twilightforest/assets/144502047/fa29158e-e980-4907-b0ad-bfdb89661ead

**Comment by GizmoTheMoonPig** [comment]
Things in the mod marked as WIP or NYI should not have tickets opened for them tbh. This block especially is in dire need of a complete rewrite but Im not gonna do that until we actually find somewhere to implement it

**Comment by AriaElidove** [comment]
I figured this wouldn't be changed any time soon, but I figure that these should be mentioned on a ticket as requested.
