### ISSUE TITLE
Slider: Block State

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2053]
### NeoForge Version

20.6.18

### Twilight Forest Version

4.5.2348

### Steps to Reproduce

Place Slider Horizontally (To move up/down)

### What You Expected

Slider to be sideways when spinning

### What Happened Instead

Slider sat up

### Additional Details

Probably just a blockstate issue from port. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Again, this is a heavily WIP block/entity. Issues like these are to be expected.

**Comment by GizmoTheMoonPig** [comment]
see #2052
