### ISSUE TITLE
Alpha Yeti: Locked Fight Transitions

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2054]
### NeoForge Version

20.6.18

### Twilight Forest Version

4.5.2348

### Steps to Reproduce

Find Yeti Cave
Make sure this section of progression is locked
Enter Yeti Cave
Attempt to attack the Alpha Yeti
It will not do damage (Intended), but the Alpha Yeti will still assume damage
Alpha Yeti will do it's flail and sit phases (Not Intended)

### What You Expected

Alpha Yeti doesn't care about the player swatting at it until the player beats the Lich

### What Happened Instead

Yeti Cries

### Additional Details

There likely isn't much that can be done here, but I feel like the check for if the Alpha Yeti should change phases should be based on if it takes more than 1 hp of damage (As you are doing 0 if it is locked, this makes sense).

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
I think this is fine honestly.

**Comment by AriaElidove** [comment]
Oh god, I found a different issue while trying how the check works lmfao.
