### ISSUE TITLE
NBT Checks for Uncrafting Recipes

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2060]
### The Suggestion

Crafting Recipes can use NBT data for specific recipes, like the Scepter variants, so I think it would be cool to have these checks for Uncrafting Recipes.

### Why Should It Be in the Mod?

Benefits data/modpack creators by giving them the ability to have multiple uncrafts based on NBT.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
as of 1.20.5 itemstacks now use components, not nbt
