### ISSUE TITLE
Ore Meter Radius Reset

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2062]
### NeoForge Version

20.4.233

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

Change Chunk Range on the Ore Meter
Calculate Ores within said Range
Reset the Ore Meter's values
The Range gets reset

### What You Expected

Range shouldn't get reset and should only be changed by the player's input.

### What Happened Instead

Range was reset when attempting to clear information.

### Additional Details

I'm so sorry Gizmo

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Sleepy-Horse** [comment]
I couldn't reproduce it on the latest version from github.

**Comment by AriaElidove** [comment]
I don't know what happened, but seeing as it fixed itself, I will close the issue.

**Comment by Tamaized** [comment]
Generally, it's not wise to report issues for versions not released on curseforge. Things WILL be broken while we port. That is normal and ***expected***

Things resolve themself as the port goes on.

**Comment by AriaElidove** [comment]
v4.4.2276 is the latest release Tama...

**Comment by Tamaized** [comment]
The 'release from github' comment made me think otherwise :stuck_out_tongue: 

But we have been getting issues lately from in dev versions from various people.

**Comment by AriaElidove** [comment]
All good 👍
