### ISSUE TITLE
Brewing with Potion Flasks (NYI)

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2065]
### The Suggestion

Allow Potion Flasks to be used with brewing. A flask filled with Awkward Potions could be brewed into a flask full of Strength Potions, or a flask filled with Instant Health Potions could be upgraded to Instant Health II Potions

![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/68e030eb-ba6c-46fc-b09f-d952cc8946ce)
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/4f6565b4-f060-4209-bd58-8a2066703287)

### Why Should It Be in the Mod?

Seeing as it is possible to add water and no-effect potions into a Potion Flask, it seems like it might be a nice idea. It could also save on resources required to make said potions (Using 1 blaze powder with 3 potion flasks would provide 12 doses of the strength effect!).

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
1 material for 12 potions instead of 3 is too much

**Comment by AriaElidove** [comment]
I agree that it's a bit much, but I'm doubtful that the brewing stand can limit it's input to only one flask at a time. Either way, some form of interaction between the flasks and brewing stand would be very cool :>

**Comment by Tamaized** [comment]
I don't agree
