### ISSUE TITLE
Tree in Undesired Locations

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2068]
### NeoForge Version

20.4.233

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

Li
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/95f79b47-ff95-4de7-9dc8-60c0430ddb4f)

### What You Expected

Tree not in water

### What Happened Instead

Tree is in water

### Additional Details

Likely a duplicate of #2058

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Improved via 0e24b7c
