### ISSUE TITLE
Cannot grow Darkwood Tree at a certain height

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#207]
Forge version: 14.23.0.2512
Twilight Forest version: Release 3.0.0
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Create a Superflat world (preferrably the preset given as default)
2. Plant a Darkwood Sapling on ground level
3. Spam Bonemeal

What I expected to happen:
Eventually a Darkwood Tree would grow

What happened instead:
The Darkwood Sapling seemingly cannot grow, despite repeated use of Bonemeal. Creating a platform around 30 blocks above the ground allows the tree to grow as normal

**Comment by Tamaized** [comment]
Sadly the tree is restricted to a min height of `TFWorld.SEALEVEL` because they can gen underground otherwise as you see here
![2017-10-22_14 03 28](https://user-images.githubusercontent.com/9671313/31866261-e79af164-b731-11e7-8632-c768d40b9bc6.png)

**Comment by GizmoTheMoonPig** [comment]
fixed now without them growing in caves
