### ISSUE TITLE
[Suggestion] Funni creative builder snake thing (length not duration)

### ISSUE THREAD

**Issue by Acat1234** [TeamTwilight/twilightforest#2074]
### The Suggestion

Add it so I can do funni spectator block snake

### Why Should It Be in the Mod?

Why not?

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
Just to clarify, are you suggesting for a custom screen effect when spectating as the Naga?

**Comment by Acat1234** [comment]
no

**Comment by Acat1234** [comment]
Like the block that when powered makes blocks in the direction you face (This block exists but it has a distance limit)

**Comment by AriaElidove** [comment]
It's called the Carminite Builder :>

**Comment by Acat1234** [comment]
Yes it is

**Comment by GizmoTheMoonPig** [comment]
not worth it in my eyes to do something like this

**Comment by Acat1234** [comment]
ok
