### ISSUE TITLE
Blocks Replaced by Timewood Branch Roots

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2076]
### NeoForge Version

20.6.70 / 20.4.233

### Twilight Forest Version

4.5.2372 / 4.42276

### Steps to Reproduce

Plant a tree of time ontop of an unbreakable block. 

### What You Expected

Unbreakable blocks shouldn't be broken by the tree's rooting branches

### What Happened Instead

Unbreakable block was broken

### Additional Details

Applies to the latest public release as well.

1.20.6:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/2856f8c6-8729-484a-ae18-bfd81ab30389)

1.20.4:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/9058ac38-d09a-407e-934b-30f804c9fb87)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Fixed properly in 004322a5734c07f05bcfb78b69799a0413bc1d9c
