### ISSUE TITLE
[1.12.2] Fullscreen Journeymap not working in twilight dimension

### ISSUE THREAD

**Issue by Thyriel** [TeamTwilight/twilightforest#208]
As title. When pressing J (Journeymap fullscreen) while in twilight forest dimension the client freezes like 3-5sec, but doesn't open the map. As this happens only in this dimension and others i added (like the beneath) work fine i guess it's a problem with the twilight forest.

Forge 14.23.0.2501
Journeymap 5.5.0rc1

**Comment by Saintares97** [comment]
I just reported this to JourneyMap as I do not have Twilight Forest installed yet and am experiencing this issue on dimensional travel. Same JourneyMap version but on different Forge version.

**Comment by ScytheIronclaw** [comment]
I too have been experiencing this issue, best to report it to Journeymap's dev as this is a bug with Journeymap. A workaround is to /gamemode 3 then go underground to switch to cave maps, then press J. This un-sticks it for awhile.

**Comment by Thyriel** [comment]
Just had the same in The End so definitly JM bug. Where did u even report it ? Their bitbucket site seems to be gone (access denied) and beside that i don't find any place to report it to them

**Comment by Killer-Demon** [comment]
Closing this issue since it wasn't a bug on our side.
