### ISSUE TITLE
Force Fields Shreds Mob AI

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2082]
### NeoForge Version

20.4.233

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

Spawn a zombie and a villager on top of force fields (I did it on the Final Castle's purple box)
Their movement goals are fried and stand still..for some reason
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/7cb8dec6-a1a6-47c1-9cb0-c0a564878183)

### What You Expected

Mob AI goals to function properly

### What Happened Instead

Mob AI goals break and causes them to stand still at time (Seemly random? I don't have a proper idea for it).

### Additional Details

This also works with the Vindicator & Villager interaction. Also tested on latest Dev.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
path finding is disabled for the block

**Comment by AriaElidove** [comment]
Is pathfinding not included with all mobs when they go after the player?

**Comment by AriaElidove** [comment]
Because I tested a Skeleton & Player interaction and it was able to move to me with zero issue.

**Comment by jodlodi** [comment]
mojank

**Comment by GizmoTheMoonPig** [comment]
skeleton strafing while shooting doesnt work like traditional mob pathing does. The goal just moves them in various directions with no care about what theyre standing on

**Comment by AriaElidove** [comment]
Okay, this makes sense then. If it's purely vanilla sided and unplanned to be changed, this can be closed.
