### ISSUE TITLE
Rope Lanterns

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2083]
### The Suggestion

Rope should be able to support lanterns under them, acting as a hangable block for them (when vertical, that is).

### Why Should It Be in the Mod?

Rope and Lanterns go hand in hand like bread and butter! Plus it could make for cool interactions with other mods. I remember in one mod that when lanterns fall after losing their support, they set a fire below them. Adding rope into that mix would make that so cool!

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Unfortunately I cant do this without making ropes solid blocks, which would kinda defeat the purpose of them. This is a vanilla limitation, nothing I can do
