### ISSUE TITLE
Twilight Scepter in Dispenser

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2084]
### NeoForge Version

20.4.233

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

Use Twilight Scepter in a dispenser until it stops being used
It's left at 1 use instead of 0 uses when it has the ability to still be used once more

### What You Expected

0/99 Uses for the Scepter

### What Happened Instead

1/99 Uses for the Scepter

### Additional Details

This might just be a "the dispenser will break the scepter if it's 0 durability" which would suck that it isn't getting it's full usage

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Sleepy-Horse** [comment]
Thank you for your report, I fixed it in [this pr](https://github.com/TeamTwilight/twilightforest/pull/2088). Could you close the issue, please?
@AriaElidove
