### ISSUE TITLE
[Suggestion] Add a new translation target for toki pona

### ISSUE THREAD

**Issue by torari-real-true** [TeamTwilight/twilightforest#2089]
### The Suggestion

This would not change any gameplay, just adding support for a language.

### Why Should It Be in the Mod?

This would benefit our community, and could also help people learn our language, it is very simple to add custom languages, and has already been done on other projects using crowdin.
Here is how you can add custom languages:
https://support.crowdin.com/changing-target-languages/#adding-custom-languages
Here is a post detailing adding toki pona support in crowdin:
https://github.com/mastodon/mastodon/issues/23372

### Please Read and Confirm the Following

- [x] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
support has been added on crowdin! Thanks for the suggestion!
