### ISSUE TITLE
Certain Damage Types Ignore Fortification Shields

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2095]
### NeoForge Version

20.4.233

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

As the title implies, the Fortification Shields do not protect against all damage types. I tested this with the Warden's Sonic Blast, but I imagine there are other types of damage that follow this logic. 

The Warden's Sonic Blast does break 1 shield on the Lich, so there is logic for the shields to block the damage, but not for the player?

### What You Expected

The Shields should protect the player when hit.

### What Happened Instead

The Shields do not protect the player.

### Additional Details

Tested in Dev as well:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/6cc91712-99a5-418f-8b41-73a024ca404a)

I've also noticed that the Lich takes MUCH less damage from the Warden's blast compared to a direct hit lol. Not sure if this is intended but it's still very funny

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This is intended, any type tagged as BYPASSES_ARMOR ignores shields
