### ISSUE TITLE
Crash when entering Twilight Forest Dimension

### ISSUE THREAD

**Issue by vos6434** [TeamTwilight/twilightforest#21]
I created a portal and when I entered it I crashed.
Twilight Forest: 2.4.0.4
Forge: 13.20.0.2315
Crash: https://pastebin.com/ezr4pK4x

**Comment by jambonmcyeah** [comment]
I crashed too: https://gist.github.com/jambonmcyeah/dad4448cb42b09c7352730f573146fd2

**Comment by ruairidh74** [comment]
I still crash after entering the portal.
Twilight Forest: 2.4.0.5
Forge: 13.20.0.2228
Crash report: 
[crash-2017-06-18_21.56.53-server.txt](https://github.com/TeamTwilight/twilightforest/files/1083378/crash-2017-06-18_21.56.53-server.txt)
