### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by chickeness** [TeamTwilight/twilightforest#2100]
### The Suggestion

After beating the Naga, you could become open for various raids on you by low-level dungeon mobs. Defeating the Naga would open you to raids by Liches consisting of the typical enemies in Lich Towers- Zombies, Skeletons, Spiders, maybe some death tomes, and perhaps even a 'raid captain' consisting of the special zombies summoned by the Lich when using its Zombie Scepter. Beating the Lich would open you to raids consisting of goblins and helmet crabs, minotaurs, and possibly a couple yetis coming to eat your livestock.
The dark tower themed raid could see a couple ghastguards drift over to you, the rest of the mobs there have logistical issues in getting out of the dark forest. The Snow Queen raid would be similar to the Lich raid, seeing her servants of Snow Guardians and Ice Crystals attempt to attack you. I can't think of anything for the hydra, given it is a single big mob. 
Given the progression ends here that's it. There's also opportunities to have non-boss raids- such as mist and winter wolf raids, king spider jockey raids, or any number of combination of mobs, such as a large horde of kobolds.
The 'raid captains' could potentially drop some good mid-tier loot to incentivize players fighting them, with increasing quality and difficulty as the raids progress.
I don't know how the raids will target the player- they could suddenly appear in the area around the player, but I understand why that might be unwanted. They could target the chunks with the highest local difficulty, if the player is present- which would guarantee that if a player has a base, it is being attacked. If you don't build within the twilight forest, then none of this would apply, unfortunately. 

### Why Should It Be in the Mod?

As to why I think this should be in the mod, the Twilight Forest, currently, feels very stagnant. You are the only actor in the world, despite there being several other humans serving as bosses, and having dominion over small parts of the world, even if it is mostly magical influence. Despite several bosses commanding legions of their own, and other boss structures inhabited by tribes of goblins and minotaurs, they don't do anything with their power. This would really liven the world up, making it seem as if the player has wandered into the middle of a twisting web of alliances- and also experience raids themselves by the inhabitants of the dungeons they plan to raid.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
What is bro cooking
