### ISSUE TITLE
Better Reappearing Blocks

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2101]
### The Suggestion

Make it so reappearing block variants do not begin reappearing until all have finished disappearing. The block variants include the default ones and the castle doors.

### Why Should It Be in the Mod?

It makes them feel clunky on larger scale doors. 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
This isn't really possible without creating a graph network system. Which is way too complicated than for what it's worth.

**Comment by GizmoTheMoonPig** [comment]
as tama said, the blocks would need a whole new system to get them to do this, and im not nearly smart enough to figure that one out. I personally think the way they work currently is fine and doesnt really need to be changed
