### ISSUE TITLE
no trees or grass or basic features anywhere in the twilight forest

### ISSUE THREAD

**Issue by safron1111** [TeamTwilight/twilightforest#2102]
### NeoForge Version

not neoforge but forge, 36.2.34

### Twilight Forest Version

twilightforest-1.16.5-4.0.870-universal.jar

### Client Log

https://gist.github.com/safron1111/9dae68b0d865d01866568da193627152

### Crash Report (if applicable)

https://gist.github.com/safron1111/a719801db1f34f911586b978c81fbe93

### Steps to Reproduce

open forge profile with twilight forest
1.16.5
make portal
go in portal
no trees or grass or anything except terrain and structures?

### What You Expected

there is meant to be trees, and other decorators and features

### What Happened Instead

every tree in every biome never generated, along with many decorators and features, structures generate fine though

### Additional Details

image of no trees
![image](https://github.com/TeamTwilight/twilightforest/assets/170552380/2658739e-5706-4dfa-8977-f114ec535de8)

the mods im using with twilight forest:
'Dustrial Decor
Advanced Explosives!
AdventureKraft
Alex's Delight
Alex's Mobs
Ambient Sounds 6
Appleskin
Architectury API
Blueprint
Chunk Loaders
Citadel
Cloth Config API
CobbleForDays
CoFH Core
Collective
Comforts
Cooking for Blockheads
Create
Create Chunkloading
Create Crafts & Additions
CreativeCore
Cucumber Library
Curios API
Decorative Blocks
Decorative Blocks modded compat
Drip Sounds
Easy Piglins
Easy Villagers
Farmer's Delight
Farmer's Respite
Farming for Blockheads
Fast Leaf Decay
FerriteCore
Flood
Flywheel
Iron Chests
Iron Furnaces
Iron Jetpacks
JourneyMap
JEI
JER
L_Ender's Cataclysm
Lucky TNT Mod
Mantle
Mekanism
Mekanism Generators
Mekanism Tools
ModernFix
Moonlight Lib
Mouse Tweaks
Nether's Delight
All of Pam's Harvest Craft 2
Patchouli
Physics Mod
Plant Producer
Productive Bees
ProjectE
ProjectE Integration
Realistic Explosion Physics
Redstone Arsenal
Redstone Pen
Refined Pipes
Refined Storage
Refined Storage Addons
Refined Storage: Requestify
Security Craft
Serene Seasons
Serene Seasons - Pam's Harvest Craft 2: Crops Compat
Serene Seasons - Pam's Harvest Craft 2: Trees Compat
SKDS Core
Spartan Shields
Spartan Weaponry
Spice of Life: Carrot Edition
Spice of Life: Potato Edition
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
Supplementaries
The One Probe
The Twilight Forest (Duh)
The Undergarden
All Official Thermal Mods
Tinker's Construct
Tool's Complement
Tree Harvester
PhysEx/Water Physics Overhaul
Weather Settings

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
1.16 is no longer supported.

IIRC this issue is caused by a different mod. I don't remember which.
