### ISSUE TITLE
[DEV] [Compat] New Chiseled Canopy Bookshelf Compat Ideas

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2105]
### The Suggestion

Allow for the player to see the type of mob is currently set in the Chiseled Canopy Bookshelf.

Chiseled Canopy Bookshelf:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/5bf94623-0e38-4a59-896b-1f866843c190)

Vanilla Spawners:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/43066321-bb86-4072-94d3-42899ddf9d60)

### Why Should It Be in the Mod?

Jade and TOP already do this with vanilla spawners. Extending this to the Chiseled Canopy Bookshelf would be a nice consistency.

This could also be added as a config option, with the type being hidden by default.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
I didnt do this intentionally as I didnt want people who have block viewers on to be able to tell which ones were spawners. If anything I might make the mob show only in creative

**Comment by AriaElidove** [comment]
In this case, having the information using the creative probe would be a good thought.
