### ISSUE TITLE
Block & Chain Blacklist

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2109]
### The Suggestion

Make a configurable blacklist/whitelist for blocks that the Block & Chain can NEVER break, regardless of the block's tool tier requirement and the destruction enchantment level

### Why Should It Be in the Mod?

This allows for modpack creatures to add or remove some more specific uses for the Block & Chain. For example, someone could make it so only pickaxe mineable blocks can be broken by the Block & Chain by blacklisting all other mineable tags. 

The whitelist is just suggested for parity with some of the configurations in the Uncrafting Table. I'm not sure if the whitelist here would work as an additive or a replacement, so that would be up to yall on how you plan on doing that

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
There's already a `mineable_with_block_and_chain` tag
