### ISSUE TITLE
Knightly Axe doesn't do extra damage.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#211]
Forge version: 14.23.0.2501
Twilight Forest version: 3.0.0 beta
Link to crash log: Not a crash.

Steps to reproduce:
1. Trying to use knighty weapons and tools.

What I expected to happen:All of them will do extra damage.

What happened instead:Except axe.

**Comment by williewillus** [comment]
cannot reproduce. the weapon damage balances *are* a little wacky right now, but the extra knightly damage does happen for all three of them. If you see enchant sparkles that means the extra damage applied
