### ISSUE TITLE
Hostile Wolves Don't Target Non-Player Mobs

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2111]
### NeoForge Version

20.6.83

### Twilight Forest Version

4.5.2348

### Steps to Reproduce

Summon a Hostile Wolf and Bighorn Sheep.

### What You Expected

Hostile Wolf targetting shouldn't be too far off of the vanilla's wolf, so it should target the selected mobs (Rabbits, Sheep, etc)

### What Happened Instead

They are the best of friends!

### Additional Details

Found in 1.20.1

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Seems to be intentional
https://github.com/TeamTwilight/twilightforest/commit/619ff554ee0a7ade034ecd4ba0d6c74e5f2abe43#diff-df9c96f0bac21e9a7de05df033f6b8354f12643d03d755082420f111ec74d52eL51-R46

@GizmoTheMoonPig
