### ISSUE TITLE
[DEV] Chiseled Canopy Bookshelf Fire Drops

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2112]
### NeoForge Version

20.6.78

### Twilight Forest Version

4.5.2348 / Dev

### Steps to Reproduce

Set the chiseled canopy shelf on fire while it is in a spawning state.

### What You Expected

The remaining books to become mobs that were set on fire. 

### What Happened Instead

It has only spawned upwards to 2 of it's mobs, with the remaining books being dropped.

### Additional Details

I am basing this as a bug based on Gizmo stating "When a shelf in the spawner state is deleted by fire, it will spew out all the remaining mobs on fire" in regards to the shelf's new functions. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
im pretty sure this happens because it tries to spawn each mob once, and if it doesnt find a good spot it fails the spawn. Im gonna need to look into forcing them to spawn regardless in this scenario
