### ISSUE TITLE
[DEV] Chiseled Canopy Bookshelf Spawning Particles

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2114]
### The Suggestion

Have particles generate where a newly spawned mob is placed. I was thinking to something similar to the Death Tome or Enchantment particles would be most appropriate.

### Why Should It Be in the Mod?

Just a visual tweak that could look nice. 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
The block is NYI and Gizzy plans to give it all the polish it deserves before it sees the light of day

**Comment by Tamaized** [comment]
This block is a bit more special, the spawning aspect is still a WIP, but the rest of the block is finished for current survival play (the decorative aspect)

We have our own plans for content that is not quite accessible in current vanilla TF survival.
