### ISSUE TITLE
[DEV] Mason Jars Deter / Attract Mobs

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2115]
### The Suggestion

If there is an item or block that would natively deter or attract a mob within a Mason Jar, create the interaction. Attractions should only be temporarily as to not permanently lock them to an interaction goal, as I'd imagine most mobs would realise that they can't get into the jar :P

Example: Piglins should be lured to a Mason Jar that has a golden item, and deterred from one that has a soul-fire light in it. 

### Why Should It Be in the Mod?

If there is a soul-fire light in a Mason Jar, it already produces the light level equivalent of a regularly placed down soul-fire light source, so adding to this with mob interactions doesn't seem too out of place. It could also lead to some interesting distractions for mobs.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Please dont make suggestions for blocks or items that arent even in the mod yet. If its not on the main branch, it doesnt exist yet. Same goes for WIP/NYI items as theyre always subject to change
