### ISSUE TITLE
The order of defense points of armors are wrong.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#212]
Forge version: 14.23.0.2501
Twilight Forest version: 3.0.0 beta
Link to crash log: Not a crash.

Steps to reproduce:
1. Checking defense points of armors.

What I expected to happen:Chestplate>leggings, helmet>boots.

What happened instead:Leggings>chestplate, boots>helmet.

**Comment by williewillus** [comment]
stupid 1.8 flipping the order of armor indices :P
