### ISSUE TITLE
[NYI/WIP] Candle Skulls Can't Be Dimmed

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2120]
### NeoForge Version

20.6.83

### Twilight Forest Version

4.5.2417

### Steps to Reproduce

Place Candle Skull, add candles, light it.
Try to make it dim using redstone (mimicing the Candelabra's feature)
Doesn't work

### What You Expected

Candle Skulls should have the Dim Lighting when right clicked with Redstone Dust

### What Happened Instead

Nothing happens; redstone dust gets placed on the ground instead of dimming the candle skull's light

### Additional Details

I tagged this as NYI/WIP with a question mark because I don't know how exactly the Candelabra's new flames are in terms of implimentation. The Dim Lighting option is available for the Candle Skulls when using a debug stick, so I'm wondering why it isn't available natively when that ability has already been fleshed out with the Candelabra. If it is unique to the Candelabra, why is it then available for the Candle Skulls?

Candelabra & Candle Skull with Dim Lighting (1.20.6):
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/1ad6f3bb-dcb9-4e38-b36d-e78c83e0b9f3)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
Not a bug, the blockstate is unobtainable in survival.
