### ISSUE TITLE
Rope Placement is Still Jank

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2124]
### NeoForge Version

20.6.116

### Twilight Forest Version

4.5.2448

### Steps to Reproduce

Was testing stuff on latest dev, and rope placement is messy once again. 

> Do the set up shown in the image at the bottom, as example to this (This occurs on all axis, but it's easiest to show with this one)
> Attempt to place a block on the top of the Darkwood Leaves to place a crossed vertical rope below the currently hung one
> Fail and cry about block state pain
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/208ee465-c02a-48d8-9695-008e7da45547)

### What You Expected

Attempting to place rope on a block that can have rope should place it; if there is issue on the axis, follow the axis the player is facing. You can extend rope placements by Right-Clicking underneath blocks that natively have rope, so this logic should apply to spots where the rope could be extended out to.

Also, intersections should know to place rope in the axis the player is facing, instead of placing along an axis the player isn't along. If the player is along the X axis, rope should not be extending out on the Z axis if the X axis is available for placements.

### What Happened Instead

Rope refuses to place this way UNLESS the rope itself (or the block directly behind/under it) is interacted with, which seems flawed.

### Additional Details

bro its too hot for me to be doing these bug reps, im going to bed

My reaction to rope placement logic:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/901e8971-abee-488c-b155-a32d382a9f82)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
https://github.com/TeamTwilight/twilightforest/assets/88628285/de4dc980-8208-4e2c-9754-7e8c693cf488

**Comment by jodlodi** [comment]
whats the problem, I dont get it

**Comment by jodlodi** [comment]
> whats the problem, I dont get it

I have since come to an understanding
