### ISSUE TITLE
[NYI/WIP] Candelabra & Candle Skull Adjustments

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2125]
### The Suggestion

Crouch Right-Clicking a Candelabra or Candle Skull while it has a Candle will remove it from the respective item. However, it is currently only able to be done with an empty hand. Having an off-hand item will simply prevent the player from picking up Candles from Candelabras and Candle Skulls. This should not be the case. 

Any time a candle is removed from a Candle Skull, add it to a stack instead of single, individual stacks. I have no idea why this is the way it is considering Candle Skulls can only have one Candle variant at any given moment.

Allow the player to remove Candles while holding their respective variant. If the player is removing a Green Candle with a Green Candle in hand, allow them to remove it without needing them to have an empty hand. In the case that a player has a Candle in their off-hand that matches the desired removeable Candle, add that Candle into the player's off-hand stack instead of an available inventory slot.

When in Creative Mode, if the player Crouch Right-Clicks a Candelabra to remove the Candle, it should return to the player's inventory if an instance of the specific Candle Variant is not in their inventory. In other words, if a Creative player attempts to remove a Green Candle and they do not have one in their inventory, add it to the inventory, if possible. Reflecting this, Candle Skulls should only provide the Candle if it is not in the inventory, where possible. If it is in their inventory, ignore the addition and remove it from the respective blocks. 

Branching away from Candle removal properties, add a dispenser usage for Candelabras that mimics the Candle Skulls' dispenser usage. Any time a dispenser with a candle inside of it is activated facing a Candelabra, add that Candle to the first available Candle slot, repeating until failure. The order can also be randomized or based on their placement in a dispenser. 

### Why Should It Be in the Mod?

General convenience to players is desireable.

Yes, the Candelabra is NYI/WIP; however, the logic between the two candle holders should be similar with some of their basic Candle placement functions. Adjusting how the Candles are removed on Candle Skulls should also be adjusted with the Candelabra, and likewise visa versa.

Also wow this could've just been several separate tickets.... oops

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
first point is not possible when crouching. This is a vanilla limitation, nothing we can do about it. 
third point is gonna lead to a lot of duplicate logic that I would prefer not to have for maintenance reasons. Candles will only be removable with an empty hand. This also cant be done for skull candles as they can hold up to 4 candles. 
the other 3 are done in 6430f72eb8143fa32ef80399543d4b0e1035cd51 and 4cdac303acfb73208325f7fbabbf14e4f27bb90c
