### ISSUE TITLE
Game crash when opening/creating a world with Yung's API and twilight forest installed

### ISSUE THREAD

**Issue by Jakoby1835** [TeamTwilight/twilightforest#2127]
### NeoForge Version

20.4.237

### Twilight Forest Version

4.4.2276

### Client Log

https://gist.github.com/Jakoby1835/7fb589d1fa0d8fa67f82f34c393e74d3

### Crash Report (if applicable)

https://gist.github.com/Jakoby1835/ed0c784205790e4b95410e3d506dbb26

### Steps to Reproduce

1. install yung's api and twilight forest in neo forge
2. launch the game
3. open / create a world

then get:
 `The game crashed whilst exception initializing level Error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectListIterator.hasNext()" because "customDensities" is null`

### What You Expected

that the world would load an not crash

### What Happened Instead

the game crashed

### Additional Details

I tried it with all 1.20.4 twilight builds and it happend with all of them. both mods run fine separately but when loaded together their produce this crash.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this has been fixed in future MC versions. Unfortunately we don't have a workable branch on 1.20.4 so going and getting this fixed is more hassle than it's worth. I would recommend removing either mod for now or updating to 1.20.6/1.21 (note, we haven't made a release for 1.21 yet but have playable dev builds over on our discord if you're interested)
