### ISSUE TITLE
Hollow Hill Spawners

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2128]
### NeoForge Version

20.4.235

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

Do you see the spawner??? Because I sure as hell dont!

Coords are given, seed is `-7651298011542360778`
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/d5beb635-e613-474d-9a47-67443f2df27c)

### What You Expected

Spawners should not be hidden behind the walls of Hollow Hills. 

### What Happened Instead

Spawners are hidden behind some walls

### Additional Details

I only experienced this once so far, so this will potentially need more testing. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
THERE ARE KOBOLDS IN MY WALLS (this part was a joke, please except this as an apology)

**Comment by Toastr125** [comment]
From my experience with looking around in spectator mode, spawners generate in the walls and floors of hills all the time. Chests too.

**Comment by AriaElidove** [comment]
Some can be visible in the ground/walls. Some are literally hidden behind stone. Fun!

**Comment by GizmoTheMoonPig** [comment]
intended. Not all spawners need to always be visible, and having them all show up all the time is probably close to impossible. It adds a little extra challenge to the hills too which im personally a fan of
