### ISSUE TITLE
E115 Statistic

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2129]
### NeoForge Version

20.4.233

### Twilight Forest Version

4.4.2276

### Steps to Reproduce

I don't know how to replicate it; All I know is that I've been eating E115 a lot (shows in the "Used" section of items stat), but it doesn't show many for general stats.

Item Stats:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/a46fbb54-cd4a-4587-bed5-041424994b17)

General Stats:
![image](https://github.com/TeamTwilight/twilightforest/assets/144502047/1a792d63-e786-4411-94a0-1bcff98e674b)

### What You Expected

If the Item Stat =/= General Stat, update the General Stat

### What Happened Instead

The two values are different.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
the used item stat also refers to things like placing the block, adding more to an existing block, and picking up slices, not just eating. Theres a reason I added a custom stat to track how many have been eaten. The general stat will show you how many you have truly eaten
