### ISSUE TITLE
The defnse points of yeti boots and yeti helmet is wrong.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#213]
Forge version: 2501
Twilight Forest version: 3.0.0.121
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Checking armors.

What I expected to happen:Yeti boots' defense points=3 and yeti helmet's defense points=4.

What happened instead:The order is still wrong.

**Comment by williewillus** [comment]
wrong according to what? If it wouldn't be too much of a hassle if you could just go to 1.7 and gather all the values for everything that would be great :P

**Comment by AppDat** [comment]
In 1.7.10, the yeti helmet has 4 defense pointsand the yeti boots has 3.
