### ISSUE TITLE
More Transformation Powder Uses

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2133]
### The Suggestion

Carminite Golem <---> Iron Golem
This one seems pretty self explanatory, and I'm surprised hasn't been set already.

Stable Ice Core <---> Snow Golem
Both shoot snowballs at their targets :)

Squirrel <---> Fox
Both are very skiddish and run away from the player.

It might also be neat to add a chance for variation. For example, a Spider could transform into either a Hedge Spider or a Carminite Broodling at a random chance!

### Why Should It Be in the Mod?

It's been sometime since Transformation Powder got some love. Let's give it some :)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
These aren't variations we're currently looking to add to the powder's repertoir for one reason or another.
