### ISSUE TITLE
[Bug] Dark Forest progression not correctly updating upon defeating the Twilight Lich

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#2138]
### NeoForge Version

1.20.6

### Twilight Forest Version

twilightforest-1.20.6-4.5.2490-universal

### Steps to Reproduce

1. Defeat the Naga, then the Twilight Lich
2. Head to the Dark Forest

### What You Expected

Progression is correctly updated

### What Happened Instead

Progression acts as if the Lich has not been defeated

### Additional Details
The progression is being incorrectly updated after clearing the first advancement of a respective area (for example opening the seal on the Knight Phantom Stronghold), rather than when the Lich is defeated.

![2024-06-20_21 55 48](https://github.com/TeamTwilight/twilightforest/assets/62183036/9a24d97e-cb5a-4a69-b949-a19c6f1a22d9)
![2024-06-20_21 56 44](https://github.com/TeamTwilight/twilightforest/assets/62183036/934ad939-c8ae-4186-a40f-8ff7b2379d52)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
This should just be a visual glitch rather than a gameplay bug. It will go away when a trophy is placed on a pedestal in the Goblin Knight Stronghold.

**Comment by SeaOfPixels** [comment]
It's a bug regardless of if it's just visual or not, it's extremely obtrusive.
