### ISSUE TITLE
[Magic Map] - Add Multiplayer Inclusion to the Conquered System

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2139]
### The Suggestion

Add an alternate icon to the Magic Map to indicate a different player other than the user has cleared a location/structure.

### Why Should It Be in the Mod?

Currently, there is no means to figure out if you have gone to a certain structure or if another player has due to the X's being the same globally. This suggestion will allow any players that haven't already been to the structure gain remaining or additional loot, which can be made extremely useful for mods such as Lootr.   

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
While it could offer some amount of help, this would be an absolute nightmare to implement and isn't something we'd want to do because of that.
