### ISSUE TITLE
The game may stuck when the lighting from the portal hits a horse.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#214]
Forge version: 2501
Twilight Forest version: 3.0.0.121
Link to crash log: ?

Steps to reproduce:
1. Creating a twilight forest portal.

What I expected to happen:Nothing.

What happened instead:The lighting hit a horse, then the game got stuck. When I close the game, the game didn't respond.

**Comment by williewillus** [comment]
log?

**Comment by Tamaized** [comment]
I believe this is just the horse entity entering the portal resulting in initial dimension generation lag on the server thread, explains why he cant do anything as it's stuck trying to finish the gen.
