### ISSUE TITLE
[Suggestion] Wild Deer should be able to eat apples

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#2140]
### The Suggestion

In real life, deer are known to eat apples, quite often, and it's odd that it's not on Twilight Forest Deer

### Why Should It Be in the Mod?

It could add more variety to Wild Deer and give them a unique distinction from cows

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
added in #2149
