### ISSUE TITLE
Fabric Update

### ISSUE THREAD

**Issue by dragoonmaster999** [TeamTwilight/twilightforest#2142]
### The Suggestion

Can we just get a newer fabric release? I don't know... at least 1.20.1?

### Why Should It Be in the Mod?

There's a ton of cool mods that are compatible with fabric releases that aren't 1.20.4 or newer. Not only TW has no +1.20.4 release, but older neither (Other than 1.19.2 and 1.18.2). So, it would be great if we can at least update the fabric release into 1.20.1

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
Please don't use this issue tracker to request game versions.
