### ISSUE TITLE
Golden and Diamond Minotaur Axes can't be enchanted whatsoever

### ISSUE THREAD

**Issue by Inonedn** [TeamTwilight/twilightforest#2143]
### NeoForge Version

21.0.22 beta

### Twilight Forest Version

4.6.2504

### Steps to Reproduce

1. Give yourself either item
2. Attempt to enchant it
3. see error

### What You Expected

The Axes dropped by the minotaur would be enchantable, just like every other axe

### What Happened Instead

they are completely incapable of being enchanted

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SeaOfPixels** [comment]
Just discovered this now, can confirm.
