### ISSUE TITLE
Tri-Bow texture reverted to regular bow

### ISSUE THREAD

**Issue by payphone101** [TeamTwilight/twilightforest#2146]
### NeoForge Version

Forge 47.2.0

### Twilight Forest Version

4.3.2508

### Steps to Reproduce

I don't exactly know what caused this bug but I suspect Apotheosis (I could be wrong)
1. Acquire Tri-Bow
2. Affix item with any Mythic Tier affix via Reforging Table (see Apotheosis)
3. Save and quit, and load the world again
4. ???
![image](https://github.com/TeamTwilight/twilightforest/assets/89388404/3beb6893-4377-468f-b0dd-182eddea1781)

5. Tri-bow now uses Minecraft bow texture and arrow is missing when used

### What You Expected

Bow should retain its texture

### What Happened Instead

Bow reverted back to vanilla bow texture

### Additional Details

The bow still functions as tri bow except it's not displaying as tribow

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
do you have a resource pack applied that changes the model of the bow item, such as vanillatweaks' diminishing tools pack? Packs like that can mess with our bows since we use the vanilla bow model as a parent

**Comment by GizmoTheMoonPig** [comment]
closing as this isnt really our fault and I never got a response back
