### ISSUE TITLE
Minotaur Axe's extra damage does not equal to it's attack and doesn't affected by attack cooldown.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#215]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Trying to use Minotaur Axe.

What I expected to happen:Minotaur Axe's extra damage does equal to it's attack and does affected by attack cooldown.

What happened instead:Minotaur Axe's extra damage does not equal to it's attack and doesn't affected by attack cooldown.

**Comment by Terrakota-d** [comment]
x
