### ISSUE TITLE
Restore 1.7.10 Carminite Reactor Visuals

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#2154]
1.7.10 had very different visual effects which we should look into restoring.

![image](https://github.com/TeamTwilight/twilightforest/assets/31552602/1635452c-5533-4ca1-ad46-a2acd31d48b1)

**Comment by AriaElidove** [comment]
When restored, these effects should include some blocks from the 1.16 update if it works/looks well.
