### ISSUE TITLE
Russian translation don't work 

### ISSUE THREAD

**Issue by UkiharaRunian** [TeamTwilight/twilightforest#2156]
### NeoForge Version

forge 40.2.14

### Twilight Forest Version

4.1.1494

### Steps to Reproduce

I tried to use russian translation with this mod

### What You Expected

I wanted to see russian language in the description of objects and other things

### What Happened Instead

Game show me english language instead (I find ru file in mod folder? but it dont work)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
Russian translations are incomplete. You can help by contributing to the Twilight Forest's [Crowdin Page](https://crowdin.com/project/twilight-forest)

**Comment by UkiharaRunian** [comment]
I know, what translations are incomplete, but it is not my problem. Mod don't see basic translation. But when I took English translation, copy it and rewrite in Russian (and add some untranslated things) it become works. 
[ru_ru.json](https://github.com/user-attachments/files/16323773/ru_ru.json)

**Comment by GizmoTheMoonPig** [comment]
unable to reproduce in 1.21 dev, and 1.18 is no longer supported. I would assume theres some sort of formatting error in the file that prevents it from loading in that version or something if it exists, probably a missing/extra comma
