### ISSUE TITLE
Fallen Leaves don't work in the Composter. Intended?

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#2159]
NeoForge version: whatever the 1.20.x branch is on
Twilight Forest version: whatever the 1.20.x branch is on

While going through the code and testing in game, I noticed that Fallen Leaves has a value set in the Compostables data map. However, as this value is set to 0, it ends up making Fallen Leaves incompatible with a Composter again, rendering it either redundant, or there's a value missing.

**Comment by AriaElidove** [comment]
I assume Gizmo must have just missed it when porting to the new system (892ed0e). The old value was 0.1, so no one was missing out on much :P
