### ISSUE TITLE
 Fiery sword not ignites enemies, when issued in any way other than crafting

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#216]
Forge version: 2512
Twilight Forest version: 3.1.1 build 128
Link to crash log: 

Steps to reproduce:
Hit the enemy fiery sword, taken from the creative inventory or by the give command

What I expected to happen:
Mob lights

What happened instead:
Nothing

**Comment by Sonicwave** [comment]
The sword is automatically enchanted with Fire Aspect II when you craft it, but if you take it from the Creative Inventory (or use /give) it doesn't have the enchantment or set fire to anything, despite its description.
