### ISSUE TITLE
[Compat Bug] - Charm of Keeping Deletes All Items when CosmeticArmorReworked is installed

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2162]
### NeoForge Version

20.6.119

### Twilight Forest Version

4.5.2490

### Steps to Reproduce

Die while having a Charm of Keeping (any) in inventory. 

### What You Expected

Items to stay with the player upon respawning (and appropriate excess items to be dropped on the ground when applicable). 

### What Happened Instead

Items are completely wiped.

### Additional Details

I was meaning to report a related issue regarding Charms of Keeping and Cosmetic Armor Reworked where Charms of Keeping would erase any/all Cosmetic Armor in 1.20.4, but now the complete opposite happens in 1.20.6 where JUST Cosmetic Armor is kept (regardless of tier)

I'm just reporting it here in case there is something TF sided rather than CA's

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
I've been stood corrected; in 1.20.4, the items are NOT erased, but they are simply not kept with the player, even with CoK3.

**Comment by GizmoTheMoonPig** [comment]
no longer an issue in 1.21 thanks to https://github.com/TeamTwilight/twilightforest/pull/2155. We never should've passed null into the inventory and 1.20.5 exposed why that was an issue due to saving stacks to nbt.

I added support for keeping cosmetic armor in 4409cf7. Should've done this a long time ago but whatevz
