### ISSUE TITLE
NO TWILIGHT FOREST FOR FABRIC PAST 1.19

### ISSUE THREAD

**Issue by u12bdragon** [TeamTwilight/twilightforest#2164]
### NeoForge Version

PLEASE

### Twilight Forest Version

MAKE

### Client Log

A

### Crash Report (if applicable)

TWILIGHT

### Steps to Reproduce

FOREST

### What You Expected

FOR

### What Happened Instead

1.20.1

### Additional Details

FABRICCCCCCCCC

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by u12bdragon** [comment]
PLEASE man. I cannot believe that one of the TOP 10 MODS of all time DOESN'T HAVE A MODERN VERSION?????????????????????????????????????????

**Comment by AriaElidove** [comment]
![LBozo](https://github.com/user-attachments/assets/690c4ca6-d0cb-4d14-bcd4-6219fd2c22ca)

**Comment by Toastr125** [comment]
If you want a modern version, either use neoforge or port it yourself. The existing fabric ports were done by a separate team.

**Comment by AriaElidove** [comment]
> PLEASE man. I cannot believe that one of the TOP 10 MODS of all time DOESN'T HAVE A MODERN VERSION?????????????????????????????????????????

also, not to be that guy, but askchually, it's the 31st most dl'ed mod 🤓☝️

**Comment by Tamaized** [comment]
Please do not brigade issues tickets.
