### ISSUE TITLE
[Compatibility] More Skull Candles!

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2165]
### The Suggestion

Allow for other mods that add mob heads to be created into Skull Candles. For example, Tinker's Construct, Heads, and some other mods add various mob's heads as drops/obtainable items. 

### Why Should It Be in the Mod?

More mod compatibility is nice, plus most mob heads sourcing from Vanilla heads/skulls mimic the same shaping, so candle additions would not be as difficult to do (for example, husk/drowned would share the same as zombie placement). This would also potentially be something that could be data driven as well, so players can pick and choose which mob heads could have skull candles created from them or not! 

I'm cooking but with week old pasta.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This is up to addon mods since it requires registering new blocks.
