### ISSUE TITLE
Minotaur Axe not critical strike while running

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#217]
Forge version: 2512 
Twilight Forest version: 3.1.1 build 128
Link to crash log: 

Steps to reproduce:
1. Apply to the enemy a critical hit while running.

What I expected to happen: Axe apply critical hit.

What happened instead: Had suffered only the usual increased damage

**Comment by Tamaized** [comment]
Seems to be working just fine for me

**Comment by Megalodab** [comment]
Im also having this problem. it doest seem to stack the regular increased damage + the critical strike (attacking while coming down from the apex of a jump)

**Comment by bs2609** [comment]
You can't perform a vanilla critical hit while sprinting, so these two bonuses are incompatible.

**Comment by Megalodab** [comment]
didnt know that, thanks
