### ISSUE TITLE
The Twilight Forest map not showing up

### ISSUE THREAD

**Issue by Ohminecraft** [TeamTwilight/twilightforest#2171]
### NeoForge Version

Forge: 47.3.0

### Twilight Forest Version

1.20.1-4.3.2508-universal

### Steps to Reproduce

1 load my map
2 i enter the twlilight forest
3 i create my map and not showing up

### What You Expected

I don't know how to describe it

### What Happened Instead

no

### Additional Details

i have epic fight and other rpg mod
(![Screenshot (11)](https://github.com/user-attachments/assets/52198b12-8e9e-4b10-b0db-d9b78cc09a53))
![Screenshot (12)](https://github.com/user-attachments/assets/0e902a46-3cca-44dc-9e90-9340c7b5a1b3)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Toastr125** [comment]
This might have to do with how Epic Fight renders things for its animations. Create a new world and test it both with and without that mod.

**Comment by Ohminecraft** [comment]
it works! but i want play with epic fight with my friend how can i fix it?

**Comment by Ohminecraft** [comment]
> This might have to do with how Epic Fight renders things for its animations. Create a new world and test it both with and without that mod.

it works! but i want play with epic fight with my friend how can i fix it?

**Comment by Toastr125** [comment]
Check to see if Epic Fight has a config to exclude items

**Comment by GizmoTheMoonPig** [comment]
we cant really do anything about this without adding explicit compat. Honestly epic fight mod should be checking for instances of MapItem when doing the map animation. I guess they do for the arms but not the item rendering itself
