### ISSUE TITLE
Выбрасывает из мира вскоре после попадания в сумеречный лес

### ISSUE THREAD

**Issue by WELLZERAGNA** [TeamTwilight/twilightforest#2172]
### NeoForge Version

Forge 1.7.10

### Twilight Forest Version

2.4.3

### Steps to Reproduce

1.Создаю портал в сумеречный лес
2.Прохожу через портал
3.Загружает лес
4.Выкидывает из мира(одиночная игра) с ошибкой об остановке сервера
![Знімок екрана 2024-07-28 143801](https://github.com/user-attachments/assets/3e5ebfc8-632c-4607-bc71-0c37d0051753)

### What You Expected

Нормальный геймплей сумеречного леса

### What Happened Instead

Постоянные вылеты пока не покину сумеречный лес

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
Are there other mods installed?

----

For the devs, basically this report is that the game crashes when entering the Twilight Forest on a Single-Player world, and does not fix unless the player is removed from the dimension. Again, this is on 1.7.10, so I don't believe there is any support as is?

**Comment by Tamaized** [comment]
2.4.3 is also the GTNH version that we don't work on.
