### ISSUE TITLE
[Mobs] Allow Boars to have Saddles

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2173]
### The Suggestion

Seeing as they are the "pigs" of the Twilight Forest, allowing them to be ridden with saddles could be nice. Considering that there are also no horses, this could be a "viable" means of transportation (although I think it is really goofy lol)

### Why Should It Be in the Mod?

This wouldfix #2157 and allow the Boar/Pig transformation to keep the saddle on the Boar/Pig through it's transformation (this would mimic the reading of NBT for Wolf Variants). 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
We'd rather not allow Boars to be saddled.
