### ISSUE TITLE
[Suggestion] New recipes to craft previously-uncraftable decorative blocks 

### ISSUE THREAD

**Issue by chickeness** [TeamTwilight/twilightforest#2175]
### The Suggestion

My idea is for two new crafting recipes, one for hedge blocks and one for underbrick. Underbrick would be 2 armor shards+ 2 bricks to produce one block, or it could be upped to 2 armor shards and 2 brick blocks to produce 2 blocks depending on balancing, or even four.
The hedge blocks would be crafted with leaf blocks and steeleaf, either 2x2 with leaf blocks and 2 steeleaf for two or four, depending on balancing.

### Why Should It Be in the Mod?

This should be added as it solves two problems at once, adding crafting recipes for two previously-uncraftable blocks, making underbrick completely renewable and making hedge blocks viable to build with, as well as providing non-tool uses for two of the special materials- knightmetal and steeleaf- added by the mod.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by AriaElidove** [comment]
Underbrick is not intended to be renewable, nor are hedges, much like castle bricks and aurora blocks.

**Comment by Killer-Demon** [comment]
See #1553
