### ISSUE TITLE
Recreate Signed Books into Uniquely Added TF Items

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2181]
### The Suggestion

Make all Kobold Signed Books into unique TF items (Perhaps something called "Forgotten Notes"), which can be piece together to form a long notebook of information. This would allow for custom page textures that mimic that of the descriptions within the actual notes, ie "An explorer's notebook, written on faintly glowing paper" would show bite and teeth marks indented onto the pages of this segment. 

The texture for this could mimic that of the Traveller's Logbook from Patcholi, where it shows more growth of pages as you collect and combine all of these pages. I'm not sure if there is a specific item design which would be perfect for this, but a book which has cluttered pages inside of it seems pretty accurate to this, and a recipe could be as simple as:

`123`
`4B5`
`678`

Where the numbers are the unique pages and B is a book of some sort; functionally mimicing the Moonworm Queen's refill mechanic in a way where not all pages are required to create the book; only 1 is. 

After thought, but this sounds like you could make some 8 pages shit with this lmfao, not my intention lol.

### Why Should It Be in the Mod?

This is simply to bump and expand more on #523 and to expand on the current Signed Books.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This would add too much dev overhead for what is missable content. It's not something we want to turn into a collectable given that it is permanently missable and a glorified tutorial. Maybe some day in the far off future when we do a journal, but not without.
