### ISSUE TITLE
[Vanilla Functionality] Aurora Block Stonecutting

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2184]
### The Suggestion

Allow Aurora Blocks to be stonecuttable into their slab and pillar variants, much like how Quartz Blocks, the most similar vanilla blocks, are able do the same.

### Why Should It Be in the Mod?

While Aurora Blocks are not made of stone, other TF blocks use the stonecutter despite this same reasoning (IE towerwood, hollow logs). Also raises the question as to what Aurora Blocks even are (Does anyone actually know?).

Just creating this as a separate ticket for consideration during the Aurora Palace's rework and to move it off of #2180 as of KD's mention. 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
As mentioned in #2180 we will look at this when we get to the rework. We're likely introducing more blocks with it and an issue for this serves no purpose until we solidify our plans for it.
