### ISSUE TITLE
Flying trees generation

### ISSUE THREAD

**Issue by Sleepy-Horse** [TeamTwilight/twilightforest#2185]
### NeoForge Version

21.0.146

### Twilight Forest Version

8acbf9fdd7ece74c9c3ab4367a8c3be95a0b9145

### Steps to Reproduce

1. Generate a world with seed 6079176244646726988
2. /tp -446 6 11581

### What You Expected

Trees can't fly

### What Happened Instead

Trees can fly
![image](https://github.com/user-attachments/assets/e6db0dea-3d3d-44b8-8d3f-5d0c87a49e8c)

### Additional Details

I will try to create a PR for this after adding oak bushes. If I should change the priority of PRs, please let me know.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Looks like the mangrove root generation failed, but the tree still generates.
