### ISSUE TITLE
[World Generation] Adjust Deadrock Plateau Erosion

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2186]
### The Suggestion

Make Weathered Deadrock appear on ALL faces of the deadrock plateau instead of purely being a vertical gradiation.

How it is now:
![image](https://github.com/user-attachments/assets/a6c28eb8-b047-45ca-a78f-d5424b6548c3)

### Why Should It Be in the Mod?

Erosion acts on multiple directions, not in a purely vertical line.

This may be better suited for the future Final Castle rework, but I will still suggest it now to have it up :P

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
This is intentional design
