### ISSUE TITLE
Weird Place Structure Issue

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2187]
### NeoForge Version

21.0.158

### Twilight Forest Version

4.6.2692

### Steps to Reproduce

Place a hedge maze via commands
Do it again in the same spot
Leaf jumpscare
![image](https://github.com/user-attachments/assets/395b1a6c-ecfc-499f-981e-86a39ec5b084)
![image](https://github.com/user-attachments/assets/a8c5312c-ac46-46b2-82cf-0a98197524c9)

### What You Expected

Place Structure command not to be so fucking weird and jank

### What Happened Instead

Place structure janked stuff

### Additional Details

This is likely purely mojank and not twilight jankest or anything but figure to report.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
The `/place` command is nothing to do with the Twilight Forest, this looks like intended behavior with the /place command.

**Comment by AriaElidove** [comment]
I don't see anything intended with leaves generating in places where they're never supposed to generate, let alone some other issues I found (loot tables being the exact same and not regenerating themselves on new placement, and cells completely breaking themselves), but if this is just mojank then that's that ¯\_(ツ)_/¯
