### ISSUE TITLE
[Dark Tower Devices] Locked Vanishing Blocks Affect Reappearing Blocks?

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2188]
### NeoForge Version

20.4.235

### Twilight Forest Version

4.6.2692

### Steps to Reproduce

Place a Locked Vanishing Block next to a reappearing block. The reappearing block is now locked.

### What You Expected

Reappearing Blocks should not be affected by the mechanics of Locked / Vanishing Blocks.

### What Happened Instead

Reappearing Blocks are locked when next to Locked Vanishing Blocks

### Additional Details

This very well might be intentional, but there is nothing in the Dark Tower mechanically which supports this.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This is intended behavior
