### ISSUE TITLE
The force filed will drop missing-texture block after destroyed bt Naga.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#219]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Let naga destroy a force field.

What I expected to happen:The force field will drop.

What happened instead:It dropped a missing-texture block instead.

**Comment by Drullkus** [comment]
I thought I fixed this in latest build. Please download newest build on Curseforge and tell me if it still persists.

Next time please put build number in
