### ISSUE TITLE
Candelabra Redstone Adjustment

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2192]
### The Suggestion

Allow for standing Candelabras to provided redstone signal to redstone connected to it.
![image](https://github.com/user-attachments/assets/45ef241a-99e8-4fab-952c-c57eb8dca61d)

### Why Should It Be in the Mod?

The redstone already moves as though it was able to, but yet it doesn't provide a signal. Only wall Candelabras do this, as shown above.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
the candelabra provides redstone signal in whatever direction the stand is facing, this is intended. I dont know why redstone connects like that but it shouldnt

**Comment by AriaElidove** [comment]
This feels wrong from a building/redstone view, but if it's whatcha wanted then this can be retitled as a bug (unless it's Mojank, in which case idk).

![image](https://github.com/user-attachments/assets/00a3231a-0e8a-4bbd-b957-3f36d8c65788)

**Comment by GizmoTheMoonPig** [comment]
looks like I cant make redstone conditionally connect to the side that actually provides power so it now doesnt at all. 

As for the signal thing, it was an intended thing to make it only emit power from the side the stand was facing. It can obviously be read with a comparator from any side (couldnt make it sided even if I wanted to), so theres no point in keeping this open anymore

**Comment by AriaElidove** [comment]
> "looks like I cant make redstone conditionally connect to the side that actually provides power so it now doesnt at all."

You could make it so that the Standing Candelabra has no redstone connections, while the Wall-Mounted Candelabra can act as a redstone repeater so that it can ignore sides which are irrelevant, changing on it's rotation. 

The former seems like an easier way to fix that, and I'd imagine the Wall-Mounted Candelabra would be fine explanatory without change because of the extra side mount.

![image](https://github.com/user-attachments/assets/7ec78bb1-5b96-47fe-9252-47e7c9c6e125)
