### ISSUE TITLE
Change how Hint Kobolds Spawn

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2195]
### The Suggestion

Hey so maybe we SHOULDNT have Kobolds spawn if you are at a high Y level or are flying over restricted areas with an elytra or something. While I absolutely LOVE flying through the Twilight Forest and watching Kobolds fall to their doom, this doesn't seem very practical nor reasonable to have continue.

In short, if there is no safe block for a Hint Kobold to spawn on near the player, don't spawn it.

### Why Should It Be in the Mod?

#StopKoboldTorment2024

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
nah its funny

**Comment by AriaElidove** [comment]
Only issue of allowing it is that they won't drop their book which kinda sucks lol. They just drop their normal Kobold drops.

Warning for Kobold Torment: https://www.youtube.com/watch?v=lMaG5bYiTLg
