### ISSUE TITLE
Troll Cave Vegetation

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2196]
### NeoForge Version

21.0.158

### Twilight Forest Version

4.6.2721

### Steps to Reproduce

Troll Cave.

### What You Expected

Vegetation! Mushglooms! All that good stuff!

Image from the wiki, dated 2017:
![image](https://github.com/user-attachments/assets/3b5ed6fa-a267-4e21-a442-52c274bf5d68)

### What Happened Instead

There is no Uberous Soil, no Huge Mushglooms or Stems, no Mycelium, no Mushglooms, nothing!
![image](https://github.com/user-attachments/assets/c98afb85-dcb9-4596-9685-d9a710ab155f)

### Additional Details

this issue was originally going to be a suggestion to bring back the mycelium and small mushglooms, but apparently the vegetation alt f4'ed or something.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by LiteWolf101** [comment]
Looks like the config for the feature only has it's heightmap set to `WORLD_SURFACE_WG` which i dont think plays nicely with underground structures. I wonder if it might need to either just be added to the underground highlands biome, or if it will need another placed feature just for it to spawn inside this structure.
