### ISSUE TITLE
Magic Sapling Bug/Game Crash

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#22]
Bug: The 4 Magic Saplings don't grow to full size, only a few blocks. They also create "ghost blocks" around them. 
Twilight Forest version: 2.4.0.4
Forge version: 13.20.0.2260
Crash report: https://pastebin.com/55pQigCP
Video showing bug: https://www.youtube.com/watch?v=IBKpGzuFzaY
The bug is shown at at 0:24-0:48, 1:03-1:21, 1:54-2:10. 
After testing some more, it seems that most(?) Twilight Forest saplings behave in the same broken way. The game crashed again: https://pastebin.com/CUsDJPHJ

**Comment by williewillus** [comment]
Same root cause as #21
