### ISSUE TITLE
Differentiate Maze and Magic Maps

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2201]
### The Suggestion

As it stands, the only way to tell the difference between a Maze Map and a Magic Map is a total of 8 pixels. That's literally it lol.

This suggestion is to introduce an addition to one or both of these maps to show the difference of the two. The Ore Map does this by having a thick, light blue outline. Perhaps something less intense for the Maze and Magic Maps would work!

### Why Should It Be in the Mod?

Changes to boost accessability, plus it would be able to mimic the changes which Mojang made with their maps.

![image](https://github.com/user-attachments/assets/cd0ce76e-8ad7-4771-963e-e641a4bde604)

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by AriaElidove** [comment]
Sat down and thought about it for a bit and made a quick design. Seeing as the Magic Map Focus has this yellowy outline to it, would doing a similar one (as below) around the Magic Map work, kinda like the blue around the Ore Map.
![magic_map_sugg](https://github.com/user-attachments/assets/66b7dc17-30bf-49f5-a8ce-651dda01ea8f)

**Comment by Killer-Demon** [comment]
We're currently happy with the way our maps look.
