### ISSUE TITLE
Timewood Clock Position on Tree of Time

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2203]
### NeoForge Version

21.0.158

### Twilight Forest Version

4.6.2721

### Steps to Reproduce

Plant a Timewood Tree
Find which direction the core is

### What You Expected

Timewood Clock should always appear at the center of whichever direction the player is when it is grown; 

### What Happened Instead

Timewood Clock will always appear on the Western side of a Tree of Time, regardless of how it was planted or grown.

### Additional Details

it is fucking 5 in the morning and i am doing *this* of all things. 

anyways, just test by bonemealing the tree and seeing if the core will generate where you can immediately see it.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Not possible
