### ISSUE TITLE
Critter Blockstates

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2204]
### The Suggestion

Make it so Fireflies and Cicadas placed on the ground actually orientate themselves with the direction they are placed. Wall and ceilings can be unaffected. 

### Why Should It Be in the Mod?

I want to make myself a row of funny fireflies on the ground. Having them randomize in direction is annoying.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
Them not orienting themselves to a player's whim helps to sell the fact that they're not _just_ blocks if only a little. Therefor it's not something we'd want to add.
