### ISSUE TITLE
Make Hollow Logs Connectable

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2207]
### The Suggestion

Alternating direction Hollow Logs should be connectable and have blockstates which represent this. Concept here using Chisel:

![image](https://github.com/user-attachments/assets/dcc15288-eae5-48d7-afb1-2c0a388c7416)

### Why Should It Be in the Mod?

I want long hollow log tunnels so i can rat.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This isn't something we're wanting to do as it would introduce far too many blockstates for something that isn't worth it.
