### ISSUE TITLE
Vangrove Jars

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2216]
### NeoForge Version

21.0.167

### Twilight Forest Version

4.6.2750

### Steps to Reproduce

Vangrove and Stripped Vangrove Jars break texturing

### What You Expected

Proper Cork Texture

### What Happened Instead

Broken Texture

### Additional Details

Jodi Declared It So It Shall Be

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Killer-Demon** [comment]
What is wrong with them?
![image](https://github.com/user-attachments/assets/74edcb78-e20a-45c2-a85f-b55eab0fe4de)

**Comment by Killer-Demon** [comment]
I see. I was two builds behind. Carry on.
![image2](https://github.com/user-attachments/assets/dfa0c2a9-bc45-4517-90a0-e1925a8af42a)
