### ISSUE TITLE
Trophy Config Settings

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2217]
### The Suggestion

If the configuration setting "Animate Trophies" is turned off, disable the Ur-Ghast tentacle animation as well.

### Why Should It Be in the Mod?

Actually disables the animation on the trophies.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
The config is only for the spinning, not anything else.
