### ISSUE TITLE
Questing Ram Colour Order

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2219]
### NeoForge Version

21.0.167

### Twilight Forest Version

4.6.2750

### Steps to Reproduce

The Questing Ram when it has full wool, seems to be out of order to the vanilla wool order; the specifics being Light Blue and Cyan being reversed and Brown being at the end instead of being between Black and Red. 

### What You Expected

Parity between QR's wool colours and vanilla colour order.

### What Happened Instead

A different rainbow-flow occured

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
I forgot to show image, whoops:
![image](https://github.com/user-attachments/assets/9f5b8c47-ccd5-420e-8b51-28c22be9316b)

**Comment by Killer-Demon** [comment]
Intended.
