### ISSUE TITLE
Encased Fire Jet Issues

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2224]
### NeoForge Version

21.0.167

### Twilight Forest Version

4.6.2750

### Steps to Reproduce

1) Place down an Encased Fire Jet. 
2) It automatically lights up the area (15)
3) Activate it via lever
4) It pops and shoots invisible flames
5) It doesn't consume any fuel

### What You Expected

There should be no light when inactive. It should not move to an idle state when there is no lava beneathe it (or acceptable fuel). Flames should not be invisible. Fuel should be consumed.

### What Happened Instead

Light while inactive, attempts to pop without a fuel source, flames are invisible, and fuel is not consumed.

### Additional Details

This also affects normal Fire Jets, gimmie a moment to ticket it too.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
encased fire jets dont use fuel, thats intended. I'll look into the lighting and particle thing
