### ISSUE TITLE
Questing Ram Swirls Banner Pattern Displays Broken Texture + Missing Lang Entry.

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2228]
### NeoForge Version

21.0.167

### Twilight Forest Version

4.6.2754

### Steps to Reproduce

While I know this is quite literally intended behaviour, as one does not exist currently, it still shows a broken texture rather than a blank texture. Also, no lang.

### What You Expected

No texture shown, just basic banner

### What Happened Instead

Black and broken pink/purple colour we are all too familiar with.

### Additional Details

note to self: dont fucking boot up 4 instances of minecraft at once. three is the limit. 

1.21.1 ![image](https://github.com/user-attachments/assets/50a42ae8-bf02-47dd-80d8-088cd5a2a281)
1.20.6: ![image](https://github.com/user-attachments/assets/3ee43537-8e93-46b9-9097-a00878e2171e)
1.20.4: ![image](https://github.com/user-attachments/assets/6c4b2ff7-c23a-4d1c-8109-80d3d8aaf459)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
#1886
