### ISSUE TITLE
Helmet Crab, Slime Beetle, Pinch Beetle and Fire Beetle must have own sounds 

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#223]
Forge version: 2512
Twilight Forest version: 3.1.1, 136

Maybe they should use their own unique sounds, as they are not variation of other mobs, unlike Hedge Spider or Towerwood borer

Sorry for my english

**Comment by Tamaized** [comment]
Looks like they used spider sounds in 1.7 as well

https://github.com/TeamTwilight/twilightforest/blob/1.7.10/src/main/java/twilightforest/entity/EntityTFHelmetCrab.java#L89-L108

**Comment by Terrakota-d** [comment]
Hmm, strange. I performatory this topic.

**Comment by Sonicwave** [comment]
This could also be applied to the Lich, it currently uses Blaze sounds

**Comment by Tamaized** [comment]
Moving this into #269
