### ISSUE TITLE
[Suggestion] Add blacklist & whitelist of items for Uncrafting Table in the config

### ISSUE THREAD

**Issue by YiceLi** [TeamTwilight/twilightforest#2231]
### The Suggestion

Game version: 1.12.2
Add editable blacklist and whitelist for the uncrafting table to the configuration file to customize which items can be dismantled

### Why Should It Be in the Mod?

This allows server administrators to customize the uncrafting table to avoid bugs based on the mods currently being added, while still retaining the fun of uncrafting table. You can extend this feature to other mod versions

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by AriaElidove** [comment]
This already exists in later versions. Also, 1.12.2 is no longer supported.

**Comment by Tamaized** [comment]
For an actual helpful response:

Use this mod for 1.12
https://www.curseforge.com/minecraft/mc-mods/uncrafting-blacklist
