### ISSUE TITLE
The old textures of the minotaur's axes are being used

### ISSUE THREAD

**Issue by LioxAcc** [TeamTwilight/twilightforest#2238]
### NeoForge Version

Forge 1.20.1-47.3.7

### Twilight Forest Version

Twilight Forest - MC 1.20.1 - 4.3.2508

### Steps to Reproduce

In any world (without using any texture pack) when checking the textures of the minotaur's axes (gold or diamond) you will see that the old textures are being used

### What You Expected

See this (Screenshot taken in Twilight Forest - MC 1.16.5 - 4.0.870)
![2024-08-27_15 12 58](https://github.com/user-attachments/assets/f1842720-03b6-4948-862b-b8732a1b6b89)

### What Happened Instead

It looks like this
![2024-08-27_15 10 34](https://github.com/user-attachments/assets/79c8f545-12c3-4397-9365-6638740d63bd)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
intended, if you want the new textures download the resource pack here: https://www.curseforge.com/minecraft/texture-packs/twilight-forest-jappa-pack
