### ISSUE TITLE
Phantom Knights lost their shield

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2239]
### NeoForge Version

21.0.167

### Twilight Forest Version

4.6.2754

### Steps to Reproduce

Fight the Knight Phantoms
None of them have a shield.

### What You Expected

The shield not to have permanently broke one day.

### What Happened Instead

No shield, no shoes, no service.

### Additional Details

This entire system is a little wonk

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
the shield only appears on one of them in hard mode, if youre playing any other difficulty they dont spawn with it

**Comment by AriaElidove** [comment]
I NEVER KNEW THAT OKAY THEN

ill test still but WOW

**Comment by Tamaized** [comment]
it's been like that since 1.12.2
