### ISSUE TITLE
Fiery Pick does not interact with "fortune"

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#224]
Forge version: 2512
Twilight Forest version: 3.1.1
Link to crash log:

Steps to reproduce:
1. Use Fiery Pick with fortune enchanted, on ore blocks such as iron or gold

What I expected to happen: Fortune works

What happened instead: Nothing

**Comment by Tamaized** [comment]
This is working as intended, the Fortune enchantment works fine on blocks it **should** work on, such as lapis, diamond, redstone, so on. But it doesn't increase the amount from smelting since well, Fortune doesn't give you more than one ore so why should it give you more than one ingot.

**Comment by Terrakota-d** [comment]
Maybe so. But one of the main reasons why the iron and gold is not mined with a pick on fortune is the duplication of ore. With a smelting fortune enchantment would make sense :P

**Comment by williewillus** [comment]
We should move the smelting to an enchant and make it incompatible with fortune maybe

**Comment by Tamaized** [comment]
I thought about that too but then what about stuff fortune should actually work on, would lose that. But I suppose this would have less confusion overall though.

**Comment by Benimatic** [comment]
I think I started with the smelting as an enchant, but moved it to innate to the material because the enchant was awkward. It made it more difficult to add more enchants, and there were several ways to lose the enchant (repairing, other mod interactions).

**Comment by Benimatic** [comment]
IIRC, Tinker's Construct in 1.10+ versions allows both fortune and autosmelting on its tools. You just end up with more iron or gold ingots.

**Comment by Tamaized** [comment]
Ah so it does, hmm should we reopen and implement this then?
