### ISSUE TITLE
Enabling automatically entering the Twilight Forest on a void flat world send the player down to the Void.

### ISSUE THREAD

**Issue by pantsguyapp** [TeamTwilight/twilightforest#2240]
### NeoForge Version

Forge 1.20.1

### Twilight Forest Version

twilightforest-1.20.1-4.3.2508-universal

### Steps to Reproduce

1. Make a Void World, but has auto-entering the TF turned on in the config.
2. As soon as you spawned in, you will spawn in the void below the forest generation.
3. Will also occur when you die without a bed in the TF.

### What You Expected

Despite the Overworld generation is set to Superflat Void, the player will still be spawned in above the top layer of the TF.

### What Happened Instead

It drop you below the bedrock layer of the TF.
I tested with the "Redstone Ready" setting and it seems that that works fine, it spawn you at y56, which is the y coord of the top most layer of block in the superflat Overworld.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This has been fixed in the current master branch. We do not do back ports however so this fix wont come to 1.20.1
