### ISSUE TITLE
Placing TF leaves on a chest prevent it from opening

### ISSUE THREAD

**Issue by pantsguyapp** [TeamTwilight/twilightforest#2242]
### NeoForge Version

no

### Twilight Forest Version

twilightforest-1.20.1-4.3.2508-universal

### Steps to Reproduce

1. Place a leaf block from any trees in the TF on a chest.
2. Try to open it.

### What You Expected

Like normal leaves, the chests would open

### What Happened Instead

The leaf prevent the open of the chest

### Additional Details

Tested with every types of leaf block in the TF forest.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AriaElidove** [comment]
This happens in latest development version (4.6.2754) as well.
