### ISSUE TITLE
[Suggestion] Sleeping in the TF should change time to day

### ISSUE THREAD

**Issue by pantsguyapp** [TeamTwilight/twilightforest#2243]
### The Suggestion

Unlike other vanilla dimensions, you can actually sleep in the TF, but you cant change the time of day when you sleep in the dimension as of current.

### Why Should It Be in the Mod?

This is necessary if you are planning to set up villagers in the TF, and want to reset the day as soon as they begin to flock to bed.
Although this won't affect the sky, as the TF has set skybox, this still make it easier for villager mechanics.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Toastr125** [comment]
Villagers aren't native to TF and TF doesn't have a day-night cycle.

**Comment by pantsguyapp** [comment]
I do aware of this, but you can easily transport them there, especially when the portal is mostly less costly to open than the Nether Portal, so the TF could make this as a perk for villager trading.

- "TF doesn't have a day-night cycle."

But allow it to affect time shouldn't do any harm, could make it a config if it truly affect servers.

**Comment by Tamaized** [comment]
This is a vanilla problem. Sleeping in any dimension does not affect the time in the overworld.
