### ISSUE TITLE
Skull Candle Dispensor pt 2

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2247]
### The Suggestion

Create a behaviour that dispenses a skull candles onto players via dispensor.

### Why Should It Be in the Mod?

Vanilla heads do this.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
I think this was inadvertently fixed by 5187395b6f2f01388cb5ca2e8de482d907b961f4 if it wasnt properly working already

**Comment by AriaElidove** [comment]
It was not.
