### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2248]
### NeoForge Version

21.0.167

### Twilight Forest Version

4.6.2754

### Crash Report (if applicable)

https://pastebin.com/hb05t2ge

### Steps to Reproduce

Boot up Isometric Render (0.4.7), Sinytra Connector and Forgified Fabric API (I don't know how to read these versions but just assume latest) with Twilight Forest

Attempt to do an area render of a Giant Block or Forcefield:
1) Place block of choice
2) Press "C" twice over the block
3) Run the command `/isorender area`
4) Crash

### What You Expected

Not to Crash.

### What Happened Instead

Crashed.

### Additional Details

This is simply a formality so it can be written down here as well as the other gits:

Giant Blocks and Force Fields crash the game when rendered by isorender. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Drullkus** [comment]
Try updating your mods, I threw
```
connector-2.0.0-beta.2+1.21.1-full.jar
ConnectorExtras-1.12.1+1.21.1.jar
forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar
isometric-renders-0.4.7+1.21.jar
owo-lib-0.12.11+1.21.jar
twilightforest-1.21.1-4.6.2775-universal.jar
```

into a fresh 1.21.1 instance with NF 21.1.34, can't reproduce crash inside the Twilight Forest dimension

**Comment by Tamaized** [comment]
The crash isn't even in our code, it's in the isorender mods code 

`TRANSFORMER/worldmesher@0.4.61.21/io.wispforest.worldmesher.WorldMesh.lambda$build$7(WorldMesh.java:369)`

Furthermore, you should never report a crash to any mod when syntra connector is involved. Ask about it in the connector discord first.
