### ISSUE TITLE
Magic Core sounds configuration

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2249]
### The Suggestion

Make Magic Core sounds disabled via config if a player choose to

### Why Should It Be in the Mod?

I don't want to constant hear "beep, boop, beep, beep" and "tick tick tick tick" while debugging things regarding the cores

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by LiteWolf101** [comment]
Why do that when there's a mod that has this ability for you?

[Extreme Sound Muffler](https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler)

I don't think it would be a good idea to have sounds for a mod as big as this to have a configuration entry just for disabling.

**Comment by AriaElidove** [comment]
Because I rather not learn how Intellij handles adding mods for `Run Client`

**Comment by Tamaized** [comment]
You.... Just put the mod in the mods folder ...

**Comment by Fooshcookie** [comment]
> You.... Just put the mod in the mods folder ...

Uhmzm,, no#'?

**Comment by Tamaized** [comment]
Yes

$project/run/mods

**Comment by Drullkus** [comment]
Fantastic find, @LiteWolf101! For anyone else curious, I dropped it into the directory that Tama posted -- It works 🎉 

<img width="1330" alt="Screenshot 2024-09-01 at 10 34 12 AM" src="https://github.com/user-attachments/assets/575ce15f-6cb1-4782-9665-2689724f02e5">

**Comment by AriaElidove** [comment]
Yea that does just work. The last times I tried something like this it just would not function, so thank you.

Following this, should yall just... remove the cicada sfx config then? Seeing as this is an option:
![image](https://github.com/user-attachments/assets/d82f2732-e9f7-4b62-a304-32bfde6e4428)

**Comment by Tamaized** [comment]
Nah

**Comment by GizmoTheMoonPig** [comment]
the main difference between the core sounds and the cicada sounds is that theres no way to control the cicada volume without the use of external tools like the sound muffler. While it is a legacy config option from the old MC sound engine days, its still good to have for people since they dont play on a certain sound channel and cant be quieted without changing the master volume
