### ISSUE TITLE
Make Castle Doors and Reappearing Blocks "Solid" while vanished

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2251]
### The Suggestion

When interacting with water while vanished, these blocks should act solid, much like how fence gates act

### Why Should It Be in the Mod?

These blocks popping into items because of water feels very inconvenient (plus, who needs a pickaxe when water bucket is now my best friend). 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
this is technically a bug, no worries because its not an issue now
