### ISSUE TITLE
Trophy Visual Adjustments

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#2252]
Minor visual adjustments for trophies:
1. Re-center the Hydra one to be on the head itself.
2. Slightly downsize the Knight Phantom one given that the helm makes it larger than it should be.
![image](https://github.com/user-attachments/assets/d39a5022-4400-4f52-925d-bdf0b49ef0dc)

**Comment by Drullkus** [comment]
Completed via [a3f85c9](https://github.com/TeamTwilight/twilightforest/commit/a3f85c9644cca45bcd16d5b88a717ca274651a57)
