### ISSUE TITLE
TF fence gates can't be used as a water blocker

### ISSUE THREAD

**Issue by pantsguyapp** [TeamTwilight/twilightforest#2253]
### NeoForge Version

No

### Twilight Forest Version

twilightforest-1.20.1-4.3.2508-universal

### Steps to Reproduce

1. Make a water flow to transport mobs
2. Use TF fence gates to block water
3. They break by the water current whereas vanilla fence gates work fine.

### What You Expected

The fence gates work as intended similar to vanilla ones

### What Happened Instead

They got destroyed instead.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
I guess I missed a bunch of blocks during the material rework in 1.20.1. Would you mind checking out some other non-full blocks and seeing if they get destroyed by water and let me know so I can fix them all in 1 go? I already tackled castle doors and reappearing blocks

**Comment by pantsguyapp** [comment]
Cant, it will be a long time before I play again.

**Comment by AriaElidove** [comment]
Fence Gates (when open) and Pressure Plates are the main two that have this issue that I've found. 

Skull Candles pop as well, but vanilla skulls do pop when interating with water sooo I take this part as a non-issue.

Rope isn't affected, but it probably should be (mimics root strands)

Force Fields, despite being waterloggable, remove the water that exists within a block (TF and vanilla glass panes dont react this way)

Everything else *looks* to be normal relating to water. Banisters, Fences, Trapped Doors, Doors, Buttons, and Signs all work like vanilla's/intended.
