### ISSUE TITLE
Red Thread Emission Fade

### ISSUE THREAD

**Issue by AriaElidove** [TeamTwilight/twilightforest#2256]
### The Suggestion

Make Red Thread gain/lose emissions gradually (fade in/out) when in/out of a player's hand instead of there being an instant emission.

### Why Should It Be in the Mod?

I just thought this might look nice visually, but there's no real reason for it

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Killer-Demon** [comment]
This would make it much harder to detect any placed Red Thread as you will no longer be able to make it "flicker" by putting it in your hand and out again.

Because of that, its already hard to see nature, and even the feasibility of it, this is not something we want to do.
