### ISSUE TITLE
[1.21.x][Neoforge] Player head clips through screen when attack animation happens 

### ISSUE THREAD

**Issue by ffuentesm** [TeamTwilight/twilightforest#2257]
### NeoForge Version

21.1.43

### Twilight Forest Version

4.6.2780

### Steps to Reproduce

Play the game with Better combat installed then make an attack with a weapon

### What You Expected

The Better COmbat animation should play out

### What Happened Instead

THe player model renders the head and causes it to clip through the camera 

### Additional Details

https://github.com/ZsoltMolnarrr/BetterCombat/issues/409

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ImAK9** [comment]
This also happens when casting spells from Iron's Spells 'n Spellbooks mod

**Comment by GreatKingKeenan** [comment]
I can confirm that this is an issue. I'm wondering if this a render state incompatibility with playerAnimator?

**Comment by ffuentesm** [comment]
Not sure, since Irons Spellbook uses Geckolib instead of player animator. 
But sure there is some incompatibility with the player model render animations.

**Comment by SkyRunner55** [comment]
i was wondering which mod i enabled made this issue when i was testing better combat, and using iron spell book's spell

**Comment by lab3** [comment]
@ffuentesm, Iron's uses playeranimator for Player animations. We only use geckolib for entity animations.

**Comment by ffuentesm** [comment]
And that is causing conflict with the player head rendering. 
Since I am using Ars wish also uses geckolib, and causes no conflict with playeranimator. 
Only TW is causing problems when I install it along side Iron's or Better Combat.
