### ISSUE TITLE
No model for layer twilightforest:knightmetal_shield#main

### ISSUE THREAD

**Issue by LeoMassaFM** [TeamTwilight/twilightforest#2264]
### NeoForge Version

21.1.51

### Twilight Forest Version

4.6.2780

### Client Log

https://gist.github.com/LeoMassaFM/ea5523646106b68e22011b59f16f3d06

### Crash Report (if applicable)

https://gist.github.com/LeoMassaFM/c1056e784fd2ad4d1bf359e06323d4b9

### Steps to Reproduce

1. Boot up the game
2. The game crashes

### What You Expected

The game should've launched

### What Happened Instead

The game crashed

### Additional Details

Unlike other reports on this kind of issue, my latest.log doesn't seem to have a line of text that says "Caused by:", so I don't know what mod(s) caused this issue. I have removed the Entity Model Features, Entity Texture Features, and Entity Sound Features (all three at the same time), but the game still crashed on startup. Here are the Gist files for that:
[latest.log](https://gist.github.com/LeoMassaFM/829ce123e421c9e0c5e52b45e6a15b78)
[crash-2024-09-15_13.17.35-client.txt](https://gist.github.com/LeoMassaFM/8267f79e1bf698145e1b0f4d8c0bc63d)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Dinocraft1515YT** [comment]
Same happend to me

**Comment by Soforak** [comment]
Same here

**Comment by X-Machiavelli** [comment]
same here. maybe this mod is using an independent CEM lib that vanila alone can't handle. or the latest version of neoforge broke it.

**Comment by Sleepy-Horse** [comment]
Could you please give me the name of the modpack because I can't reproduce the crash.

**Comment by LeoMassaFM** [comment]
I would post the zip file here but it is way too large. Just know that it has 200 mods, and that I also tried removing Sinytra Connector (and all Fabric mods I had installed), but that didn't solve anything. I'll do more testing in order to find the real culprit(s).

**Comment by khanhtimn** [comment]
same happened

**Comment by X-Machiavelli** [comment]
I'm thrilled. I finally find out what was causing this error. 'The Twilightforest' conflicts with 'Remove Reloading Screen' mod. I'm not a programmer, so I don't know the details of why, I'll leave that to bros.

**Comment by Tamaized** [comment]
Wack, thank you for figuring that out.

**Comment by Tamaized** [comment]
I've deemed this unfixable on our end.

That mod looks like it breaks a LOT of mods 

And the dev is quite something else to be honest.

<https://github.com/dima-dencep/NanoLiveConfig/commit/841e17eacca2d3a1e12b025fc490f392d202ea73#diff-1ff14800a2d51a7283fec4f7b0caab72161948abb6f423e62d4a3ba6e2a07bd1R22>
