### ISSUE TITLE
Druit hut not generating loot

### ISSUE THREAD

**Issue by Glumac777** [TeamTwilight/twilightforest#2265]
### NeoForge Version

21.1.42

### Twilight Forest Version

4.6.2780

### Steps to Reproduce

Visit druid hut
Druid spawners and structure itself is generated without issues
Chests that should contain loot are empty

### What You Expected

Usual loot table with food and useful early game stuff

### What Happened Instead

3 empty chests without any loot

### Additional Details

Another player found a druid hut that had loot, but only in 1/3 of the chests.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Sleepy-Horse** [comment]
2372692034780807487
/tp 293.50 2.00 19173.94

TF version is 05818c455ebdc475e80c8d07be232c4e42873533
