### ISSUE TITLE
Portal refuses to activate despite parameters being met, magiculture 2 modpack, 1.12.2

### ISSUE THREAD

**Issue by StonedGoat** [TeamTwilight/twilightforest#2271]
### NeoForge Version

Forge (notneo) Version 14.23.5.2860

### Twilight Forest Version

3.11.1021-universal

### Client Log

https://gist.github.com/StonedGoat/d6de6feb03913a8310c07708603193d0

### Crash Report (if applicable)

N/A

### Steps to Reproduce

Step 1. Assemble Portal
Step 2. Drop Diamonds in water
Step 3. Portal doesn't activate?

### What You Expected

The portal to activate upon throwing diamonds into the water

### What Happened Instead

The portal did NOT activate and is not working for anyone.

### Additional Details

I will note that Optifine is not the cause here, as my friend (who I am reporting in their stead because they're anxious af) removed optifine and tried again without it on, and it did not work still.

However, _I_ do have optifine on, but given the fact it's clearly not the cause, I'm assuming it's fine to have it active when sending the latest.log. 
I threw diamonds into the would-be portal shortly before copying the file, so it should be near the end of it for convenience.

I don't really know what could be causing it to not work. We're playing on the magiculture 2 modpack, albeit with a couple small additions. Like, literally no more than maybe 10 mods, though I don't think they're related but I can try to provide them if it's any help.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
Since you have reported this issue on a modpack, I would check to see if the modpack has configured the portal to accept a different portal activator.

**Comment by StonedGoat** [comment]
oh wow that was lightning fast, where would i check that? is that like in a config file?

**Comment by Andromander** [comment]
1.12.2, so it should be in the config.

**Comment by StonedGoat** [comment]
aahhh i think i might've found it, lemme test rq

**Comment by StonedGoat** [comment]
okay well TIL that there's a config to change the activation item, neat.

problem resolved, item was something friend in question had access to and was tossed in, worked instantly!

ty tytytytytyyyy
