### ISSUE TITLE
Biome-blending cannot be disabled for dark leaves

### ISSUE THREAD

**Issue by Lolothepro** [TeamTwilight/twilightforest#2273]
### NeoForge Version

21.1.64

### Twilight Forest Version

4.6.2790

### Client Log

https://mclo.gs/Az2icCw

### Steps to Reproduce

Go to the border between the “dark_forest” biome and the “dark_forest_center” biome
Press Esc
Go to video settings and set “Biome Blending” to “Off”.

### What You Expected

No biome-blending

### What Happened Instead

The color of the leaves is still blended

### Additional Details

![2024-09-29_12 03 32](https://github.com/user-attachments/assets/44b68ccc-9088-47b2-8cf8-25a595dd54f4)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
This appears to be how Dark Leaves - and to this extent, Giant Leaves - are tinted.

Long story short: the blend radius setting is working.

Short story long: It works, but only if we just got the average foliage colour and called it a day. Instead, an average is picked from a small radius around the block itself. That basically means blending is always present, but if "disabled", the blending is only slightly less so than if it were enabled. It appears to be a 1-block radius from the center, so an average of all the foliage colour in a 3x3 area.
As for why, I can't really explain it, tbh. Someone else that may have ported the mod to 1.12 might know.

No Biome Blending:
![2024-10-12_21 52 47](https://github.com/user-attachments/assets/895f62f1-37af-4b88-bc7b-b99fae521acc)

Normal Biome Blending:
![2024-10-12_21 52 56](https://github.com/user-attachments/assets/a87ef67b-3dd2-46c6-8655-534db39ee224)

**Comment by GizmoTheMoonPig** [comment]
I went all the way back to 1.12 to check this out and apparently our code is just a copy-paste job of how `BiomeColorHelper.getColorAtPos` used to work. I dont see any need for us to keep doing what we're doing when we can just use vanilla's methods for blending. I'll be fixing this soon

**Comment by GizmoTheMoonPig** [comment]
also worth noting this affects every single one of our leaves, not just dark
