### ISSUE TITLE
Crashing when loading the world

### ISSUE THREAD

**Issue by DKLYNTLY** [TeamTwilight/twilightforest#2276]
### NeoForge Version

forge 36.2.24

### Twilight Forest Version

4.0.870

### Crash Report (if applicable)

https://gist.github.com/DarklyNightly/1dca5c553003c0277a0181b0b398e1f2

### Steps to Reproduce

install modded oneblock skyblock latest version of the modpack

### What You Expected

load into the world

### What Happened Instead

crash when rendering something

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
1.16 is no longer supported.
