### ISSUE TITLE
Going through portal just generates another one in the overworld 1.19.2

### ISSUE THREAD

**Issue by asstaIDST** [TeamTwilight/twilightforest#2277]
### NeoForge Version

Forge 43.4.2

### Twilight Forest Version

1.19.2

### Steps to Reproduce

1. The portal successfully spawns into the game after throwing a diamond
2. I jump in the portal, and go through one loading world screen, followed by a quick flash and another loading screen with the portal audio resetting,
3. I spawn back into the main world 70 ish blocks away with a second twilight portal spawned next to me covered by 4 dirt blocks

### What You Expected

I was expecting to load into the Twilight forest

### What Happened Instead

I respawn into the main world 70 blocks away with a 2nd twilight portal

### Additional Details

Using Immersive portals along with this, and oculus as  shaders

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
1.19.2 is very old and very buggy. It is not supported.
