### ISSUE TITLE
Kicked from server for failure to encode when creating Magic maps 

### ISSUE THREAD

**Issue by tisStrangeStuff** [TeamTwilight/twilightforest#2280]
### NeoForge Version

21.1.61

### Twilight Forest Version

4.6.2790

### Client Log

https://gist.github.com/tisStrangeStuff/180696fb47712fd2e0b9cb158ed66c2b

### Steps to Reproduce

Obtain any form of magic map, right click to create the map.

### What You Expected

The map is supposed to render

### What Happened Instead

The game freezes momentarily then I am kicked from the server

### Additional Details

Server Log: https://gist.github.com/tisStrangeStuff/c16dd49d31bdde8a207026141e52e6ec

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by tisStrangeStuff** [comment]
Deleted moonlight lib, fixed. this mod is not compatible with moonlight lib.

**Comment by GizmoTheMoonPig** [comment]
if moonlight is causing this, make sure theyre aware of the issue please
