### ISSUE TITLE
[Suggestion] Config option to toggle tfEnforcedProgression gamerule

### ISSUE THREAD

**Issue by charleadev** [TeamTwilight/twilightforest#2282]
### The Suggestion

I made this suggestion in the discord server but I'm just posting it here as a reference :3

I haven't played the modern versions of the mod so I'm unaware of this is already a thing/the progression isn't as linear as it was in 1.7.10, but a config option to manually disable the progression system would be terrific.

### Why Should It Be in the Mod?

Some players don't like being forced through a linear progression system in an open-world game, but the only way to disable this is to turn the gamerule off in a world with cheats enabled.

### Please Read and Confirm the Following

- [x] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
This is not exactly the case, gamerules are generally intended to be modified when creating a world. We have decided that it was more suitable as a gamerule.
