### ISSUE TITLE
Hydra, Winter Wolf, Fire Beetle, and Snow Queen breath attacks deal no damage

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#229]
Forge version: 14.23.0.2512
Twilight Forest version: Release 3.1.128

Steps to reproduce:
1. Bathe in the Hydra's fire breath (not fireballs)

What I expected to happen:
Receive damage from fire and set alight

What happened instead:
The fire breath does nothing

**Comment by Sonicwave** [comment]
This also applies to the Fire Breath attack of Fire beetles.

**Comment by Terrakota-d** [comment]
Winter Wolf also does not cause damage with his breath.
