### ISSUE TITLE
Missing Registry When Loading Twilight Forest

### ISSUE THREAD

**Issue by EukaryoteofDreams** [TeamTwilight/twilightforest#2295]
### NeoForge Version

47.3.0 (Forge)

### Twilight Forest Version

4.3.2508

### Client Log

https://gist.github.com/EukaryoteofDreams/7823ca4bffab935a0bce5cc930982ccd#file-latest-log

### Crash Report (if applicable)

https://gist.github.com/EukaryoteofDreams/2314c8e1f9a2e2bdb920d8a938ff3aaa#file-gistfile1-txt

### Steps to Reproduce

1. Add twilight forest mod to mods folder after downloading appropriate version.
2. Start up minecraft from launcher.
3. Load into forge launcher (Ver 47.3.0) and check for mod to work properly.
4. Load into single player world where the mod is loaded, and everything works.
5. Load into server where the registry error is then encountered.

### What You Expected

I expected the mod to load along with other mods installed and there to be no errors.

### What Happened Instead

When I download the mod and load into a single player world, everything works. I even tested the portal to see if the dimension would load and it did. When I try to join my server, I encounter the registry crash error.

### Additional Details

This is the error I'm provided with the the game crashes:
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / twilight:restrictions]
Exit Code:-1

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
This means the version isnt the same on the server and client. Or the mod is missing from the server.

**Comment by EukaryoteofDreams** [comment]
Hmm, does this mean that twilight forest can only be played on a server if it's installed on said server? Both MC client and server versions are 1.20.1. The server is third party and only allows fabric mods to be installed directly. My takeaway is that if what I'm thinking above is correct, I won't be able to use the twilight forest mod on the specific server I chose.

**Comment by Drullkus** [comment]
Correct, the server must have Twilight Forest installed to know about the mod's content, such as its blocks, items, animals, dungeons, etc

**Comment by EukaryoteofDreams** [comment]
Ah, gotcha. Well that solves it then. Thank you both for help. It was greatly appreciated.
