### ISSUE TITLE
[Suggestion] add the missing item rope tag to rope

### ISSUE THREAD

**Issue by ffuentesm** [TeamTwilight/twilightforest#2297]
### The Suggestion

Mod the c:ropes tag from the block to the item section. 
![image](https://github.com/user-attachments/assets/a5406780-3d14-4005-ac50-ee66d196201d)
![image](https://github.com/user-attachments/assets/67ccc22c-5e91-43f0-85bc-9312e2b9c75a)

### Why Should It Be in the Mod?

This will make it in line with other rope items.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
implemented in c84f8c1df924bab3786a808366743228c8dcc4b1
