### ISSUE TITLE
Can't hide uncrafting table in JEI/EMI

### ISSUE THREAD

**Issue by Boshigiri** [TeamTwilight/twilightforest#2298]
### NeoForge Version

21.1.76

### Twilight Forest Version

4.6.2790

### Steps to Reproduce

I disabled uncrafting table in config, but it still show in the JEI/EMI
![QQ截图20241110220441](https://github.com/user-attachments/assets/9f6a43ee-4f45-4d43-9e2c-9e0d58d1743a)

### What You Expected

In past version 1.20.1, it will be hide correctly

### What Happened Instead

Pass

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jodlodi** [comment]
fixed in b50221db26f9289d0212895d8973570722d96663
