### ISSUE TITLE
Boss healthbar displays as "entity.twilightforest:(bossname).name

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#230]
Forge version: 14.23.0.2512 (1.12.2)
Twilight Forest version: 3.1.128

Steps to reproduce:
1. Spawn a Hydra, Lich or Ur-ghast using a spawn egg.

**Comment by Andromander** [comment]
I believe this was fixed in a dev build, but I don't remember which one

**Comment by Sonicwave** [comment]
Ah yes it's been fixed as of 3.1.136, my bad
