### ISSUE TITLE
Fix Tree Root Problems

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#2304]
1.) Pull the Canopy tree trunk downwards by one block maximum if it is exposed to air.
2.) Fix Mangrove tree surface root origin point to be above the water.
3.) Fix Robust Twilight Oak tree surface roots being lower/just different than they should be.
4.) Fix Robust Twilight Oak tree surface roots not always turning into logs if exposed to air.

**Comment by jodlodi** [comment]
Fixd
