### ISSUE TITLE
[Suggestion] Music Discs Tag

### ISSUE THREAD

**Issue by TheBedrockMaster** [TeamTwilight/twilightforest#2306]
### The Suggestion

Add the `c:music_discs` item tag to Music Discs from the mod.

### Why Should It Be in the Mod?

The item tag can be used to group the music discs from this mod with the music discs from Minecraft and other mods.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by jodlodi** [comment]
implemented in ee15cfe929194b70ece226ef53e2f2381c2ab01d
