### ISSUE TITLE
Firefly Particle Spawner Breaking Overlay

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#2310]
### NeoForge Version

21.1.66

### Twilight Forest Version

4.6.2856

### Steps to Reproduce

Try to break a Firefly particle Spawner.

### What You Expected

The breaking overlay to confirm to the shape of the jar.

### What Happened Instead

![image](https://github.com/user-attachments/assets/16a2ac3c-711a-4fb8-884d-e80b33c99530)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
cant be fixed without changing the model, which I dont intend on doing
