### ISSUE TITLE
[Bug Report/Suggestion] Replace Fire Beetle loot table

### ISSUE THREAD

**Issue by Cicopath** [TeamTwilight/twilightforest#2315]
### NeoForge Version

N/A

### Twilight Forest Version

4.3.2508

### Steps to Reproduce

1. Install Twilight Forest and EMI Loot.
2. Create a new world with the two mods installed.
3. Look at the Fire Beetle's drops in the EMI menu.

### What You Expected

I expected `twilightforest:fire_beetle` to have its own unique loot table.

### What Happened Instead

It instead uses the vanilla Creeper's loot table. [See here](https://github.com/TeamTwilight/twilightforest/blob/1.21.x/src/generated/resources/data/twilightforest/loot_table/entities/fire_beetle.json/#L9).

### Additional Details

This causes non-game crashing issues with mods. For example, EMI Loot is a mod which provides the details of what a mob drops. Because `twilightforest:fire_beetle` literally takes the Creeper's loot table, EMI Loot shows that this mob drops a Creeper Head.

Furthermore, it's simply better practice to give the Fire Beetle its own unique table rather than using another mob's loot table because of issues like these.

I would put in my own pull request, but since it's under `generated/resources`, I can't fix it "by hand."

![image](https://github.com/user-attachments/assets/6fee54e8-3c86-42f0-bded-26ec3e3493e7)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Cicopath** [comment]
I just realized that this also applied to other entities as well, such as Carminite Ghasts. Although it makes sense to use the Ghast's loot table for that entity, it's still a bit funky not to create their own unique loot tables since, today, mods can be easily configured by players and modpack developers through datapacks, no?

**Comment by Toastr125** [comment]
> I just realized that this also applied to other entities as well, such as Carminite Ghasts. Although it makes sense to use the Ghast's loot table for that entity, it's still a bit funky not to create their own unique loot tables since, today, mods can be easily configured by players and modpack developers through datapacks, no?

TBF, it makes a lot more sense for those since they are literally a variant of the vanilla mob, as opposed to the fire beetles being completely unrelated to creepers aside from being intended to have gunpowder as their drop.
Additionally, the twilight forest mobs in question still do have their own loot tables and can thus be datapack configured individually. It's just that, by default, those loot tables simply roll another loot table.

**Comment by Andromander** [comment]
Only an observation, EMI noting that the Fire Beetle can drop a Creeper Head might actually be the mod itself doing this. The Creeper loot table doesn't mention the Creeper Head and is hardcoded into the Creeper to drop the Head if possible. That being said, it's probable that Fire Beetles may drop a Music Disc.
Still, this may have been a remnant of yonder days, where reusing mob drops from other entities was more efficient than making new drops and mob heads weren't a thing. 

Edit: Yes, Fire Beetles can drop Music Discs.
