### ISSUE TITLE
Structure names don't auto-complete with /locate

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#232]
Not really a big thing, but it would be nice if rare structures (such as Dark towers) could be detectable by the /locate command.

**Comment by Andromander** [comment]
It should be possible, however, the locate feature requires the `twilightforest:` prefix on the structure names for it to work, since the locate feature defaults it to `minecraft:`

**Comment by Sonicwave** [comment]
Ah it does work (at least "/locate twilightforest:dark_tower"), however none of them show up in the TAB list for some reason (unlike entities or blocks). Not sure if that's an issue with the /locate command itself instead of the mod.

**Comment by Andromander** [comment]
The TAB list is hard-coded into Minecraft itself, which makes it inaccessible to modify. There may be a way to modify the list, but that's as far as I know

**Comment by Tamaized** [comment]
Yea the Tab autocompletion is a hardcoded array placed right into the method's return, there's no way to modify it as far as i can tell.

The `twilightforest:` was just something I decided to add to avoid possible conflicts however I don't feel it's actually necessary and I can remove that if needed.

**Comment by Sonicwave** [comment]
Ok that makes sense.

**Comment by bs2609** [comment]
There was a Forge issue opened about this here: https://github.com/MinecraftForge/MinecraftForge/issues/3932

**Comment by Andromander** [comment]
Issue appears to be resolved, structures are appearing when tab-completed (this is also on top of the command system being different from before, so tab just goes through a list these days).
