### ISSUE TITLE
Emperor's Cloth crafting recipe always shows in recipe viewer despite recipe being removed

### ISSUE THREAD

**Issue by Partonetrain** [TeamTwilight/twilightforest#2320]
### NeoForge Version

21.1.89

### Twilight Forest Version

1.21.1-4.6.9

### Steps to Reproduce

1. Remove `emperors_cloth_recipe` via datapack
2. Press 'u' over Emperor's Cloth with JEI or EMI 
3. Observe

### What You Expected

Recipe to not show in recipe viewer, confirming it was removed

### What Happened Instead

Recipe remained in recipe viewer, even though it doesn't function in an actual crafting table

### Additional Details

Recipe can be removed with a datapack by replacing it with the following:
```
{
  "neoforge:conditions": [
    {
      "type": "neoforge:false"
    }
  ],
  "type": "minecraft:crafting",
  "category": "misc"
}
```
I've also tried CraftTweaker, but strangely the recipetype does not appear in the recipetype dump command

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This is because recipe viewers use a special category to show this that isnt based on the recipe. This is a special recipe type, like cloning a map or creating firework stars, so its not normally shown in things like JEI or EMI. I'll see if I can do anything about making it conditionally show based on that recipe

**Comment by GizmoTheMoonPig** [comment]
fix was also applied to the moonworm queen display since that had the same issue, will be fixed next update
