### ISSUE TITLE
Unstable Ice Core creates glitched blocks when mobGriefing is false

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#234]
Forge version: 14.23.0.2512
Twilight Forest version: 3.1.136

Some mobs will break/change blocks even when gamerule _mobGriefing_ is set to false. So far this seems to affect Nagas, Hydras and Unstable Ice cores; ghasts aren't affected.

**Comment by Sonicwave** [comment]
The Unstable Ice Core still destroys/changes blocks with _mobGriefing_ false (in 3.2.157), but they seem to be the glitched blocks that revert when you right-click on them (or relog) and cause you to get stuck if you fall onto them. (I should clarify that this was the same behavior for them in 3.1.136; bosses destroying blocks are indeed fixed)

**Comment by Tamaized** [comment]
fixed in d05b30db72f3226af325f70cf815ea0a4fbd6e74
