### ISSUE TITLE
New portals are created in the wrong places

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#235]
Forge version: 2512
Twilight Forest version: 3.1.1, 136

Something strange happened to me. I created a new superflat world, made a portal and appeared in the arena Naga. Some time later I created another portal in the Overworld and found himself directly in the hollow hill.  Even if it's not a bug, I don't think that portals should emerge in the structures.

Seed of the first (6523966656122967062) and second (2682322816311212132) world

https://www.dropbox.com/s/id3o3oyb0m4s782/2017-10-14_21.03.07.png?dl=0
https://www.dropbox.com/s/ukdcjjud01fi94q/2017-10-14_21.02.22.png?dl=0
https://www.dropbox.com/s/615bqp82b8zyeel/2017-10-14_21.34.59.png?dl=0
https://www.dropbox.com/s/hie1kwiacmprd2m/2017-10-14_21.35.15.png?dl=0

**Comment by Tamaized** [comment]
related to #205
