### ISSUE TITLE
Unnecessary advancements

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#236]
Forge version: 2512
Twilight Forest version: 3.1.1, 136

Steps to reproduce:
1. Create a new portal in the Twilight Forest and enter it.

What I expected to happen: Only need advancement

What happened instead: https://www.dropbox.com/s/tl85xlso8mwfhfh/2017-10-14_22.58.40.png?dl=0

**Comment by Tamaized** [comment]
Image link is broken, you can upload images directly to github (just drag it in)

**Comment by Terrakota-d** [comment]
Oh, sorry.
