### ISSUE TITLE
TESR Trophy Renderers break advancement icons

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#237]
:thonk:

<img width="637" alt="screen shot 2017-10-14 at 2 49 04 pm" src="https://user-images.githubusercontent.com/5010174/31579640-087e2a70-b0ef-11e7-9902-468cb8f1a015.png">

**Comment by williewillus** [comment]
i think this is a forge/vanilla bug, try using a chest and seeing if it happens?

**Comment by Drullkus** [comment]
Does not look like it.

<img width="824" alt="screen shot 2017-10-14 at 5 55 46 pm" src="https://user-images.githubusercontent.com/5010174/31580575-ee58c618-b108-11e7-9f41-7d210ec8d470.png">

**Comment by Tamaized** [comment]
perhaps theres a gl leak in the tesr render

**Comment by Drullkus** [comment]
Seems though that the vanilla Skull IS broken, but only on its own tab.

<img width="618" alt="screen shot 2017-10-14 at 5 59 22 pm" src="https://user-images.githubusercontent.com/5010174/31580590-6b53332e-b109-11e7-818a-ae943275ed59.png">

**Comment by Drullkus** [comment]
Was missing a `enableCull`.
