### ISSUE TITLE
Hydra, Winter Wolf and Fire Beetle's breath do no damage.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#238]
Forge version: 2501
Twilight Forest version: 3.1.139
Link to crash log: Not a crash
Steps to reproduce:
1. Fighting against them.

What I expected to happen:Their breath does damage.

What happened instead:but they don't.

**Comment by Tamaized** [comment]
#229

**Comment by Tamaized** [comment]
Gonna close this one since it's a dupe of the other
