### ISSUE TITLE
Redcap boots don't render

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#240]
Forge version: 14.23.0.2512
Twilight Forest version:  3.1.136

Steps to reproduce:
1. Spawn Redcap Goblin or Redcap Sapper with a spawn egg

What I expected to happen:
They are wearing their boots

What happened instead:
Someone's already nicked their boots. Also they have a stumpy leg

**Comment by williewillus** [comment]
the code gives them their boots, but they're just not being rendered properly
