### ISSUE TITLE
Winter Wolf and Mistwolf have unrealistically small shadows

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#242]
Forge version: 14.23.0.2512
Twilight Forest version: 3.1.136

Steps to reproduce:
1. Spawn a Mistwolf or Winter Wolf

What I expected to happen:
Their shadows match the size of the mob

What happened instead:
Super small shadows
![2017-10-16_07 41 00](https://user-images.githubusercontent.com/29526717/31589502-e43376b8-b245-11e7-96b1-51f76fdef4cc.png)
![2017-10-16_07 41 09](https://user-images.githubusercontent.com/29526717/31589505-e780a3cc-b245-11e7-89df-916840185c8a.png)

**Comment by williewillus** [comment]
redirect to #272
