### ISSUE TITLE
StackOverflowError with LichBomb

### ISSUE THREAD

**Issue by phit** [TeamTwilight/twilightforest#249]
Forge version: forge-1.12.2-14.23.0.2512
Twilight Forest version: 1.12.2-3.1.128
Link to crash log: https://gist.github.com/phit/2349bd8317fe7ebbaeb7445a5b876ec5

Steps to reproduce:
1. no clue, supposedly something with the lich boss, also maybe related to spongeforge

to quote the player: "soo i was in the twilight forest castle thing and the lich spawned and the server crashed - sorry if that was me! v.v"

**Comment by williewillus** [comment]
couldn't get it to happen locally but whatever the fix is simple

**Comment by phit** [comment]
just tested with the dev build (1.12.2-3.1.151), did indeed fix it! thanks
