### ISSUE TITLE
The amount of Experiment 115 does not change when the player places the first one on the ground.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#250]
Forge version: 2501
Twilight Forest version: 3.1.149

Steps to reproduce:
1. Placing a experiment 115 on the ground.(I had 14 in my hand)

What I expected to happen:14-13

What happened instead:It didn't change.

**Comment by Drullkus** [comment]
Were you in Creative mode?

**Comment by Drullkus** [comment]
I tried it, it works as expected. What are you trying to do?

**Comment by AppDat** [comment]
Place it on the ground.

**Comment by Drullkus** [comment]
Works fine for me

![exp115](https://user-images.githubusercontent.com/5010174/31695274-87de4464-b35e-11e7-87a9-37883e18f562.gif)

**Comment by Tamaized** [comment]
It's valid, the first placement doesn't decrease the stacksize

**Comment by Drullkus** [comment]
:man_facepalming: Did not see that
