### ISSUE TITLE
Shift can't work probably while using uncrafting table.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#251]
Forge version: 2501
Twilight Forest version: 3.1.149
Link to crash log: (please use a paste site, do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Crafting 64 wood planks pressing shift.

What I expected to happen: It will craft 64.

What happened instead: It only craft 4. I clicked 16 times to finish the crafting.

**Comment by williewillus** [comment]
Probably this lol https://github.com/TeamTwilight/twilightforest/blob/a2252a9148f7be3f9ee4fc244795838c92dada57/src/main/java/twilightforest/inventory/ContainerTFUncrafting.java#L428-L437
