### ISSUE TITLE
Yeti armor UV's are messed up

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#26]
![bugged yeti helmet render](https://user-images.githubusercontent.com/29523364/27263958-f7a57b3a-5429-11e7-8619-f7f703f6f538.png)
TF version 2.4.0.4
Forge version 13.20.0.2260

**Comment by williewillus** [comment]
What it should look like (the chestplate, legs are all out of wack)

![2017-06-18_16 32 49](https://user-images.githubusercontent.com/2015032/27264529-0c7bf5f4-5446-11e7-9457-c41600d58633.png)
