### ISSUE TITLE
Wrong icon advancement

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#260]
Forge version: 2512
Twilight Forest version: 3.2.1, 156
Link to crash log:

Steps to reproduce:
1. Open menu advancements

What I expected to happen: Advancement "Consumate Baaahs" will have icon challenge.

What happened instead: This is not

**Comment by Drullkus** [comment]
I don't think it's needed

**Comment by Terrakota-d** [comment]
Sorry, didn't know this was an intentional change  ,-,
