### ISSUE TITLE
Possible improvement new material blocks

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#261]
Forge version: 2512
Twilight Forest version: 3.2.1, 156

Block of Arctic Fur
1. Сrafted from four Arctic Fur as wool
2. Breaks shears and makes a sound wool in the destruction

Block of Steeleaf
 Also Breaks shears and makes a sound leaves

**Comment by Killer-Demon** [comment]
Feature was implemented with e0fc12d87ab8d4e4617d83332bc9f112952366a7.
The following blocks with their own special properties were added:
- Block of Ironwood
- Block of Fiery Metal
- Block of Steeleaf
- Block of Arctic Fur

Thank you for your suggestion.
