### ISSUE TITLE
Twilight Lich does not lose one of it's shield when it falls from a high place.(It does in 1.7.10)

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#262]
Forge version: 2501
Twilight Forest version: 3.2.155

Steps to reproduce:
1. Let Lich fall from a high place.

What I expected to happen: It will lose one of it's shield.

What happened instead: But it won't.

**Comment by Killer-Demon** [comment]
As far as I'm concerned fall damage is not supposed to break a shield, only magic sources such as the Scepter of Twilight are.

**Comment by Tamaized** [comment]
It's intended to only lose a shield when he takes magic damage (the bolt he fires for example) if fall damage worked in 1.7 then that was a bug which seems to be fixed now.
