### ISSUE TITLE
Animated textures fof Carminite and Fiery blocks

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#265]
Forge version: 2512
Twilight Forest version: 3.2.1, 156

Carminite Block could have animated texture of a swirling vortex and Fiery block shimmering texture as the rest of the fiery items. It would be fascinating :3

**Comment by Tamaized** [comment]
We could totally fullbright the fiery with ctm too

**Comment by Drullkus** [comment]
I don't feel like investing myself into animation for the Carminite block and the animation for Fiery Block would be weird.

Fiery block has Fulbright on both layers, but one of the is broken and is pending fix on CTM side by @tterrag1098
