### ISSUE TITLE
(Suggestion) Add Towerwood Shield.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#267]
Forge version: 2501
Twilight Forest version: 3.2.170

**Comment by Zarafa04** [comment]
there not updating 1.7.10 anymore this suggestion would be good in 1.12.2 with the offhand

**Comment by Zarafa04** [comment]
oops i missed that your talking about 1.12.2

**Comment by Killer-Demon** [comment]
This niche should be filled by the Knightly Shield, which can be crafted with Towerwood and several other materials.
