### ISSUE TITLE
Add custom sounds for all mobs

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#269]
Many mobs don't have sounds except for reusing player sounds when hurt, which sounds a bit strange. This includes Yetis, Death Tomes, Penguins, Goblin Knights, Mosquitos, Cave Trolls, and the passive/ambient animals such as squirrels. Forest bunnies could simply reuse vanilla rabbit sounds.

**Comment by Tamaized** [comment]
Renaming this so we can include the other issue among any others related to custom sounds for TF mobs

**Comment by bs2609** [comment]
Also worth noting the subtitles for vanilla sounds are hardcoded to their respective entity names.

**Comment by Killer-Demon** [comment]
This has been completed aside from a few bosses which would be better suited to be combined with their respective reworks. All animals now have custom sounds as well as practically all mobs that needed them.
