### ISSUE TITLE
Crash when using the Uncrafting Table

### ISSUE THREAD

**Issue by vos6434** [TeamTwilight/twilightforest#27]
Twilight Forest: 2.4.0.4
Forge: 13.20.0.2315
Crash: https://pastebin.com/1bAMxLv8

**Comment by ruairidh74** [comment]
Same here. Crashed when placing an item into the table.
Twilight Forest: 2.4.0.4
Forge: 13.20.0.2228
Crash Report: 
[crash-2017-06-18_21.32.40-client.txt](https://github.com/TeamTwilight/twilightforest/files/1083354/crash-2017-06-18_21.32.40-client.txt)
