### ISSUE TITLE
Mossy Mazestone Brick does not generate

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#273]
Forge version: 14.23.0.2512
Twilight Forest version: 3.2.167

Steps to reproduce:
1. Find a Labyrinth
2. Find a Mossy Mazestone Brick block in the Labyrinth

What I expected to happen:
The Mossy Mazestone Brick blocks generate similarly to the Cracked Mazestone Brick.

What happened instead:
It cannot be found. I'm not too sure if this is intentional or not, but the block exists, yet it doesn't generate with the structure

**Comment by Drullkus** [comment]
Partially fixed by allowing them to be obtained via Chisel's chisel tool - we'll come back to this, we have bigger plans

**Comment by Drullkus** [comment]
We'll just cover this in structure overhaul

**Comment by bs2609** [comment]
Fixed via bec08e92e3ceda41c9d4b96ce3d3bb9e99fff954.

![2019-05-27_20 57 58](https://user-images.githubusercontent.com/1447117/58437789-80d60b00-80c3-11e9-9fd4-35103c04b445.png)
