### ISSUE TITLE
Twilight Lich sinks in water and walks around normally as if on land

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#274]
Forge version: 14.23.0.2512
Twilight Forest version: 3.2.171

When you spawn a Twilight Lich in water, it sinks to the bottom instead of floating (causing drowning damage). It also walks and jumps normally as if on land.

**Comment by Drullkus** [comment]
:thonk:

**Comment by Sonicwave** [comment]
Might have to do with these lines of code in EntityTfLich.java (line 153)

```@Override
	public boolean isInLava() {
		return false;
	}

	@Override
	public boolean isInWater() {
		return false;
	}
```

**Comment by Drullkus** [comment]
Fixed your embedded code block

**Comment by williewillus** [comment]
Also doesn't have a swimming SO task

**Comment by williewillus** [comment]
*AI
