### ISSUE TITLE
Knightly Axe tooltip contains error

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#275]
Forge version: 2512
Twilight Forest version: 3.2.1, 171

Steps to reproduce:
1. Get Knightly Axe

What I expected to happen: It's deals extra damage to armored targets as the rest of the knightly weapons and hint will reflect this.

What happened instead: The tooltip says "unarmored targets" although it is not.

**Comment by Tamaized** [comment]
Looks like it actually is supposed to be unarmored however the code isn't there in the current version but here it is in the 1.7 source
https://github.com/TeamTwilight/twilightforest/blob/1.7.10/src/main/java/twilightforest/item/ItemTFKnightlyAxe.java#L67-L78

**Comment by Terrakota-d** [comment]
I think it would be logical that Knightly Axe will deals extra damage to armored enemies similar other weapons. It is strange that Knightly Axe didn't do this from the beginning.
