### ISSUE TITLE
Hydra do not follow the 1.9+ damage fomula.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#278]
Forge version: 2501
Twilight Forest version: 3.2.177

Steps to reproduce:
1. Hit a Hydra head using a 40 attack sword or a 80 attack sword.

What I expected to happen: The 80 attack one will do less hit times than half of the 40 attack one because attack damage can reduce the effect of armor points.

What happened instead: The 80 attack one hit 13 times and the 40 attack one hits 25 times.

**Comment by Tamaized** [comment]
The Hydra does nothing special except dividing the damage by 8.
https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/entity/boss/EntityTFHydra.java#L608

Perhaps you hit the head with the 40 attack?

**Comment by AppDat** [comment]
Yes. The glass sword.

**Comment by Tamaized** [comment]
Actually it seems the damage dealt to the hydra changes when hitting a head depending if the head mouth is open or not
https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/entity/boss/EntityTFHydra.java#L637-L642

Is this actually an issue then?

**Comment by AppDat** [comment]
I hit the hydra only the mouth is closed
.

**Comment by AppDat** [comment]
So the damage does not follow the 1.9+ armor rule is on purpose. In order to prevent player from hitting the body using high attack weapons?

**Comment by Tamaized** [comment]
I'm not even sure what this rule is, we delegate the damage to the super call. Everything else is handled by vanilla.

**Comment by williewillus** [comment]
I think what's meant is that the damage values haven't been rebalanced to account for armor getting nerfed overall in 1.9

**Comment by williewillus** [comment]
#285
