### ISSUE TITLE
Upper Goblin Knight's special attack damage is too high.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#279]
Forge version: 2501
Twilight Forest version: 3.2.177

Upper Goblin Knight's special attack is 30. It used to be fine in 1.7.10 and only does 12 damage to a full iron armor player. But because of the 1.9+ damage formula, it's damage is able to do 19 damage to a full firey armor player, enough to kill that player if it's health is not full.

**Comment by williewillus** [comment]
#285
