### ISSUE TITLE
Twilight Arrival Achivement does not have a texture

### ISSUE THREAD

**Issue by vos6434** [TeamTwilight/twilightforest#28]
![2017-06-18_22 03 21](https://user-images.githubusercontent.com/21976486/27264243-45545836-5472-11e7-9075-597dfa643178.png)
Twilight Forest: 2.4.0.5
Forge: 13.20.0.2315

**Comment by williewillus** [comment]
it used to use the portal icon but the portals no longer have an item form. We should just switch it to some other item that is representative of the entire mod
