### ISSUE TITLE
Naga Outside the court yard area where you find him.

### ISSUE THREAD

**Issue by bob0bob** [TeamTwilight/twilightforest#281]
I have the lastest 1.12.2 version of twilight and I went into it and I was under the impression that the Naga was basically confined to the court yard.  I was unable to kill and decided to retreat and come back.

Two things.  One I was not going to say really anything about, was the tinkers construct 2 weapon have a hard time for the hit box on the creature.  I can be ran over and it doesn't get hit.

Mainly,  Naga is following me throughout the twilight forest.   It is not restricted to the court yard.  Here is a  picture.

I'm in a tree getting a way from him,  he will not quit.

![2017-10-22_23 35 42](https://user-images.githubusercontent.com/30982580/31872542-6c3fdd08-b782-11e7-83b7-c5fa3a80b24f.png)

**Comment by Tamaized** [comment]
As for the hitbox issue, it used to be like a 16 block range from the head for when it could hit you but I decreased that down to 4 blocks quite some time ago, I didn't have much issue with that value.

**Comment by AppDat** [comment]
I think the natural Naga outside the court yard is unable to be hit.

**Comment by Tamaized** [comment]
Correct, there's code that makes the Naga invulnerable if it is outside its Home range. This existed in 1.7 as well, prob so the Naga can run back to its home without worry.
