### ISSUE TITLE
Minoshroom's head-mushroom fused into his head

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#282]
Forge version: 14.23.0.2512
Twilight Forest version: 3.2.187

The Mushroom texture on the Minoshroom's head is a bit into his head.
![2017-10-23_16 35 56](https://user-images.githubusercontent.com/29526717/31875238-8d2d5ad4-b810-11e7-8db4-32d9e7836be7.png)

**Comment by Drullkus** [comment]
Can confirm this issue occurs, but forgot to report it
