### ISSUE TITLE
[1.12.2] Feature Request: Allow Whitelist for Blocks or Mods for Antibuilder

### ISSUE THREAD

**Issue by Darkosto** [TeamTwilight/twilightforest#283]
Can you please look into adding a whitelist of some type to allow pack devs to give certain block ID's or even mods the ability to ignore the antibuilder mechanics. Specifically, any gravestone mods that will have their inventory deleted when a player dies (from falling creepers). It would probably help alleviate some frustration on the player's end :P 

Thanks!
Darkosto

**Comment by Drullkus** [comment]
@Tamaized not only that but also check out how it breaks the blocks. Apparently it breaks bedrock
