### ISSUE TITLE
(Suggestion) The ability to plant plants Twilight Forest in a flower pot.

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#286]
Forge version: 2515
Twilight Forest version: build 187

**Comment by Shadows-of-Fire** [comment]
Plants does this, as well as for a few other mods

**Comment by Drullkus** [comment]
Check out his mod, it does this. https://minecraft.curseforge.com/projects/plants

**Comment by Terrakota-d** [comment]
Okay, thanks)

**Comment by Terrakota-d** [comment]
But is it possible to integrate this feature in Twilight Forest apart from other mods?

**Comment by Tamaized** [comment]
It's not worth it, we'd have to replace the flowerpot with our own and Plants already does this, would just cause incompatibility.

**Comment by Drullkus** [comment]
What Tam said. I’d rather a stand-alone mod make this potentially incompatible change than include it in Twilight Forest as part of its package. That’s bad design.

**Comment by bogger33** [comment]
sounds like forge needs a flower pot capability

**Comment by williewillus** [comment]
This will be easy to do in 1.13 so let's just wait till then
