### ISSUE TITLE
Improvement Giant's Sword

### ISSUE THREAD

**Issue by Terrakota-d** [TeamTwilight/twilightforest#287]
Forge version: 2515
Twilight Forest version: the build 187

Possible as Giant's Pickaxe, Giant's Sword could have the unique ability, for example a large attack range. Even with recent changes it's still quite situational.

**Comment by AppDat** [comment]
I haven't seen any mod that can make weapon has long attack range. The giant sword in mods like Orespawn only shoots invisible entity so it looks like "long range".

**Comment by Terrakota-d** [comment]
I don't know about the sword from Orespawn but it's a pretty interesting idea.

**Comment by egogowa** [comment]
◡‿◡
