### ISSUE TITLE
Investigate Weird unprotected Lich Tower

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#288]
Discovered by @darkosto

![27416e31-3949-4121-8a23-ad9c52eabae7](https://user-images.githubusercontent.com/5010174/32015479-108ba456-b976-11e7-97e0-8963ca807c05.jpeg)

**Comment by Andromander** [comment]
I think I've seen this before. Don't remember what version I was playing, but it may have been 1.7.10 or dev build 1.11.2.

**Comment by Killer-Demon** [comment]
Neither Darkosto nor I could reproduce this issue on the world it happened on.
Closing the issue for being stale, will be reopened and looked into if it comes up again.
