### ISSUE TITLE
Magic and maze maps don't fully work and/or crash

### ISSUE THREAD

**Issue by williewillus** [TeamTwilight/twilightforest#29]
Requires some forge PR's.

**Comment by Benimatic** [comment]
Do we still need custom classes for the MapData? For the maze map, could we store the y-value somewhere like in the NBT for the item itself? For the magic map, the main thing we're storing is alternate MapDecorations, but it seems like there might be a different way here too.

**Comment by williewillus** [comment]
you can't use NBT on the item itself, because multiple itemstacks referring to the same map can co-exist (map cloning, /give, etc.)

**Comment by Benimatic** [comment]
Good point
