### ISSUE TITLE
Silk Touch overrides magic tree metadata

### ISSUE THREAD

**Issue by 666lumberjack** [TeamTwilight/twilightforest#290]
Forge version: 2512
Twilight Forest version: 3.2.155

Steps to reproduce:
1. Grow a Sorting, Miner's or Transformation Tree
2. Mine the logs/core with an axe enchanted with Silk Touch

What I expected to happen:
The correct core/wood for the tree in question would drop

What happened instead:
I received Timewood and a Timewood Clock regardless of which tree I broke the blocks from. This seems to be because these are the default/no-metadata versions of the blocks.

**Comment by Andromander** [comment]
Something else I can see in the issue is harvestable cores. That shouldn't be possible

**Comment by Shadows-of-Fire** [comment]
It's because silk touch is defaultly enabled for all full cubes.  I had this issue with Plants.  It also defaults to some weird drop, which would explain the 0 meta.
