### ISSUE TITLE
(Suggestion) Add something in Final Castle to prevent playerss from passing unfairly.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#291]
Forge version: 2501
Twilight Forest version: 3.2.194

**Comment by Tamaized** [comment]
The Final Castle is WIP, there's not really any "fairness" to be had here if it's not even close to done.

**Comment by AppDat** [comment]
I mean when it's finished. It seems there are no intention of adding this recently.

**Comment by Killer-Demon** [comment]
It has not seen any development aside from some cosmetic blocks and forcefield tweaks.
The Final Castle itself is in almost the exact same state as it was in 1.7.10, saying you seeing that there are no intentions for X recently is odd.
The Final Castle + the final boss are both in the design document, I can assure you they will be the best they can be.

In the future, you don't have make issues about WIP things that aren't relevant or implemented yet.
