### ISSUE TITLE
[Suggestion] Blocks of Fiery Metal sustain fire indefinitely like Netherrack

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#294]
Since Fiery Metal blocks damage mobs on top of it (like magma blocks), and is essentially made of fire anyways, it might be a neat little feature to have.

**Comment by williewillus** [comment]
Seems to already be done by https://github.com/TeamTwilight/twilightforest/commit/3ac77c84922d051ef8c10fed3ec237e41ae4ecd1
