### ISSUE TITLE
Dying from standing on a Fiery Metal block gives death message "Player discovered floor was lava"

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#295]
Forge version: 14.23.0.2512
Twilight Forest version: 3.3.202

Very minor issue, but Fiery Metal blocks seem to be using the same death message as Magma Blocks. This is technically incorrect, since Fiery Blocks are made of fire/metal instead of lava.

**Comment by Drullkus** [comment]
Still gonna keep it, as it's a funny joke on jumping between pieces of furniture to avoid touching the ground.
