### ISSUE TITLE
Command TFFeature has no usage description

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#297]
Forge version: 14.23.0.2512
Twilight Forest version: 3.3.202

Steps to reproduce:
1. Type `/TFFeature`
2. Wait for usage text

What I expected to happen:
There is a description on using the command

What happened instead:
commands.tffeature.usage. Just thought it would be handy for those who don't know what the command does

**Comment by bs2609** [comment]
Fixed by 17e4c4dca0d8aca2b83b757c58169e5f8a96fe89.
