### ISSUE TITLE
Enormous Spruce Trees in Snowy Forest use Spruce and Oak Wood

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#301]
Forge version: 14.23.0.2512
Twilight Forest version: 3.3.203

The largest trees in the Snowy Forest use Spruce wood for Trunks and Oak wood for branches. I have been told this might be a bug. (Image below uses Blue for Spruce and Green for Oak)
![2017-10-27_14 33 40](https://user-images.githubusercontent.com/29526717/32088073-f58ee104-bb23-11e7-9b10-3eade4363369.png)

**Comment by williewillus** [comment]
got a seed/coords I can use instead of running around in the laggy worldgen? :P

**Comment by Andromander** [comment]
Seed: -465569040536298571 around co-ords -471 81 -2486 should be a Snowy Forest
