### ISSUE TITLE
Replace maze map focus with blank maze maps on loot tables

### ISSUE THREAD

**Issue by Benimatic** [TeamTwilight/twilightforest#305]
A QOL change. Like the title says, replace the maze map focus with blank maze maps on minotaur loot tables. Also possibly add them to chests in the labyrinth.

**Comment by EnderiumSmith** [comment]
do they stack?

**Comment by Drullkus** [comment]
Yep, blank ones do.

**Comment by Killer-Demon** [comment]
As per https://github.com/TeamTwilight/twilightforest/commit/c7be118fe64eba6f151edce678ecd95bd635a87c, decided to add the Blank Maze Maps to the chest loot tables of the Maze alongside the focus to still allow players the choice what to use the focus for in crafting.
