### ISSUE TITLE
Block and Chain sometimes acts like shield after throwing it

### ISSUE THREAD

**Issue by Sonicwave** [TeamTwilight/twilightforest#308]
Forge version: 14.23.0.2512
Twilight Forest version: 3.3.205

Sometimes if you throw a Block and Chain, it will start acting like a shield and blocking attacks, but without slowing you down or taking durability damage. Switching to another item seems to fix this.

[Demonstration video](https://youtu.be/z8Fx3NwnQ1w)

**Comment by Tamaized** [comment]
That is weird

**Comment by Drullkus** [comment]
Fixed via e9752dc
