### ISSUE TITLE
Minoshroom maze under hollow hill

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#31]
![maze under hill](https://user-images.githubusercontent.com/29523364/27264556-1dfa7ff4-5436-11e7-8fe5-c3966cb6a1a1.png)
Twilight Forest version 2.4.0.5
Forge version 13.20.0.2260
EDIT: It's structured like the above ground hedge maze
![underground hedge maze](https://user-images.githubusercontent.com/29523364/27264581-7f78f7a6-5436-11e7-9d36-3c59160ec209.png)

**Comment by williewillus** [comment]
is this actually a bug? (not sure if both of them qualify as major structures or not, the HH could be a minor structure)

**Comment by keybounce** [comment]
Somehow, I thought the maze under hollow hills was OLD -- pre 1.7.10, or else removed early in 1.7.10.

I did not know it was still around in 1.11.2
