### ISSUE TITLE
(Suggestion) More structures

### ISSUE THREAD

**Issue by TheLastCookie11** [TeamTwilight/twilightforest#312]
More ruins and structures to explore with maybe an new mob like undead...

**Comment by Tamaized** [comment]
boi

**Comment by TheLastCookie11** [comment]
yes ?

**Comment by Tamaized** [comment]
stop spamming

**Comment by TheLastCookie11** [comment]
ok srry

**Comment by Drullkus** [comment]
Duplicate of #309 and #311 

Please stop posting duplicate issues please, thank you. If you continue I will report to Github

**Comment by TheLastCookie11** [comment]
ok il stop
