### ISSUE TITLE
Hydra cant attack

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#313]
Forge version: 
Twilight Forest version: twilightforest-1.12.2-3.3.202-universal

Steps to reproduce:
See here my bugreport on modern skyblock 2
https://minecraft.curseforge.com/projects/modern-skyblock-2/issues/303

**Comment by Drullkus** [comment]
Are you on a server?

**Comment by phit** [comment]
Yeah this seems to happen when Sponge is on the server, haven't had the time to look into it yet.

**Comment by ghost** [comment]
yeah it is on the a server and yes on sponge >.<

im sorry for the late answer

**Comment by Drullkus** [comment]
Open `config/sponge/global.conf` and set the `max-bounding-box-size` to `6000` or higher, or `0`.

Sponge's default maximum bounding box is too low for the Hydra.

**Comment by ghost** [comment]
It works ty x3
