### ISSUE TITLE
(Suggestion) Make Minoshroom destroys blocks.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#315]
Forge version: 2501
Twilight Forest version: 3.3.202

Minoshroom can easily be killed by any type of scepter because of the wooden cage. It's too weak to be a mini boss.

**Comment by Tamaized** [comment]
I was actually planning on doing this tbh, you can cheese the minoshroom by just breaking only one fence block.

**Comment by bs2609** [comment]
Covered by 6dc85e95d54c7731f27fbb2878da17441f0177a4?

**Comment by Tamaized** [comment]
oh yea, forgot this issue existed.
