### ISSUE TITLE
(Extra Suggestion) Enlarge the detection range of Minoshroom.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#316]
Forge version: 2501
Twilight Forest version: 3.3.202

Players can shoot it to death from the other side of the cage, and it won't respond.

**Comment by Killer-Demon** [comment]
As good as a duplicate of #315
Tama's response would encompass this as well.

**Comment by Tamaized** [comment]
Yea, i'm gonna mess with the AI a bit when I get to the other issue. An enlarged detection radius isn't even needed what-so-ever. Just a simple "aggro when i'm hit" is good enough.
