### ISSUE TITLE
Block and chain can attack the Snow Queen through the ice cloud.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#318]
Forge version: 2501
Twilight Forest version: 3.3.208

Steps to reproduce:
1. Attacking the snow queen through the ice cloud.

What I expected to happen: The cloud will retract back the block.

What happened instead: It hit the snow queen through the ice cloud, this makes the snow queen too easy.

**Comment by Tamaized** [comment]
#1385
