### ISSUE TITLE
Hydra doesn't display properly

### ISSUE THREAD

**Issue by ruairidh74** [TeamTwilight/twilightforest#32]
Twilight Forest: 2.4.0.5
Forge: 13.20.0.2228
The Hydra isn't displaying correctly. When moving around parts of the hydra will disappear and reappear.
![2017-06-18_22 56 12](https://user-images.githubusercontent.com/29524403/27264609-3e09793c-547a-11e7-945d-868b192c4bc1.png)

**Comment by Benimatic** [comment]
Should be fixed in https://github.com/TeamTwilight/twilightforest/commit/88f1c7911abbdda1d88dba34d8d134190e06d550
