### ISSUE TITLE
Armor Rendering issues

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#320]
Forge version: 14.23.5212
Twilight Forest version: 3.3.212

There are two issues I found.
Steps to reproduce:
1. Wear any Helmet Armor (excluding Fiery Helm)
2. Wear any other Fiery Armor piece in any other slot

*AND*

1. Wear Phantom Plate
2. Wear any Legs Armor with an enchantment attached

What I expected to happen:
The armor would render as normal in both instances

What happened instead:
1. Any Helmet Amor is darkened
2. The enchantment effect from the legs is extended to the chest (but not the arms)

**Comment by bs2609** [comment]
Issue 1 should be fixed by f4de33deac3b21283c27b16fceca280bedbff50c.

**Comment by Andromander** [comment]
Both issues appear to be resolved.
