### ISSUE TITLE
[1.7.10] Server Tick Loop Exception Crash

### ISSUE THREAD

**Issue by Whimsyturtle** [TeamTwilight/twilightforest#321]
Forge version: 10.13.4.1614
Twilight Forest version: (this is the build number) 2.3.7
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline) https://pastebin.com/vCSmAKgt

Steps to reproduce:
1. Make a KCauldron Server Environment with the Mod List in the Crash Log

What I expected to happen:
For the server to start up without issues.

What happened instead:
java.lang.NullPointerException: Exception in server tick loop (Crash)

**Comment by danieru-desu** [comment]
Same here https://pastebin.com/wUdsLcLU

**Comment by Andromander** [comment]
I don't think the devs are going to do anything about the issue. 1.7.10 is an outdated version and is no longer supported.

**Comment by williewillus** [comment]
^ try it without kcauldron, failing that do the normal binary search to find the offending mod (remove half the mods, remove half of that, etc.)
