### ISSUE TITLE
Add Uncrafting-specific Recipes, as well as being definable by json

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#324]
The json should be able to let creators to define single input item and its stack size, as well as its output, in shaped or shapeless. In addition to that, the Exp level cost (or actual exp cost, take a pick).

Maybe executable MC functions like Advancements too.

This should allow players to be able to uncraft TF loot that would be otherwise OP to have actual recipes including Glass Swords, Minotaur Axes, etc

Crafttweaker support too

**Comment by williewillus** [comment]
what does shaped vs. shapeless mean in the context of uncrafting? there's only one input slot

**Comment by Drullkus** [comment]
Shapeless output. Do you want the output to be in a shape or just shove the items from an array into the slots?

**Comment by EnderiumSmith** [comment]
it should also allow custom recrafting recipes. i have phantom armor with mending but i can recraft it into fiery armor because it does not have a recipe.

**Comment by GizmoTheMoonPig** [comment]
I didnt realize we had an issue for this. #1401 implements a serializer to make uncrafting-specific recipes. Although it isnt used in any recipes at the moment, it exists for later use or for modpack makers to utilize
