### ISSUE TITLE
1.12.2 ArrayIndexOutOfBoundsException Crash

### ISSUE THREAD

**Issue by imrgr** [TeamTwilight/twilightforest#327]
[crash-2017-11-07_21.27.18-client.txt](https://github.com/TeamTwilight/twilightforest/files/1454351/crash-2017-11-07_21.27.18-client.txt)

Happened a few seconds after the world loaded (10 seconds at the most). There are a number of Blue Castle Runes and Blue shields placed within the loaded chunks. Otherwise, it is a freshly generated world other than some vanilla blocks and the Twilight Forest Portal. I imagine that's what caused it?

I hope this helps.

**Comment by Andromander** [comment]
Crash log seems to be pointing at the Castle Brick Pillar. Does this crash still occur when you reload the world?
