### ISSUE TITLE
Cannot dismount the Pinch Beetle

### ISSUE THREAD

**Issue by StrommKral** [TeamTwilight/twilightforest#333]
Forge version: 
Twilight Forest version: 1.12.1-2.4.0.74
Link to crash log: not a crash

Steps to reproduce:
1. Get picked up by a Pinch Beetle

What I expected to happen: Shift to dismount

What happened instead: Could not dismount bug, had to pour lava on the ground to kill it. teleportation did not work either.

**Comment by Tamaized** [comment]
Not a bug, this is working as intended. You're supposed to kill the beetle.

**Comment by StrommKral** [comment]
was not able to attack it with a draconic sword or a tinkers axe, will try with a normal sword
