### ISSUE TITLE
Crash on entering player generated dimensions

### ISSUE THREAD

**Issue by Setsuna04** [TeamTwilight/twilightforest#337]
Forge version: 1.12.2-14.23.0.2537
Twilight Forest version: 1.12.2-3.3.202
Link to crash log: https://gist.github.com/Setsuna04/ada2a315bd68edb944b22679924becdd

Entering a dimension created by Simple Dimensions generates a client crash when playing on a server. The issue resolves itself when TF isn't present on the server, so it's looking like an issue with TF and not SD. Thanks for the help!

**Comment by Andromander** [comment]
Duplicate of #334

**Comment by Setsuna04** [comment]
Thanks. apologies for the dup; caught the issue a few days ago and didn't recheck the tracker after.
