### ISSUE TITLE
Portal in Naga Arena

### ISSUE THREAD

**Issue by MadToilet** [TeamTwilight/twilightforest#339]
Forge version: forge-1.12.2-14.23.0.2542-universal
Twilight Forest version: twilightforest-1.12.2-3.3.202-universal

Portal was crated in the Naga Arena - two screenshots showing the coords of each portal are in the link below:

twilightforest-1.12.2-3.3.202-universal

Cross-posting this with you comments section.

**Comment by Tamaized** [comment]
duplicate of #235
