### ISSUE TITLE
Giants in Final Castle

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#34]
![2017-06-18_15 14 00](https://user-images.githubusercontent.com/29523364/27264698-203cb93c-5439-11e7-8ffd-ac2b17bf65b9.png)
Twilight Forest version 2.4.0.5
Forge version 13.20.0.2260

**Comment by Benimatic** [comment]
The giants are placeholders for now, and will remain until the actual mobs are made.

**Comment by Benimatic** [comment]
The giants are placeholders to make sure that mobs of that size can spawn in the castle. They can stay until the actual mobs are made.
