### ISSUE TITLE
Players don’t come out of the right portal in multiplayer

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#340]
In multiplayer, if there are multiple portals created by different players, players always come out of the same portal in the Twilight Forest, Additionally, they seem to return to the last portal made when returning to the overworld, rather than returning to the portal that they made and entered themselves.

The Twilight Forest version: 3.3.202
Forge version: 14.23.0.2531

**Comment by forteddyt** [comment]
Is there any work being done on this? I feel like this is a pretty serious issue on servers

**Comment by Andromander** [comment]
From what I have heard from the Official Twilight Forest Server, the portal logic seems to be working as normal. The server uses version 3.7.398.

**Comment by forteddyt** [comment]
Is there any documentation that describes what the logic is?

I tested it out in single player (on sevtech mod pack 3.0.6) and placing two portals 250 blocks apart got me two different twilight forest spawn points.

**Comment by Drullkus** [comment]
Seems to be working fine then.
