### ISSUE TITLE
[1.12.2] SP Hosted LAN Players don't receive advancements correctly

### ISSUE THREAD

**Issue by MokahTGS** [TeamTwilight/twilightforest#344]
Forge version: 2537
Twilight Forest version: 3.3.202
Link to crash log: 

Steps to reproduce:
1. LAN Players join hosted game on SP and travel through a TW portal.
2. TW Advancements do not update for those players at all or update erratically.

What I expected to happen:
Players gain advancements along with or when they do the required steps.

There really needs to be a way to either give advancements to players via commands or turn off area progression.

**Comment by Andromander** [comment]
Addressed in #176. It is possible to completely disable progression with `tfEnforcedProgression`, but that affects every area progression and cannot be used selectively

**Comment by MokahTGS** [comment]
So I can turn it off completely?

**Comment by Andromander** [comment]
Yes. Using `/gamerule tfEnforcedProgression false` will disable progression

**Comment by Drullkus** [comment]
I'd to investigate this issue still.

**Comment by MokahTGS** [comment]
Do you need more data from us?

**Comment by Drullkus** [comment]
Nah

**Comment by Tamaized** [comment]
Is this still an issue in the latest builds? As I can't reproduce.

**Comment by Drullkus** [comment]
Probably fixed in newer versions of Minecraft
