### ISSUE TITLE
Naga Invisible After Rejoining World

### ISSUE THREAD

**Issue by ChloeDawn** [TeamTwilight/twilightforest#347]
**Forge version:** [1.12.2-14.23.0.2546](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2546/forge-1.12.2-14.23.0.2546-changelog.txt)
**Twilight Forest version:** [3.4.239](https://minecraft.curseforge.com/projects/the-twilight-forest/files/2502059)

After leaving and entering the TF dimension (portal was created inside the Naga zone), the Naga was invisible on the client (could not see it's bounding box with `F3+B` either). A clip of it hissing and breaking blocks can be seen here: [streamable.com/4fw5e](https://streamable.com/4fw5e)

**Comment by GizmoTheMoonPig** [comment]
I havent seen anyhting like this in 1.16 with the exception of Optifine ruining the multipart rendering (which we cant really fix), so im gonna close this.
