### ISSUE TITLE
[1.12.2] No fireflies in firefly jar

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#350]
![2017-11-23_17 39 20](https://user-images.githubusercontent.com/25916106/33182696-53c2f812-d075-11e7-8740-7c44ce7ce65f.png)

There used to be fireflies in the jar, but now there aren’t anymore, for some reason.

The jar is still a source of light, though. This is just a visual glitch.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**The Twilight Forest version**: 3.4.239

**Comment by DAgility** [comment]
Petition to rename "Firefly Jar" to "Jar"

**Comment by DAgility** [comment]
In all seriousness try checking your particle settings, if you have particles set to off or minimal they might not appear.

**Comment by ghost** [comment]
Particles are enabled.

**Comment by Drullkus** [comment]
Will add parameter to force particles on no particles to the method

**Comment by ghost** [comment]
@Tamaized Thanks! 👍
