### ISSUE TITLE
[Feature] Make portals respect world borders.

### ISSUE THREAD

**Issue by PurpleIsEverything** [TeamTwilight/twilightforest#351]
This is a simple feature asking for portals to respect vanilla world borders when placing portals. Currently when a border is set and a person creates a portal it will spawn them outside of the border than they will die. Either this or a radius based limit to where TF will search for placing a portal would be wonderful.

Thanks!

**Comment by williewillus** [comment]
this actually is handled by forge, which should have it fixed. try a forge version 2544 or higher and see if it is still an issue

**Comment by Killer-Demon** [comment]
The issue seems to have been fixed at some point, so I'm closing this. Feel free to re-open if it happens again.
