### ISSUE TITLE
[1.12.2] World Placement after re-entering TF after client being booted

### ISSUE THREAD

**Issue by Morpheus1101** [TeamTwilight/twilightforest#352]
Forge version:  14.23.1.2554
Twilight Forest version: 3.4.239

Steps to reproduce:
1.  Enter TF and wait to get booted out of the game
2. Re-join game an wait for TF to load
3. Your now standing in a location approx 100 blocks or so from where your actual portal is

What I expected to happen: To be standing next to my TF portal to go back to overworld

In the pic below the "Bad Spot" shown is where i spawn upon re-entering TF after being booted, the Blue line is where my portal is just below my location marked.

![2017-11-26_09 05 32](https://user-images.githubusercontent.com/10524952/33238746-47f3f010-d2df-11e7-8401-20df0e7331ff.png)

**Comment by Andromander** [comment]
Seems to be that the "bad spot" is in a restricted area, but the portal location is in a safe spot. Known issue, but good to know some more info.

**Comment by Tamaized** [comment]
This happens with nether portals as well, if you timeout while going through one this exact same thing happens. No idea why.

**Comment by kreezxil** [comment]
I player of mine "takemylunch" and  here's an excerpt from his latest.log https://pastebin.com/tvqewRyu is having the same problem on Forge build 2749.

His description:
```
11:05 AM] TakeMyLunch: if you time out or crash teleporting to the twilight forest you'll be displaced to the coords you entered the portal at.
example : if you enter a portal at x50 z50 in the overworld and the portal in the twilight is at x200 z200 and you crash you'll be placed at x50 z50 in the twilight. now i dont know if im just this unlucky but every time this has happened it just so happens to ALSO be in the final acid rain area killing me and making my stuff unobtainable unless an admin either aquires it for me, give me achives so barriers disappear or im creative'd to get it back. this bug isn't just for this pack. it's for any pack that twilight forest is in.
```

We are using version 1.12.2-3.7.424

**Comment by Tamaized** [comment]
The timeout issue is a vanilla bug. The same thing happens with nether portals.

**Comment by GizmoTheMoonPig** [comment]
this is part of #1459 as it has to do with portal redirection out of unsafe biomes. We'll look into a fix for it eventually
