### ISSUE TITLE
Crash whene a firefly dieds or you kill it

### ISSUE THREAD

**Issue by ashly138** [TeamTwilight/twilightforest#353]
Forge version: 
Twilight Forest version: twilightforest-1.12.2-3.5.246-universal <-- tought a newer version than the one on curseforge might fix it but did not.

Link to crash log: https://gist.github.com/ashly138/f80af5d68ff51980ef226c5f020d29f0

Steps to reproduce:
1. Kill a Firefly or let it die on it own.  

What I expected to happen:
Keep Playing MC :P

What happened instead:
Grey greenish screen and than crashes..

Allso reported this in ichuns issues page.

Edit: what do i use if i want to blacklist the firefly in ichuns Morph mod?

**Comment by tyler489** [comment]
EntityTFMobileFirefly I Believe

**Comment by Tamaized** [comment]
This was fixed on ichun's end
https://github.com/iChun/Morph/issues/889
