### ISSUE TITLE
[1.12.2] Anti Builder causes crash

### ISSUE THREAD

**Issue by generic-user-acc** [TeamTwilight/twilightforest#354]
Forge version: 14.23.1.2554
Twilight Forest version: 3.5.246
Link to crash log: https://pastebin.com/dPGVQidB

Steps to reproduce:
1. Place down an anti builder or find one in the ghast tower
2. Place or destroy any block in its radius

What I expected to happen: The game doesn't crash and the anti builder does what it's supposed to do.

What happened instead: The game crashes and upon rejoining, the anti builder did nothing.

**Comment by Drullkus** [comment]
Fixed via de6dd19
