### ISSUE TITLE
[3.4.239] breaking special wood with TNT drops timewood

### ISSUE THREAD

**Issue by AugiteSoul** [TeamTwilight/twilightforest#357]
Affected wood types:
-miningwood
-sortingwood
-timewood (in a way?)
-enchanted wood

When broken using an explosion, all drop Timewood.

**Comment by williewillus** [comment]
is this actually a bug? I looked around and the old FTB wiki says the wood cores are only obtainable with silk touch (though the silk touch logic isn't there either, lol)

**Comment by Killer-Demon** [comment]
Issue is about the wood, not cores.
Breaking Transwood, Minewood, or Sortingwood results in Timewood being dropped, the method of breaking doesn't matter.
Cores drop their respective coreless wood, no issue there.

**Comment by williewillus** [comment]
ah I misread, this is for the normal woods. fixed by 0b5df37
