### ISSUE TITLE
Flattening list

### ISSUE THREAD

**Issue by williewillus** [TeamTwilight/twilightforest#358]
for 1.13, which is still a *long* way off, but it's good to be prepared

Blocks:
- [ ] `old name` -> `split names` [ properties retained on each split ]
- [ ] `twilight_log` -> `oak_log`, `canopy_log`, `mangrove_log`, `dark_log` [ axis ]
- [ ] `twilight_leaves` -> `oak_leaves`, `canopy_leaves`, `mangrove_leaves`, `rainboak_leaves` [ decayable, check_decay ]
- [ ] `maze_stone` -> `maze_stone`, `maze_stone_brick`, `maze_stone_chiseled`, `maze_stone_decorative`, `maze_stone_cracked`, `maze_stone_mossy`, `maze_stone_mosaic`, `maze_stone_border` [ ]
- [ ] `hedge` -> `hedge`, `darkwood_leaves` [ ]
- [ ] `boss_spawner` -> probably gonna leave this unflattened?
- [ ] `twilight_plant` -> `moss_patch`, `mayapple`, `clover_patch`, `fiddlehead`, `mushgloom`, `forest_grass`, `dead_bush`, `torchberry`, `root_strand` [ ]
- [ ] `root` -> `root`, `liveroot` [ ]
- [ ] `fire_jet` -> `smoker` [ ], `encased_smoker` [ active ], `jet` [ {idle, popping, flame} ], `encased_jet` [ {idle, popping, flame} ]
- [ ] `naga_stone` -> not sure how to split this one yet. head vs non head?
- [ ] `twilight_sapling` -> `oak_sapling`, `canopy_sapling`, `mangrove_sapling`, `darkwood_sapling`, `hollow_oak_sapling`, `time_sapling`, `transformation_sapling`, `mining_sapling`, `sorting_sapling, `rainbow_sapling` [ ]
- [ ] `magic_log` -> `time_log`, `transformation_log`, `mining_log`, `sorting_log` [ axis ]
- [ ] `magic_log_core` -> `time_log_core`, `transformation_log_core`, `mining_log_core`, `sorting_log_core` [ axis, active ], make it use a real active state instead of piggybacking onto the old "bark on all sides" meta
- [ ] `magic_leaves` -> `time_leaves`, `transformation_leaves`, `mining_leaves`, `sorting_leaves` [ decayable, check_decay ]
- [ ] `tower_wood` -> `tower_wood`, `tower_wood_encased`, `tower_wood_cracked`, `tower_wood_mossy`, `tower_wood_infested` [ ]
- [ ] `tower_device` -> `reappearing_block` [ active ], `vanishing_block` [ {inactive, active, locked} ], `carminite_builder` [ {inactive, active, timeout} ], `antibuilder` [ ], `ghast_trap` [ active ], `carminite_reactor` [ active ]

-- todo finish this (tower_translucent to end)

Items:
- [ ] All ItemBlocks corresponding to above changed blocks
Nothing else! Yay for not using god items with 200 metas!

**Comment by Drullkus** [comment]
I think the naga heads should be split from the body blockstate group. Let’s not flatten the boss spawners too.
