### ISSUE TITLE
Twilight Forest bows incompatibility with CoFH Core

### ISSUE THREAD

**Issue by Kevun1** [TeamTwilight/twilightforest#359]
Forge version: 2545
Twilight Forest version: 3.4.239

~~Steps to reproduce:~~
~~1. Fire tri-bow~~
~~2. One arrow is shot~~

~~What I expected to happen: Three arrows are shot~~

Tri-Bow, Ice Bow, and Seeker Bow all lose their special effects when CoFH Core is present. 

I suspect the issue is on CoFH's end.

**Comment by Andromander** [comment]
Cannot reproduce. Tri-bow shoots three arrows on my end

**Comment by Kevun1** [comment]
This seems to only happen when CoFH Core is also present.

[I've opened up an issue here](https://github.com/CoFH/Feedback/issues/663)

**Comment by Kevun1** [comment]
This was fixed on their end, but now all modded bows don't work with the Multishot enchant and Quivers from CoFH. KingLemming stated that he'd add an API later and mods can opt into being compatible.
