### ISSUE TITLE
Ice Bow doesn't slow down mobs

### ISSUE THREAD

**Issue by Kevun1** [TeamTwilight/twilightforest#360]
Forge version: v2545
Twilight Forest version: 3.4.239

Steps to reproduce:
1. Fire Ice Bow at a mob

What I expected to happen: No special effects happen to mob

What happened instead: Mob is slowed or covered in ice

**Comment by Andromander** [comment]
Cannot reproduce. Ice bow covers target in ice and slows it down

**Comment by Kevun1** [comment]
Combined into #359
