### ISSUE TITLE
Entering Twilight Forest Timeout

### ISSUE THREAD

**Issue by Dreandor** [TeamTwilight/twilightforest#361]
Forge version: 14.23.0.2552
Twilight Forest version: 3.4.239
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Enter Twiilight Forest
2. Disconnect by Timeout

What I expected to happen: Enter the Twilight Forest and no Timeout

What happened instead: Enter Twilight Forest and I'll get Timeout. My Friend must port me.

**Comment by Tamaized** [comment]
Duplicated of #349
