### ISSUE TITLE
(Suggestion) Add cooldown for scepters.

### ISSUE THREAD

**Issue by AppDat** [TeamTwilight/twilightforest#363]
Forge version: 2501
Twilight Forest version: 3.5.272

Twilight scepter and lifetrain scepter are much better than regular weapons after the attack speed was added. These two scepters don't need to wait while attacking and mobs can't get close to players, which make swords and axes worse. 
The 1.9 version added cooldown for the ender pearl, so it also make sence to add cooldown for other items.

**Comment by williewillus** [comment]
the scepters don't last very long and already are dropped from bosses in the mod, so we decided against adding cooldowns for them.
