### ISSUE TITLE
Naga anti-cheese can break bedrock

### ISSUE THREAD

**Issue by purpleposeidon** [TeamTwilight/twilightforest#365]
1. Lock the Naga's head in a small bedrock ring
2. Stand a bit in front of the naga, pillar up onto some bedrock.
3. The naga'll break the bedrock you're standing on, sometimes.

**Comment by bs2609** [comment]
This shouldn't be the case at least since c447d72e3d39f311b4908bdcc752ab8c844bba3b.

Feel free to reopen this if you can reproduce it in a newer version (3.6.345+).
