### ISSUE TITLE
"With Fire It Writes" Advancement not given

### ISSUE THREAD

**Issue by Shahelion** [TeamTwilight/twilightforest#366]
Forge version: 2555
Twilight Forest version: 239

Steps to reproduce:
1. Enter the Forest
2. Kill a Raven
3. Craft the Magic Map Focus
4. Craft a Magic Map

What I expected to happen:
To get both "With Fire It Writes" and "I Can See For Miles"

What happened instead:
Only the second is given, the first remains locked.

![2017-12-09_16 09 55](https://user-images.githubusercontent.com/6917535/33800754-c5651bb6-dcfb-11e7-88ef-bbdcd8ab24e0.png)
![2017-12-09_16 09 56](https://user-images.githubusercontent.com/6917535/33800755-c57bb786-dcfb-11e7-93ff-a6561d532543.png)
![2017-12-09_16 09 57](https://user-images.githubusercontent.com/6917535/33800756-c593c132-dcfb-11e7-90ab-64384563dfc4.png)

**Comment by Andromander** [comment]
This issue looks to be in 3.4.239, which is not the latest version. Can you try to replicate this issue in 3.5.263?

I have tried to replicate this issue with Forge 14.23.1.2558 and Twilight Forest 3.5.263 and it works fine.

**Comment by Shahelion** [comment]
Didn't even realize I missed an update. Will re-open if still an issue.
