### ISSUE TITLE
Entities disappear when placed through portals

### ISSUE THREAD

**Issue by Sunconure11** [TeamTwilight/twilightforest#367]
Forge version: 14.3.1.2560
Twilight Forest version: 3.5.263
Link to crash log: No crash report

Steps to reproduce:
1. Get an entity into the portal
2. ???
3. No entity at the other end of the portal

What I expected to happen:

The entity to be transported to the other side of the portal (in this case, into the twilight forest)

What happened instead:

Entity vanished entirely from existence.

**Comment by Andromander** [comment]
Has the Twilight Forest dimension been loaded? Entities can be transported through portals, however, if the Twilight Forest has not been accessed yet, entities are more than likely to disappear, due to the dimension not having loaded yet.

**Comment by Sunconure11** [comment]
Dimension was not loaded when placing them, as I was not in it, nor was anyone else.

**Comment by Andromander** [comment]
Yup, this sounds like a Vanilla bug. Any entity that enters a portal before the dimension is loaded will vanish.
https://bugs.mojang.com/browse/MC-83350

**Comment by Sonicwave** [comment]
That issue appears fixed in 15w33c, though it's possible that the entity is being teleported to incorrect coordinates (instead of vanishing entirely) as described in https://bugs.mojang.com/browse/MC-116279. It may be that the two are actually describing the same issue however.

**Comment by Andromander** [comment]
Closing as this is a vanilla issue. Any forms of spawn persistence will prevent this.
