### ISSUE TITLE
Wispy Cloud Drop

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#369]
Make Wispy Clouds drop as blocks like Fluffy Clouds.

**Comment by Drullkus** [comment]
I literally don't understand why it's not dropping them. @Tamaized?

According to the code it should drop when silked.

**Comment by williewillus** [comment]
the Material used by the cloud has `setRequiresTool` called, which means any block break that occurs is ineligible for drops without the right tool
