### ISSUE TITLE
Improper Block Generating in Dark Tower

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#37]
![improper block spawning](https://user-images.githubusercontent.com/29523364/27264893-94049150-543e-11e7-89df-46b7d64c6aab.png)
![improper block spawning 2](https://user-images.githubusercontent.com/29523364/27264894-94c79330-543e-11e7-8c88-798cccde2f5d.png)
![improper block generating 3](https://user-images.githubusercontent.com/29523364/27264910-18a4772c-543f-11e7-8121-d7c7e2e07ac2.png)
Twilight Forest version 2.4.0.5
Forge version 13.20.0.2260

**Comment by Benimatic** [comment]
Think I got all of these fixed in https://github.com/TeamTwilight/twilightforest/commit/52cb075ff5598cd5e3418f325a09e717a43543ad
