### ISSUE TITLE
Crash when loading into the TF. twilightforest.world.TFGenLargeWinter.buildTrunk

### ISSUE THREAD

**Issue by Gamerbolts** [TeamTwilight/twilightforest#371]
Hello. I have TF on my modpack for my friends community, on our server someone went into the twilight forest and it crashed the server. Here is the error log I recovered https://pastebin.com/V2B2g4GQ

Any help is appreciated. Thank you

Forge version: 2555
Twilight Forest version: twilightforest-1.12.2-3.5.263

Steps to reproduce:
1. Hard to reproduce if you aren't on the modpack and server

What I expected to happen:
Go into the Twilight Forest

What happened instead:
Server meltdown

**Comment by Tamaized** [comment]
This looks more like the server "crashed" due to exceeding max tick time (1min by default)

see #85

**Comment by Gamerbolts** [comment]
hmm ok I will look into that

**Comment by williewillus** [comment]
you can disable the timeout in server.properties (check the vanilla wiki)

**Comment by DrunkTaank** [comment]
I think this might be related to a bug I have been seeing on my server when generating new terrain in the TWF.  I had a similar issue when changing dimensions between the Overworld and the TWF.  My best guess is that after attempting to go back and forth between the two dimensions, enough terrain had finally generated to allow me to enter.  However I was seeing huge drops in TPS and getting lots of spam in my server log about the server not being able to keep up and having to skip ticks.  After spending about 45 minutes in the TWF, not moving so as not to generate terrain, my server finally caught back up.  I decided to do some terrain generation while watching my server console, and I got the following message:

`[23:08:46] [Server thread/WARN] [FML]: The Twilight Forest loaded a new chunk (-65, -31 Dimension: 7) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.​`

**Comment by Tamaized** [comment]
There's only one place in the entire Twilight Forest, afaik anyway, that causes cascading world gen and it's so insignificant it wouldn't cause an entire server to just freeze.

**Comment by DrunkTaank** [comment]
Tamaized, I'd be happy to provide you with my latest server log as I have spent the last hour or so attempting to duplicate it (getting mostly can't keep up messages).  What's strange is that I just got the error message again while in the TWF, except this time it was triggered by Binnie Core.  TWF doesn't have any dependencies on Binnie Core, does it?

`[23:08:46] [Server thread/WARN] [FML]: The Twilight Forest loaded a new chunk (-65, -31 Dimension: 7) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.​`

**Comment by Tamaized** [comment]
These don't provide any valuable info to what's consuming so much processing power, you'd need to profile it to get any real info

**Comment by DrunkTaank** [comment]
I'll keep digging into it and make sure there aren't hardware limitations causing this.  There are advantages on having physical access to your server. lol

**Comment by Killer-Demon** [comment]
The issue most likely lies with vanilla's inefficient lighting calculations, which is a known issue.
We can't solve this ourselves, but a PR has been made to Forge at: https://github.com/MinecraftForge/MinecraftForge/pull/4729

The async lighting feature in Sponge may alleviate this temporarily for the time being as a bandaid.

A profile of the issue would still be welcome if the problem is still relevant though, on the off chance this is not it.
