### ISSUE TITLE
[Suggestion] Make some Twilight Saplings usable as Furnace Fuel

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#373]
Forge Version: 14.23.1.2558
Twilight Forest Version: 3.5.263 (probably doesn't matter)

Like how Vanilla Saplings can be used as Furnace Fuel, some of the saplings in the Twilight Forest should b usable as Fuel, barring Magic Saplings, of course.

**Comment by bs2609** [comment]
Could be done using https://github.com/MinecraftForge/MinecraftForge/pull/4083.
