### ISSUE TITLE
Dimension Teleport command

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#375]
A command to get to and from the Twilight Forest.
Useful for modpack makers, server administrators, and creative players alike.

**Comment by Helimyne** [comment]
The config ability to disable the return portal generation would also work for modpack makers, server administrators, and creative players alike.

**Comment by Tamaized** [comment]
This is part of Forge now:
https://github.com/MinecraftForge/MinecraftForge/pull/4602/files#diff-0e72401776afcbeca458abc11504fba5

**Comment by Drullkus** [comment]
@Helimyne I tried doing that but it creates more issues that I’d like. Instead I added a different kind of portal that can generate instead. It’s a portalbut with a barrier, disallowing you to use it unless you toss in a diamond or another activation item.
