### ISSUE TITLE
Random Freezing

### ISSUE THREAD

**Issue by Frontrider** [TeamTwilight/twilightforest#376]
Forge version: 14.23.1.2562
Twilight Forest version:1.12.2-3.3.202
Link to crash log: none
Steps to reproduce:
1. walk around

What I expected to happen:
The game not to freeze.
What happened instead:
The game froze.

The only specific I can give is that the machine was a asus x556u laptop (using the integrated vga, because mc has more frames with that). Checked optifine, the only difference it makes, that it happens much sooner if I use that.

The freeze only happens in twighlight, I can spend hours anywhere else.

Its very vague, but its really all I can give.

update: teleporting out of the dimension, immidietly unfreezes the client, no restart is needed.

update2: turns out that the server log contains lines like this, can be unrelated, but they've never shown up before I entered the dimension:
[13:47:04] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 9b127dc5-65a6-4087-8eab-9c2e2354dab5

**Comment by Andromander** [comment]
Your Twilight Forest version is outdated. Try it again with 3.5.263

**Comment by Killer-Demon** [comment]
Closing this issue as it's no longer active and for a outdated version.
If the issue persists for you in the latest version feel free to reopen it with new information.
