### ISSUE TITLE
Progression stuck

### ISSUE THREAD

**Issue by SimulatorSia** [TeamTwilight/twilightforest#377]
I'm so very glad it's back but I can't turn off progression because I have cheats disabled and I am following the progression guide. I've killed the Naga, Twilight Lich, then Minoshroom and gotten Meef Stroganoff but the Hydra still has the little yellow squares around it. Wtf. I'm stuck. Please help.

Do I have to have the Meef Stroganoff in my inventory?

**Comment by Drullkus** [comment]
You need to eat the Stroganoff

**Comment by SimulatorSia** [comment]
:O

ohhhhhhhhh I gotta eat it????
