### ISSUE TITLE
could not create portals

### ISSUE THREAD

**Issue by 0uti** [TeamTwilight/twilightforest#378]
Forge version: 14.23.1.2566
Twilight Forest version: build 265+ (starting with commit https://github.com/TeamTwilight/twilightforest/commit/c88f60d8e32552e9c4d4788d0ad6b48c6ca2134a )
Link to crash log: no crash log needed

Steps to reproduce:
1.  build water pool with flowers
2.  throw diamond into pool

What I expected to happen:
create portal to TF

What happened instead:
nothing

Notes:  no other mods installed

**Comment by Drullkus** [comment]
Are you playing on a server? Can you take a screenshot of the water?

**Comment by 0uti** [comment]
i am in single player mode

![2017-12-16_18 42 46](https://user-images.githubusercontent.com/1269456/34072984-0206c6f6-e291-11e7-9ae6-90502475e458.png)

**Comment by Drullkus** [comment]
Can you show me the config file?

**Comment by 0uti** [comment]
[twilightforest.cfg.txt](https://github.com/TeamTwilight/twilightforest/files/1565120/twilightforest.cfg.txt)

**Comment by 0uti** [comment]
i have found the bug.

https://github.com/TeamTwilight/twilightforest/blob/f4889405e2b44df148e5f8fe147f4e72badc4b66/src/main/java/twilightforest/block/BlockTFPortal.java#L134

flowers aren't full blocks (cubes)

<img width="434" alt="tf debug" src="https://user-images.githubusercontent.com/1269456/34074827-ffa3750e-e2b7-11e7-9774-8ce888f7120f.PNG">

**Comment by Drullkus** [comment]
Whoops. That was definitely for the isDirtOrGrass method

**Comment by Tamaized** [comment]
This was fixed in 9524fe6456c933d58e430d42605cfe3df4b9b063
