### ISSUE TITLE
Crash on LAN 1.12.2

### ISSUE THREAD

**Issue by solunareclipse1** [TeamTwilight/twilightforest#379]
Forge version: 14.23.1.2560
Twilight Forest version: 3.5.263
Link to crash log: https://hastebin.com/jihocisisi.sql

Steps to reproduce:
1. Open to lan, with another player
2. Go to forest, equip mekanism armored jetpack on both players
3. have the host kill the naga, but the other player not
4. both players fly toward lich tower
5. when non-host sees progression particles (yellow squares), should crash for host with above report

What I expected to happen:
No crash
What happened instead:
Crash

**Comment by Tamaized** [comment]
This is on mekanism's end

`at mekanism.client.render.RenderTickHandler.tickEnd(RenderTickHandler.java:135)`

**Comment by Killer-Demon** [comment]
Issue is on Mekanism's side.
