### ISSUE TITLE
Blazes in 2nd Miniboss Chamber

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#38]
![blazes](https://user-images.githubusercontent.com/29523364/27264902-ce9e2d1c-543e-11e7-9dd6-74e74a71367d.png)
Twilight Forest version 2.4.0.5
Forge version 13.20.0.2260

**Comment by Benimatic** [comment]
The blazes are placeholders for now, since neither the room nor the mobs that go in it are finished.

**Comment by Benimatic** [comment]
The blazes are placeholders to make sure mob spawns in that room work and don't interfere with spawns in the rest of the castle. This won't be fixed until that room is revised, so I'm closing this for now.
