### ISSUE TITLE
[feature request] Add config to allow spawning in Twilight dimension

### ISSUE THREAD

**Issue by Zygus42** [TeamTwilight/twilightforest#381]
Would love to be a able to set server spawn point in the Twilight Forest dimension so that everyone starts there.  Currently there are no mods in 1.12 that let me set the spawn point to another dimension (that i can find anyway).

**Comment by liach** [comment]
You can try spongeforge and sponge plugins if you really can find nothing, although tamaized stated that twilight forest would not support sponge.

**Comment by Tamaized** [comment]
I personally don't support it, not that the mod or team itself doesn't support it, I can't make that claim :P

**Comment by Zygus42** [comment]
Seems a lot of effort to do such a simple thing.  Have considered setting up an overworld spawn location with no egress except for a portal to the Twilight Forest, but would be nice not to have to go to those lengths.  Twilight Forest has support for things that are really only of use in the early game, and no one goes there early game due to the need for the diamond to open the portal.  Would be good for the mod to have some way of getting there early in a game, either through the ability to start there or some other method, such as perhaps naturally occurring portal pools in the overworld.

**Comment by Andromander** [comment]
There is a config option to change what item you can throw into the pool to create the portal. You will need to restart the game for the change to take effect, obviously.

**Comment by Zygus42** [comment]
So there is - interesting.  Would still prefer a "start in Twilight" and return to the overworld game, but this may be an alternative if i can't have that.

**Comment by hanleybrand** [comment]
Another thought is to use the Ruins mod and create portal templates so that TF portals appear randomly in the world - not what you were going for, but it's another way to allow people to get to TF earlier. 

https://gist.github.com/hanleybrand/7e78e8e4cdc75efb73a0089b9e19284e

**Comment by Tamaized** [comment]
61b418b9bc205ac2ce87a6c540ba4a51ad0e4f0d
