### ISSUE TITLE
Unable to plant magic beans

### ISSUE THREAD

**Issue by xenoflot** [TeamTwilight/twilightforest#382]
Forge version: 14.23.1.2560
Twilight Forest version: (this is the build number) 3.5.230
Link to crash log: No crash

I'm unable to plant magic beans. I acquired some via the obsidian vault, picked up some of the provided uberous soil and bonemeal. I've tried placing the soil in various positions directly under cloud blocks, in a spot such that it would grow adjacent to a could block and also several blocks away. Right-clicking the beans on the soil has no effect. Unable to till the soil. Even placed some water just in case that was the problem :) I also tried on some naturally occurring surface blocks. I _do_ get the hand-wave movement when I rightclick.

Did I derp, or do we have a bug?

Cheers!

**Comment by Hubry** [comment]
It's fixed in dev already (91143da412a34d5b76cfaf56a93665862a2df7c7). I assume this is the FTB wiki server, right? :P

**Comment by xenoflot** [comment]
Don't you have something better to do than stalk my github posts?

**Comment by Hubry** [comment]
No, I'm on the TF Discord and they have a GitHub webhook set up :P
