### ISSUE TITLE
Possible conflict with BOP?

### ISSUE THREAD

**Issue by Gamerbolts** [TeamTwilight/twilightforest#384]
Forge version: 2555
Twilight Forest version: 3.5.263
Link to crash log: https://pastebin.com/7bNR1ZYy

I have my modpack on my server for my friends community as I stated in my other issue report. But I am getting a different crash. I was not awake when this happened I just saw the crash log. Am wondering if it is a conflict with BOP?

**Comment by williewillus** [comment]
The server watchdog thread is just killing the server since it's taking too long lagging to generate terrain. Increase the timeout in server.properties or pregenerate your world

**Comment by Gamerbolts** [comment]
I went to server properties. I see two possible options

player-idle-timeout or max-tick-time. Which one of those do I increase?

**Comment by williewillus** [comment]
max-tick-time, either set it higher or set it to -1 to disable the watchdog thread

**Comment by Gamerbolts** [comment]
will do. thank you very much
