### ISSUE TITLE
firefly in monster spawner 

### ISSUE THREAD

**Issue by beesyndicate** [TeamTwilight/twilightforest#385]
Forge version: 1.12.2-14.23.1.2560
Twilight Forest version: (this is the build number)3.5.263
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. go into gamemode c 
2. place spawner
3. put firefly spawn egg in spawner

What I expected to happen:

Spawn fireflys in world

What happened instead:

nothing the firefly spins round and round in the spawner but never spawns 

Thank you guys for reviving this great mod and for all your hard work.
Happy Holidays

**Comment by Andromander** [comment]
Is the spawner in the right conditions (large enough space to spawn them, dark enough so the spawner isn't disabled)?

**Comment by Drullkus** [comment]
[The attempts to spawn the mob by spawner must be below sea level and dark](https://github.com/TeamTwilight/twilightforest/blob/e41771b0f358c58ec9eeffd8fcdb3546905dd02f/src/main/java/twilightforest/entity/passive/EntityTFMobileFirefly.java#L111-L119)
