### ISSUE TITLE
World-gen lag with recurrent complex

### ISSUE THREAD

**Issue by godemperoroftheworld** [TeamTwilight/twilightforest#386]
Forge version: 
Twilight Forest version: 3.5.263
Link to crash log: N/A

Steps to reproduce:
1. Run server with recurrent complex and twilight forest
2. Blacklist twilight forest in recurrent complex config (UniversalDimensionMatcher=!7) & even set recurrent complex to light mode
3. Explore in twilight forest

What I expected to happen:
No world-gen lag

What happened instead:
Experience Minecraft in 2tps with 350+ms mean tick time (server console will be spammed with Recurrent complex... loaded chunk during chunk population ... causing cascading worldgen lag)

**Comment by beesyndicate** [comment]
I have also experienced this problem. I however did not have TF disabled in the Reccurnt complex configs.
I had to disable portal creation to prevent users from going to the TF.

**Comment by Andromander** [comment]
I'm unsure on what Recurrent Complex is, however it seems that it is not possible to disable it for Twilight Forest, which sounds like the issue is not because of Twilight Forest. Is this issue open on their end too?
I'm only making an assumption based on reproduction steps and what happens, because most cascading worldgen lag in the Twilight Forest has been ironed out, except for the one instance that cannot be fixed due to vanilla Minecraft.
In the meantime, are any of you able to post a client log of this issue occurring?

**Comment by Hubry** [comment]
>I'm unsure on what Recurrent Complex is

[Recurrent Complex](https://minecraft.curseforge.com/projects/recurrent-complex) is a rather powerful worldgen mod.

**Comment by beesyndicate** [comment]
I will but won't be able to until after the holidays

**Comment by LiskoSlayer63** [comment]
I noticed this too, is there any updates yet?

**Comment by Andromander** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/287

Since it is relevant to the issue, I'll link this here.

**Comment by godemperoroftheworld** [comment]
The issue is on Recurrent Complex's end.
When you disable worldgen for recurrent complex in a dimension, it doesn't disable it for everything
For example, custom trees stilll generate. So I had to flat out disable those to get rid of the issue

**Comment by noah1gamble** [comment]
Still an issue.

**Comment by Andromander** [comment]
From what I understand, this is an issue relating to features generated by RecurrentComplex not being disabled and putting additional stress on world generation. For 1.12, there are mods out there such as Phosphor that can help mitigate problems like these. However, for 1.16, Cascading Worldgen Lag is no longer a problem, and worldgen in general is improved.
