### ISSUE TITLE
timewood clock

### ISSUE THREAD

**Issue by gustaff67** [TeamTwilight/twilightforest#387]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:
I try to harvest a timewood clock with different silk touth tools.
normaly i should get the clock now.

What happened instead:
i only get timewood

**Comment by Andromander** [comment]
Magic Wood Cores cannot be harvested. Working as intended

**Comment by Tamaized** [comment]
^
