### ISSUE TITLE
Returning to vanilla world in the ground from Twilight forest

### ISSUE THREAD

**Issue by ArtistChibi** [TeamTwilight/twilightforest#388]
Forge version: 14.23.1.2555
Twilight Forest version: 3.5.263
Link to crash log: There is nothing in the logs stating anything about the mod when transporting from one realm to the next.

Steps to reproduce:
1. Hopped into portal, like normal, to return to vanilla world after exploring a bit.

What I expected to happen:
I expected to show up on the platform where the portal to the forest is.

What happened instead:
I spawned in the ground about 100 blocks away from where I was supposed to end up, at around Y level 40. This is the second time this happened. Figured it was a fluke the first time since I went into the portal numerous times before and after without issues.

**Comment by OutcastZeroOne** [comment]
Same versions of Forge and twilight forest.

I am also having this same issue. what ever Z level the portal is at in the TF i am returned to that same level in the overworld, regardless of if it is clear or not or not.

**Comment by Drullkus** [comment]
Should be fixed via 9524fe6
