### ISSUE TITLE
Can't locate swamp biom. 

### ISSUE THREAD

**Issue by Tiviacz1337** [TeamTwilight/twilightforest#389]
Forge version: 10.13.4.1558-1.7.10
Twilight Forest version: 1.7.10-2.3.7

So I've got my private modpack and when I'm going to Twilight Forest, I can't locate Swamp. I've Spent 3 hours for finding this biom. 
Maybe It's Biome Ids' conflict, because I've got this message when entering world. But I checked ids and everything seems Ok, so I don't know what should I do. ;/
In my modpack I've got those mods with new biomes:
Biomes o' plenty
Thaumcraft (It adds biomes too, like Magical Forest)
Galacticraft (?) 
Aether II (?)
I think thats's all.
Can you help me?

**Comment by Killer-Demon** [comment]
Try `/locate twilightforest:hydra_lair` for me, will you?

**Comment by Tiviacz1337** [comment]
Not working
Unknown command. Try /help for a list of commands. 
:(
Any ideas?
I've read, this command is only available for minecraft 1.11+. I'm playing on 1.7.10 ;//

**Comment by Killer-Demon** [comment]
Didn't even look at your version number as I took people being on 1.12.2 for granted.
1.7.10 does not have that command and is unsupported by us for almost _three_ years by now.

Couldn't tell you if you have a unlucky streak with your seed or if it actually is a bug or a bad interaction between mods.
I hope you can resolve your issue all the same, though.

**Comment by Tamaized** [comment]
1.7.10 is unsupported
