### ISSUE TITLE
Missing Item Frames

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#39]
![2017-06-18_16 00 27](https://user-images.githubusercontent.com/29523364/27264923-77697000-543f-11e7-8dde-10a862ace96b.png)
Twilight Forest version 2.4.0.5
Forge version 13.20.0.2260

**Comment by ruairidh74** [comment]
I got the same:
![2017-06-19_00 06 31](https://user-images.githubusercontent.com/29524403/27264959-3deaab02-5483-11e7-8e06-981616694eaa.png)

Twilight Forest: 2.4.0.5
Forge: 13.20.0.2228
