### ISSUE TITLE
Overactive cicada singing

### ISSUE THREAD

**Issue by OreCruncher** [TeamTwilight/twilightforest#393]
Forge version: 14.23.1.2582
Twilight Forest version: 3.5.263
Link to crash log: None

Steps to reproduce:
Stand in an area where cicadas spawn.

What I expected to happen:
Cicada song would only happen if a player is in reasonable range for them to actually hear it.

What happened instead:
There appears to be 120+ cicada sound instances in the Minecraft sound manager.  Downside is that I don't hear any cicada sounds so the sounds are being generated by cicadas that are several chunks away.  I have my mod Dynamic Surroundings installed and it increases the number of sound channels available.  It's why I am reporting such a large number.  Minecraft default is 32 sound channels.

If you want to see what is queued down in the sound engine installed Dynamic Surroundings.  Enable DS debug, and while in game hit F3.  On the left of the screen in gold is a list of the ogg files that are being played at any given time.  The number at the end of each line is the number of instances of that particular ogg file.

**Comment by bs2609** [comment]
Sounds on the server are sent to all players within a certain range based on the volume, but these sounds are client-side and are always played if the TE is loaded:
https://github.com/TeamTwilight/twilightforest/blob/0119dca00c06994f29c1206de02fa98145cbcd8e/src/main/java/twilightforest/tileentity/critters/TileEntityTFCicadaTicking.java#L73-L77

There doesn't seem to be any client-side equivalent built in, but it could probably be looked at.

**Comment by GizmoTheMoonPig** [comment]
doesnt seem to be an issue anymore, so im gonna close this. If its still a problem in 1.16, please reopen this.
