### ISSUE TITLE
Charm of Keeping Tier 2 with Charm of Life Tier 1, bug

### ISSUE THREAD

**Issue by Teslachu** [TeamTwilight/twilightforest#394]
Forge version: 14.23.0.2522
Twilight Forest version: 3.3.202

This bug created no log of any kind. No crash.

Steps to reproduce:
1. Have 2 charms of keeping tier 2 in your inventory
2. Have 2 charms of life, tier 1 in your inventory
3. Starve to death (Cause you went afk irl for a bit)

What I expected to happen:
As fatal damage occurs, the first charm of life should break and save you. 
As your life gets down the second time, this should happen for the second time, destroying the second charm of life.
With both charms of life gone, you should be left with 2 charms of keeping. 
Upon finally dying from starvation (or anything), one charm of keeping, tier 2, should break, and when you res, you should have all the stuff from your hotbar and equipment still on.

What happened instead:
Fatal damage occurs and both a charm of life (tier 1) and a charm of keeping (tier 2) break. 
The charm of life saves you and at the same time, you lose all your armor and stuff on your hotbar.
As you hit fatal damage the second time, the exact same thing happens.

So the charm of keeping is triggering when you take fatal damage, but not when you actually died. Now I know the charm of keeping (tier 3) worked to keep my items before... (I also had a charm of life -tier 1-, at the same time, but for some reason that charm didn't trigger/break/go off - so only the keeping one broke)... so I don't understand why both charms break in this case and override themselves. However, it is a very devastating lost, especially since I am playing on a server. So my stuff is gone. What makes it worse is this modpack has gravestone... so I would have been better off without the charms, cause I wouldn't have lost all my good gear and nicely leveled tinkers tools.... I hope this isn't how it is supposed to work. I don't remember this kind of thing happening from the 1.7 version of Twilight Forest.

**Comment by Tamaized** [comment]
Update Twilight Forest

**Comment by Teslachu** [comment]
That doesn't help when playing on a mod pack... On a server and I'm not the server administration or anything, but thanks for the replay.

**Comment by Tamaized** [comment]
Well I've already fixed it on our end, and the update is live. Not much else we can do ¯\\_(ツ)_/¯
100% on the user's end now.

**Comment by Teslachu** [comment]
I know.. Sorry. It just sucks. I had a ton of stuff I lost. Just kind of wish I had known before it happened... Not that I should've starved in the first place, but so goes life. Thanks again for the response.
