### ISSUE TITLE
Crashing In Snow Biome

### ISSUE THREAD

**Issue by Shockingglitch3** [TeamTwilight/twilightforest#395]
So as I began my adventure in the snow biome I just froze and crashed after a minute. I'm not sure why I don't know if it's my computer or what. Is there any way to fix it? Heres my specs: not anything spectacular, but it ran minecraft well enough

CPU
	- AMD Ryzen 7 1700 Eight-Core Processor

GPU
	- Radeon RX 560 4 GB

RAM
	- 16 GB Samsung @ 1200 MHz
This is my crash report
https://drive.google.com/open?id=1to1L3n-P1YHayc4N1xUQE_j3fveTjI4G

**Comment by Andromander** [comment]
Are you able to reproduce this with only Twilight Forest installed? Another mod may be interfering.

**Comment by Drullkus** [comment]
Can you give us the world seed and location?

**Comment by Ghostrider231** [comment]
Hello everyone, I think I've figured out what's causing that crash. 

The 'wolfarmor' mod which is the Wolf Armor and Storage Mod making the Winter Wolf spawns crash the game. Which is also why you can't spawn winter wolves via spawn eggs or commands.

Of course, If you just have the wolf armor mod and twilight forest itself alone. It only breaks the Winter Wolves but won't crash the game. (I assume)

I've tested twilight forest without wolf armor and the Crash stoped and Winter Wolves can spawn again. If I add the mod back in, it crashes again.

I don't think it matters what seed it is. You just have to be in the Snowy Forest Biome. (You cannot be on peaceful or else the crash won't happen)

Edit: For the Wolf issue with wolf armors mod, this problem only applies to the winter wolf. The other ones are no problem. (ie. Hostile Wolf and Mistwolf)

**Comment by bs2609** [comment]
Is this resolved now?

**Comment by Ghostrider231** [comment]
@bs2609 Yes, the newest version of wolf armor had resolved this issue on their side. Which changes the way how it interacts with wolves. Furthermore, no longer breaks Winter Wolves and allows them to spawn normally.

**Comment by bs2609** [comment]
Ok, good to know.
