### ISSUE TITLE
Singleplayer Server Crashes Upon Finding Major Landmarks and Continues Crashing When Opened Again

### ISSUE THREAD

**Issue by SomethingToTell** [TeamTwilight/twilightforest#396]
Forge version: 14.23.1.2555
Twilight Forest version: 3.5.263
Link to crash log: https://hastebin.com/idacezuqez.sql https://hastebin.com/juzofuveba.sql

Steps to reproduce:
1.  Open singleplayer server
2.  Enter Twilight Forest via portal (which should cause a separate crash that resolves after logging in and opening the world again)
3.  Wander through the forest until you find a hollow hill
4.  Game should crash if encountering a hollow hill is not a coincidence with when the crash happened
5.  Attempting to open the server again will result in another crash that prevents any player input

What I expected to happen: The game would run as normal when approaching or inside a structure like a hollow hill, and I would be able to continue playing if it did crash.

What happened instead: The game crashed with an "exception ticking world" error upon reaching a hollow hill at both times of discovery. Every attempt to enter the server again would result in another crash and an "exception in server tick loop" error. The first crash report above is for the "exception in server tick loop". The second one is for the "exception ticking world".

**Comment by Andromander** [comment]
This issue has been fixed, but is currently unavailable on Curseforge.

**Comment by Tamaized** [comment]
^
