### ISSUE TITLE
Development builds break OTG multiverse functionality.

### ISSUE THREAD

**Issue by PersonTheCat** [TeamTwilight/twilightforest#397]
Forge version: 14.23.1.2555
Twilight Forest version: 274 - 296
Link to crash log: https://pastebin.com/Ew5X7GVr

OTG multiverse functionality is broken in builds 274 - 296, where vanilla dimensions and dimensions added by other mods (e.g. Aether Legacy) are unaffected. Entering secondary dimensions created through OTG results in a crash. 

Posting this even though these are experimental builds because it isn't the sort of thing you would test before a release version.

**Comment by Andromander** [comment]
Might be related to #334, since they share a similar crash report

**Comment by bs2609** [comment]
Looks like https://github.com/TeamTwilight/twilightforest/issues/334#issuecomment-344767981.

https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B/platforms/forge/src/main/java/com/pg85/otg/forge/OTGWorldServerMulti.java#L66-L87

**Comment by Drullkus** [comment]
They must call the super method
