### ISSUE TITLE
NoSuchElementException Erorr

### ISSUE THREAD

**Issue by avescarelo** [TeamTwilight/twilightforest#398]
Forge version: 14.23.1.2583
Twilight Forest version: 1.12.2-3.5.263
Link to crash log: https://gist.github.com/pingvikin/1f50dd1d0bafa84997106c3a61e88304

Hello, I encountered a problem, please help me. If you go in the twilight world and even during the loading this world player open inventory or leave the portal, server is crash.

**Comment by bs2609** [comment]
Looks like a Sponge error: https://github.com/SpongePowered/SpongeCommon/commit/8bc303b917e4c3670b3b2210ba3a26535a202e8e
