### ISSUE TITLE
Final Castle generation froze the game

### ISSUE THREAD

**Issue by Bobb-E-Burns** [TeamTwilight/twilightforest#399]
Forge version: `forge-1.12.2-14.23.1.2559`
Twilight Forest version: `twilightforest-1.12.2-3.5.263-universal`
Link to crash log: https://gist.github.com/LeLobster/af737ac9ee7d3e795d04fbaf59609ac1

**Steps to reproduce:**
1. Wander into the troll cave close enough to the Final Castle
2. Wait

**What I expected to happen:**
Generating Final Castle without freezing the game

**What happened instead:**
The game completely froze at 01:16, and at 01:28 I decided to kill the Java process because I got tired of waiting.  
CPU's were constantly spiking to 100% usage
I'm seeing a lot of `Maze of color * is getting a bit excessive.`, perhaps it's having trouble generating proper mazes?

**Comment by Drullkus** [comment]
I need seed and co-ords

**Comment by Bobb-E-Burns** [comment]
Don't have time to play right now so did a quick look with NBTExplorer.  
TF seed is the same as regular Minecraft seed in use?  

**edit:** `S:twilightForestSeed=` in the .cfg is empty so I'm assuming it's using the MC seed.  

`RandomSeed:` 4829061305580255573
`Pos:` 587.106938831521, 18, -153.779081649965

**edit2:** Loaded up the world today and it seems like the castle generated fine. (even though I killed the Java process earlier)  
I went through it without issues and got to the final platform where I read the final boss sign.    
Seeing a lot of this `[Server thread/WARN] [twilightforest]: Final Castle tower has null for glyph color, this is a bug.` in the log file though.
 

Besides the frequent desync/lag in the world during play and no final boss yet It was really fun playing through TF again. Last time for me was in 1.2.5 iirc. Fantastic work keeping this mod alive.  

Also I wish I could mine the Castle Tower door blocks because they would look neat in the main base. :)

**Comment by recolic** [comment]
Same issue. 
This error message crashes my minecraft server running 1.12.2 forge.
```
[twilightforest]: Final Castle tower has null for glyph color, this is a bug.
...
```

**Comment by Andromander** [comment]
Those warnings generally don't result in crashes; if anything, the log spam might be a bit much, but not too much, though this no longer happens in 1.16.
World generation in 1.12 can be sluggish, and it is advised that mods such as Phosphor are installed to help mitigate this. If this persists in 1.16, feel free to create a new issue.
