### ISSUE TITLE
Issue with this mod and Carry On

### ISSUE THREAD

**Issue by Sunconure11** [TeamTwilight/twilightforest#402]
Forge version: 14.23.1.2589
Twilight Forest version: 3.5.263
Link to crash log: No crash log

Steps to reproduce:
1. Install Twilight Forest and Carry On
2. Pick something up

What I expected to happen:

The player to be able to hold things normally without looking like they were hit by a frost bow.

What happened instead:

https://github.com/Tschipp/CarryOn/issues/63

**Comment by Sunconure11** [comment]
Issue appears to be resolved. If it happens again, please reopen

**Comment by bs2609** [comment]
Should be fixed by a5a1c3398ba30edc1bc47d4fa2c9c0dcbb117994 I think.

**Comment by Tamaized** [comment]
Ah yea, forgot to close this.
