### ISSUE TITLE
Add Twilight Dimension Music

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#405]
Made possible by MinecraftForge/MinecraftForge#4539

**Comment by DartPower** [comment]
Cool idea. Very good for enhancing game atmospheric

**Comment by kitsu** [comment]
3.6.324 crashes on startup on Forge 14.23.1.2587.
The change log should mention a hard dependence on a specific forge version
(or you could check for the required method and fail gracefully on older Forge versions).

**Comment by bs2609** [comment]
See 6712f2e029454bdf2e517f783e2518ec9befbfb7.

**Comment by Tamaized** [comment]
^ and why was this commented on this specific issue :thonk:

**Comment by Drullkus** [comment]
Admittedly I think we need one or two more. >.>
