### ISSUE TITLE
Client crash when placing Giant Blocks in a position where they will overwrite Snow Layers

### ISSUE THREAD

**Issue by TeetoKaziim** [TeamTwilight/twilightforest#406]
Tested with giant cobble and giant obsidian, but I got tired of load times.

Forge version: 14.23.1.2600
Twilight Forest version: 3.5.263
Link to crash log: https://pastebin.com/raw/ad5at2LX

Steps to reproduce:
1. Place giant blocks so that you can predict the allignment.
2. Place snow layers where a giant block placement will overwrite those blocks.
3. Attempt to place a giant block in a place where it'll occupy that same space.
 

What I expected to happen:
A giant piece of obsidian deleting all the snow on the ground mightily.

What happened instead:
My client crashed, and upon reloading, no block had been placed.

**Comment by bs2609** [comment]
This is the problem, the position needs to be matched here:
https://github.com/TeamTwilight/twilightforest/blob/aeab38e948e8878e03ecaad173274812ec6168f2/src/main/java/twilightforest/block/BlockTFGiantBlock.java#L35-L36
