### ISSUE TITLE
Random crash while exploring

### ISSUE THREAD

**Issue by KorDum** [TeamTwilight/twilightforest#409]
Forge version: 
Twilight Forest version: build from commit `ffba948` (only test)

Steps to reproduce:
1. explore TF some time
2. crash will not wait long

What happened instead:
Server crash
https://gist.githubusercontent.com/KorDum/134785c86cebc0c85942f9ac74acdd67/raw/e487f592d9ec455e2311c76fb157820cb51b1307/gistfile1.txt

**Comment by Drullkus** [comment]
Server watchdog died. The stacktraces don't even mention Twilight Forest.

**Comment by KorDum** [comment]
But this happens only in TF when researching. In Overworld, NetherEX or The End don't reproduce.
You yourself have not reproduce it? It's enough just to fly around the TF.

I was hoping that my tests would help to release a stable build more so that I could launch players into this world and enable portal.

**Comment by Andromander** [comment]
I have to ask. Where did you get this version of Twilight Forest? 3.6 is unreleased.

**Comment by Tamaized** [comment]
#371

**Comment by KorDum** [comment]
@Andromander as I write in first post, I built it from commit `ffba948` (latest for now) to understand what state the mod is in now.

@Tamaized It looks like though there is a mention of mod in stacktrace.
