### ISSUE TITLE
Server crashed if i enter the Twilight forrest

### ISSUE THREAD

**Issue by PumaBlack** [TeamTwilight/twilightforest#411]
The Server crashes if i enter the forest (loading screen with the magenta colored mystic letters ;) ), or if i walk around in the forest. Any Suggestions? Thanks in advance.

System:
- Minecraft 1.12.2
- Forge 1.12.2-14.23.1.2587
- CTM-MC1.12-0.2.3.12.jar
- twilightforest-1.12.2-3.5.263-universal.jar

Server Crash Log: [https://pastebin.com/z6DJCztx](https://pastebin.com/z6DJCztx)

**Comment by Andromander** [comment]
It looks like the server watchdog has stopped responding. You'll need to adjust timeout settings as referred to in #371

**Comment by Tamaized** [comment]
^
