### ISSUE TITLE
[Minor][Enhancement]: Add OreDict values of "treeLeaves" to Twilight Forest Leaves

### ISSUE THREAD

**Issue by Lanse505** [TeamTwilight/twilightforest#414]
Forge version: 14.23.1.2601
Twilight Forest version: 1.12.2-3.5.263

This issue is being created as a follow-up to a conversation with @Drullkus on Discord.
See Picture: https://i.imgur.com/FtCCYVP.png

Essentially currently TwiFo leaves don't have the "appropriate" leave ore dictionary tag of "treeLeaves" that most other mods tree's use.

**Comment by williewillus** [comment]
wot https://github.com/TeamTwilight/twilightforest/blob/c94a21aead7f1aa90419a7600e382eed93caf428/src/main/java/twilightforest/item/recipe/TFRecipes.java#L23

**Comment by Lanse505** [comment]
let me grab a screenshot

**Comment by Lanse505** [comment]
Okey so it seems to only be specific leaves.

To be more precise:
Thorn Leaves, Beanstalk Leaves and Darkwood Leaves
https://i.imgur.com/pK2iY6d.png
https://i.imgur.com/VIccU8q.png
https://i.imgur.com/wfgGrzs.png

**Comment by Lanse505** [comment]
So this issue "might" be invalid 🤔

**Comment by williewillus** [comment]
Ah no it is valid. Those blocks use a different ID

**Comment by Lanse505** [comment]
Well I meant invalid incase y'all didn't want those things having that oredict :P 
Technically "Giant Leaves" could have that oredict as well but that seems abit redundant

**Comment by Drullkus** [comment]
So I did this in commit a6f2791 and forgot to close, lul
