### ISSUE TITLE
Crash on startup(addMusicType NoSuchMethodError)

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#417]
Forge version: forge-1.12.2-14.23.1.2555
Twilight Forest version: twilightforest-1.12.2-3.6.324-universal
Link to crash log: [crash log](https://gist.github.com/ferreusveritas/ada89fbd1acc46f1dd48bc5a9f32fe61)

Other info: The release version twilightforest-1.12.2-3.5.263-universal starts and runs fine with the mods i'm using.  This seems to be a new bug in the beta version.

Steps to reproduce:
1. Run Minecraft launcher with a modded Forge profile(mods used in crash log)

What I expected to happen:
2. Minecraft finish initializing past the loading screen.

What happened instead:
3. Minecraft will crash before getting to the title screen.

**Comment by bs2609** [comment]
Update to at least Forge version 14.23.1.2599.

**Comment by ghost** [comment]
That was it.  Thanks.
