### ISSUE TITLE
[1.12.2] Sponge-server crash

### ISSUE THREAD

**Issue by Vitali8** [TeamTwilight/twilightforest#419]
Forge version: 2611
Sponge version: 7.1.0-BETA-2884
Twilight Forest version: 3.6.342
Link to crash log: https://pastebin.com/Y5B2rpHC

Steps to reproduce:
1. Launch sponge server with current ver. of TF
2. It crashed

**Comment by ProsperCraft** [comment]
That isn't sponge, it happening with the latest update on forge only-
https://paste.fedoraproject.org/paste/IwDylgqpB8psrvHXkLzFdg

**Comment by williewillus** [comment]
:wotintarnation:
