### ISSUE TITLE
Dark Tower missing Tower Keys

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#42]
Twilight Forest: 2.4.0.5
Forge: 13.20.0.2228

The Dark Tower does not have Tower Keys in loot chests. After checking every room with a chest, none of them seem to have keys.

**Comment by Tamaized** [comment]
Seems the keys are totally missing from the loot table jsons

**Comment by williewillus** [comment]
I converted things as exactly as I could, if someone could hunt down where the keys were being added in 1.7 that'd be great
