### ISSUE TITLE
400+ Naga segements in overworld at 0,0,0

### ISSUE THREAD

**Issue by Brackenpelt** [TeamTwilight/twilightforest#420]
Forge version: 10.13.4.1614 for minecraft 1.7.10
Twilight Forest version: 2.3.7
Link to crash log: https://pastebin.com/WnKwQtSX

Steps to reproduce:
Running a server with Hunters of Sin from the Technic launcher, regularly produces Naga segments to be seen at 0,0,0
Segments are only client side and any form of clearing entities or server side commands affect them
Doesn't really fit into your report labels:
We are using the Hunters of Sin mod pack on the Technic launcher. Over time we started experiencing severe frame lag and in some chunks it dropped to 1 fps or lower. After some investigation into any given error that we could have, the only one happening regularly is that there are roughly 400-500 Naga segments falling form 0,0,0 into the void then respawning to do it all over again.
Picture:
![naga bug](https://user-images.githubusercontent.com/36117240/35772669-06c94a6e-0911-11e8-9744-c30ed4231a4c.PNG)
Video: (people talking kinda loud, take care)
https://www.dropbox.com/s/kclg94mhc8qhsfg/Base%20Profile%202018.02.03%20-%2016.17.54.01.mp4?dl=0

**Comment by Andromander** [comment]
1.7.10 is no longer supported

**Comment by Drullkus** [comment]
That sounds really bad but unfortunately we've dropped support for 1.7.10.
