### ISSUE TITLE
can't play the new release

### ISSUE THREAD

**Issue by EpicKillKitty** [TeamTwilight/twilightforest#422]
Forge version: forge-1.12.2-14.23.2.2611-universal
Twilight Forest version: 1.12.2-3.6.345
Link to crash log: https://gist.github.com/EpicKillKitty/41c0711d3d29adfe40fb36445980174a

Steps to reproduce:
1. Download latest forge (2611); download latest twilight forest (345) download latest ctm (3.12 dependency)
2. put forge into bin folder and other 2 files into mods folder and zip then send to technic via dropbox. 
3. try to play pack via technic launcher

What I expected to happen: Play my pack which only has the twilight forest mod and it's dependency 

What happened instead: I realize this may be user error but i have tried everything i can think of to get the new update to TF into my modpack but when i add the 3 noted files above it's like minecraft decides to skip over the fact that i have forge or any mods installed and just loads up vanilla minecraft. I have been trying to fix this for 4 days now. please help!

**Comment by Drullkus** [comment]
This sounds like it's on Technic. Ask the Technic guys.

[I googled and found a guide for you.](https://technicpack.zendesk.com/hc/en-us/articles/204199345-How-to-make-a-Minecraft-modpack)
