### ISSUE TITLE
Crash with the new version for 1.12

### ISSUE THREAD

**Issue by Kinnalory** [TeamTwilight/twilightforest#423]
Forge version: 14.23.2.2611
Twilight Forest version: 1.12.2 - 3.6.343
Link to crash log: https://gist.github.com/Kinnalory/b954de1b174dfae71aba5b27913b5607#file-gistfile1-txt

Steps to reproduce:
1. Create a portal to twilight forest.
2. Enter it.
3. Try to move arround with some tinker's weapons or tools.
4. Get disconnected message and be kick from your game, to never return, losing your save.

What I expected to happen: Enter twilight forest and have wonderful adventures.

What happened instead: Enter twilight forest and crash horribly.

**Comment by Drullkus** [comment]
Update to 345
