### ISSUE TITLE
Error when using magic beans on uberous soil.

### ISSUE THREAD

**Issue by Exanadu** [TeamTwilight/twilightforest#424]
Forge version: 
Twilight Forest version: 1.12.2 3.5.263
Link to crash log:  https://pastebin.com/BNbYk1Xa

Steps to reproduce:
1.  Attempt to plant magic beans in uberous soil

What I expected to happen: Grow beanstalk.

What happened instead: Server had to be rebooted due to lag from the errors.

**Comment by Drullkus** [comment]
[Try updating to the latest version](https://minecraft.curseforge.com/projects/the-twilight-forest/files)

Also please give us the full error log, since it reveals more details than just the stacktrace.

**Comment by Tamaized** [comment]
was fixed long ago: 91143da412a34d5b76cfaf56a93665862a2df7c7
