### ISSUE TITLE
The lightning stroke that opens a portal to the Twilight Forest starts fires.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [TeamTwilight/twilightforest#425]
Forge version: 14.23.1.2608
Twilight Forest version: 3.6.324, though I noticed it in a a build from October (either 3.1.128 or 3.2.155) as well.

Steps to reproduce:
1.  Assemble a portal to the Twilight Forest. Size/shape does not appear to matter.
2. Toss a diamond into the water to summon a bolt from the blue and open the portal.

What I expected to happen:
Stroke of lightning might damage me (it usually does) but it's never set anything on fire before.

What happened instead: Stroke of lighting sets one or more of the flowers on fire. The portal doesn't fail if the vegetation is burned away, but it's still a hazard.

[modlist.txt](https://github.com/TeamTwilight/twilightforest/files/1697919/modlist.txt)

**Comment by Andromander** [comment]
The lightning to the portal does that. I would say not a bug, but I'm not sure if the devs will change it.

**Comment by liach** [comment]
Yeah, the portal would only fail if you remove grass blocks around the portal.

**Comment by Scorch-Mechanic** [comment]
The thing I'm reporting isn't the portal not failing, the thing I'm reporting is the fire. My experience with literally every single other Twilight Portal I've opened, since I started playing Twilight Forest back in 1.4.6 (roughly) has been completely without minor conflagrations. I'll grant it's possible I've just had incredibly strange luck, but this is still a different result than I've had before. If it's a bug it should be squashed. If it's not or it won't be, so be it. Either way is fine by me, it's not a big deal either way.

**Comment by Drullkus** [comment]
Commit 9ef2f0a should handle this fine. If you don't like lightning zapping you or setting things on fire then you can edit it in config for it to not to.

**Comment by Scorch-Mechanic** [comment]
I've played my fair share of Dwarf Fortress, ain't nobody can say I don't like Fun. The issue I brought up is addressed now though, so I'll take the fix happily, and leave the true thunderbolt in. Far as I'm concerned, it ain't Twilight Forest if you don't pay to enter in blood.

**Comment by Drullkus** [comment]
> `it ain't Twilight Forest if you don't pay to enter in blood.`

Niiiiice.

**Comment by Scorch-Mechanic** [comment]
Thank you. Seriously, I appreciate it. I tend to make my bases in forests.
