### ISSUE TITLE
Magic Map position indicator stops working after using a Twilight Forest portal.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [TeamTwilight/twilightforest#427]
Forge version: 14.23.1.2608
Twilight Forest version: twilightforest-1.12.2-3.6.345-universal

Steps to reproduce:
1. Have a Magic Map that you have used at least once (i.e. is not blank).
2. Step through a portal to the Twilight Forest. 

What I expected to happen:
Player position indicator functions at all times.

What happened instead:
Upon passing through a portal to the Twilight forest, the player position arrow will not update to show heading or position. Instead, it stays frozen, and does not rotate or move. Saving, quitting, and reloading while inside the Twilight Forest dimension will cause the arrow to function correctly until the next time I use a Twilight Forest Portal.
[modlist.txt](https://github.com/TeamTwilight/twilightforest/files/1713971/modlist.txt)

**Comment by Andromander** [comment]
Can verify. This issue is more than likely related to Twilight Forest.

**Comment by LickitySplit74** [comment]
Having same exact issue as Scorch-Mechanic in the SevTech ages pack.
