### ISSUE TITLE
Chest won't open

### ISSUE THREAD

**Issue by MaybeitsTreybelline** [TeamTwilight/twilightforest#430]
There is a bug with chests when right clicking the chest will not open.

**Comment by Andromander** [comment]
Did you make sure there was space to open the chest?

**Comment by MaybeitsTreybelline** [comment]
Yes, no block above it

**Comment by Andromander** [comment]
Can you give a Forge Version, Twilight Forest version, and the other mods you have installed

**Comment by MaybeitsTreybelline** [comment]
forge: 1.12.2 -14.23.2.2611, TF: 1.12.2-3.6.345, Optifine: 1.12.2 HD U C7

**Comment by Drullkus** [comment]
Are you on a server? Can you send a screenshot of this?

**Comment by bs2609** [comment]
Issue with that version of OptiFine I believe.

**Comment by MaybeitsTreybelline** [comment]
I figured it out, it was the Optifine version
