### ISSUE TITLE
Penguins in Twilight Glacier lower FPS

### ISSUE THREAD

**Issue by DJJBanx** [TeamTwilight/twilightforest#432]
##Forge version: 14.24.2.2618
##Twilight Forest version: 3.6.324
##Pack: Interaction 0.12
##Mod List: https://minecraft.curseforge.com/projects/interaction (In case its mod conflicts)

The penguins in the biome Twilight Glacier are causing a huge amount of frame rate lag. Either you're rendering the penguins in like 20 different sections or the penguin's AI is way more complex than meets the eye. Penguins are evil though so I understand if this is an intended mechanic.

The lastest log does not mention anything about rendering or penguins or Twilight Forest so I did not include it, but I can get it to you if you need it.

##Video:
https://streamable.com/v8eza

##Steps to reproduce:
1. Go to the biome with all the evil penguins. (Twilight Glacier)

##What I expected to happen:

I expected the game to be playable.

##What happened instead:

My frames per second turned into seconds per frame.

**Comment by williewillus** [comment]
run a profiler on both sides using `/debug`, Sampler, or WarmRoast and post the results

**Comment by Hjaldar** [comment]
Using sampler helped me identify the culprit as [roughmobs](https://minecraft.curseforge.com/projects/rough-mobs), which the author admits has performance issues.

I can't upload .nps here, so here is a screenshot:
https://i.imgur.com/L8pX1h9.png

One additional possible clue... when I removed roughmobs to confirm it as the culprit and loaded in the world, all the penguins I could see furiously flapped their arms for about 5 seconds and then settled down, like they were catching up on something.

**Comment by williewillus** [comment]
so this isn't a TF issue then (the penguin AI is quite tame, really, not much more intense than a normal vanilla animal)
