### ISSUE TITLE
Server immediately crashes when entering twilight forest with spongeforge

### ISSUE THREAD

**Issue by LuminescentMoon** [TeamTwilight/twilightforest#433]
Forge version: 2611
Twilight Forest version: 1.12.2-3.6.345
Link to crash log: https://hastebin.com/obaniqujic.vbs
Link to mod list: https://hastebin.com/yimepasuju.vbs

Crash happens even with thebetweenlands or foamfix removed.

Steps to reproduce:
1. Create twilight forest portal.
2. Enter it.

What I expected to happen:
Load into the twilight forest.

What happened instead:
Server immediately crashes.

**Comment by Andromander** [comment]
Can you try it without OTG? Just curious.

**Comment by LuminescentMoon** [comment]
@Andromander doesn't crash when OTG is removed.

It's interesting to note that this issue does **NOT** occur when entering a portal from [The Betweenlands](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod), a mod similar to Twilight Forest in that it adds a new world that has its own separate content.

Posted on PG85/OpenTerrainGenerator#141
