### ISSUE TITLE
Fiery Metal Block Model is bugged

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#435]
Forge version: 14.23.22613
Twilight Forest version: (3.6.345)
CTM lib(0.2.3.12)

What I expected to happen:That the fiery Metal block renders properly with ctm

What happened instead:some parts kinda got transparent

**Comment by Drullkus** [comment]
Do you have pictures? You’re reporting a visual problem but giving us no visual evidence of the problem.

**Comment by ghost** [comment]
[1](https://imgur.com/rPP8jF6) 
[2](https://imgur.com/xh6Cl6y)
[3](https://imgur.com/KwjRnuc)
[4](https://imgur.com/H8DWxCH)
[5](https://imgur.com/Q6sG0NX)
sorry forgot the pictures

**Comment by Tamaized** [comment]
Besides the weird lighting, this is how they're supposed to look.

**Comment by Drullkus** [comment]
Intentional, the inverted quads make it look like it has a line around it. The lighting is a different issue and is on CTM to be fixed.

**Comment by CTH999** [comment]
Reporting it to CTM
