### ISSUE TITLE
Player kick when logging into a server.

### ISSUE THREAD

**Issue by lryanle** [TeamTwilight/twilightforest#436]
Forge version: 14.23.2.2616
Twilight Forest version: MC1.12 3.6.345
Link to crash log: (Sorry, I can't post in text form! Server provider doesn't give it in text! ;) ) https://cdn.discordapp.com/attachments/256495203874111488/418256222207213579/Screen_Shot_2018-02-27_at_11.00.28_PM.png

Steps to reproduce:
1. Log into server
2. Get timed out.

What I expected to happen:
I should have logged into the server just fine.

What happened instead:
I get timed out almost instantly. The Twilight Forest login screen only pops up for a few seconds..

Notes:
1. Before I installed twilight forest everything was fine.
2. After the mod is removed, everything turns fine.
3. I only get crashed when I go inside the portal, yet it doesn't seem like I can come out.
4. The pack I'm using is very heavy on mods, if that helps.

**Comment by Tamaized** [comment]
Seems the player saved nbt data got too large to send over the network. Not related to TF at all.

Although the fact removing TF solves the issue, that's... odd.

**Comment by Drullkus** [comment]
Send player NBT file

**Comment by williewillus** [comment]
It's a chat packet though, unless we send a ginormous message on logon?

**Comment by Tamaized** [comment]
Oh whoops didn't notice that, and no we don't.. at least i'm pretty sure we don't

**Comment by lryanle** [comment]
https://cdn.discordapp.com/attachments/256495203874111488/418574717700800523/lryanle.dat
https://cdn.discordapp.com/attachments/256495203874111488/418574770578259968/c46772dd-0061-48d1-b788-3577f57ea20a.json
https://cdn.discordapp.com/attachments/256495203874111488/418574848730726411/c46772dd-0061-48d1-b788-3577f57ea20a.dat

One of these should be it! Sorry, I'm not really good with these things. :(

**Comment by bs2609** [comment]
This seems like a JourneyMap issue - it looks like that's the mod sending the oversized string.
