### ISSUE TITLE
Major lag issues and framerate drops into single digits

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamTwilight/twilightforest#437]
Minecraft: 1.12.2
Forge version:  14.23.2.2624
Twilight Forest version: 3.6.345
Link to fml log: https://gist.github.com/DatrixTHLK/23c4369bb64ecb3ea2d2c82f508822a4

I don't have any crash reports as the game didn't crash but remained very slugish while loading in the chunks compared to when the mod was removed.

Now before someone spouts out that I need a faster computer, My computer has 8GBs of ram my graphics card is an R9 290X Series AMD Radeon The processor is Quadcore. My computer can handle as many as 140 mods. This mod in particular is what's causing the issues within the game not my computer.

Steps to reproduce:
1. Start up minecraft
2. Hit new game
3. Going into the world with
4. Experiencing huge Framerate spikes/drops down to at least 5fps with this mod installed
[Picture Here](https://imgur.com/a/Rnw3R)

5. Without I have at least 30fps
[Picture Here](https://imgur.com/a/ItZTf)
Link to fml log: https://gist.github.com/DatrixTHLK/891869a8843b91a2390063e28affcf32

What I expected to happen:
Frame rate to stay around 30fps and game not be so slow when loading in

What happened instead:
Frame rate didn't even go past 10fps and game was very slugish when loading in.

**Comment by Andromander** [comment]
Can you provide a debug profile and the system details?

Debug profiling can be done by using `/debug start` and `/debug stop` to create a profile which is saved to the debug folder. While you may have given us some computer specs, a crash report will give us some more details, which can be done by holding `F3+C` for 10 seconds and releasing.

From a standpoint view, it looks like Minecraft is trying to do too many processes at once, which may be caused by too many mods, or certain mods using too much memory.

**Comment by DatrixTHLK** [comment]
Would a crash log help at all? I did the steps you provide me to do within the game and within 10 seconds the game crashed.
Crash log: https://gist.github.com/DatrixTHLK/723c6c96bf5436b25b0e4ad6b832d73d

**EDIT:** I took out Biomes O'plenty and the Framerate jumped back to 50-60fps. Before it was spiking and dropped down to the single digits often. Now rarely does it. I don't get it...

**Comment by Andromander** [comment]
I would also suggest removing Optifine and adding BetterFPS and FoamFix. As much as Optifine says it improves performance, sometimes performance is worse with it.

**Comment by DatrixTHLK** [comment]
Thanks for the info. I'll test this out now and see what happens. 

**Edit:** It seems to work much better than Optifine. Thanks again.
