### ISSUE TITLE
Crahses

### ISSUE THREAD

**Issue by StardustSys** [TeamTwilight/twilightforest#439]
Forge version: 
Twilight Forest version: 1.12.2

When i played this it crashed my minecraft i dont know if it was a mod incompatibility or what but i wouldn't let me access my crash log either if you think a list of the mods i was using with it would be helpful ask i really want to use this mod :(

**Comment by Tamaized** [comment]
can't help without the log, and it should generate in your minecraft run directory/crash-reports/

**Comment by Drullkus** [comment]
No response and ambiguous issue - closing
