### ISSUE TITLE
Mayapple is missing texure and wrong breaking sound

### ISSUE THREAD

**Issue by jambonmcyeah** [TeamTwilight/twilightforest#44]
Twilight Forest: e9b64e1
Forge: 13.20.0.2228

![image](https://user-images.githubusercontent.com/21069675/27265456-4e2a3c90-5464-11e7-8804-d9b7f9df3ff8.png)

**Comment by Tamaized** [comment]
Sound issue is fixed in 14bbb309d54baad50874734db9575f3c9c5d83fd

@Drullkus does this still need to be open?
