### ISSUE TITLE
[DW20] MP Server, hunger effect not disappearing from Swamp after Lich

### ISSUE THREAD

**Issue by Koyoss** [TeamTwilight/twilightforest#440]
Forge version: 2601
Twilight Forest version: 3.5.263
Link to crash log: 

Steps to reproduce:
1. Kill Naga
2. Kill Lich
3. Go to swamp, hunger effect remains.

What I expected to happen:
Hunger effect to disappear

What happened instead:
Hunger remains, but the visual effect is gone.

I've looked for many solutions to this, including trying to drop the items and picking them up again, but I haven't found a solution.
I've killed several lichs now in an attempt to fix the problem. 
![image](https://user-images.githubusercontent.com/22041700/37088022-f84dbffc-21c9-11e8-90da-d0f0f6fa3b2a.png)
This is what my advancements look like.

**Comment by Andromander** [comment]
Can you try updating the Twilight Forest version? You have an outdated version

**Comment by Koyoss** [comment]
I'm playing on the direwolf modpack, so I can't since I'm on a multiplayer server for it until the server and the modpack updates unfortunately...

**Comment by Tamaized** [comment]
Is this still an issue on the latest builds?
