### ISSUE TITLE
Knight forest/Urghast tower zone edge bug

### ISSUE THREAD

**Issue by VallenFrostweaver** [TeamTwilight/twilightforest#442]
Forge version: 14.23.2.2617
Twilight Forest version: 1.12.2-3.6.345
Link to crash log: n/a

Steps to reproduce:
1. Normal Twilight progression up to Knight's forest but not Urghast tower yet.
2. Go into a Knight's forest maze entrance not far from a zone edge that hasn't been unlocked yet (like the Urghast tower) and if you get close you get the usual kobold spawning with a book and the maze gets cut off by unbreakable bars/walls. The mobs near that area are invincible and I didn't know I was too close as I didn't venture further in, just tried to go around. I was picked up by a pincer bug and held there but couldn't hurt it. I was more or less stuck there until I either die or cheat my way out.

What I expected to happen:
To be able to kill the pincer bug on the outside of the "locked" zone.
What happened instead:
The pincer bug was invincible.

**Comment by Tamaized** [comment]
We've done all we could for this, see #1487
