### ISSUE TITLE
Plants Plantability

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#447]
The following blocks can be planted on any block, but will disappear after a couple of seconds.
 - Mayapple
 - Clover Patch
 - Fiddlehead
 - Forest Grass
 - Dry Bush

Fiddlehead is the only one that drops itself afterwards, see issue: #192

Perhaps having them be plantable on any block could be a feature instead of a bug for aesthetic reason.

**Comment by bs2609** [comment]
Most likely caused by this:
https://github.com/TeamTwilight/twilightforest/blob/8f5f5026d663cac4c64e2ac4bfc95690d0cda6fb/src/main/java/twilightforest/block/BlockTFPlant.java#L83-L93

Will probably resolve itself when the block gets "flattened" (#358).
