### ISSUE TITLE
TPS drop when teleport in/out twilight

### ISSUE THREAD

**Issue by Reizenkun** [TeamTwilight/twilightforest#449]
Forge version: 2611
Twilight Forest version: 345

Steps to reproduce:
1.  Rapid travel across worlds with using portal

What I expected to happen:
Day ago i installed twilight forest on my server and noticed massive TPS drop when i entering in portal in/out twilight world, i look into source code and find one strange thing in placeInExistingPortal method, namely very big chunk load on teleportation, i tried to set scan radius to 32 blocks and lags disapear, maybe it would be better to reduce scan radius or somehow resolve problem with lags on teleportation?

**Comment by kwetroi** [comment]
up

**Comment by bs2609** [comment]
There have been a couple of changes recently that should help with this (eg 10cb6286c0328d742c2f6c514a7facd5372917be).

The latest dev builds are available here: http://builds.steamnsteel.info/browse/TF-ONETWELVE/latest/artifact, you can try them and let us know if you see an improvement.

**Comment by kwetroi** [comment]
Thanks It works.

**Comment by bs2609** [comment]
Good, thanks for checking!
