### ISSUE TITLE
Naga Kill did not get accounted

### ISSUE THREAD

**Issue by MSar70** [TeamTwilight/twilightforest#452]
Forge version (mod loader): 7.10.99.99
Twilight Forest version: 2.3.7
Link to crash log: no crash log

Steps to reproduce:
Not sure it can be reproduced, since I do not want to try it again on a second naga. But I think, this is what happened.

Playing minecraft sky (tekkit-launcher, mod pack, by Skate708), using the "Key to King's Law" (Botania, r1.8-249) while standing on a Greatwood Tree (Thaumcraft, 4.2.3.5) which spawned inside the Naga arena. The naga did not seem to get to know who shot it, so after the kill, it just exploded, did not drop any scales nor experience points.
Next time I will give the killing blow while standing on one of the pillars and hope it gets accounted for this time.
Minecraft: 1.7.10

What I expected to happen:
To get experience, scales and the achivement Naga Hunter.

What happened instead:
Nothing of the expected, the Naga just vanished.

**Comment by Hubry** [comment]
1.7.10 is not supported for ages now... try to reproduce it on 1.12.2 - a creative world will make that easy.

**Comment by MSar70** [comment]
Since it is part of a mod-pack, difficult to update the minecraft version, since the mod-pack is bound to this version.
It seemingly is an issue with the height I had while killing the Naga. Killed 2 more now, standing on the provided pillars, and got the achivement Naga Hunter, but did not get scales.
Since one can get the achivement, the bug is rather a "nice to know, and look into it, if time and mood allows" than a "needs to be fixed urgendly".

**Comment by Tamaized** [comment]
Pick up the trophy. Anyway yea, 1.7.10 is not supported.
