### ISSUE TITLE
Winter Wolf breaks with Wolf Armor and Storage Installed

### ISSUE THREAD

**Issue by Ghostrider231** [TeamTwilight/twilightforest#455]
Forge version: 14.23.2.263
Twilight Forest version: (1.12.2 - 3.6.345)

Incompatible with: wolfarmor-1.12.2-2.1.0.24-RELEASE.jar 

Most of these issues are very related to issue https://github.com/TeamTwilight/twilightforest/issues/395

I've also experienced the same issue, but something worth pointing out on a separate report. Interestingly enough, this problem doesn't persist on Mist Wolves or Hostile Wolves.

If you attempt on trying to spawn the Winter Wolf via spawn eggs or commands, It won't work. Again, I don't have time atm to check the 'latest.log' in my other computer to see what's going on.

Also if you try to wander aimlessly around in the Snowy Forest Biome, while NOT being in peaceful mode the game tries to spawn a winter wolf, but crashes instead with the same issue.

Having only Twilight Forest and Wolf Armor and Storage will only break the Winter Wolves but won't crash the game. (I can't verify if this is true, it could crash still)

----
Here's how you can repeat the problem:
1. Twilight Forest should be installed.
2. Have the Wolf armor and Storage Mod installed.
3. Enter the Twilight Forest.
4. Go or teleport to any Snowy Forest Biome while being on Easy, Normal, or Hard mode.
5. Wander around aimlessly in the Snowy Forest Biome.
6. The game will very likely crash shortly once a Winter Wolf tries to spawn.

----

**Update: Winter Wolves with the wolf armor mod installed seems to be working again. (Winter wolves can spawn again) It seems another mod is actually helping from keeping the crash from happening. I may need to test some more to see what mod is dispelling the crash. So i could post which mod is helping to keep the crash away.** 

**Update 2: I don't know If anyone is still looking into this, but I'm gonna reference to the Wolf armor's issue tracker side as well: https://github.com/CenturionFox/wolfarmor/issues/44**

**Comment by bossbasslol** [comment]
This is exactly what happened to me. Here is the specific crash report, but I have other mods present, **INCLUDING** Wolf Armor and Storage: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.3-core.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 3/24/18 9:20 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:229)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:229)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)

-- Affected level --
Details:
	Level name: FoolWithTheWrist
	All players: 1 total; [EntityPlayerMP['bossbasslol'/337, l='FoolWithTheWrist', x=553.21, y=32.00, z=-780.20]]
	Chunk stats: ServerChunkCache: 268 Drop: 0
	Level seed: 939673229
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 320440872 bytes (305 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 38
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 Optifine OptiFine_1.12.2_HD_U_C8_pre 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version              | Source                                        | Signature                                |
	|:--------- |:----------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2               | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp               | 9.42                 | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99            | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.2.2624         | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0                  | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | auginter          | 1.1.0                | auginter-1.1.0-1.12.x.jar                     | None                                     |
	| UCHIJAAAA | codechickenlib    | 3.1.5.331            | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | enderstorage      | 2.4.2.126            | EnderStorage-1.12.2-2.4.2.126-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | magicmirror       | 1.0                  | magicmirror+1.1+[1.12].jar                    | None                                     |
	| UCHIJAAAA | thebetweenlands   | 3.3.3                | TheBetweenlands-3.3.3-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAA | torohealthmod     | 1.12.2-11            | torohealth-1.12.2-11.jar                      | None                                     |
	| UCHIJAAAA | twilightforest    | 3.6.345              | twilightforest-1.12.2-3.6.345-universal.jar   | None                                     |
	| UCHIJAAAA | wolfarmor         | 1.12.2-2.1.0-RELEASE | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar         | None                                     |
	| UCHIJAAAA | worldedit         | 6.1.8                | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| UCHIJAAAA | xray              | 1.4.0                | xray-1.12.2-1.4.1.jar                         | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.3-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['bossbasslol'/337, l='FoolWithTheWrist', x=553.21, y=32.00, z=-780.20]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by satyrnidae** [comment]
Definitely a problem with my mod.  The HAS_CHEST / ARMOR_ITEM DataParameter ID is conflicting with BREATH_FLAG from EntityTFWinterWolf.  Formulating a fix on my end.

**Comment by Ghostrider231** [comment]
Thank you @CenturionFox, the new version seems to fix the Winter Wolf Bug. Closing the issue.
