### ISSUE TITLE
Several Scepter Issues

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#456]
- Scepters are unable to be repaired when enchanted.
- Scepters are unable to be repaired when they have any amount of durability left.
- Zombie Scepter breaks when used at 0 durability and spawns a 10th Loyal Zombie in the process.

- Scepter of Life Draining should not get continuously lowered and brought back up when holding down the use key to draining life, instead it should be doing the bow drawing animation when the use key is held over a mob.
It does this properly in Creative, just not when it loses durability.
The reason for this being included is because it looks jarring and makes the Scepter overall feel less impactful and of lower quality.

**Comment by Tamaized** [comment]
Point 2 was originally intended but we're gonna change that.

**Comment by bs2609** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4834 should allow a proper fix for point 4.
