### ISSUE TITLE
Flashing Yellow Squares

### ISSUE THREAD

**Issue by Immaculala** [TeamTwilight/twilightforest#458]
I’m having a graphics issue with TF.
It has not happened with any other mod.
These flashing yellow square outlines appeared as I approached a Swampy Labyrith (see image).
It has also occurred when near a 'castle'.
It goes when I leave the area.
Turning particles down to minimal didn’t help.
It only occurs in Survival mode, not in Creative mode.

twilightforest-1.12.2-3.6.345-universal
Forge 1.12.2-14.23.2.2611

CPU: Intel Core i7 7700K @ 4.20Ghz
RAM: 16GB
OS: Win 10 64 bit
Gfx: Nvidia GeForce GTX 1080 (drivers up to date)
2GB RAM allocated to MC )increased it to try but no change)

<img width="748" alt="2018-03-24_17 38 58" src="https://user-images.githubusercontent.com/26187212/37872850-d23ed19c-3007-11e8-820b-156f9d40349c.png">

**Comment by Andromander** [comment]
This is because you are in a restricted area. Not a bug

**Comment by Immaculala** [comment]
Ah, so I need to do something before enterring the area?

**Comment by Andromander** [comment]
Assuming from where you are, you need to slay the Lich, which also requires slaying the Naga

**Comment by Immaculala** [comment]
Thanks Andromander.
