### ISSUE TITLE
1.12.2-3.6.345 Entering the forest and crashing

### ISSUE THREAD

**Issue by Wiral2** [TeamTwilight/twilightforest#459]
Forge version: 
Twilight Forest version: (1.12.2-3.6.345-universal)

Steps to reproduce:
1.  Enter the Twilight Forest

What I expected to happen: Not crash

What happened instead: Crashed and got this: 
https://gist.github.com/Wiral2/e41fefb61dddd52b5c7428fdd2c7672b

**Comment by Ghostrider231** [comment]
Techguns is most likely causing that crash, normally happens if you have your global spawnweight set to 0 in the techguns config.

Relate to this: https://github.com/pWn3d1337/Techguns/issues/132

**Comment by Wiral2** [comment]
Thanks! I fixed the problem by changing the spawnweights

**Comment by Killer-Demon** [comment]
Issue was resolved.

**Comment by momocow** [comment]
Anything else of Techguns configs beside `"Techguns Spawnweight NEther` and `Techguns Spawnweight Overworld` did you change to solve this problem?
Setting both of them to 1 should fix the problem, right?
