### ISSUE TITLE
Server Crash, ticking entity

### ISSUE THREAD

**Issue by walker-dev** [TeamTwilight/twilightforest#460]
Forge version: 1.12.2-14.23.2.2640
[crash-2018-03-30_01.44.37-server.txt](https://github.com/TeamTwilight/twilightforest/files/1862310/crash-2018-03-30_01.44.37-server.txt)

Twilight Forest version: (364)

**Comment by Tamaized** [comment]
Another mod is using an invalid SpawnListEntry weight value, see #459 

I would track down which mod is the cause and report it to them.
As this isn't TF's end.

**Comment by walker-dev** [comment]
I do not crash when entering the twilightforest dimension, but after we killed hydra

**Comment by bs2609** [comment]
Not really a Twilight Forest issue, I'm afraid.
