### ISSUE TITLE
Make Fiery Tools glow in Dark

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#461]
Made possible via MinecraftForge/MinecraftForge#4700

**Comment by bs2609** [comment]
Linking https://github.com/MinecraftForge/MinecraftForge/pull/5047 here for reference.

**Comment by Drullkus** [comment]
So unfortunately Trophies CANNOT be TEISRs yet, since we don’t get the transform type enum.

**Comment by Shadows-of-Fire** [comment]
You can store the transform type from handlePerspective, since its always called before rendering.
