### ISSUE TITLE
Crash on Startup without Tinkers Construct

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#464]
Forge version: 14.23.2.2641
Twilight Forest version: 3.6.372
Link to crash log: https://gist.github.com/Hubry/2d3164c7d60b40ef61ff11255fc649f7

```
Hubry - Today at 9:50 PM
Drull, you added a dependency on TiC :(
```

Tinkers Construct is not a present mod, causing the game to crash due to a non-existent class.

**Comment by Tamaized** [comment]
fixed in bd795156a00a245d0c4b253dda4aa4d610168b90
