### ISSUE TITLE
Portal generated under water

### ISSUE THREAD

**Issue by daddy77gaming** [TeamTwilight/twilightforest#465]
Forge version: 14.23.2.2635
Twilight Forest version: 1.12.2-3.6.345-universal
Pack: SevTech Ages including optifine and SEUS shaders

Upon Entering the portal for the first time, i got teleported back to the overworld almost instantly again, took me a bit to realize i was pushed into the portal straight away on the other end.. then took me a while to not be ported back instantly.
Played quite a few packs with twilight in it, first time seeing this happen.

![2018-03-31_13 25 26](https://user-images.githubusercontent.com/31905330/38163199-17062022-34f0-11e8-8670-b7611e598787.png)

**Comment by Andromander** [comment]
Can you supply the seed for the world and the co-ordinates of each portal block?
Also, and it's just for a theory of mine, what difficulty were you in when you first entered the portal?

It's not the easiest issue to replicate, and we need some specifics to see if this issue can be reliably replicated.

**Comment by daddy77gaming** [comment]
![2018-03-31_13 51 14](https://user-images.githubusercontent.com/31905330/38163361-2335401e-34f3-11e8-8c18-6b0a6a147e8c.png)

Sevtech has coordianted locked until further progression, so need to copy save and go into cheat mode to get them coordinates.

Also reported issue to sevtech github, maybe some changes they made caused this.

**Comment by daddy77gaming** [comment]
Twilight location is x35 z171 y30 and x38 z168 y30
overworld location is x46 z168 y 63 and x49 z171 y63

**Comment by bs2609** [comment]
Should be ok now:
![2018-06-01_05 18 55](https://user-images.githubusercontent.com/1447117/40821528-6786322c-655f-11e8-8c71-d92b471996fb.png)
