### ISSUE TITLE
Minor Typo in description of Mighty Stroganoff 

### ISSUE THREAD

**Issue by Jandakast** [TeamTwilight/twilightforest#467]
Forge version: 14.23.2.2635
Twilight Forest version: 3.6.345

Steps to reproduce:
1. Look at the Mighty Stroganoff Achievement 
2. See mushroom is spelled incorrectly.

**Comment by Tamaized** [comment]
`musroom`... nice
https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/resources/assets/twilightforest/lang/en_us.lang#L68
