### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Nicon4454** [TeamTwilight/twilightforest#469]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1.  Go in to the portal

What I expected to happen:
to go in to the twilight forest
What happened instead:
Server Crashed.

Crash Report
https://pastebin.com/fc3EniY1

MC 1.12.2
MC Log https://pastebin.com/HsM61WXv
twilightforest-1.12.2-3.6.345-universal
forge-1.12.2-14.23.2.2651-universal

**Comment by Tamaized** [comment]
`Invalid dimension id 144`

**Comment by Tamaized** [comment]
Also your crash report and MC logs are different, the crash report states invalid dimension ID however the MC Log states your server shutdown for taking too long on a single tick (60 seconds). See #371

**Comment by Nicon4454** [comment]
ok thank  you it is a conflict with compactmachines3-1.12.2-3.0.7-b197 so i changed the dimID
