### ISSUE TITLE
Server crashing in Twilight Forest when breaking leaves with Terraqueous 

### ISSUE THREAD

**Issue by xun468** [TeamTwilight/twilightforest#472]
Forge version: 14.23.2.2630
Twilight Forest version: 3.6.345
Link to crash log: https://pastebin.com/RMqnyfKY

Steps to reproduce:
1. Player is breaking leaves in the Twilight Forest, it does not happen every time they break a leaf but two crashes happened after a leaf was broken and the crash logs are identical. 

This has been crossposted with Terraqueous as well

**Comment by Tamaized** [comment]
Cross Link: ShetiPhian/Localizations-and-Issues/issues/174

**Comment by williewillus** [comment]
easily fixed on our side, but calling getpickblock in a harvestdrops handler is a bit...strange to say the least
