### ISSUE TITLE
The advancement is not yet initialized

### ISSUE THREAD

**Issue by iridium34** [TeamTwilight/twilightforest#473]
Forge version:  14.23.2.2645
Twilight Forest version: 1.12.2-3.6.345
Link to crash log: https://gist.github.com/iridium34/1378bfd10161c1e1859d84dfb80d4dcf

Steps to reproduce:
1. moving in Twilight Forest Dim
or
1. login while in Twilight Forest Dim

**Comment by bs2609** [comment]
That's coming from Sponge code (https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/advancement/MixinAdvancementProgress.java#L254), can you reproduce without Sponge?

**Comment by iridium34** [comment]
Without Sponge it doesn't crash.

**Comment by bs2609** [comment]
In that case, report it there: https://github.com/SpongePowered/SpongeForge/issues
