### ISSUE TITLE
Improvement: Add Nightkosh's gravestone block to default config

### ISSUE THREAD

**Issue by Geethebluesky** [TeamTwilight/twilightforest#477]
Related to #283. This isn't a bug, just suggesting that the initial configuration file could also include the block **gravestone:gsgravestone** as part of the default blocks blacklisted from the anti-builder, for obvious reasons.

(Mod I'm talking about is [this one](https://minecraft.curseforge.com/projects/gravestone-mod-graves?gameCategorySlug=mc-mods&projectID=62929).)

**Comment by Tamaized** [comment]
I more or less put tombmanygraves as a default in there as an example for users/packdevs to add other mods to the config themselves.

**Comment by Andromander** [comment]
Closing as compatibility can be added via Tag. Unfortunately, we can't really add every gravestone mod.
