### ISSUE TITLE
Giant Log textures are misaligned

### ISSUE THREAD

**Issue by tahg** [TeamTwilight/twilightforest#478]
Forge version:  2651
Twilight Forest version: (this is the build number) 3.6.345
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline) N/A

Steps to reproduce:
1.  Place a Giant Log

What I expected to happen:  The textures should all line up correctly.

What happened instead: The top texture is off by 1 block in the z direction. The bottom texture is off by 2 blocks in the z direction.

**Comment by theishiopian** [comment]
Pictures?

**Comment by Drullkus** [comment]
@theishiopian No need, I know the issue and have a partial fix in a dep, I just need to implement the fix in TF.

**Comment by theishiopian** [comment]
Ah, just trying to help :)

**Comment by bs2609** [comment]
This fixed by b344af81d43844c267979a972e68ccc352dbf429?
