### ISSUE TITLE
Giant Skins [Suggestion]

### ISSUE THREAD

**Issue by tahg** [TeamTwilight/twilightforest#479]
When running on a server, and there are names in the OP list, use those player skins to randomly texture the giants.

**Comment by theishiopian** [comment]
Or maybe just grab random ones from the skin database. Or even better, use the skins of donators.

**Comment by Drullkus** [comment]
Not sure about the donors list skins or random skins from Mojang (there are chances of inappropriate ones) but I can do a config-based list of skin UUIDs, as well as the Op list.

**Comment by theishiopian** [comment]
Ooh, good point on the random skins. I forgot that some people have nothing better to do.

**Comment by jodlodi** [comment]
Implemented in e637204933c0fbeaf32b1cfe3ce9b1f3cd430985.
There is now a setting in the client config that lets you insert player UUIDs for the giants to reference.
