### ISSUE TITLE
[12.2.2] Final Tower generation error in server log

### ISSUE THREAD

**Issue by Geethebluesky** [TeamTwilight/twilightforest#480]
Forge version:  forge-1.12.2-14.23.3.**2655**-universal.jar (most recent recommended, running the server)
Twilight Forest version: **twilightforest-1.12.2-3.6.345-universal.jar**
Link to crash log: [Gist](https://gist.github.com/Geethebluesky/64829c38bda5a842b483779c4d818bad) starting at line **767**.

Steps to reproduce:
1. Told chunk pregen to generate a new Twilight region file bordering already-explored locations. Just happened to hit the coordinates for the Final Tower.

I did this specifically because worldgen causes big FPS drops with my mod list and pregenerating the world is one of the ways to avoid that, so I like to explore already-generated maps.

What happened:
- Upon starting final tower generation, the server log gets spammed with the following:
[11:28:57] [Server thread/WARN] [twilightforest]: Final Castle tower has null for glyph color, this is a bug.

Possibly related to #63 and/or #399? I'm absolutely not sure about that.

I don't mind deleting the region file and restarting since nobody is about to explore that far out yet in Twilight, we're just starting the progression.

**Comment by Andromander** [comment]
From what I understand, this no longer happens in 1.16. The error itself is harmless and nothing happens as a result of it.
