### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Pirog17000** [TeamTwilight/twilightforest#486]
Forge version: 1.12.2 (feb stable build)
Twilight Forest version: 1.12.2-3.6.345

Steps to reproduce:
1. Go into TL dimension (better 3-4 people at least) and run in different areas at the same time.

What I expected to happen:
Good Performance

What happened instead:
![image](https://user-images.githubusercontent.com/3022852/39422711-3c4a0bfc-4c77-11e8-9a2a-c289e73a70db.png)

**Comment by Andromander** [comment]
Please install Forge Version 14.23.3.2675, as it fixes the lighting issues that vanilla causes.

**Comment by mjra007** [comment]
Just curious, @Pirog17000 what profiling tool are you using?

**Comment by Sirse** [comment]
@mjra007, WarmRoast

**Comment by ExDomino** [comment]
We are only two players and only one is exploring the Twilight and our server laaaaaaags!
Why exploring the Twilight is so laaaging?

**Comment by Tamaized** [comment]
@Andromander that profile report speaks nothing of lighting calculations.

**Comment by Graitt** [comment]
@Tamaized Is it the getPossibleCreatures that causes the lags? I'm not really good at reading reports ;/

**Comment by Tamaized** [comment]
Closing as this is quite old and most likely not an issue in 1.18 builds
