### ISSUE TITLE
Questing Ram Sound Volume

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#487]
Questing Ram sounds are always at full volume, distance doesn't matter.

**Comment by bs2609** [comment]
As far as I can tell, the sounds should be affected by distance, but the quest ram is loud (same volume as the ender dragon):
https://github.com/TeamTwilight/twilightforest/blob/7d5221b6d6f13432eded40351e1be5930be0b676/src/main/java/twilightforest/entity/passive/EntityTFQuestRam.java#L208-L211

AIUI this means that for some distance, the volume would be capped and wouldn't start to decay until further out.

We could perhaps turn him down a bit?

**Comment by Andromander** [comment]
I recall sounds being converted from stereo to mono fixing something related to sounds not fading properly, so I'll consider this resolved unless it's still too loud.
