### ISSUE TITLE
[Suggestion] Magic map cloning

### ISSUE THREAD

**Issue by 3TUSK** [TeamTwilight/twilightforest#489]
Forge version: 14.23.3.2673
Twilight Forest version: 3.6.398
Link to crash log: N/A

Magic map should support vanilla-style cloning. It will be very helpful when you want to build a wall like the one featured below, but also want to have a copy for exploration:
![image](https://user-images.githubusercontent.com/9113033/39462231-d20b70ac-4cc4-11e8-8681-15928dcb64dd.png)

Steps to reproduce:
1. Try doing something like [this](https://minecraft.gamepedia.com/Map#Crafting_ingredient) but with twilight forest magic map.

What I expected to happen:  
A magic map cloning recipe should be available.

What happened instead:
It is absent as of the version given above.

**Comment by Drullkus** [comment]
I thought we had compat for map cloning, wtf

**Comment by Drullkus** [comment]
[:P](https://github.com/TeamTwilight/twilightforest/blob/11db4d19d86e29f8bf966c1c620db335825af256/src/main/java/twilightforest/item/recipe/TFRecipes.java#L58-L60)

**Comment by 3TUSK** [comment]
Confirmed. I should have tested with magic map... :/
