### ISSUE TITLE
Sophisticated Wolves and Twilight OutOfMemoryError

### ISSUE THREAD

**Issue by Pirog17000** [TeamTwilight/twilightforest#490]
Forge version: 14.23.3.2655 (because latest doesn't have /fml confirm)
Twilight Forest version: 1.12.2-3.6.345
Link to crash log: 
https://pastebin.com/eh6usyzs

Steps to reproduce:
1. ? ? ? 

What happened instead:
OutOfMemoryError

**Comment by Andromander** [comment]
Can you also report this to the creator of Sophisticated Wolves, and also check if this error occurs with other portals?

**Comment by Pirog17000** [comment]
already made it https://github.com/NightKosh/Sophisticated-wolves/issues/51
