### ISSUE TITLE
Overhaul Aurora Palace

### ISSUE THREAD

**Issue by Benimatic** [TeamTwilight/twilightforest#496]
What I expected to happen:

Rooms generate properly, possible to navigate through the tower without missing stairways, blocked doors, etc.

What happened instead:

Some rooms generate badly

**Comment by bs2609** [comment]
See also #71.

**Comment by Drullkus** [comment]
Renamed issue, since I'll go track the Aurora Palace rework here as well.

**Comment by EnderiumSmith** [comment]
The rooms look quite empty. could also use a bit more decoration
