### ISSUE TITLE
[Suggestion] Configurable stalactite generation of ores from other mods in hollow hill

### ISSUE THREAD

**Issue by 3TUSK** [TeamTwilight/twilightforest#499]
#### Environment
Forge version: 14.23.3.2678
Twilight Forest version: 3.7.412
Link to crash log: N/A
Side note: the modpack used is the "Do I am Cake".

#### Synopsis 
See also #172, which is mod-specific version of this issue.
For players who set up their base in twilight forest, it may be a hard time for them to find certain types of non-vanilla ore in twilight forest, due to the combination of their generation range and low average altitude of twilight forest. Examples would be copper and aluminium (bauxite) from Immersive Engineering (both of them have min. gen. y-level of 40 by default), and apatite from Forestry (which has non-configurable min. gen. y-level of 56). 
Therefore, were there stalactites of modded ores in hollow hill, the problem described above would have be largely alleviated.

#### Reproduction
Steps to reproduce:
1. Find a hollow hill; size doesn't matter.

What I expected to happen:
Ore blocks from other mods appear in hollow hill in form of stalactite.

What happened instead:
Only stalactites of vanilla ores (coal, iron, gold, redstone, diamond, lapis, emerald) and glowstone appear in hollow hill.

#### Analysis
As of e9752dc08877447fb5ca53b85e84f70236ec89b5:
`TFGenCaveStalactite::makeRandomOreStalactite` can only return instance of `TFGenCaveStalactite` that contains one of: diamond, lapis, emerald, gold, redstone, iron, coal, glowstone. This means that we currently have a fixed pool of ore choices to choose. One of intuitive solution would be exposing them as a config option.
The underlying challenge will be the method of describing block state in config file - even though metadata is available for now, it will be phased out in upcoming Minecraft 1.13, which, if metadata is used, will create extra problems in the future.

**Comment by Rongmario** [comment]
Is this still being considered?

**Comment by 3TUSK** [comment]
AFAIK there is a WIP IMC API that would allow you do this if completed. 

> so many abbreviations

**Comment by Rongmario** [comment]
Seriously hope this is getting worked on.

**Comment by Drullkus** [comment]
Partially worked on! Kinda busy with IRL things, if you'd like to contribute some code via PR, that'd be helpful.

**Comment by Rongmario** [comment]
This is still applicable right? https://github.com/TeamTwilight/twilightforest/blob/1.12.x/CONTRIBUTING.md

**Comment by Tamaized** [comment]
Yes
