### ISSUE TITLE
1.12 Penguins have no AI

### ISSUE THREAD

**Issue by Zygus42** [TeamTwilight/twilightforest#500]
Forge version: forge-1.12.2-14.23.3.2673-installer-win
Twilight Forest version: twilightforest-1.12.2-3.6.345-universal

The Penguins on top of the Twilight Glacier biome spawn, all looking south and never move or twitch - unless you hit them, in which case they move a bit very slowly and then stop again.

**Comment by Drullkus** [comment]
Please execute `/forge tps` for me and tell me what the numbers are

**Comment by Zygus42** [comment]
Mean tick time: 59.655ms.   Mean TPS 16.73.

Overworld (after travelling there):
Mean tick time: 18.004ms.   Mean TPS 20.00.

Thing is, everything else appears fine - deer, tiny birds, ram, naga, just not the penguins.

**Comment by Drullkus** [comment]
Weeeeird...
