### ISSUE TITLE
Twilight Forest with FBP

### ISSUE THREAD

**Issue by crashmaker18** [TeamTwilight/twilightforest#501]
Forge version: 
Twilight Forest version: 2.3.7
Link to crash log: https://pastebin.com/pPhRN8De

Steps to reproduce:
1. Go into the Twilight Forest with Fancy Block Particles mod enabled.
2. Wait for a second or 2.
3. ???
4. Profit

What I expected to happen:
For it to work normally.

What happened instead:
Crash to multiplayer screen.

**Comment by TominoCZ** [comment]
Original post: https://github.com/TominoCZ/FancyBlockParticles/issues/82

**Comment by Hubry** [comment]
I am pretty sure 1.7.10 is no longer supported here - 441b472a5ced4f5175ae6bdc94ceab7ef7f73d68 should've fixed it, but that's 1.12 land.

**Comment by Killer-Demon** [comment]
1.7.10 is unsupported as @Hubry said.
