### ISSUE TITLE
Castle Doors drop the wrong item when mined

### ISSUE THREAD

**Issue by justinrusso** [TeamTwilight/twilightforest#502]
Forge version: 14.23.3.2681
Twilight Forest version: 3.6.345

Steps to reproduce:
1. Mine a door at the castle
2. Receive yellow instead of pink colored door.

What I expected to happen:
Drops the correct item matching the meta of the door block

What happened instead:
All of the doors drop meta 0 block

**Comment by Killer-Demon** [comment]
This was fixed with a6a669db43f713ac339065849e094087735c3954
This fix will be in the next release.
