### ISSUE TITLE
1.12 crash on startup with no other mods

### ISSUE THREAD

**Issue by Zygus42** [TeamTwilight/twilightforest#504]
Forge version: forge-1.12.2-14.23.3.2685-installer-win
Twilight Forest version: twilightforest-1.12.2-3.7.424-universal

No other mods at all.

Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
Happy to attach the crash report as a txt, but not going to go and set up an account just to cater to your odd taste in reporting.

Steps to reproduce:
1. Start game

What I expected to happen:
Game to work.

What happened instead:
Crashed with a security exception, which is not something I've ever seen before in all my years of modding minecraft, so well done :)

**Comment by Andromander** [comment]
Please supply a crash report. This doesn't say anything about the crash.

EDIT: Read the message in the "Link to crash log". You don't need to create an account on Pastebin. You can also use your GitHub account to create a Gist.

**Comment by Zygus42** [comment]
[crash-2018-05-13_14.57.39-client.txt](https://github.com/TeamTwilight/twilightforest/files/1998356/crash-2018-05-13_14.57.39-client.txt)

**Comment by bs2609** [comment]
> Happy to attach the crash report as a txt, but not going to go and set up an account just to cater to your odd taste in reporting.

FYI, you can use your GitHub account on https://gist.github.com.

**Comment by Andromander** [comment]
The crash log is raising numerous questions. For one, Twilight Forest is not listed at all, which brings up the second point that there is no list of mods. What may need to be done is to clean install Forge and try again. If it still fails, binary check your mods (remove half the mods and find which half crashes until you find the mod that causes the crash).

This might also be stretching out possible issues, but there might be an issue with Java itself, or any of the coremods?

**Comment by Zygus42** [comment]
Playing minecraft fine on my modpack.

No other mods installed in my test folder.  I AM running latest forge which is a couple of versions higher than the one you specified.

So I gather when you run this version of twilight forest you're not having any issues ?

**Comment by Zygus42** [comment]
And I deleted the old config file as well, just in case that was the issue.

**Comment by Tamaized** [comment]
Please use gist as I can't view that log easily on mobile.

**Comment by Zygus42** [comment]
<script src="https://gist.github.com/Zygus42/ab9351385b47e6e640866aeb32ca2262.js"></script>

**Comment by Zygus42** [comment]
https://gist.github.com/Zygus42/ab9351385b47e6e640866aeb32ca2262

**Comment by Tamaized** [comment]
Update Forge, this was a bug in forge that was resolved shortly after.
