### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by theishiopian** [TeamTwilight/twilightforest#505]
Forge version: 14.23.3.2678
Twilight Forest version: 3.7.424
Link to crash log: [https://pastebin.com/zQLHNRrK](https://pastebin.com/zQLHNRrK)

The log said to report this, so here it is. It should be noted that I'm using the official TF server modpack, and this world was generated as a superflat world.

**Comment by Tamaized** [comment]
#429
