### ISSUE TITLE
Add block.canEntityDestroy to mobs

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#506]
From Corail:

- [x] Add `block.canEntityDestroy` to mobs that break blocks, especially Naga and Hydra
- [ ] Add API for ignores in block breaking from AntiBuilders and other related devices

**Comment by bs2609** [comment]
Linking #365 here.

**Comment by bs2609** [comment]
First point is addressed by 8251ba16272deef7041e1470b30782d5801b5530.

**Comment by GizmoTheMoonPig** [comment]
Since theres an antibuilder blacklist that exists as a tag (and we can make tags for any other devices if needed), and the first part was already addressed, im gonna consider this one solved.
