### ISSUE TITLE
Castle Stairs Rotation

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#509]
When placing both castle stairs variants upside down their rotation will mess up when trying to connect them.
Nagastone stairs are not affected.

![12423546](https://user-images.githubusercontent.com/31552602/40242559-3ce75704-5abe-11e8-9a3f-9ed710119607.png)

**Comment by bs2609** [comment]
Used the rotation values from the nagastone stairs blockstate file - seems fine now.
