### ISSUE TITLE
Crashing on Registration

### ISSUE THREAD

**Issue by DomAmato** [TeamTwilight/twilightforest#511]
Forge version: 1.12.2...
Twilight Forest version: (this is the build number)
Link to crash log: https://pastebin.com/j6gD1gzN

Steps to reproduce:
1. Start Server with Roboticraft

What I expected to happen:
Server to start

What happened instead:
Server crashes

There is an incompatibility with my mod here that someone posted about on my mod issues but the problem is that its possible to call client side code on a server and it crashes. 

https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/block/BlockTFSapling.java#L133

what my mod does it it tries to get all the names of blocks and items and outputs them to python files so that they can be used with a coding component in the game. I could make some changes to try and prevent crashes from my end but thats going to be an absurd amount of edge cases so just bringing this up for you guys :)

**Comment by Tamaized** [comment]
~~It's not reasonable to call getLocalizedName on the server side~~ Take that back as it's used by the common I18n for commands.

**Comment by DomAmato** [comment]
Thats fair and I think I actually fixed it before the issue was reported though that fix hasnt been released yet.

**Comment by Tamaized** [comment]
Went ahead and solved this on our end as well: 920d74a5ef8c48d0f5ff2fac9eb9c7e7994aee73
