### ISSUE TITLE
1.12.2-3.7.424 requires a dev version of Forge

### ISSUE THREAD

**Issue by LemADEC** [TeamTwilight/twilightforest#514]
Forge version: n/a
Twilight Forest version: 1.12.2-3.7.424
Link to crash log: n/a

Steps to reproduce:
1. boot with latest recommended forge version, 2655

What I expected to happen:
Game should boot with latest recommended forge

What happened instead:
Game fails due to the mod requiring a dev version.
Please ask Lex to push a new recommended version if you need that fix.

**Comment by Tamaized** [comment]
u wat

**Comment by liach** [comment]
yeah bro download latest. lexmanos tag recommended builds on a hardly predictable basis.

**Comment by LemADEC** [comment]
Lex said explicitly that if a mod needs a dev version of forge, their author should go ask for a new recommended build

**Comment by LemADEC** [comment]
As Lex said, it's up to the mod author to ask for RB:
https://github.com/MinecraftForge/MinecraftForge/issues/4940

So go ask him!
