### ISSUE TITLE
[1.12.2] Twilight Forest crashes Mystcraft Age

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#517]
Forge version: 14.23.3.2702
Twilight Forest version: 3.7.424
Link to crash log:  https://pastebin.com/reLjC3A0

Steps to reproduce:
1.  Make a Mystcraft age with a Twilight Forest biome in it
2. Enter Age with book

What I expected to happen:
Game to load the age and play normally.
What happened instead:
Game crashes, might be a problem with structure gen?

**Comment by bs2609** [comment]
Could probably do with a null-check here:
https://github.com/TeamTwilight/twilightforest/blob/ffbda148648c3cda6db76e76cb83f00fe194b3be/src/main/java/twilightforest/world/TFGenWitchHut.java#L177-L180
