### ISSUE TITLE
Jungle trees in Dark Tower spawn with opposite blocks

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#52]
Forge Version: 13.20.0.2315
Twilight Forest Version: 2.4.0.17

Jungle trees in the Dark Tower have leaves for wood and wood for leaves
![2017-06-19_15 20 43](https://user-images.githubusercontent.com/29526717/27271305-50c2e59e-5507-11e7-8750-15dbead5a1a7.png)
![2017-06-19_15 37 14](https://user-images.githubusercontent.com/29526717/27271311-5632e236-5507-11e7-9325-88b60e4fa104.png)

**Comment by AtomicBlom** [comment]
#Closed #ByDesign
