### ISSUE TITLE
Metal Fluids Texture

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#522]
When placing Molten Fiery Metal and Molten Knightmetal via the buckets with the fluids provided by Tcon the texture breaks.
![image](https://user-images.githubusercontent.com/31552602/40461384-720e6e62-5f0b-11e8-9320-138b8afc491c.png)

**Comment by bs2609** [comment]
Was fixed via 0935c033914c33af0489be588ed03f9c915bd46d and d418a5e56904ee4b34c5e6fcd050a953aff079b0.
