### ISSUE TITLE
[feature request] 1.12 config option to disallow start with portal

### ISSUE THREAD

**Issue by Zygus42** [TeamTwilight/twilightforest#524]
With the new option you've added to allow starting in the Twilight Forest, it would be great to have a config option to go with it, to have it not make a portal where you start.  The idea would be to have the player need to make their own portal if they want to leave the Twilight Forest, not provide one for them.

**Comment by Drullkus** [comment]
I've already attempted what you're asking for but it creates a problem in the teleporter code and there's so much unwrapping I have to do to fix it so just set `B:shouldReturnPortalBeUsable` to false and you should be fine.

```
# If false, the return portal will require the activation item.
B:shouldReturnPortalBeUsable=false
```
