### ISSUE TITLE
[translate] en_us.json content issues

### ISSUE THREAD

**Issue by sfs131010** [TeamTwilight/twilightforest#525]
twilightforest.book.labyrinth.1 to twilightforest.book.labyrinth.5 and
twilightforest.book.yeticave.1 to twilightforest.book.yeticave.3
have the same content:
The curse seems to be of a type too powerful for one being alone to produce. Several wizards working in combination would be necessary.
If one of the wizards stopped contributing, the blizzard would calm. Strangely, my divinations do not show signs of any nearby living wizards. I did see something interesting in one of the nearby pointy-roofed towers though...

I'm one of the zh_tw translators, so that I want to confirm if it's correct or not to translate it quickly for Chinese players.(Although I do think there is wrong)

Thank you.

**Comment by Drullkus** [comment]
Yeah this is fine. I re-ordered the progression so I had to change those language keys up.
