### ISSUE TITLE
[Solved] Can't log into server?

### ISSUE THREAD

**Issue by 34486** [TeamTwilight/twilightforest#532]
Forge version: 1.12.2 - 2703
Twilight Forest version: 3.7.424
No crash log, Nothing crashed, no error accept in server console.

What I expected to happen: Log into the server.

What happened instead: Didn't log into the server.
I go to log into my server, it says I leave, never said I joined, normal most of the times when it kicks me lol, but it gives me [twilightforest] : Mod was keeping bauble items for player %s but they logged out! Items are being dropped.

The client says, Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge) I have the server AND client on the SAME forge version! I saw a post saying to remove project red, I did that, nothing changed. 

Anybody have a way to fix this? I will try to find a way to isolate the mods and reproduce this..

EDIT: If its not a twilightforest issue, should I go to baubles and talk to them? By the way, I have baubles and Botania, chisel and connectedtextures and mrjtp all updated to latest version.

**Comment by Kuktar** [comment]
Have you tried upgrading forge? That bauble message in the server console is normal even without a crash

**Comment by 34486** [comment]
I don't see your message here, well I saw it for a second, I am on forge stable, I can go up to the next one, but the one after that says it is bugged..

**Comment by 3TUSK** [comment]
Update Forge to 14.23.4.2705 or above.

**Comment by 34486** [comment]
Worked! Thanks!
