### ISSUE TITLE
magic map no longer updates after death

### ISSUE THREAD

**Issue by mabelrxu** [TeamTwilight/twilightforest#533]
Forge version: 14.23.1.2590
Twilight Forest version: 3.5.263
Link to crash log: n/a

Steps to reproduce:
1. Have magic map in offhand
2. Die from falling from high place
3. Map no longer updates, copied maps from that map also no longer updates

What I expected to happen:
When I pick up the map again from my gravestone (corail's tombstone mod), my map should still be dynamic and updating, not stuck in the state it was when I died.

What happened instead:
Map got stuck in the state when I died.

If this has been fixed, then apologies for the duplicate report, currently playing through Modern Skyblock 2.

**Comment by mabelrxu** [comment]
after saving and quitting, and reloading from a recent save, the map is now complete (was almost complete before, and did run over the not filled in part while the map was in the frozen state), but there's no animated arrow to show current location and orientation

**Comment by bs2609** [comment]
Probably the same issue as #427.

This should be fixed in the latest release (3.7.424), but if it isn't please let us know.

**Comment by mabelrxu** [comment]
ah, I see. based on comments from that issue, it looks like saving and reloading will work, so I'll just do that for now, not looking to make changes to the modpack. thanks for the info!
