### ISSUE TITLE
Player marker not appearing on Magic Map

### ISSUE THREAD

**Issue by justinrusso** [TeamTwilight/twilightforest#534]
Forge version: 14.23.4.2705
Twilight Forest version: 3.7.424

Steps to reproduce:
1. Create a new world
2. Go to Twilight
3. Spawn in a blank magic map
4. Open the blank magic map
5. See no player marker

What I expected to happen:
The player marker should appear showing the direction the player is facing and where they are on the map

What happened instead:
The player marker is missing

**Comment by Andromander** [comment]
Unable to reproduce on my end. Are there any mods installed that affect map rendering?

**Comment by justinrusso** [comment]
Fresh instance, fresh world, just went to the Twilight Dimension and cheated in a map:

![image](https://user-images.githubusercontent.com/25138621/40868046-49cb9286-65d7-11e8-9b6a-60b0e16f724b.png)

### Mods Installed:
**Forge:** 14.23.4.207
**JEI:** 4.9.2.196
**Twilight Forest:** 3.7.424

**Comment by bs2609** [comment]
To be clear, how did you cheat in the map - did you spawn in an empty map, or a filled one?

You'd need to open the map to get added to it, I believe, but I don't think vanilla maps are different in that regard.

**Comment by justinrusso** [comment]
Agh.. that was it. Didn't see blank one in JEI until you pointed that out. Thanks
