### ISSUE TITLE
Feat: Allow for multiple items to be used as portalCreationItem

### ISSUE THREAD

**Issue by justinrusso** [TeamTwilight/twilightforest#535]
This is a feature request to add support for multiple items to be added for the portalCreationItem.

The use case would be for situations where once the player is in the twilight, they have an alternative item they can use if needed to get back.

Current:
```
S:portalCreationItem=astralsorcery:itemcraftingcomponent
```

Suggested:
```
S:portalCreationItem <
    astralsorcery:itemcraftingcomponent
    minecraft:log
 >
```

Reference Issue: https://github.com/DarkPacks/SevTech-Ages/issues/2626

**Comment by Tamaized** [comment]
Also note, we'd have to change how we handle the meta value as well.

**Comment by AtomicBlom** [comment]
FYI, I literally just wrote something that does what you need for Weirding Gadget
https://github.com/AtomicBlom/WeirdingGadget/blob/devel-1.12/src/main/java/com/github/atomicblom/weirdinggadget/WeirdingGadgetFuel.java

Just need to strip out the time components of the regex and it'll work a treat..

**Comment by artdude543** [comment]
Would it be possible to allow to set the side the item could only work on? As an optional argument to add to the end of the config input.

Use case for example in SevTech: Ages would be to enforce the route for the item in the overworld and as a secondary item for people who get stuck in the TF _(who did not bring spare items)_ that item we set for secondary would only work on the TF. Thus allowing the pack to retain its enforcement tree. And still giving a secondary access back out which would only work in the TF if the player gets it's blown up or whichever.

**Comment by Drullkus** [comment]
Hmmm alright.

**Comment by artdude543** [comment]
Was the option of considering adding the optional dimension Id talked about @Tamaized or @Drullkus?

**Comment by Drullkus** [comment]
Check the config. It's been there for years.

**Comment by bs2609** [comment]
Believe they were referring to this comment: https://github.com/TeamTwilight/twilightforest/issues/535#issuecomment-394077095

**Comment by artdude543** [comment]
Yeah, I'm quite confused on how he thought I meant about the actual dimension Id for the _dimension_ itself 😕 But yes I was refering to me comment about allowing an optional `:` entry for setting an item to only work for a portal on either side.
