### ISSUE TITLE
Message "[twilightforest]: Mod was keeping bauble items in reserve for player %s but they logged out! Items are being dropped." on player disconnect

### ISSUE THREAD

**Issue by fraenkelc** [TeamTwilight/twilightforest#541]
Forge version: forge-14.23.4.2703
Twilight Forest version: twilightforest-1.12.2-3.7.424-universal.jar

Steps to reproduce:
1. player disconnects from server

What I expected to happen:
I only expect log messages relating to dropped baubles if there are actually dropped baubles

What happened instead:
Log messages appear on every disconnect

The logging guard in https://github.com/TeamTwilight/twilightforest/blob/3d63886bc211845d53c245c56a5fdb5b05ac0ced/src/main/java/twilightforest/TFEventListener.java#L430-L438 looks wrong, especially when compared to the one a few lines above: https://github.com/TeamTwilight/twilightforest/blob/3d63886bc211845d53c245c56a5fdb5b05ac0ced/src/main/java/twilightforest/TFEventListener.java#L420-L427

**Comment by Blumed** [comment]
I am seeing this as well. Is this not an issue? Warnings should be warnings when they are warnings right? False warnings are always good to tamper.

**Comment by Andromander** [comment]
False warnings have been resolved in the latest version, 3.8.654. If you are seeing that message as of this update, you might be experiencing a real problem
