### ISSUE TITLE
Baubles missing from Grave

### ISSUE THREAD

**Issue by Xules01** [TeamTwilight/twilightforest#542]
Forge version: forge-1.12.2-14.23.4.2707-universal.jar
Twilight Forest version: twilightforest-1.12.2-3.7.424-universal.jar
Link to crash log:  N/A
Steps to reproduce:
1. Place and item in your baubles slot.
2. player death (ie, fall from high place, etc)
3. go back to grave stone and collect items.

What I expected to happen:  I should receive all my items, including those that were in the baubles slot.

What happened instead:  Baubles were missing.  

I find it strange that it was Twilight Forest that was causing it, as I had updated several mods and was testing them out.  I finally started over and was adding them one by one.  It broke when I added the latest version of Twilight Forest.   For now I've gone back to the previous version.

Tested with both of these mods:  [gravestone-1.10.1.jar](https://minecraft.curseforge.com/projects/gravestone-mod/files)
                                                     [OpenBlocks-1.12.2-1.7.6.jar](https://minecraft.curseforge.com/projects/openblocks/files)

Let me know if there was something I may have done wrong.  

Thank you for your wonderful mod, have had many hours of fun exploring your world.

**Comment by bs2609** [comment]
Just to confirm, the baubles weren't still on your player, or on the floor around where you respawned?

**Comment by Xules01** [comment]
Correct, they were not in the area nor on my character.   The gravestone mod give you a list of items that it stored.  The baubles items were missing while testing with the latest version of Twilight Forest.

**Comment by bs2609** [comment]
Tested this with the OpenBlocks grave. Currently, baubles are always restored to the player on respawn, even without a Charm of Keeping (due to 8a508288f24ce6716bc9cf30624e38270fe0b872). As a result, they wouldn't be saved by graves.

This should be fixed now - you can try a dev build here (http://builds.steamnsteel.info/browse/TF-ONETWELVE/latest/artifact) and post if there's still a problem.

**Comment by Xules01** [comment]
Wow, that was a very fast fix.  That worked perfectly.  Thank you!
