### ISSUE TITLE
Can't login back into server when have logged out from within Twilight dim

### ISSUE THREAD

**Issue by chezpaul** [TeamTwilight/twilightforest#545]
Forge version: 2707
Twilight Forest version: 1.12.2 3.7.424
Link to crash log: [https://pastebin.com/57xeAzCm](https://pastebin.com/57xeAzCm)

Steps to reproduce:
1. Logout when in Twilight Forest Dim
2. Try to log back in. Screen stays on Loggin in...

What I expected to happen: I should be able to login

What happened instead: It won't let me, even though the server thinks I am about to.

**Comment by Tamaized** [comment]
Can you also provide the client log when this happens.

**Comment by chezpaul** [comment]
Sure
[https://pastebin.com/bGt3stZQ](https://pastebin.com/bGt3stZQ)

**Comment by Tamaized** [comment]
Looks like it fails here:
NullPointerException
`mcjty.lostcities.dimensions.world.LostWorldType.getBiomeProvider(LostWorldType.java:65)`

**Comment by chezpaul** [comment]
Thanks

**Comment by bs2609** [comment]
Seems to be fixed: https://github.com/McJtyMods/LostCities/issues/136#issuecomment-395279547
