### ISSUE TITLE
Worldgen lag persistent through many versions of Twilight Forest

### ISSUE THREAD

**Issue by Carnaxus** [TeamTwilight/twilightforest#547]
I've been playing packs and servers with Twilight Forest in them for a long time now (at least since 1.4.7 if not earlier) and many have had worldgen lag issues when people are exploring the Forest.  I find it somewhat odd that this issue has persisted for so many years and through so many updates.  What is it about this mod's worldgen code that causes so much worldgen lag?

One server even spun up a quick test instance with just Twilight Forest and watched as the TPS ground nearly to a halt with only two people exploring in different directions, although that was a few versions ago now.

I didn't stick to the "official form" because this is neither a crash nor is it specific to any one version of the mod.

**Comment by Tamaized** [comment]
I'd need to see a profile report.

**Comment by Carnaxus** [comment]
I'll see if I can get one from the most recent server, the owner's a friend of mine.

**Comment by alxcool** [comment]
Concurrent Modification exception ± Cascading world Gen ± twilight magic map = Crash

Single player 1.12.2 Forge 2705
twilightforest-1.12.2-3.7.424-universal
https://paste.dimdev.org/ahisugewod.mccrash

Steps to reproduce:
[latest.log](https://github.com/TeamTwilight/twilightforest/files/2300917/latest.log)


Edit : Updated game's version, then can't reproduce this crash, sorry for that, I should update when I can!
