### ISSUE TITLE
minotaurs drop magic map focus instead of maze map focus

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamTwilight/twilightforest#549]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:

**Comment by bs2609** [comment]
Fixed by 09283dd4112f1ea1868d96576360dd67639ac6e3, will be in next release.
