### ISSUE TITLE
Mod's axes deal too little damage 

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamTwilight/twilightforest#550]
Vanilla exes except wood and gold deal 9 damage. Twilight axes deal only 8. Ive noticed this while using the minoshroom axe. Since the minoshroom axe is a unique dungeon item it should deal a bit more. maybe 11. at least 10.

**Comment by bs2609** [comment]
Fixed by d471d6604d5c6c61a626534fa8e17866aa121152, will be in next release.
