### ISSUE TITLE
TF crash at initialization in modded

### ISSUE THREAD

**Issue by undidon** [TeamTwilight/twilightforest#551]
Forge version: 14.23.4.2705
Twilight Forest version: 1.12.2 - 3.7.424
https://gist.github.com/undidon/56be8c041d1624f27cc79f71c3f5153e

Steps to reproduce:
1. None, Crash happens at initialization as the pack is. 
I've tried these versions as well (3.6.345)(3.6.324) each has resulted in a crash 

What I expected to happen: My instance to launch.

What happened instead: Instance crashes at at loading TF.

Of course Tf loads fine when it's the only mod installed.
So there may be a mod interaction causing this sadly reading crash logs is not my thing.
It may have something to do with this starting at line 58 in the above link - java.lang.ClassNotFoundException: twilightforest.item.TFRegisterItemRenderingEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) -
So it may be a crash due to my having to many mods or not enough ram I'm not sure.

**Comment by Tamaized** [comment]
https://github.com/shadowfacts/Forgelin/issues/38
