### ISSUE TITLE
Encased Fire Jet & Smoker Malfunction

### ISSUE THREAD

**Issue by Wettoson** [TeamTwilight/twilightforest#552]
Forge version: 
Twilight Forest version: (3.7.424)

So here I am, just messing around in creative mode, and then I see the Encased Fire Jet. The texture on the block is normal. I decide to try it, but when I place it down, it's pitch black, with a few red rings. Obviously this did not seem to be something unintended, because the texture for it must have been designed. So I ignore that, and try it out. When I turn it on, the rings turn green, and the ring on the top gets small, and has a 2x2 patch of different colored green on it. Sure, the lava sounds occur, but no embers appear. Then, it makes the sound when it shoots out the fire, no particles come out, but everything, including me, gets set on fire. This is the exact same case with the Encased Smoker. Same black ring texture, no particles come out. Also, when I placed down the normal Smoker, it's particles came out. But after let's say a good 5-10 minutes, it stopped.

![image](https://user-images.githubusercontent.com/40153426/41213327-8eb11398-6cf9-11e8-8c68-178fdbeb1549.png) 
Inactive 

![image](https://user-images.githubusercontent.com/40153426/41213382-e664c436-6cf9-11e8-9fa2-b19dea228a9a.png)
Active

I don't know if this is the game, or my computer, because at some point I re logged, the particles showed up for a few minutes. Anyway, thanks for wasting your time reading this. This is my first report, so I don't know how to write this or who this goes to.

So, I leave you with Shizzles and Gizzles,

-Wettoson

**Comment by Andromander** [comment]
Do you have either ConnectedTexturesMod or Optififine installed? If CTM isn't installed, install it, but if Optifine is installed, remove it, as it may be breaking rendering

**Comment by Wettoson** [comment]
Gotcha. Thanks.
