### ISSUE TITLE
Not compatible with Immersive Engineering

### ISSUE THREAD

**Issue by MrAnkylasuarus** [TeamTwilight/twilightforest#553]
Forge version: 14.23.4.2707
Twilight Forest version: 3.8.494
Link to crash log: https://gist.github.com/MrAnkylasuarus/706bd758573deacd0b33cb629e92e519

Steps to reproduce:
1. Made sure to have all dependencies.
2. I launched the game.

What I expected to happen: I expected it to load to the main menu.

What happened instead: It stated that i required a newer version of immersive engineering than is currently built. Specifically version 0.12-83-397, I have the latest on available for download on curseforge, 0.12-82.

**Comment by Drullkus** [comment]
I'm aware of this, It's only unavailable on Jared's Maven. Furthermore, the build is marked as Alpha.

EDIT: Pulled the version from Curseforge
