### ISSUE TITLE
Goblin knight stronghold still requires killing the hydra

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamTwilight/twilightforest#555]
Forge version: 
Twilight Forest version: 3.7.424
Link to crash log: 

Steps to reproduce:
1. kill naga
2. kill lich
3. go to goblin knight stroghold
4. place head on pedestal

What I expected to happen:
the door to the dungeon would open

What happened instead:
it showed an unlocalized message in chat

**Comment by bs2609** [comment]
Duplicate of #507, fixed by #508.
