### ISSUE TITLE
Fiery pick does not respect stack size

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamTwilight/twilightforest#558]
if you mine an item that smelts into multiple items(like the ironwood materials but a block) it only drops one. for example with the refining enchant from thaumcraft the native clusters only drop 1. and yes, i can confirm that the thaumcraft enchant processes first.

**Comment by bs2609** [comment]
Probably due to this?
https://github.com/TeamTwilight/twilightforest/blob/fc772c432ebf750f6a92896e4e6d35239ca8648f/src/main/java/twilightforest/item/ItemTFFieryPick.java#L48
