### ISSUE TITLE
Random crashes (without crash report) when entering and just being in the dimension

### ISSUE THREAD

**Issue by Fenekhu** [TeamTwilight/twilightforest#559]
Forge version: 14.23.4.2708
Twilight Forest version: 3.7.424
Link to crash log: Unfortunately, minecraft quits instantly and doesn't even generate a crash report. Here is everything starting at me entering my minecraft world: [gist](https://gist.github.com/TheGoldenProof/e23147ba7c7890279292590e535ae928).

Steps to reproduce:
1. go into the twilight forest
2. if it didn't crash from doing that, exploring around.
3. generating chunks seems to make it crash
4. it doesn't always happen and sometimes i can come and go from the twilight forest just fine.

What I expected to happen:
everything is normal and i just explore around

What happened instead:
it instacrashes without any "shutting down internal server" or crash report, as if its been force closed by task manager.

**Comment by Fenekhu** [comment]
I may have figured it out, it could have been due to memory usage spikes that caused my computer to run out of memory and force quit minecraft

**Comment by Andromander** [comment]
This kind of crash does generate a crash log, but not in the crash log folder. You may be experiencing a problem with Java itself.

**Comment by Fenekhu** [comment]
I also found that it doesn't only happen in the twilight forest either, it happened not long after i went back through the portal. Where is that crash log?

**Comment by Andromander** [comment]
Those are typically saved into the root of the `.minecraft` folder, starting with `hss_`.

**Comment by Fenekhu** [comment]
Yeah I found it. It totally goes way over my head. I guess I'll just leave it and try to bring down my memory usage.
