### ISSUE TITLE
TF Crashes on a Server

### ISSUE THREAD

**Issue by ruairidh74** [TeamTwilight/twilightforest#56]
Twilight Forest: 2.4.0.23
Forge: 13.20.0.2228

After entering the twilight portal and moving around I get this crash:
[crash-2017-06-19_21.07.53-server.txt](https://github.com/TeamTwilight/twilightforest/files/1086220/crash-2017-06-19_21.07.53-server.txt)

**Comment by ruairidh74** [comment]
Same versions.
I deleted and regenerated the world and get another error, after entering the portal.
(A report wasn't made so I took it from the console, and removed my IP address for obvious reasons.)
Crash: 
[crash-2017-06-19_21.43.38-server.txt](https://github.com/TeamTwilight/twilightforest/files/1086322/crash-2017-06-19_21.43.38-server.txt)

**Comment by ruairidh74** [comment]
Same Versions.
Ok after another try, I was able to get the world generating and working for a while, but crashed again.
Crash:
[crash-2017-06-19_22.53.46-server.txt](https://github.com/TeamTwilight/twilightforest/files/1086456/crash-2017-06-19_22.53.46-server.txt)

**Comment by ruairidh74** [comment]
Same Versions.
Found another, different crash, happened when generating the Ur-ghast boss area:
[crash-2017-06-20_00.52.13-server.txt](https://github.com/TeamTwilight/twilightforest/files/1086612/crash-2017-06-20_00.52.13-server.txt)

**Comment by williewillus** [comment]
you don't have to do it for this one but next time if the crash is different make another ticket pls :D

**Comment by Benimatic** [comment]
I think these should all be fixed.
