### ISSUE TITLE
The repeaters in the ur ghast tower are set to 0 delay causing the sticky pistons to not pull the block back

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamTwilight/twilightforest#562]
its the one in the room with the pressure plate that powers a sticky piston that pushes a block causing it to unpower itself. i dont know if redstone changed between 1.7 and 1.12 or the metadata for the structure was lost during porting. anything above 0 delay allows it to work

**Comment by bs2609** [comment]
Updated to match original:
https://github.com/TeamTwilight/twilightforest/blob/15d26a3522c67f271029ca390324f0248aa63eb0/src/main/java/twilightforest/structures/darktower/ComponentTFDarkTowerWing.java#L713
