### ISSUE TITLE
Make fiery sword fire aspect a property of the sword instead of an enchant

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamTwilight/twilightforest#563]
The fiery sword comes enchanted with fire aspect. that causes 2 problems: you cant enchant it at a table and if you disenchant it, it looses the fire ability. The fiery pick sets tings on fire by itself so the sword should too. maybe have it additive so fire aspect increases the duration instead on doing nothing. also make sure mobs drop cooked meat if one shoted like fire aspect does.

**Comment by GizmoTheMoonPig** [comment]
Its done this way now in 1.16 versions. I didnt even know this issue existed, but im gonna close it since it works
