### ISSUE TITLE
1.7.10 Crash

### ISSUE THREAD

**Issue by stephen92** [TeamTwilight/twilightforest#564]
Forge version: 1.7.10-1614.58
Twilight Forest version: (twilightforest-1.7.10-2.3.7.jar)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
https://pastebin.com/PZ6CdrUy

Steps to reproduce:
1. Random server crash

What I expected to happen:

What happened instead:

**Comment by Andromander** [comment]
Unfortunately, 1.7.10 is no longer a supported version. You may need to update to 1.12.2.

**Comment by williewillus** [comment]
^

**Comment by Bogdan-G** [comment]
Help info (for those who have this or a similar problem):
crutch for BiomeDecorator issues: 
1) in server https://github.com/Bogdan-G/MinecraftForge/commit/62c0c21e8499c158df96e0bf195725ece09b7181
2) look commits https://github.com/Bogdan-G/twilightforest/commit/3f71b68eb64989c97437908af19c2c79e8fb3e30#diff-32e5e155d893f1f8e9111c45d70dc89aR151 or add try-catch in problem zone.

P.S. you should do it yourself as above wrote that the mod for 1.7.10 is not supported.
