### ISSUE TITLE
Magic map performance

### ISSUE THREAD

**Issue by adventurerok** [TeamTwilight/twilightforest#568]
Forge version: 14.23.4.2712
Twilight Forest version: 3.7.424

So I was profiling my server (I ran the sampler for 20 seconds) during a laggy period while one of my players was in the Twilight Forest exploring with the magic map in hand and I found the following result:

![screenshot 401](https://user-images.githubusercontent.com/1076294/42171458-3f23f88a-7e11-11e8-9184-98712faaf0fd.png)

Perhaps this could be fixed by running the biome generator for the magic map on a separate thread or by caching the results if they aren't already?

**Comment by bs2609** [comment]
This has been partially addressed by 1d6c77c4c42f8af50ad792dc4b9f6ae07568fb2d (build 518 [here](http://builds.steamnsteel.info/browse/TF-ONETWELVE)).

If this is still a problem, I'll look again at caching biome ID lookups and anything else that can be done.
