### ISSUE TITLE
Sugar Cane next to Twilight Portal vanishes

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#57]
Technically working as expected but still weird behavior.

Sugar cane can be used to make a Twilight Portal. But they will drop the next block update after the portal was established, as the nearby block is no longer water but a portal block.

Suggestion: Blacklist sugar cane as a plant for portal creation or make the portal block behave like water to sugar canes so that they continue to grow.

**Comment by GizmoTheMoonPig** [comment]
works now in 1.16. Enjoy!
