### ISSUE TITLE
OTG + BiomeBundle + TF (Still crash)

### ISSUE THREAD

**Issue by Snez0K** [TeamTwilight/twilightforest#570]
Forge version: forge-1.12.2-14.23.4.2705-universal.jar
Twilight Forest version: twilightforest-1.12.2-3.7.424-universal.jar
Link to crash log: https://pastebin.com/Kq5Fd3Ch

Steps to reproduce:
1. install OTG and Biome Bundle and TF (all latest versions) and try to enter TF dimension

What I expected to happen:
That i can enter like normal in TF dimension

What happened instead:
All info in crashlog, pls help.

**Comment by Tamaized** [comment]
This is on otg's end. Report it there.
