### ISSUE TITLE
bug with the final boss here text

### ISSUE THREAD

**Issue by JBSTheGamer** [TeamTwilight/twilightforest#571]
Forge version: 1.12.2-forge1.12.2-14.23.4.2705 
Twilight Forest version: (Twilight Forest - MC 1.12.2 - 3.7.424)
Link to crash log: (this is not a crash bug)
This is what happened i accidently sift right clicked on the text that was saying about the final boss here in the highlands castle. Then when i did that it took all my armor off of me and put it on this thing what ever it is. I then thought it was maybe a armor stand. Then when i tried to take my armor off off of that thing. I could not take it off and then i tried to kill the entity. Then it made it worst and now all of my armor is gone including the text. I was not happy so i had to spend a whole day cheating my armor back in and maxing it out again. The armor was from draconic evolution. I had to because it was not supposed to happen. I made another world to show this and for some reason on the other world i was not able to get the armor off but in this world i was able to. Could you make it to where this entity does not accept armor plz?
![2018-07-07_11 27 06](https://user-images.githubusercontent.com/32559193/42412793-01fcc8a0-81c8-11e8-8e9c-1401ebbbcfeb.png)

**Comment by Hubry** [comment]
The armor stands placed by TF there should be set as markers, which means they should be impossible to interact in any way. Shift-clicking armor onto armor stands is not vanilla behavior either. Can you share the full modlist?

**Comment by bs2609** [comment]
> The armor stands placed by TF there should be set as markers, which means they should be impossible to interact in any way.

You'd think so, but actually:
https://github.com/TeamTwilight/twilightforest/blob/cdf78320ccdbdf16f99298b2f038dcd741f5bdc7/src/main/java/twilightforest/structures/StructureTFComponent.java#L77-L78

(blame Drullkus)

**Comment by JBSTheGamer** [comment]
yea here is the mod list

https://www.dropbox.com/sh/fblfy267ivthxgu/AABjLPCKWIH6kR6-bz_8vr6Fa?dl=0

**Comment by JBSTheGamer** [comment]
well is that a bug cause you just said you not supposed to interact with them but i was able to do just that when it supposed to not do that.
