### ISSUE TITLE
Cascading World Gen causing massive lag

### ISSUE THREAD

**Issue by jsgunman** [TeamTwilight/twilightforest#575]
Forge version: 
Twilight Forest version: 1.12.2-3.7.424

Steps to reproduce:
1. Generate new chunks inside the Twilight Forest.

Massive server lag happens whenever new chunks are generated inside the Twilight Forest. This is most likely due to Cascading World Gen, where structures are loaded outside the loaded chunks. Can this be fixed, or do I have to temporarily not use Twilight Forest?

**Comment by bs2609** [comment]
If this is due to cascading worldgen, then there will be warnings about it in the log.

Upload the `latest.log` file from the server experiencing lag to [Gist](https://gist.github.com/), and we can look at it.

**Comment by jsgunman** [comment]
https://gist.github.com/jsgunman/918ca2dffaafd9a6e34e74d6e3387327#file-gistfile1-txt

I hope this is what you meant!

**Comment by jsgunman** [comment]
Anybody home? People love this mod but unfortunately it causes such severe tps loss that it is essentially unusable right now.

**Comment by bs2609** [comment]
Sorry for the delay. Can you go to the coordinates mentioned in the log, and say what biome/structure is at that location? (The log gives chunk coordinates, you can multiply by 16 to get the block coords: ~[X0, Z1280])

Also, as there aren't a large number of cascading generation warnings (and we have fixed a couple of cases in development already), this is probably not the main cause of the worldgen issues. Take a look at the config, there are a few options that can be tweaked to improve worldgen performance (mainly lighting related).

**Comment by Tamaized** [comment]
A full log would have been better, there are known mods that cause TF gen to cascade. The log would expose what mods you have to us.

Going to close for inactivity though, feel free to drop a log if this still happens.
