### ISSUE TITLE
Loss of hotbar and inventory with Charm of Keeping and PlayerRevive mod

### ISSUE THREAD

**Issue by bmwalter68** [TeamTwilight/twilightforest#576]
Forge version: 14.23.4.2705
Twilight Forest version: 1.12.2-3.8.559
Link to crash log: not a crash

Steps to reproduce:

- Install mods: Baubles (1.5.2) Twilight Forest (3.8.559) JEI (4.11.0.202, optional) PlayerRevive (1.2.13) and it's dependency CreativeCore (1.9.22)
- Create a dedicated server with the same mods
- In both single player and multi player start with a player that has items in each inventory: Miners Ring in baubles, Sword in hotbar, Cobblestone in inventory
- Die both with and without the Charm of Keeping III

What I expected to happen:

On both single and multi player I expect all items to drop when the Charm of Keeping III is not equipped and for all inventory to be equipped after death when it is equipped.  Also, there appears to be a visual effect when the charm 'Does it's Thing (tm)' on player respawn which should happen in both single and multi player.

What happened instead:

When the player has Charm of Keeping III equipped in multi player, baubles are correctly kept through death but the players hotbar and inventory items do not drop.  There is also no visual effect on respawn.  This appears to be a conflict with the way PlayerRevive handles giving an opportunity for the player to avoid death by being revived by another player.  Removing PlayerRevive resolves the issue.

My first thought was this was a PlayerRevive issue, but I can only make it happen with the Charm of Keeping.

**Comment by bs2609** [comment]
Probably a similar issue to #338 then. Can you see if build 560 fixes this?

**Comment by bmwalter68** [comment]
Build 560 does appear to fix this issue.  Single and multi player dedicated are behaving as intended, including the visual effect.

Just out of curiosity, do you have any idea when a release (beta would be fine) with this fix would go live on Curse?  They don't let anyone publish modpacks with dev releases in them.  Not rushing you in any way, believe me I know how that goes...  You guys are really super responsive!  I'm just trying to decide if I should go ahead and push a version of my pack with PlayerRevive removed so no more inventory goes poof.
