### ISSUE TITLE
[suggestion] More Config Options!

### ISSUE THREAD

**Issue by mxnmnm** [TeamTwilight/twilightforest#577]
Add a config option to revert the progression system to the way it was before :)

**Comment by Hubry** [comment]
`/gamerule tfEnforcedProgression false` - the way it was waaay before, that is, no progression :P

**Comment by mxnmnm** [comment]
I meant more like the progression system before version 3.7.424  I liked the more strict progression system

**Comment by 3TUSK** [comment]
Side note: pursuing the old progression is still possible in the new progression mechanics. You can still do the old minotaur-hydra-phantomKnight-urGhast-yeti-snowQueen one by one (if you have enough self-control power)

**Comment by mxnmnm** [comment]
I know but I'm making a modpack and I just liked the more linear style it had

**Comment by mxnmnm** [comment]
It's not the end of the world but more of a creature comforts type thing

**Comment by 3TUSK** [comment]
This is rather a complex issue. AFAIK, currently Twilight Forest binds the progression with the advancement, and it's kinda impossible to have two set of progression tree in parallel, controlled by a config option - it's limitation inside Minecraft itself.

**Comment by Tamaized** [comment]
It may be possible to change the advancements themselves as a modpack maker to get your desired results.

**Comment by Drullkus** [comment]
You can revert the advancements by changing them with a ~~data pack~~ changing the advancement on the world save.
