### ISSUE TITLE
Twilight forest multiplayer

### ISSUE THREAD

**Issue by ShawmanicRonin** [TeamTwilight/twilightforest#579]
Forge version: 1.12.2
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. install Twilight Forest mod in mod folder for both .minecraft and the server file.
2. attempt to make a portal to the Twilight forest.

What I expected to happen: Lightning strikes after surrounding a 2X2 pool of water with flowers and throwing a diamond in creating the portal.

What happened instead: No lightning and no portal.

**Comment by Hubry** [comment]
Are you sure you have installed Forge properly? Please provide a console log from the server, if possible. 
Also, you didn't provide the Forge version or the mod version...

**Comment by ShawmanicRonin** [comment]
I am using V 1.12.2 of Minecraft and 1.12.2 Forge. and I am sure I have it installed correctly, it works in single player. I am also using the latest released 1.12.2 version of the mod. I am currently visiting family so I don't want to port forward my server and the latest log did not have the mod installed because we uninstalled it after we were unable to use it as well as experiencing the same problem with the Aether mod and the Betweenlands. I will provide a log as soon as I am able to.

**Comment by Drullkus** [comment]
Please post a screenshot of either:

The Minecraft Main Menu, or what you see when you have the F3 debug information visible (press F3 to toggle it)

**Comment by Tamaized** [comment]
@Drullkus That'd only confirm for the client.. which we already know is fine. The server end is the one having issues. A server log file will give us enough details.

**Comment by Drullkus** [comment]
In that case, I'd like screenshot of the server screen when it displays the server listing.

If the server is running vanilla, then it will show as a V on the right. If it is running forge, then it will show as a checkmark on the right.

I'm trying to see if they're even running forge.
