### ISSUE TITLE
Crash with Immersive Engineering

### ISSUE THREAD

**Issue by forestbat** [TeamTwilight/twilightforest#580]
Forge version: 2705
Twilight Forest version: 567
Link to crash log:
https://paste.dimdev.org/zekobedole.mccrash

Steps to reproduce:
1. setup twilight forest with IE

What I expected to happen:

What happened instead:

**Comment by Andromander** [comment]
Can confirm this does happen in build 567.

Before the crash, the following line is printed in the log.

`[17:03:48] [main/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber twilightforest for modid java.lang.NoClassDefFoundError: twilightforest/compat/ie/ItemTFShader`

Full log here: https://gist.github.com/Andromander/2ee76b03033c5a6790b6becc109ba6d3

**Comment by Drullkus** [comment]
Is this happening with build 574?

**Comment by Andromander** [comment]
Just tested build 574 with Immersive Engineering 84. Still crashes with same results.

**Comment by bs2609** [comment]
Does it work now (as of build 592)?

**Comment by Andromander** [comment]
Yes. Both with and without Immersive Engineering present.

**Comment by Drullkus** [comment]
Resolved by 3557c0e and eef7238
