### ISSUE TITLE
Client crash when approaching Dark Forest after killing Naga

### ISSUE THREAD

**Issue by Eplear** [TeamTwilight/twilightforest#583]
Forge version: spongeforge-1.12.2-2705-7.1.0-BETA-3342
Twilight Forest version: twilightforest-1.12.2-3.7.424-universal
Link to crash log: https://pastebin.com/04hCnYT5

Steps to reproduce:
1. Kill Naga
2. Load Dark Forest chunk.

What I expected to happen: a lovely stroll around the perimeter of the Dark Forest

What happened instead: screen goes solid green (kind of a bluish green), followed by a crash.

Notes:

I am on a server with about 10 people. I am the server owner and I am (as of now) the only person with this problem. Only one other player has killed a Naga and he does not have this problem.

If only part of the Dark Forest is loaded it does not seem to be a problem. I can see the trees in the distance but if I get closer than a chunk or two it keeps crashing.

The crash does not occur while in Creative mode.

Clearing the "world/advancements/PLAYER/" file fixes the problem until killing the Naga again.

**Comment by Andromander** [comment]
Does this also happen with the other biomes such as Snowy Forest, Swamp and Highlands? 

Also, do the players crash when the Lich is slain or if the Naga isn't slain?

**Comment by Eplear** [comment]
I tested the swamp and it crashes there too. 
So far no players have reported crashing when entering new biomes.

**Comment by Eplear** [comment]
It happened when I entered each of those areas. And no other players -again so far- have reported this.

**Comment by Eplear** [comment]
Reinstalled client files: No change. Still crashes upon killing Naga.
Deleted player files in server. No change. Still crashes upon killing Naga.

**Comment by Andromander** [comment]
Can they try killing a Naga *and* a Lich?

From what I'm getting at the crash log, something is trying to be a null when it shouldn't. Has this been reported to SpongeForge?

**Comment by Eplear** [comment]
One of my players is almost done with the progression actually and has killed all but the Ur-Ghast, Minotaur, and Hydra. He has had no problems. 
I also went into single-player and everything was working fine.

**Comment by Eplear** [comment]
And I have not reported to Sponge yet. I will shortly.

**Comment by Eplear** [comment]
So when I killed the Lich it doesn't crash but it still doesn't explain why I would crash upon entering these areas. I guess if you want to mark this solved it technically was.

**Comment by Andromander** [comment]
The crash has something to do with the weather rendering. Because the player has access to the area, they don't see the weather, but it seems to crash on trying to render the weather effects if the player can't access the area yet. 

I'd keep the issue open so the devs can take a look at it and for others with the same problem.

**Comment by bs2609** [comment]
75bf843569226725a53d8ab8c897dc391c284659 should stop this from crashing at least.

What is odd here is that only you were affected by this, which makes me think there's probably some other catalyst involved.

I'll close this as I don't think there's anything else to be done on our side, but I'd also recommend reporting it to Sponge as well, just so they can take a look at it.
