### ISSUE TITLE
CTD when breaking reappearing block

### ISSUE THREAD

**Issue by chantrykomori** [TeamTwilight/twilightforest#585]
My first time encountering the dark tower, I used my pickaxe to break a reappearing block because I wasn't sure what to do to get inside. When it broke, the screen went a light pastel green and then crashed. Upon trying to reload, I was stuck there as the game had already saved itself.

**Comment by Andromander** [comment]
Can you paste the crash log here, preferably via Gist, Pastebin or Hastebin?

**Comment by chantrykomori** [comment]
sorry, here you go! [https://pastebin.com/6NEeAyrr](https://pastebin.com/6NEeAyrr)

**Comment by Tamaized** [comment]
Chisel-Team/ConnectedTexturesMod/issues/63

**Comment by bs2609** [comment]
To be clear, you need to update CTM to the latest version.
