### ISSUE TITLE
Bug Breaking Particles

### ISSUE THREAD

**Issue by Killer-Demon** [TeamTwilight/twilightforest#588]
When breaking a Moonworm, Cicada, or Firefly it shows Soul Sand breaking particles.
They shouldn't have breaking particles at alll, as you don't break them and simply pick the little critters up.

![literal bugs](https://user-images.githubusercontent.com/31552602/43644664-dfe43adc-972f-11e8-8772-7185dc26cd10.png)

**Comment by bs2609** [comment]
To start with,  7d5221b6d6f13432eded40351e1be5930be0b676 changes this to use a more appropriate texture at least.
