### ISSUE TITLE
Thorns spread out and get glitchy after breaking

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#59]
Just destroyed one using a iron axe. Instead of disappearing, it did branch out to the side an turning into glitched green.

![2017-06-19_23 09 30](https://user-images.githubusercontent.com/10476794/27306113-b74a06e8-5544-11e7-9a13-94092079b44b.png)

**Comment by Benimatic** [comment]
That's how they're supposed to work.
