### ISSUE TITLE
Ur Ghast disappears as soon as it's spawned

### ISSUE THREAD

**Issue by wysohn** [TeamTwilight/twilightforest#591]
Forge version: 14.23.4.2705
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.7.424
Link to crash log: https://pastebin.com/PNPk2G7n

Steps to reproduce:
1.  spawn ur-ghast

What I expected to happen:

What happened instead:

---

I can clearly see that it's something to do with Sponge, but I have no idea if it can be fixed by TF or Sponge.

**Comment by bs2609** [comment]
Needs reporting to [Sponge](https://github.com/SpongePowered/SpongeForge/issues).

In the meantime, you can edit `config/sponge/global.conf` and set the `max-bounding-box-size` to 4500 or higher, or 0.
