### ISSUE TITLE
Baubles inventory will be cleared after player has been revived

### ISSUE THREAD

**Issue by CreativeMD** [TeamTwilight/twilightforest#592]
Hey there,

I'm the author of [PlayerRevive](https://minecraft.curseforge.com/projects/playerrevive) and recently somebody reported an issue between Baubles, PlayerRevive and your mod (https://github.com/CreativeMD/PlayerRevive/issues/14).

PlayerRevive prevents a player from death and instead "knocks" him. Other players can revive for a certain time. Once the time is over the player will die.

The problem is that Twilightforest clears the Baubles inventory, if a player will be revived.
Steps to reproduce:
1. Install CreativeCore, PlayerRevive, Baubles, Thaumcraft and Twilightforest
2. Place an item of Thaumcraft in the Baubles inventory
3. Open to Lan (Enable cheats)
4. Type in `/kill`
5. Type in `/revive <minecraftname>`
6. Look at your Baubles inventory (will be empty).

Once a player dies, PlayerRevive will cancel the event ([source](https://github.com/CreativeMD/PlayerRevive/blob/1.11.2/src/main/java/com/creativemd/playerrevive/server/ReviveEventServer.java#L216)), but it looks like Twilightforest can't handle it and clears the baubles inventory for some reason ([suspected method](https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/TFEventListener.java#L248)).

Unfortunately I don't know how to fix it, maybe you have an idea?

In Regards,
CreativeMD

**Comment by bs2609** [comment]
See #576 - what version of the mod is this relating to?

**Comment by CreativeMD** [comment]
Tested it using twilightforest-1.12.2-3.7.424-universal.jar (basically the newest versions of every mod).

**Comment by bs2609** [comment]
Can you try it using build 560+?

Dev builds of the mod can be found here: http://builds.steamnsteel.info/browse/TF-ONETWELVE

**Comment by Drullkus** [comment]
[Here's the latest build. Just click on 'Universal' under "Artifact".](http://builds.steamnsteel.info/browse/TF-ONETWELVE/latest/artifact)

**Comment by CreativeMD** [comment]
Nice, it worked without any problem. Thanks for your help!

**Comment by Darkmega18** [comment]
Drullkus, would it be possible to get a curse upload of your latest update that had fixed this? I'm hoping to update my modpack with this fix as soon as I can so it stops being a thing for everyone. :) glad it was already so quickly worked out though. I'm just not sure on the logistics of pack inclusions when it's not officially on curse and downloadable. :V
