### ISSUE TITLE
Construct's Armory support

### ISSUE THREAD

**Issue by drhead** [TeamTwilight/twilightforest#596]
Since Twilight Forest has its own tinker's construct support built in, I figure it'd be worth adding support for Construct's Armory as well.  I think it would be sufficient to add support for Ironwood, Naga Scale, Fiery Metal, Steelleaf, and Knightmetal.  I am not sure if it would make sense for Arctic/Yeti Fur to be used as a material since you can't use leather in CA, but I can't see many reasons not to do it.

**Comment by Killer-Demon** [comment]
This is unfortunately outside of the scope of the mod and we're not currently looking to add compat to addons for Tinkers' Construct. However, it's prime real estate for an addon mod to make it happen.
