### ISSUE TITLE
Server crash with latest version

### ISSUE THREAD

**Issue by Anteater46** [TeamTwilight/twilightforest#597]
Forge version: 14.23.4.2705
Twilight Forest version: 3.8.652
Link to crash log: https://pastebin.com/SRagprjQ

Dedicated server crashes on start.

**Comment by bs2609** [comment]
Hotfix Soon(tm)

**Comment by bs2609** [comment]
Should be fixed by 7c10453975d6fc91051b48c5b45f7f08486815a2.

**Comment by bs2609** [comment]
Released as version 3.8.654
