### ISSUE TITLE
Latest TF Release Crashes Dedicated Server

### ISSUE THREAD

**Issue by SalmonSays** [TeamTwilight/twilightforest#598]
Forge version: 1.12.2-14.23.4.2749
Twilight Forest version: 1.12.2-3.8.652
Link to crash log: https://hastebin.com/oxejecupol.coffeescript

Steps to reproduce:
1. Start up a fresh dedicated Forge server. Download Twilight Forest 1.12.2-3.8.652, stick it in the mods folder. Download Immersive Engineering 1.12-84, stick it in the mods folder. Launch normally.

What I expected to happen: I expected the dedicated server to load up and chug along happily.

What happened instead: The server did not load up/chug along and is very sad. This crash only happens on a dedicated server- the client loads into a world normally with the same mods. The offending line appears to be "java.lang.NoClassDefFoundError: net/minecraft/client/renderer/OpenGlHelper" so I'm hopeful this is just a client-only class that accidentally ended up getting called by the server as a result of the update involving Immersive Engineering shaders?

**Comment by Tamaized** [comment]
duplicate #597
