### ISSUE TITLE
Enchanted effect on Alpha Yeti helmet bleeds over onto adjacent items

### ISSUE THREAD

**Issue by bs2609** [TeamTwilight/twilightforest#600]
Probably caused by it using a 32x32 texture since f287922ed9c83e21cba3eb10ed787d4a78ae1041.

**Comment by Drullkus** [comment]
Admittedly I fail to see how the 32x32 texture causes this to happen. It’s only an item model that’s been scaled up. Got a screenshot?

**Comment by bs2609** [comment]
![2018-08-20_18 11 47](https://user-images.githubusercontent.com/1447117/44355477-a125c900-a4a4-11e8-9393-04a70324eef8.png)

**Comment by Drullkus** [comment]
Mojang.... WTF?

**Comment by Megalodab** [comment]
was just abt to report this I took a screenshot of the same thing with glass panes in the inv screen haha

**Comment by GizmoTheMoonPig** [comment]
Drull fixed this in the upcoming 1.16 port, so im closing this :)
