### ISSUE TITLE
Game crash during Forge initialization

### ISSUE THREAD

**Issue by PegasusRider** [TeamTwilight/twilightforest#601]
Forge version: 14.23.4.2757 (and 2747)

Twilight Forest version: 1.12.2-3.8.654

Link to crash log:

[https://gist.github.com/PegasusRider/55d8fa11d0ad1c6c41bfea2afdbf2a62](https://gist.github.com/PegasusRider/55d8fa11d0ad1c6c41bfea2afdbf2a62)

Steps to reproduce:

  1. Click "Play" on the Launcher.

What I expected to happen:

  The game to initialize and begin.

What happened instead:

  During the Forge initialization process, the game crashes. Not knowing anything about these crash reports beyond "if you don't know what you're doing..." so I'll leave the conjecture to you. But reverting to the previous version (1.12.2-3.7.424) of The Twilight Forest stops the crash(ing). Let me know if you need a mod list or something.

**Comment by Andromander** [comment]
Update Thaumcraft, that version has a major issue for compat.

**Comment by PegasusRider** [comment]
That did the trick. So "frustrating"! Thank you much, for the insight and the rapid response that ultimately isn't even _this_ mod's fault.

(and apparently I did something wonky with the "link", sorry. I'll try to remember to double check that in the future.)
