### ISSUE TITLE
Visual trouble with armor.

### ISSUE THREAD

**Issue by VadimComrade** [TeamTwilight/twilightforest#603]
Forge version: 14.23.4.2705
Twilight Forest version: (3.7.424)
![unknown 1](https://user-images.githubusercontent.com/42557990/44371759-4367a000-a4e9-11e8-8c64-4268798a0aa9.png)

**Comment by Andromander** [comment]
Can you try reproducing this with TF 3.8.654? Also, are there any other mods installed?

**Comment by VadimComrade** [comment]
I'll try 3.8.654 later because i noticed that version only today. And yes, there are many mods installed. 
![screenshot_3](https://user-images.githubusercontent.com/42557990/44372848-96902180-a4ee-11e8-9bc8-0a539d59a2b8.png)

**Comment by VadimComrade** [comment]
Ok, i tried to delete all other mods and download only TF new and old version and there was no visual bug with all armor. Relief :D.

**Comment by VadimComrade** [comment]
But this is strange, looks like some of this mods broke TF armor. And i noticed that bug earlier, playing on 
version 1.7.10 with TF and other mods.

**Comment by bs2609** [comment]
Closing this as it seems not to be an issue on our end. Feel free to ask on `#tech-support` on the [Discord](https://discord.gg/6v3z26B) if you would like help/advice finding the mod causing the issue.
