### ISSUE TITLE
Crash during boot with TF/Thaumcraft Error on heavily modded client.

### ISSUE THREAD

**Issue by Eogen** [TeamTwilight/twilightforest#606]
Forge version: forge-1.12.2-14.23.4.2705-universal.jar
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.8.654
--
Link to crash log: http://www.knodel.net/technic/CrashDumpLogs/TwlightForest/crash-2018-08-23_23.29.27-client.txt

Time: 2018-08-23 23:29:27 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Twilight Forest (twilightforest)
Caused by: java.lang.NoClassDefFoundError: thaumcraft/api/aspects/AspectRegistryEvent

Similar error was not seen on matching server install.

**Comment by Drullkus** [comment]
`thaumcraft                | 6.1.BETA17               | Thaumcraft-1.12.2-6.1.BETA17.jar`

Update your thaumcraft. We've set a minimum version of `6.1.BETA21` and for some reason that's not working.

**Comment by Eogen** [comment]
My bad -- only installed Thaumcraft a couple of weeks ago, did not think to check it for a new version so soon.  Thanks for the quick reply.
