### ISSUE TITLE
Blocking the naga with a shield crashes dedicated servers

### ISSUE THREAD

**Issue by Hubry** [TeamTwilight/twilightforest#608]
Forge version: 14.23.4.2739
Twilight Forest version: 3.8.654
Link to crash log: https://gist.github.com/retep998/9384bf88e4f5a2c24f5624eddb5bb817

Steps to reproduce:
1. Make sure you are on a server.
2. Try to use a shield to block the naga.

Seems like you are using a client-only method `Entity#setVelocity` here:
https://github.com/TeamTwilight/twilightforest/blob/7535b56cbb8ae018308195ed058854af50127034/src/main/java/twilightforest/entity/boss/EntityTFNaga.java#L671-L674

Tama pls.

**Comment by Tamaized** [comment]
reee
