### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#609]
Forge version: 14.23.4.2749
Twilight Forest version: (1.12.2-3.8.654)
Link to crash log: 

Steps to reproduce:
1. Shoot moonworm at trophy or under the trophy

What happened:Game crashed

**Comment by Andromander** [comment]
Fixed in b02840f0e532ba38200620894433872891e5bd8a

**Comment by Alex7896** [comment]
thank)
