### ISSUE TITLE
Duplication glitch (when used with an additional mod)

### ISSUE THREAD

**Issue by kara2810** [TeamTwilight/twilightforest#615]
#### Title: 

Dupe bug when using twilight uncrafting table with evilcraft broom caps:

#### Short description:

When using the uncrafting table to uncraft the broom caps, you are able to scroll through all types of caps regardless of the type of cap you plan to uncraft. When you actually try to uncraft said cap, you are able to get the cap, while getting the results of the "uncrafting". The only cost is experience 

#### Steps to reproduce the problem:

1. Get wand cap
2. Put wand cap into uncrafting table
3. Attempt to uncraft cap
4. Lose xp, keep cap, gain uncrafted results 

#### Expected behaviour:

The cap is consumed, and you get the items of the specific cap 
____

#### Versions:

- This mod: 3.8.654
- Minecraft: 1.12.2
- Forge: 14.23.4.2757

**Comment by Andromander** [comment]
As this is a duplication issue using the Uncrafting Table and how a mod may handle how recipes work, this essentially ties into #586 as the solution would require blocking a recipe from being used in it.
