### ISSUE TITLE
Feature Request: Troll Caves in Skylight Forest

### ISSUE THREAD

**Issue by Darkosto** [TeamTwilight/twilightforest#616]
Forge version: 2760
Twilight Forest version: 3.8.654

Is it possible to edit the surrounding mushroom and trollstein decorations to look a bit nicer when using the Skylight Forest config option? Currently, it looks a bit out of place because it's meant to be in a cave and not a void. Possibly removing the mushroom portion or adding some blocks in between?

Thank you very much! Have a great day!
DarkSoda

**Comment by bs2609** [comment]
"filler" terrain around the troll caves and the final castle basement is on the 'todo' list.

**Comment by bs2609** [comment]
"first draft" for troll caves is in 3bc422f777423ca4af6e402b40dca0719c6f34dd.

**Comment by Drullkus** [comment]
I'd like to also add that you can get the latest development build (which has 3bc422f) [here](http://builds.steamnsteel.info/browse/TF-ONETWELVE/latest/artifact)

Let us know how it works for you!

**Comment by Killer-Demon** [comment]
This would be relegated to a datapack nowadays and is for a feature (at least) currently not natively supported anymore. I'm closing this issue because of that and the previous comments on this.
