### ISSUE TITLE
Disconnecting player reserved bauble warning message omits player name

### ISSUE THREAD

**Issue by ahills** [TeamTwilight/twilightforest#619]
Forge version: 14.23.4.2715
Twilight Forest version: 1.12.2-3.7.424
Link to crash log: N/A

Steps to reproduce:
1. Player with bauble items in reserve disconnects from server

What I expected to happen:
```
[Server thread/WARN] [twilightforest]: Mod was keeping bauble items in reserve for player <player> but they logged out! Items are being dropped.
```

What happened instead:
```
[13:17:54] [Server thread/WARN] [twilightforest]: Mod was keeping bauble items in reserve for player %s but they logged out! Items are being dropped.
```
(The format string isn't expanded.)

**Comment by bs2609** [comment]
Should be fixed by 3f001e9bccf161b6d9192c3cda582090760d3c69, update to 3.8.654.

**Comment by ahills** [comment]
Thanks. Do you know when that will be promoted to `1.12.2-recommended`?

**Comment by bs2609** [comment]
Soon™

**Comment by Drullkus** [comment]
Recommended release bumped via f0a7364
