### ISSUE TITLE
Question: How do you subdue the enchantment renderer?

### ISSUE THREAD

**Issue by WolfieWaffle** [TeamTwilight/twilightforest#621]
I'm making an addon where I'm trying to make it compatible with steeleaves. Right now I have a pickaxe with the same texture, but when enchanted it's enchant glint purple effect is very strong compared to the tools in this mod. How did you achieve this effect?

**Comment by williewillus** [comment]
as far as I can tell we don't do anything to the enchantment effect

**Comment by WolfieWaffle** [comment]
Weird. Maybe since the mod I'm using has multiple components, they are stacking together? Thanks anyways.
