### ISSUE TITLE
Alpha fur progression doesn't trigger

### ISSUE THREAD

**Issue by iggyk** [TeamTwilight/twilightforest#622]
Forge version: 14.23.4.2715
Twilight Forest version: 3.7.424
(All The Mods 3 pack, build 5.9.8d)

Advancements made at the point:
- Twilight forest
- The Silence of the Forest
- The boots are mine
- With fire it writes
- Time to even the scales (2/2)
- Bring out your dead (2/2)
- Mighty Stroganoff (2/2)
- Trophied champion (2/2)
- Carminite acclimation (2/2)
- Something strange in the Towerwood
- Tears of fire (2/2)

Steps to reproduce:
1. Kill a bunch of Alpha Yetis
2. Pick up a heap of Alpha Furs
2.1 Throw it and pick it again a few times
3. Create a full set of Alpha Fur armor and wear it
4. Jump up and down, run around in futility.

What I expected to happen:
- Gain "Alpha Fur" advancement and access to Glacier

What happened instead:
- "Alpha Fur" advancement shows "1/2"

**Comment by Tamaized** [comment]
The advancement is gained by slaying the Alpha Yeti alone, crafting and wearing Arctic Armor or Yeti Armor doesn't affect this.

Regardless, i'm unable to reproduce the issue. Is this still a problem on the latest Alpha or Dev builds?
