### ISSUE TITLE
Blocking a Naga charge using a IE Heavy Plated Shield crashes

### ISSUE THREAD

**Issue by seasonedfish** [TeamTwilight/twilightforest#623]
Forge version: forge-1.12.2-14.23.4.2755
Twilight Forest version: 3.8.654 
Link to crash log: https://gist.github.com/fisher521/5051b9b801a7278470684c49890441e6

Steps to reproduce:
1.  Fight a Naga
2. When it charges, block using an Immersive Engineering Heavy Plated Shield

What I expected to happen:
The naga become dazed and the server not crash

What happened instead:
Server crashed

**Comment by bs2609** [comment]
Duplicate of #608, fixed in dev by 97511b2ac87c1ac4b15d619eeacb969ebcfa383c.
