### ISSUE TITLE
Blindness effect not disappearing with progression through fire swamp/lich castle.

### ISSUE THREAD

**Issue by NamelessTech** [TeamTwilight/twilightforest#624]
Forge version: 14.23.4.2705
Twilight Forest version: 3.8.654
Link to crash log: Not a crash, but a gameplay bug.

I've read in the version notes for this particular version that this bug has been fixed, but when playing over LAN _and_ single player for my particular world, the darkness effect persists over the Goblin Stronghold. All the other progression works, just not for the Goblin Strongholds. This doesn't cause a crash, it's just an inconvenience.

What I expected to happen:
The darkness effect would disappear with the defeat of the naga/lich castle.
What happened instead:
It didn't disappear, even though the naga has been killed, and two lich staves have been acquired.

Current Mods:
Aether Legacy v3.2
AtomicStryker's Battle Towers (Latest Build for 1.12.2)
Baubles v1.5.2
BiblioCraft v2.4.5
Biomes'o'Plenty v7.0.1.2399
ImmersiveEngineering v0.12-84
InventoryTweaks v1.63
JEI 4.11.0.212
JRFTL (ZombieFlesh to Leather mod) v1.1
Mantle v1.3.2.24
Tinker's Construct v2.10.1.87
Thaumcraft v6.1b23
WearableBackpacks v3.1.3
Xaero's Minimap v1.15.3

**Comment by Tamaized** [comment]
Is this still an issue on the latest builds? if so can i see your advancements for Twilight Forest.

**Comment by NamelessTech** [comment]
I’ll have to test the latest build, I removed it from my private modpack in the interim.

**Comment by Tamaized** [comment]
#1487
