### ISSUE TITLE
New Portal Every Time You Enter TF

### ISSUE THREAD

**Issue by King-of-Ferrets** [TeamTwilight/twilightforest#626]
Forge version: 14.23.4.2760
Twilight Forest version: 1.12.2-3.8.654
No Crash

Steps to reproduce:
1. Go through TF portal to TF
2. Exit TF portal to OW 
3. Re-enter TF portal (This should make a new portal every time you enter TF)

What I expected to happen:
Me to come through and leave through the same portals without creating a plane of portals.
What happened instead:
The creation of new portals every time my Father or I enter the dimension causing portals to spawn everywhere. There is also another glitch that I'm aware of but that I found out through another Issue on the thread: https://github.com/TeamTwilight/twilightforest/issues/617

**Comment by Andromander** [comment]
Can you supply a `debug.log` (preferrably via Gist due to the potential size of it)? It should show what's happening when portals are being created instead of being linked.

**Comment by King-of-Ferrets** [comment]
How do I get you this log? I am a bit new to this, and by that completely new.

**Comment by Andromander** [comment]
It should be in the `logs` folder in the `.minecraft` directory (getting there will be different depending on what operating system is being used. If it's Windows, you can type `%appdata%` and the `.minecraft` directory should just be there).

**Comment by King-of-Ferrets** [comment]
Here is today's game session, and yeah it's a bit big. https://gist.github.com/King-of-Ferrets/4c377e4f86c3274328033c553cf224d2
Edit: After I get the achievement [Take Aim] is when I start flopping back and forth between TF and OW dimensions.

**Comment by Vahtera** [comment]
Same bug here, using FTB Revelation pack. It creates a new portal upon teleporting via already made one, regardless from which dim we do it. As in, go into the TF - it creates a new portal, go to OW - it creates a new portal. 

I don't know if this is related, accidental or a feature of the Revelation pack, but if you make a waypoint in TF using JourneyMap and try to teleport to it (and have all the appropriate permissions), it teleports you OUT of TF to the OW ... and creates a new portal.

**Comment by bs2609** [comment]
Some work on fixing multiple portals being placed in the same location is in bec03618eae4def04e2908cccdd7d023f7b983fb (build 915).

**Comment by GizmoTheMoonPig** [comment]
redirecting this to #1459 so we can keep track of every portal issue in 1 place
