### ISSUE TITLE
Issue with Perfect Spawn & Twilight Forest

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#628]
I am using Perfect Spawn in my pack with people starting in the Wasteland from AbyssalCraft but when re-entering The Twilight forest  inside the Twilight Forest it sends me back to default world DIM 0 but I ant using world default world DIM 0  so is there anyway with The Twilight forest that I can set it to send me back to the Wasteland from Abyssalcraft instead of default world Dim 0 as all My spawn point and respawn Locations are AbyssalCraft Wasteland for my Default world as I am making a custom pack that does not have anyone respawning in the OverWorld aka DIM **0.**

Thanks Again,

Flame

**Comment by ghost** [comment]
https://github.com/lumien231/Perfect-Spawn/issues/23

**Comment by Drullkus** [comment]
Your message is a run on sentence, making it really hard to understand what you're trying to say. Can you at least break it up?

From what I can understand; I'm not even sure what's going on here, some mod is interfering with our portal... Chances are it's Perfect Spawn I guess?

Please try reproducing this issue by doing the actions you did to encounter this issue. Once you're done, please open the `logs` folder inside the Minecraft Directory to find the `debug.log` file. Once you've located it, please open it and make a gist ([gist.github.com](https://gist.github.com)) with the contents of the file and put the link here.

**Comment by Drullkus** [comment]
After an epiphany from a friend on Discord, am I correct to assume that when you exit the Twilight Forest through one of our portals, you're expecting to be in the Abyssal Wasteland dimension?

~~Unfortunately, this isn't possible at the moment. Normally you can only make portals to the Twilight Forest from the Overworld, and all Twilight Portals in the Twilight Forest will send you to the Overworld.~~

~~To leave the Twilight Forest back to the Abyssal Wasteland, you'd have to use a Wasteland portal.~~

As of commit cbeabfa you'll be able to change which dimension Twilight Portals send you to if you're trying to exit the Twilight Forest.

**Comment by bs2609** [comment]
Does cbeabfa4cbf4939efe4eedf6906ac80208c03b45 address your issue?

**Comment by ghost** [comment]
Yes, I am expecting when I exit the Twilight Forest through one of your portals, I go back to the Abyssalcraft Wasteland Dimension.
