### ISSUE TITLE
Final Castle Generation Bugs

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#63]
![2017-06-19_14 46 59](https://user-images.githubusercontent.com/29523364/27307693-c13ae5ea-54ff-11e7-8c84-13169ab231f2.png)
![2017-06-19_14 48 40](https://user-images.githubusercontent.com/29523364/27307694-c24826c8-54ff-11e7-9b9e-d9f43e9fa608.png)
![2017-06-19_14 53 23](https://user-images.githubusercontent.com/29523364/27307695-c4131422-54ff-11e7-9521-4ec39197e8d7.png)
Not too sure about the last picture, the tower on the right looked a little "broken" to me.
TF version 2.4.0.23
Forge version 13.20.0.2260

**Comment by Benimatic** [comment]
Can you post the seed and location?

**Comment by Benimatic** [comment]
Also the last picture shows a tower in "wrecked" condition. It's intentional, although the appearance may chance.

**Comment by ghost** [comment]
Just to let you know, this was on a server. We flew far away from the spawn point in the overworld and created a portal. The reason we don't have a seed is because it crashed, and ruairidh74 lost the world. We were also having trouble reproducing it

**Comment by GizmoTheMoonPig** [comment]
gonna throw this over into #1054, since that's a more up to date structure issue and includes this issue in it
