### ISSUE TITLE
Suggesttion: More variants of twilight woods in 1.13+ versions

### ISSUE THREAD

**Issue by mser7** [TeamTwilight/twilightforest#632]
More specific:
The bark blocks and the stripped bark blocks:
https://minecraft.gamepedia.com/Wood
The stripped log blocks:
https://minecraft.gamepedia.com/Stripped_log#Stripped_logs

**Comment by Winstannce** [comment]
There will be new variants of wood types coming up in the next Twilight Forest update I believe, and they will come as well with doors, fences, slabs, stairs and other blocks related to the wood type.

**Comment by Andromander** [comment]
Wood has been added since the beta release, and Stripped Logs and Stripped Wood is implemented via d1e8902.
