### ISSUE TITLE
Area progression effect not disappearing for lich castle

### ISSUE THREAD

**Issue by ambycloud** [TeamTwilight/twilightforest#633]
Forge version: forge-1.7.10-10.13.4.1614-1.7.10-installer-win
Twilight Forest version: (twilightforest-1.7.10-2.3.7)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline) **It didn't crash**

Steps to reproduce:
1. Naga has been defeated more than once with a morning star and a red katar
2, Naga scales have been picked up and placed in inventory.
3. Lich tower is inaccessible. Glowing yellow field is still in place.

What I expected to happen:
To be able to enter and defeat the Twilight Lich

What happened instead:
Stuck in the Progression, unable to advance without defeating the Twilight Lich and getting the sceptre.

**Comment by Andromander** [comment]
1.7.10 is no longer supported. Update to 1.12.2

**Comment by ambycloud** [comment]
well that's useless for support - no can do. modpack isn't set up for that. thanks for nothing.

**Comment by Tamaized** [comment]
You're welcome.
