### ISSUE TITLE
IDK?

### ISSUE THREAD

**Issue by budz7421** [TeamTwilight/twilightforest#635]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:
[crash-2018-09-30_19.56.09-server.txt](https://github.com/TeamTwilight/twilightforest/files/2432283/crash-2018-09-30_19.56.09-server.txt)

**Comment by bs2609** [comment]
Please follow the issue template, specify the mod/Forge versions you are using and
>please use a paste site such as gist, do not attach the .txt or paste the log inline

**Comment by Killer-Demon** [comment]
Closing this unless more information can be provided.
