### ISSUE TITLE
Custom mob spawner can't change the mob spawning

### ISSUE THREAD

**Issue by superwizzman** [TeamTwilight/twilightforest#639]
Forge version: 14.23.4.2705
Twilight Forest version: twilightforest-1.12.2-3.8.689-universal
Steps to reproduce:

My problem: 
Hi, I have a problem with my server. The twilight is very very full of monsters(and my game lagg). So I try to reduce the mob spawning with the config of custom mob spawner and modify the entitySpawnTypes. I put lower value to spawn cap and increase the spawntickrate. I put: I:spawncap=1 and I:spawntickrate=4000 and it's still spawning an over shit load of mobs. The only value is working is 0(no monsters). So I need help, I try many many things like disable plugins and nothing worked.

Thank you very much. Sorry for my bad english I'm Quebecer :P

**Comment by Tamaized** [comment]
Doesn't appear to be a problem with Twilight Forest alone. The only thing we do with mob spawns is disallow them from spawning above ground, that wont cause more spawns than vanilla so perhaps another mod is at play.
