### ISSUE TITLE
Crash Minecraft when i stay in Twilight Forest

### ISSUE THREAD

**Issue by Alex38Rus228** [TeamTwilight/twilightforest#640]
Forge version: 10.12.2.1147
Twilight Forest version: 2.0.0
Link to crash log: https://pastebin.com/8123uaM9

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:
![2](https://user-images.githubusercontent.com/43985839/46657057-174ad000-cbb8-11e8-90fb-badfbf277f71.PNG)

**Comment by Andromander** [comment]
Version 1.7.2 is not supported, and is more outdated than 1.7.10. Please update to 1.12.2.

**Comment by Drullkus** [comment]
You're using a *massively* outdated Twilight Forest version. This has been fixed 4 years ago.

You're on 2.0.0 for 1.7.2, the latest 1.7.10 version is 2.3.7, the absolute latest is 3.8.689 on 1.12.2.
