### ISSUE TITLE
[Skylight Forest] Naga wants the sweet voidic embrace of death

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#641]
Forge version: `does it look like I remember?`
Twilight Forest version: 3.8.654

Steps to reproduce:
1. Fight the Naga when it's a little too close to the edge.
2. Let it charge, preferably when it is facing towards the edge (you are standing by the edge).

What I expected to happen:
It'd attempt to not go over the edge when it charges towards the player.

What happened instead:
It may end up charging over the edge of the arena, causing it to continue falling towards the void. Sometimes it may want to avoid falling, but due to the way it digs the surroundings, sometimes it end up careening down the side. Perhaps the Naga may need some sort of way to prevent it from going over edges?

**Comment by Drullkus** [comment]
Hmmm...

What if I made the Naga fall from the sky after falling? Perhaps I could look into adding a temporary potion effect to reduct/negate fall damage if that happens to the Naga.

It'd fall from the sky centered on where its mob spawner was.

**Comment by GizmoTheMoonPig** [comment]
shouldnt be a problem anymore, the naga wont target you if you leave the courtyard. Skylight doesnt even exist atm, but regardless it should be fixed
