### ISSUE TITLE
Ghast trap advancement does not fire in the expected area

### ISSUE THREAD

**Issue by Hubry** [TeamTwilight/twilightforest#645]
Forge version: 14.23.5.2772
Twilight Forest version: 3.8.689
Link to crash log: n/a

Steps to reproduce:
1. ~~Run a dedicated server.~~ 
2. Activate a charged ghast trap (3+ ghastlings killed nearby) with a redstone signal while standing close to it *in a certain area around the trap* . An Ur-ghast is optional.

What I expected to happen: The advancement is given to the player.
What happened instead: The ghast trap fires but advancement is not given.

(pack is [Wikipack 3.2](https://minecraft.curseforge.com/projects/wikipack-3-2) but I have seen this happen on the previous iteration of the official TF server.)

**Comment by bs2609** [comment]
Does the trophy pedestal advancement work fine on a dedicated server?

If so, does build 735+ work?

**Comment by bs2609** [comment]
I'm gonna blame this:
https://github.com/TeamTwilight/twilightforest/blob/f43b214933801cbf258f3eb57eb7a63a3c75f4b2/src/main/java/twilightforest/block/BlockTFTowerDevice.java#L237

**Comment by Hubry** [comment]
Yes, the trophy pedestal one worked fine every time I tried so far.

So I was just unlucky by always activating the traps when standing in the wrong area, but only when playing on a server? Welp, correcting the issue now...

**Comment by bs2609** [comment]
Thanks for checking. As the trophy pedestal advancement triggers fine, then this is probably just that bounding box issue, which is fixed by 9e38c2f5f9de9b864b1491caa5e74272559d027c.
