### ISSUE TITLE
Unable to progress passed the Naga

### ISSUE THREAD

**Issue by MechanosG** [TeamTwilight/twilightforest#646]
Forge version: 14.23.5.2768
Twilight Forest version: 3.8.689 Universal
Link to crash log: N/A - no crash
Additional Information:  Enigmatica 2 Modpack version 1.51 for Minecraft 1.12.2

Steps to reproduce:
1. Kill Naga
2. Pick up loot (scales, trophy, shaders, etc)
3. Travel to nearest forest tower
4. Protection shielding doesn't go away - Can't enter the tower.
5. Repeat step 1 three more times, each time with a different weapon (all Tinker's Construct weapons).  Drop scales and trophy repeatedly then pick them back up hoping something will trigger while gear is unequipped to make sure nothing is teleporting/magnet'ing the items into inventory.  Kill ravens and make magic maps thinking maybe the progress is linked based on random Google feedback.  Bash head against tree and give up.

What I expected to happen:
I expected the yellow effects around towers to go away and let me inside.

What happened instead:
![2018-11-04_14 17 46](https://user-images.githubusercontent.com/4360512/47975835-81924b80-e064-11e8-8ca3-18da0df76cd5.jpg)
![2018-11-04_22 45 33](https://user-images.githubusercontent.com/4360512/47982205-be216f80-e083-11e8-9ed4-9498167ac58c.jpg)

**Comment by Tamaized** [comment]
Progression is based on your Advancements. Most likely the Naga advancement never triggered for some reason, check your Advancements, it is possible that the Modpack author may have changed them around. Or you're missing a prerequisite advancement.

**Comment by MechanosG** [comment]
Right, I forgot to mention that.  The advancement says I have 1/2 progress, and the text regarding what I need to do is semi-garbled.

**Comment by Tamaized** [comment]
Make sure you have the previous advancement done too

**Comment by MechanosG** [comment]
I did mention killing ravens.  The previous advancement is killing a raven for the feathers.  Then there is a nearby advancement where you have to make a magic map with the feather.  It doesn't come before the Naga advancement, but does have a line stretching across to it, so I made the map just to be certain.

**Comment by Tamaized** [comment]
You tried tossing the scale and trophy down and picking them back up again after killing a Raven too? If that still doesn't work I honestly have no idea why it wouldn't trigger.

**Comment by MechanosG** [comment]
Yep.  Tried that a bunch of times.  Even removed all my armor and baubles first just in case one of those might be messing it up, then tried picking the scales and trophy back up.  No change.  Also tried remaking the map once as the first time I made it I was in the overworld with my crafting supplies.  ...oh wait, now that I think about it, I've been crafting with an rftools storage thing.  And just today I had a Thaumcraft advancement not trigger because rftools is doing something odd with it's crafting.  When I recrafted using the normal craft window, it worked properly.  Maybe my map advancement hasn't triggered because I need to craft the map with a regular crafting box?  I'll try that soon as I can load up the game.

**Comment by MechanosG** [comment]
Darn.  Thought I was onto something, but that didn't fix it.  Gonna update main post with a screenshot of the advancements screen.

**Comment by Tamaized** [comment]
Your screenshot shows that the Twilight Hunter advancement hasn't been completed yet.

**Comment by MechanosG** [comment]
You're right.  I didn't realize that completed advancements should be dark yellow like the first one.  HOWEVER, I can't seem to get the Twilight Hunter to complete lol.  I just ran around killing everything in sight.  Boards, Deer, Ravens, Rams, Small birds, random enemies..  some with a tinker Kama, some with bare hand.  Can't get the Twilight Hunter advancement.

**Comment by 016Nojr** [comment]
![2019-01-30_00 33 19](https://user-images.githubusercontent.com/8192699/51947892-af4e1d00-2426-11e9-9fe0-0b54647135c8.png)

Advancements are broken for me, as you can see I have recieved the advancement for crafting the map, but not for entering the portal. And the map was made by killing a raven and crafting it from scratch.

**Comment by Tamaized** [comment]
is this still an issue?

**Comment by MechanosG** [comment]
Heya.  It was still an issue last I tested it (last year).  I never was able to successfully complete the advancement and had to cheat it to progress.  I no longer have access to that game world though (server shut down), so I'm unable to test further without just starting a new game in a new modpack.

Unless something has changed, I assume it's still an issue that can happen though.  Seems like it happened to me once in the past with a different modpack too.

**Comment by thewitchmaker** [comment]
i can confirm, it's still an issue.

**Comment by ptrxyz** [comment]
It's still an issue (playing on MC Eternal).

![2020-03-21_15 40 55](https://user-images.githubusercontent.com/209056/77228880-8d63ac80-6b8a-11ea-9889-c9f5a03a0056.png)

**Comment by joshlee233** [comment]
Issue for me too, playing mc eternal

**Comment by Tamaized** [comment]
No longer an issue, there's a vanilla bug that forces you to leave and rejoin the world for some advancements to appear.

**Comment by infernox64** [comment]
for me it was simply unequipping the botania magnet ring then dropping the trophies and scales and picking them up normally. that worked for both the naga and the lich, which both had the issue once i got to him
