### ISSUE TITLE
Mob lag problem in Twilight Forest

### ISSUE THREAD

**Issue by Wiral2** [TeamTwilight/twilightforest#647]
Forge version: 
Twilight Forest version: (1.12.2-3.8.689r)

The twilight forest itself isn't laggy at all, but the mobs inside the dimension seem to be laggy as seen in this video: 

https://streamable.com/du6n5

Is there any way to fix this? The mods I was running while doing this test were:
BetterFps 1.4.8
foamfix 0.10.2
Optifine HD U C9
Twilight Forest 1.12.2-3.8.689

Forge Version is "forge-1.12.2-14.23.5.2768"

**Comment by williewillus** [comment]
this seems like normal serverside lag (esp since your view distance is above 16 and more chunks keep loading during the video)

**Comment by Wiral2** [comment]
Even when I go afk for a bit in the twilight forest and then hit a mob again, it stills lags like that.

**Comment by williewillus** [comment]
could you take a profiler run with spark profiler (https://sparkprofiler.github.io/) or the vanilla profiler (/debug start, wait a minute or so, /debug stop) and post it?
