### ISSUE TITLE
Transparent pixels on various items

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#650]
The following have shown to have transparent pixels where they should not:
* [x] Alpha Yeti Fur
* [x] Arctic Fur
* [x] Arctic Plate, undyable layer
* [x] Crumble Horn
* [x] Fiery Blood
* [x] Fiery Plate
* [x] Fiery Legs
* [x] Ice Bomb
* [x] Ironwood Plate
* [x] Ironwood Legs
* [x] Knightly Plate
* [x] Knightly Greaves
* [x] Liveroot
* [x] Magic Map
* [x] Naga Scale Tunic
* [x] Naga Scale Leggings
* [x] Phantom Plate
* [x] Steeleaf Plate
* [x] Torchberries
* [x] Yeti Leggings
* [x] Yeti Jacket

**Comment by Drullkus** [comment]
Holy shit
