### ISSUE TITLE
Map doesn't reflect block colours of the Compressed Blocks

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#651]
Mostly aesthetic, but the Compressed Blocks on the map does not reflect what they look like. The map shows all Compressed Blocks as light grey.
![2018-11-21_22 15 06](https://user-images.githubusercontent.com/29526717/48840834-7ae13380-eddb-11e8-8162-bdd4117e991f.png)
Yes, I am a stickler for this kind of detail.

**Comment by bs2609** [comment]
This fixes the basic issue. If you'd like to do better colour matching, you can provide the `MapColor` you think looks best for each block and we can use those.

**Comment by Andromander** [comment]
Eventually ran a test world with 807, here's what I think:

Fiery Metal: Either `MapColor.GOLD` or `MapColor.BLACK_STAINED_HARDENED_CLAY`
Carminite: Either `MapColor.RED` or `MapColor.TNT`

**Comment by bs2609** [comment]
Forgot about that, sorry. Better colours added in 9bf29f6516686da004469e64aded659ab251c8f3.
