### ISSUE TITLE
Is this a problem with the Twilight Forest MOD?

### ISSUE THREAD

**Issue by BaiYeLoser** [TeamTwilight/twilightforest#652]
Forge version: 
Twilight Forest version:1.12.2
Link to crash log: https://shimo.im/docs/v6fA25xnJ20vxtAy/ 「Server Error」I am from China, I am sorry that I will not use git.
Steps to reproduce:
1. When I join the server,The console will send an error message，never happened before

What I expected to happen:
I am not sure if this is a problem with the Twilight Forest MOD.
What happened instead:

**Comment by 3TUSK** [comment]
> Copy of that log, for convenience: https://paste.ubuntu.com/p/j8FmPbsZBF/

Guess you have to provide full mod list and `debug.log` (located under `logs` folder). Twilight Forest is mentioned but I am not sure...

<details>
<summary>Uh. 点箭头展开</summary>
国内的话 https://paste.ubuntu.com 可用。  

请提供完整的 Mod 列表以及 `debug.log`（服务器/客户端目录下的 `logs` 文件夹里有。要出错时的那一份，请确认文件最后修改时间）。
</details>

**Comment by BaiYeLoser** [comment]
I am sorry that I am going to work now. I will send the relevant information to Discord. Which channel will I send to?


> > Copy of that log, for convenience: https://paste.ubuntu.com/p/j8FmPbsZBF/
> 
> Guess you have to provide full mod list and `debug.log` (located under `logs` folder). Twilight Forest is mentioned but I am not sure...
> 
> Uh. 点箭头展开
> 国内的话 https://paste.ubuntu.com 可用。
[debug.log](https://github.com/TeamTwilight/twilightforest/files/2606656/debug.log)

> 请提供完整的 Mod 列表以及 `debug.log`（服务器/客户端目录下的 `logs` 文件夹里有。要出错时的那一份，请确认文件最后修改时间）。

I am sorry that I am going to work now. I will send the relevant information to Discord. Which channel will I send to?

**Comment by bs2609** [comment]
The error is probably caused by this:
`[18:58:32] [Server thread/ERROR] [FML]: Cannot Hotload Dim: 25`
It looks like the dimension couldn't load, and so the world was null, which caused the following error.

**Comment by 3TUSK** [comment]
> #tech-support if you are going to send stuff over Discord.

**Comment by Tamaized** [comment]
was this ever resolved?

**Comment by BaiYeLoser** [comment]
> Forge version:
> Twilight Forest version:1.12.2
> Link to crash log: https://shimo.im/docs/v6fA25xnJ20vxtAy/ 「Server Error」I am from China, I am sorry that I will not use git.
> Steps to reproduce:
> 
> 1. When I join the server,The console will send an error message，never happened before
> 
> What I expected to happen:
> I am not sure if this is a problem with the Twilight Forest MOD.
> What happened instead:
