### ISSUE TITLE
Twilight forest isn't generate(at the server)

### ISSUE THREAD

**Issue by Skilvzlom** [TeamTwilight/twilightforest#653]
Forge version: 10.13.4.1614
Twilight Forest version: (this is the build number) 1.7.10 (2.3.7)
Link to screenshots log: https://imgur.com/a/rZ0eZjs

Steps to reproduce:
1. I jumped into the portal to Twilight forest.
2. I saw that the world wasn't generated.

What I expected to happen: I hoped to see normal twilight forest.

What happened instead: I saw that the world wasn't generated.

P.S. I am playing at the server.When I tried to generate Twilight forest at Singleplayer it had generated as usual.

**Comment by williewillus** [comment]
1.7 is not supported
 additionally, this seems to just be worldgen lag. let it settle for a bit and it should appear
