### ISSUE TITLE
Cannot Pick-Block Double Slabs

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#657]
Forge version: 13.24.5.2768
Twilight Forest version: 3.8.807

Attempting to pick-block a double slab of any TF Block will not switch to or bring up the single slab.

**Comment by bs2609** [comment]
Should be fixed by 06530334720c0377c50285bfe42d3503246fb61b and 0c3cad8ae29c9ba3659a9dce166a4d57dcb71116.
