### ISSUE TITLE
Anti-builders delete Iron Chests' shulker boxes

### ISSUE THREAD

**Issue by ItsTheKais** [TeamTwilight/twilightforest#659]
Forge 14.23.5.2772
Twilight Forest 3.8.689
Iron Chests 7.0.54.838

**Steps to reproduce:** Place any shulker box from Iron Chests near an anti-builder.

**What I expected to happen:** The box is dropped as an item with its contents intact, like a vanilla shulker box.

**What happened instead:** The box is vaporized, taking all of the loot stored inside with it.

**Comment by Andromander** [comment]
Closing as this can now be configured with a Tag.
