### ISSUE TITLE
Entity inside Twilight Forest crashes server

### ISSUE THREAD

**Issue by SomeBrian** [TeamTwilight/twilightforest#660]
**Forge version**: 14.23.4.2759
**Twilight Forest version**: 3.8.654
**Modpack**: FTB Revelation 2.5.0

**Link to crash log**: [Crash log](https://gist.github.com/SomeBrian/b987ef5cbfe6d67b413eaef12df06ced)

So I'm running an unmodified FTB Revelation server. I assume one of the other mods in the pack are fighting with this one, but I am unsure on how to prevent this conflict. I tried searching previous issues, but couldn't find any that were specific to my crash.

**_Edit_**: Just realized the modpack comes with Twilight Forest version 3.8.654. Would updating to current version help?

**Steps to reproduce**:
1. Exploring Twilight Nether (generates fine, can exit/return fine). I believe it was a castle place?
2. Entity error, Server crashes/shuts down
3. Log back in character, server immediately hits problem again and shuts down again.
4. Tried deleting DIM5 (and DIM-5) folders to reset forest
5. Different Entity crashed server once explored far enough in (this crash log is from the crash after reset)
6. If I manually change player location and return to the Twilight forest, it works until I hit a bad Entity.

**What I expected to happen**:
Explore the forest without crashing, haha. My first time here, so not sure what was supposed to happen normally.
**What happened instead**:
Repeated server crash

**Comment by bs2609** [comment]
Can reproduce, but it isn't an issue with the mod - it appears that there's some incompatibity here with the JVM your server is using.

This has been reported to Forge (see the linked issue) but in the meantime, I can only really recommend seeing if you can have your server run with an OpenJDK-based JVM.

**Comment by SomeBrian** [comment]
Well that's no good. Unfortunately, it's through a minecraft server hosting site. So I wouldn't have control on what JVM they use. The price of convenience...

Thanks for the help though!

**Comment by SigmaChi07** [comment]
https://pastebin.com/jJzCzszM

Confirmed. Still causing a server crash. It seems to only be with Swarm Spider Spawners in the Twilight Forest. I can delete them in MCEdit and go in fine, but the minute I generate a new SSSpawner the server crashes and I have to MCEdit it back out again. There are only two versions of Java 8 that Minecraft-Hosting.pro uses in its control panel, Java 8 and Java 8 (Legacy). I can't even run DW20 1.12.2 with the legacy version. So if it's something with Java 8, has anyone found a fix? Or, is there a way to just disable SSSpawners in the TF?

**Comment by Andromander** [comment]
```    
Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181107_95 (JIT enabled, AOT enabled)
    OpenJ9   - 090ff9dcd
    OMR      - ea548a66
    JCL      - b5a3affe73 based on jdk8u192-b12), Eclipse OpenJ9
```
This is still an issue regarding with OpenJ9 (see comment above by bs2609).

**Comment by bs2609** [comment]
This should now be fixed as of Forge 2815.
