### ISSUE TITLE
Convert Sorting Tree to check inventory capability instead of vanilla chests

### ISSUE THREAD

**Issue by noobanidus** [TeamTwilight/twilightforest#662]
Forge version: 
Twilight Forest version: 46ad3f9
Link to crash log: N/A

Currently, the Sorting Tree is the most amazing thing in the game. Unfortunately, it only supports vanilla inventories. The code is a bit spaghetti, but it would be great if it could be updated to check for any compatible inventory within range.

**Comment by jodlodi** [comment]
Implemented in [https://github.com/TeamTwilight/twilightforest/commit/9b44e0ba0eb77ce531816bf1738baeda44df9fa6](url)
