### ISSUE TITLE
Rapiers from Tinkers construct does not have special effect on Twilight lich's shields

### ISSUE THREAD

**Issue by mser7** [TeamTwilight/twilightforest#664]
Forge version: 14.23.4.2749
Twilight Forest version: (this is the build number)1.4.23
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Spawn Twilight Lich
2. Hit Lich with a rapier from Tinkers

What I expected to happen:
Rapier either:
Depletes one of lich's shield, like in this vid: https://youtu.be/WSXU0EPsmVo?t=438
Bypass the shield, damage the lich's health, while it is still in the first phase.
What happened instead:
Nothing happened.

**Comment by Tamaized** [comment]
Not our issue. Besides, seems like a bug was fixed.

**Comment by Drullkus** [comment]
1.4.23???

**Comment by mser7** [comment]
My bad, it was 3.8.689
