### ISSUE TITLE
Improve Chisel integration & make Nagastone craftable

### ISSUE THREAD

**Issue by noobanidus** [TeamTwilight/twilightforest#665]
Currently, the default integration with Chisel (I'm not actually sure whether this is a choice by Chisel or whether this is a part of Twilight Forest itself, because I haven't sat down and dug through the source code of each) allows you to convert any type of stone into Nagastone, and vice versa.

This allows you to obtain Nagastone without ever visiting a Naga Courtyard or even the Twilight Forest itself.

Having a semi-reliable source of Nagastone itself would be great, but I feel as though this default implementation makes it too easy to get. An alternate recipe would involve 8 OreDictionary stone around a single naga scale: the number of nagastone this creates could be modified as desired. Example: ![javaw_2018-12-05_11-07-50](https://user-images.githubusercontent.com/8621206/49483222-81b18100-f886-11e8-9c16-b8d962f78cd5.png)

Additionally, moving Nagastone to its own Chisel section would mean the ability to chisel the individual types, without making it an infinite, no-cost resource.

**Comment by bs2609** [comment]
Partly resolved by 2cbcd6c75ac5439484c5f29b386b9ed638b154a0, we can also look at adding a "conversion" recipe later.

**Comment by Killer-Demon** [comment]
This would be more fitting for an addon these days.
