### ISSUE TITLE
Twilight Portal is unable to be "activated"

### ISSUE THREAD

**Issue by Steamoonkie** [TeamTwilight/twilightforest#666]
Forge version: 14.23.5.2795
Twilight Forest version: 3.8.689
Link to crash log: Not Crashed

Steps to reproduce:
1. Make Twilight Forest portal being "circular" as on provided screenshot.
https://imgur.com/a/Vp8YkcG

What I expected to happen: According to Wikipedia of Sir Benimatic, portal can be "any shape and size as long as it have 4 blocks of water". I expected Twilight Portal to create.

What happened instead: No Twilight Portal created.
(OFF-TOPIC - #666 Post... "The Evil Within" :-P)

**Comment by Andromander** [comment]
Chances are that the portal of the left is too large to create a portal. I might not have specified that properly on the Wiki.

**Comment by bs2609** [comment]
^ There's a maximum size of 64 water blocks as well, sorry if that isn't made clear.

**Comment by Steamoonkie** [comment]
Alright, so its needed to be max. average size of **64 blocks which is like 8x8 inline & 9x9 outline blocks**? Hopefully I understood right. Closing cause I was though it using same mechanix as Nether Vanilla Portal :)
Thanks for help! Keep up good work! P.S.: Great work on textures and logo! Youre doing good work on making this again one of best mods ever (it always was in my heart) :)))
