### ISSUE TITLE
Darkwood Trees Drop to 0 FPS when using Tree Chopper Mod

### ISSUE THREAD

**Issue by dauntlessgamer** [TeamTwilight/twilightforest#673]
Darkwood Tree FPS drops to 0 FPS using Tree Chopper

I noticed a huge lag spike whenever trying to chop a Darkwood tree using any axe with the Tree Chopper Mod.
If you can fix this then it would be greatly appreciated.

Dauntless Gamer

**Comment by noobanidus** [comment]
Is this with the normally chopping or with the Tree Chopper functionality? I know the default automatically turns it on, but if you shift-mine the block with an axe it should just do the normal default chopping.

Either way, this is likely going to be an issue with the interconnectedness of Darkwood forests and Tree Chopper attempting to path a "tree" out of them but somehow becoming connected to multiple trees. In all likelihood, you'd need to talk to the Tree Chopper developers about an upper limit on how many blocks they try to path through when searching for trees.

Alternately, if it's happening in normal mode (non-Tree Chopper) with just Tree Chopper installed, it's probably still a Tree Chopper issue but might be something else.
