### ISSUE TITLE
Miscellaneous Suggestions

### ISSUE THREAD

**Issue by orian34** [TeamTwilight/twilightforest#676]
Here are some ideas and suggestions put here since the experiment on discord has ended.

Items:
-A swiftness charm based on how empty your inventory is(empty slots eg).
-An Aurora shield that can only protect from magic(breaks if you take physical and needs to recharge).
-A luck charm that gives a small chance to add some loot to never opened chests.
-Elemental Variants on the Peacock Feather Fan(such as boreal or fiery).
-Aria Charm, gives water breathing as long as you don't do any actions except moving.

Locations:
-A spider infested tree, with cobwebs and spawners, cocoons and shenanigans. Could also be in the dark forest depths with spider queens.

Creatures:
-Drowned souls that appear underwater in the lake biomes. Would act like twilight wraiths, they would be trying to make you sink.
-A siren-like creature in a lake cave. Could even be a boss and a small dungeon.

**Comment by noobanidus** [comment]
All of these are ideas that I supported during the experiment! Something to make underwater exploration/underwater ruins more accessible would be great -- perhaps an area-of-effect underwater breathing? I'm not sure how water breathing works these days.

**Comment by orian34** [comment]
Reworked the aria charm, should be similar to what you meant 👌

**Comment by mateidragony** [comment]
My favorite idea here is the twilight lake improvements. I think that they're currently pretty bland and some sort of mini boss would hugely improve the biome as a whole

**Comment by Killer-Demon** [comment]
While a tree full of spiders and more things for the lake are things we might and want to do, the rest of the suggestions are a not quite things we're currently looking to add in their suggested forms. Because of that I'll be closing this issue, but we might see something from here in the future.
