### ISSUE TITLE
Bighorn sheeps still have the old wool color

### ISSUE THREAD

**Issue by mser7** [TeamTwilight/twilightforest#677]
Disgusting
https://imgur.com/2hdEJLx

**Comment by bs2609** [comment]
As far as I can tell, they have exactly the same wool colours as vanilla sheep. Can you post a screenshot showing what you think the difference is?

(also, embed images in the post rather than linking elsewhere if possible)

**Comment by mser7** [comment]
Ok, I will post the comparision when I have the chance, for the image embed, I don't know how, but will try to find out.

**Comment by mser7** [comment]
![2018-12-24_09 10 48](https://user-images.githubusercontent.com/22555489/50389396-6ab2d000-075c-11e9-9528-2ebf204609ba.png)
Yeah you was right, sorry
