### ISSUE TITLE
Sleeping in TF dimension don't clear rain

### ISSUE THREAD

**Issue by mser7** [TeamTwilight/twilightforest#679]
Forge version: 14.23.4.2749
Twilight Forest version: 3.8.689
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Sleep on a bed in TF dimension as it is raining

What I expected to happen:
The rain go away as I wake up
What happened instead:
It doesn't

**Comment by Tamaized** [comment]
I remember looking into this with another dimension mod.
`DerivedWorldInfo` is to blame and is the default WorldInfo instance for all non-overworld dimensions.

**Comment by Drullkus** [comment]
[Issue related to Mojang being Mojang; see my write-up here](https://github.com/TeamTwilight/twilightforest/issues/1174#issuecomment-928652461)
