### ISSUE TITLE
Giant lily pads spawning improperly

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#68]
Forge Version: 13.20.0.2315
Twilight Forest Version: 2.4.0.23

Giant Lily Pads have two issues. First issue, sometimes Giant Lily Pads will spawn on ocean-level grass. Second issue, some Giant Lily Pads may overlap when spawning, causing a portion of the lily pad to vanish.
![2017-06-20_13 52 24](https://user-images.githubusercontent.com/29526717/27316074-be334876-55c0-11e7-892e-13ea5f47d187.png)

**Comment by Matti-Koopa** [comment]
They will also incorrectly break. Leaving cut-off parts behind.
