### ISSUE TITLE
Crashed While Initializing Game

### ISSUE THREAD

**Issue by Bubbleflames101** [TeamTwilight/twilightforest#683]
Forge version: 1.7.10 - 10.13.4.1614
Twilight Forest version: (1.7.10 - 2.3.7)
Link to crash log: https://gist.github.com/Bubbleflames101/b2c975e6d6b4608dd4b194c394d193c5

Steps to reproduce:
1. Press the "Play" button on the Minecraft launcher.

What I expected to happen:
 - Game go through all seven steps of Forge setup correctly and run game.

What happened instead:
 - Game crashed during initialization.

**Comment by Tamaized** [comment]
1.7 isn't supported
