### ISSUE TITLE
Crash with JEID (BlockTFMagicLogSpecial)

### ISSUE THREAD

**Issue by Sunconure11** [TeamTwilight/twilightforest#685]
Forge version: 14.23.5.2807
Twilight Forest version: MC 1.12.2 - 3.9.851
Link to crash log: https://paste.dimdev.org/nodubaloti.mccrash

Steps to reproduce:
1. Install twilight forest off of curseforge
2. ???
3. Profit

What I expected to happen:

Game to boot up

What happened instead:

https://paste.dimdev.org/nodubaloti.mccrash

**Comment by Andromander** [comment]
You might want to throw that to VanillaFix, JEID, or any mod that uses Mixins since the stacktrace mentions they are used. Twilight Forest does not have these.

Correction: this is definitely caused by JEID.

**Comment by ScienceDrummer** [comment]
So we should take this issue to the Just Enough IDs team? I have the same exact crash btw.

https://paste.dimdev.org/iyutolasoh.mccrash

**Comment by bs2609** [comment]
Yes, this isn't an issue on our side.

**Comment by PulseBeat02** [comment]
If you use a slightly older version (one version earlier) it should work.

**Comment by ValentineBlaze** [comment]
For anyone having this problem JEID does have a fix its a jeid intergration  mod which fixes it

**Comment by Tamaized** [comment]
The JEID dev has this fixed in-dev. Honestly i'd rather people bug him to push a new release as this is annoying.
