### ISSUE TITLE
I cant run it (new version)

### ISSUE THREAD

**Issue by peryus** [TeamTwilight/twilightforest#686]
[crash-2019-01-12_16.08.54-client.txt](https://github.com/TeamTwilight/twilightforest/files/2752120/crash-2019-01-12_16.08.54-client.txt)

**Comment by peryus** [comment]
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2019-01-12 16:08:54 EET
Description: Initializing game

java.lang.ExceptionInInitializerError
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_403_TFEntities_registerEntities_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3930)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
    at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:415)
    at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:286)
    at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:271)
    at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:256)
    at net.minecraftforge.common.util.EnumHelper.addSpawnPlacementType(EnumHelper.java:156)
    at twilightforest.entity.TFEntities.<clinit>(TFEntities.java:31)
    ... 16 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.getDeclaredConstructor(Unknown Source)
    at net.minecraftforge.common.util.EnumHelper.getConstructorAccessor(EnumHelper.java:207)
    at net.minecraftforge.common.util.EnumHelper.makeEnum(EnumHelper.java:220)
    at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:406)
    ... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3792187992 bytes (3616 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
  JVM Flags: 7 total; -Xmn128M -Xmx4096M -XX:+UseConcMarkSweepGC -Xms4096m -Xmx4096m -XX:PermSize=256m -XX:MaxPermSize=512m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 88 mods loaded, 87 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                     | Version                | Source                                        | Signature                                |
       |:----- |:---------------------- |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft              | 1.12.2                 | minecraft.jar                                 | None                                     |
       | UCH   | mcp                    | 9.42                   | minecraft.jar                                 | None                                     |
       | UCH   | FML                    | 8.0.99.99              | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge                  | 14.23.5.2768           | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | ivtoolkit              | 1.3.3-1.12             | minecraft.jar                                 | None                                     |
       | UCH   | foamfixcore            | 7.7.4                  | minecraft.jar                                 | None                                     |
       | UCH   | baubles                | 1.5.2                  | Baubles-1.12-1.5.2.jar                        | None                                     |
       | UCH   | jei                    | 4.13.1.224             | jei_1.12.2_4.13.1.224.jar                     | None                                     |
       | UCH   | thaumcraft             | 6.1.BETA26             | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
       | UCH   | botania                | r1.10-358              | Botania+r1.10-358.jar                         | None                                     |
       | UCH   | aiotbotania            | 0.5.1                  | aiotbotania-0.5.1.jar                         | None                                     |
       | UCH   | antiqueatlas           | 4.4.8                  | antiqueatlas_1.12.2_4.4.8.jar                 | None                                     |
       | UCH   | antiqueatlasoverlay    | 1.2                    | antiqueatlas_1.12.2_4.4.8.jar                 | None                                     |
       | UCH   | examplemod             | 1.0                    | antiqueatlas_1.12.2_4.4.8.jar                 | None                                     |
       | UCH   | applecore              | 3.1.3                  | AppleCore_mc1.12.2_3.1.3.jar                  | None                                     |
       | UCH   | appleskin              | 1.0.8                  | AppleSkin_mc1.12_1.0.8.jar                    | None                                     |
       | UCH   | aztech                 | 1.5                    | aztech-1.12.2.5.jar                           | None                                     |
       | UCH   | betteranimalsplus      | 3.0.0                  | betteranimalsplus_1.12.2_3.0.0 (1).jar        | None                                     |
       | UCH   | bibliocraft            | 2.4.5                  | BiblioCraftv2.4.5MC1.12.2 (2).jar             | None                                     |
       | UCH   | bookshelf              | 2.3.568                | Bookshelf_1.12.2_2.3.568 (1).jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | bmtr                   | 0.4                    | BringMeTheRings_0.4.jar                       | None                                     |
       | UCH   | carryon                | 1.12                   | CarryOnMC1.12.2v1.12.jar                      | None                                     |
       | UCH   | chameleon              | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                      | None                                     |
       | UCH   | chickens               | 6.0.4                  | chickens-6.0.4.jar                            | None                                     |
       | UCH   | ctm                    | MC1.12.2-0.3.3.22      | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
       | UCH   | chisel                 | MC1.12.2-0.2.1.35      | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
       | UCH   | cookingforblockheads   | 6.4.65                 | CookingForBlockheads_1.12.2_6.4.65.jar        | None                                     |
       | UCH   | cyclopscore            | 0.11.11                | CyclopsCore-1.12.2-0.11.11 (1).jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCH   | dailies                | 1.12.2-6               | dailies-1.12.2-6.jar                          | None                                     |
       | UCH   | dummycore              | 2.4.112.5.             | DummyCoreUnofficial-2.4.112.5.jar             | None                                     |
       | UCH   | endercrop              | 1.12-1.3.4             | endercrop_1.12_1.3.4 (1).jar                  | None                                     |
       | UCH   | endreborn              | 0.2.7                  | EndReborn+II+[0.2.7].jar                      | None                                     |
       | UCH   | evilcraft              | 0.10.64                | EvilCraft-1.12.2-0.10.64 (2).jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCH   | evilcraftcompat        | 1.0.0                  | EvilCraft-1.12.2-0.10.64 (2).jar              | None                                     |
       | UCH   | farmingforblockheads   | 3.1.25                 | FarmingForBlockheads_1.12.2_3.1.25.jar        | None                                     |
       | UCH   | findyourway            | 1.2.1                  | findyourway-1.12.2-1.2.1.jar                  | None                                     |
       | UCH   | foamfix                | 0.10.3-1.12.2          | foamfix-0.10.3-1.12.2.jar                     | None                                     |
       | UCH   | followingvillagers     | 1.0.0                  | FollowingVillagers_1.0.0.jar                  | None                                     |
       | UCH   | forgelin               | 1.7.4                  | Forgelin_1.7.4 (2).jar                        | None                                     |
       | UCH   | fpsreducer             | mc1.12.2-1.10.3        | FpsReducer_mc1.12.2_1.10.3.jar                | None                                     |
       | UCH   | gardenstuff            | 1.12-2.1.1             | GardenStuff-1.12-2.1.1.jar                    | None                                     |
       | UCH   | gottschcore            | 1.5.1                  | GottschCore-mc1.12.2-f14.23.5.2768-v1.5.1.jar | None                                     |
       | UCH   | huntingdim             | 1.0.30                 | HuntingDimension_1.12.2_1.0.30 (1).jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | waila                  | 1.8.26                 | Hwyla_1.8.26_B41_1.12.2.jar                   | None                                     |
       | UCH   | llibrary               | 1.7.14                 | llibrary-1.7.14-1.12.2 (1).jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | UCH   | iceandfire             | 1.6.0                  | iceandfire-1.6.0-1.12.2.jar                   | None                                     |
       | UCH   | ironchest              | 1.12.2-7.0.48.833      | ironchest_1.12.2_7.0.48.833.jar               | None                                     |
       | UCH   | lex                    | 1.0.7                  | LibEx-1.12.2-1.0.7.jar                        | None                                     |
       | UCH   | magma_monsters         | 0.3.0                  | MagmaMonsters_1.12.2_0.3.0.jar                | None                                     |
       | UCH   | malisiscore            | 1.12.2-6.4.0           | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
       | UCH   | malisisdoors           | 1.12.2-7.3.0           | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
       | UCH   | morechickens           | 3.1.0                  | morechickens-1.12.2-3.1.0.jar                 | None                                     |
       | UCH   | mowziesmobs            | 1.5.1                  | mowziesmobs-1.5.1.jar                         | None                                     |
       | UCH   | naturescompass         | 1.5.0                  | NaturesCompass_1.12.2_1.5.0.jar               | None                                     |
       | UCH   | nex                    | 2.0.7                  | NetherEx-1.12.2-2.0.7.jar                     | None                                     |
       | UCH   | nutrition              | 4.0.0                  | Nutrition-1.12.2-4.0.0.jar                    | None                                     |
       | UCH   | harvestcraft           | 1.12.2zb               | PamsHarvestCraft1.12.2zb (2).jar              | None                                     |
       | UCH   | reccomplex             | 1.4.7                  | RecurrentComplex-1.4.7.jar                    | None                                     |
       | UCH   | xreliquary             | 1.12.2-1.3.4.767       | Reliquary_1.12.2_1.3.4.767 (1).jar            | None                                     |
       | UCH   | repairgem              | 1.0.0                  | RepairGem-1.12.2-1.1.0.jar                    | None                                     |
       | UCH   | roost                  | 1.3.0                  | roost-1.12-1.3.0 (1).jar                      | None                                     |
       | UCH   | rustic                 | 1.0.12                 | rustic_1.12.2_1.0.12.jar                      | None                                     |
       | UCH   | spartanweaponry        | beta 1.2.3             | SpartanWeaponry-1.12.2-beta-1.2.3.jar         | None                                     |
       | UCH   | spartanfire            | 0.03                   | spartanfire-0.03.jar                          | None                                     |
       | UCH   | spartanshields         | 1.4.1                  | SpartanShields-1.12.2-1.4.1.jar               | None                                     |
       | UCH   | storagedrawers         | 1.12-5.2.5             | StorageDrawers-1.12.1-5.3.3.jar               | None                                     |
       | UCH   | stygian                | 1.0.4                  | stygian-1.0.4.jar                             | None                                     |
       | UCH   | thaumicbases           | 3.3.310.5r             | tb-3.3.310.5r.jar                             | None                                     |
       | UCH   | fastcrafting           | 2.6                    | TCFastCraftingMod_2.6_mc1.12_1.12.2.jar       | None                                     |
       | UCH   | texfix                 | 4.0                    | TexFixV_1.12_4.0.jar                          | None                                     |
       | UCH   | thaumicjei             | 1.2.1                  | ThaumicJEI-1.12.2-1.5.5-23.jar                | None                                     |
       | UCH   | thaumicperiphery       | 0.3.0                  | thaumicperiphery-0.3.0.jar                    | None                                     |
       | UCH   | thaumictinkerer        | 1.12.2-5.0-353c71c     | thaumictinkerer-1.12.2-5.0-353c71c (1).jar    | None                                     |
       | UCH   | tombmanygraves         | 1.12-4.2.0             | TombManyGraves_1.12_4.2.0 (2).jar             | None                                     |
       | UCH   | torohealthmod          | 1.12.2-11              | torohealth-1.12.2-11.jar                      | None                                     |
       | UCH   | toroquest              | 1.12.2-5.3             | toroquest-1.12.2-5.3.jar                      | None                                     |
       | UCH   | totemexpansion         | 1.0.4                  | totemexpansion_1.0.4_1.12.2.jar               | None                                     |
       | UCH   | bspkrscore             | at_0.9                 | Treecapitator-1.12-at_0.9a.jar                | None                                     |
       | UCH   | treecapitator          | at_0.9                 | Treecapitator-1.12-at_0.9a.jar                | None                                     |
       | UCH   | twilightforest         | 3.9.851                | twilightforest-1.12.2-3.9.851-universal.jar   | None                                     |
       | UCH   | vampirism              | 1.4.9                  | Vampirism-1.12.2-1.4.9 (1).jar                | None                                     |
       | UCH   | teamlapen-lib          | 1.4.9                  | Vampirism-1.12.2-1.4.9 (1).jar                | None                                     |
       | UCH   | vampirism_integrations | vampirism_integrations | VampirismIntegrations-1.12.2-1.0.0.jar        | None                                     |
       | UCH   | vanillafix             | 1.0.10-SNAPSHOT        | VanillaFix_1.0.10_99.jar                      | None                                     |
       | UCH   | wings                  | 1.1.2                  | wings-1.1.2-1.12.2.jar                        | None                                     |
       | UCH   | bauble_wings           | 1.0.0                  | wings-1.1.2-1.12.2.jar                        | None                                     |
       | UCH   | orelib                 | 3.5.1.3                | OreLib-1.12.2-3.5.1.3BETA.jar                 | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | UD    | mobends_wings          | 1.0.0                  | wings-1.1.2-1.12.2.jar                        | None                                     |
  Loaded coremods (and transformers): MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      CoreModBase (TCFastCraftingMod_2.6_mc1.12_1.12.2.jar)
                                        com.dazo66.fastcrafting.asm.MainTransformer
                                      VanillaFixLoadingPlugin (VanillaFix_1.0.10_99.jar)
                                        
                                      BringMeTheRings plugin (BringMeTheRings_0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      wings (wings-1.1.2-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      llibrary (llibrary-core-1.0.6-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      AppleCore (AppleCore_mc1.12.2_3.1.3.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      IvToolkit (IvToolkit_1.3.3_1.12 (1).jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin_1.7.4 (2).jar)
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13543 Compatibility Profile Context 0' Renderer: 'AMD Radeon (TM) R5 M330'
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore'
  Suspected Mods: The Twilight Forest (twilightforest)
  Launched Version: ForgeOptiFine 1.12.2
  LWJGL: 2.9.4
  OpenGL: AMD Radeon (TM) R5 M330 GL version 4.6.13543 Compatibility Profile Context 0, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: Русский (Россия)
  Profiler Position: N/A (disabled)
  CPU: 2x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

**Comment by bs2609** [comment]
Issue with one of the coremods you have installed, probably Optifine.
The version of Optifine you are using is outdated, so I'd try updating that first.
