### ISSUE TITLE
only one player can connect to the server at once.

### ISSUE THREAD

**Issue by mmahs** [TeamTwilight/twilightforest#688]
Forge version: 
Twilight Forest version: 1.12.2
Link to crash log: (There was no crash)

Steps to reproduce:
1. join server
2. get disconnected

What I expected to happen:
join the server properly
What happened instead:
"a fatal error has occurred, this connection is terminated"

**Comment by Andromander** [comment]
That doesn't really explain anything. Can you provide a log of when this occurs (via https://gist.github.com), as this could contain an error message with a stacktrace, along with a sequence of events.
