### ISSUE TITLE
Twilight forest mod crash when it's being loaded.

### ISSUE THREAD

**Issue by TheUnknownFlame12** [TeamTwilight/twilightforest#689]
Forge version: Forge 10.13.4.1614 for 1.7.10
Twilight Forest version: 2.3.7
Link to crash log: https://gist.github.com/TheUnknownFlame12/3b7d240877f85425fd423af5678b6559

Steps to reproduce:
1. When you start your forge 1.7.10.

What I expected to happen: Was to load and started properly.

What happened instead: It Crash every times it loads in the initialization mod phase 2 and when preinitialization is done it just crashes every time but when I removed the twilight forest mod it just works perfectly and loads flawlessly I don't know what I'm doing wrong.

**Comment by Tamaized** [comment]
1.7 is unsupported
