### ISSUE TITLE
Twilight Forest 3.9.851 crashes upon attempting to launch with Forge version 14.23.5.2807

### ISSUE THREAD

**Issue by ALPHANUMERIC1** [TeamTwilight/twilightforest#691]
Forge version: 14.23.5.2807
Twilight Forest version: (3.9.851)
Link to crash log: [https://gist.github.com/ALPHANUMERIC1/dd9692c3dab402d08858e1efcb5d531b](https://gist.github.com/ALPHANUMERIC1/dd9692c3dab402d08858e1efcb5d531b)

Steps to reproduce:
1. Attempt to launch the game

What I expected to happen: I expected to be able to launch the game

What happened instead: The game crashed

**Comment by Andromander** [comment]
Duplicate of #685. This is caused by JEID.

**Comment by ALPHANUMERIC1** [comment]
Thanks.
