### ISSUE TITLE
BOSS Buildings Lost Protection When I use SpongeForge

### ISSUE THREAD

**Issue by nice-winter** [TeamTwilight/twilightforest#695]
Forge version: 1.12.2-14.23.5.2768
Twilight Forest version: 1.12.2-3.8.689
SpongeForge: 1.12.2-2768-7.1.4
Link to crash log: (No crash)

BOSS Buildings Lost Protection When I use SpongeForge.
(My English is no so good, Sorry!)

Steps to reproduce:
1.Join the game, Then enter the twilightforest world
2.Not killing Naga, To find the Lich Tower(or any BOSS buildings) and broke it. You can see that they are not protected.
3.Now you can attack any BOSS.

What I expected to happen:
**Killed the BOSS to challenge the next BOSS.**
What happened instead:
**BOSS buildings are out of protection.**

**Comment by bs2609** [comment]
If you're having an issue with SpongeForge specifically, it's probably better to report it to their issue tracker [here](https://github.com/SpongePowered/SpongeForge/issues).

**Comment by nice-winter** [comment]
Okay, Thank you:)
But I'm not sure whether TwilightForest or SpongeForge has problems...
