### ISSUE TITLE
Just trying to set up a small modded server for me and my friends

### ISSUE THREAD

**Issue by CourtyShorty34** [TeamTwilight/twilightforest#696]
Forge version: 
Twilight Forest version: 1.12.2
Link to crash log: https://gist.github.com/CourtyShorty34/3917465a28a03adbe35c060170895401.js

Steps to reproduce:
1.  Im not sure what this means

What I expected to happen: in the server ive just added the mod and thought it would just run with everything

What happened instead: but opening the server it just comes up with red writing about somethings wrong with the mod or something like that

**Comment by Drullkus** [comment]
This is 100% not the crash. Can you please give me the server startup log as a gist?

**Comment by CourtyShorty34** [comment]
ill be 100% honest im not sure where that log is or what a startup log is, what i sent is all i have as it worries me because when the server is loading up it writes out in red, it hasn't actually crashed i just wanted to know if ive done something wrong

**Comment by Drullkus** [comment]
Nothing wrong at all. Those are two advancements erroring out because Thaumcraft or Immersive Engineering neither exist. You can ignore these because they are completely inconsequential and have no impact on the game at all.

**Comment by CourtyShorty34** [comment]
Okay thank you very much
