### ISSUE TITLE
Block model error

### ISSUE THREAD

**Issue by Zarpyk** [TeamTwilight/twilightforest#697]
Forge version: forge1.12.2-14.23.5.2779
Twilight Forest version: 1.12.2-3.8.689

Steps to reproduce:
1. Place the block
![2019-01-20_13 50 38](https://user-images.githubusercontent.com/30746531/51867676-59a54200-234c-11e9-8dff-44108b914e62.png)
![2019-01-20_13 51 48](https://user-images.githubusercontent.com/30746531/51867677-5a3dd880-234c-11e9-80bb-b9edbe24a275.png)

**Comment by Killer-Demon** [comment]
This was fixed at some point and looks to be working fine now.
