### ISSUE TITLE
New Decorative stone for Twilight Forest - Malahit

### ISSUE THREAD

**Issue by mrJyggalag** [TeamTwilight/twilightforest#703]
I suggest adding a new decorative stone for Twilight Forest (like diorite/granite from Overworld) - [malachite](https://en.wikipedia.org/wiki/Malachite)
![2019-02-01_20_58_28](https://user-images.githubusercontent.com/25662632/52469373-50ae3f00-2b9c-11e9-9f7b-fd411ce8f7da.png)
From left to right: malachite, malachite brick, smooth malachite, and malachite pillar.

Link to download .rar with textures - [link](https://drive.google.com/open?id=1AKbA5H9HFPqB1upmdFzy_lJx0piYTxUb)

**Comment by Killer-Demon** [comment]
Those are some pretty and snazzy textures! Unfortunately, we're not looking to add any stone variants to the world. We actually turned down the rate at which the three vanilla stone variants generate at some point.
