### ISSUE TITLE
Incorrect Breaking Sounds

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#704]
Twilight Forest version: 3.9.851

Currently tested on the new Twilight Wood blocks, there are a few blocks that make the sound of Stone rather than Wood:
* Trapdoors
* Doors

Author's Note: I mean, it probably makes sense for the Minewood Door and Trapdoor since it looks like a vault door.

**Comment by bs2609** [comment]
Was fixed in 809130dcb8f08cfb2dbb268f53aeb17fefc3ac7b.

**Comment by Andromander** [comment]
Aye, appears to be so.
