### ISSUE TITLE
Client Crashed during forge initialization

### ISSUE THREAD

**Issue by DragonHalo99** [TeamTwilight/twilightforest#706]
Forge version: 14.23.5.2808
Twilight Forest version: 3.9.851
Link to crash log: https://gist.github.com/DragonHalo99/b7bb1e32237b3b6bc4fc04cce5e6897a
Steps to reproduce:
1. 
Start Minecraft
What I expected to happen:
minecraft runs
What happened instead:
Crashed

**Comment by 3TUSK** [comment]
Try remove JustEnoughID

**Comment by DragonHalo99** [comment]
ok

**Comment by DragonHalo99** [comment]
can't run the mod pack without justenoughid like i thought. I will switch back to the release version. I was mainly posting the crash log incase it would help with the dev build.

**Comment by Andromander** [comment]
It's more to do with JEID trying to use Mixin on a method that doesn't exist here anymore. It is up to them to fix it.

**Comment by DragonHalo99** [comment]
oh should I report that to JEID?

**Comment by Tamaized** [comment]
duplicate of #685
