### ISSUE TITLE
Advancement not recognizing defeat of Phantoms Knights

### ISSUE THREAD

**Issue by SolSavvy** [TeamTwilight/twilightforest#707]
Forge version: 14.23.5.2814
Twilight Forest version: 3.9.851
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce: defeat the Phantom Knights
1. 

What I expected to happen: I expected to complete the advancement to move onto the Ur-Ghast, Clearly I have the trophy on my hotbar to prove it

What happened instead: No advancement
![2019-02-24_19 35 05](https://user-images.githubusercontent.com/27328200/53307953-5b8af400-386b-11e9-8d19-ff2be0c24733.png)

**Comment by bs2609** [comment]
Known issue, already fixed in dev (89fae3c97ea56cf57551f7ef00bb71252e89cab4).

**Comment by SolSavvy** [comment]
ok, but how do i fix it in my world?

**Comment by SolSavvy** [comment]
There hasnt been a new version of Twilight Forest since Jan 12th 2019, so this will be fixed in next version?

**Comment by bs2609** [comment]
Yes, this will be fixed in the next alpha version released.
