### ISSUE TITLE
1.12.2 : How to change biomes ID ?

### ISSUE THREAD

**Issue by ExDomino** [TeamTwilight/twilightforest#709]
Hello,

I would like to know how to change the ID of the biomes added by your mod please.
I'm playing on 1.12.2. I'm using the version 3.9.851 of your mod.

Thank you in advance!

**Comment by williewillus** [comment]
integer biome ID's are automatically-assigned by forge on startup and cannot be changed manually

string ID's will not be changed since they will break world compat

**Comment by ExDomino** [comment]
Thank for you reply, but I want to ask you something.
Even if it's not your fault, do you know a way to fix the bug when Twilight Glacier is generated in the overworld with the mod Biome Bundle ? I mean, without lost my world.

**Comment by Drullkus** [comment]
Can you show me a screenshot of this glacier in the overworld? Maybe biome bundle has their own glacier biome

**Comment by ExDomino** [comment]
Hello, sorry for my late reply...
This is the screenshot you requested : https://image.noelshack.com/fichiers/2019/11/2/1552345617-2019-03-11-19-02-59.png

As you can see, the map generation is correct, the biome is generated as a river by Biome Bundle, but after, as Minecraft thinks the river is a Twilight Glacier, water slowly become ice and it snows instead of raining. There are also your own version of squids (the red ones) that spawn in this area.

Spawning of red squids is not an issue. the issue is the ice and the snow inside a temperate place.
Biomes nearby are not cold, they are either temperate or hot, so ice at this place is weird.

If you're able to fix that bug, can you also make a fix for maps that are already generated? For example, a kind of function that replace all "Twilight Glacier" biomes in overworld by the "River" biome when a chunk is generated or loaded. I'm not sure if this is possible though, I never made a mod myself. Or a function that prevent water to become ice in "Twilight Glacier" biomes in overworld? And if so, that turns already existing ice into water as well.

Thank you in advance!
