### ISSUE TITLE
Rooms in Aurora Palace generate improperly

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#71]
Forge Version: 13.20.0.2315
Twilight Forest Version: 2.4.0.27

Rooms where wooden planks and slabs generate in an abnormal fashion
![2017-06-20_19 08 18](https://user-images.githubusercontent.com/29526717/27328186-94c3a1b4-55f4-11e7-8942-e4f3ca91b664.png)
![2017-06-20_19 10 59](https://user-images.githubusercontent.com/29526717/27328201-9fe3c6f0-55f4-11e7-8d68-171e01ed19b3.png)

**Comment by Andromander** [comment]
Issue still exists in version 1.12.x. Several other issues exist in the Aurora Palace exist too, such as

- Entry to the Aurora Palace is missing a roof piece, only appearing flat
- Due to the way the entrance generates, sometimes a stairwell does not generate
- Also, the entrance may spawn alongside a tower, blocking off the corridor to the main tower or an access to the entrance, or both
- Staircases are either rotated improperly, or do not generate, only sitting along the bottom of the room or are a wooden pillar to the next chamber

**Comment by meliornox** [comment]
I've also found places where towers will overlap slightly on the top and bottom, spawning excess aurora blocks inside rooms

**Comment by Andromander** [comment]
I'm not too sure if I should close this issue now, or when the Aurora Palace is revamped with the other structures.

**Comment by meliornox** [comment]
It's still happening with the latest official release, 1.12.2-3.5.263-universal.  If the structure is going to be replaced entirely before the generation is fixed though it might be better just to close it.

**Comment by Drullkus** [comment]
Correct, Structure will be replaced
