### ISSUE TITLE
Iron chest issue

### ISSUE THREAD

**Issue by EternalOne11** [TeamTwilight/twilightforest#710]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1.  hit a shuker box  or chest from the iron chest mod

What I expected to happen:
Expected the shulker box to drop
What happened instead:
the shulker box disappears and the items don't drop if you use the ball and chain on it made from knightly metal.

Discord username: EternalOne nickname Eternal

**Comment by Andromander** [comment]
Similar issue to #659. I suspect this might be an issue with Iron Chest, but that is yet to be seen with other containers with similar behaviour to a Shulker Box.
