### ISSUE TITLE
Door Models Missing

### ISSUE THREAD

**Issue by RyanCR03** [TeamTwilight/twilightforest#711]
Forge version: 
Twilight Forest version: (3.9.851)
Link to crash log: (no crash)

Steps to reproduce:
1. get any twilight forest wood
2. make them into planks
3. craft doors

What I expected to happen: to see a normal door model

What happened instead: door model was pink and black like the model was missing

**Comment by bs2609** [comment]
This is a known issue, it's an alpha build and not everything is finished for release yet.

**Comment by ilvrak** [comment]
in 3.9.888 inworld models present, with textures
only inventory item textures is missing

**Comment by RyanCR03** [comment]
im pretty sure that was a long time ago

**Comment by NielsPilgaard** [comment]
The models now work, but the texture is still broken (purple/black)
`twilightforest-1.12.2-3.9.984-universal`

**Comment by yancypro** [comment]
I am still having this issue. What can I provide to help fix this?
![image](https://user-images.githubusercontent.com/65453692/82121406-b6ec1f00-975a-11ea-917a-7ea058f34219.png)

I am using Twilight Forest 3.10.1013 and Forge 14.23.5.2847 for Minecraft 1.12.2

**Comment by Tamaized** [comment]
It's not broken, they just don't exist period. It's unfinished content.

This won't be finished in 1.12

**Comment by Alyaqdhans** [comment]
> It's not broken, they just don't exist period. It's unfinished content.
> 
> This won't be finished in 1.12

Please don't say there is no more updates for 1.12 because I'm waiting for long time for the final boss in 1.12.2 and bugs like this to be fixed :/

**Comment by SteveHeist** [comment]
Dumb question - but is there an assigned file to the item (to give it a texture) or no?

**Comment by DehzitO** [comment]
Have any solution for this problem?

**Comment by Tamaized** [comment]
Wait for us to actually make the models, which will be in the 1.16 initial port.

**Comment by Alyaqdhans** [comment]
You won't complete it in 1.12.2?

**Comment by Breadabix** [comment]
Im seeing that doors might not get a texture in 1.12? Even if 1.12 isnt getting major updates this seems like an easy thing to implement when the door textures will already exist for 1.16.

**Comment by Tamaized** [comment]
It's not a texture issue it's an entire model that hasn't been created. We weren't copying vanillas flat texture style at the time.

**Comment by Breadabix** [comment]
damn, so that means 1.12 wont be getting them.

**Comment by aghzafen** [comment]
Is there an update on this issue? As of release for the version 1.16.5 the models are still missing.

**Comment by Tamaized** [comment]
Our artist is burnt out, give them time please.

**Comment by yancypro** [comment]
I really appreciate all the work done on Twilight Forest. I played many
long hours in 1.12.2 but had to start a new world when 1.16.5 came out
because of all of the main program upgrades. When I realized that the mod
hadn't updated, I was very sad. You made me very happy with the upgrade to
1.16.5, so now I can kill the Lich King and all of the other minions in
Twilight Forest! YAY!!

**Comment by Andromander** [comment]
Going to delegate this to #1035 as it lists some other missing textures.

**Comment by xemnes** [comment]
just to let you know, i have fixed this for 1.12. the pull request is here if you wish to build it yourself should it never gets merged and updated on curseforge https://github.com/TeamTwilight/twilightforest/pull/1225
