### ISSUE TITLE
Client crash when opening an ME system. java.lang.ClassCastException: net.minecraft.item.ItemAir

### ISSUE THREAD

**Issue by ProsperCraft** [TeamTwilight/twilightforest#717]
Forge version: 2815
Twilight Forest version: twilightforest-1.12.2-3.9.888-universal

https://gist.github.com/ProsperCraft/ba7d06e526b701df7d716784aa20f7ce

This is difficult to test, as it happens in a client/server environment and very infrequently, can play for hours without it happening, and the world is on a multiplayer server with many other players playing - https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

From Discord - 
[3:21 PM] quadraxis: @Goshen if you can, try build 893 and see if that fixes the crash
[3:21 PM] quadraxis: can get it here: http://builds.steamnsteel.info/browse/TF-ONETWELVE-893/artifact

**Comment by Tamaized** [comment]
Fixed in dev (bbadbe36066900e0cb33bcb5602afc20d371bc2a)
