### ISSUE TITLE
Using Ice Crystal attack Goblin Knight (upper) of Twilight Forest caused crash

### ISSUE THREAD

**Issue by FworksHN** [TeamTwilight/twilightforest#720]
Forge version: 14.23.5.2768

Twilight Forest version: (this is the build number):3.8.689
Link to crash log: 

Minecraft log:https://paste.ee/p/fMlDc
crash log:https://gist.github.com/FworksHN/f33bc6a86a0161874ce15db77c1d7112

Ice Crystal is a tool from [https://github.com/BobMowzie/MowziesMobs](https://github.com/BobMowzie/MowziesMobs) mod that can be used to freeze mobs and do damage constantly to them.

Steps to reproduce:
1. I only left these mods to test:
journeymap-1.12.2-5.5.2
llibrary-1.7.15-1.12.2
mowziesmobs-1.5.3
OptiFine_1.12.2_HD_U_E2
twilightforest-1.12.2-3.8.689-universal
2. Summon a goblin knight in creative mode
3. Use Ice Crystal to “blow” the knight

What I expected to happen:
Both upper and lower part freeze (with specified texture change from MM mod) and take 
constant damage as using it on other mobs

What happened instead:
Game freeze and crashed.

**Comment by FworksHN** [comment]
This might be the point:
> Caused by: java.lang.ClassCastException: com.bobmowzie.mowziesmobs.server.entity.frostmaw.EntityFrozenController cannot be cast to net.minecraft.entity.EntityLiving
	at twilightforest.entity.EntityTFGoblinKnightUpper.func_70098_U(EntityTFGoblinKnightUpper.java:193)

This also happened on the server I'm playing in:
https://github.com/BobMowzie/MowziesMobs/issues/140

**Comment by 3TUSK** [comment]
https://github.com/TeamTwilight/twilightforest/blob/2be1b61e18fcea330154d544850122bae94e7b9c/src/main/java/twilightforest/entity/EntityTFGoblinKnightUpper.java#L189-L195

Wrong assumption on actual type of entity being ridden?
