### ISSUE TITLE
[1.12.2] King Spider Initial Spawn no isRemote Check

### ISSUE THREAD

**Issue by jredfox** [TeamTwilight/twilightforest#721]
**Forge version**: 1.12.2-forge1.12.2-14.23.5.2814
**Twilight Forest version**: twilightforest-1.12.2-3.8.689-universal
**Issue**: if you create a king spider and specify on initial spawn so any entity get's it's equipment for client side rendering it spawns in on client side into the client's world the other entity skeletons.

**Steps to reproduce**:
install something that renderes king spider on client side(silkspawners mod forge edition)
create superflat creative world
/tp 0 4 0
place the spawner block notice on 0 0 0 the skeletons are there spawned in

**What I expected to happen**:
no client side entities to render that don't exist on server side

**What happened instead**:
It rendered the entity due to your hard coded spawning code on king spider

**Comment by Tamaized** [comment]
what hard coded spawning, link it please,

**Comment by jredfox** [comment]
the code specify on either side to spawn in a new druid skeleton into the world even on client side without a check if !world.isRemote this was already specified inside of my initial post

**Comment by Tamaized** [comment]
link it

**Comment by jredfox** [comment]
shouldn't have to link it as using github would sometimes result in improper code from the twilight forest version that is the dev's and or dev helper's jobs
https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/entity/EntityTFKingSpider.java#L46

**Comment by Tamaized** [comment]
See: EntitySpider#onInitialSpawn

**Comment by jredfox** [comment]
hmmm it's my side then I just don't know how to fix it. How do you remove the entity from the world without setting it dead and stuff on passengers?

**Comment by Tamaized** [comment]
This aint a general modder help desk, go to the forge forums or a discord meant for this~

**Comment by jredfox** [comment]
Wasn't asking for help when two issues become related it's very difficult not to discuss which side it is. I will figure it out on my side thanks for the pointer

**Comment by Kuktar** [comment]
Damn. Shots fired lol.

Christopher Kuhn,
Semper Fidelis

**Comment by bs2609** [comment]
The issue is on the spawner side: https://bugs.mojang.com/browse/MC-114019

**Comment by Kuktar** [comment]
Nice work Ben. Of all 300 mods I play with since 1.7.10 twilight forest is
the best :)

Christopher Kuhn,
Semper Fidelis
