### ISSUE TITLE
I cant see barely anything at all!

### ISSUE THREAD

**Issue by AnnaTheKitty** [TeamTwilight/twilightforest#722]
Forge version: 1.12.2 - 14.23.5.2768
Twilight Forest version: 1.12.2 - 3.8.689

Steps to reproduce:
1. [Green Particles] Just walk up to either a boss or a random place in the world and random green particles starts to appear out of the bloom.
2. [Random Black and Red Particles] Happens randomly when you go into a different biome(AKA you are basically screwed in the end)

What I expected to happen:  No particles covering my screen and couldn't see barely anything

What happened instead: A ton of particles covering my screen and couldn't see barely anything

Pictures/Screenshots: 
![2019-03-28_18 54 29](https://user-images.githubusercontent.com/48998087/55198373-1e789100-518c-11e9-8467-c2a3b8c254f7.png)
![2019-03-28_18 54 42](https://user-images.githubusercontent.com/48998087/55198374-1e789100-518c-11e9-95ed-f68ffce638ec.png)
![2019-03-28_18 54 49](https://user-images.githubusercontent.com/48998087/55198375-1e789100-518c-11e9-8b6d-4fcf1809c303.png)
![2019-03-28_18 54 58](https://user-images.githubusercontent.com/48998087/55198376-1e789100-518c-11e9-80f4-94261468efb7.png)
![2019-03-28_18 55 21](https://user-images.githubusercontent.com/48998087/55198377-1e789100-518c-11e9-9a7a-bea61b166631.png)
![2019-03-28_18 56 04](https://user-images.githubusercontent.com/48998087/55198378-1e789100-518c-11e9-825c-59319a8a7a5c.png)

**Comment by Andromander** [comment]
Check your Advancements. Have you unlocked any of those areas yet?

**Comment by AnnaTheKitty** [comment]
What do you mean by that?

**Comment by Andromander** [comment]
[This page](http://benimatic.com/tfwiki/index.php?title=Progression) explains it all, but in short, Biomes and Structures are locked behind a Progression barrier. You have to go through each boss in order, as seen in Advancements, before you can enter the next area. You can disable the barrier with `/gamerule tfEnforcedProgression false`.

**Comment by AnnaTheKitty** [comment]
Oh okay that makes a bit more sense, also I tried the command you gave me and I still get the particles.

**Comment by Andromander** [comment]
You may need to leave the Twilight Forest/the save file then enter back in if you use the command (#627). It's just a visual bug.

**Comment by AnnaTheKitty** [comment]
Okay, also while fighting some of the monsters, the giant Naga escaped from their building and the game won't let me hurt it, is that supposed to happen or...?
![2019-03-28_19 24 18](https://user-images.githubusercontent.com/48998087/55199112-3dc4ed80-518f-11e9-8b1d-acebef4e3cd1.png)

**Comment by Andromander** [comment]
It's intended. The Naga is supposed to return to the Courtyard if it ends up outside of the boundaries, but at the same time it becomes invulnerable until it is back inside.

**Comment by Tamaized** [comment]
Going to assume this is resolved.
