### ISSUE TITLE
Into the twilight world crazy refresh error

### ISSUE THREAD

**Issue by ReonAqest** [TeamTwilight/twilightforest#723]
Forge version:  MC 1.12.2 - 3.8.689
Twilight Forest version: (this is the build number)
Link to crash log: https://paste.ubuntu.com/p/M4Fk9y6S6B/

Steps to reproduce:
1. An error occurs when entering the world on the spigot + forge server and entering the twilight world
Server address

https://github.com/CatServer/CatServer/
What I expected to happen:

What happened instead:

**Comment by Tamaized** [comment]
Closing as this is quite old and theres no reports of this on the 1.18 builds
