### ISSUE TITLE
Twilight Forest naga courtyard/swamp lilypad determinism

### ISSUE THREAD

**Issue by noobanidus** [TeamTwilight/twilightforest#724]
As requested.

**Comment by 3TUSK** [comment]
The lilypad one should be fixed by https://github.com/TeamTwilight/twilightforest/commit/70e43ff50f2a64ec86cbe44ab6786d7092c93fe0

**Comment by noobanidus** [comment]
I just remembered someone said to open an issue and when I looked there weren't any open. IF it's already been dealt with then someone please close! Trying to keep track of a lot of things at the minute and stuff is getting past me :(

**Comment by 3TUSK** [comment]
Well. The other half of the issue hasn't been fixed yet AFAIK... so this one should keep open. Anyhow it's better to track everything :p

**Comment by Drullkus** [comment]
Is this a problem anymore? Gonna close, poke in here if there's still a problem
