### ISSUE TITLE
[Feature Request]  split config for compatibility in to all three not just one toggle.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamTwilight/twilightforest#726]
Currently, in my modpack i have Immersive engineering, but not tinkers orThaumcraft, so I get red stacktraces in console because it tries to load those two but is unable.

Please split it so there are three config options, one for each compatibility.

**Comment by Drullkus** [comment]
Before we continue with resolving this issue, can you please post those stacktraces?

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/7d06cd7538eaf1175e1c340f12f59d63

**Comment by Tamaized** [comment]
Pretty sure we can't control advancement loading conditionally

**Comment by ProsperCraft** [comment]
I am looking for a config that looks like this-

compat {
        B:actuallyadditions=false
        B:albedo=false
        B:attaineddrops2=false
        B:baubles=true
        B:betterwithmods=false
        B:bloodmagic=false
        B:botania=false
        B:chisel=true
        B:chiselsandbits=false
        B:cofhcore=true
        B:crafttweaker=true
        B:denseores=false
        B:enderio=false
        B:extrautils2=false
        B:forestry=false
        B:foundry=false
        B:harvestcraft=false
        B:ic2=true
        B:inspirations=false
        B:mysticalagriculture=false
        B:opencomputers=false
        B:railcraft=true
        B:tconstruct=false
        B:thaumcraft=false
        B:theoneprobe=true
        B:thermalfoundation=false
        B:waila=false

Not this-

    # Should TF Compatibility load? Turn off if TF's Compatibility is causing crashes or if not desired.
    B:doCompat=true

**Comment by Tamaized** [comment]
Sure, but it still won't get rid of the errors in the log.

**Comment by Drullkus** [comment]
^

Adding config still won't fix the advancements failing due to nonexistence of mods, because advancements are much further out of our control. They exist as json files without conditional loading.

If it bothers so much, use CraftTweaker to remove the advancements.

**Comment by ProsperCraft** [comment]
I think the conversation went down a different path then I had hoped, I asked for a feature request to split out the compatibility, is that not going to be considered?

**Comment by Drullkus** [comment]
Even if we did that, that won't remove the console stacktraces.

**Comment by ProsperCraft** [comment]
Which is fine.
