### ISSUE TITLE
Totemic Totem Base interaction with Twilight Forest Maze Map causes a crash.

### ISSUE THREAD

**Issue by Dutchs** [TeamTwilight/twilightforest#728]
Forge version: 14.23.5.2815
Twilight Forest version: 3.8.689
Link to crash log: https://pastebin.com/npgykgeQ

Steps to reproduce:
1. Place Totemic Totem Base
2. Open/Select Maze Map

Totemic related issue: https://github.com/TeamTotemic/Totemic/issues/104

**Comment by Tamaized** [comment]
`at pokefenn.totemic.block.totem.BlockTotemBase.func_180659_g(BlockTotemBase.java:157)` it's on their end

**Comment by bs2609** [comment]
Yeah, this is a Totemic issue:
https://github.com/TeamTotemic/Totemic/blob/9af3a19135b0cbe29c4ae6f2b6312319a63fd8d4/src/main/java/pokefenn/totemic/block/totem/BlockTotemBase.java#L157
