### ISSUE TITLE
Charms of keeping don't keep special Betweenlands gear

### ISSUE THREAD

**Issue by MorzanTLD** [TeamTwilight/twilightforest#730]
Forge version:  14.23.5.2835
Twilight Forest version: 1.12.2-3.8.689

Betweenlands version: 3.4.6

Steps to reproduce:
1. Equip Betweenlands amulet
2. Obtain charm of keeping 3
3. Die

What I expected to happen:
The amulet is still equipped upon respawn or in my inventory

What happened instead:
The amulet is dropped at the location of death

**Comment by Tamaized** [comment]
Yeah, it's quite hard for us to special case for every single mod out there. Maybe we can do some IMC thing idk.

**Comment by Tamaized** [comment]
Seeing how Betweenlands is 1.12 and that we no longer support 1.12, I'm going to close this.
