### ISSUE TITLE
Familiar Fauna mobs not spawning 

### ISSUE THREAD

**Issue by fivelol** [TeamTwilight/twilightforest#731]
Forge version: 14.23.5.2815
Twilight Forest version: 3.8.689 (the latest build marked release on curseforge)
Link to crash log: n/a

Steps to reproduce:
Familiar fauna configs allow you to set the spawn of mobs to whichever biome you like, by default, some of these entities should be spawning in the twilight forest, I've been told by forstride (the author of the mod) that the mobs use normal forge mob spawning and am reposting my issue from their repo to here. 
Pixies, turkeys and butterflies (and whatever other mobs are supposed to) are not spawning in the twilight forest, they should according to the wiki and my config, I've searched the designated biomes for all three of these.
Additionally, I added deer to most of twilight's forest biomes (using the config) and disabled the twilight forest deer (using bad mobs mod) however familiar fauna deer are not spawning.

This can be replicated with only forge, familiar fauna and twilight forest and the default config settings for both mods.

What I expected to happen:
Familiar fauna mobs spawn in the twilight forest (as they should by default).

What happened instead:
They didn't spawn.

**Comment by bs2609** [comment]
> I've been told by forstride (the author of the mod) that the mobs use normal forge mob spawning and am reposting my issue from their repo to here.

Can you link the original issue please?

**Comment by fivelol** [comment]
The response was on their discord server but here's the link to the issue
https://github.com/Glitchfiend/FamiliarFauna/issues/34

The discord link can be found here
https://minecraft.curseforge.com/projects/familiar-fauna

**Comment by bs2609** [comment]
I don't think this is an issue on our side.

The mod is registering its entities in pre-init, it should move to registering them in the appropriate registry event. Attempting to modify spawns in pre-init isn't going to work for any modded biomes as they won't have been registered then.

**Comment by Andromander** [comment]
I believe that has been proven that the issue was on their side. Can't verify if it is fixed as the issue no longer exists; repo is Archived.
