### ISSUE TITLE
Server does not start with twilight forest

### ISSUE THREAD

**Issue by Feeston** [TeamTwilight/twilightforest#735]
Server doesn't start with twilght forest
I tried different versions of the mod but none of them worked
I tried to launch the server with only twilight forest but still crashed

Pictures of the crashlog:
![crash1](https://user-images.githubusercontent.com/50032754/56837899-cca75180-6884-11e9-8b6d-f8f76d6d21aa.PNG)
![crash2](https://user-images.githubusercontent.com/50032754/56837900-cdd87e80-6884-11e9-9c36-6d1310d43a36.PNG)

**Comment by Andromander** [comment]
Please use the issue template that was provided when the issue was created. We need the version numbers for Twilight Forest and Forge.

**Comment by Feeston** [comment]
> Please use the issue template that was provided when the issue was created. We need the version numbers for Twilight Forest and Forge.

Forge version is 14.23.5.2768 and I tried multiple versions of twilight forest but none of them worked

**Comment by bs2609** [comment]
Please upload the full crash report file (from the location mentioned at `This crash report has been saved to:`) to [gist](https://gist.github.com/) and link it here.

**Comment by Feeston** [comment]
> Please upload the full crash report file (from the location mentioned at `This crash report has been saved to:`) to [gist](https://gist.github.com/) and link it here.

https://gist.github.com/Feeston/dfb82cf1f254030b7d55ea85145c15d0

**Comment by Hubry** [comment]
```
| UCH | forge | 14.23.3.2655 | minecraft_server.jar | e3c3d50c7c986df74c645c0ac54639741c90a557
```
You are using 2655, not 2768.

**Comment by Feeston** [comment]
> ```
> | UCH | forge | 14.23.3.2655 | minecraft_server.jar | e3c3d50c7c986df74c645c0ac54639741c90a557
> ```
> You are using 2655, not 2768.

So updating forge should solve the issue?

**Comment by bs2609** [comment]
> So updating forge should solve the issue?

Yes, updating Forge should solve this issue.

Feel free to reopen it with a new crash report if it does not.
