### ISSUE TITLE
King Spider 1/100 Have Skeleton instead of Skeleton Druid

### ISSUE THREAD

**Issue by NullSector76** [TeamTwilight/twilightforest#737]
According to your code and also verified this in game your king spider doesn't remove passengers before adding  your druid. Since it's not forced on the entity the druid doesn't spawn in at all and all that remains is a regular skeleton. Not sure if this is intended but, It seems like a bug to me.

what to do instead. Remove passengers before creating your druid and placing it on your king spider

KingSpider#onInitialSpawn

**Comment by Drullkus** [comment]
Oh yeah I'll probably do something evil with this

**Comment by Tamaized** [comment]
Worth noting: https://bugs.mojang.com/browse/MC-114019 (Since i know what you're on about)

But ya, this sounds like a feature to me :^)

**Comment by NullSector76** [comment]
has nothing to do with mob spawners. Research before you comment. This can occur regardless of how the entity is created on server side.

**Comment by Tamaized** [comment]
I did research and I know how you discovered this. I'm just throwing it out there because I know exactly what you're trying to do in your own mod.

**Comment by NullSector76** [comment]
Again this has nothing to do with mob spawners you can literally see them as regular skeletons inside of the world
