### ISSUE TITLE
Multiple bosses spawning in a single area.

### ISSUE THREAD

**Issue by zach2045** [TeamTwilight/twilightforest#739]
Forge version: 14.23.5.2781
Twilight Forest version: 3.8.689
Link to crash log: This has not yet caused the server to crash.

Steps to reproduce:
1. Simply starting the server with the mod installed seems to cause this issue. Deleting and recreating the dimension file also did not fix this.

What I expected to happen: The bosses to spawn normally and only one at a time in each given area.

What happened instead: All bosses seem to spawn in multiples. For example in a single stone maze it spawned 6 separate Naga bosses with 6 different health bars. This causes players to either get timed out or drop to 1-2 fps until they leave that area/dimension. We are running the modpack Enigmatica 2 Expert on this server so I am not sure if one of the other mods is messing with the spawns or not. It is also worth mentioning that the spawn rates did get altered to be higher once installing Sponge onto the server. None of our players had reached Twilight Forest yet so I wasn't able to see if that was when the change occurred with the boss spawning but in thinking back I thought one player had gone through the Forest mod bosses near the start of the server which would have been before we installed sponge forge and I never heard of this issue at that time. https://gyazo.com/1a81a986206d12a472c8a88c6d38f348

**Comment by bs2609** [comment]
Most likely this Sponge issue: https://github.com/SpongePowered/SpongeForge/issues/2682

**Comment by zach2045** [comment]
Alright it looks like we are not quite up to date with our version of Sponge Forge. I will try updating it now and see if that fixes it. Thank you for the help!
