### ISSUE TITLE
1.12.2 - Server - ConcurrentModificationException

### ISSUE THREAD

**Issue by LotuxPunk** [TeamTwilight/twilightforest#740]
Forge version: 2836 (1.12.2)
Twilight Forest version: twilightforest-1.12.2-3.8.689-universal.jar
Link to crash log: https://pastebin.com/VH9VUFsG

Steps to reproduce:
1. Generating terrain (Twilight) on my server

What I expected to happen:
* No server crash

What happened instead:
* Server crash

**Comment by Andromander** [comment]
The stacktrace seems to mention the Tardis mod. Has this been reported to them, too?
Also, just in case there is a change in later versions that may fix this, can you try Twilight Forest version 3.9.888?

**Comment by noobanidus** [comment]
`world.func_175690_a 1.12` is `setTileEntity`, which is what causes the concurrency issue. I'm pretty sure the issue has to do with the Tardis mod, as the initial call to it is from `func_72939_s` which is `world.updateEntities`.

So, it's already iterating over the entity list to update them, meanwhile one of those tile entities causes chunk loading which tries to create & then add a new entity to the list that is currently being iterated on. Hence, concurrency.

Ruins is the one that's actually doing the chunk loading, though (`onEntityEnteringChunk` is calling `wold.getChunk`), so it's potentially not entirely Tardis mod's fault.

I'd investigate to see if it still happens with just Ruins installed, or just Tardis installed, or neither of them installed.

**Comment by bs2609** [comment]
This does not appear to be an issue with TF, but I will look into it regardless as it may also not be a simple mod issue.

**Comment by LotuxPunk** [comment]
Hey !
Apparently, even with the beta build 3.9.888, CME still happen.
Do you want I transfer this issue to Tardis Mod ?

**Comment by LotuxPunk** [comment]
https://pastebin.com/Aszy2Ux9

**Comment by LotuxPunk** [comment]
Apparently, update to beta version fix this issue
