### ISSUE TITLE
Crash with OpenJ9 Hotspot

### ISSUE THREAD

**Issue by BugmanBugman** [TeamTwilight/twilightforest#743]
Forge version:  14.23.5.2838
Twilight Forest version: 3.9.888
Link to crash log: https://paste.dimdev.org/aniwetuset.mccrash

Steps to reproduce:
1. have openj9 as your javaw.exe
2. start minecraft

What I expected to happen: the game to load up

What happened instead: crashed

**Comment by Andromander** [comment]
See #685, this is not an issue with Twilight Forest.
