### ISSUE TITLE
Multiplayer Server Boss Progression Issue (Fairly Annoying!)

### ISSUE THREAD

**Issue by jwrtn** [TeamTwilight/twilightforest#745]
Forge version: 2831 1.12.2
Twilight Forest version: (this is the build number) 1.12.2-3.8.689
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline) N/A

Steps to reproduce:
1. Host a server of any kind (in my case SkyFactory 4), and if any player besides you gets the killing blow on any boss, you don't get the progression for it, even if you dealt damage to the boss. Example: You and your friend are fighting the Naga, you get the Naga to 10hp, then your friend gets the kill, and you're unable to fight the Twilight Lich because you never got the progression for the naga.

What I expected to happen: I expected to get progression for participating in killing a boss on a server with friends

What happened instead: I'm required to find a completely separate boss and kill it to get progression, which is wildly frustrating even without SkyFactory 4.

**Comment by bs2609** [comment]
Boss trophies (and a couple of other boss drops) also count towards the advancement for this reason.

**Comment by jwrtn** [comment]
> Boss trophies (and a couple of other boss drops) also count towards the advancement for this reason.

Regardless, if you participated in killing a boss, you should get the progression and/or required items, such as the Hydra Trophy, from them

**Comment by Tamaized** [comment]
Killing a boss gives all players in the area the advancement trigger, so this can be closed.
