### ISSUE TITLE
Crash when trying to start DoIAmCake twitch modpack.

### ISSUE THREAD

**Issue by RadioactiveBoyyo** [TeamTwilight/twilightforest#746]
Forge version: I don't know
Twilight Forest version: (this is the build number) I don't know
Link to crash log: (please use a paste site such as [gist]
https://gist.githubusercontent.com/RadioactiveBoyyo/3b3c9fa6de84d4c0e88487e531ceb9c5/raw/3738d62d2bd6629ff4b066b685dc437d7e57df78/crash%2520report

(https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. ??

What I expected to happen: Minecraft starting so I can play on the server

What happened instead: The game crashed

**Comment by Tamaized** [comment]
This issue tracker isn't meant for the modpack
