### ISSUE TITLE
[Suggestion] Config Option to lock portal use behind a specified Twilight achievement

### ISSUE THREAD

**Issue by Dragnier** [TeamTwilight/twilightforest#747]
For modpack use when spawning in the Twilight on world/server join is enabled, this would be useful to enforce progression. It would make it so newly spawned players could not immediately bypass Twilight by simply using someone else's portal.

Further, the ability to at least prevent a portal from forming on world gen spawn would be a decent temporary fix as one can make the portal key object one of the later trophies or deny portals entirely in favor of another mod like Dimensional Edibles.

Additionally, I tried setting the destination dimension from 0 to 7 just to see what would happen... things get **_very_** weird...

**Comment by GizmoTheMoonPig** [comment]
didnt notice this was open still. 
In 1.17 we added a config option to lock portals behind a certain advancement. Portals can't be opened unless the player in question has this advancement, and portals that are already formed can't teleport a player without the advancement. There's no advancement assigned by default, but if you provide a valid resourcelocation for the advancement then the system will work.
Portal forming on world spawn also has a config option, so feel free to use that as needed. Thank you for the suggestion!
