### ISSUE TITLE
Curse of vanishing shouldn't be applicable to Phantom equipment

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#748]
![Phantom Plate. Is never lost on death. Enchantments: Curse of Vanishing.](https://cdn.discordapp.com/attachments/343501360517611531/588375333368233995/2019-06-12_20.58.35.png)

**Comment by bs2609** [comment]
Already a thing, as far as I can see:
https://github.com/TeamTwilight/twilightforest/blob/6e85c5923dca2d15b58fa04915456895ba6b9f4f/src/main/java/twilightforest/item/ItemTFPhantomArmor.java#L54-L57

Do note that this does not apply in the specific case of applying a book with an anvil in creative mode only, as vanilla specifically permits that. However, I would not consider that alone to be an issue with the mod.

Is this reproducible under any other circumstances?

**Comment by Drullkus** [comment]
Ah, good one. Looking at the screenshot, it looks the player who posted this screenshot was in creative mode too.

**Comment by taigenraine** [comment]
I just got this same issue, in survival.  Phantom Helm dropped from boss with Mending, Aqua Affinity, Curse of Vanishing, and Protection III on it.

**Comment by Drullkus** [comment]
Enchantment Tags are a thing now IIRC. Can just attach a tag for enchants to not add
