### ISSUE TITLE
Game freeze on return from Twilight Forest; Cubic Chunks-related

### ISSUE THREAD

**Issue by BaccarWozat** [TeamTwilight/twilightforest#75]
Forge version:  1325
Twilight Forest version: 2.4.0 branch 1.11.2 commit a7a2437
Link to crash log: https://pastebin.com/hnsnJBie
(Not a crash log as it froze and did not make a crash log, but the fml-client-latest.log)
Steps to reproduce:
1. Start game with TF and Cubic Chunks (build 0.0.625.0)
2. Make a world with tall terrain (in CustomCubic, set at least one factor to 1024)
3. Go up to Y>2048
4. Make a Twilight Forest portal, go through
5. Return from same portal

What I expected to happen: Either a return to the portal at Y>2048 (3177 in the below example), or a return to somewhere Y<256, whether or not there was a new portal created there.

What happened instead: Game froze on "Loading terrain" screen and had to be manually shut down.

![2017-06-21_01 10 00](https://user-images.githubusercontent.com/8357501/27370779-bf18115a-5623-11e7-95c7-bfbde1327899.png)
![2017-06-21_01 11 39](https://user-images.githubusercontent.com/8357501/27370780-bf184738-5623-11e7-9780-98405bf301e7.png)

**Comment by williewillus** [comment]
I'm surprised this even works at all

**Comment by theishiopian** [comment]
Perhaps this should be taken to the cubic chunks issue tracker instead?

**Comment by Tamaized** [comment]
See https://github.com/Shinoow/AbyssalCraft/issues/220#issuecomment-308866647

**Comment by Tamaized** [comment]
Gonna close this as it seems to be fixed on the other mod's end
