### ISSUE TITLE
Twilight forest crashing my All the Mods 3 Server?

### ISSUE THREAD

**Issue by Shaun-Craddock** [TeamTwilight/twilightforest#751]
I posted in the All the Mods 3 (ATM3) GitHub about my server crashing and a user pointed out to me that the crash is related to the Twilight Forest and suggested I post on here as well to see if you guys could help enlighten me as to what might be causing the crash. Below is a copy of the post from the ATM3 GitHub. At the bottom is the crash, settings cfg and world files.

Any help would be appreciated
Thanks
Craddrock 

Hello I run and host an All the Mods 3 server running 5.12.1 for me and a friend. We went to space and created a space station the other day and the server was fine. It got late so we came back to the over world, saved and backed up the server and shut it down for the night. Since then I have tried booting up the server which will boot up fine but when one of us tries to log into the server it crashes out and our games disconnect. I have tried restoring from a backup however it seems to be when we are in the over world the game crashes as the backups where we are in space the server will let us log in fine but when we try loading into the over world the server will crash.
We created the space station ages ago however we decided to "upgrade" the station and make it much bigger than it previously was. I have tried adjusting the server RAM to no avail. I originally had it set to 10 GB but changed it to different amounts to see if that helps. I even ran memtest86 on my PC just to make sure my RAM wasn't faulty.

I have included the crash, server cfg and world files in the hopes someone might be able to deduce why my server is crashing. I have put 14 days into this server so I would like to keep it going if possible.

Thank you
Craddrock

My system specs:
Intel i7 6700k (4 cores 8 threads) which is water cooled.
32 GB RAM.
Nvidea GTX 1070.
(More than enough storage).

Crash log:
https://drive.google.com/file/d/1J-D3uZ2mRgSZ8FMN6ThxaWRQfAu74bra/view?usp=sharing

Server cfg file:
https://drive.google.com/file/d/1zl9k_swjXWBbpY9F82MxMFAhZQfKvloP/view?usp=sharing

world file:
https://drive.google.com/file/d/1cWj0fzgopBRqiguSLQmE06kTTHycDMS7/view?usp=sharing

**Comment by bs2609** [comment]
Can you post the full `latest.log` from the server when a crash occurs?

**Comment by Shaun-Craddock** [comment]
Latest.log:
https://drive.google.com/file/d/1YQL2TyY3vnXi9LKZH_chnGtA_Vd_4HFl/view?usp=sharing

**Comment by bs2609** [comment]
See these errors from earlier on in your log:
```
[14:04:41] [Server thread/ERROR] [FML]: Cannot Hotload Dim: 26
java.lang.IllegalArgumentException: Could not get provider type for dimension 26, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:164) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:252) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:832) [MinecraftServer.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$9.selectNetworks(FMLOutboundHandler.java:304) [FMLOutboundHandler$OutboundTarget$9.class:?]
	...
```

The error here is causing the world to be null, which then causes a `NullPointerException` in the networking code immediately after.

**Comment by Shaun-Craddock** [comment]
So whatever it is is causing the over world not to load?

**Comment by Kizzycocoa** [comment]
I was directed to post here, it seems there is a similar issue occuring in my world:

log: https://pastebin.com/FJAfYmGa
crash report: https://pastebin.com/HtnMyPq9
debug log: https://gist.github.com/Kizzycocoa/8930dc410561d634b037359fa9761801

Issue is, mca files 0,0 and -1,0 are crashing my Mystcraft world. Happened in SMP, where it had a chunkloader, so no idea what is causing it.

**Comment by Andromander** [comment]
This issue appears to have been mostly addressed in another commit.
However, as dimensions are handled differently in the 1.16 versions, this may no longer be a problem at all. That is, if dimension loading is the real problem here. Feel free to reopen if it comes back.
