### ISSUE TITLE
Hydra fireball shots sound like a fence gate

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#752]
Forge version: 1.12.2 - 14.23.5.2768
Twilight Forest version: 1.12.2 - 3.8.689

Steps to reproduce:
1. Summon hydra
2. Wait for it to use its 3 fireball throwing attack, and listen to the sounds it makes when it shoots each fireball

What I expected to happen:
Sounds like.. whatever a hydra shooting a fireball sounds like

What happened instead:
sounds like a fence gate opening or closing

**Comment by Tamaized** [comment]
Pretty sure this is intended.

**Comment by Megalodab** [comment]
there's no sound effect for hydras shooting fireballs? I thought this was some kind of bug. When I put show subtitles on in the sounds settings it says Fence Gate Creaks when the hydra goes thru its fireballs.

**Comment by Megalodab** [comment]
[Video Cutter_23_6_22_30_43.zip](https://github.com/TeamTwilight/twilightforest/files/3318977/Video.Cutter_23_6_22_30_43.zip)
shows the fence gate sound. U can tell by reading the subtitles in the bottom right of the screen

**Comment by jellysquid3** [comment]
I'm having a hard time understanding why you thought it would be a good idea to play music in the background with many other mobs around, all taking damage. It's impossible to hear individual sounds in the video you linked due to all the noise. It would help a ton if you could upload a clean video with only the Hydra sounds.

**Comment by Megalodab** [comment]
> I'm having a hard time understanding why you thought it would be a good idea to play music in the background with many other mobs around, all taking damage. It's impossible to hear individual sounds in the video you linked due to all the noise. It would help a ton if you could upload a clean video with only the Hydra sounds.

When i noticed the problem I had music playing in the background and just went back and recorded it. I thought it was obvious and reproduceable enough that I didn't have to retake the video especially bc of the subtitles.
