### ISSUE TITLE
Parsing error loading built-in advancement

### ISSUE THREAD

**Issue by KokSaker** [TeamTwilight/twilightforest#753]
Forge version: 14.23.5.2838
Twilight Forest version: 1.12.2-3.9.888-universal
Link to crash log: https://gist.github.com/KokSaker/1fc67c8f9194219e00046e1d1a618abf
Steps to reproduce:
1. Install Twilight forest.

What I expected to happen:
Built-in advancements loading. Immersive Engineering, Thaumcraft and Tinkers construct mods absence in the pack shouldn't result in an error.

What happened instead:
Built-in advancements not loading.

Mods:
 - BetterAdvancements-1.12.2-0.1.0.77
 - champions-1.12.2-1.0.9
 - deepmoblearning-1.12.2-2.5.2-universal
 - Forgelin-1.8.3
 - iChunUtil-1.12.2-7.2.1
 - jei_1.12.2-4.15.0.283
 - JustEnoughResources-1.12.2-0.9.2.60
 - MatterOverdrive-1.12.2-0.7.1.0-universal
 - Mekanism-1.12.2-9.7.8.379
 - MekanismGenerators-1.12.2-9.7.8.379
 - MetalChests-v5.1.2+mc1.12.2
 - NuclearCraft-2.17a-1.12.2
 - Patchouli-1.0-19
 - PortalGun-1.12.2-7.1.0
 - RebornCore-1.12.2-3.13.12.447-universal
 - RebornStorage-1.12.2-3.3.4.85
 - refinedstorage-1.6.14
 - refinedstorageaddons-0.4.4
 - TBone-v1.3.0+mc1.12.2
 - TechReborn-1.12.2-2.22.1.979-universal
 - twilightforest-1.12.2-3.9.888-universal
 - VanillaFix-1.0.10-99

**Comment by bs2609** [comment]
Known issue, it's not a major problem - as you don't have those mods, it not important that their related advancements don't work.

Currrently, we're stuck waiting on https://github.com/MinecraftForge/MinecraftForge/pull/5255 for us to be able to fix this properly.

**Comment by KokSaker** [comment]
Thank you. Glad to see that this was being already worked on.

**Comment by bs2609** [comment]
Resolved by 2c21da4c894ace5924d33c705e5dfa1c4b679fad and the mentioned PR being merged.
