### ISSUE TITLE
When fishing into portal, TF returns exception

### ISSUE THREAD

**Issue by preeefix** [TeamTwilight/twilightforest#756]
Forge version: 1.12.2 - 14.23.5.2838
Twilight Forest version: ) 3.8.689
Link to crash log: https://transfer.sh/LkZOB/debug.log

Steps to reproduce:
1. Acquire Fishing Pole
2. Use Fishing Pole, casting inside of a TF portal.

What I expected to happen:
- Upon return, an Experiment 115 should appear in the inventory

What happened instead:
- The fishing pole is returned to it's uncast state.

**Comment by bs2609** [comment]
For reference, the error messages here are actually a vanilla bug ([MC-4581](https://bugs.mojang.com/browse/MC-4581)).

**Comment by Andromander** [comment]
Just to keep here as a reference: this crashes in 1.12. However, 1.16...just has some very funky behaviour.

**Comment by GizmoTheMoonPig** [comment]
I went and fished in the TF portal a couple days ago and it seemed totally fine to me. Granted, the loot just immediately went to the TF instead of to the player, but it was normal otherwise. Since this isnt an issue anymore, im gonna close this.
