### ISSUE TITLE
Mob names not shown correctly on Servers

### ISSUE THREAD

**Issue by ruairidh74** [TeamTwilight/twilightforest#76]
Forge version: 13.20.0.2228
Twilight Forest version: 37 (2.4.0.37)
Link to crash log: N/A

Steps to reproduce:
1. On a server, change to Survival Mode.
2. Spawn in, or find a mob that can kill you.

What I expected to happen:
When you die to a Twilight Forest mob it should say: "ruairidh74 was slain by Giant Miner" for example.

The names show correctly in singleplayer, examples:
![2017-06-21_11 56 08](https://user-images.githubusercontent.com/29524403/27381445-cd62e86e-567a-11e7-8c4a-fe78c8c31105.png)
![2017-06-21_11 58 07](https://user-images.githubusercontent.com/29524403/27381448-d1221060-567a-11e7-9806-52ec215711c9.png)

What happened instead:
Instead, when you're killed by a mob, on a server, it'll say "slain by entity.twilightforest:giant_miner.name" for example, instead of "slain by Giant Miner".

On a Server, examples:
![2017-06-21_11 51 46](https://user-images.githubusercontent.com/29524403/27381370-814d3b82-567a-11e7-8d50-a7f514a59ff5.png)
![2017-06-21_11 52 48](https://user-images.githubusercontent.com/29524403/27381377-8512e29e-567a-11e7-8904-c7547c04f22d.png)

**Comment by Tamaized** [comment]
This seems to have been fixed already? Not sure which commit though.

**Comment by williewillus** [comment]
should be fixed now
