### ISSUE TITLE
NullPointerException: Rendering item

### ISSUE THREAD

**Issue by wojoeraf** [TeamTwilight/twilightforest#760]
Forge version: 
Twilight Forest version: twilightforest-1.12.2-3.8.689-universal.jar
Link to crash log: https://gist.github.com/wojoeraf/0e6aecce39779800c40bcb55d0efbb89

Steps to reproduce:
1. I was opening the simple storage networks mod remote control and startetd typing "hy" in the search panel. Not reproducible for me.

What I expected to happen: No Crash

What happened instead: Crash

**Comment by bs2609** [comment]
It's hard to tell exactly what's going on here, especially as you say the crash isn't reproducible. However, c9d5e90d7f281795eb88824a9fb238b84e4eeadb should make our code here less likely to crash in future, even if something's wrong.
