### ISSUE TITLE
Skin changed to Adherent on Multiplayer

### ISSUE THREAD

**Issue by sjennings530** [TeamTwilight/twilightforest#763]
My friends and I have a private multiplayer server with the Direwolf 1.12 mod pack (which includes the Twilight Forest mod). I have completed all that the mod pack has to offer and returned to the overworld for some time now. But recently my skin has changed from what I have it set to, to that of the Adherent enemy in the Final Castle. Normally this wouldn't bother me but the skin itself is slightly larger than normal and makes it harder to get through doorways and is just more of an inconvenience. I was just wondering if there was something I had eaten or equipped that caused this and if there is any way to reverse it. Thanks
![20190704_102337 (1)](https://user-images.githubusercontent.com/52539311/60673813-ac78ad80-9e46-11e9-8150-25affc846fa0.jpg)

**Comment by Andromander** [comment]
I suspect this is likely another mod doing it, perhaps Morph mod or something that may cause the player model to change to another entity?
As far as it is know, Adherents don't possess the player in any way, nor can the player become an Adherent normally. If this issue occurs with TF alone, feel free top reopen this.
