### ISSUE TITLE
fire beetles fire and skeleton druids projectiles go thru shields

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#764]
Forge version: 1.12.2 - 14.23.5.2768
Twilight Forest version: 1.12.2 - 3.8.689

Steps to reproduce: 
1. Spawn fire beetle and skeleton druid
2. Equip shield
3. go into survival mode, attempt to block the fire or skeleton druid projectiles with shield

What I expected to happen: Shield can block the incoming projectiles

What happened instead: projectiles ignore the shield and damage me instead

**Comment by xevilredx** [comment]
I think that happens because it's a magic attack. For what i've seen, those can't be blocked with the shield.
I found a mod called **parry** (Or Shield parry), that allows you to enchant your shield with "rebound" so it can fully reflect any proyectile.

**Comment by Megalodab** [comment]
just tested this in the 1.16 beta and it looks like its been fixed --- BUT skeleton druids aim a little higher like at ur head so the projectiles hit u more. fire beetles flames get blocked by the shield a little better I think. its still totally possible to get hit by both of these if ur not very careful so its balanced now imo.
