### ISSUE TITLE
Maze Maps stop updating after you die with it in inventory

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#766]
**Forge version: 1.12.2 - 14.23.5.2768
Twilight Forest version: 1.12.2 - 3.8.689**

**Steps to reproduce:**
1. Partially explore a maze map somewhere, I was in a labyrinth if that helps.
2. get killed by something because you decided to go in with half armor (twice)
3. somehow magically find both sets of stuff on the second try on the bottom floor of the maze.
4. pick up and open map. white pointer is visible but moving and map stops updating. the pointer was static in my death location, facing in the same direction too.

**What I expected to happen:** Maze map continues updating as normal once I pick it back up, and pointer goes to my new position instead of location on death.

**What happened instead:** the map pretty much stayed exactly the same as how I had it the first time, did not update anymore after I picked it back up. **The problem got fixed when I restarted minecraft.**

**Comment by bs2609** [comment]
Likely the same issue as #533, but for maze maps, which was fixed in-dev by 685f952fff8e088a6b968a7343b699894377d3dc.

**Comment by bs2609** [comment]
This should now be fixed in the newer releases - feel free to leave a comment if you can still reproduce it in the latest version.
