### ISSUE TITLE
Lagging or all players disconnected due to enter TF portal

### ISSUE THREAD

**Issue by zhourui123** [TeamTwilight/twilightforest#767]
Forge version:  spongeforge-1.12.2-2768-7.1.6-RC3627
Twilight Forest version: twilightforest-1.12.2-3.8.689-universal
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Switch to the specified sponge version
2. delete world dir and set seed to `7133479666482362947` at server.properties
3. start server and tp player to 20, 64, 124 (It seems that surrounding this location will cause timeout problems)
5. make a TF portal
6. Enter and  return back to over world, Once again enter the TF portal

What I expected to happen:
rapidly enter TF

What happened instead:
Lagging or all players disconnected due to timeout.

edit:
This problem does not occur beyond 400 coordinates.

**Comment by zhourui123** [comment]
aikar timing report:
https://timings.aikar.co/?id=fe01ac7e538b412ab94e0c77dbef3438

server log with spark tick analyze:(line 362 start to enter TF)
https://gist.github.com/zhourui123/985d5c39e8ec01c78a4c052c913b16ff

server log with spark tick analyze and Phosphor mod:(line 276 start to enter TF)
https://gist.github.com/zhourui123/603b696b6b5835ee81b9bfc8a0216571

**Comment by bs2609** [comment]
Will assume this is https://github.com/SpongePowered/SpongeForge/issues/2862, is that correct?

**Comment by zhourui123** [comment]
Yes, also #769
