### ISSUE TITLE
Performance issue in TFTeleporter#placeInExistingPortal

### ISSUE THREAD

**Issue by ImMorpheus** [TeamTwilight/twilightforest#769]
Forge version: 14.23.5.2838
Twilight Forest version: 1.12.2-3.8.689
Link to crash log: none

https://github.com/TeamTwilight/twilightforest/blob/3ab2ef5aca4e0739a6d12b57ccadbfa05c25d909/src/main/java/twilightforest/TFTeleporter.java#L209

This is queuing for unload the same chunk over and over. (not sure about the logic in the first part of the for loop, but this looks like an issue). 
There is not check to know if https://github.com/TeamTwilight/twilightforest/blob/3ab2ef5aca4e0739a6d12b57ccadbfa05c25d909/src/main/java/twilightforest/TFTeleporter.java#L180 returned a previous handled chunk.

This was found thanks to https://github.com/SpongePowered/SpongeForge/issues/2862
(the method was queuing for unload the spawn chunk over and over which was triggering a config save).

**Comment by GizmoTheMoonPig** [comment]
looks like that snippet of code is no longer used in modern versions (its commented out) so I assume this is no longer an issue
