### ISSUE TITLE
suggestion/enhancement: extra inventory/character slot for charms of life and keeping

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#770]
maybe above the offhand slot there would be two extra slots for a charm of keeping and a charm of life, sort of like terraria has those extra slots. and maybe another for a totem of undying? just some ideas, not sure if this will be too op.

**Comment by bs2609** [comment]
Currently, charms can be worn as baubles if you have that mod installed.

**Comment by Megalodab** [comment]
Oh didn’t know that. Will tf gear for all of the baubles accessory slots be made or are there plans? Just wondering

**Comment by Killer-Demon** [comment]
We have Baubles integration for versions on 1.12.2 and will re-add the functionality at a later point for Curios.
