### ISSUE TITLE
Server crashes when a player enters the portal.

### ISSUE THREAD

**Issue by Bofumofu** [TeamTwilight/twilightforest#771]
Forge version: 
Twilight Forest version: (1.12.2-3.6.345)
Link to crash log: (https://gist.github.com/Bofumofu/423f192dc45912e6c72851afd44a0834)

Steps to reproduce:
1. Run a forge-1.12.2-14.23.5.2768-universal server
2. Create a functioning portal.
3.Go into the portal 

What I expected to happen:
Enter the new dimension

What happened instead:
Server crashed, everybody timed out , when I restarted the server I was in the new Dimension and I even could get out of the dimension by recreating a portal there.

**Comment by Andromander** [comment]
The log provided does not appear to indicate any crashes, despite the server allegedly crashing (unless Time Out means crash). Do you have a crash log of this event, if there is one? 

On another note, your mod is outdated, and the issue may be no longer present. Can you update it?

**Comment by xxfoofyxx** [comment]
everybody timing out could mean that your server was just having difficulty handling the new dimension being loaded/created. did your server software actually close, or just everybody timed out? @Bofumofu 

edit: your server logs suggest this is the case, last line is it saying it's having trouble keeping up lol.

`[18:42:33] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2166ms behind, skipping 43 tick(s)`
