### ISSUE TITLE
Very low Fps when entering while on a server

### ISSUE THREAD

**Issue by Benjihs** [TeamTwilight/twilightforest#773]
Forge version: 14.23.5.2831
Twilight Forest version: 1.12.2-3.8.689

Steps to reproduce: Go in The Twilight Forest while hosting the serving locally

What I expected to happen: A constant 50-60 fps in Twilight Forest

What happened instead: Massive Lag

Hi, so I am currently using the roguelike adventures and dungeons modpack, which includes Twilight Forest in it. I host a server on my PC and earlier today, when my friends and I entered The Twilight Forest, I experienced a massive fps drop (from 60 fps in the overworld to a constant 1-5 fps in the Twilight Forest). I thought it might be due to the server running on my PC so i "moved" the server to another PC. However, I still experience very low fps (1-5) in The Twilight Forest even though the server is hosted on a secondary PC. Also, it is important to point out that in singleplayer I entered The Twilight Forest and had a constant 60 fps. Any Ideas as to why this is happening?
Thanks!

Update: I tried single player again and i do get some 15-20 fps from time to time, but it is nowhere close to the low fps I get on a server.
Update 2: I don't know if this is a known issue, but it seems like an area around the spawning pool/portal for The Twilight Forest is a no no zone for my fps. Once I got out of that zone, i hit constant 60 fps. My friends don't seem to experience that problem, weird... Anyway, as long as I stay away from that "entry zone", I don't experience lag.

Below is when i'm in The Twilight Forest while on my secondary PC's server:
![image](https://user-images.githubusercontent.com/46755766/61102470-e98f0200-a43b-11e9-947f-de64ac21c996.png)

My pc specs: Core i7-7700 16 GB Ram and Nvidia Gtx 1060
I am running this on a laptop

**Comment by bs2609** [comment]
For client-side FPS issues, you'll need to provide information from the client-side profiler, which can be accessed via shift-F3 and navigated using the number keys.
