### ISSUE TITLE
Uncrafting table uses wrong recipe + costs xp: uncrafting blocks of condensed material

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#776]
Forge version: 1.12.2 - 14.23.5.2768
Twilight Forest version: 1.12.2 - 3.8.689

Steps to reproduce:
1. Take a block of a "condensable" item (example: block of steeleaf) and put it into the input slot of the uncrafting table
2. instead of normally returning a stack of 9 steeleaf in this case, it returns the full grid of single steeleaves with a cost of 9 xp. 

What I expected to happen: the condensed block is returned to the materials that created it, without costing xp, the way regular crafting tables do it.

What happened instead: uses the forward crafting recipe for the block instead of the uncondensing recipe for returning a single stack of 9 of that material, costing 9 xp. 

It wouldn't matter if it kept filling the grid with materials instead of the one stack of 9. The real problem here is that it just costs xp to do this, even though it is not supposed to.

**Comment by bs2609** [comment]
You can use the regular 'unpacking' recipe by placing the block in the 3*3 crafting grid, as you would with a regular crafting table.

**Comment by Megalodab** [comment]
Facts. I forgot abt that
