### ISSUE TITLE
cant hear seeker bow sound effects when Friendly Creatures sound effect is off

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#778]
Forge version: 1.12.2 - 14.23.5.2768
Twilight Forest version: 1.12.2 - 3.8.689

edit: cannot hear the bow firing, arrow hitting, and if you are breaking blocks with the bow for some reason the breaking sound has no volume either.

Steps to reproduce:
1. turn friendly creatures sound effects off
2. fire a seeker bow. I couldn't hear the sound of the bow firing the arrow and the arrow hitting a wall or target etc, even though it worked fine w a regular bow.

What I expected to happen: I can hear the seeker bow firing and arrow hitting

What happened instead: cant hear the seeker bow firing and arrow hitting

**Comment by bs2609** [comment]
Fixed for the triple bow by 575a60b66a8376eafa0b03a5300693e68fee9b09, already fixed in-dev for the other bows by the cleanup in 767a343e981ee081148b81a197c6e29e279f9b8c.
