### ISSUE TITLE
no option to open recipe book in uncrafting table

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#779]
**Edit: also tested on June 21 8pm 2021 for 1.16:
Forge Version 1.16.5 - 36.1.0
Twilight Forest version: 1.16.5 - 4.0.490 (beta)
totally still an issue in 1.16**

Forge version: 1.12.2 - 14.23.5.2838
Twilight Forest version: 1.12.2 - 3.9.974

Steps to reproduce: 
1. open uncrafting table

What I expected to happen: button to open recipe book is visible

What happened instead: button isnt there

**Comment by Megalodab** [comment]
https://github.com/TeamTwilight/twilightforest/issues/776
yo id like to bring up a report i made a while ago about an uncrafting table issue. bs2609 shows a workaround, but its still a workaround. and if u havent had ur coffee that morning then u will still waste the xp even tho thats not really how its intended to work. so I would like u guys to take another look at this please.
like for the recipes that can be undone normally without wasting xp, just dont cost xp for those if a player decides to put it in the special uncrafting slot.

**Comment by Tamaized** [comment]
#322

**Comment by Drullkus** [comment]
Added via [2c65fe5](https://github.com/TeamTwilight/twilightforest/commit/2c65fe53eaf811ed126dffc0410d4d48d070a5fd)
