### ISSUE TITLE
Crash while ticking entity/player

### ISSUE THREAD

**Issue by redstone2019** [TeamTwilight/twilightforest#780]
Forge version: 10.13.4.1614
Twilight Forest version: 2.3.7
Link to crash log: https://gist.github.com/redstone2019/24fe25f4120c59a55fcd88db65c361c9

Steps to reproduce:
1. Explore the Twilight dimension

What I expected to happen:
Nothing but exploration

What happened instead:
Crashing while ticking entity

**Comment by Andromander** [comment]
1.7.10 is no longer a supported version. Update to 1.12.2.

**Comment by redstone2019** [comment]
I can't, the modpack i'm using has a max version of 1.7.10

**Comment by redstone2019** [comment]
Do you need a modlist?

**Comment by redstone2019** [comment]
This happened 4 times before I stopped playing
The first crash: Ticking Entity: 
https://gist.github.com/redstone2019/810e70b0078e0336e413ead78ef14277
The second crash: Ticking Entity:
https://gist.github.com/redstone2019/1a73486b2850f9a051b0963c13fbfa67
The third crash: Ticking Entity: **This Post**
https://gist.github.com/redstone2019/24fe25f4120c59a55fcd88db65c361c9
The fourth crash: Ticking Player:
https://gist.github.com/redstone2019/ef4db8a8c6297ff8f311ba02471b135e

**Comment by Tamaized** [comment]
1.) This tracker is for 1.12+
2.) Your crash report has nothing to do with TF, it's aether.

**Comment by redstone2019** [comment]
Thanks! 👍
