### ISSUE TITLE
Giant blocks' texture works incorrectly

### ISSUE THREAD

**Issue by banz3369** [TeamTwilight/twilightforest#781]
Forge version: 
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.8.689

The textures for the giant blocks work incorrectly , and it just looks so ugly

Steps to reproduce:
1. Place any giant block on the ground

What I expected to happen: 

![download](https://user-images.githubusercontent.com/53364489/61995465-89df5a80-b0bb-11e9-8b33-0a02dfb73289.jpg)

What happened instead:

![2019-07-27_22 11 36](https://user-images.githubusercontent.com/53364489/61995469-995ea380-b0bb-11e9-8d4a-e8174b9b77bc.png)

**Comment by bs2609** [comment]
Do you have CTM installed?

**Comment by banz3369** [comment]
wat , we need that for these giant blocks now? we didn't need that before

**Comment by xxfoofyxx** [comment]
@banz3369 The Twilight Forest mod has a soft dependency on CTM to make stuff look better. It's not needed to play the mod, but to make it look better you need it. [Here's an excerpt from the FAQ channel on the discord.](http://prntscr.com/olwe9k)
