### ISSUE TITLE
Root Strands can only be placed on dirt; disappear immediately 

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#79]
First, use Shears to obtain some Root Strands.

What I expected to happen:
I can place them below other Root Strands to extend them downwards (as that is how they generate).

What happened instead:
I can only place them on Dirt blocks (and only on the upside) and they appear after the next block tick (about a second). They also just vanish without a particle effect or sound.

**Comment by Matti-Koopa** [comment]
Possibly related: Moss Patch can also only be played on Dirt and Grass.
Usually it spawns on wood (fallen tree on the ground) but it can't be placed there.

**Comment by williewillus** [comment]
this might be due to https://github.com/MinecraftForge/MinecraftForge/issues/4053

**Comment by williewillus** [comment]
This *should* be fixed. give it a try in the next build.

**Comment by Killer-Demon** [comment]
Torchberry Plants can now be placed on the bottom of dirt as intended again.
Same for Root Strands, which also allow placement on each other.
Moss patches can be placed on any surface.

All three seem to work as intended.
