### ISSUE TITLE
Server crashing on hitting zombie  

### ISSUE THREAD

**Issue by omegagear4** [TeamTwilight/twilightforest#791]
The entire server crashes when I (and only I) hit a zombie, it's hosted through ApexHosting and I already asked their tech support to look at the crash logs, they said it had been a zombie from the twilight forest mod, so they said I should ask here since you guys would have more knowledge on the matter. As far as I've seen and tested it's only with zombies, and it can be any weapon, but only if I am the one to hit it, no one else in the server has recreated the crash. Any information would be amazing
Forge version: 14.23.5.2824
Twilight Forest version: 3.8.689
Link to crash log: https://gist.github.com/omegagear4/4247f5469971daf67bcf92be961196ae
Steps to reproduce:
1. Find a zombie
2. Hit zombie with any weapon (only my character, none of the other 3 in the server cause crash)

What I expected to happen:
1. Zombie dies, gives the much desired EXP

What happened instead:
1. Server crashes for everyone inside, forced to restart server from console

**Comment by Tamaized** [comment]
It's not even a Loyal Zombie and `Level dimension: 0` this is the overworld, the support staff from ApexHosting are dumb as fuck.

This isn't a TF issue.
