### ISSUE TITLE
twilightforest:castle_door_vanished

### ISSUE THREAD

**Issue by xXUnholyWolfXx** [TeamTwilight/twilightforest#792]
Forge version: 14.23.5.2838
Twilight Forest version: (this is the build number)3.9.984
Link to crash log:  [Log](https://gist.github.com/xXUnholyWolfXx/84bf12d78d028a69d81c98bc42929f32)
I updated my twilight forest and tried to start my server and it came back with this error and no matter what i type in it just crashes.
to add here I tried to update my twilight forest from twilightforest-1.12.2-3.8.689-universal to twilightforest-1.12.2-3.9.984-universal and got the error Missing minecraft:items: twilightforest:castle_door_vanished

**Comment by Pythonic-Rainbow** [comment]
This is only introduced in Build 984. Not a crash, just a missing registry, and doesn't seem to be veryimportant.

I noticed it says its a missing item, but in TF code this vanshied door is registered as a block?

**Comment by bs2609** [comment]
The item form of the block was removed as it served no purpose and wasn't obtainable outside of commands (and possibly bugs).

I don't see any crash in the log posted, did the server actually stop running or just freeze?

**Comment by xXUnholyWolfXx** [comment]
Sadly it did crash though in an odd way when I type -Dfml.queryResult=confirm or -Dfml.queryResult=cancel they both cause the server to simply freeze and go non responsive.

**Comment by Pythonic-Rainbow** [comment]
I don't have the freeze. I however have "Fatally missing registry" but I think thats not related to TF

**Comment by Andromander** [comment]
The warning for missing entries is mostly harmless and proceeding shouldn't cause problems. Crashing doesn't appear to have happened as the log does not mention it, not was one provided when asked. If it has frozen, it is more than likely trying to load up the world. If one can be provided, feel free to reopen this issue.
