### ISSUE TITLE
startup crash NoClassDefFoundError: twilightforest/block/BlockTFMagicLogSpecial

### ISSUE THREAD

**Issue by Fenekhu** [TeamTwilight/twilightforest#793]
Forge version: forge-14.23.5.2838
Twilight Forest version: 3.9.984-universal
Link to crash log: https://pastebin.com/Nj6JtEsa

Steps to reproduce:
1. launch minecraft
2. wait a minute

What I expected to happen: Minecraft launches fine

What happened instead: Minecraft crashed

**Comment by Tamaized** [comment]
duplicate #685

Please look for duplicates first before posting an issue. This one specifically is pinned.

**Comment by Fenekhu** [comment]
oh dang sorry. I looked at that one but I didn't look at the crash log since I thought it was a little old to be the same issue, and because I forgot I had JEID. I rolled back to 3.8.689 and got it working again but I'll look into JEID now.
