### ISSUE TITLE
json errors on startup when you dont use some optional supported mods like Immersive Engineers 

### ISSUE THREAD

**Issue by sharkiller** [TeamTwilight/twilightforest#795]
Forge version: 1.12.2-14.23.5.2838
Twilight Forest version: 1.12.2-3.9.984
Link to crash log: https://pastebin.com/raw/2gAeVYTd

Steps to reproduce:
1. Download last version
2. Start server.
3. See errors on startup.

What I expected to happen:
If i dont use some of the supported mods, there should be no errors.

What happened instead:
Errors in the console.

**Comment by Drullkus** [comment]
Since Forge has no support for optional advancement loading unlike recipes, we’re not able to prevent these errors from appearing on your console. However the game will function just fine.

**Comment by sharkiller** [comment]
this is a problem with your patchouli implementation. seriously a wontfix for errors to display 2 lines on a optional book about an option mod?

**Comment by Andromander** [comment]
There really isn't a fix if Forge does not have the support.

**Comment by sharkiller** [comment]
maybe a config to disable expressly an optional mod in the config? 
or simply not add 2 lines of text for an optional mod until they add the proper support? 
you dont write broken code just because there is no proper support.

**Comment by Andromander** [comment]
Again, there is no fix, and removing those lines will break the mod more than just a couple harmless errors. There already is a "disable mod compatability" config option. Stop trying to suggest solutions to a problem that cannot be fixed on this side because these errors are completely harmless. If you *do* want a fix, you have to take it up to Forge, or get the optional mods.

**Comment by Tamaized** [comment]
This has nothing to do with patchouli at all

**Comment by Tamaized** [comment]
See: https://github.com/TeamTwilight/twilightforest/issues/753#issuecomment-505575777
