### ISSUE TITLE
Crash on client side start up

### ISSUE THREAD

**Issue by ValentineBlaze** [TeamTwilight/twilightforest#796]
Forge version: 
Twilight Forest version: 3.9.984
Link to crash log: https://paste.dimdev.org/egasilovox.mccrash

Steps to reproduce:
1. I just well launched it trying to make a new pack and crashed

What I expected to happen: it to work

What happened instead:  it crashed on step one

**Comment by vani2620** [comment]
Forge version: 1.12.2-14.23.5.2837
Twilight Forest version: 3.9.984
Crash log link: https://paste.dimdev.org/cozomineki.mccrash
Synopsis: same as above
