### ISSUE TITLE
Seeker Bow NEEDS better prioritizing + damage seems weird

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#798]
**Edit: Also tested on June 18 2021 11:00am for latest 1.16 versions:
Forge Version 1.16.5 - 36.1.0
Twilight Forest version:  1.16.5 - 4.0.490 (beta) **

Forge version: 1.12.2 - 14.23.5.2838
Twilight Forest version: 1.12.2 - 3.9.974

### **Prioritizing problems**
Steps to reproduce:
1. spawn some target mobs around and test different situations where the seeker bow will select which targets to fire at. The problem itself is hard to describe in words so ive got a video that demonstrates what im talking about, recorded in 1.12 version, about 1.5 min long: https://youtu.be/iXV5uFOf0GU
heres another vid that shows the same thing, this was recorded in the 1.16 version: https://medal.tv/clips/58666111/d1337pzgkVY3

What I expected to happen: seeker bow will seek the right targets

What happened instead: arrows are redirected toward other targets that are even harder to hit, or toward targets that cant be hit because there is a wall or other obstacle in the way, or toward a target that is clearly not where my crosshair shows im trying to aim at (i can see how this situation might be tough to determine "what" the player is aiming at especially if theres multiple mobs close together. maybe this one doesnt get changed as much).
Another change I think would be good: prioritize hostile over passive mobs, even if the passive one is like closer or whatever. Ex: if im in a cave trying to shoot the skeleton, then target the skeleton not the bat flying between us. 

### **Damage problems**
Steps to reproduce: try spawning the same mob close vs. far away and hit it with seeker bow and compare how many hits it takes

What i expected to happen: damage is consistent whether i hit it up close or long range. and its not too op.

What happened instead: it looks like the damage drastically increases the farther the target is away. its one shotting zombies, creepers, spiders, skeletons, redcap goblins + sappers, flame + slime beetles, and even a witch after drinking a resistance pot or something. then i stopped testing bc thats pretty broken imo for just medium range, literally at least 10+ blocks away.
Vid recorded in 1.16 demonstrating with zombies, distances 0-35 blocks away with seeker vs. vanilla bow. https://medal.tv/clips/58625100/d1337wgGJtBy
So if the damage increasing over long range is WAI then cool I think that can be a new interesting feature to reward longshots, altho it is kinda weird since it makes those longshots for u... maybe this can be an idea for a different bow? either way I think this is too op in its current state, and its only nerf to keep it balanced is the fact that its prioritizing is wack lol

**Comment by Megalodab** [comment]
also it sometimes targets passive mobs instead of the hostile i was aiming at. so it should prioritize hostiles first

**Comment by GizmoTheMoonPig** [comment]
The damage has now been completely fixed: it has the same damage as a normal bow and will do less depending on how much it redirects the arrow
