### ISSUE TITLE
Knight Stronghold Transfered to a Yeti Lair

### ISSUE THREAD

**Issue by lololloser** [TeamTwilight/twilightforest#805]
Forge version: 
Twilight Forest version: (3.10.994)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:Completely Generated Dark Forest

What happened instead:One of knight strongholds was transfered to a alpha yeti lair(The Dark Forest Coincident with a snowy forest)

**Comment by Tamaized** [comment]
Seed and location would be nice
