### ISSUE TITLE
Suggestion: Tconstruct Block and Chains.

### ISSUE THREAD

**Issue by Mohl97** [TeamTwilight/twilightforest#807]
When I first used the block and chain, I absolutely loved how it felt (other than block destruction, but that's just me I think), and then realized that was the only one (unless the cube of annihilation counts). Then it hit me: The mod already has native Tconstruct integration, why not take it a step further and allow block&chains to be made from other materials? Have the loop act as the handle trait-wise, the chains be the extra, and then the block be the head, obviously. Maybe have different chain materials affect the length the block will go out to, or use the TNT modifier to make the head explode on impact instead of coming back, like some sort of mine-flail.

**Comment by Ketrai** [comment]
Sounds like a lot of effort considering a tinker's tool is expected to have support for every trait out there. Sure, some traits might not have an effect. Like when you put "Unnatural" On a sword instead  of a pickaxe, but the majority has some form of benefit. The block and chain is unique that it can both break blocks, and damage mobs. Which begs the question how one is supposed to implement effects on both?

**Comment by Killer-Demon** [comment]
As @Ketrai mentioned, this falls outside of the scope of the mod. However, if someone were to like this enough, they could always try to make an addon mod for it.
