### ISSUE TITLE
Knightmetal is disproportionally strong as a tinker's trait.

### ISSUE THREAD

**Issue by Ketrai** [TeamTwilight/twilightforest#808]
I don't know the exact mechanics, but it appears that by hitting enemies with a tinker's tool that has the stalwart trait quickly beefs you up with a resistance status effect. This effect stretches from I to III, and can last up to 30 seconds. This is especially powerful on fast weapons like shurikens, and rapiers where you have to hit an enemy only three to five times or so to get the full effect. It feels a bit too good. Essentially carrying around a portable, more powerful beacon so to speak, adding an additional 60% damage reduction (20% per level of resistance). This is on top of the potential maximum damage reduction of 80% armor can provide, though without having to go through the effort of enchanting, as well as stacking with enchantments.

Perhaps it would be better to limit the potency of knightmetal? Having one part gives you stalwart I. Where you have to spend an additional modifier to add more metal for stalwart II? Stalwart III probably shouldn't even be attainable. Resistance is special in that it reduces the damage of all sources by 20/40/60/80/100%. You wouldn't even need feather falling with resistance III. And I believe it applies before armor even does. So if you get hit for 20HP, or 10 hearts. You'd only take 4 hearts of damage, which is already laughable. And then armor reduces it easily to <half a heart. Mind you, for an attack that would kill an unarmored person in one hit. 3 layers of possible protection is too much.

**Comment by bs2609** [comment]
7d152e56b17d2a7b12ac780bc32e8390f7dbae8f makes Stalwart only give Resistance I rather than III and reduces the duration, which should make this a little more balanced.
