### ISSUE TITLE
Pinch Beetle displays dismount message when grabbing you

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#81]
The default "Press LSHIFT to dismount" message appears when a Pinch Beetle grabs you.

Obviously, this doesn't work and you are supposed to attack the mob and kill it while it caries you. The message should not appear or should be changed to say something like "It got you! Quick, kill the Beetle".

**Comment by ruairidh74** [comment]
This is also the same for Yeti's.

**Comment by Tamaized** [comment]
Looks like this message is set in `NetHandlerPlayClient#handleSetPassengers` and I don't see any real way to intercept this. Maybe we can do some sort of tick event and check if we're riding one of these entities and if so set the `overlayMessage` and/or `overlayMessageTime`?

**Comment by Drullkus** [comment]
Hmmm there might need to be a hook on Forge's side
