### ISSUE TITLE
Crashing with latest version twilightforest-1.12.2-3.9.984-universal

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [TeamTwilight/twilightforest#811]
Forge version:  14.23.5.2838
Twilight Forest version: twilightforest-1.12.2-3.9.984-universal
Link to crash log: https://paste.ee/p/tNR3n

Steps to reproduce:
1. Start Game
2. ???
3. Don't profit

What I expected to happen: The game to run

What happened instead: The game crashed

**Comment by Tamaized** [comment]
duplicate please look at the pinned issues
