### ISSUE TITLE
Crash on 3.9.984, but not on 3.8.689

### ISSUE THREAD

**Issue by cohenjw** [TeamTwilight/twilightforest#814]
Forge version: 14.23.5.2838
Twilight Forest version: 3.9.984
Link to crash log: https://pastebin.com/AETvsbRt

Steps to reproduce:
1. Load a 1.12.2 Minecraft instance, with the specified Forge and Twilight Forest versions,
and the other mods (not sure if they make a difference) listed in the crash log.
1.5. Removing Twilight Forest from the mods folder fixes the issue.

What I expected to happen:
Game loads up.

What happened instead:
Game doesn't load up. Crashes on construction of mods.

**Comment by Tamaized** [comment]
Please look for duplicate issues before submitting a report. Especially those that are pinned.
Duplicate #685
