### ISSUE TITLE
[Compatibility] Underground Biomes stone does not appear in TF

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#819]
Just looking to see if there's a way to get compatibility with Underground Biomes.
https://github.com/Aang23/UndergroundBiomesConstructs/issues/171

**Comment by Tamaized** [comment]
Unless i'm mistaken this is all they need? Which we def post? I'm too lazy to read their codebase tho
https://github.com/Aang23/UndergroundBiomesConstructs/blob/master/src/main/java/exterminatorjeff/undergroundbiomes/world/WorldGenManager.java#L85

**Comment by ghost** [comment]
Something weird going on. Other mods were able to do worldgen, including replacing all stone... I've decided to backburner the live in the TF project and just play normally for now. Thank you.
