### ISSUE TITLE
Moss Patch Render Error

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#82]
![2017-06-21_16 56 44](https://user-images.githubusercontent.com/10476794/27390869-b160f75a-56a2-11e7-80e8-ee0e4b665d0b.png)

**Comment by Drullkus** [comment]
That's on me, will patch tonight.

**Comment by ruairidh74** [comment]
That's strange, it's fine on my end. Build 40, Forge: 13.20.0.2228

![2017-06-21_22 14 22](https://user-images.githubusercontent.com/29524403/27407087-05f7d334-56cf-11e7-8cd5-9ff8170ff076.png)

**Comment by Drullkus** [comment]
@ruairidh74 You're missing [CTM](https://minecraft.curseforge.com/projects/ctm) which makes the connected textures possible on the moss.

**Comment by Drullkus** [comment]
Fixed the main issue.
