### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by Sunsmilktea** [TeamTwilight/twilightforest#820]
I didn't use your format, please forgive my recklessness.

Chinese developers have developed the Minecraft bedrock version of the Twilight Forest but have not got yours
Authorization Will you stop it?

If you can answer me

**Comment by ChloeDawn** [comment]
Have you tried contacting MCPEDL to have the post taken down? 

(Link for reference: https://mcpedl.com/twilight-forest-mod )

**Comment by ChloeDawn** [comment]
Seems to me the only thing they are doing wrong is not declaring the license of the original assets

**Comment by Tamaized** [comment]
![Screenshot_2019-09-29-09-50-50_1](https://user-images.githubusercontent.com/9671313/65833478-da7f5980-e29e-11e9-8c81-d79b6d8b4c24.jpg)
