### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by iiSwegPanda** [TeamTwilight/twilightforest#821]
Forge version: 14.23.5.2847
Twilight Forest version: 3.9.984
Link to crash log: https://gist.github.com/iiSwegPanda/8a8f2412fc357c59e9f36aa72b32e477

Steps to reproduce:
1. Open the game up

What I expected to happen:
It would load
What happened instead:
It didn't load
![tfissue](https://user-images.githubusercontent.com/35710544/66110429-1c473180-e60a-11e9-9ab2-a17826ff6380.PNG)

**Comment by Andromander** [comment]
Not an issue with the mod. Please read the error message and do exactly as it says.

**Comment by iiSwegPanda** [comment]
> Not an issue with the mod. Please read the error message and do exactly as it says.

do you think i tried that?

**Comment by bs2609** [comment]
```
[18:12:15] [main/INFO] [FML/]: Forge Mod Loader version 14.23.0.2529 for Minecraft 1.12.2 loading
```
I don't think you tried it successfully, at least.
