### ISSUE TITLE
The mod makes the game crash on load

### ISSUE THREAD

**Issue by Electroblade** [TeamTwilight/twilightforest#825]
Forge version: 14.23.5.2847
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.9.984
Link to crash log:<script src="https://gist.github.com/Electroblade/4699164fd572be808dd6aff7b6bdc8a0.js"></script>

Steps to reproduce:
1. Install The Twilight Forest with twitch app
2. Run the game

What I expected to happen: Game should complete the loading process and run

What happened instead: When loading just after finishing stage 2 the game crash

**Comment by Andromander** [comment]
Simply put, there's too many blocks/items being registered and the game cannot handle it. You'll need to remove some mods to free up the IDs, or install a mod to extend the number of IDs allowed.

**Comment by Electroblade** [comment]
Ok Thanks
