### ISSUE TITLE
Something about the server console screaming at me about Banned Block or hole, Depth: 1 ID: Block{minecraft:air}

### ISSUE THREAD

**Issue by JBSTheGamer** [TeamTwilight/twilightforest#826]
Forge version: 1.12.2 - 14.23.5.2847
Twilight Forest version: Twilight Forest - 1.12.2 - 3.9.984
Link to crash log: https://hastebin.com/raw/exohihasir
This is the link to the part of the console logs screaming at me till i stopped exploring and generating chunks and after i left that dim and went back to the overworld then everything was fine again:
https://hastebin.com/raw/jusodolada
Steps to reproduce:
1. There is really no way except for using the same modpack i have made and hosting the server with the forge server hosting files.

What I expected to happen:
I thought the twilight forest was going to be a good mod to add to my modpack to host a server with and there was going to be no problems with it but except for small TPS lagg like usual.
What happened instead:
Well i was wrong this was screaming at me about some blocks. You can see it in the server console logs. I have also provided a crash report for when it did crash if i kept on exploring that dim and generating chunks. I have also explained everything in that second hastebin link.

**Comment by Andromander** [comment]
This looks more like an issue with Battle Towers generating in the dimension.

**Comment by JBSTheGamer** [comment]
I will test it witout that mod and see how it does. If it still does it i will get back to this and ask what it may be this time because i have had problems with servers with some mods that gens structures to often or mods being bugged. I had been thinking its been that mod all this time. It kept saying something about battle towers. I also knew it was something about battle towers when it gens its structures in that specfic dim.

**Comment by JBSTheGamer** [comment]
Ok it fixed the issue thanks for the help.
