### ISSUE TITLE
Very hard bug in the twilight forest.

### ISSUE THREAD

**Issue by Neptun9** [TeamTwilight/twilightforest#827]
In the twilight world, this is what happens. No blocks. Just emptiness. Reinstalling the mod did not help. What to do?
![image](https://user-images.githubusercontent.com/56735027/67111434-8f8d9d80-f1dd-11e9-9644-b0d71134ea88.png)
![image](https://user-images.githubusercontent.com/56735027/67111469-a2a06d80-f1dd-11e9-86e0-26c0082c7352.png)
![image](https://user-images.githubusercontent.com/56735027/67111476-a7fdb800-f1dd-11e9-8b05-e46f38bd3a12.png)

**Comment by Tamaized** [comment]
Not a bug, this is an actual feature. Check your config for skylight forest.

**Comment by Neptun9** [comment]
> Не ошибка, это актуальная особенность. Проверьте ваш конфиг на лес в крыше.

What am I supposed to do about it? What to look for in the config? How to fix?
