### ISSUE TITLE
Cant Reflect back Lich attack

### ISSUE THREAD

**Issue by Xleonq** [TeamTwilight/twilightforest#829]
Forge version: 14.23.5.2838
Twilight Forest version: 3.9.984

Steps to reproduce:
1. Naga was Killed
2. head to the twilight lich

What I expected to happen: Was able to to reflect the Lich ender pearl attack

What happened instead: It break instead of reflect,i try using punch/sword or arrow also give me the same result

i was using the Roguelike Adventures and Dungeons mod pack

**Comment by markismodded** [comment]
I have the exact same problem on my custom pack. I have the latest version of the mod.

**Comment by Tamaized** [comment]
Can you show your advancements

**Comment by dconorozzo** [comment]
Same problem.  Pearls will not reflect.  They appear to break.  Using twilightforest-1.12.2-3.10.1013. 
 Here are my advancements:
![2020-02-26_17 30 06](https://user-images.githubusercontent.com/34375823/75394314-e018b400-58bd-11ea-8516-415a3de8af5e.png)

**Comment by dconorozzo** [comment]
After restarting the server, the number of Lichs was reduced to a single set of 3 and I was able to find the correct one and destroy the shields.
