### ISSUE TITLE
Suffocating in Wall after Death

### ISSUE THREAD

**Issue by ruairidh74** [TeamTwilight/twilightforest#83]
Forge version: 13.20.0.2228
Twilight Forest version: Build 37 (2.4.0.37)
Link to crash log: N/A

Steps to reproduce:
1. Create a world with this seed: 82995420346874850
2. Go/tp to these coordinates X: 156 Y: 68 Z: 242
3. Create a Portal. Remove the 4 grass blocks at these coordinates:
X:154 Y:67 Z:241, 
X:153 Y:67 Z:241,
X:153 Y:67 Z:240,
X:154 Y:67 Z:240.
(Using the "Looking at:" part in the F3 menu you can easily find these block locations.)
Then create the portal as normal round those removed blocks and go through.
4. Once you're through, you can use the /kill command or, go into Survival mode, spawn a hostile mob and let it kill you.
5. Click Respawn.

What I expected to happen:
I expect to spawn next to the Portal inside the Twilight Forest after dying.

What happened instead:
After going through the portal and dying, I respawned on top of the portal, instead of next to it, which brought me back to the overworld. I was then inside the ground and started suffocating.
I tested this many times and it doesn't seem to happen every time. I did try creating a portal in another location in the overworld, and it happened again there, so it may or may not be related to the seed/location.

I recorded myself doing it here:
https://youtu.be/VkyWW4FkYvw
It happened on the second try in this video, but on the very first time I generated a world with this seed it happened the first time.

**Comment by Matti-Koopa** [comment]
I just had this and landed in a cave 300 blocks away from my portal.
This might be Vanilla Nether portal finding code that happens.

**Comment by ThemInspectors** [comment]
Yeah It happens with me quite a bit, Portal exit spawning can spawn you anywhere, eg. in the ground or high enough to die from fall damage. It also happens that you spawn somewhere not near the portal. Maybe it could be a problem with handling spawn points in the Twilight forest?

**Comment by bs2609** [comment]
This was probably fixed by a9835f4f25460a90778ac8e3ed8ef6ef34cdbaf1.
