### ISSUE TITLE
"Unexpected end of ZLIB input stream"

### ISSUE THREAD

**Issue by mootmmot** [TeamTwilight/twilightforest#834]
Forge version: 1.12.2- 14.23.5.2837
Twilight Forest version: 3.10.1013
Link to crash log: https://github.com/mootmmot/Crash-Report/commit/6663f80b3906efc7e9d6096988f553bb338a865b

Steps to reproduce:
1. Go to Fight Hydra
2. Get within range to fight it
3. game crashes?

What I expected to happen: Epic Boss fight with hydra

What happened instead: Game crashed when I got close, won't let me open the world without crashing.

**Comment by TheHolyTopBob** [comment]
Sometimes happens with liquids. Try reproducing it again in another world. All I can offer.
