### ISSUE TITLE
Advancements not Given

### ISSUE THREAD

**Issue by TwoBoogerFace** [TeamTwilight/twilightforest#835]
Forge version: 14.23.5.(something) and 14.23.5.2847
Twilight Forest version: 3.8.369 and 3.10.1013
Link to crash log: Not a crash

Steps to reproduce:
1. Attempt to get an advances(I had issues with "Time to Even the Scales" and "I Wish for More Burning")
2. Get lucky?

What I expected to happen:
To get "Time to Even the Scales" and "I Wish for More Burning"

What happened instead:
I was not rewarded with any advancements. I finally got "Time to Even the Scales" when I accidental dropped my Naga Scale in the Lich Tower I think, but I'm not completely sure. Now, I'm having trouble with "I Wish for More Burning". I currently have the Lamp of Cinders in my hand. I have fired it at the thorns, and even dropped it, and picked it back up, but I can't seem to unlock the advancement. I wish I could give more information, but I don't have any.

Edit:
Ok, I just reloaded the world and got the "I Wish For More Burning" advancement.

**Comment by Andromander** [comment]
Closing as this was resolved, as indicated by edited comment.
