### ISSUE TITLE
Possible bug in equipped baubles when trying to put new ones via right-click in hand

### ISSUE THREAD

**Issue by Venom31** [TeamTwilight/twilightforest#836]
# Version Information
Forge version:  14.23.5.2846
Twilight Forest version:  3.9.984
Botania version:  r1.10-362
Baubles version:  1.12-1.5.2

# Further Information
Link to crash log: https://paste.dimdev.org/powejewabe.mccrash  
Steps to reproduce:
1. Get any Botania bauble and put it on via right clicking with it in your hand to know where it usually goes, remove it and put back into your hand.
2. Get Twilight Forest bauble that can go into any bauble slot and put it in the one expected by the Botania bauble.
3. Right click the Botania bauble back on again while the Twilight Forest bauble occupies it.

What I expected to happen:
The Botania bauble would switch with the bauble occupying the slot, leaving you with the Twilight Forest bauble in your hand as it does with other Botania baubles.

What happened instead:
The Botania bauble remained in hand, error info appeared with its log above. Playing on FTB Academy 1.1.0 mod pack that just displays error info with Ctrl+I and doesn't crash to desktop.

(Tested with Botania as it's the most bauble-rich mod in the pack played. To be fair, it's the only mod I detected in this pack, such that it has "right-click in hand to put on" functionality, so I've posted a bug report there as well.)

**Comment by bs2609** [comment]
> so I've posted a bug report there as well

Thanks, but please also link it in the description in future like so: https://github.com/Vazkii/Botania/issues/3026

Having had a quick look at this, I believe this is a Botania issue with their bauble handling here:
https://github.com/Vazkii/Botania/blob/6666cf1e23a21e721a20aa1be6b61ab516d58a20/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java#L101-L125

Their code is trying to cast the item to an `IBauble` directly, it should be calling `getCapability` to obtain an `IBauble` instance instead.

In any case I'll tag @williewillus to have a look at this, as they helpfully have worked on both projects involved.

**Comment by Venom31** [comment]
Great, thanks!
I thought I could link it later, after I create both posts (just in case). But I couldn't see any 'Link' button after creation. I was only able to press Edit on the title. Is linking only allowed at the initial message?

POST-EDIT. I'm able to edit a comment though. Kinda new to Github, sorry for noobishess.

**Comment by Tamaized** [comment]
You simply just include the url to the other issue in a comment.

**Comment by Venom31** [comment]
I thought it was some special functionality. I'm sure I've seen some 'Link' button during initial edit of the post. And now I don't see it during edit.

**Comment by bs2609** [comment]
Seems to have been dealt with on Botania's side, so I think this is now resolved.
