### ISSUE TITLE
Goblin Stronghold Bossroom Glitch

### ISSUE THREAD

**Issue by flamingredbird** [TeamTwilight/twilightforest#839]
Forge version: 1.12.2
Twilight Forest version: 3.10.1013

Steps to reproduce:
1. Go to any of the Goblin Strongholds that spawn in the Twilight.
2. Attempt to get into the boss room, only for it all to be located within the deep dark forest.
3. Unable to clear the dungeon due to the blindess effect in the whole boss room.

What I expected to happen:
The whole dungeon (or even a majority of it) would be located in terrain that could be explored without having to beat that dungeon's boss.

What happened instead:
Had to dig out of the dungeon and move to another one in order to clear the boss so we could go back to the first one and clear it out.
![2019-11-29_21 22 53](https://user-images.githubusercontent.com/58375792/69907109-16f92f80-138c-11ea-8d27-65ed2e2ffde8.png)

**Comment by yezhiyi9670** [comment]
The problem is that the generation of the Stronghold is not hard-limited to Dark Forest, so some of the non-center parts of the Stronghold can go into the Dark Forest Center. I've seen this too.

Note that there are usually more than one bossrooms in the Stronghold.

**Comment by Tamaized** [comment]
#1487
