### ISSUE TITLE
Stack of Firefly on the ground renders incorrectly

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#84]
A stack of 2 or more Fireflies on the ground is messed-up.
![2017-06-21_18 45 58](https://user-images.githubusercontent.com/10476794/27396059-360806a6-56b2-11e7-9cf1-9834832d0c9f.png)

**Comment by williewillus** [comment]
Forge bug ( i can't find the ticket number but there is one open)

**Comment by williewillus** [comment]
MinecraftForge/MinecraftForge#3886
