### ISSUE TITLE
Enhancement Request : Configuration Options to increase Difficulty

### ISSUE THREAD

**Issue by mactso** [TeamTwilight/twilightforest#841]
We love the look of twilight forest but unfortunately, even with normal diamond gear, all of the encounters are trivial.

I've looked at the configuration and see no way to increase the difficulty.

While a robust, per encounter, option would be nice, even something as simple as the following would be nice:

GeneralHpBonus:1-2billion
GeneralDamageBonus: 0-256
GeneralDamageReductionBonus: 0-256

BossHpBonus: 1-2billion
BossDamageBonus:0-256
BossDamageReductionBonus:0-256

TwilightWeaponsBypassDamageReduction: True/False

Example
GeneralHpBonus:10 // Mobs have +10 hit points
GeneralDamageBonus: 2   // Mobs hit for +2 damage
GeneralDamageReductionBonus: 1  // Mobs take -1 damage from players

BossDamageBonus:4  // Boss Mobs hit for +4 damage
BossDamageReductionBonus: 4 // Boss Mobs take -4 damage from players.
BossHpBonus: 1200 // Boss Mobs have +1200 hp

TwilightWeaponsBypassDamageReduction: True  // Weapons from the expansion ignore the damage reduction bonus making them more useful.

--

Thank you.  I hope you will consider this idea.

**Comment by Tamaized** [comment]
Partial duplicate #637

Honestly I feel modifications like this are out of the scope of the mod and should be done by another mod rather than any mod out there with entities having a giant config for them.

check out https://www.curseforge.com/minecraft/mc-mods/in-control

**Comment by Tamaized** [comment]
Also your insanely huge amounts of health points are not possible in Minecraft. The game itself has a hard limit of 1024HP or 512 Hearts, though there might be a mod out there that removes this limit. But that reinforces the idea that **this is out of the scope of Twilight Forest**.

**Comment by mactso** [comment]
Okay, I understand go ahead and close it.

Sad tho.  Nothing is a challenge with even the weakest equipment from other mods.

I'll see if I can boost them with InControl.
