### ISSUE TITLE
Only bosses spawn

### ISSUE THREAD

**Issue by lujoco** [TeamTwilight/twilightforest#844]
Forge version: forge-1.7.10-10.13.4.1558-1.7.10-installer
Twilight Forest version: twilightforest-1.7.10-2.3.7
Link to crash log: no crash

Steps to reproduce:
1. 

What I expected to happen: I expected that I would have to fight mobs before defeating the boss
What happened instead: No mobs before boss, only the boss spawns

**Comment by Hyxaru** [comment]
For the green snake boss (the Naga), that is intentional, aswell as the Hydra in the fire swamp.

**Comment by lujoco** [comment]
i know that but like only the bosses spawn with every dungeon except if there are spawners

**Comment by Tamaized** [comment]
1.7.10 is not supported.
