### ISSUE TITLE
Villages are broken 

### ISSUE THREAD

**Issue by earlt612** [TeamTwilight/twilightforest#846]
Forge version: 14.23.5.2847
Twilight Forest version: t- MC 1.12.2 - 3.10.1013
Link to crash log: No Crash
Steps to reproduce:
1. Install mod
2.Open or create a world with cheats 
3. Find a village using /locate Village 

What I expected to happen: The chat would say " Found village at 270 (y?) -199 "

What happened instead: The chat said, "Unable to locate feature 'Village'

Note: I did have Actually Additions installed, so the /locate command did work. I recomend anyone who attempts to recreate this to not have AA installed

**Comment by Tamaized** [comment]
Villages don't exist in twilight forest.

**Comment by earlt612** [comment]
Im talking about overworld villages

**Comment by Tamaized** [comment]
We don't control the overworlds chunk generator and in turn, the /locate for that dimension.

**Comment by earlt612** [comment]
Upon furthur testing, I was being stupid. However, most of the buildings spawn without doors. \

**Comment by Tamaized** [comment]
Well, again, we don't control the overworld chunk generator which includes overworld structures which includes villages.

**Comment by Andromander** [comment]
Closing as we do not affect how Villages generate. As a matter of fact, a Village can generate without Doors, or it's has been attacked by Zombies already.
