### ISSUE TITLE
Mc Stops me from loading the main page

### ISSUE THREAD

**Issue by KingAlphaIV** [TeamTwilight/twilightforest#847]
Forge version: 
Twilight Forest version: 3.10.1013 
Link to crash log: https://paste.dimdev.org/ipinuqonek.mccrash
Steps to reproduce:
1. don't know

What I expected to happen: for it to load to the main screen

What happened instead: it showed a text saying report to dev

**Comment by Andromander** [comment]
Can you try reproducing this without Optifine installed? I recall seeing an issue like this before where it was the cause.

**Comment by bs2609** [comment]
^ This is most likely caused by you using an outdated version of Optifine.

**Comment by KingAlphaIV** [comment]
> Can you try reproducing this without Optifine installed? I recall seeing an issue like this before where it was the cause.

no, I can not I just choose an older version of twilight and it worked

**Comment by bs2609** [comment]
Duplicate of #686
