### ISSUE TITLE
Anti-Builder blacklist missing listing for the Gravestone Mod

### ISSUE THREAD

**Issue by MarioSMB** [TeamTwilight/twilightforest#849]
The Gravestone Mod [https://www.curseforge.com/minecraft/mc-mods/gravestone-mod](url) creates a block with the ID `gravestone:gravestone` upon death. It would be nice if this could be blacklisted from the Anti-Builder by default.

It's worth noting that this gravestone item can also be crafted and placed by players, so blacklisting it would allow players to place them here.

**Comment by Tamaized** [comment]
The current config only has a default value purely to show as an example. The current one shouldn't even need to be in there at all.

**Comment by Andromander** [comment]
Closing as compatibility can be added via Tag. Not every gravestone mod is going to be added by us.
