### ISSUE TITLE
TF Crashes on a Server (Server Tick took 60 seconds)

### ISSUE THREAD

**Issue by ruairidh74** [TeamTwilight/twilightforest#85]
Forge version: 13.20.0.2228
Twilight Forest version: Build 40 (2.4.0.40)
Link to crash log: https://pastebin.com/LnmrbHPp

Steps to reproduce:
1. On a server, explore. Move around using creative mode.

What I expected to happen:
Not to crash.

What happened instead:
When exploring in Creative mode it crashed. My server console gave this error:
```[21:21:09] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)```
```[21:21:09] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.```

**Comment by ruairidh74** [comment]
Just got the crash again, but this time two crash reports were generated. One is the same as the one above, and the other was this: https://pastebin.com/3tUaWH5Q

**Comment by williewillus** [comment]
It's just lagging so badly the server bailed. We'll work on improving the performance in another ticket
