### ISSUE TITLE
Towerwood Borer Hitbox is weird

### ISSUE THREAD

**Issue by SunnyOpossum** [TeamTwilight/twilightforest#850]
![2020-02-02_14 33 28](https://user-images.githubusercontent.com/60582335/73614055-bd022980-45c9-11ea-9728-0c21f0676441.png)
Forge version: 14.23.5.2847
Twilight Forest version: 3.10.1013

**Comment by Tamaized** [comment]
Nice

**Comment by Tamaized** [comment]
495802866ee64908b0bb758d0771407c7a1f8e0d
