### ISSUE TITLE
The Door's inventory texture is textureless twilight forest 1.12.2 3.10.1013

### ISSUE THREAD

**Issue by Sageking10** [TeamTwilight/twilightforest#851]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
![2020-02-03_18 56 40](https://user-images.githubusercontent.com/48606472/73701384-5ce9b100-46b7-11ea-9dc7-b7903a4ef0a5.png)

Steps to reproduce:
1. 

What I expected to happen: To see a glorious Door texture provided by the amazing art team. 

What happened instead: SQUARE.

**Comment by Tamaized** [comment]
#711
