### ISSUE TITLE
Infinite Meef Stroganoff

### ISSUE THREAD

**Issue by vortexcube** [TeamTwilight/twilightforest#852]
Forge version:  forge-14.23.5.2847
Twilight Forest version: 1.12.2-3.10.1013-universal
Modpack: Project Ozone 3 Kappa Mode 3.2.51

The Meef Stroganoff just stays in inventory after usage. Sometimes it gives an additional empty bowl. Tested it in new world as well.

**Comment by Andromander** [comment]
This behaviour sounds like it's being caused by the modpack itself changing the behaviour. First time I've heard of this.

**Comment by Killer-Demon** [comment]
This sounds like something that was changed by the mod pack you're playing, as it doesn't behave like such with only Twilight Forest.
