### ISSUE TITLE
Shader Compatibility | Config to Remove TF Skybox

### ISSUE THREAD

**Issue by TheRealJarbean** [TeamTwilight/twilightforest#854]
Forge version: 14.23.5.2847
Twilight Forest version: MC 1.12.2 - 3.10.1013
Link to crash log: N/A

Steps to reproduce:
1. With Optifine installed, and SEUS Renewed, SEUS-v11, or Sildur's Enhanced Default in the shaderpacks folder, load one of the listed shaderpacks and look up at the sky.

A few friends and I have been developing a modpack that relies on shaders for visual enhancement, and they are completely incompatible with the awesome skybox included by TF. The graphical errors can be seen in the attached screenshot. I understand mods are not typically developed to have compatibility with Optifine's shaders, but having an option in the config to disable the custom skybox would be much appreciated.

![Skybox Issue](https://user-images.githubusercontent.com/47651803/74703871-a6b8b800-51dc-11ea-93ee-c14dcac5f5a2.png)

**Comment by renekuhs** [comment]
Were you able to resolve this? I am also searching for an option to do this.

**Comment by renekuhs** [comment]
I was able to remove the sky glitch by disabling VBO rendering in the video options. Only tested with Isildur's Enhanced Default but would assume this would fix the same issue for other shaders as well.

**Comment by Andromander** [comment]
This is an Optifine issue. On top of this, because of how 1.16 handles skyboxes now, they can be "configured" off with a datapack (just make sure the option is set to the overworld).

**Comment by Quantumrage10** [comment]
i'm having the same issue. anyone figured out how to fix this problem client side yet?

**Comment by darkracer125** [comment]
don't know if anyone is still looking for a solution.  but let me answer it with a question. 
other then the shader,  do you happen to also have astral sorcery and/or botania installed?  
because they will do exactly this.   
with astral sorcery change "skyRenderingEnabled ="  from "overworld"  to nothing.  just blank (leave the brackets there) 
and with botania just disable any kind of sky rendering.

**Comment by dabunginator** [comment]
Does anyone know how to create a datapack that removes the TF skybox? I can't find any premade datapacks like that or any tutorials.

**Comment by EvergreenSystems** [comment]
If you are in the Twilight Forest discord server I have one available in a forum post (Datapacks by Shae), feel free to grab it there
