### ISSUE TITLE
Roots and Liveroots interaction with dank//null and better builders wands

### ISSUE THREAD

**Issue by Wonka006** [TeamTwilight/twilightforest#855]
I hope this is the right place to put something like this but if it helps, I'm playing Project Ozone 3.

Basically players can generate infinite liveroots, the block not the crafting item, if they also have the block form of the roots.

Steps to reproduce:
1. Place block of liveroots
2. Use any better builder's wand on it while normal root blocks are in inventory or dank//null
3. Profit

What I expected to happen:
Wanted to place the blocks of liveroot I had in my inventory, but the wand took normal roots from my dank//null and placed them.
What happened instead:
The roots became liveroot blocks and dropped the ironwood item.

**Comment by Tamaized** [comment]
This doesn't sound like an issue on our end but the other mods' ends?

**Comment by Wonka006** [comment]
I'll send a message to the other mod devs tomorrow.  Thanks for the response.

**Comment by Andromander** [comment]
Closing as this sort of interaction is likely a part of a modpack or other mods.
