### ISSUE TITLE
How soon will you finished 1.15.2?

### ISSUE THREAD

**Issue by lovexyn0827** [TeamTwilight/twilightforest#857]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:

**Comment by Andromander** [comment]
Please do not use Issues to ask for ETAs, as it is for reporting issues with the mod itself. It will come out when it does.
