### ISSUE TITLE
You can put the monster items and split into two modules？

### ISSUE THREAD

**Issue by Abo233** [TeamTwilight/twilightforest#858]

**Comment by Drullkus** [comment]
Can you please describe your suggestion in more detail? What would motivate us to create a sub mod and drop these 'monster items' into that? What do you mean by monster items?

**Comment by Abo233** [comment]
Can you separate the creatures of the module into a new module?

**Comment by Abo233** [comment]
The items and biology class alone into a module, a total of two

**Comment by Drullkus** [comment]
There's zero need to do that, we don't have any reason to do that. You can add the mod and use the spawn eggs to spawn the mobs without needing to visit the forest.

**Comment by Abo233** [comment]
In order to improve the link, you can put the module inside of biological extraction, change for the players

**Comment by Drullkus** [comment]
I think you've got the wrong mod, this issue tracker is for the Twilight Forest.

**Comment by 3TUSK** [comment]
@Abo233 

  1. 暮色森林 Mod 中的内容是一个整体。把生物和物品分成两个 Mod 并没有意义。
  2. 拆成两个 Mod 只会增加工作量，而开发者们并没有时间。
  3. 配置文件里有关于禁用暮色森林传送门的选项。你可以考虑通过禁用传送门来让玩家不能进入暮色森林，然后在其他维度生成暮色森林的生物。
  4. ~~配置文件里可以修改激活暮色森林传送门的物品，你可以把它改成空气。~~ Credits to @Tamaized
