### ISSUE TITLE
Fully charged Lamp of Cinders does not work

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#86]
Forge version: 13.20.0.2315
Twilight Forest version: 2.4.0.42

Steps to reproduce:
1. Aiming at Thorns, fully charge a Lamp of Cinders
2. Release trigger when fully charged

What I expected to happen: Thorns around the player would become burnt.

What happened instead: Nothing happens. Simply right-clicking a Thorn bush burns an individual block, but a fully charged lamp has no effect. Also, no burning sound plays.

**Comment by williewillus** [comment]
can't reproduce. works properly for me

**Comment by Andromander** [comment]
Just tried it out now. Must have been lag causing the issue
