### ISSUE TITLE
Twilight Forest？What happened？

### ISSUE THREAD

**Issue by Nuttar2004** [TeamTwilight/twilightforest#860]
Forge version: 
Twilight Forest version: 1.12.2-3.10.1013
Link to crash log:
[latest.log](https://github.com/TeamTwilight/twilightforest/files/4309720/latest.log)

What I expected to happen:The game runs successfully

What happened instead:When mod is loaded, the twilight forest will collapse

This is the mods I joined. I don't know where there is a problem. Please answer it
![mod](https://user-images.githubusercontent.com/61998229/76270740-38ce5080-62b1-11ea-8cab-25664d207a6b.PNG)

**Comment by Tamaized** [comment]
duplicate #685

**Comment by Nuttar2004** [comment]
Thanks，
