### ISSUE TITLE
Suggestion: Add a flying hostile creature in highland biomes

### ISSUE THREAD

**Issue by FlyingCart000** [TeamTwilight/twilightforest#862]
Currently, players in highland can simply build blocks to reach to the cloud cottage or pass through thornlands, which makes Lamp of Cinders and Magic Beans, which are items that are needed to pass through these areas, less meaningful than intended.

By solving this, a flying hostile creature uniquely summoned in highland biomes like a hawk or a giant raven that is able to attack players in the sky can be a great choice. If players are trying to build blocks to pass those area, they will be attacked by those creatures, which makes it quite challenging to reach the location without falling down. But by using Magic Beans or Lamp of Cinders, players can easily reach those areas with much less difficulty, since the beanstalk is wide enough for players to avoid falling down and the lamp can avoid players from building up to the sky.

**Comment by TFGS-Soul** [comment]
A giant raven's nest would be so cool!

**Comment by Killer-Demon** [comment]
It's a valid argument that it's too easy to tower up to the clouds. However, we do have some plans for the highlands and will be revisiting it at some point to rework and have a better experience overall. A flying mob might be something we want at that point but we;ll get to that when we do.
