### ISSUE TITLE
Druid huts with iron ladders spawn with 2 empty doublechests

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#863]
twilight forest 3.10.1013
forge 14.23.5.2838

What I expected to happen: The variant of druid huts that have an iron ladder on a canopy log going to the top floor spawn with a double chest on each floor and a single chest on the top floor. both should contain loot.

What happened instead: only the top floor single chest has loot, other 2 doubles are empty

**Comment by Drullkus** [comment]
Chests intentionally made empty to seed doubt

**Comment by Megalodab** [comment]
haha nice
