### ISSUE TITLE
Minecraft Start up Error

### ISSUE THREAD

**Issue by LordSMRayquaza** [TeamTwilight/twilightforest#864]
Forge version: 1.12.2-14.23.5.2847
Twilight Forest version: 1.12.2-3.10.1013
Link to crash log: https://paste.dimdev.org/cutucaqofu.mccrash
My Minecraft client provides me with this crash with the latest version of Twilight Forest. I'm also using the latest version of Forge for 1.12.2. I don't know what I am doing wrong.

**Comment by LordSMRayquaza** [comment]
Plus, all I know is that it is an initializing error.

**Comment by Andromander** [comment]
I believe this is an issue caused by Optifine, perhaps an outdated version?

**Comment by LordSMRayquaza** [comment]
Then should I just remove Optifine, cause its not like I need it.

**Comment by bs2609** [comment]
Duplicate of #686
