### ISSUE TITLE
twilight variants of planks, ex. druid hut roofs don't catch fire normally

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#865]
twilight forest 3.10.1013
forge 14.23.5.2838

Steps to reproduce:
1. invade a druid hut and kick the druid's ass
2. try to light his roof on fire with flint and steel bc he was mean to u

What I expected to happen: with flint +steel, right clicking twilight wood plank variants on their side, like planks, slabs, and stairs, should catch them on fire like vanilla wood. they won't need an empty block above them to catch on fire, and the fire animation thing can be seen on the sides of the block, below it if its floating, above it, etc.

What happened instead: only twilight plank BLOCKS catch fire when right clicked w flint/steel, and only if you light the top of a block, not the sides. this is diff bc the sides/bottom cant be lit, and stairs/slabs cant be lit at all.

before u ask, yes doFireTick is on true

**Comment by GizmoTheMoonPig** [comment]
fixed in one of my most recent commits for 1.16
