### ISSUE TITLE
{SUGGESTION} Fiery Pick Fortune Compat

### ISSUE THREAD

**Issue by xevilredx** [TeamTwilight/twilightforest#867]
It would be cool if the Fiery Pick with the Fortune enchant gives you more of the melted ore.
For example if I mine the iron ore with the fiery pick enchanted wi8th Fortune III it would give me 2 or 3 instead of 1 iron ingot. I feel like it would be a very useful feature.

**Comment by egogowa** [comment]
[https://github.com/TeamTwilight/twilightforest/issues/224](url)

**Comment by egogowa** [comment]
#224

**Comment by GizmoTheMoonPig** [comment]
just a note for the future: 1.17 allows for fortuning all ores which means we dont need to really add this anymore. Im gonna keep this open in case there are other blocks we should consider.

**Comment by Tamaized** [comment]
There aren't any other blocks to consider, Mojang did away with ore block collection.
