### ISSUE TITLE
Build failiure

### ISSUE THREAD

**Issue by Zemogiter** [TeamTwilight/twilightforest#871]
Forge version: 31.1.35
Twilight Forest version: https://github.com/TeamTwilight/twilightforest/commit/65ef7e35dd8c9a2fd67027cac5acd847b3a6287e
Link to crash log: [log.txt](https://github.com/TeamTwilight/twilightforest/files/4422861/log.txt) (log came from executing the `gradlew.bat` file)

Steps to reproduce:
1. Open the repo in Visual Studio Code
2. Open Teminal
3. Write `gradle build`

What I expected to happen:
Successful compilation
What happened instead: I got this error message:
```
> Configure project :
New Dep: net.minecraftforge:forge:1.15.2-31.1.0_mapped_snapshot_20200123-mixed-1.15.2_at_0df7c4489006c78f083ba2d02b5983a80410640b

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'twilightforest-1.15.x'.
> Failed to notify project evaluation listener.
   > org.gradle.internal.nativeintegration.services.FileSystems.getDefault()Lorg/gradle/internal/nativeplatform/filesystem/FileSystem;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by Tamaized** [comment]
well no fucking shit

**Comment by Drullkus** [comment]
```
> Failed to notify project evaluation listener.
   > org.gradle.internal.nativeintegration.services.FileSystems.getDefault()Lorg/gradle/internal/nativeplatform/filesystem/FileSystem;
```

Looks like your gradle isn't configured correctly on your end

**Comment by Tamaized** [comment]
Not only that... but what makes you think the 1.15 branch is error free currently.

**Comment by Zemogiter** [comment]
> 
> 
> ```
> > Failed to notify project evaluation listener.
>    > org.gradle.internal.nativeintegration.services.FileSystems.getDefault()Lorg/gradle/internal/nativeplatform/filesystem/FileSystem;
> ```
> 
> Looks like your gradle isn't configured correctly on your end

Unfortuatly there is no solution for that error that worked for me. That's why i'm here. Using gradle 6.3, added to PATH.

**Comment by Tamaized** [comment]
ForgeGradle 3 does not (as far as i know) work with newer gradle versions. Use the wrapper provided by the repo. Regardless, nothing you do here will solve any compilation error unless you manage to port the entire project yourself and fix every error.
