### ISSUE TITLE
GameCrash with "gamerule doDaylightCycle false"

### ISSUE THREAD

**Issue by vakryvenik** [TeamTwilight/twilightforest#875]
Forge version: 14.23.5.2847
Twilight Forest version: twilightforest-1.12.2-3.10.1013-universal
Link to crash log: https://pastebin.com/7wLEN0FS

Steps to reproduce:
1. Download and install both mods Simple Dimensions and Twilight Forest. I'm using "SimpleDimensions-MC1.12-1.3.1" and "twilightforest-1.12.2-3.10.1013-universal" versions.
2. In game create new dimension by using command "/simpledimensions create" applying default settings
3. Somehow teleport to that new dimension. I used for that Forge Essentials (forgeessentials-1.12.2-12.3.82-server) command "/mwtp 30000"(because SimpleDimensions dimension's id start with 30000)
4. Change gamerule - "/gamerule doDaylightCycle false"
5. Get any achievement...
6. ... profit?

What I expected to happen:
normal game but without changing day/night time

What happened instead:
game crashed with error "java.lang.NullPointerException: Ticking player"

Why i think this is TwilightForest mod problem:
because without this mod the game continues to work normally (with mods SimpleDimensions and ForgeEssentials)

**Comment by bs2609** [comment]
Seems to be the same crash as #840, but when I looked into that it didn't seem to be an issue with this mod, there isn't anything that ought to be null on that line:
https://github.com/TeamTwilight/twilightforest/blob/fd5c2f0a43556f06618f45c99301f80df6e0f42b/src/main/java/twilightforest/TFCommonProxy.java#L72

I notice that both you and the other person are using Simple Dimensions, so perhaps you should take it up with them?

Also to be clear, are you saying you don't experience a crash if you don't change the game rules?

**Comment by vakryvenik** [comment]
Yes -  if i don't change the game rules i don't have this crash.
BUT yeah, my bad, guys. I'm sorry.
I'm created new server on Sponge core with some plugins (with Nucleus to be clear). So I did the same steps as above but this time without "SimpleDimensions" mod (instead of command "/simpledimensions create" now i'm used "/world create" from Nucleus)...
...and all works correctly. =_=
Topic can be closed - problem not with TwilightForest but instead with "SimpleDimensions".
I apologize again for the inconvenience. =/
