### ISSUE TITLE
Help still no response, only bosses will spawn not the defenders like 

### ISSUE THREAD

**Issue by lujoco** [TeamTwilight/twilightforest#876]
Forge version: forge-1.7.10-10.13.4.1558-1.7.10-installer
Twilight Forest version: twilightforest-1.7.10-2.3.7
Link to crash log: no crash
Steps to reproduce:
1.
What I expected to happen: I expected that I would have to fight mobs before defeating the boss
What happened instead: No mobs before boss, only the boss spawns
For example when I went to defeat the snow queen , there was only the snow queen in the whole building no other mobs

**Comment by Tamaized** [comment]
Do not make a duplicate #844
