### ISSUE TITLE
Server crashes when enters portal (twilightforest-1.12.2-3.10.1013)

### ISSUE THREAD

**Issue by Adam-12100** [TeamTwilight/twilightforest#877]
Forge version: forge-1.12.2-14.23.5.2847-universal
Twilight Forest version: (twilightforest-1.12.2-3.10.1013)
Link to crash log: https://gist.github.com/Adam-12100/5325351bbcd6e9411d6ba1698b8540d9

I tried to read the crash report but I don't really understand.

Steps to reproduce:
1. When someone tries to enter the portal

What I expected to happen:
To explore the twilight forest

What happened instead:
The server crashes

Thank you

**Comment by bs2609** [comment]
The server was stopped because it fell too far behind.

You can change this behaviour with `max-tick-time` in your `server.properties` file. I would also check the logs to see if there are warnings about cascading worldgen.

See also #589, #371 and probably other similar issues.
