### ISSUE TITLE
Suggestion: Completed quest rams are ridable

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#878]
After you complete a quest ram's quest you should be able to ride it like a mount like a horse. Maybe it needs a saddle, maybe it doesn't, maybe it needs a totally diff item. Maybe it would have some special ability like speed or something or maybe bc the stripes make it really long then multiple players could ride the same ram, and the front player would control it or something

**Comment by TFGS-Soul** [comment]
Love it!

**Comment by Killer-Demon** [comment]
The way we envision and the Questing Ram currently exist don't line up with making him a mount. This, unfortunately, isn't something we're looking to add.
