### ISSUE TITLE
Paper server running TTF won't create TF dimension, breaking the mod

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [TeamTwilight/twilightforest#879]
Forge version: 14.23.5.2854
Twilight Forest version: 3.10.1013
Link to crash log: N/A

Steps to reproduce:

1. Download a paperclip.jar compatible with MC 1.12.2
2. Download the latest version of The Twilight Forest
3. Start the server, then stop it
4. Delete the world folders
5. Copy the TF .jar to the mods folder
6. Start the server again
7. Start Minecraft and connect to 127.0.0.1

What I expected to happen:
Upon first starting the server with The Twilight Forest mod installed, its dimension should be created.

What happened instead:
A Twilight Forest dimension is not created, breaking the mod.

Note: I plan to update my version of TTF, and will post the results here as a comment.

**Comment by M1CR0H4CK3R** [comment]
I just realized that the version I have IS that latest version. Wow, just wow.

**Comment by Tamaized** [comment]
As far as I can tell, paper doesn't support forge mods? This isn't our issue. Even if it actually is running forge then this would be on their end not ours.

**Comment by M1CR0H4CK3R** [comment]
Couldn't you run a check for paper's api, and support integration with paper if it finds it? I'm pretty sure that paper's api is open-source.

**Comment by M1CR0H4CK3R** [comment]
I don't want to do a spigot installation, and paper is drop-in-and-go, which I like a lot better.

**Comment by M1CR0H4CK3R** [comment]
Not to mention the significantly less memory footprint.

**Comment by Tamaized** [comment]
Why would we do that, that means we'd have to support every single server software out there. This is not feasible nor is it sane by any means. This is not our problem.
