### ISSUE TITLE
It is possible to walk into Thorns and 'suffocate'

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#88]
Forge version: 13.20.0.2315
Twilight Forest version: 2.4.0.42

Steps to reproduce:
1. Walk straight into Thorns

What I expected to happen: Thorns is a solid block and would stop the player (along with contact damage)

What happened instead: The player is able to walk a small distance into Thorns, displaying the suffocating screen. This may be a transparent block issue as the player still stops at the collision box

EDIT: As mentioned by ThemInspectors, Firefly Jar is also affected by this. Further testing on other blocks also shows that Block of Knightmetal is also affected (Tested in Twilight Forest Version 2.4.0.91)

**Comment by ThemInspectors** [comment]
I think it also happens with the firefly jar.
