### ISSUE TITLE
efficiency doesn't affect aurora blocks

### ISSUE THREAD

**Issue by Megalodab** [TeamTwilight/twilightforest#880]
Forge version: 1.12.2 - 14.23.2838
Twilight Forest version: Twilight Forest - MC 1.12.2 - 3.10.1013

Steps to reproduce:
1. try to break aurora blocks with an unenchanted pickaxe and an efficiency pickaxe, compare times

What I expected to happen: efficiency makes it go faster

What happened instead: its about the same amt of time, or maybe its too small i didnt recognize

**Comment by GizmoTheMoonPig** [comment]
I made it so the pickaxe is effective against aurora blocks, so efficiency should work with them now

**Comment by Megalodab** [comment]
> 
> 
> I made it so the pickaxe is effective against aurora blocks, so efficiency should work with them now

Thanks guys for still going thru bug reports even those that I submitted a yr ago <3
