### ISSUE TITLE
 Version question, trophy suggestion

### ISSUE THREAD

**Issue by VzeusV** [TeamTwilight/twilightforest#882]
Sorry for that question but I wanted to ask if the mod will still be updated to 1.12.2 or just ahead?
I would like to suggest changing the trophies to the mod, replacing the heads with bodies like the ghost. I think cool heads like trophies, but miniatures are much cooler.
Or maybe a way to keep both types to please both fans.

I love this mod, it has to be fixed in all modpack ..

**Comment by Andromander** [comment]
Supported versions will be whatever the latest version is, so 1.12.2 is no longer supported as of writing this.
Trophies are likely to stay as they are.
