### ISSUE TITLE
{SUGGESTION} Block and Chain modifications? Also, Discord problems.

### ISSUE THREAD

**Issue by TotallyRealReimu** [TeamTwilight/twilightforest#888]
First off, the Block and Chain feels really weird. I think it should have more reach because it's a flail. It adds more depth to the combat, as you can space out your fights more while the cooldown means less DPS and a little more strategy, adding a bit of spice to the fights you take part in. As for the Discord thing, I messed up; I said I'd continue to suggest what I'm suggesting here on it, and I admit I am entirely in the wrong with that, but one of the staff took it so poorly. Long story short, I said they should be nicer, they said they "don't sugar coat things", and when I suggested the difference between being a bit rude and being more straightforward, they straight up said they didn't care. I figured I couldn't do much more and ended it with a sarcastic remark, and apparently this is enough to get me banned! As far as I'm concerned, the second punishment isn't being banned. I had been kicked for trying to tell them off the first time, and after figuring I'd end it off with a pinch of my dry humor I'm prevented from joining entirely. Is being sarcastic bannable now? I bet they're gonna delete this post to hide my side on the matter...don't take this part of it as the main point of this post, it was an after point. I just really want the Block and Chain to be more like a flail.

**Comment by TotallyRealReimu** [comment]
Actually, while we're add it, if it gets a range boost maybe you can throw it like the block and chain goblins do?

**Comment by Tamaized** [comment]
Use this issue tracker for serious issues/suggestions. Trolling isn't appreciated.

**Comment by TotallyRealReimu** [comment]
> Use this issue tracker for serious issues/suggestions. Trolling isn't appreciated.

...I'm not trolling? This is a serious issue, in fact YOU were the person who did this

**Comment by Tamaized** [comment]
#892
