### ISSUE TITLE
Winter Wolf Bug

### ISSUE THREAD

**Issue by ghost** [TeamTwilight/twilightforest#89]
Forge version: 13.20.0.2315
Twilight Forest version: 2.4.0.42
https://www.youtube.com/watch?v=s1bDUJPyuE8

The Winter Wolf doesn't "shoot" its snow breath. There are also no particles showing.
It also doesn't do it when it's outside a minecart, it just follows you and melee attacks you

**Comment by Tamaized** [comment]
It seems the breath attack does indeed activate but does no damage right now, the particle issue was fixed in 20ed85fb7eae359f70d782058cfb433b49c21b39

**Comment by Tamaized** [comment]
Also based on the 1.7.10 branch it seems it never did damage? Hmm..
https://github.com/TeamTwilight/twilightforest/blob/1.7.10/src/main/java/twilightforest/entity/EntityTFWinterWolf.java#L147-L153

**Comment by Benimatic** [comment]
Interesting. I wonder what happened there.
