### ISSUE TITLE
[Suggestion] Use Optifine CTM instead of CTM mod in 1.15.2

### ISSUE THREAD

**Issue by GeForceLegend** [TeamTwilight/twilightforest#898]
Add code of CTM mod into models will cause model error in 1.15.2. And CTM mod doesn't support 1.15. Optifine CTM can do the same thing but need a little work.
This is an example of Optifine CTM, affects fiery block.
(This resource pack cannot use directly, but it can be placed in other packs)
[CTM_Fiery_Block.zip](https://github.com/TeamTwilight/twilightforest/files/4773989/CTM_Fiery_Block.zip)

**Comment by Tamaized** [comment]
No

**Comment by 3TUSK** [comment]
> CTM mod doesn't support 1.15

False, there has been test builds already.

**Comment by Tamaized** [comment]
Not to mention @Drullkus, one of our devs, is also a dev for ctm (and chisel for that matter).

**Comment by 3TUSK** [comment]
Also, the more important factor is that Twilight Forest for Minecraft 1.15.2 is not even qualified for alpha testing stage. There are even missing blocks. The dimension is totally broken.   
The current focus of the dev team, AFAIK, is to get all blocks/items/entities fixed first, then take care of the world gen rewrite from ground up. Mod compat is very very low priority to my knowledge.

**Comment by GeForceLegend** [comment]
> 
> 
> Also, the more important factor is that Twilight Forest for Minecraft 1.15.2 is not even qualified for alpha testing stage. There are even missing blocks. The dimension is totally broken.
> The current focus of the dev team, AFAIK, is to get all blocks/items/entities fixed first, then take care of the world gen rewrite from ground up. Mod compat is very very low priority to my knowledge.

But using CTM code in model files will cause **MODEL ERROR** (full block with black and purple texture) if CTM is not installed, and after only deleting CTM codes, models will work correctly

**Comment by Tamaized** [comment]
Haven't you considered that both mods are being worked on. It's not complete.

**Comment by Drullkus** [comment]
Twilight Forest will use the CTMod, there will be no change of position on this topic.
