### ISSUE TITLE
Cant break blocks, how am i meant to make the portal?

### ISSUE THREAD

**Issue by xDemocx** [TeamTwilight/twilightforest#899]
Forge version: 
Twilight Forest version: Forge 1.12.2
I cant break blocks or anything, not even in creative mode, how am i meant to make the portal?

**Comment by willtarax** [comment]
That sounds like you are still within spawn of the server. Move away and try again. Twilight Forest is not keeping you from being able to break blocks...

**Comment by Andromander** [comment]
This doesn't sound like a bug in this mod. Closing as not much info was provided.
