### ISSUE TITLE
Hexxit crashes on launch. TwilightForest is the reason

### ISSUE THREAD

**Issue by JACKO4590** [TeamTwilight/twilightforest#900]
Forge version: 14.23.5.2854
Twilight Forest version: (this is the build number) 10/29/19 | Twilight Forest - MC 1.12.2 - 3.10.1013
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)
 [gist](https://gist.github.com/JACKO4590/b7e3a94da3be0cb84f035bbd37bcfc56)
Steps to reproduce:
1. installed fresh Twitch app, Miinecraft and Hexxit Updated 
2. then clicked launched

What I expected to happen: The game to launch menu

What happened instead: The game comes up with error
https://cdn.discordapp.com/attachments/596615602483888138/726334164344766494/Capture.PNG

**Comment by Andromander** [comment]
"Link to crash log: (please use a paste site such as gist, do not attach the .txt or paste the log inline)". We need one, otherwise we can't tell what's happening

**Comment by JACKO4590** [comment]
I thought that is what https://gist.github.com/JACKO4590/b7e3a94da3be0cb84f035bbd37bcfc56 is. Is this what you need?

**Comment by Andromander** [comment]
Ah, did not see that. 

It appears that is issue has been reported here before, but is caused by Optifine. I don't use it myself, but the fix is either to update or change version.

**Comment by JACKO4590** [comment]
omg yes looks like removing that makes it work. Ill post on the hexxit discord as well and at lease now I can play. Thank you
