### ISSUE TITLE
Suggestion: Boss + Biome concepts (Sphynx and Desert Biome?)

### ISSUE THREAD

**Issue by TFGS-Soul** [TeamTwilight/twilightforest#901]
Hi! I was totally inspired by the Twilight Forest and the Dev team seems really open-minded which I appreciate! Not that I want to put more work on your plate but I do have some fun ideas to throw out that I think might be interesting ideas to explore if you plan to expand past the world you already have built.
As it stands there is a savannah biome but no desert biome. I think a Desert boss/temple would be very cool! you could incorporate it as the origin for glass swords, theme the structure around colored glass? I was envisioning a boss or enemy that made use of a mirage mechanic? There do seem to be a few different reappearing blocks already. Possibly a fountain of youth that you can fill bottles with? Causing buffs and potion effects? I think some kind of Sphynx boss somehow inspired by parrots or cats might be fun! Both me and my sister love the Twilight Forest, and it was our first mod. I want to contribute my ideas to this community! I hope to hear back, even if its just to say you aren't looking for more ideas right now. Thanks for hearing me out!

**Comment by Tamaized** [comment]
Deserts and Forests dont mix
