### ISSUE TITLE
Twilight Forest crashing!!

### ISSUE THREAD

**Issue by nosnowowie93347** [TeamTwilight/twilightforest#903]
My Twilight Forest mod keeps crashing when I go to the Twilight Dimension!!

Here's the log
[crash-2020-07-15_17.16.27-server.txt](https://github.com/TeamTwilight/twilightforest/files/4928615/crash-2020-07-15_17.16.27-server.txt)

**Comment by Tamaized** [comment]
1.7.10 is no longer supported.

**Comment by nosnowowie93347** [comment]
Why? And so what? Please just help me fix the issue

**Comment by nosnowowie93347** [comment]
I can't update to 1.16 i have other mods

**Comment by Tamaized** [comment]
Sorry that codebase is too ancient I have no idea.

**Comment by nosnowowie93347** [comment]
welp. This is why Terraria is so much better. It never crashes

**Comment by Andromander** [comment]
T...Terraria is a game, not a Minecraft mod made by (at that point in time) singular person not getting money from it.
