### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by shane-create** [TeamTwilight/twilightforest#904]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen: that it would work

What happened instead: it said that the version of twillight forest was to old for version 1.16.1

**Comment by Tamaized** [comment]
Wat

**Comment by corgiblu** [comment]
I believe they're trying to run the mod on MC 1.16.

Not actually an issue. Just someone who doesn't understand how mods work.
