### ISSUE TITLE
Ghast removed at spawn + spam errors

### ISSUE THREAD

**Issue by avescarelo** [TeamTwilight/twilightforest#906]
forge-1.12.2-14.23.5.2854
twilightforest-1.12.2-3.10.1013-universal

All mods: (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Animania, AppleCore, Auto Network Lib, AutoRegLib, Baubles, Bewitchment, Cases, Ceiling Torch, Chameleon, Chunk Pregenerator, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Decocraft, Divine Favor, DupeFix Project, Farseek, FoamFix, FoamFixCore, Gravestone Mod, Improved Mobs, LibraryEx, Login Shield, NetherEx, Ore Veins, OreLib Support Mod, Patchouli, Quark, Realistic Terrain Generation, Restricted Portals, Serene Seasons, Shadowfacts' Forgelin, Spice of Life: Carrot Edition, SpongeForge, Storage Drawers, Streams, TenshiLib, The Twilight Forest, TreeCapitator, Wearable Backpacks, bspkrsCore

1. Ghast in the tower when spawning appears as an errored entity and is removed by the forge 
(the setting for deleting errored entities is enabled in the forge settings)

2. And also spam errors in server logs

What I expected to happen:
![image](https://user-images.githubusercontent.com/26678843/89063684-5049cb00-d371-11ea-97a8-6d00b18c6c51.png)

**Comment by Andromander** [comment]
The Ur-Ghast being removed is a problem on Sponge's side due to it removing entities that are too big by default. The allowed size can be configured to be bigger or disabled.
As for the log spam, that appears to have been resolved.
