### ISSUE TITLE
[1.16] World Gen Issues

### ISSUE THREAD

**Issue by Tamaized** [TeamTwilight/twilightforest#908]
**Post all issues regarding world generation, the dimension itself, and trees here.**

Checklist will be updated as issues come in.

### Worldgen Issues

- [x] Floating Firefly blocks
- [x] Canopy Trees don't properly generate
- [x] Twilight Leaves decay even when valid to not decay
- [x] Structures do not generate
- [x] Trees do not generate

**Comment by EnderConstructor** [comment]
- [x] High number of poppies,dandelions,pumpkins and clovers
- [x] Core blocks from special tree spacings are rotated in the wrong way
- [x] Upon bonemealing a miners tree, the tree grows in its full size but the bottom block of the tree breaks and drops the miners sapling and the tree starts decaying
- [x] Moonworm queen crashes the game upon being used

**Comment by EnderConstructor** [comment]
- [x] Robust twilight oaks arent generated correctly, similiar to canopy trees

**Comment by EnderConstructor** [comment]
- [x] TF portal issue, upon coming back to the overworld from twilight forest the portal spawns underground instead of the original place the portal was created at

**Comment by Jumpscare314** [comment]
- [x] the following biomes aren't generating:

twilightforest:dark_forest
twilightforest:dark_forest_center
twilightforest:deep_mushroom_forest
twilightforest:enchanted_forest
twilightforest:fire_swamp
twilightforest:highlands_center
twilightforest:snowy_forest
twilightforest:spooky_forest
twilightforest:thornlands
twilightforest:twilight_clearing
twilightforest:twilight_forest
twilightforest:twilight_glacier
twilightforest:twilight_highlands
twilightforest:twilight_lake
twilightforest:twilight_stream
twilightforest:twilight_swamp

**Comment by marcforgotten** [comment]
hello I'm not great at coding but if you need someone to test it as you update it I'm down to help

**Comment by Tamaized** [comment]
@EnderConstructor a lot of the issues you posted here don't relate to world gen at all, can you split those into their own individual issues. Add crash reports for the ones that crash as well.
