### ISSUE TITLE
Maze boss not fenced-in

### ISSUE THREAD

**Issue by Matti-Koopa** [TeamTwilight/twilightforest#91]
What I expected to happen:
The boss to be fenced-in with wooden fences you have to destroy before the battle

What happened instead:
There were no fences and the boss was loose in the maze and attacked me quite a few corners away from the final room.

![2017-06-21_16 22 46](https://user-images.githubusercontent.com/10476794/27421462-cf985140-572a-11e7-8bc0-5b3e5357f804.png)

**Comment by theishiopian** [comment]
This happened to me as well.
