### ISSUE TITLE
New to modding, having trouble with the forge version required to run this mod.

### ISSUE THREAD

**Issue by sun1z09** [TeamTwilight/twilightforest#910]
Forge version: 
Twilight Forest version: 1.7.2-2.2.3
Forge version: 1.7.2

Steps to reproduce:
1.  download forge 1.7.2
2. run a 1.7.2 version of minecraft, then the forge iteration.

What I expected to happen:
The Minecraft launcher closes and Forge boots up, like expected.

What happened instead:
The launcher closed and nothing else happens.

Note: I'm aware that ideally I should be approaching Forge with this issue, not you guys. However they explicitly said in their EAQ that they do not provide support for legacy versions of Forge, so I'm hoping you can help me instead.

**Comment by Drullkus** [comment]
Is there a reason why you're on 1.7.2? Why not 1.7.10? Please post your crashlog too, you will find it in the minecraft directory

**Comment by sun1z09** [comment]
I tried with 1.7.2 because I saw that was the latest version of the forest released, however 1.7.10 worked just fine. I guess such an old version didn't really gel with the newer Minecraft... Anyway it's good to know I found a community here :)

**Comment by Drullkus** [comment]
The latest version of Twilight Forest is 1.12. Where are you downloading this mod??

**Comment by Tamaized** [comment]
Curseforge displays latest as the latest file that was uploaded, which happens to be one of the legacy recovered files, the 1.7.2 file.

The latest mc version for the mod is 1.12, which curse also displays.
