### ISSUE TITLE
Blank Texture for twilight doors

### ISSUE THREAD

**Issue by Jennifercutixx** [TeamTwilight/twilightforest#911]
Don't know if this problem has come up in the issues before but i'm getting no textures for the twilight doors when in hand. Do'nt know if its an issue or just no textures have been added.
![Untitled](https://user-images.githubusercontent.com/60190810/89199282-3e9d3900-d5a6-11ea-9898-5c36cf460c39.png)
Any help would be nice or if a issue hope it gets fixed. Thank you ^^

**Comment by Tamaized** [comment]
Duplicate #711

**Comment by Jennifercutixx** [comment]
thank you for letting me know
