### ISSUE TITLE
boss progression can break with things that allowed you to teleport through walls

### ISSUE THREAD

**Issue by Discusser** [TeamTwilight/twilightforest#914]
Forge version: 14.23.5.2847
Twilight Forest version: 3.10.1013
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. install a mod that has a tool that lets you teleport through walls. I used The Ender sword from Ender IO with the travel sword.

What I expected to happen: Ur-Ghast wouldn't be killable, you wouldn't be able to teleport through forcefields, you wouldn't be able to open chests blocked by Giant Obsidian in the Troll Caves, etc..

What happened instead:
I killed the Ur-Ghast while there was the block protection and mob protection (which made me redo the dark forest mazes and the boss fight). I teleported through forcefields in the final castle and killed those mobs in the boxes. I opened the chest blocked by Giant Obsidian without a giant pickaxe.

**Comment by Tamaized** [comment]
It's not our job to police what users do with other mods, just like using flight.
