### ISSUE TITLE
suffication damage for carminite ghastlings

### ISSUE THREAD

**Issue by Jumpscare314** [TeamTwilight/twilightforest#915]
Forge version: 1.16.1-4.0.168
Twilight Forest version: 1.16.1-4.0.168
Link to crash log: there isn't a crash

Steps to reproduce:
1. make a 2 block high room
2. spawn a carminite ghastling (also works with higher rooms but only when they fly agains the ceiling)

What I expected to happen: the ghastling flies around

What happened instead: the ghastling starts to take suffication damage just for having a block above its head

**Comment by Tamaized** [comment]
Lol suicidal ghastlings
