### ISSUE TITLE
[1.12.2 Suggestion] Charm items should be charm baubles

### ISSUE THREAD

**Issue by vizthex123** [TeamTwilight/twilightforest#916]
Title. It's literally in their name.

Plus, very few mods use that slot so it would help populate it.

**Comment by Tamaized** [comment]
Pretty sure they currently can go into any bauble slot? I might be wrong.
Or do you mean strictly have them be the charm slot only.

**Comment by vizthex123** [comment]
Yes, make them only go into Charm slots.

They work with any slots right now, and I think it's just odd since they're called "charm of X"

**Comment by Andromander** [comment]
Just as a note: since 1.16 no longer has Baubles and Curios appears to be the replacement mod, it would be best to look into that. Whether Curios has similar slot names, that'll have to be a part of that look.

**Comment by GizmoTheMoonPig** [comment]
closing as curios compat was added in later versions, see #1082. Since we don't support 1.12 anymore that's all that will be done in regard to this.
