### ISSUE TITLE
Boss mobs won't spawn. Spawner just sits there, idle. Placing a spawner from the creative menu spawns the boss normally.

### ISSUE THREAD

**Issue by guessjuze** [TeamTwilight/twilightforest#917]
Forge version: 14.23.5.2847
Twilight Forest version: 3.10.1013

Boss mobs won't spawn. I'm quite clueless as to why. The spawner just sits there, not doing anything, and nothing we did would make the boss spawn. The only way I found to spawn bosses was just to get the spawner from the creative inventory, and as soon as I placed it down, it would disappear and the boss would spawn. Something must be wrong with the generated spawners. Unfortunately, there's literally nothing in the logs, so sending them would be useless.
I looked into it a bit, and as far as I could gather, the spawners check if a player is in range, and if so, spawn the boss. So I assume something must be interfering with this process, but I don't understand what.
Obviously I can't just ignore the problem, because while I can just give myself a spawner, other people in the server can't as they don't have creative mode access. And me doing it for them every time is not exactly manageable.
The only thing I can come up with that could possibly help you identify what could be causing this is giving you a list of the mods in my pack, hoping it helps since you obviously know your mod better than I do. 

Here's the modlist: https://pastebin.com/5CR1Bpq8

**Comment by Tamaized** [comment]
Solved in discord, issue was tiquality
