### ISSUE TITLE
Giant's Sword does not have increased range when attempting to attack mobs

### ISSUE THREAD

**Issue by bleh1245** [TeamTwilight/twilightforest#919]
Forge version: 1.12.2-forge-14.23.5.2854
Twilight Forest version: 3.10.1013

Steps to reproduce:
1. Just attempt to attack a mob with a Giant's Sword slightly further away than you normally would with a sword.

What I expected to happen: I hit the mob and deal damage.

What happened instead: I didn't.

Note that this only applies to hitting mobs. Mining blocks from further away still seems to work just fine.

**Comment by Drullkus** [comment]
Item attributes make this a lot easier to pull off, I could look into it for sure

**Comment by GizmoTheMoonPig** [comment]
just tested this and it seems to work on 1.16 builds, if it doesnt work for someone else please reopen this or make a new issue
