### ISSUE TITLE
(Suggestion) "Frosted" status effect

### ISSUE THREAD

**Issue by bleh1245** [TeamTwilight/twilightforest#923]
As it currently stands, the Frosted status effect simply a copy of the slowness effect, with the only difference being aesthetic. I feel like being inflicted with this status effect should be more consequential, especially since one of the causes of the effect is tied to progression.

Here're some possible additional effect ideas I had for the Frosted status, in order of how fitting I feel they'd be:

> 1. Weakness effect (Always equivalent to Weakness I, regardless of Frosted level) or reduced attack damage
>
> 2. Mining Fatigue effect
>
> 3. Gradual damage (Maybe half a heart for every 200 ticks with the length of time halved for every level of Frosted?)
>
> 4. Reduced full hunger health regeneration
>
> 5. Gradual hunger loss (increases food exhaustion by 0.001 × level per game tick)
>
> 6. Blindness effect

Now I'm not suggesting ALL of these should be added to Frosted, as doing such would be brutal when inflicted with Frosted III; I'm just suggesting SOME of, or maybe even just one of, these possible additions be added to Frosted.

**Comment by Tamaized** [comment]
We recently reworked the frosted effect to include some of these effects.
