### ISSUE TITLE
Unable to launch on the minecraft server.

### ISSUE THREAD

**Issue by kuretoshi** [TeamTwilight/twilightforest#924]
Forge version: 1.16.1-32.0.108
Twilight Forest version: 1.16.1-4.0.174
Link to crash log: https://gist.github.com/kuretoshi/40a52cca847f11d96e6569953f3ce294

Steps to reproduce:
1. Running on a ubuntu server.(Can be reproduced on Windows.)
2.It happens when you put the twilightforest in the mods folder and start the server.

What I expected to happen:
I need to activate it.

What happened instead:
I can't start up.

**Comment by Tamaized** [comment]
Fixed in 28a8cf6a10a79bec737f856a38996713700dba7b
