### ISSUE TITLE
[1.16.2] Incorrect Tooltips, Advancement name, obtainable unique enchantments, & another missing texture

### ISSUE THREAD

**Issue by ThousandFields** [TeamTwilight/twilightforest#927]
Forge version: 33.0.5

All tooltips are incorrect (instead of Fiery helmet, chestplate, and leggings showing "Burns attackers", "item.twilightforest.fiery_leggings.tooltip" appears instead).

TF portal creation advancement has the same problem, but with the name.

"enchantment.twilightforest.fire_react" and "enchantment.twilightforest.chill_aura" are the Enchanted Books for the Fiery armour and Yeti armour unique effects, and are obtainable in survival (at least, certain in Librarian Villager trading).

The advancement screen background for TF is missing its texture.

**Comment by GizmoTheMoonPig** [comment]
all of these are now fixed from what I can tell. If any of these things are still happening, reopen the issue and let me know :)
