### ISSUE TITLE
[1.16.2] No data fixer registered

### ISSUE THREAD

**Issue by kuretoshi** [TeamTwilight/twilightforest#928]
Forge version: 1.16.2-33.0.5
Twilight Forest version: 4.0.183
Link to crash log: https://gist.github.com/kuretoshi/db02dbbe6327312dc8f8c747838f3524

An error occurs if the data fixer related to the twilight forest is not registered when the forge server is started.

**Comment by Tamaized** [comment]
Moving the 2nd issue to #908
