### ISSUE TITLE
Authors Cont.

### ISSUE THREAD

**Issue by AlexTrified** [TeamTwilight/twilightforest#930]
Forge version: Yes. 
![Screenshot_20200819-020615](https://user-images.githubusercontent.com/69915087/90664222-ac896780-e218-11ea-92c8-f2a996c595e9.png)
in this screenshot of the comments, before they were disabled, you can see a specific author being as rude as possible in a repy to a post which i believe said "why aren't they updating older versions anymore" the author had almost no cause to be this rude and pretentious, but yet were anyway, because authority power.

**Comment by Tamaized** [comment]
This is not the correct place for this.

But I'll answer you anyway.

You spamming does no good. Comments were temporarily disabled to prevent this until things calmed down seeing how curse has yet to implement a block feature for projects.

As to why the comment I dunno maybe seeing the same thing repeated over and over and over and over and finally one with a tiny bit of attitude on it causes somebody to snap over their hobby project which they wish they could work on with love but slowly realize it's becoming more of a chore and straight up job to maintain or at least that's how the user base treats us, at least the vocal ones. Funny that guys question was even answered only a few comments down.

Look I've already tried to remove it and curse being curse doesn't always work right and doesn't actually remove comments sometimes mixed in with the issue of you simply cannot remove your own comments creates a mess. Infact you made fun of this action with another snarky comment. You're no better.

You prolonging this just makes things worse. I'm stressed as it is this doesn't help.

Furthermore you didn't even ask a question you just made a snarky comment yourself and now you're demanding an answer to what, a statement? 

Right anyway this is an issue tracker not a drama generator.
