### ISSUE TITLE
[1.16.2] Armour don't come with enchantments when crafted, Uncrafting Table incorrect item render, & Deer drop Cooked Venison when killed

### ISSUE THREAD

**Issue by ThousandFields** [TeamTwilight/twilightforest#933]
Forge version: 33.0.5
Twilight Forest version: 4.0.187

None of the TF armour get enchantments when crafted, even though it shows they do in JEI and the creative menu.

Uncrafting Table uses the wrong item render, looking like this:
![image](https://user-images.githubusercontent.com/58322110/90857508-46086480-e352-11ea-9295-2549b26025f8.png)

Deer drop Cooked Venison instead of Raw when killed without fire.

**Comment by Tamaized** [comment]
Just for future reference, let's try to split each individual issue into their own issues, it helps with management.
