### ISSUE TITLE
[1.16.2] Stone Stairs, chisel blocks not usable in Stone cutter

### ISSUE THREAD

**Issue by BedrockLegends** [TeamTwilight/twilightforest#935]
Forge version: 33.0.20
Twilight Forest version: (4.0.187)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. None of the stairs or Chisel stone blocks are usable in a stonecutter like other mods have by default, as this is a vanilla feature that most mods take advantage of

What I expected to happen:
to see if your Stone Stairs, Chisel Stone and whatever else that is stone could be added to Stone cutter

![2020-08-23_19 04 14](https://user-images.githubusercontent.com/48525410/90992178-927eba80-e573-11ea-82e6-9bafecb2f86c.png)
![2020-08-23_19 04 18](https://user-images.githubusercontent.com/48525410/90992179-93afe780-e573-11ea-927f-02cf212d57b3.png)
![2020-08-23_19 04 29](https://user-images.githubusercontent.com/48525410/90992180-94487e00-e573-11ea-9411-2847f06f0bd6.png)
![2020-08-23_19 04 52](https://user-images.githubusercontent.com/48525410/90992181-94e11480-e573-11ea-8eed-254b7026a1a9.png)

**Comment by Drullkus** [comment]
Intended, you will not be able to make Nagastone variants from stone bricks or cobble.
