### ISSUE TITLE
it just crashes when joining world

### ISSUE THREAD

**Issue by IncimathCal** [TeamTwilight/twilightforest#937]
Forge version: 33.0.21
Twilight Forest version: newest
problem:the title

**Comment by Andromander** [comment]
Cool story, but what crash?

**Comment by Tamaized** [comment]
Please follow the issue guidelines, provide a gist or any pastebin like service link to the crash log. This will remain closed until done so.

**Comment by IncimathCal** [comment]
sorry I am just back

**Comment by IncimathCal** [comment]
mc ver.:1.16.2

**Comment by IncimathCal** [comment]
it crashes when joining world then it started saving chunks

**Comment by IncimathCal** [comment]
pls come back

**Comment by bs2609** [comment]
> provide a gist or any pastebin like service link to the crash log

Please just do this, don't spam comments, thanks.

**Comment by IncimathCal** [comment]
oh
