### ISSUE TITLE
Add more Tags for configuring

### ISSUE THREAD

**Issue by Drullkus** [TeamTwilight/twilightforest#938]
- Twilight Portal
  - [x] Activation Item
    - Inherit `#forge:gems/diamond`
  - [x] Fluid Blocks
    - Inherit `#minecraft:fluids/water.json`
    - If we can use first entry in list as a default, all the better
  - [x] Edge Blocks
    - Normally Grass/Dirt/Course Dirt/Podzol/Mycel
    - (Additional testing if they're full-cubed)
  - [x] Decoration Blocks
    - Normally all flora blocks
    - Check if sugarcane qualifies. It should be able to be added.
- [x] Carminite Reactors
  - Copy from `minecraft:wither_immune`, but do not inherit `#minecraft:wither_immune` as part of list
- Ore Magnet Blocks
  - Used for Ore Magnet and Mining Tree
  - [x] Stone Ores - these get replaced with stone
  - [x] Netherrack Ores - these get replaced with netherrack
  - [x] Endstone Ores - these get replaced with endstone
  - Is there a way we could just set the resource path to be `/tags/blocks/magnet/<namespace>/<block to replace with>.json`?
- [x] Fire Jet fuel
  - Could we reference lava as blocks?
  - If not, then fuel lists for both fluids and blocks?
- [x] Trophy Pedestal Blocks
  - All boss trophies
- I considered the Dimension Loading Screen items, but I may rather gate specific icons behind progression to give the player further variety as they delve into the mod.
- [x] Add giant obsidian to Ender Dragon immunity tags

**Comment by Drullkus** [comment]
If anyone has suggestions for more tags to add, that'd be appreciated

**Comment by Tamaized** [comment]
Closing for the sake of completeness. Commits that add more tags can still reference this.
