### ISSUE TITLE
crashes 1.16

### ISSUE THREAD

**Issue by IncimathCal** [TeamTwilight/twilightforest#939]
Sorry for the last time 
Forge version: 33.0.22
Twilight Forest version:4.0.195
Link to crash log: https://paste.ee/p/bdkpw
Steps to reproduce:
1. enter game
2.press the "mods" button
3.press "twilight forest"

What I expected to happen:show the mod info

What happened instead:the game crashed

**Comment by Drullkus** [comment]
Do you have a firewall on your computer?

Is this also happening with other Minecraft mods? Try using a different 1.16.2 mod for Forge and see if it makes the same crash.

**Comment by IncimathCal** [comment]
no it does not I tried jei and a lot of other mods

**Comment by IncimathCal** [comment]
and I am a Mac, btw

**Comment by IncimathCal** [comment]
stops crashing in 4.0.197. your mod is great. bye!!
