### ISSUE TITLE
crash when using the magical map

### ISSUE THREAD

**Issue by IncimathCal** [TeamTwilight/twilightforest#940]
Forge version: 32.0.22
Twilight Forest version: 4.0.195
Link to crash log: https://paste.ee/p/osEJi

Steps to reproduce:
1. use the map

What I expected to happen:generate the map

What happened instead:crash
mod is extremely good, like it.
keep going!!!!!!!!!!!

**Comment by Tamaized** [comment]
This log doesn't relate to the magic map at all, I think you linked the wrong one

**Comment by IncimathCal** [comment]
I didn't

**Comment by Tamaized** [comment]
Yet the crash log you posted is the same trace as #939 
ModListScreen

**Comment by IncimathCal** [comment]
oh sorry don't close issue I update tomorrow with the true one
sorry for my bad English,i am Chinese
my grammar Is not good
