### ISSUE TITLE
broken advancements

### ISSUE THREAD

**Issue by xluuk2** [TeamTwilight/twilightforest#941]
![Schermopname (443)](https://user-images.githubusercontent.com/70483982/91665772-5f4ea500-eaf8-11ea-8b2e-c7d9777548b8.png)
when i deleted all my advancements at the final boss tower that broke my advencement so coudnt get any advancements anymore

**Comment by Tamaized** [comment]
..?

**Comment by Andromander** [comment]
You should only remove advancements by the advancement command unless you know what you are doing. This is not a bug with TF.
