### ISSUE TITLE
TF Trees don't grow from saplings

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [TeamTwilight/twilightforest#943]
Forge version: 33.0.23
Twilight Forest version: 4.0.203

Saplings wont grow into trees, no matter how much they are bonemealed or if the randomtickspeed is set really high.

**Comment by Andromander** [comment]
Resolved in https://github.com/TeamTwilight/twilightforest/commit/526589b320ca4952fa73a4f6497638d22b09a292
