### ISSUE TITLE
(1.16.2 Bug) Yeti Helmet enchantment glint is broken

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#948]
Forge version: 
Twilight Forest version: twilightforest-1.16.2-4.0.214-universal

A simple fix for this would be to change the Yeti Helmet texture to be 16x16, so the bugged custom model is not needed.

**Comment by Tamaized** [comment]
bbf4a5c364179ae5d2452d3b3ab34f1fa7cdff80
