### ISSUE TITLE
(1.16.2 Bug) Hydra body model disappears sometimes, often when growing more heads

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#949]
Forge version: 
Twilight Forest version: twilightforest-1.16.2-4.0.214-universal

Steps to reproduce:
1. Summon a Hydra with a spawn egg
2. Kill one of the heads

**Comment by Tamaized** [comment]
837d79e8bdee067350701231b8c03e4ee802493d
