### ISSUE TITLE
(1.16.2 Bug) Snow Queen ice shield and Naga segments lag behind with choppy animation

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#952]
Forge version: 
Twilight Forest version: twilightforest-1.16.2-4.0.214-universal

**Comment by Goredeus** [comment]
This also happens with the naga segments

**Comment by Andromander** [comment]
It'll be happening to all Entities with a "multipart". Other examples would likely include Hydra, Block and Chain Goblin, and I suspect that the Block and Chain is affected.

**Comment by Tamaized** [comment]
Related: #1002 #949

**Comment by Tamaized** [comment]
837d79e8bdee067350701231b8c03e4ee802493d
