### ISSUE TITLE
(1.16.2 Bug) Fiery Items are not emissive

### ISSUE THREAD

**Issue by SeaOfPixels** [TeamTwilight/twilightforest#955]
Forge version: 
Twilight Forest version: twilightforest-1.16.2-4.0.214-universal

NOTE: **Only fiery items aren't emissive; the fiery armor model renders correctly.**

**Comment by Andromander** [comment]
I believe Fiery Items had emissive textures with CTM. Might be possible to make them emissive without it, or just wait until compat is looked at.

**Comment by Tamaized** [comment]
I can do it myself easily

**Comment by Tamaized** [comment]
19b886be8cbd00584a285d66372607fe3083f560
