### ISSUE TITLE
(1.16.2 Bug) Skeleton drops gear with broken twilight forest enchantments

### ISSUE THREAD

**Issue by bigdious** [TeamTwilight/twilightforest#959]
Forge version: 33.0.37
Twilight Forest version: 4.0.203-universal

Steps to reproduce:
1.  Kill a skeleton that has enchanted armor and was spawned from a monster spawner

What I expected to happen: It drops a leather chestplate with normal enchants

What happened instead: The leather chestplate it dropped had Protection II, enchantment.twilightforest.chill_aura and enchantment.twilightforest.fire_react.

**Comment by GizmoTheMoonPig** [comment]
forgot to mention I fixed this about a week ago with my bugfix commit. The books shouldn't appear on armor or in librarian trades anymore. If they do, please reopen the issue.
