### ISSUE TITLE
Spawned Into Twilight Forest Surrounded by Acid Rain on All Sides

### ISSUE THREAD

**Issue by Tybold** [TeamTwilight/twilightforest#966]
Forge version: 14.23.5.2847
Twilight Forest version: 3.10.1013
Link to crash log: 
N/A, but here's a link to a screenshot of my map
![twilight](https://user-images.githubusercontent.com/8304590/94852050-50a92580-03f7-11eb-8f9b-760dd90da766.png)

Steps to reproduce:
1. Create a Twilight Forest portal in the overworld (in my case it was a Project Ozone 3 "Garden of Glass" skyblock world) at X: -1195/Y: 86/Z: -6.364, on the seed -8601135849584893795
2. Upon entering you'll be in-between 2 Dark Towers, resulting in being surrounded on all sides by acid rain from the nearby Dark Forest biomes.

What I expected to happen:
Get to the Naga unhindered by biome hazards.
What happened instead:
Have to come up with a way to traverse the acid rain without dying.

**Comment by Tamaized** [comment]
That is.. very interesting

**Comment by Tamaized** [comment]
I'm going to close this as it's actually not possible to solve, it's just a really unfortunate occurrence with world gen.
