### ISSUE TITLE
Dying in the forest glitches game cant move 

### ISSUE THREAD

**Issue by SmolBeans1** [TeamTwilight/twilightforest#967]
Forge version:  (SERVER: forge-1.12-14.21.1.2443    CLIENT: 1.12.2-forge-14.23.5.2854)

Twilight Forest version: (twilightforest-1.12.2-3.10.1013-universal)

Link to crash log: There isn't really a crash it more or less just becomes unplayable I guess?

Steps to reproduce:
1. I have these mods installed (twilightforest-1.12.2-3.10.1013-universal, Pam's+HarvestCraft+1.12.2zg, IronBackpacks-1.12.2-3.0.8-12,furniture-6.3.1-1.12.2 )
2. I turned the server on

 and connected to it 
3. I made the portal jumped in it and killed myself inside (Either through the command or just natural)

What I expected to happen:
I was hoping to respawn maybe and continue playing the game 

What happened instead:
Game glitches out, Can't move, and cant reconnect to the server

**Comment by Tamaized** [comment]
This sounds more like the server is still in the process of world generation which causes everything to stall until complete. You could use the phosphor mod to help speed this process up.

**Comment by Andromander** [comment]
This doesn't really sound like a bug on our end, and could potentially be world generation still processing. If this issue still persists, feel free to open this again.
