### ISSUE TITLE
JEI rendering issue with Fiery Ingot

### ISSUE THREAD

**Issue by xJon** [TeamTwilight/twilightforest#969]
Forge version: `14.23.5.2854`
Twilight Forest version: `3.11.1021`
Just Enough Items: `4.16.1.302`
(No Optifine installed)

Steps to reproduce:
1. Render `Fiery Ingot` in JEI alongside other items (e.g. search `ingot`)

What I expected to happen: Nothing

What happened instead: The other items appear darker / less vibrant in JEI

**_[> Example gif <](https://user-images.githubusercontent.com/8945347/95109130-d5bc7380-0744-11eb-8cab-943cac26e05f.gif)_**

**Comment by Tamaized** [comment]
Shouldn't be a problem anymore as we're using custom BakedModels now instead of raw OpenGL calls
