### ISSUE TITLE
(1.16.2 Bug) Game Always Crashes on opening a Magic Map.

### ISSUE THREAD

**Issue by Neboer** [TeamTwilight/twilightforest#970]
Forge version: 34.1.17
Twilight Forest version: 1.16.3-4.0.229
Link to crash log: https://gist.github.com/Neboer/e59c25492b317d5bc4436c75ca7f7360#file-gistfile1-txt
Game server will always crash when a player holding a Magic Map (magic_map) on his main hand.

**Comment by TheCurle** [comment]
This was fixed in 4.0.240, i believe.

**Comment by Tamaized** [comment]
fa3476dacb96f39f742b3c22375bdfbe7cb33f62
