### ISSUE TITLE
Can't Access the Highlands After Beating Hydra, Snow Queen, and Ur-Ghast

### ISSUE THREAD

**Issue by Markosmywords** [TeamTwilight/twilightforest#971]
Forge version: 1.12
Twilight Forest version: 1.12.2-3.11.1020
Link to crash log: It didn't crash?

Steps to reproduce:
1. Defeat the Hydra, Snow Queen, and Ur-Ghast.
2. Step into the Highlands.

What I expected to happen: The acid rain clears.

What happened instead: The acid rain did not clear.

**Comment by Zyian** [comment]
You need to get the Lamp of Cinders from the giant obsidian vaults in the Troll caves. Once you have the lamp the acid rain goes away

**Comment by noamgez** [comment]
zyian the lamp of cinders is for the thorns, not the acid rain

**Comment by Zyian** [comment]
Correct, the lamp is primarily for the thorns but the advancement, when combined with the both three bosses, is what truely clears the acid rain, at least in the 1.12.2 version.

**Comment by Tamaized** [comment]
Yes there are two areas where the rain exists, the Highlands and the Plateau, which are you referring to exactly. The Castle is on the Plateau, the trolls and giants are on the Highlands.
