### ISSUE TITLE
Advancement Problem

### ISSUE THREAD

**Issue by HydraHunterX09** [TeamTwilight/twilightforest#981]
Forge version: 1.12.2 - 14.23.5.2854
Twilight Forest version: 3.11.1021
Link to crash log: 

Problem: Silence Of The Forest advancement not working

What I expected to happen: Kill some wildlife like deer, hogs, bunnies, etc,  this way I could continue to the Naga.

What happened instead: Advancement just won't show up. Like anything I do won't let me get the advancement.

**Comment by Tamaized** [comment]
Does leaving and rejoining the world solve this?
