### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HappyBunny98765** [TeamTwilight/twilightforest#982]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:
Error message: Missing dependency with ID 'ae4b1574-be3e-4fac-b9b1-4699a2bb4f56' and version '1.0.2'.

**Comment by Tamaized** [comment]
Please actually follow the issue template
