### ISSUE TITLE
Maze/Ore Maps don't display at all

### ISSUE THREAD

**Issue by Andromander** [TeamTwilight/twilightforest#984]
Forge version: 35.0.15
Twilight Forest version: Yes

Steps to reproduce:
1. Observe an item implemented within the Minecraft modification known as Twilight Forest under the aliases of Magic Map, Maze Map, or Maze/Ore Map.

What I expected to happen:
Maps to work, I guess.

What happened instead:
There's nothing.

Yes, I'm intentionally filling this out as badly as I can. It's mainly a note to not forget this is a thing that's happening.

**Comment by Tamaized** [comment]
Magic Maps now display, need to come back to them for feature icons once structures are in
