### ISSUE TITLE
CTM for Moss patch doesn't work for some reason.

### ISSUE THREAD

**Issue by CaptainYoRw** [TeamTwilight/twilightforest#987]
Forge version: 
Twilight Forest version: (twilightforest-1.12.2-3.11.1021)

Steps to reproduce:
Install last version of CTM or any other
Install last version of Twilight Forest

What I expected to happen:
Textures should be connected between moss blocks.
What happened instead:
Moss are separated

Also: Tried without optifine, only with twilight forest and ctm, tried on different client, results all the same.
![image_2020-12-19_220503](https://user-images.githubusercontent.com/47063784/102697363-53712500-4246-11eb-8752-8a00c8b11e3d.png)

**Comment by Tamaized** [comment]
Iirc @Drullkus disabled it completely way back. I forget the exact reasoning, he can explain better.

**Comment by CaptainYoRw** [comment]
> Iirc @Drullkus disabled it completely way back. I forget the exact reasoning, he can explain better.
Thank you, I'm looking forward for his answer!

**Comment by Drullkus** [comment]
Fixed in 872d6384b491aaf74a7032073706a7d74a2d8ac0
