### ISSUE TITLE
Blockstates not working for Trollstein block. 

### ISSUE THREAD

**Issue by CaptainYoRw** [TeamTwilight/twilightforest#988]
Forge version:
Twilight Forest version: (twilightforest-1.12.2-3.11.1021)

Steps to reproduce:
Install last version of Twilight Forest for 1.12.2

What I expected to happen:
Texture of Trollstein block should become brighter under the sun.

![image](https://user-images.githubusercontent.com/47063784/102721177-49b0f580-430a-11eb-9e81-cc7c4727c9ac.png)

![image](https://user-images.githubusercontent.com/47063784/102721234-a6acab80-430a-11eb-902d-17231ce75412.png)

![image](https://user-images.githubusercontent.com/47063784/102721275-d491f000-430a-11eb-8303-f32e5aa4218a.png)

**Comment by bs2609** [comment]
This `World` check in `getActualState` is no good for rendering:
https://github.com/TeamTwilight/twilightforest/blob/87574e3df3b5e0ccf9e0b0d414e8a231a6bdb0e4/src/main/java/twilightforest/block/BlockTFTrollSteinn.java#L59

Probably not relevant in 1.16.x though.

**Comment by GizmoTheMoonPig** [comment]
works fine in 1.16 versions, so im closing this
