### ISSUE TITLE
Naga segments are not always attackable

### ISSUE THREAD

**Issue by Benimatic** [TeamTwilight/twilightforest#99]
Steps to reproduce:
1. Attack segments of the naga, particularly ones far from the head

What I expected to happen:
In previous versions you can attack the naga on any part of its body, particularly with arrows

What happened instead:
It seems like if the player is not in range to attack the head, the game engine ignores attacks on the body

Notes: How does the Ender Dragon manage this?

**Comment by williewillus** [comment]
I's like to move all the bosses off of vanilla's weird broken multiparts in the future but these will do for now

**Comment by Benimatic** [comment]
Yeah. I had a semi-working version of the naga with IEntityMultipart stripped out, but while working on it I hit on this solution.

It would be nice to have a working multipart system, but trying to just switch to separate entities without any framework at all just led to terrible jankiness while de/serializing, both over the network and on disk. 

The naga head needs a working reference to all the segments at all times, which need a reference back to the head.  If we had something for that, it would be easier. We're already using not-great solutions for the hydra (for the heads) and the lich (for the shadow clones.)
