### ISSUE TITLE
so... the new 1.16.3 version of the mod is not working bruh :/

### ISSUE THREAD

**Issue by controosoft** [TeamTwilight/twilightforest#990]
Forge version: 
Twilight Forest version: (this is the build number)
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:

**Comment by Drullkus** [comment]
Please actually use the issue template when reporting a problem, and provide crash log too please
