### ISSUE TITLE
Cubic Chunks compatibility issue.

### ISSUE THREAD

**Issue by border999** [TeamTwilight/twilightforest#991]
Forge version: 
Twilight Forest version: 1.12.2-3.11.1021-universal
Link to crash log: https://gist.github.com/border999/83774fc927bca5e80463ef59d74a1dbb

Steps to reproduce:
1.  Use a Cubic Chunks world type/ Possibly the hybrid worlds addon/ worldtype on.
2. Attempt to enter the Twilight Forest Dimension.

What I expected to happen:
Enter the Twilight Forest

What happened instead:
Crash

**Comment by Drullkus** [comment]
Support should dramatically be improved in newer versions
