### ISSUE TITLE
1.12.2 Bugs Conflicts with other mods

### ISSUE THREAD

**Issue by Alex6357** [TeamTwilight/twilightforest#994]
Forge version: 14.23.5.2854
Twilight Forest version: 1.12.2-3.9.984 (included) and later
Link to crash log: [gist](https://gist.github.com/Alex6357/c813f6a1712fd2cbb78d33e4e902779d)

Conflict with
    Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
    DLFMLCorePlugin (dynamiclights-1.12.2.jar)
    OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
    CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
    ForgelinPlugin (Shadowfacts Forgelin1.9.41.10.21.12.xForgelin-1.8.2.jar)
    LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
    LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)

Version below 3.9.984 can be loaded
Though 1.12.2 is an old version,really hope the bug can be fixed

**Comment by Tamaized** [comment]
Update Optifine

**Comment by Alex6357** [comment]
> 
> 
> Update Optifine
oh,thanks.I shouldnt have used a integration package
